### ISSUE TITLE
[BUG] FeatureFlagConfigurationSetting overrides all of value when updating property

### ISSUE THREAD

**Issue by mrm9084** [Azure/azure-sdk-for-java#34904] opened 2023-05-11 22:28 UTC
**Describe the bug**
When a set method is called such as `setClientFilters` it overrides anything that is stored in value that is not part of the standard Feature Flag object.

***Exception or Stack Trace***
N/A

**To Reproduce**
```java
FeatureFlagConfigurationSetting featureFlag = new FeatureFlagConfigurationSetting("Alpha", true);
featureFlag.setValue("{\"conditions\":{\"requirement_type\":\"All\"}}");
featureFlag.setClientFilters(filters);
```

When client filters is set it removes the conditions I set manually.

**Expected behavior**
The setting a value should override another part of the json object.

**Comment by jsquire** [comment] 2023-05-17 14:09
As discussed via internal email, this has been investigated and determined to be the intended behavior.  Closing this out.

**Closed** 2023-09-18 22:24 UTC
Labels: Client, App Configuration
