### ISSUE TITLE
Azure Blob - "BlobItem.getMetadata()" returns null but "BlobClient.getProperties().getMetadata()" returns correct value

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#20895] opened 2021-04-22 11:45 UTC
We are using `BlobContainerClient.listBlobsByHierarchy(..)`  to get list of blobs while iterating we realised that `BlobItem.getMetadata()` returns null but `BlobClient.getProperties().getMetadata()` returns correct value

**Prerequisite**
Create a blob which should have metadata 

***Code Snippet To Reproduce***
```
 public void getBlobMetadata() throws Exception {
        String containerName = "**-test";
        String directoryName = "**-test";

        BlobServiceClient blobServiceClient = new BlobServiceClientBuilder().endpoint(BLOB_SAS).buildClient();
        BlobContainerClient blobContainerClient = blobServiceClient.getBlobContainerClient(containerName);

        ListBlobsOptions listBlobOption = new ListBlobsOptions();
        listBlobOption.setMaxResultsPerPage(10);
        listBlobOption.setPrefix(directoryName);

        PagedIterable<BlobItem> pagedIterable = blobContainerClient.listBlobsByHierarchy(null, listBlobOption, null);
        Iterable<PagedResponse<BlobItem>> iterableByPage = pagedIterable.iterableByPage(10);

        Iterator<PagedResponse<BlobItem>> pagedResponseiterator = iterableByPage.iterator();
        while (pagedResponseiterator.hasNext()) {
            PagedResponse<BlobItem> pagedResponse = pagedResponseiterator.next();
            Iterator<BlobItem> pagedBlobItems = pagedResponse.getElements().iterator();
            while (pagedBlobItems.hasNext()) {
                BlobItem blobItem = pagedBlobItems.next();
                LOGGER.info("BlobItem - BlobName '{}', Metadata '{}'", blobItem.getName(), blobItem.getMetadata());

                BlobClient blobClient = blobContainerClient.getBlobClient(blobItem.getName());
                LOGGER.info("BlobClient - BlobName '{}', Metadata '{}'", blobItem.getName(), blobClient.getProperties().getMetadata());
            }
        }
    }
```

**Expected behavior**
`BlobItem.getMetadata()`  should return available metadatas

**Screenshots**
![image](https://user-images.githubusercontent.com/22897837/115708898-77fe1a80-a368-11eb-9b87-e97d9256333a.png)

**Setup (please complete the following information if applicable):**
OS: window
IDE : eclipse
Version of the Library used: `azure-storage-blob-12.10.2`

**Comment by abhikt48** [comment] 2021-04-22 12:11
I have one more query on top of above questions. Please find below details -

`BlobClient.getProperties()` returns `com.azure.storage.blob.models.BlobProperties`, but
`blobItem.getProperties()` returns   'com.azure.storage.blob.models.BlobItemProperties'

Both classes (`BlobProperties`, `BlobItemProperties`) have approximate same parameters but there are some inconsistent parameters, such as - `BlobProperties `have `expiresOn` property but `BlobItemProperties ` **does not** have `expiresOn`

Could you please suggest which one is correct Properties and we should be using which class going forward?

Please let me know for any queries.

**Comment by alzimmermsft** [comment] 2021-04-22 16:13
Hi @abhikt48, in the code sample you provided it appears that [setDetails](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/models/ListBlobsOptions.java#L42) isn't being configured to [retrieve metadata](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/models/BlobListDetails.java#L68). Without this configuration the listed `BlobItem` won't return metadata: https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs#response-body

> Snapshots, blob metadata, and uncommitted blobs are included in the response only if they are specified with the include parameter on the request URI.

**Comment by abhikt48** [comment] 2021-04-23 15:29
Hi @alzimmermsft, Thanks for quick update. I tested with your suggestion and able to retrieve metadata, but failed to retrieve tags. It is throwing **This request is not authorized to perform this operation using this permission.**
I checked permission of SAS key as well and I have provided all permissions. Please refer below screenshot.
I am not able to get tags with `BlobClient `as well.

Could you please suggest your opinion on below two issues - 
1. How can I get tags with `BlobItem `and `BlobClient` ? Please refer below sample code and errrorStacktrace.
2. What is the recommendation from your side to access Blob properties while listing blobs? Should we use BlobItem ` or `BlobClient` ? Please suggest.

**Source Code**
```
public void getBlobMetadata() throws Exception {
        String containerName = "***-test";
        String directoryName = "**test";
        
        BlobServiceClient blobServiceClient = new BlobServiceClientBuilder().endpoint(BLOB_SAS_SERVICE).buildClient();
        BlobContainerClient blobContainerClient = blobServiceClient.getBlobContainerClient(containerName);

        ListBlobsOptions listBlobOption = new ListBlobsOptions();
        listBlobOption.setMaxResultsPerPage(10);
        listBlobOption.setPrefix(directoryName);
        
        BlobListDetails blobListDetails = new BlobListDetails();
        blobListDetails.setRetrieveMetadata(true);
        blobListDetails.setRetrieveTags(true);
        blobListDetails.setRetrieveVersions(true);
        
        listBlobOption.setDetails(blobListDetails);

        PagedIterable<BlobItem> pagedIterable = blobContainerClient.listBlobsByHierarchy(null, listBlobOption, null);
        Iterable<PagedResponse<BlobItem>> iterableByPage = pagedIterable.iterableByPage(10);

        Iterator<PagedResponse<BlobItem>> pagedResponseiterator = iterableByPage.iterator();
        while (pagedResponseiterator.hasNext()) {
            PagedResponse<BlobItem> pagedResponse = pagedResponseiterator.next();
            Iterator<BlobItem> pagedBlobItems = pagedResponse.getElements().iterator();
            while (pagedBlobItems.hasNext()) {
                BlobItem blobItem = pagedBlobItems.next();
                LOGGER.info("BlobItem - BlobName '{}', Metadata '{}', tags '{}', versionID '{}'", blobItem.getName(), blobItem.getMetadata(), blobItem.getTags(), blobItem.getVersionId());

                BlobClient blobClient = blobContainerClient.getBlobClient(blobItem.getName());
                BlobProperties blobProperties = blobClient.getProperties();
                LOGGER.info("BlobClient - BlobName '{}', Metadata '{}', tags '{}', versionID '{}'", blobItem.getName(), blobProperties.getMetadata(), blobItem.getTags(), blobProperties.getVersionId());
            }
        }
    }
```
**Permission**
![image](https://user-images.githubusercontent.com/22897837/115892964-99860180-a44f-11eb-96e6-7fda355437f3.png)

**ERROR**
```
Exception in thread "main" com.azure.storage.blob.models.BlobStorageException: If you are using a StorageSharedKeyCredential, and the server returned an error message that says 'Signature did not match', you can compare the string to sign with the one generated by the SDK. To log the string to sign, pass in the context key value pair 'Azure-Storage-Log-String-To-Sign': true to the appropriate method call.
If you are using a SAS token, and the server returned an error message that says 'Signature did not match', you can compare the string to sign with the one generated by the SDK. To log the string to sign, pass in the context key value pair 'Azure-Storage-Log-String-To-Sign': true to the appropriate generateSas method call.
Please remember to disable 'Azure-Storage-Log-String-To-Sign' before going to production as this string can potentially contain PII.
Status code 403, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.
RequestId:***
Time:2021-04-23T15:15:03.7787690Z</Message></Error>"
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.azure.core.http.rest.RestProxy.instantiateUnexpectedException(RestProxy.java:337)
	at com.azure.core.http.rest.RestProxy.lambda$ensureExpectedStatus$5(RestProxy.java:378)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:320)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:337)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2344)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onSubscribe(MonoCacheTime.java:276)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:191)
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:132)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2344)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:103)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)
	at reactor.core.publisher.FluxDelaySubscription$DelaySubscriptionMainSubscriber.onNext(FluxDelaySubscription.java:180)
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onNext(FluxTimeout.java:173)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:171)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:252)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:144)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:144)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1783)
	at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:152)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:138)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:206)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:262)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:383)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:373)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:429)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:655)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1533)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1294)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1331)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Flux.blockLast(Flux.java:2497)
		at com.azure.core.util.paging.ContinuablePagedByIteratorBase.requestPage(ContinuablePagedByIteratorBase.java:94)
		at com.azure.core.util.paging.ContinuablePagedByPageIterable$ContinuablePagedByPageIterator.<init>(ContinuablePagedByPageIterable.java:49)
		at com.azure.core.util.paging.ContinuablePagedByPageIterable.iterator(ContinuablePagedByPageIterable.java:37)
		at com.blob.test.BlobListByPage.getBlobMetadata(BlobListByPage.java:106)
		at com.blob.test.BlobListByPage.main(BlobListByPage.java:125)

```

**Comment by abhikt48** [comment] 2021-04-23 16:33
@alzimmermsft  - One more input on top of above comment. There are two problems for selection between `BlobProperties `and `BlobItemProperties`. Please find below details 
1.  `BlobProperties `and `BlobItemProperties` are not consistent. Such as - `BlobItemProperties.contentLength` and `BlobProperties.blobSize`
2.  While listing I will get `BlobItem` in return, so I need to create specifically `BlobClient ` again which could be performance issue "blobContainerClient.getBlobClient(blobItem.getName());" 

Please suggest your recommendation, so i can implement same.

**Comment by gapra-msft** [comment] 2021-04-23 17:28
Hi @abhikt48 

For your permissions issue, could you share the sas token you are using (you can redact any blob related information and the signature part of it)?

I just ran your repro code with a SAS token from portal just as you showed and I was able to get the tags information.

**Comment by abhikt48** [comment] 2021-04-23 17:40
HI @gapra-msft 

Please find masked SAS -` https://***.blob.core.windows.net/?sv=2019-12-12&ss=b&srt=sco&sp=rw**cx&se=2021-10-31T21:53:13Z&st=2020-11-19T13:53:13Z&spr=https&sig=8xyC***9Ix**`

Please let me know for any other inputs.

**Comment by gapra-msft** [comment] 2021-04-23 17:41
@abhikt48  Can you un-redact the sp query parameter?

**Comment by gapra-msft** [comment] 2021-04-23 17:50
For reference, here is the sas token I got back from portal
https://XXXX.blob.core.windows.net/?sv=2020-02-10&ss=bfqt&srt=sco&**sp=rwdlacuptfx**&se=2021-04-28T01:22:02Z&st=2021-04-23T17:22:02Z&spr=https&sig=XXXXXXX

**Comment by abhikt48** [comment] 2021-04-23 18:39
@gapra-msft  Please find updated one -

`https://***.blob.core.windows.net/?sv=2019-12-12&ss=b&srt=sco&sp=rwdlacx&se=2021-10-31T21:53:13Z&st=2020-11-19T13:53:13Z&spr=https&sig=8xyC***9Ix**`

Another one - `https://***.blob.core.windows.net/?sv=2019-12-12&ss=b&srt=sco&sp=rwdlacupx&se=2021-10-31T21:53:13Z&st=2020-11-19T13:53:13Z&spr=https&sig=8xyC***9Ix**`

**Comment by gapra-msft** [comment] 2021-04-23 18:43
Hi @abhikt48 

I think the problem is Azure Portal has not yet been updated to support sas versions that allow you to specify tag permissions. Can you generate the sas using the SDK 

blobServiceClient.generateSas(<InsertSASOptions>)

The above API should allow you to create a SAS that supports tags permissions.

**Comment by abhikt48** [comment] 2021-04-26 10:43
HI @gapra-msft  - Thanks for providing details. Is it possible for you to raise internal request to generate latest SAS version in Azure Portal ?

Based on your suggestion - AccountName and AccountKey is manadatory for generating SAS.  We are using SAS only in most applications, so we can't enforce user to use AccountName and AccountKey instead of SAS. This will be a huge change for us.
```
StorageSharedKeyCredential credential = new StorageSharedKeyCredential("accountName", "accountKey");
BlobServiceClientBuilder blobServiceClient = new BlobServiceClientBuilder().credential(credential);
// Client must be authenticated via StorageSharedKeyCredential
String sas = blobServiceClient.generateAccountSas(sasValues);
```

Could you please suggest **your recommendation on below query**? We have to take decision based on your suggestion.

![image](https://user-images.githubusercontent.com/22897837/116070366-709a8200-a684-11eb-8bf4-b29bc582aa08.png)

**Comment by gapra-msft** [comment] 2021-04-26 17:32
Hi @abhikt48 

For 1. blobSize and contentLength are the same thing, I believe we chose blobSize for getBlobProperties since it is more idiomatic for users. 
2. Could you please clarify what you mean by this question?

**Comment by abhikt48** [comment] 2021-04-26 21:57
Hi @gapra-msft , Thanks for quick reply. Please find below details - 

Our developed component using various download and list operations. While 

1) downloading - we are getting `BlobClient` and `BlobClient.getProperties()` returns `com.azure.storage.blob.models.BlobProperties`
2) Listing - We are getting `BlobItem`, and `blobItem.getProperties()` returns   `com.azure.storage.blob.models.BlobItemProperties`

Eventually both classes (`BlobProperties`, `BlobItemProperties`) returns blob properties, but both classes **does not have exact property**. We want to maintain consistent over all operations. So we would like to have same properties over both operations.

While listing I get `BlobItem`, I can new `BlobClient` with blob name which could be a performance issue.

Could you please suggest your recommendation - Which class we should to use for accessing Blob properties?

Please find below property differences -

1. `BlobProperties`have `expiresOn` property but `BlobItemProperties ` **does not** have `expiresOn`
2. `BlobProperties`have `copyDestinationSnapshot` property but `BlobItemProperties ` **does not** have `copyDestinationSnapshot`
3. `BlobProperties`have `encryptionKeySha256` property but `BlobItemProperties ` **does not** have `encryptionKeySha256`
4. `BlobProperties`have `committedBlockCount` property but `BlobItemProperties ` **does not** have `committedBlockCount`
5. `BlobProperties`have `isCurrentVersion` property but `BlobItemProperties ` **does not** have `isCurrentVersion`
6. `BlobProperties`have `objectReplicationDestinationPolicyId` property but `BlobItemProperties ` **does not** have `objectReplicationDestinationPolicyId`

7. `BlobItemProperties`have `destinationSnapshot` property but `BlobProperties ` **does not** have `destinationSnapshot`
8. `BlobItemProperties`have `deletedTime` property but `BlobProperties ` **does not** have `deletedTime`
9. `BlobItemProperties`have `remainingRetentionDays` property but `BlobProperties ` **does not** have `remainingRetentionDays`
10. `BlobItemProperties`have `customerProvidedKeySha256` property but `BlobProperties ` **does not** have `customerProvidedKeySha256`

11. ` BlobItem`have `snapshot` property but ` BlobClient` **does not** have `snapshot`


Please let me know for any queries.

**Comment by gapra-msft** [comment] 2021-04-28 17:32
Hi @abhikt48 
Thanks for clarifying. I am going to check with other platforms to see how they expose these variables and will get back to you.

**Comment by abhikt48** [comment] 2021-05-05 09:26
HI @gapra-msft  - Could you please update on this isuue ?

**Comment by gapra-msft** [comment] 2021-05-05 20:26
Hi @abhikt48 

I spoke with my team. We will take a second look at the properties returned by listBlobs/getProperties and ensure they align with all the service supported properties.

**Comment by gapra-msft** [comment] 2021-05-06 22:23
Hi @abhikt48 

It looks like there are a few naming convention mismatches here. I'll cover all your concerns one by one below

> BlobPropertieshave expiresOn property but BlobItemProperties does not have expiresOn

The listBlobs API does not support expiresOn according to the REST [docs](https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs#response-body).

> BlobPropertieshave copyDestinationSnapshot property but BlobItemProperties does not have copyDestinationSnapshot

The listBlobs API does not support copyDestinationSnapshot according to the REST [docs](https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs#response-body).

> BlobPropertieshave encryptionKeySha256 property but BlobItemProperties does not have encryptionKeySha256

BlobProperties.encryptionKeySha256=BlobItemProperties.customerProvidedKeySha256. There is just a naming mismatch here.

> BlobPropertieshave committedBlockCount property but BlobItemProperties does not have committedBlockCount

The listBlobs API does not support commitedBlockCount according to the REST [docs](https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs#response-body).

> BlobPropertieshave isCurrentVersion property but BlobItemProperties does not have isCurrentVersion

BlobProperties.isCurrentVersion = **BlobItem**.isCurrentVersion. This property is one level up in the hierarchy

> BlobPropertieshave objectReplicationDestinationPolicyId property but BlobItemProperties does not have objectReplicationDestinationPolicyId

The listBlobs API does not support objectReplicationDestinationPolicyId according to the REST [docs](https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs#response-body).

> BlobItemPropertieshave destinationSnapshot property but BlobProperties does not have destinationSnapshot

This is BlobProperties.copyDestinationSnapshot

> BlobItemPropertieshave deletedTime property but BlobProperties does not have deletedTime

The getProperties API does not support deletedTime according to the REST [docs](https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob-properties#response-headers).

> BlobItemPropertieshave remainingRetentionDays property but BlobProperties does not have remainingRetentionDays

The getProperties API does not support remainingRetentionDays  according to the REST [docs](https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob-properties#response-headers).

> BlobItemPropertieshave customerProvidedKeySha256 property but BlobProperties does not have customerProvidedKeySha256

BlobProperties.encryptionKeySha256=BlobItemProperties.customerProvidedKeySha256. There is just a naming mismatch here.

> BlobItemhave snapshot property but BlobClient does not have snapshot

You can call BlobClient.getSnapshotId to get the snapshot of a BlobClient. 


Hope this helps!

**Comment by abhikt48** [comment] 2021-05-16 07:55
@gapra-msft  Thanks for feedback. 

Can you please consider feature request to match same name in both objects?

As list api doesn’t return some properties, so we can ignore other properties.

please suggest.

**Comment by gapra-msft** [comment] 2021-05-18 18:29
Hi @abhikt48 

As a design principle, the SDK errs on the side of following the naming convention of the service, so we would not be able to change the name unless the service decides to resolve the naming issue. 

I will go ahead and raise this issue to the service's attention, so they can move forward appropriately.

Generally we don't track service issues on this repo so if I've answered all your questions, please feel free to close the issue.

Thanks for the feedback!

**Closed** 2021-05-19 08:27 UTC
Labels: Client, Storage, customer-reported, needs-team-attention

**Comment by gapra-msft** [comment] 2021-05-27 18:33
Hi @abhikt48 I've created an issue tracking this (it isn't publicly visible but I noted this issue number so whoever picks this item up can update you)
