### ISSUE TITLE
[BUG] Schema inference gives a blank string value for json object in cosmos container

### ISSUE THREAD

**Issue by jenilChristo** [Azure/azure-sdk-for-java#29181] opened 2022-06-02 03:54 UTC
**Describe the bug**
The schemaInference reads the json object in a cosmos container as a blank string. This causes a data loss while using the connector. When a customSchema is passed to `spark.read.schema(customSchema)` with struct types, the data is been read as expected.

**To Reproduce**
- Reading from a cosmos container having ~2k documents
- schema `{
    "id":"test",
    "child":{
        "id":"testid",
        "number": "testnumber"
    },
    "element2": Array[Objects],
    "element3": Array[Objects]
}`
- Read configuration for inferSchema

``"spark.cosmos.read.inferSchema.enabled" -> "TRUE",
"spark.cosmos.read.inferSchema.query" -> "select * from c",
"spark.cosmos.read.inferSchema.samplingSize" -> "2000",
"spark.cosmos.read.inferSchema.includeSystemProperties" -> "FALSE",
"spark.cosmos.read.inferSchema.includeTimestamp" ->"FALSE",
"spark.cosmos.read.schemaConversionMode" -> "Relaxed",
"spark.cosmos.read.partitioning.strategy" -> "Default"``

- The child property is expected as a valid json in dataframe, however it shows as a blank string

***Code Snippet***
```spark.read.format("com.azure.cosmos.spark.CosmosItemsDataSource").options(config).load()```

**Expected behavior**
When reading using the schemaInference, the connector should output the json object as a valid struct column in the dataframe instead of giving blank string values.

**Setup (please complete the following information):**
 - Running `azure-cosmos-spark_3-1_2-12` (version 4.0.0) on databricks 
 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by FabianMeiswinkel** [comment] 2022-06-02 09:01
Hi jenil,
I looked at this work item, but unfortunately, I did not quite get what is happening. Schema inference in Spark will try to map the json documents into a relational schema (which can include Structs/Arrays - but Structs have to be well defined - there is no notion of a generic Json object like JsonNode in Java etc.)
The way it works in the Cosmos DB connector is that when you have an array[object] we look at the objects and build a schema with a superset of properties - so, if array[0] has an object { "property1", "Test" } and array[1] { "property2": "Test" } the resulting schema would be an array of struct with property1:String and property2: String.
That said, schema inference also only looks at a certain sample set of documents (1000 random documents by default, can be changed) - so only properties that exist in any of the 1000 documents would be reflected in the inferred schema.

**I have a few questions regarding the work item that you created:**
- What schema is inferred (if df is the Dataframe you read like above - what is the df.printSchema output)?
- When you say the child property shows as blank string - is this happening for all documents or only the row where the document doesn't even contain a child-property?
- Are you able to share a few (can be anonymized so that they don't have privacy related info in them) documents - ideally enough that I can use them to reproduce what you are seeing after ingesting them into one of my containers? If you don't want to share them at github feel free to send them to me via mail - fabianm[at]microsoft.com
- Are you aware that you can also provide your own manually created schema instead of using schema inference?
- Are the documents of very different structure - so that the fact that only 1000 random documents are used for schema inference would be relevant in your case? If so, there is a way to specify a query that is used to pick the documents for schema inference - for example to force only reading documents with certain filters or only reading the most recently modified documents etc.
- Which exact version of the Spark connector are you using? The latest version is 4.10.1 (can be retrieved from maven via https://repo1.maven.org/maven2/com/azure/cosmos/spark/azure-cosmos-spark_3-1_2-12/4.10.1/azure-cosmos-spark_3-1_2-12-4.10.1.jar) - assuming you are using an older version - are you able to check whether the issue still reproduces at the latest version?

**Comment by jenilChristo** [comment] 2022-06-02 14:33
@FabianMeiswinkel  Thanks for your quick response. The issue is seen in version `4.0.0`  and cannot be reproduced in latest version `4.10.1`

1)What schema is inferred (if df is the Dataframe you read like above - what is the df.printSchema output)?
Output
```
 |-- id: string (nullable = false)
 |-- child: string (nullable = false)
 |-- result: boolean (nullable = false)
 |-- element2: array (nullable = false)
 |    |-- element: struct (containsNull = true)
 |    |    |-- prop1: struct (nullable = false)
 |    |    |-- prop2: boolean (nullable = false)
 |-- element3: array (nullable = false)
 |    |-- element: struct (containsNull = true)
 |    |    |-- prop1: struct (nullable = false)
 |    |    |-- prop2: boolean (nullable = false)
```
 
 Expected
```
 |-- id: string (nullable = false)
 |-- child: struct (containsNull = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- id: string (nullable = false)
 |    |    |-- number: string (nullable = false)
 |-- result: boolean (nullable = false)
 |-- element2: array (nullable = false)
 |    |-- element: struct (containsNull = true)
 |    |    |-- prop1: struct (nullable = false)
 |    |    |-- prop2: boolean (nullable = false)
 |-- element3: array (nullable = false)
 |    |-- element: struct (containsNull = true)
 |    |    |-- prop1: struct (nullable = false)
 |    |    |-- prop2: boolean (nullable = false)
```
2) When you say the child property shows as blank string - is this happening for all documents or only the row where the document doesn't even contain a child-property?

All elements.

3) Are you able to share a few (can be anonymized so that they don't have privacy related info in them) documents - ideally enough that I can use them to reproduce what you are seeing after ingesting them into one of my containers? If you don't want to share them at github feel free to send them to me via mail - fabianm[at]microsoft.com

Yes, the issue is reproduced with version 4.0.0, However this is not happening with latest version 4.10.1. I can share via mail if you still need to have a look.

4) Are you aware that you can also provide your own manually created schema instead of using schema inference?

Yes, The issue is not reproducible if we pass the custom schema (even with version 4.0.0)

5) Are the documents of very different structure - so that the fact that only 1000 random documents are used for schema inference would be relevant in your case? If so, there is a way to specify a query that is used to pick the documents for schema inference - for example to force only reading documents with certain filters or only reading the most recently modified documents etc.

No all the documents has the same schema.

6) Which exact version of the Spark connector are you using? The latest version is 4.10.1 (can be retrieved from maven via https://repo1.maven.org/maven2/com/azure/cosmos/spark/azure-cosmos-spark_3-1_2-12/4.10.1/azure-cosmos-spark_3-1_2-12-4.10.1.jar) - assuming you are using an older version - are you able to check whether the issue still reproduces at the latest version?

  We were using version 4.0.0. Tested with latest version 4.10.1 and unable to reproduce the issue. It works as expected.

**Comment by FabianMeiswinkel** [comment] 2022-06-02 14:50
Thanks for the confirmation - yes, there have been several critical improvements made - also in this area - since 4.0.0. So, I am going to close this ticket. For reference - the change log for the different versions is here: https://aka.ms/azure-cosmos-spark-3-1-changelog

In general, my recommendation would be to snap to the latest version regularly - like at least every few months. And the change log can be used to determine how significant changes are for your workload.

**Closed by FabianMeiswinkel** 2022-06-02 14:50 UTC
Labels: question, customer-reported, needs-triage
