### ISSUE TITLE
[BUG] cosmos:v4-item queries with group by clause not returning more than one page.

### ISSUE THREAD

**Issue by balakathiresh-impiger** [Azure/azure-sdk-for-java#12910] opened 2020-07-08 15:21 UTC
When passing a query with "group by' clause, the "iterableByPage()" method in "Iterable" object is not returning more than one page even though there are more number of items than the specified page size.
Also the "getContinuationToken()" on the "FeedResponse" object returns null.

***Code Snippet***
int currentPageNumber=0;
String query = "select count(1), s.programId from ScheduleSlots s group by s.programId";
CosmosQueryRequestOptions queryOptions = new CosmosQueryRequestOptions();
queryOptions.setPartitionKey(new PartitionKey("1"));

Iterable<FeedResponse<JsonNode>> feedResponseIterator =
                    container.queryItems(query, queryOptions, JsonNode.class).iterableByPage(continuationToken,100);

for (FeedResponse<JsonNode> page : feedResponseIterator) {
                logger.info(String.format("Current page number: %d", currentPageNumber));
}
*****

Total number items returned while executing the above query in the portal: 300+

**Expected behavior**
I expected to see log for four page numbers

Note this snippet of code works as expected for other queries without group by clause.

**Comment by balakathiresh-impiger** [comment] 2020-07-13 09:51
@joshfree is this bug being worked upon? 
We would like to start using sdk v4.
But this bug is stopping us from using v4.

**Comment by kushagraThapar** [comment] 2020-07-21 23:16
@balakathiresh-impiger I just got notified about this issue, let me investigate this.

**Comment by balakathiresh-impiger** [comment] 2020-07-22 08:15
@kushagraThapar thanks for the update. eagerly waiting for the fix

**Comment by kushagraThapar** [comment] 2020-07-29 19:17
@balakathiresh-impiger - 
```
Also the "getContinuationToken()" on the "FeedResponse" object returns null.
```

The issue here is that we do not support continuation tokens for GROUP BY queries. The client currently will send by empty pages until it drains all pages from the BE, since it is not allowed to return a single grouping until it has seen all the groupings.
 
We don’t support continuation tokens, since the state would be too large to fit in a string that many try to insert into headers.

In the future we will support ORDER BY + GROUP BY, which will keep the size of the continuation token bounded

As a workaround, please do not use continuation tokens on group by query, and as for the pageSize - the SDK will return number of documents what you specify in pageSize. So for now, please use a large enough pageSize that supports your case. 

You should use portal as a starting point and then tweak your queries in the application code for this specific case.

**Comment by kushagraThapar** [comment] 2020-07-29 19:24
@balakathiresh-impiger  - meanwhile, I will debug this into more detail if I can reproduce this issue without continuation token and with a limited pageSize.

**Comment by kushagraThapar** [comment] 2020-07-31 02:20
@balakathiresh-impiger  - we found out the issue and will have a fix out soon, thanks!

**Comment by balakathiresh-impiger** [comment] 2020-07-31 13:39
@kushagraThapar thanks for the update. eagerly waiting for the fix

**Comment by kushagraThapar** [comment] 2020-08-10 19:03
This is done, and will be released in next azure-cosmos release by the end of this week.

**Closed by kushagraThapar** 2020-08-10 19:03 UTC
Labels: Client, Cosmos, Service Attention, bug, cosmos:v4-item, customer-reported
