### ISSUE TITLE
[BUG] SAS tokens that start with '?' cause requests to storage to fail

### ISSUE THREAD

**Issue by SukruthKS** [Azure/azure-sdk-for-java#6578] opened 2019-11-27 08:26 UTC
**Describe the bug**
If SAS token begins with '?' (like when copied from Azure Portal), it fails with the below error:

```
com.azure.storage.blob.models.BlobStorageException: 
Status code 403, 
<?xml version="1.0" encoding="utf-8"?>
  <Error>
      <Code>AuthenticationFailed</Code>
      <Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId: redacted Time: redacted</Message> . 
      <AuthenticationErrorDetail>sr is mandatory. Cannot be empty</AuthenticationErrorDetail>
  </Error>
```
***Exception or Stack Trace***
Added above

**To Reproduce**
Add an existing storage account name in the endpoint below and should be able to reproduce the issue:
```
String endpoint = "https://<storage_account>.blob.core.windows.net/";
BlobServiceClient client = new BlobServiceClientBuilder()
    .endpoint(endpoint)
    .sasToken("?sv=2019-02-02&ss=bf&srt=sco&sp=rla&se=2019-11-27T16:03:21Z&st=2019-11-27T08:03:21Z&spr=https&sig=NZX%2FZH7GFSPgmb7j62GldqDEW%2BINoFKlAC4euoxM1Xc%3D")
    .buildClient();

BlobServiceProperties properties = client.getProperties();
```

***Code Snippet***
Added above

**Expected behavior**
SDK should be able to handle both scenarios - a SAS token that begins with '?' and one that does not.

**Screenshots**
NA

**Setup (please complete the following information):**
 - OS: Linux
 - IDE : IntelliJ
 - Version of the Library used: 12.0.0

**Additional context**
NA

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by SukruthKS** [comment] 2019-11-27 08:31
Just found that this issue was already reported [#6193](https://github.com/Azure/azure-sdk-for-java/issues/6193) and a fix for it was committed. However, I'm still seeing this issue. Perhaps the fix is not released yet. If that's the case, please feel free to close this.

**Comment by gapra-msft** [comment] 2019-11-27 15:26
Hi @SukruthKS,
It seems like you are encountering the issue reported here https://github.com/Azure/azure-sdk-for-java/issues/6542. We are aware of the problem and are currently working on a fix for it.

**Comment by gapra-msft** [comment] 2019-11-27 18:53
@SukruthKS, I tried reproducing your error and I don't get an error when I reproduce it exactly. However when I do this I get the failure you see 

```
String endpoint = "https://<storage_account>.blob.core.windows.net/?sv=2019-02-02&ss=bf&srt=sco&sp=rla&se=2019-11-27T16:03:21Z&st=2019-11-27T08:03:21Z&spr=https&sig=NZX%2FZH7GFSPgmb7j62GldqDEW%2BINoFKlAC4euoxM1Xc%3D";
BlobServiceClient client = new BlobServiceClientBuilder()
    .endpoint(endpoint)
    .buildClient();

BlobServiceProperties properties = client.getProperties();
```

Does your code match this or is it more like your code snippet where you set the endpoint and sasToken separately?

**Comment by SukruthKS** [comment] 2019-11-27 19:07
Can you try with this exact code snippet (including the same SAS token and endpoint) and see if you get that error? I'm assuming you are also using version `12.0.0`.

```
String endpoint = "https://images.blob.core.windows.net/";
BlobServiceClient client = new BlobServiceClientBuilder()
    .endpoint(endpoint)
    .sasToken("?sv=2019-02-02&ss=bf&srt=sco&sp=rla&se=2019-11-27T16:03:21Z&st=2019-11-27T08:03:21Z&spr=https&sig=NZX%2FZH7GFSPgmb7j62GldqDEW%2BINoFKlAC4euoxM1Xc%3D")
    .buildClient();

BlobServiceProperties properties = client.getProperties();
```

**Comment by gapra-msft** [comment] 2019-11-27 19:39
Hi @SukruthKS, you're right. I wasn't testing with 12.0.0 so that's probably why I wasn't seeing the issue.

As you pointed out a fix for the issue you mentioned was committed so it will be in our next release. 

I'll go ahead and close this issue since you should be resolved by our next release.

**Closed by gapra-msft** 2019-11-27 19:39 UTC
Labels: Client, Storage, customer-reported
