### ISSUE TITLE
[Azure Blob Storage SDK] Client classes marked as final - making them unable to mock

### ISSUE THREAD

**Issue by Silvatre** [Azure/azure-sdk-for-java#5051] opened 2019-08-20 11:02 UTC
Hi,

Most (if not all) of the Azure Blob Storage SDK clients are marked as final, making it not possible (or overcomplicated) to write the tests with mocked client layer (e.g. with Mockito) - which seems to be a common use case.

**Version**
```
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-storage-blob</artifactId>
    <version>12.0.0-preview.2</version>
</dependency>
```

 
 **Solution**
Make the client classes non-final or provide client interfaces.

**Comment by rickle-msft** [comment] 2019-08-21 00:13
@Silvatre. Thank you for bringing this to our attention. 

@JonathanGiles Can you please give us some guidance for how to support mocking scenarios and still be within Azure SDK guidelines?

**Comment by alzimmermsft** [comment] 2019-08-21 00:26
@Silvatre #5017 has discussions and potential solutions for mocking. It is missing direct mention for mocking final class and clients, I will work with @srnagar to add recommendations for those cases.

**Comment by alzimmermsft** [comment] 2019-09-17 23:28
@Silvatre, did the linked issue have enough documentation to help alleviate the classes being marked as final issue?

**Comment by alzimmermsft** [comment] 2019-09-24 01:38
Removing the `Storage` label as this is an issue that spans across our SDK offerings.

**Comment by joshfree** [comment] 2019-10-17 23:48
Resolving as a duplicate of #5017 

@Silvatre please feel free to add more comments or reactivate if needed; otherwise we will use #5017 to continue to track mocking support

**Closed by joshfree** 2019-10-17 23:48 UTC
Labels: Azure.Core, Client, customer-reported
