### ISSUE TITLE
[BUG] Extremely slow downloads on BlobClientBase::download(OutputStream) in unit tests

### ISSUE THREAD

**Issue by jaschrep-msft** [Azure/azure-sdk-for-java#6015] opened 2019-10-23 20:51 UTC
**Describe the bug**
In unit tests, BlobClientBase::download(OutputStream) runs extremely slowly, taking up to three minutes for a 256MB file. In release builds, this process takes 10-15 seconds.

***Exception or Stack Trace***
N/A

**To Reproduce**
Write a test similar to the followiong in blob service unit tests:
```groovy
def "Download test"() {
    setup:
    blobac = new BlobClientBuilder().pipeline(blobac.getHttpPipeline()).endpoint("https://xclientdev3.blob.core.windows.net/perftest/4a3ff883-0822-452b-b052-3ee713a497898451525172718223843.txt").buildAsyncClient()

    def start = System.currentTimeMillis()

    blobac.download().then().block()

    def end = System.currentTimeMillis()
    System.out.println(end - start)
}
```

***Code Snippet***
Unknown

**Expected behavior**
A similar runtime to normal builds.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : IntelliJ
 - Version: 12.0.0-preview.4 (additionally, master as of commit 126f19539f0d232ff1d6ce57bb1b34329f069324)

**Additional context**
None

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by alzimmermsft** [comment] 2022-03-14 12:55
There is a possibility that an exception happened during download resulting in a retry with back-off happening. Does this still occur as there has been a lot of work to harden network failures in the SDKs since this was written.

**Comment by alzimmermsft** [comment] 2022-05-03 16:22
Closing this as there are performance tests which use `download(OutputStream)`, so if there is a significant regression it'll be caught and a newer tracking issue can be opened if that occurs.

**Closed by alzimmermsft** 2022-05-03 16:22 UTC
Labels: Storage, Client, needs-team-attention
