### ISSUE TITLE
[QUERY] Disable Cosmos datasource auto configuration with Test Profile 

### ISSUE THREAD

**Issue by rharish1983** [Azure/azure-sdk-for-java#32588] opened 2022-12-13 19:01 UTC
**Query/Question**
We are having a SpringBoot app(Springboot version 2.6.6). App is connecting to CosmosDB at startup using the spring-cloud-azure-starter-data-cosmos artifact. Connection properties are defined in the application.properties. Is there anyway we can disable the Cosmos datasource autoconfiguration with the Test Profile ? 

***Why is this not a Bug or a feature Request?***
This is a question related to usage of the libraries as opposed to a feature / bug request. 

**Setup (please complete the following information if applicable):**
 - OS: iOS
 - IDE: STS, IntelliJ
 - Library/Libraries: com.azure:azure-spring-data-cosmos:3.20.0, com.azure.spring:spring-cloud-azure-starter-data-cosmos:4.1.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by chenrujun** [comment] 2022-12-14 02:54
Hi, @rharish1983 
Thanks for reaching out.

To disable Cosmos datasource autoconfiguration, you can use property `spring.cloud.azure.cosmos.enabled=false`. And you can load property file based on spring profiles.
Refs:
1. https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configuration-properties-azure-cosmos-db
2. https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure_4.5.0/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/data/cosmos/CosmosDataAutoConfiguration.java#L26
3. [How to load property file based on spring profiles](https://stackoverflow.com/questions/41263105/how-to-load-property-file-based-on-spring-profiles)

**Comment by jpmani11** [comment] 2022-12-14 15:44
@chenrujun Myself @jpmani11 running into same issue. Thanks for your couple of Refs. I have tried one from those in application-test.yml file,
spring:
    cloud:
        azure:
            cosmos:
                enabled: false
now cosmos bean related issues went away while doing mvn clean install. but application specific exceptions are coming up. we are using CosmosReactiveRepository for DB operations. So we are seeing below errors,
**********************************
APPLICATION FAILED TO START
**********************************
**Description:**
Parameter 0 of method *********************  in DaoService required a bean of type '*************CosmosReactiveRepository' that could not be found.

**Action:**
Consider defining a bean of type '*************CosmosReactiveRepository' in your configuration.

**ERROR** [main] o.s.test.context.TestContextManager      : Caught exception while allowing TestExecutionListener [org.springframework.test.context.web.ServletTestExecutionListener@72c927f1] to prepare test instance [ApplicationTests@47a05ad8]
java.lang.IllegalStateException: Failed to load ApplicationContext

In order to avoid "Failed to load ApplicationContext" error, I have commented @Test like below in ApplicationTests class  then all errors are went away when doing mvn build and server start up.
@ActiveProfiles({ "test" })
@SpringBootTest
class ApplicationTests {
	**//@Test**
	void contextLoads() {
	}
}
but please share your thought on this whether is that correct way? If this is wrong please suggest some other idea to handle CosmosReactiveRepository errors.

**Comment by chenrujun** [comment] 2022-12-15 02:03
@jpmani11 

Maybe this can help you: https://stackoverflow.com/questions/43851621/is-it-possible-to-mark-springboot-tests-so-they-run-only-when-certain-profile-is

**Comment by MapFilterMagic** [comment] 2022-12-22 16:25
> @jpmani11
> 
> Maybe this can help you: https://stackoverflow.com/questions/43851621/is-it-possible-to-mark-springboot-tests-so-they-run-only-when-certain-profile-is

Hi. Following up on this. Our issue is not with our profile setup. We have successfully defined test profile behavior in several of our other applications, and the test profile is, in-fact, running as we expect in this case. We have found 2 potential solutions:

- `@DataJpaTest`
- `@AutoConfigureTestDatabase`

Sticking either of these annotations on top of our main test class resolves the Cosmos errors and effectively stops any attempt for Cosmos to autoconfigure itself and reach out to the DB. We are currently investigating what exactly these do, why these work, and why all previous suggestions/attempts did not work for us. (`@AutoConfigureTestDatabase` is on `@DataJpaTest` itself) 

Any insight from your guy's end would be appreciated.

**Comment by MapFilterMagic** [comment] 2022-12-22 16:39
> @jpmani11
> 
> Maybe this can help you: https://stackoverflow.com/questions/43851621/is-it-possible-to-mark-springboot-tests-so-they-run-only-when-certain-profile-is

Hi. Following up on this. Our issue is not with our profile setup. We have successfully defined test profile behavior in several of our other applications, and the test profile is, in-fact, running as we expect in this case.

**Comment by saragluna** [comment] 2022-12-23 03:48
Why does the `DaoService` require a `*************CosmosReactiveRepository`?
`

**Comment by MapFilterMagic** [comment] 2022-12-23 15:35
> Why does the `DaoService` require a `*************CosmosReactiveRepository`?

Our DaoService layer invokes the methods in the CosmosReactiveRepository to query our DB

**Comment by chenrujun** [comment] 2022-12-26 01:47
Hi @MapFilterMagic 

1. If you set `spring.cloud.azure.cosmos.enabled=false`, then the `*****CosmosReactiveRepository` not exist, it will have error like `a bean of type '*************CosmosReactiveRepository' that could not be found.`
2. If you set `spring.cloud.azure.cosmos.enabled=true`, the `*************CosmosReactiveRepository` bean will be provided.

What's your expected behavior? Do you want a `*************CosmosReactiveRepository` bean that is used for test only? Do you want a mock `*************CosmosReactiveRepository` bean?

**Comment by MapFilterMagic** [comment] 2023-01-04 15:19
> Hi @MapFilterMagic
> 
> 1. If you set `spring.cloud.azure.cosmos.enabled=false`, then the `*****CosmosReactiveRepository` not exist, it will have error like `a bean of type '*************CosmosReactiveRepository' that could not be found.`
> 2. If you set `spring.cloud.azure.cosmos.enabled=true`, the `*************CosmosReactiveRepository` bean will be provided.
> 
> What's your expected behavior? Do you want a `*************CosmosReactiveRepository` bean that is used for test only? Do you want a mock `*************CosmosReactiveRepository` bean?

Hi. Apologies on the late reply--a bunch of us have been on holiday.

We ended up having to provide a concrete dummy implementation of `***CosmosReactiveRepository` that overrides all methods to return garbage. For the purpose of unit testing, we end up stubbing responses anyway, so these returning nothing don't i.e.

```
public class ***CosmosReactiveRepositoryImpl implements ***CosmosReactiveRepository {
    @Override
    public Mono<***Entity> findById(String id, PartitionKey partitionKey) {
        return Mono.empty();
    }

    @Override
    public Mono<Void> deleteById(String id, PartitionKey partitionKey) {
        return Mono.empty();
    }
...
```

And then we return this implementation (`new  ***CosmosReactiveRepositoryImpl()`) when `@ConditionalOnMissingBean(***CosmosReactiveRepository.class)` and import this test configuration in our main test class.

With azure auto config turned off and this concrete implementation/setup, we can now run our unit test tests without being forced to connect to our cosmos DB instance.

We appreciate the insight.  Thanks!

**Comment by chenrujun** [comment] 2023-01-05 01:47
@MapFilterMagic 

Thanks for your feedback! Closing this issue because problem solved.

**Closed by chenrujun** 2023-01-05 01:47 UTC
Labels: question, Client, customer-reported, needs-author-feedback, azure-spring
