### ISSUE TITLE
[BUG]azure-spring-boot-starter-cosmosdb server start error. java.lang.NoSuchMethodError: io.micrometer.core.instrument.Timer.start()

### ISSUE THREAD

**Issue by Abhisar** [Azure/azure-sdk-for-java#13804] opened 2020-08-05 05:32 UTC
**Describe the bug**
Spring boot server throws error while starting up 
java.lang.NoSuchMethodError: io.micrometer.core.instrument.Timer.start()
java.lang.NoSuchMethodError: io.micrometer.core.instrument.Timer.start()Lio/micrometer/core/instrument/Timer$Sample;
        at com.azure.data.cosmos.internal.directconnectivity.rntbd.RntbdRequestArgs.<init>(RntbdRequestArgs.java:49)

***Exception or Stack Trace***
Add the exception log and stack trace if available

2020-08-05 09:52:37.777 [reactor-http-nio-2] WARN  i.n.c.AbstractChannelHandlerContext - An exception '{}' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.NoSuchMethodError: io.micrometer.core.instrument.Timer.start()Lio/micrometer/core/instrument/Timer$Sample;
        at com.azure.data.cosmos.internal.directconnectivity.rntbd.RntbdRequestArgs.<init>(RntbdRequestArgs.java:49)
        at com.azure.data.cosmos.internal.directconnectivity.RntbdTransportClient.invokeStoreAsync(RntbdTransportClient.java:117)
        at com.azure.data.cosmos.internal.directconnectivity.TransportClient.invokeResourceOperationAsync(TransportClient.java:15)
        at com.azure.data.cosmos.internal.directconnectivity.StoreReader.readFromStoreAsync(StoreReader.java:623)
        at com.azure.data.cosmos.internal.directconnectivity.StoreReader.readFromReplicas(StoreReader.java:213)
        at com.azure.data.cosmos.internal.directconnectivity.StoreReader.lambda$readMultipleReplicasInternalAsync$10(StoreReader.java:391)
        at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:46)
        at reactor.core.publisher.FluxRepeatPredicate$RepeatPredicateSubscriber.resubscribe(FluxRepeatPredicate.java:113)
        at reactor.core.publisher.FluxRepeatPredicate.subscribeOrReturn(FluxRepeatPredicate.java:49)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4203)
        at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:207)
        at reactor.core.publisher.FluxConcatArray.subscribe(FluxConcatArray.java:80)
        at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54)
        at reactor.core.publisher.Flux.subscribe(Flux.java:8325)
        at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:75)
        at reactor.core.publisher.Operators.complete(Operators.java:135)
        at reactor.core.publisher.FluxEmpty.subscribe(FluxEmpty.java:41)
        at reactor.core.publisher.Flux.subscribe(Flux.java:8325)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:418)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1755)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1755)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
        at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:173)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:287)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:287)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1755)
        at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1755)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)
        at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112)
        at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213)
        at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
        at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:178)
        at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:96)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1755)
        at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:121)
        at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252)
        at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
        at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:366)
        at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:367)
        at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:423)
        at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:607)
        at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1407)
        at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1189)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1223)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

**To Reproduce**
Used the latest cosmos spring boot starter package.

**Expected behavior**
the server should start normally

**Setup (please complete the following information):**
 - OS: MacOs
 - IDE : Intellij
 - 	<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-cosmosdb-spring-boot-starter</artifactId>
			<version>2.3.2</version>
	</dependency>

**Comment by joshfree** [comment] 2020-08-06 17:17
Thanks for filing this github issue, @Abhisar.  Someone from the `azure-spring` team will follow up shortly

/cc @jialindai

**Comment by zhoufenqin** [comment] 2020-08-07 00:47
hi @Abhisar, can you provide more details about how to reproduce it? I follow[ this link](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db), it works well and can't reproduce your problem
BTW, some of my `azure-cosmosdb-spring-boot-starter` dependencies shows below, the `io.micrometer.core.instrument.Timer.start()` method exists in `micrometer-core:1.5.3` 
![image](https://user-images.githubusercontent.com/8765864/89596609-3dac2600-d88a-11ea-937c-a088b7607630.png)

**Comment by Abhisar** [comment] 2020-08-07 19:12
Hey figured that out , it was because of versioning issue .Once i bumped up the version this got resolved

**Comment by zhoufenqin** [comment] 2020-08-10 00:50
closing the issue

**Closed by zhoufenqin** 2020-08-10 00:50 UTC
Labels: Client, azure-spring, azure-spring.cosmos, bug, customer-reported
