### ISSUE TITLE
[BUG] Cosmos starter - exception with 2.4.0

### ISSUE THREAD

**Issue by AndreasVolkmann** [Azure/azure-sdk-for-java#17692] opened 2020-11-19 21:03 UTC
**Describe the bug**
When starting up with the cosmos starter and one simple repository, it fails with the following exception.

***Exception or Stack Trace***
```
2020-11-19 21:31:47.805  WARN 5716 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'run' defined in me.avo.cosmos.CosmosApplication: Unsatisfied dependency expressed through method 'run' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'notificationRepository': Unsatisfied dependency expressed through method 'setCosmosOperations' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cosmosTemplate' defined in class path resource [com/microsoft/azure/spring/autoconfigure/cosmosdb/CosmosAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.microsoft.azure.spring.data.cosmosdb.core.CosmosTemplate]: Factory method 'cosmosTemplate' threw exception; nested exception is java.lang.NoSuchMethodError: reactor/netty/resources/ConnectionProvider.fixed(Ljava/lang/String;IJLjava/time/Duration;)Lreactor/netty/resources/ConnectionProvider; (loaded from file:/C:/Users/anvolkma/.gradle/caches/modules-2/files-2.1/io.projectreactor.netty/reactor-netty-core/1.0.1/d3b6861cd9cd8b1e3387f14d80eb9c6724fd052b/reactor-netty-core-1.0.1.jar by jdk.internal.loader.ClassLoaders$AppClassLoader@1bff1c41) called from interface com.azure.data.cosmos.internal.http.HttpClient (loaded from file:/C:/Users/anvolkma/.gradle/caches/modules-2/files-2.1/com.microsoft.azure/azure-cosmos/3.7.3/b82f7d25a9badb5e27942c92f7bc400484076d3d/azure-cosmos-3.7.3.jar by jdk.internal.loader.ClassLoaders$AppClassLoader@1bff1c41).
2020-11-19 21:31:47.823  INFO 5716 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-11-19 21:31:47.854 ERROR 5716 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.azure.data.cosmos.internal.http.HttpClient.createFixed(HttpClient.java:47)

The following method did not exist:

    reactor/netty/resources/ConnectionProvider.fixed(Ljava/lang/String;IJLjava/time/Duration;)Lreactor/netty/resources/ConnectionProvider;

The method's class, reactor.netty.resources.ConnectionProvider, is available from the following locations:

    jar:file:/C:/Users/anvolkma/.gradle/caches/modules-2/files-2.1/io.projectreactor.netty/reactor-netty-core/1.0.1/d3b6861cd9cd8b1e3387f14d80eb9c6724fd052b/reactor-netty-core-1.0.1.jar!/reactor/netty/resources/ConnectionProvider.class

The class hierarchy was loaded from the following locations:

    reactor.netty.resources.ConnectionProvider: file:/C:/Users/anvolkma/.gradle/caches/modules-2/files-2.1/io.projectreactor.netty/reactor-netty-core/1.0.1/d3b6861cd9cd8b1e3387f14d80eb9c6724fd052b/reactor-netty-core-1.0.1.jar


Action:

Correct the classpath of your application so that it contains a single, compatible version of reactor.netty.resources.ConnectionProvider
```

**To Reproduce**
Run a simple sample with spring boot 2.4.0

***Code Snippet***
```kotlin
@SpringBootApplication
class CosmosApplication {

    @Bean fun run(notificationRepository: NotificationRepository) = CommandLineRunner {
        val notification = Notification("Test", "Test")
        notificationRepository.save(notification)
    }

}

fun main(args: Array<String>) {
	runApplication<CosmosApplication>(*args)
}
```

**Expected behavior**
Should start without issues. 

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : IntelliJ
 - Version of the Library used
`"com.microsoft.azure:azure-cosmosdb-spring-boot-starter:2.3.5"`

**Additional context**
The version shown on the project page does not exist:
`"com.azure.spring:azure-spring-boot-starter-cosmos:3.0.0-beta.1"`

**Comment by kushagraThapar** [comment] 2020-11-20 02:28
@chenrujun @saragluna  - please take a look at this issue. 

@AndreasVolkmann  - the exception you are getting is because of a netty dependency issue. Please check for netty and reactor-netty dependency versions used in your project and provided by spring and azure-cosmos modules.

**Comment by chenrujun** [comment] 2020-11-24 07:55
Hi, @AndreasVolkmann, could you please share your pom?

**Comment by AndreasVolkmann** [comment] 2020-11-24 16:45
@chenrujun I am using gradle kotlin script.

```kotlin
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
	val kotlinVersion = "1.4.20"
	id("org.springframework.boot") version "2.4.0"
	id("io.spring.dependency-management") version "1.0.10.RELEASE"
	kotlin("jvm") version kotlinVersion
	kotlin("plugin.spring") version kotlinVersion
}

group = "me.avo"
version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_1_8

repositories {
	jcenter()
	mavenCentral()
}

dependencies {
	implementation("org.springframework.boot:spring-boot-starter")
	implementation("org.springframework.boot:spring-boot-starter-aop")
	implementation("org.jetbrains.kotlin:kotlin-reflect")
	implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
	implementation("com.microsoft.azure:azure-cosmosdb-spring-boot-starter:2.3.5")

	testImplementation("org.springframework.boot:spring-boot-starter-test") {
		exclude(group = "org.junit.vintage", module = "junit-vintage-engine")
	}
	testImplementation("io.strikt:strikt-spring:0.28.0")
	testImplementation("com.tngtech.archunit:archunit:0.14.1")
}

tasks.withType<Test> {
	useJUnitPlatform()
}

tasks.withType<KotlinCompile> {
	kotlinOptions {
		freeCompilerArgs = listOf("-Xjsr305=strict", "-Xinline-classes")
		jvmTarget = "1.8"
		useIR = true
	}
}
```

**Comment by chenrujun** [comment] 2020-11-25 01:22
Hi, @AndreasVolkmann, 
Thank you for your kotlin script.

I reproduced your problem.
And fixed the problem by following commit:
https://github.com/chenrujun/azure-sdk-for-java-issue17692/commit/af69d6d0561b173757a8607b2816bfae5125c53e

Could you please try it in your project?

`spring-boot:2.4.0` just released, and we haven't support it for now.
Please wait our next release.

**Comment by AndreasVolkmann** [comment] 2020-11-25 13:49
@chenrujun Thanks, it does work with older versions.
I am waiting for the next release.

**Comment by chenrujun** [comment] 2020-11-25 23:24
cc: @yiliuTo . FYI.

**Comment by RUBenGAMArrarodRiguEZ-ToMtOm** [comment] 2021-01-16 14:24
@chenrujun after about a month ago of that finding https://github.com/Azure/azure-sdk-for-java/issues/17692#issuecomment-733402462
A new version has been released, `spring data cosmos 3.3.0` 

Des it support any of the spring boot 2.4.0 or 2.4.2 versions?
https://github.com/Azure/azure-sdk-for-java/pull/18645

**Comment by chenrujun** [comment] 2021-01-18 02:53
Hi, @RUBenGAMArrarodRiguEZ-ToMtOm 

Sorry that now it does NOT support spring boot 2.4.0 or 2.4.2 versions.
Because we have some problem in this PR: https://github.com/Azure/azure-sdk-for-java/pull/17905

**Comment by RUBenGAMArrarodRiguEZ-ToMtOm** [comment] 2021-01-19 20:59
Thanks for the update I took a look at that issue.

**Comment by juliojgd** [comment] 2021-02-10 14:00
@chenrujun Do you have any estimated date to release a versión supporting Spring Boot 2.4.x versions? 
Thanks

**Comment by chenrujun** [comment] 2021-02-18 01:09
@juliojgd 
We will support spring-boot-2.4.x before `2021-03-31`.

**Comment by chenrujun** [comment] 2021-03-25 23:12
Closing this issue because [azure-spring-boot-starter-cosmos:3.3.0](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-boot-starter-cosmos/CHANGELOG.md#330-2021-03-22) has been released. It supports spring-boot:2.4.3.

**Closed by chenrujun** 2021-03-25 23:12 UTC
Labels: Client, Cosmos, azure-spring-cosmos, customer-reported, question

**Comment by mark-lassche-maersk** [comment] 2021-07-20 12:55
Hi Chenrujun,

We're running into this this or similar problem with spring boot 2.4.3 and the following dependency:

<dependency>
  <groupId>com.azure</groupId>
  <artifactId>azure-cosmos</artifactId>
  <version>4.11.0</version>
</dependency>

Is this expected? 

Best,

**Comment by chenrujun** [comment] 2021-07-21 09:23
Hi, @mark-lassche-maersk, thanks for reaching out.

1. What's your `azure-spring-boot-starter-cosmos`'s version? could you please share your pom?
2. Could you please try latest versions: `spring-boot:2.5.2` and `azure-spring-boot-starter-cosmos:3.7.0`?

**Comment by mark-lassche-maersk** [comment] 2021-07-21 09:48
Hi @chenrujun,

I'm afraid I can't share the pom in its entirety but if we continue the java/cosmos approach I'll try to get an isolated repro case. I'll have to discuss this with the team. Are there any dependencies that you know of that can get in the way?

I've updated to spring-boot2.5.2 and azure-spring-boot-starter 3.7.0 and the exception persists.

**Comment by chenrujun** [comment] 2021-07-22 01:10
Hi, @mark-lassche-maersk .

Could you please create a new issue, and create a simple project to reproduce your problem?
I can not help if I can not reproduce your problem.
I guess there is some version problem of `reactor-netty-core` in your project, but I'm not sure.
