### ISSUE TITLE
[BUG] EventHubConsumerAsyncClient suddenly stops receiving messages with org.apache.qpid.proton.engine.TransportException

### ISSUE THREAD

**Issue by roehrijn** [Azure/azure-sdk-for-java#23157] opened 2021-07-23 10:13 UTC
While receiving messages from an IoT hub we experiencing a constantly reproducible error after a few hours after EventHubConsumerAsyncClient  has been started to consume data from a dedicated partition:

`2021-07-22 18:36:50.066+0000 [reactor-executor-1] INFO  c.a.c.a.i.ReactorConnection - connectionId[MF_5faa2d_1626958475815] signal[org.apache.qpid.proton.engine.TransportException: specified frame size 911487025 greater than maximum valid frame size 65536, errorContext[NAMESPACE: **************.servicebus.windows.net], isTransient[false], initiatedByClient[false]]: Disposing of ReactorConnection.
2021-07-22 18:36:50.066+0000 [reactor-executor-1] INFO  c.a.c.a.i.RequestResponseChannel:$cbs - Upstream connection publisher was completed. Terminating processor.
2021-07-22 18:36:50.066+0000 [reactor-executor-1] INFO  c.a.c.a.i.RequestResponseChannel:$cbs - namespace[MF_5faa2d_1626958475815] entityPath[$cbs]: AMQP channel processor completed. Notifying 4 subscribers.
2021-07-22 18:36:50.069+0000 [reactor-executor-1] WARN  c.a.c.a.i.RequestResponseChannel:$cbs - Error occurred closing Disposable channel.
block()/blockFirst()/blockLast() are blocking, which is not supported in thread reactor-executor-1
2021-07-22 18:36:50.069+0000 [reactor-executor-1] INFO  c.a.c.a.i.RequestResponseChannel:$management - Upstream connection publisher was completed. Terminating processor.
2021-07-22 18:36:50.069+0000 [reactor-executor-1] INFO  c.a.c.a.i.RequestResponseChannel:$management - namespace[MF_5faa2d_1626958475815] entityPath[$management]: AMQP channel processor completed. Notifying 2 subscribers.
2021-07-22 18:36:50.070+0000 [reactor-executor-1] INFO  c.a.c.a.i.RequestResponseChannel:$cbs - Upstream connection publisher was completed. Terminating processor.
2021-07-22 18:36:50.070+0000 [reactor-executor-1] INFO  c.a.c.a.i.RequestResponseChannel:$cbs - namespace[MF_5faa2d_1626958475815] entityPath[$cbs]: AMQP channel processor completed. Notifying 0 subscribers.
2021-07-22 18:36:50.073+0000 [reactor-executor-1] INFO  c.a.c.a.i.handler.ConnectionHandler - onConnectionUnbound hostname[iothub-ns-connectedc-3990145-07b9540cf0.servicebus.windows.net], connectionId[MF_5faa2d_1626958475815], state[ACTIVE], remoteState[ACTIVE]
2021-07-22 18:36:50.074+0000 [reactor-executor-1] INFO  c.a.c.a.i.handler.SendLinkHandler - onLinkFinal connectionId[MF_5faa2d_1626958475815], linkName[mgmt:sender]
2021-07-22 18:36:50.075+0000 [reactor-executor-1] INFO  c.a.c.a.i.handler.ReceiveLinkHandler - onLinkFinal connectionId[MF_5faa2d_1626958475815], linkName[mgmt:receiver]
2021-07-22 18:36:50.076+0000 [reactor-executor-1] INFO  c.a.m.e.i.ManagementChannel - Management endpoint state: CLOSED
2021-07-22 18:36:50.078+0000 [reactor-executor-1] INFO  c.a.c.a.i.handler.SessionHandler - onSessionFinal connectionId[MF_5faa2d_1626958475815], entityName[mgmt-session], condition[null], description[null]
2021-07-22 18:36:50.078+0000 [reactor-executor-1] INFO  c.a.c.a.i.handler.ReceiveLinkHandler - onLinkFinal connectionId[MF_5faa2d_1626958475815], linkName[0_d81418_1626958477435]
2021-07-22 18:36:50.080+0000 [reactor-executor-1] INFO  c.a.m.e.i.AmqpReceiveLinkProcessor - linkName[0_d81418_1626958477435] entityPath[connectedcooler-ingress-d/ConsumerGroups/cosmosdb-input/Partitions/0] Receive link endpoint states are closed. Requesting another.
2021-07-22 18:36:50.080+0000 [reactor-executor-1] INFO  c.a.m.e.i.AmqpReceiveLinkProcessor - Requesting a new AmqpReceiveLink from upstream.
2021-07-22 18:36:50.080+0000 [reactor-executor-1] INFO  c.a.m.e.i.AmqpReceiveLinkProcessor - linkName[0_d81418_1626958477435] entityPath[connectedcooler-ingress-d/ConsumerGroups/cosmosdb-input/Partitions/0]. Setting next AMQP receive link.
2021-07-22 18:36:50.081+0000 [boundedElastic-7] INFO  c.a.m.e.i.AmqpReceiveLinkProcessor - linkName[0_d81418_1626958477435] entityPath[connectedcooler-ingress-d/ConsumerGroups/cosmosdb-input/Partitions/0] Receive link endpoint states are closed. Requesting another.
2021-07-22 18:36:50.081+0000 [reactor-executor-1] INFO  c.a.m.e.EventHubConsumerAsyncClient - connectionId[MF_5faa2d_1626958475815] linkName[0_d81418_1626958477435] Creating receive consumer for partition '0'
2021-07-22 18:36:50.081+0000 [boundedElastic-7] INFO  c.a.m.e.i.AmqpReceiveLinkProcessor - Requesting a new AmqpReceiveLink from upstream.
2021-07-22 18:36:50.082+0000 [reactor-executor-1] ERROR c.a.c.a.i.ReactorSession - connectionId[MF_5faa2d_1626958475815] sessionName[****************/ConsumerGroups/*************/Partitions/0] entityPath[*****************/ConsumerGroups/***********/Partitions/0] linkName[0_d81418_1626958477435] Cannot create receive link from a closed session.
`

This always happens after 1-6 hours of working stream consumption. 

This is how I create the client and consume messages:

	EventHubConsumerAsyncClient eventProcessorClient = new EventHubClientBuilder()
		.connectionString(eventHubConnectionString, eventHubName)
		.consumerGroup(consumerGroup)
		.buildAsyncConsumerClient();

	eventProcessorClient
		.receiveFromPartition("0", EventPosition.fromSequenceNumber(lastSequenceNo))
		.limitRate(100)
		.subscribe(new Subscriber<PartitionEvent>() {
			private Subscription subscription;

			@Override
			public void onSubscribe(Subscription subscription) {
				this.subscription = subscription;
				this.subscription.request(1);
			}

			@Override
			public void onNext(PartitionEvent partitionEvent) {
			   doSomethingExpensive()
				this.subscription.request(1);
			}

			@Override
			public void onError(Throwable throwable) { }

			@Override
			public void onComplete() {

			}
		}
	);

I'm using the following `com.azure:azure-messaging-eventhubs:5.7.0` as a transitive dependency of `com.azure.spring:azure-spring-integration-eventhubs:2.4.0`

**Comment by joshfree** [comment] 2021-07-23 21:52
@conniey @anuchandy @YijunXieMS

**Comment by conniey** [comment] 2021-07-26 19:42
@roehrijn Hey, can you provide some information about your Event Hubs instance? (Throughput units, partitions, SKU, etc?) Also, what is the hardware / VM specs you're running on?
This exception is coming from our underlying AMQP library (FrameParser.java https://github.com/apache/qpid-proton-j/blob/main/proton-j/src/main/java/org/apache/qpid/proton/engine/impl/FrameParser.java#L304)

@JamesBirdsall Is there a time we may change the frame size? After the AMQP connection is created... I don't think the frame size changes, or does it?

**Comment by JamesBirdsall** [comment] 2021-07-26 20:11
The maximum frame size is negotiated as part of the AMQP connection open and I doubt there's anything in the protocol which can change it after that. Even if it were possible, we'd never be allowing frames nearly a gigabyte in size. In AMQP, the frame size is the first four bytes of a frame, and 911487025 considered as a bit pattern and viewed as an ASCII string is "6T01", which could be part of a timestamp. It looks like the stack has become desynchronized from the frame stream and is trying to parse starting in the middle of a frame.

**Comment by conniey** [comment] 2021-07-26 21:17
Duplicate of: #20958.

Even though the connection is interrupted, we should be requesting another connection be created upstream. @YijunXieMS had a fix for this in Service Bus.

**Closed by conniey** 2021-07-26 21:17 UTC
Labels: Client, Event Hubs, customer-reported, pillar-reliability, question
