### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by stingster** [Azure/azure-sdk-for-java#18072] opened 2020-12-10 14:17 UTC
**Describe the bug**
The method copyFromUrl() does not seem to work when the blob is encrypted with customer-provided, and managed, keys

***Exception or Stack Trace***
`com.azure.storage.blob.models.BlobStorageException: Status code 409, \"<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>CannotVerifyCopySource</Code><Message>The blob is encrypted with customer specified encryption, but it was not provided in the request.\nRequestId:4f36bdd5-701e-007c-4428-ce3b45000000\nTime:2020-12-09T12:38:52.1019664Z</Message></Error>\"\n\tat sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_265]\n\tat sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_265]\n\tat sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_265]\n\tat java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_265]\n\tat com.azure.core.http.rest.RestProxy.instantiateUnexpectedException(RestProxy.java:320) ~[com.azure.azure-core-1.7.0.jar:na]\n\tat com.azure.core.http.rest.RestProxy.lambda$ensureExpectedStatus$3(RestProxy.java:361) ~[com.azure.azure-core-1.7.0.jar:na]\n\tat reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118) ~[io.projectreactor.reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]\n\tat reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782) ~[io.projectreactor.reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]\n\tat reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:320) ~[io.projectreactor.reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]\n\tat reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:337) ~[io.projectreactor.reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]\n\tat reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2344) ~[io.projectreactor.reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]\n\tat reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onSubscribe(MonoCacheTime.java:276) ~[io.projectreactor.reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]\n\tat reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:191) ~[io.projectreactor.reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]\n\tat reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53) ~[io.projectreactor.reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]\n\tat reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57) ~[io.projectreactor.reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]\n\tat reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[io.projectreactor.reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]\n\tat reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:132) ~[io.projectreactor.reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]\n\tat reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57) ~[io.projectreactor.reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]\n\tat reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150) ~[io.projectreactor.reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]\n\tat reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114) ~[io.projectreactor.reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]\n\tat reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123) ~[io.projectreactor.reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]\n\tat reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112) ~[io.projectreactor.reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]\n\tat reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213) ~[io.projectreactor.reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]\n\tat reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123) ~[io.projectreactor.reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]\n\tat reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:178) ~[io.projectreactor.reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]\n\tat reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:96) ~[io.projectreactor.reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]\n\tat reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782) ~[io.projectreactor.reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]\n\tat reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:121) ~[io.projectreactor.reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]\n\tat reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252) ~[io.projectreactor.reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]\n\tat reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136) ~[io.projectreactor.reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]\n\tat reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:378) ~[io.projectreactor.netty.reactor-netty-0.9.10.RELEASE.jar:0.9.10.RELEASE]\n\tat reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:373) ~[io.projectreactor.netty.reactor-netty-0.9.10.RELEASE.jar:0.9.10.RELEASE]\n\tat reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:429) ~[io.projectreactor.netty.reactor-netty-0.9.10.RELEASE.jar:0.9.10.RELEASE]\n\tat reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:625) ~[io.projectreactor.netty.reactor-netty-0.9.10.RELEASE.jar:0.9.10.RELEASE]\n\tat reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96) ~[io.projectreactor.netty.reactor-netty-0.9.10.RELEASE.jar:0.9.10.RELEASE]\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[io.netty.netty-all-4.1.50.Final.jar:4.1.50.Final]\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[io.netty.netty-all-4.1.50.Final.jar:4.1.50.Final]\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[io.netty.netty-all-4.1.50.Final.jar:4.1.50.Final]\n\tat io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[io.netty.netty-all-4.1.50.Final.jar:4.1.50.Final]\n\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[io.netty.netty-all-4.1.50.Final.jar:4.1.50.Final]\n\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[io.netty.netty-all-4.1.50.Final.jar:4.1.50.Final]\n\tat io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[io.netty.netty-all-4.1.50.Final.jar:4.1.50.Final]\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[io.netty.netty-all-4.1.50.Final.jar:4.1.50.Final]\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[io.netty.netty-all-4.1.50.Final.jar:4.1.50.Final]\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[io.netty.netty-all-4.1.50.Final.jar:4.1.50.Final]\n\tat io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1518) ~[io.netty.netty-all-4.1.50.Final.jar:4.1.50.Final]\n\tat io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1267) ~[io.netty.netty-all-4.1.50.Final.jar:4.1.50.Final]\n\tat io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1314) ~[io.netty.netty-all-4.1.50.Final.jar:4.1.50.Final]\n\tat io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) ~[io.netty.netty-all-4.1.50.Final.jar:4.1.50.Final]\n\tat io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440) ~[io.netty.netty-all-4.1.50.Final.jar:4.1.50.Final]\n\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[io.netty.netty-all-4.1.50.Final.jar:4.1.50.Final]\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[io.netty.netty-all-4.1.50.Final.jar:4.1.50.Final]\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[io.netty.netty-all-4.1.50.Final.jar:4.1.50.Final]\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[io.netty.netty-all-4.1.50.Final.jar:4.1.50.Final]\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[io.netty.netty-all-4.1.50.Final.jar:4.1.50.Final]\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[io.netty.netty-all-4.1.50.Final.jar:4.1.50.Final]\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[io.netty.netty-all-4.1.50.Final.jar:4.1.50.Final]\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[io.netty.netty-all-4.1.50.Final.jar:4.1.50.Final]\n\tat io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[io.netty.netty-all-4.1.50.Final.jar:4.1.50.Final]\n\tat io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[io.netty.netty-all-4.1.50.Final.jar:4.1.50.Final]\n\tat io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[io.netty.netty-all-4.1.50.Final.jar:4.1.50.Final]\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[io.netty.netty-all-4.1.50.Final.jar:4.1.50.Final]\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty.netty-all-4.1.50.Final.jar:4.1.50.Final]\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-all-4.1.50.Final.jar:4.1.50.Final]\n\tat java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_265]\n","sourceThread":"OSL-akka.actor.default-dispatcher-6","akkaSource":"OslRoutingService(akka://OSL)","sourceActorSystem":"OSL","akkaTimestamp":"12:38:52.209UTC"}`

**To Reproduce**
- Deposit an encrypted blob by using `public Mono<BlockBlobItem> upload(Flux<ByteBuffer> data, long length)` method from `BlockBlobAsyncClient` class
- Use `public Mono<String> copyFromUrl(String copySource)` from `BlobAsyncClientBase` class to copy the message using customer provided keys (or none for that matter, the fail happened no matter what keys and/or number of keys we provided after upload)
- the `copySource` was built from `sourceUrl` and generated SAS token as per next snippet:
`  private def getBlobServiceAccessToken(sourceBlobClient: BlockBlobAsyncClient) = {
    val expiryTime = OffsetDateTime.now().plusDays(1)
    val permission = new BlobSasPermission().setReadPermission(true)
    val myValues = new BlobServiceSasSignatureValues(expiryTime, permission).setStartTime(OffsetDateTime.now())
    sourceBlobClient.generateSas(myValues)
  }

  private def buildSourceLocationUrl(sas: String, sourceUrl: String) = {
    if (sourceUrl.contains('?')) {
      s"${sourceUrl}&${sas}"
    }
    else {
      s"${sourceUrl}?${sas}"
    }
  }`

***Code Snippet***
See reproducing steps from above

**Expected behavior**
The method returns with success

**Screenshots**

**Setup (please complete the following information):**
 - OS: Linux
 - IDE : IntelliJ
 - Version of the Library used: Azure SDK for Java version 12.8.0

**Additional context**
Hitting this issue we implemented a workaround where we use:
- same encryption keys provided for copy
- same clients (built with the same method)
to retrieve and deposit the message. This works just fine.
Also, without encryption, the copyFromUrl() method works fine. The only problem appears when the blob is encrypted

The Azure Account used was with Shared Credentials Key.

I am open to any other questions you might have
.
**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [yes] Bug Description Added
- [yes] Repro Steps Added
- [yes] Setup information Added

**Comment by gapra-msft** [comment] 2020-12-10 18:33
@stingster Thanks for reporting this issue. I will look into reproducing the issue and update you on the investigation

**Comment by gapra-msft** [comment] 2020-12-10 18:54
@stingster I looked into this issue a little further, and it looks like [copyFromUrl](https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob-from-url) doesn't support customer provided keys, so it is expected that you get this error (though I would say the error messaging from the service should probably be clearer). 

Please let us know if you have any other questions.

**Comment by stingster** [comment] 2020-12-10 19:25
Hi @gapra-msft ,

Thank you for your prompt answer!

As a matter a fact there are few questions that we need to raise because we need to decide how we should go from this with the implementation:
* This issue reproduces also on the `beginCopy()` method. Is this also not supported for customer provided keys?
* Is there any other built-in copy method that does support this feature?
* Is there a plan to offer support for this? If yes, was there a date established?

Thank you once again.

**Comment by gapra-msft** [comment] 2020-12-10 20:27
@stingster, Thank you for your questions! Here are the answers

- This issue reproduces also on the beginCopy() method. Is this also not supported for customer provided keys?
beginCopy() also does not currently support customer provided keys.
 
- Is there any other built-in copy method that does support this feature?
There is no API that supports customer provided keys at the source currently. 

Is there a plan to offer support for this? If yes, was there a date established?
We are looking into this feature, but we don't have any timelines yet.

Hope this helps.

**Comment by stingster** [comment] 2020-12-10 21:00
Thank you, it helps because now we know what to do next.

**Comment by gapra-msft** [comment] 2020-12-11 18:04
@stingster Thanks for the feedback. 

Just to provide context on what the message is - it's the same response provided if you do a GET on the source file without providing key information. 

The error message is less than ideal currently but I think will make more sense in the future if support is added for source-encryption-key.

**Comment by gapra-msft** [comment] 2020-12-11 18:05
I'm going to go ahead and close this issue as I believe all your questions have been addressed. Feel free to re-open this issue/ create another issue if you have any other issues!

Thanks!

**Closed by gapra-msft** 2020-12-11 18:05 UTC
Labels: Client, Storage, customer-reported, question
