### ISSUE TITLE
Application Freezes without error message

### ISSUE THREAD

**Issue by harry12345678910** [Azure/azure-sdk-for-java#19837] opened 2021-03-14 00:17 UTC
Hi,

when both dependencies are enabled, my application freezes without an error message:

```
<dependency>
	<groupId>com.azure.spring</groupId>
	<artifactId>azure-spring-boot-starter-keyvault-secrets</artifactId>
	<version>3.2.0</version>
</dependency>
<!--<dependency>
	<groupId>com.azure</groupId>
	<artifactId>azure-storage-blob</artifactId>
	<version>12.6.0</version>
</dependency>-->`
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc84b055-7874-13cd-912c-7f8e37bbb880
* Version Independent ID: 3aa67db1-9d45-9486-f67d-4cd4e9784fb7
* Content: [Azure Key Vault Secrets Spring Boot starter client library for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/spring-boot-starter-keyvault-secrets-readme?view=azure-java-stable)
* Content Source: [docs-ref-services/latest/spring-boot-starter-keyvault-secrets-readme.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/latest/spring-boot-starter-keyvault-secrets-readme.md)
* Service: **springboot**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by joshfree** [comment] 2021-03-15 17:37
@stliu could you please help route this?

**Comment by stliu** [comment] 2021-03-16 02:55
Thanks @joshfree

**Comment by saragluna** [comment] 2021-03-16 04:45
@harry12345678910 thanks for reporting this, we'll try to reproduce this issue. 

@ZhuXiaoBing-cn please help reproduce this issue. I am suspecting it is caused by a dependency conflict.

**Comment by stliu** [comment] 2021-03-16 08:24
Okay, I have reproduced this issue, internally, there is an exception

```
was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.NoSuchMethodError: 'java.util.List com.azure.core.http.HttpHeader.getValuesList()'
	at com.azure.core.http.netty.NettyAsyncHttpClient.lambda$bodySendDelegate$2(NettyAsyncHttpClient.java:115)
	at reactor.netty.http.client.HttpClientConnect$HttpClientHandler.requestWithBody(HttpClientConnect.java:552)
	at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.lambda$onStateChange$0(HttpClientConnect.java:394)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
	at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.onStateChange(HttpClientConnect.java:395)
	at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:638)
	at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onStateChange(DefaultPooledConnectionProvider.java:195)
	at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnection.onStateChange(DefaultPooledConnectionProvider.java:466)
	at reactor.netty.channel.ChannelOperationsHandler.channelActive(ChannelOperationsHandler.java:63)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:209)
```

And this is caused by the dependency conflict

`com.azure:azure-storage-blob:12.6.0` has a dependency of `com.azure:azure-core:1.4.0` and `com.azure.spring:azure-spring-boot-starter-keyvault-secrets` depends on `com.azure:azure-core:1.3.0` and `com.azure:azure-core-http-netty:1.8.0`.

the method `com.azure.core.http.HttpHeader.getValuesList()` is removed from azure-core:1.4.0, which causes this breaking change.

I'm still trying to find a workaround

**Comment by saragluna** [comment] 2021-04-12 10:22
Closing this issue now and please reopen it if you still encounter this problem.

**Closed by saragluna** 2021-04-12 10:22 UTC
Labels: Client, azure-spring, azure-spring-keyvault, customer-reported, question
