### ISSUE TITLE
Getting intermittent 502 Bad Gateway error from azure-service-bus queue

### ISSUE THREAD

**Issue by prakash-ag** [Azure/azure-sdk-for-java#1913] opened 2017-09-21 09:54 UTC
Hi,

While trying to create/delete queue I am getting 502 Bad Gateway error intermittently. 
Here is one such example error activity/diagnosis log collected from azure-portal: (request-id removed )
```
HTTP/1.1 502 Bad Gateway [Cache-Control: no-cache, Pragma: no-cache, Content-Type: application/json; charset=utf-8, Expires: -1, x-ms-failure-cause: service]
```

What might be the reason for these errors? Is it due to any request throttling?

Regards,
Prakash

**Comment by anuchandy** [comment] 2017-09-21 16:27
Tagging owner from service team @binzywu

**Comment by praries880** [comment] 2018-12-07 23:17
@prakash-ag Are you still experiencing the isue?

**Comment by jfggdl** [comment] 2019-05-28 20:19
@prakash-ag - We are going to be closing this issue, but feel free to reopen it if you still are interested in us researching the root cause of this issue.

**Closed by jfggdl** 2019-05-28 20:19 UTC
Labels: Service Attention, Service Bus
