### ISSUE TITLE
Unable to get disk size for unmanaged disks.

### ISSUE THREAD

**Issue by ImranBijapuri** [Azure/azure-sdk-for-java#2015] opened 2018-02-01 16:49 UTC
I am using Azure java SDK v1.1.2 and I am seeing inconsistent behaviour when I am trying to get the disk size for unmanaged disks.
These two methods
  - VirtualMachine::osDiskSize()
  - VirtualMachineUnmanagedDataDisk::size()
return a value of 0 for some unmanaged disks.

I replaced this API call with azure storage sdk which gets the reference to the container and then gets the reference to the unmanaged disk blob and I am able to read the size of the blob (disk) correctly. 

I also checked the power state of the VMs and they seem to be in a running state as well.

What is the reason behind such inconsistent behaviour ?

**Comment by arielctal** [comment] 2018-02-01 17:22
Maybe someone can shed some light on the cases where 0 is being returned.

In this example the writer seemed to have dealt with it by setting a default value -
https://github.com/Azure/azure-sdk-for-java/blob/f8d8b3c95c31c1830e3d8d8674462e3c87a4ba62/archive/azure-samples/src/main/java/com/microsoft/azure/management/compute/samples/ManageVirtualMachineWithUnmanagedDisks.java
```
            int osDiskSizeInGb = windowsVM.osDiskSize();
            if (osDiskSizeInGb == 0) {
                // Server is not returning the OS Disk size, possible bug in server
                System.out.println("Server is not returning the OS disk size, possible bug in the server?");
                System.out.println("Assuming that the OS disk size is 256 GB");
                osDiskSizeInGb = 256;
            }
```

What are the circumstances when this might happen? Is there a characteristic of the VM that will cause this issue?

**Comment by arielctal** [comment] 2018-02-01 19:15
This may be a duplicate of https://github.com/Azure/azure-sdk-for-java/issues/1643

**Comment by praries880** [comment] 2018-11-19 21:35
Closing this as it s a dupe of #1643

**Closed by praries880** 2018-11-19 21:35 UTC
