### ISSUE TITLE
[BUG] OutOfMemoryError only get events from Azure EventHub 

### ISSUE THREAD

**Issue by jhunior244** [Azure/azure-sdk-for-java#26366] opened 2022-01-07 21:34 UTC
My application consumes memory up to the limit, even just getting the events from the hub and taking no action.

java version: 16
azure-messaging-eventhubs:5.10.1
azure-messaging-eventhubs-checkpointstore-blob:1.10.0

I have two consumers as per the following code:
![image](https://user-images.githubusercontent.com/45322859/148609837-61061fb1-a85a-4f42-8432-f1b42be2489f.png)
![image](https://user-images.githubusercontent.com/45322859/148609958-7da2cf18-980e-4331-9ec3-2b4292d00485.png)

The image below is the use of memory after some minutes running the program:
![image](https://user-images.githubusercontent.com/45322859/148609744-e5b04e52-80b7-49d5-97e8-67e4f13cf67b.png)

**Comment by joshfree** [comment] 2022-01-10 19:40
@anuchandy could you please follow up? 

/cc @conniey

**Comment by andrepintorj** [comment] 2022-01-12 18:45
Any updates on this, guys?

**Comment by anuchandy** [comment] 2022-01-13 03:34
@jhunior244 @andrepintorj - there is a known issue when enabling "timeout" for batch receive API. please see this issue https://github.com/Azure/azure-sdk-for-java/issues/23950 and linked Reactor windowTimeout issue. 

We currently don't have a workaround for this functionality. Until it is addressed, could you use batch receive API that does not take a timeout?

**Comment by jhunior244** [comment] 2022-01-13 21:02
> @anuchandy I am using this code e I am still having memory problems
> 
> ![image](https://user-images.githubusercontent.com/45322859/149407092-42e97fb4-887d-4f39-b1f2-1e12c7324efe.png)
> 
> and the use of memory is like this
> 
> ![image](https://user-images.githubusercontent.com/45322859/149407267-3f356362-e6f6-4424-959d-49ab0c4a4830.png)

**Comment by anuchandy** [comment] 2022-01-14 20:28
Thank you, @jhunior244, for moving to the API without a timeout. 

From the initial graph (API with timeout), I can see the heap usage is increasing, and you were running into OOM.

For the latest graph (API without timeout), are you experiencing only higher_memory usage, or do you see it also leads to OOM like the previous case?

**Comment by jhunior244** [comment] 2022-01-17 13:16
Hi @anuchandy. Even without using timeOut property, after some time runing the OOM error occurs.

**Comment by anuchandy** [comment] 2022-01-20 20:43
I see. thanks, @jhunior244. Could you share the following info - 

1. The average size of each event
2. The number of paritions
2. The location of the event hub and consumer application
3. It looks like you can repro this quickly after starting the processor. Do you know if there were enough events in the event hub to keep the processor busy? or there are certain periods (during  the test duration) in which the processor can be idle due to the absence of events (trying to correlate it with internal timeouts, which involves releasing of resources)

I'm asking for these datas so that we can try to replicate it.

**Comment by jhunior244** [comment] 2022-01-21 17:42
1. The average size of each event is 3.3kb and I try process them with a batch size of 1000.
2. It has 16 partitions
3. Both event hub and consumers are on East US
4. The hub keeps the application busy all time, it has usually millions of events to be delivered to the consumers.
5. The max heap was set to 4GB (Xmx)

**Comment by liukun-msft** [comment] 2022-01-24 12:54
Hi @jhunior244. Thanks for the information. However, I couldn't reproduce your issue from my end. So I may need you help to provide more details:
1. How many times it may take from start application to encounter OOM error? 
2. Do you have any settings for the GC? or do you know which garbage collector are you using? 
3. What's server/container hardware properties (like CPU cores and total memory)?
4. The maximum event size. 
5. JDK specific version, Oracle JDK or Open JDK?

Below is the code I use to test `EventProcessorClient` and I keep sending one million events data (around 3.3kb each) with 10 minutes interval to make application always busy. Please also help to check if this code is good to you.
EventHubsClientConfiguration.java
```Java
@Configuration
public class EventHubsClientConfiguration {
    private static final String eventHubconnectionString = "";
    private static final String eventHubName = "";
    private static final String storageConnectionString = "";
    private static final String storageContainer = "";

    @Bean(initMethod = "start")
    public EventProcessorClient eventOfferUpProcessorClient(){
        BlobContainerAsyncClient blobContainerAsyncClient = new BlobContainerClientBuilder()
                .connectionString(storageConnectionString)
                .containerName(storageContainer)
                .buildAsyncClient();

        return new EventProcessorClientBuilder()
                .connectionString(eventHubconnectionString, eventHubName)
                .consumerGroup(EventHubClientBuilder.DEFAULT_CONSUMER_GROUP_NAME)
                .processEventBatch(getBatchEvents(), 2000)
                .processError(getProcessError())
                .checkpointStore(new BlobCheckpointStore(blobContainerAsyncClient))
                .buildEventProcessorClient();
    }

    private Consumer<EventBatchContext> getBatchEvents(){
        return eventBatchContext -> {
            List<EventData> events = eventBatchContext.getEvents();
            eventBatchContext.updateCheckpoint();
        };
    }

    private Consumer<ErrorContext> getProcessError() {
        return errorContext -> {
            System.out.printf("Error occurred in partition processor for partition %s, %s.%n",
                    errorContext.getPartitionContext().getPartitionId(),
                    errorContext.getThrowable());
        };
    }
}
```
Application.java
```Java
@SpringBootApplication
public class Application {
	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}
}
```

The maximun heap only reaches 750MB in 1 hours. The trend looks it wouldn't throw OOM but we can extend the time if needed.
![image](https://user-images.githubusercontent.com/97088315/150783987-9b462147-860c-4e23-91f4-4dad6d2a01c8.png)

**Closed** 2022-02-15 01:39 UTC
Labels: question, Event Hubs, Client, customer-reported, pillar-reliability, needs-author-feedback, no-recent-activity

**Comment by dusmar** [comment] 2023-02-20 21:18
Hi @jhunior244
Have you found the solution for this? Seeing the same behavior in our app. Thank you!
