### ISSUE TITLE
[QUERY] About eventhub sdk performance

### ISSUE THREAD

**Issue by lu-cheng** [Azure/azure-sdk-for-java#15478] opened 2020-09-22 08:14 UTC
Hi, @conniey  @mikeharder 
I created a test project about eventhub, The test uses resources (VM, Eventhub) in the same region，and the round trip time through eventhub is 100-300 msec. Is this performance a normal expectation?  I have a customer here and expect this result to be 50 msec. Can it be improved?

If my test code is incorrect, please help me correct it.
Repository: https://github.com/lu-cheng/eventhub-test

**Comment by conniey** [comment] 2020-09-22 16:37
This is a duplicate of https://github.com/Azure/azure-sdk-for-java/issues/15077

**Closed by conniey** 2020-09-22 16:37 UTC
Labels: Client, Event Hubs
