### ISSUE TITLE
ADLs Gen2: readToFileWithResponse throws java.lang.IllegalArgumentException: The value of the parameter 'count' should be between 0 and 9223372036854775807 error

### ISSUE THREAD

**Issue by rajeevsinghAD** [Azure/azure-sdk-for-java#11035] opened 2020-05-11 13:04 UTC
Hello ADLS Gen2 Team,

I am using ```readToFileWithResponse``` API with parallel transfer options and I am receiving ```java.lang.IllegalArgumentException: The value of the parameter 'count' should be between 0 and 9223372036854775807``` error for any value for range and byte size.

I also tried to use new ```FileRange(0)``` to download the file but ended up with a different error. 
I am using ```azure-storage-file-datalake 12.0.1``` version with ```azure-core-http-okhttp 1.2.0``` and ```azure-identity 1.0.4```

```
ParallelTransferOptions parallelTransferOptions = new ParallelTransferOptions(128, 2, null, null);
		DownloadRetryOptions downloadRetryOptions = new DownloadRetryOptions().setMaxRetryRequests(5);
		Set<OpenOption> openOptions = new HashSet<>(
				Arrays.asList(StandardOpenOption.CREATE_NEW, StandardOpenOption.WRITE, StandardOpenOption.READ)); 
																								
		FileRange fileRange = new FileRange(0, 256L);

		fileClient.readToFileWithResponse(localDownloadedFilePath, fileRange, parallelTransferOptions,
				downloadRetryOptions, null, false, openOptions, this.timeout, new Context(this.key2, this.value2));
```

Error stack trace

```
java.lang.IllegalArgumentException: The value of the parameter 'count' should be between 0 and 9223372036854775807.
	at com.azure.storage.common.implementation.StorageImplUtils.assertInBounds(StorageImplUtils.java:158)
	at com.azure.storage.blob.HttpGetterInfo.setCount(HttpGetterInfo.java:58)
	at com.azure.storage.blob.specialized.ReliableDownload.lambda$applyReliableDownload$1(ReliableDownload.java:117)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:177)
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:89)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onNext(FluxTimeout.java:173)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:242)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:107)
	at reactor.core.publisher.FluxTakeUntil$TakeUntilPredicateSubscriber.onNext(FluxTakeUntil.java:77)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.FluxRepeatPredicate$RepeatPredicateSubscriber.onNext(FluxRepeatPredicate.java:79)
	at reactor.core.publisher.FluxJust$WeakScalarSubscription.request(FluxJust.java:99)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:1956)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:1830)
	at reactor.core.publisher.FluxJust.subscribe(FluxJust.java:70)
	at reactor.core.publisher.FluxRepeatPredicate$RepeatPredicateSubscriber.resubscribe(FluxRepeatPredicate.java:113)
	at reactor.core.publisher.FluxRepeatPredicate.subscribeOrReturn(FluxRepeatPredicate.java:49)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8120)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:188)
	at reactor.core.publisher.MonoUsing$MonoUsingSubscriber.onNext(MonoUsing.java:229)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2148)
	at reactor.core.publisher.MonoUsing$MonoUsingSubscriber.request(MonoUsing.java:175)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onSubscribe(MonoFlatMapMany.java:134)
	at reactor.core.publisher.MonoUsing$MonoUsingSubscriber.onSubscribe(MonoUsing.java:205)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.MonoUsing.subscribe(MonoUsing.java:102)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8134)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:188)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:127)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)
	at reactor.core.publisher.MonoProcessor.onNext(MonoProcessor.java:317)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)
	at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:61)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4087)
	at reactor.core.publisher.MonoProcessor.add(MonoProcessor.java:457)
	at reactor.core.publisher.MonoProcessor.subscribe(MonoProcessor.java:370)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4087)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:202)
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:48)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:103)
	at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onNext(FluxDoOnEach.java:159)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:127)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)
	at reactor.core.publisher.FluxDelaySubscription$DelaySubscriptionMainSubscriber.onNext(FluxDelaySubscription.java:180)
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:89)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onNext(FluxTimeout.java:173)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:156)
	at com.azure.core.http.okhttp.OkHttpAsyncHttpClient$OkHttpCallback.onResponse(OkHttpAsyncHttpClient.java:171)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:133)
		at reactor.core.publisher.Mono.block(Mono.java:1687)
		at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:101)
		at com.azure.storage.blob.specialized.BlobClientBase.downloadToFileWithResponse(BlobClientBase.java:557)
		at com.azure.storage.file.datalake.DataLakeFileClient.lambda$readToFileWithResponse$1(DataLakeFileClient.java:487)
		at com.azure.storage.file.datalake.implementation.util.DataLakeImplUtils.returnOrConvertException(DataLakeImplUtils.java:36)
		at com.azure.storage.file.datalake.DataLakeFileClient.readToFileWithResponse(DataLakeFileClient.java:486)
		at com.informatica.prototypes.TestAdlsGen2Read.testReadToFileUsingPartialRange(TestAdlsGen2Read.java:301)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
		at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
		at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
		at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
		at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
		at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
		at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
		at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
		at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
		at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
		at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
		at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
		at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
		at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
		at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
		at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
		at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
		at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
		at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
		at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
		at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
```

**Comment by rickle-msft** [comment] 2020-05-11 15:48
Thank you, @rajeevsinghAD, for reporting this. Do you mind sharing the value of count that you passed in? Even though I imagine your blob is not larger than 9 exabytes...

@gapra-msft can you take a look?

**Comment by rajeevsinghAD** [comment] 2020-05-11 16:51
Hello @rickle-msft ,
My file size is 1015, I tried giving this whole value as count and also values in multiple of 128. I also tried with block size 128, which also did not work. During debug, I found out that on subsequent evaluation count value is being calculated as -1015 (see attached screenshot), which is why probably I am seeing this error.

Rajeev

![adlsgen2counterror1](https://user-images.githubusercontent.com/15330007/81587846-38e3ed00-93d5-11ea-848d-31160f209345.jpg)

**Comment by gapra-msft** [comment] 2020-05-13 19:47
Hi @rajeevsinghAD 

I tried to reproduce your issue with the dependencies you listed and had no success. Could I get more information about the issue? 

Specifically, what httpClient are you using? What is the timeout value that you're setting?

**Comment by rajeevsinghAD** [comment] 2020-05-18 08:37
Hi @gapra-msft,

I am using okhttp client and I am getting this error. However with nettyhttp client I dont get any error but I don't see the file downloaded either using the same API. 
I am setting timeout value as 300.

**Comment by gapra-msft** [comment] 2020-05-18 17:08
Hi @rajeevsinghAD 

This issue seems to be related to the okhttp client package if it works fine using netty http clients. 

@alzimmermsft Could you please take a look/forward this to whoever owns okhttp?

**Comment by gapra-msft** [comment] 2020-05-19 16:51
Hi @rajeevsinghAD Are you seeing this issue every time or just transiently?

**Comment by rajeevsinghAD** [comment] 2020-05-20 09:33
Hi @gapra-msft I see this issue all the time. Let me know if you need me to open a support ticket. we can do screenshare then and I can explain you the scenario.

**Comment by gapra-msft** [comment] 2020-06-05 15:44
Hi @rajeevsinghAD Sorry about the delay in getting back to you. It appears this is related to retry behavior so I only see the issue transiently. I will try to mock the error and see what might be happening.

**Comment by gapra-msft** [comment] 2020-06-08 17:57
Hi @rajeevsinghAD, Just to update you, I am able to consistently reproduce this issue now. I will investigate further and let you know if I progress any further.

**Comment by rickle-msft** [comment] 2020-06-18 22:04
@rajeevsinghAD I believe we have found a fix for this and will work on getting it merged into master

**Closed** 2020-06-23 16:39 UTC
Labels: Client, Data Lake Storage Gen2, Storage, customer-reported, question
