### ISSUE TITLE
[BUG] Cost-management group by muliple tags returns null values

### ISSUE THREAD

**Issue by Ramedlaw-knil** [Azure/azure-sdk-for-java#24285] opened 2021-09-23 12:10 UTC
**Describe the bug**
I have multiple tags which i place on all my resources (e.g. userid, projectid etc.). 
For my usecase i want to get the costs grouped by all my tags.
When i now request the usage grouped by these tags i receive only values for the first one and the others are set null.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
```
   String scope = "subscriptions/XXXX-XXX-XXXXXXX";

    Map<String, QueryAggregation> aggregateByTotalCost = Map.of("totalCost", new QueryAggregation()
        .withName("Cost")
        .withFunction(FunctionType.SUM));

    List<QueryGrouping> groupByTag = new ArrayList<>();
    groupByTag .add(new QueryGrouping()
            .withType(QueryColumnType.fromString("TagKey"))
            .withName("projectId"));
     groupByTag .add(new QueryGrouping()
            .withType(QueryColumnType.fromString("TagKey"))
            .withName("userId"));

    QueryDataset queryDataset = new QueryDataset()
        .withAggregation(
            aggregateByTotalCost)
        .withGrouping(
            groupByTag);

    QueryDefinition queryDefinition = new QueryDefinition()
        .withType(ExportType.ACTUAL_COST)
        .withTimeframe(TimeframeType.MONTH_TO_DATE)
        .withDataset(queryDataset);

    QueryResult usage = manager
        .queries()
        .usage(scope, queryDefinition);
```

**Expected behavior**
I expect that the i receive the cost/usage data grouped by all my defined tags.

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE: Intellij IDEA
 - Library/Libraries: com.azure.resourcemanager:azure-resourcemanager-costmanagement 1.0.0-beta.3 and com.azure:azure-identity 1.3.4
 - Java version: 8
 - Frameworks:Spring boot

**Additional context**
This also happens when i do my request with postman. It is possible that the azure Cost-Management API 
dose not support multiple tags.
Then i would need a workaround

postman request body:
```
{
    "type": "ActualCost",
    "dataSet": {
        "aggregation": {
            "totalCost": {
                "name": "Cost",
                "function": "Sum"
            }
        },
        "filter": { 
            "Tags": {
                "Name": "adpresourcetype",
                "Operator": "In",
                "Values": [ "ondemand" ]
            }
        },
        "grouping": [
            {
                "type": "TagKey",
                "name": "projectid"
            },
            {
                "type": "TagKey", 
                "name": "userid"
            }
        ],
        "granularity": "None"
    },
    "timeframe": "MonthToDate"
}
```

response body:
```
{
    "id": "subscriptions/XXXX_XXXX_XXXX/providers/Microsoft.CostManagement/query/XXXX_XXXX_XXXX",
    "name": "XXXX_XXXX_XXXX",
    "type": "Microsoft.CostManagement/query",
    "location": null,
    "sku": null,
    "eTag": null,
    "properties": {
        "nextLink": null,
        "columns": [
            {
                "name": "Cost",
                "type": "Number"
            },
            {
                "name": "TagKey",
                "type": "String"
            },
            {
                "name": "TagValue",
                "type": "String"
            },
            {
                "name": "Currency",
                "type": "String"
            }
        ],
        "rows": [
            [
                2.07598162E-07,
                "userid",
                null,
                "EUR"
            ],
            [
                0.001148328523571,
                "projectid",
                "1",
                "EUR"
            ],
            [
                0.001386685128425,
                "projectid",
                "2",
                "EUR"
            ],
            [
                0.006164051683191,
                "userid",
                null,
                "EUR"
            ],
            [
                1.29847054E-07,
                "projectid",
                "2",
                "EUR"
            ],
            [
                1.298470536E-06,
                "projectid",
                null,
                "EUR"
            ],
            [
                1.0809767209E-05,
                "projectid",
                "1",
                "EUR"
            ],
            [
                1.2238084799E-05,
                "userid",
                null,
                "EUR"
            ],
            [
                5.4877692473272477,
                "projectid",
                null,
                "EUR"
            ],
            [
                5.4877692473272477,
                "userid",
                null,
                "EUR"
            ],
            [
                13.686397307427212,
                "projectid",
                "1",
                "EUR"
            ],
            [
                13.860597627890197,
                "projectid",
                "2",
                "EUR"
            ],
            [
                24.803993800861953,
                "projectid",
                null,
                "EUR"
            ],
            [
                52.350988736179367,
                "userid",
                null,
                "EUR"
            ],
            [
                1.7815025964649649,
                "projectid",
                null,
                "EUR"
            ],
            [
                1.7815025964649649,
                "userid",
                null,
                "EUR"
            ]
        ]
    }
}
```

**Comment by joshfree** [comment] 2021-09-28 17:37
@weidongxu-microsoft could you please follow up with @Ramedlaw-knil on their question?

**Comment by weidongxu-microsoft** [comment] 2021-09-29 02:22
To cost management service, please investigate.

**Comment by handeeeadiguzel** [comment] 2021-09-29 23:24
We will investigate further and get back to you

**Comment by handeeeadiguzel** [comment] 2021-10-05 19:03
When Query API is called with group by TagKeys, the response will have both TagKey and TagValue (by design). And if you have null values for TagKeys it is expected to see null values in the response.

**Comment by ShilpiGautam** [comment] 2021-11-09 07:33
@Ramedlaw-knil pls let us know if above explanation does not help you. It has been more than a week since any response on the suggestion made by @handeeeadiguzel. Henc closing this trhead.

**Closed by ShilpiGautam** 2021-11-09 07:33 UTC
Labels: question, Service Attention, Mgmt, customer-reported, needs-team-attention, Cost Management - Query
