### ISSUE TITLE
File upload takes much longer time than expected

### ISSUE THREAD

**Issue by rakhmvi** [Azure/azure-sdk-for-java#18425] opened 2021-01-04 12:12 UTC
**Query/Question**
Hi, 
we are using algorithm (#18002) to upload to BlobStorage and for dev environment And we use General Purpose V2 with LRS (Blob Access Tier is "HOT") in dev environment. 
Now we faced another issue when file upload takes much longer time then expected, and for same now we are trying to investigate the issue.

Below observation/assumption we have in mind during investigate and need your comment/details on it:
1) As we use LRS - so 3 copies of same file in same Storage DC. So Is Azure SDK upload all 3 copies simultaneously or in sequence. And when the caller will get response of success? Means after upload done on all 3 places in LRS?
2) We read in doc that Azure Blob Storage use 256 MB max size of single blob for one file object. So SDK uses internal cache of file stream to size 256 MB and then starts writing on Block blob? 
3) If answer of 2nd is Yes then is there any ways to change by setting block blob size from 256 to smaller like 20-30 MB to save time of caching and then writing? (We use code of upload ref in #18002)
4) Also is there any stats you have documented mentioning average time of upload file with Azure SDK w.r.t. different different file size?

***Why is this not a Bug or a feature Request?***
Still not sure if the issue is in sdk, code implementation or in our dev/environment infrastructure.

**Setup (please complete the following information if applicable):**
 - OS: win10
 - IDE : eclipse
 - azure sdk 12.9

**Comment by gapra-msft** [comment] 2021-01-04 21:01
Hi @rakhmvi 

Thank you for your question. 

From the post you linked it looks like you are using BlockBlobOutputStream to upload data. 

1. I'm not too sure on the answer for this one as it seems more service related. The SDK issues a single request to the service and the service does what it needs to do to maintain consistency between the 3 copies and it responds back. 
2. Yes, I believe we do cache data within our buffered upload implementation to determine whether we want to upload the data as a single put or as multiple stage blocks. This value is based on ParallelTransferOptions.maxSingleUploadSize whose default value is 256MB.
3. Yes, you can change this value by modifying the ParallelTransferOptions.maxSingleUploadSize value. You can also change a few other options like ParallelTransferOptions.blockSizeLong to configure the block size of data you would like to upload in a single request so we can chunk the data appropriately for you.
4. There are no stats we have on hand for upload file times mainly because everyone's environment is different. We generally suggest that users test different configurations of ParallelTransferOptions to determine optimal values for their environment.

I hope that clarifies your questions.

**Comment by rakhmvi** [comment] 2021-01-07 15:26
HI @gapra-msft ,
thank you for the response.  Using your recommendations I configured ParallelTransferOptions for BlobOutPutStream: 
`		Long blockSize = 4L*com.azure.storage.common.implementation.Constants.MB;
		ParallelTransferOptions parallelTransferOptions = new ParallelTransferOptions();
		parallelTransferOptions.setMaxSingleUploadSizeLong(blockSize);
		parallelTransferOptions.setBlockSizeLong(blockSize);
		parallelTransferOptions.setMaxConcurrency(16);
		try(
				BlobOutputStream blobOutStream = 
  blobClient.getBlockBlobClient().getBlobOutputStream(parallelTransferOptions, null, null, null, null);
				BufferedInputStream bin = prepareEncryptStream(encryptionFlag, is, parametersMap);){
				int readBufferSize = 1024*4;
				java.nio.ByteBuffer byteBuffer = java.nio.ByteBuffer.allocate(readBufferSize);
				int len;
				while((len = bin.read(byteBuffer.array())) != -1) {
					blobOutStream.write(byteBuffer.array(), 0, len);
				//blobOutStream.flush();
				}
			}`
So the app is able to upload 500MB files now, but still fails for 1Gb files. I tried various combination of ParallelTransferOptions 
 values, but only one is success when `parallelTransferOptions.setMaxConcurrency(1)`. Obviously, in this case we ran into performance issue as the upload takes much time (>30 min). In other cases, the upload fails with: 
`java.io.IOException: com.azure.storage.blob.models.BlobStorageException: Status code 400, "?<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidBlockList</Code><Message>The specified block list is invalid.
RequestId:b2d52bf2-601e-006b-5644-e4883e000000
Time:2021-01-06T15:55:28.5726784Z</Message></Error>"
	at com.azure.storage.blob.specialized.BlobOutputStream$BlockBlobOutputStream.lambda$new$1(BlobOutputStream.java:231)
`
Now we are investigating the reasons. Unfortunately, I could not find any way to monitor upload process, partial uploading, etc. 1. Could you suggest me any tool or solution how I can monitor process of uploading data to Az Storage? 
2. Is it possible to upload stream sequentially without buffering?

**Comment by gapra-msft** [comment] 2021-01-08 18:41
Hi @rakhmvi 

You can use the ProgressReceiver on ParallelTransferOptions to log progress of the upload. 

As far as the invalid block list error goes, I'd need to investigate that. Let me reproduce your issue and get back to you with what I find.  

We don't have a convenient upload method that uploads without buffering currently. You could break up the data yourself and call BlockBlobClient.[stageBlock](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block) and BlockBlobClient.[commitBlockList](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block-list). Please refer to the REST API docs to learn more about that if you are interested.

**Comment by gapra-msft** [comment] 2021-03-17 16:54
Looks like this thread has been answered, closing for now. @rakhmvi Please feel free to open another issue or reopen this issue if you hit any further problems, and we are happy to help

**Closed by gapra-msft** 2021-03-17 16:54 UTC
Labels: Client, Storage, customer-reported, question
