### ISSUE TITLE
Virtual machine adapter operation to increase the data disk

### ISSUE THREAD

**Issue by rogertong** [Azure/azure-sdk-for-java#1763] opened 2017-06-16 01:35 UTC
The following way we can specify the disk type. The current test result is that we can successfully add the default type(STANDARD_LRS) of data disk, however can't add the PREMIUM_LRS type.

```
String client = "***********************";
        String tenant = "*****************";
        String key = "************";
        ApplicationTokenCredentials token = new ApplicationTokenCredentials(client, tenant, key, AzureEnvironment.AZURE);
        Azure azure = Azure.authenticate(token).withSubscription("**********************");
        VirtualMachine virtualMachine=azure.virtualMachines().getById("/subscriptions/3959936e-aa79-461a-becd-2da372325dd2/resourceGroups/roger/providers/Microsoft.Compute/virtualMachines/rogerVM0616");
        virtualMachine.update()
                .withDataDiskDefaultStorageAccountType(StorageAccountTypes.PREMIUM_LRS)
                .defineUnmanagedDataDisk("newDatadisk1")
                .withNewVhd(10)
                .withCaching(CachingTypes.READ_WRITE)
                .attach()
                .apply();
```

**Comment by liqiang-fit2cloud** [comment] 2017-06-16 07:45
The key is valid, thanks.

**Comment by anuchandy** [comment] 2017-06-16 15:18
To add unmanaged data disk to an existing virtual machine and to use specific storage account, use the following code. This works only for global azure now. We have a PR opened fixing this. This will be available in the next release. This sample code creates a premium storage account and use it as target for the unmanaged data disk via `storeAt()`.

```java
 StorageAccount storageAccount = storageManager.storageAccounts()
            .define(SA_NAME)
            .withRegion(Region.ASIA_EAST)
            .withNewResourceGroup(RG_NAME)
            .withSku(SkuName.PREMIUM_LRS)
            .create();

vm.update()
        .defineUnmanagedDataDisk("disk3")
            .withNewVhd(100)
            .storeAt(storageAccount.name(), "vhds", "disk3-zzdrtui.vhd")
            .attach()
        .apply();

```

**Comment by rogertong** [comment] 2017-06-19 04:27
.withDataDiskDefaultStorageAccountType(StorageAccountTypes.PREMIUM_LRS)

Is this a bug? Will it be fixed in the next release for both global and other version? or will this way be replaced by storeAt() way for ever?

**Comment by anuchandy** [comment] 2017-06-19 14:58
The behavior of `withDataDiskDefaultStorageAccountType` is not a bug, this setting in the `update` chain get applied only if the data disk is based on the managed disk. 

It seems you are using the unmanaged disk, so `storeAt` is the correct way of specifying unmanaged disk target (Standard vs Premium account), but as I mentioned above PR with fix for NON-Global azure is opened and this will be available in the next release (1.2.0).

**Comment by anuchandy** [comment] 2017-07-26 16:03
Fix for resolving endpoint based environment is merged, will be available in 1.2 release.

**Comment by anuchandy** [comment] 2017-08-31 22:22
Feature is available as of v1.2 hence closing this.

**Closed by anuchandy** 2017-08-31 22:22 UTC
