### ISSUE TITLE
[BUG] Issue with uploading a file in smaller chunks with uploadWitResponse with a bunch of stageBlocks followed by a commitBlockList.

### ISSUE THREAD

**Issue by kirankumar994** [Azure/azure-sdk-for-java#37801] opened 2023-11-23 12:58 UTC
**Describe the bug**
I am trying to upload a file in smaller chunks. The file is getting transferred in smaller chunks and it is being uploaded. However, it creates a new version with 36B for every file after uploading successfully. Please find the below code snippet and respective screenshot of the sop's. The file sizes I tried with 1MB, 5MB, 10MB and so on.. Please have a look at the issue and thanks in advance. 

***Code Snippet***
`public Mono<Document> addNewDocument(Mono<FilePart> file, Document document) {
        if (LOG.isDebugEnabled()) LOG.debug("addNewDocument: Uploading new document ===>" + document);

        BlobContainerAsyncClient blobContainerAsyncClient = blobServiceAsyncClient.getBlobContainerAsyncClient(document.getDocumentLibraryId());
        BlobAsyncClient blobAsyncClient = blobContainerAsyncClient.getBlobAsyncClient(document.getDocumentName());

        return handleFileUpload(file)
                .collectList()
                .flatMap(data -> {
                    Flux<ByteBuffer> combinedData = Flux.fromIterable(data);
                    long blockSize = 1 * Constants.KB;
                    ParallelTransferOptions parallelTransferOptions = new ParallelTransferOptions()
                            .setBlockSizeLong(blockSize)
                            .setMaxConcurrency(1)
                            .setProgressListener(bytesTransferred ->
                                    System.out.printf("Upload progress: %s bytes sent", bytesTransferred));

                    return blobAsyncClient.uploadWithResponse(combinedData, parallelTransferOptions, null, document.getMetadata(), null, null)
                            .flatMap(response -> {
                                BlockBlobAsyncClient blockBlobAsyncClient = blobAsyncClient.getBlockBlobAsyncClient();
                                String base64BlockID = Base64.getEncoder().encodeToString("base64BlockID".getBytes());
                                return blockBlobAsyncClient.stageBlock(base64BlockID, BinaryData.fromObject(combinedData))
                                        .then(blockBlobAsyncClient.commitBlockListWithResponse(new BlockBlobCommitBlockListOptions(Collections.singletonList(base64BlockID))
                                                .setMetadata(document.getMetadata())));
                            });
                })
                .then(Mono.just(document));

    }

    public Flux<ByteBuffer> handleFileUpload(Mono<FilePart> fileMono) {
        return fileMono
                .flatMapMany(filePart -> filePart.content()
                        .map(DataBuffer::asByteBuffer)
                        .doOnNext(byteBuffer -> System.out.println("Emitted ByteBuffer size: " + byteBuffer.remaining()))
                        .doOnDiscard(ByteBuffer.class, byteBuffer -> System.out.println("Discarded ByteBuffer"))
                );
    }`

**Expected behavior**
The file should be uploaded in smaller chunks to the container as I may have larger files too. 

**Screenshots**
![Screenshot from 2023-11-23 18-25-20](https://github.com/Azure/azure-sdk-for-java/assets/19862708/f257a0cc-6d20-40ee-8779-71a5c75b2611)

![Screenshot from 2023-11-23 18-27-38](https://github.com/Azure/azure-sdk-for-java/assets/19862708/7f74f8dd-9708-43a4-b79b-1738449ca87c)
![Screenshot from 2023-11-23 18-27-26](https://github.com/Azure/azure-sdk-for-java/assets/19862708/578e8103-99be-4f26-9871-56bd22bae8df)

My handleFileUpload is emitting 
....Emitted ByteBuffer size: 1024
Emitted ByteBuffer size: 1024
Emitted ByteBuffer size: 1024
Emitted ByteBuffer size: 1024
Emitted ByteBuffer size: 1024
Emitted ByteBuffer size: 1024
Emitted ByteBuffer size: 1024
Emitted ByteBuffer size: 1024
Emitted ByteBuffer size: 1024
Emitted ByteBuffer size: 1024
Emitted ByteBuffer size: 1024
Emitted ByteBuffer size: 1024
Emitted ByteBuffer size: 1024
Emitted ByteBuffer size: 294

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: [e.g. 8] 
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by joshfree** [comment] 2023-11-27 15:58
@ibrahimrabab @alzimmermsft could you please follow up?

**Comment by alzimmermsft** [comment] 2023-11-27 19:02
Thanks for filing this issue @kirankumar994.

I believe the issue in this code:

```java
return blobAsyncClient.uploadWithResponse(combinedData, parallelTransferOptions, null, document.getMetadata(), null, null)
                        .flatMap(response -> {
                            BlockBlobAsyncClient blockBlobAsyncClient = blobAsyncClient.getBlockBlobAsyncClient();
                            String base64BlockID = Base64.getEncoder().encodeToString("base64BlockID".getBytes());
                            return blockBlobAsyncClient.stageBlock(base64BlockID, BinaryData.fromObject(combinedData))
                                    .then(blockBlobAsyncClient.commitBlockListWithResponse(new BlockBlobCommitBlockListOptions(Collections.singletonList(base64BlockID))
                                            .setMetadata(document.getMetadata())));
                        });
```

`blobAsyncClient.uploadWithResponse` will upload the entire `combinedData` as a block blob. But the code then stages another block to that block blob and commits it, which will overwrite the previously uploaded `combinedData`. Which is what the portal is showing where there are two versions of the blob, one of the file size you're uploading and another that's always 36B.

**Comment by ibrahimrabab** [comment] 2023-12-11 23:49
Hi @kirankumar994 
Were you able to take a look at the response from @alzimmermsft and figure out your issue? Let us know if you have any more questions, or we can go ahead and close the issue.

**Comment by kirankumar994** [comment] 2023-12-12 14:59
Hi @alzimmermsft, & @ibrahimrabab,
I figured out the issue myself and refactored the code to make it work. But, I would like you to have a quick look at the code below and let me know if it looks good for upload streaming. I can then be more confident on the upload streaming part as I may have large to upload parallelly. Thanks in advance.

`public Mono<Document> handleFileUpload(Mono<FilePart> file, Document document, Map<String, String> tags, Map<String, String> metadata) {
        BlobContainerAsyncClient blobContainerAsyncClient = blobServiceAsyncClient.getBlobContainerAsyncClient(document.getDocumentLibraryId());
        BlobAsyncClient blobAsyncClient = blobContainerAsyncClient.getBlobAsyncClient(document.getDocumentName());
        BlockBlobAsyncClient blockBlobAsyncClient = blobAsyncClient.getBlockBlobAsyncClient();

        return file
                .flatMapMany(FilePart::content)
                .flatMapSequential(dataBuffer -> {

                    // Convert DataBuffer to ByteBuffer
                    ByteBuffer byteBuffer = dataBuffer.asByteBuffer();
                    // Generate random UID for each block (for each chunk)
                    // Staging each chunk as a block on azure
                    String blockID = Base64.getEncoder().encodeToString(UUID.randomUUID().toString().getBytes(StandardCharsets.UTF_8));
                    return blockBlobAsyncClient.stageBlock(blockID, BinaryData.fromByteBuffer(byteBuffer))
                            .thenReturn(blockID);
                })
                .collectList() // Collect all sequential blocks to commit (Preparing the whole blob)
                .flatMap(blockIds -> {
                    return blockBlobAsyncClient
                            .commitBlockListWithResponse(new BlockBlobCommitBlockListOptions(blockIds)
                                    .setMetadata(metadata)
                                    .setTags(tags)); // Commits the blob with all blocks (smaller chunks)
                })
                .then(Mono.just(document));
    }`

**Comment by ibrahimrabab** [comment] 2023-12-12 21:49
@kirankumar994 your code snippet looks good to me! Good to hear the issue is resolved, let us know if you have any other questions :)

**Closed by ibrahimrabab** 2023-12-12 21:49 UTC
Labels: question, Storage, Client, customer-reported, needs-team-attention
