### ISSUE TITLE
[BUG] Track 2 SB Send Messages Sync API is slow. Investigate performance optimization.

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-java#16128] opened 2020-10-10 00:51 UTC
**Describe the bug**
Track 2 SB Send Messages Sync API is slow. Reactor implementation can potentially be optimized. 
Investigate optimizations for this API.

**To Reproduce**
Run the sync send messages performance test to analyze the performance. (I can do a screen share)

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : IntelliJ
 - Version of the Library used: beta.6

**Comment by anuchandy** [comment] 2022-04-26 03:47
Many reliability and perf improvements have happened since Oct-2020.  The performance of the amqp-core ReactorSender is on par with the T1 sender; the send specific testing done as part of this git-ticket https://github.com/Azure/azure-sdk-for-java/issues/26372 confirmed it.

Closing this now based on recent data.

**Closed by anuchandy** 2022-04-26 03:47 UTC
Labels: Service Bus, Client, pillar-performance
