### ISSUE TITLE
OS Disk size of a VM is always 0

### ISSUE THREAD

**Issue by tmonning** [Azure/azure-sdk-for-java#1285] opened 2016-11-21 13:10 UTC
Hi,

I'm trying to retrieve the OS disk size of a Virtual Machine. Therefore I'm using `com.microsoft.azure.management.compute.VirtualMachine.osDiskSize()`. But that always returns `0`. 
Also `com.microsoft.azure.management.compute.VirtualMachine.storageProfile().osDisk().diskSizeGB()` always returns `null`.

My current workaround is to get there via storage meta data:
```
CloudPageBlob pageBlobReference = containerReference.getPageBlobReference(blobRefId);

// Update meta data
pageBlobReference.downloadAttributes();

// Retrieve meta data
HashMap<String, String> metadata = pageBlobReference.getMetadata();
Lun osDisk = new Lun();
osDisk.name = metadata.get("MicrosoftAzureCompute_DiskName");
osDisk.uuid = metadata.get("MicrosoftAzureCompute_DiskId");
osDisk.size = pageBlobReference.getProperties().getLength() / 1_000_000_000L * 1024L * 1024L * 1024L;
```
But the workaround takes a few seconds for each call. Is the proper lookup just not implemented, yet? Or is it on purpose that those methods do not return any data?

**Comment by anuchandy** [comment] 2016-11-22 00:54
@tmonning this is a known limitation, where compute GET VM API won't return the OS disk size if the virtual machine is created from a platform image. I am not aware of a solution other than the work around you use. I will check with compute team about their plan to fix this and update here.

**Comment by ezhil45** [comment] 2017-01-20 11:09
@anuchandy We are facing same issue and wanted to check if there is any updates on this.

**Comment by anuchandy** [comment] 2017-02-21 03:34
It seems this issue is fixed for virtual machine based on managed disks, limitation still exists for storage account based disks.

**Comment by brokenjpl** [comment] 2017-04-17 17:35
I also have the same issue. Used the above for a workaround.

VM disk size is always zero for unmanaged OS disks when using the following command:
`com.microsoft.azure.management.compute.VirtualMachine.osDiskSize()`

**Comment by anuchandy** [comment] 2017-10-06 06:07
CRP is aware of this issue, feature owner has been tagged in the similar issue https://github.com/Azure/azure-sdk-for-java/issues/1643#issuecomment-319749937 `VM payload contains NULL as value for the OS Disk size.`

**Comment by martinsawicki** [comment] 2017-10-09 22:37
closing as duplicate of https://github.com/Azure/azure-sdk-for-java/issues/1643

**Closed by martinsawicki** 2017-10-09 22:37 UTC
