### ISSUE TITLE
[QUERY] java.io.IOException: Alias name [cert-name] does not identify a key entry

### ISSUE THREAD

**Issue by crichey** [Azure/azure-sdk-for-java#21213] opened 2021-05-06 19:46 UTC
**Query/Question**
I'm using the keyvalut-certificates library (com.azure.spring:azure-spring-boot-starter-keyvault-certificates:3.0.0-beta.6) to enable TLS support for my sprint-boot application with the default embedded Tomcat server. I am providing the following in the application.properties as per the documentation at [:](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault-certificates)
```
server.ssl.key-alias=schizogenously-cert
server.ssl.key-store-type=AzureKeyVault
server.ssl.trust-store-type=AzureKeyVault
azure.keyvault.uri=MY_URI
```

When deploying I get this stacktrace and the server won't start.
```
org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat server
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181)
        at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54)
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155)
        at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123)
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:940)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:591)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
        at com.factgem.gem.MainApplication.main(MainApplication.java:25)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
Caused by: org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat server
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:229)
        at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:43)
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178)
        ... 23 common frames omitted
Caused by: java.lang.IllegalArgumentException: standardService.connector.startFailed
        at org.apache.catalina.core.StandardService.addConnector(StandardService.java:244)
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.addPreviouslyRemovedConnectors(TomcatWebServer.java:282)
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:213)
        ... 25 common frames omitted
Caused by: org.apache.catalina.LifecycleException: Protocol handler start failed
        at org.apache.catalina.connector.Connector.startInternal(Connector.java:1067)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardService.addConnector(StandardService.java:240)
        ... 27 common frames omitted
Caused by: java.lang.IllegalArgumentException: Alias name [schizogenously-cert] does not identify a key entry
        at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:99)
        at org.apache.tomcat.util.net.AbstractJsseEndpoint.initialiseSsl(AbstractJsseEndpoint.java:71)
        at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:216)
        at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1159)
        at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:1245)
        at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:603)
        at org.apache.catalina.connector.Connector.startInternal(Connector.java:1064)
        ... 29 common frames omitted
Caused by: java.io.IOException: Alias name [schizogenously-cert] does not identify a key entry
        at org.apache.tomcat.util.net.SSLUtilBase.getKeyManagers(SSLUtilBase.java:336)
        at org.apache.tomcat.util.net.SSLUtilBase.createSSLContext(SSLUtilBase.java:246)
        at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:97)
        ... 35 common frames omitted
```

***Why is this not a Bug or a feature Request?***
AS this is a beta release I don't know if this is a bug or not.

**Setup (please complete the following information if applicable):**
 - Version of the Library used: 3.0.0-beta.6

**Comment by joshfree** [comment] 2021-05-06 20:38
Thanks for reporting this @crichey.  @stliu could you please take a look?

/cc @vcolin7

**Comment by chenrujun** [comment] 2021-05-07 08:58
@crichey , thanks for reaching out.

Please check these:

1. Make sure properties like `azure.keyvault.tenant-id`, `azure.keyvault.client-id`, `azure.keyvault.client-secret`.
2. Make sure cert `schizogenously-cert` created successfully in Azure Portal.
3. Make sure the client-id can access target Key Vault.

Refs: https://github.com/Azure/azure-sdk-for-java/tree/azure-spring-boot-starter-keyvault-certificates_3.0.0-beta.6/sdk/spring/azure-spring-boot-starter-keyvault-certificates#using-a-client-id-and-client-secret

**Comment by chenrujun** [comment] 2021-05-25 00:46
Hi, @crichey , is your problem solved? Which version of spring-boot are you using?

**Comment by chenrujun** [comment] 2021-05-26 01:03
Hi, @crichey .

> I haven’t tried since I reported the bug as I was forced to find a new solution.

What's the new solution?

**Comment by crichey** [comment] 2021-05-26 01:13
I’m not using the AzureKeystore anymore. 😉

**Comment by chenrujun** [comment] 2021-05-26 09:12
Closing this issue because we can not reproduce customer's problem. And customer not use AzureKeystore  anymore.

**Closed by chenrujun** 2021-05-26 09:12 UTC
Labels: Client, azure-spring, azure-spring-keyvault, customer-reported, question
