### ISSUE TITLE
Update "Spring Boot Starters for Azure" to serve as complete list of starters

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21499] opened 2021-05-14 09:41 UTC
As a customer advocate, I look at the article Spring Boot Starters for Azure as the exhaustive list of Spring Boot Starters for Azure.  If it is not mentioned in this page, it doesn't exist.  Assuming my understanding of the purpose of that article, it seems to me some existing starters are missing.  Looking at this change made by @yiliuTo  I see the following list of starters:
azure-keyvault-secrets-spring-boot-starter
azure-active-directory-spring-boot-starter
azure-active-directory-b2c-spring-boot-starter
azure-cosmosdb-spring-boot-starter
spring-data-gremlin-boot-starter
azure-servicebus-jms-spring-boot-starter
azure-spring-boot-metrics-starter
azure-spring-boot-starter-storage

#21444

**Comment by seanli1988** [comment] 2021-08-06 09:07
duplicate of https://app.zenhub.com/workspaces/azure-spring-starters-5f067afb1fdee5002af58493/issues/azure/azure-sdk-for-java/21444

**Closed by seanli1988** 2021-08-06 09:07 UTC
Labels: Client, azure-spring, azure-spring-docs
