### ISSUE TITLE
[BUG] Defining a POJO with BigDecimal fields causes runtime error when trying to persist in CosmosDB

### ISSUE THREAD

**Issue by rharish1983** [Azure/azure-sdk-for-java#28341] opened 2022-04-15 17:39 UTC
**Describe the bug**
Defining a POJO with BigDecimal fields causes runtime error when trying to persist in CosmosDB

***Exception or Stack Trace***
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.math.BigInteger java.math.BigDecimal.intVal accessible: module java.base does not "opens java.math" to unnamed module @48c76607
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354) ~[na:na]
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[na:na]
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178) ~[na:na]
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172) ~[na:na]
	at org.springframework.util.ReflectionUtils.makeAccessible(ReflectionUtils.java:791) ~[spring-core-5.3.18.jar:5.3.18]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:550) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:714) ~[spring-core-5.3.18.jar:5.3.18]
	at org.springframework.data.mapping.context.AbstractMappingContext.doAddPersistentEntity(AbstractMappingContext.java:424) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:381) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.lambda$createAndRegisterProperty$3(AbstractMappingContext.java:605) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.createAndRegisterProperty(AbstractMappingContext.java:602) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:556) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:714) ~[spring-core-5.3.18.jar:5.3.18]
	at org.springframework.data.mapping.context.AbstractMappingContext.doAddPersistentEntity(AbstractMappingContext.java:424) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:381) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.lambda$createAndRegisterProperty$3(AbstractMappingContext.java:605) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.createAndRegisterProperty(AbstractMappingContext.java:602) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:556) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:714) ~[spring-core-5.3.18.jar:5.3.18]
	at org.springframework.data.mapping.context.AbstractMappingContext.doAddPersistentEntity(AbstractMappingContext.java:424) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:381) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.lambda$createAndRegisterProperty$3(AbstractMappingContext.java:605) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.createAndRegisterProperty(AbstractMappingContext.java:602) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:556) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:714) ~[spring-core-5.3.18.jar:5.3.18]
	at org.springframework.data.mapping.context.AbstractMappingContext.doAddPersistentEntity(AbstractMappingContext.java:424) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:381) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at 

**To Reproduce**
Define a persistence POJO with BigDecimal fields and save to CosmosDB

***Code Snippet***
public class JpaEntity {
	private BigDecimal field1;
}

**Expected behavior**
Field is accepted and saved into Cosmos

**Screenshots**

**Setup (please complete the following information):**
 - OS: MacOS
 - IDE: STS
 - Library/Libraries: com.azure:azure-spring-data-cosmos:3.19.0, 3.19.1
 - Java version: Java version 11
 - App Server/Environment: Tomcat (embedded with SpringBoot)
 - Frameworks: SpringBoot (version 2.6.6)

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by kushagraThapar** [comment] 2022-04-18 17:58
@aayush3011  - can you please take a look at this issue?

**Comment by rharish1983** [comment] 2022-05-02 14:18
Any thoughts when this will be looked at for a resolution ?

**Comment by rharish1983** [comment] 2022-05-05 16:41
@aayush3011 @kushagraThapar - Is this actively being investigated ?

**Comment by aayush3011** [comment] 2022-05-05 18:45
I created a POJO with BigDecimal bigDecimalField, and I am able to persist in the CosmosDB. Here is the screenshot depicting that. 

<img width="1186" alt="Screen Shot 2022-05-05 at 11 43 34 AM" src="https://user-images.githubusercontent.com/14010132/167001602-42e5ec72-b22a-4ec2-b4bc-59184164a8e3.png">

**Comment by rharish1983** [comment] 2022-05-05 19:24
Are you trying on Java version 11 ? Is there anything specific you did to set the scale to 2 decimals while persisting ?

**Comment by aayush3011** [comment] 2022-05-06 15:38
Yes, I am using Java version 11. I persisted with the BigDecimal as below.

BigDecimal bigDecimalField = new BigDecimal("0.03")

**Comment by rharish1983** [comment] 2022-05-06 21:49
I keep running into the error whenever specifying the BigDecimal field. Would there be anything more required from me ? 

`Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.math.BigInteger java.math.BigDecimal.intVal accessible: module java.base does not "opens java.math" to unnamed module @f14a7d4
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354) ~[na:na]
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[na:na]
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178) ~[na:na]
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172) ~[na:na]
	at org.springframework.util.ReflectionUtils.makeAccessible(ReflectionUtils.java:791) ~[spring-core-5.3.18.jar:5.3.18]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:550) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:714) ~[spring-core-5.3.18.jar:5.3.18]
	at org.springframework.data.mapping.context.AbstractMappingContext.doAddPersistentEntity(AbstractMappingContext.java:424) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:381) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.lambda$createAndRegisterProperty$3(AbstractMappingContext.java:605) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.createAndRegisterProperty(AbstractMappingContext.java:602) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:556) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:714) ~[spring-core-5.3.18.jar:5.3.18]
	at org.springframework.data.mapping.context.AbstractMappingContext.doAddPersistentEntity(AbstractMappingContext.java:424) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:381) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.lambda$createAndRegisterProperty$3(AbstractMappingContext.java:605) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.createAndRegisterProperty(AbstractMappingContext.java:602) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:556) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:714) ~[spring-core-5.3.18.jar:5.3.18]
	at org.springframework.data.mapping.context.AbstractMappingContext.doAddPersistentEntity(AbstractMappingContext.java:424) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:381) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.lambda$createAndRegisterProperty$3(AbstractMappingContext.java:605) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.createAndRegisterProperty(AbstractMappingContext.java:602) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:556) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:714) ~[spring-core-5.3.18.jar:5.3.18]
	at org.springframework.data.mapping.context.AbstractMappingContext.doAddPersistentEntity(AbstractMappingContext.java:424) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:381) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:266) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:209) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:92) ~[spring-data-commons-2.6.3.jar:2.6.3]
	at com.azure.spring.data.cosmos.core.convert.MappingCosmosConverter.writeJsonNode(MappingCosmosConverter.java:121) ~[azure-spring-data-cosmos-3.19.0.jar:3.19.0]
	at com.azure.spring.data.cosmos.core.CosmosTemplate.insert(CosmosTemplate.java:202) ~[azure-spring-data-cosmos-3.19.0.jar:3.19.0]
	at com.azure.spring.data.cosmos.core.CosmosTemplate.insert(CosmosTemplate.java:181) ~[azure-spring-data-cosmos-3.19.0.jar:3.19.0]
	at com.azure.spring.data.cosmos.repository.support.SimpleCosmosRepository.save(SimpleCosmosRepository.java:94) ~[azure-spring-data-cosmos-3.19.0.jar:3.19.0]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]`

**Comment by rharish1983** [comment] 2022-05-06 22:37
Also just noticed that the Java version on application startup indicates 17. Apologies for indicating it as 11. 

Starting Application using Java 17 on ${hostname} with PID

**Comment by rharish1983** [comment] 2022-05-12 23:21
Have you been able to reproduce the issue ?

**Comment by aayush3011** [comment] 2022-05-17 16:28
Hey @rharish1983, at present we don't support JDK 17. I won't be able to reproduce the issue, we will soon start supporting it, but there is no ETA on that as of now. 

To resolve the issue that you are facing right now, you can use JDK 11 for your application. As It's shown in the above screenshots attached, JDK 11 is working correctly when trying to persist BigDecimal to CosmosDB.

**Comment by rharish1983** [comment] 2022-05-18 21:41
Thanks for the heads up @aayush3011. Let me downgrade my JDK and check if it works fine and will circle back.

**Comment by aayush3011** [comment] 2022-06-16 15:37
Provided the solution above, closing this issue.

**Closed by aayush3011** 2022-06-16 15:37 UTC
Labels: bug, Cosmos, Client, customer-reported, azure-spring-cosmos

**Comment by KnyGoo** [comment] 2022-08-02 13:17
@aayush3011 
When will JDK17 be supported? I'm also facing this issue since upgrading to Java 17...

**Comment by monarkkoshta** [comment] 2023-03-13 06:32
Hi @aayush3011 
Is there any updates when JDK17 will be supported ?
