### ISSUE TITLE
[BUG] NotificationHubs.getById is not working.

### ISSUE THREAD

**Issue by changbaebang** [Azure/azure-sdk-for-java#25122] opened 2021-11-01 09:46 UTC
**Describe the bug**
NotificationHubs.getById make exception.

***Exception or Stack Trace***
Add the exception log and stack trace if available
com.azure.core.exception.HttpResponseException: Deserialization Failed

**To Reproduce & Code Snippet**

Run below codes
```
AzureProfile profile = new AzureProfile("....", "...", AzureEnvironment.AZURE);
        TokenCredential credential = new DefaultAzureCredentialBuilder()
                .authorityHost(profile.getEnvironment().getActiveDirectoryEndpoint())
                .build();
        
        NotificationHubsManager manager = NotificationHubsManager.authenticate(credential, profile);
        NotificationHubs notificationHubs = manager.notificationHubs();
        //NotificationHubResource byId = notificationHubs.getById("/subscriptions/.../resourceGroups/.../providers/Microsoft.NotificationHubs/namespaces/.../notificationHubs/...-01");
        notificationHubs.list("...", "..."); // no exception
        
        NotificationHubResource byId = notificationHubs.getById("/subscriptions/.../resourceGroups/.../providers/Microsoft.NotificationHubs/namespaces/.../notificationHubs/...-01");
```

``` pom.xml - dependancy
<dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-core</artifactId>
      <version>1.21.0</version>
    </dependency>
    <dependency>
      <groupId>com.azure.resourcemanager</groupId>
      <artifactId>azure-resourcemanager-notificationhubs</artifactId>
      <version>1.0.0-beta.1</version>
    </dependency>
    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-identity</artifactId>
      <version>1.3.7</version>
    </dependency>
    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-core-http-netty</artifactId>
      <version>1.11.1</version>
    </dependency>
```

**Trace**
```
Exception in thread "main" com.azure.core.exception.HttpResponseException: Deserialization Failed.
        at com.azure.core.implementation.serializer.HttpResponseBodyDecoder.lambda$decodeByteArray$1(HttpResponseBodyDecoder.java:114)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
        at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:110)
        at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
        at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:143)
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
        at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
        at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onNext(FluxDoOnEach.java:173)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:284)
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:187)
        at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
        at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:174)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
        at reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2664)
        at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:180)
        at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:260)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:150)
        at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:145)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:150)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1817)
        at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:159)
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:213)
        at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:269)
        at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:400)
        at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:419)
        at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:473)
        at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:684)
        at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)  
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)  
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)    
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)  
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)  
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)    
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1372)
        at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1246)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1286)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) 
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)  
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)  
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)    
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)  
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)  
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)     
                at reactor.core.publisher.Mono.block(Mono.java:1706)
                at com.azure.resourcemanager.notificationhubs.implementation.NotificationHubsClientImpl.getWithResponse(NotificationHubsClientImpl.java:1241)
                at com.azure.resourcemanager.notificationhubs.implementation.NotificationHubsImpl.getWithResponse(NotificationHubsImpl.java:95)
                at com.azure.resourcemanager.notificationhubs.implementation.NotificationHubsImpl.getById(NotificationHubsImpl.java:386)
                at com.mkyong.hashing.App.main(App.java:334)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: **Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)**
 at [Source: (byte[])"{"id":"/subscriptions/.../resourceGroups/.../providers/Microsoft.NotificationHubs/namespaces/.../notificationHubs/...-01","name":"...-01","type":"Microsoft.NotificationHubs/namespaces/notificationHubs","location":"East Asia","tags":{},"properties":{"registrationTtl":"10675199.02:48:05.4775807","authorizationRules":[]}}"; line: 1, column: 381] (through reference chain: com.azure.resourcemanager.notificationhubs.fluent.models.NotificationHubResourceInner["properties.name"])
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)        
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1601)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1375)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1280)
        at com.fasterxml.jackson.databind.DeserializationContext.extractScalarFromObject(DeserializationContext.java:872)
        at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:62)       
        at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)       
        at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)       
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
```

**Setup (please complete the following information):**
 - OS: Windows 11
 - IDE: Visual Code
 - Library/Libraries: 
 - Java version: 8 
 - App Server/Environment: java
 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [V ] Bug Description Added
- [ V] Repro Steps Added
- [ V] Setup information Added

**Comment by joshfree** [comment] 2021-11-01 16:55
@weidongxu-microsoft could you please assist with this `Notification Hubs` issue?

**Comment by weidongxu-microsoft** [comment] 2021-11-02 03:24
@XiaofeiCao 
Could you take a look? My guess is the response from service is not same as their REST API spec.

**Comment by XiaofeiCao** [comment] 2021-11-02 03:26
Ok, I'll take a look.

**Comment by changbaebang** [comment] 2021-11-02 06:25
`notificationHubs.get("...", "...", "...");` has same issue -  Deserialization Failed

```
Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (byte[])"{"id":"/subscriptions/.../resourceGroups/nhbangbang/providers/Microsoft.NotificationHubs/namespaces/.../notificationHubs/...","name":"...-01","type":"Microsoft.NotificationHubs/namespaces/notificationHubs","location":"East Asia","tags":{},"properties":{"registrationTtl":"10675199.02:48:05.4775807","authorizationRules":[]}}"; line: 1, column: 381] (through reference chain: com.azure.resourcemanager.notificationhubs.fluent.models.NotificationHubResourceInner["properties.name"])
```

with REST API, the response is like below.
https://docs.microsoft.com/en-us/rest/api/notificationhubs/notification-hubs/get

{
  "id": "/subscriptions/.../resourceGroups/...providers/Microsoft.NotificationHubs/namespaces/.../notificationHubs/...",
  "name": "...",
  "type": "Microsoft.NotificationHubs/namespaces/notificationHubs",
  "location": "East Asia",
  "tags": {},
  "properties": {
    "registrationTtl": "10675199.02:48:05.4775807",
    "authorizationRules": []
  }
}

**Comment by XiaofeiCao** [comment] 2021-11-02 09:22
Successfully reproduced the bug. It's related to the JsonFlattern in azure-core. 
``` 
NotificationHubResourceInner inner = JacksonAdapter.createDefaultSerializerAdapter().deserialize(
"{\"id\":\"/subscriptions/.../resourceGroups/nhbangbang/providers/Microsoft.NotificationHubs/namespaces/.../notificationHubs/...\",\"name\":\"...-01\",\"type\":\"Microsoft.NotificationHubs/namespaces/notificationHubs\",\"location\":\"East Asia\",\"tags\":{},\"properties\":{\"registrationTtl\":\"10675199.02:48:05.4775807\",\"authorizationRules\":[]}}"
, NotificationHubResourceInner.class
, SerializerEncoding.JSON);
```
Will try to release a fix tomorrow.

**Comment by XiaofeiCao** [comment] 2021-11-03 05:40
Released a new version to fix the bug
`azure-resourcemanager-notificationhubs:1.0.0-beta.2`
``` pom.xml - dependancy
<dependency>
  <groupId>com.azure.resourcemanager</groupId>
  <artifactId>azure-resourcemanager-notificationhubs</artifactId>
  <version>1.0.0-beta.2</version>
</dependency>
```
Please let me know if this new version solved your problem @changbaebang

**Comment by weidongxu-microsoft** [comment] 2021-11-03 05:50
Root cause is still the `JsonFlatten` in azure-core (actually, regression). But new releases of management SDK no longer rely on the `JsonFlatten`.

**Comment by XiaofeiCao** [comment] 2021-11-03 05:53
Reported no exception thrown, closing this issue.

**Closed** 2021-11-03 05:54 UTC
Labels: question, Notification Hub, Mgmt, customer-reported

**Comment by changbaebang** [comment] 2021-11-03 05:57
The exception has gone.
I could get `com.azure.resourcemanager.notificationhubs.implementation.NotificationHubResourceImpl@....` with get or getById.

Many Thanks!!! @XiaofeiCao

**Comment by XiaofeiCao** [comment] 2021-11-03 06:24
Sure! BTW thanks for the clear expression of the issue, helps a lot.
