### ISSUE TITLE
[BUG] AuthenticationFailed while creating Blob container

### ISSUE THREAD

**Issue by szymon-wlodarczyk** [Azure/azure-sdk-for-java#5295] opened 2019-09-09 10:09 UTC
**Describe the bug**
I am not able to create Blob container using Java SDK.
SDK version is com.azure:azure-storage-blob:12.0.0-preview.2

***Exception or Stack Trace***
<code>
Caused by: com.azure.storage.blob.models.StorageErrorException: Status code 403, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:ebc42eb6-101e-006e-7af4-660749000000
Time:2019-09-09T09:54:58.6761308Z</Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request 'uZ4D3JDqZIarosUpFjpAnlL9hUZOEAfy+aTEZpeuNOo=' is not the same as any computed signature. Server used following string to sign: 'PUT
Mon, 09 Sep 2019 09:54:58 GMT
x-ms-client-request-id:b919fac6-30f7-4e73-af22-f686d1102219
x-ms-meta-deviceid:8879f545-c5fc-450a-b046-f201ca2ef3bb
x-ms-meta-projectid:16fdb486-88c6-48f9-869c-bedfbf9abd02
x-ms-version:2018-11-09
/acblobstoragedev/201909-id-16fdb486-88c6-48f9-869c-bedfbf9abd02
restype:container'.</AuthenticationErrorDetail></Error>"
</code>
As you can see Authorization header is missing which is required according to documentation https://docs.microsoft.com/en-us/rest/api/storageservices/create-container

***Code Snippet***
I have following bean configuration:
<code>
  @Bean
  public BlobServiceClient blobServiceClient() {
    return new BlobServiceClientBuilder()
        .endpoint(storageUrl())
        .credential(new SharedKeyCredential(storageAccountName, storageAccountKey))
        .buildClient();
  }
</code>
Exception is thrown in following line:
<code>
      Response<ContainerClient> response =
          blobServiceClient.createContainer(containerName, metadata, null);
</code>

**Expected behavior**
Container should be created with container metadata assigned.
I can confirm that following code works:
<code>
    Response<ContainerClient> container =
        blobServiceClient.createContainer(containerName);
</code>

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : IntelliJ

**Comment by rickle-msft** [comment] 2019-09-09 18:54
Hi, @szymon-wlodarczyk. Thank you for reporting this issue, and we are sorry you are experiencing this difficulty. One thing to note is that the information you are seeing in the error response is what was used as the string to sign, not the full request. The authorization header is formed by computing the HMAC over this value and so is not actually included in what the service is using as the string to sign and hence why you're not  seeing it returned. 

I think the easiest way for us to diagnose this is if you can go to the definition of SharedKeyCredential and set a breakpoint on the buildStringToSign method to see what is getting returned. Once we have the string to sign the SDK is setting, we can compare that to what the service is computing and that'll give us a pretty clear idea of where something is going wrong.

If you could please set that break point and comment here with the string to sign you are observing in the SDK as well as the string to sign returned in error from the service, that would be very helpful (especially as I am not able to reproduce this locally)

**Comment by szymon-wlodarczyk** [comment] 2019-09-10 09:12
Hi,
Thanks for quick reply on this.

After invoking following code:
<code>
blobServiceClient.createContainer(containerName);
</code>
Shared key header value is:
<code>
SharedKey acblobstoragedev:fSG2NrBpva/QY5ag5DMTXjo6hCIx3PecigXyayLX4Ms=
</code>

After invoking following code:
<code>
blobServiceClient.createContainer(containerName, metadata, null);
</code>
Shared key header value is:
<code>
SharedKey acblobstoragedev:BaCNmF00Sn8qlxD2SvsMrVJEWHhpgMbhPQlIxvXgKmU=
</code>

Do you need exact values of cointanerName and metadata for investigation purposes ?

Regards,
Szymon

**Comment by gapra-msft** [comment] 2019-09-10 15:57
Hi, @szymon-wlodarczyk. Thanks for the quick response! 

I believe you may have misunderstood my colleague's message and I hope I can clarify his response. You seem to be setting a break point on the result of the generateAuthorizationHeader method. In that method, there should also be a call to the method buildStringToSign, could you please set a break point on the result of the buildStringToSign method so we can get a better understanding of what is going on? 

Thank you for your cooperation!

**Comment by szymon-wlodarczyk** [comment] 2019-09-10 18:32
Ok, sorry I thought that complete header value would be more helpful.
I will post those values tomorrow.
Thanks for the support on this !

**Comment by szymon-wlodarczyk** [comment] 2019-09-16 08:43
Any updates on this issue?

**Comment by gapra-msft** [comment] 2019-09-16 17:43
Apologies for the delayed response. I'm seeing two different issues here. 

1. The original posted issue saying that you have the wrong authorization header being generated due to a bad string to sign, and 
2. The issue mentioned later in the thread stating that you aren't generating a string to sign for the header. 

These appear to be two different issues that are incompatible in the same call. I think the best step forward would be for you to provide an end to end code snippet to clarify and reproduce the exact issue you are experiencing.

**Comment by szymon-wlodarczyk** [comment] 2019-09-18 13:15
[demo.zip](https://github.com/Azure/azure-sdk-for-java/files/3626574/demo.zip)

Attached project which simulates the issue with container creation.
Please remember to update storage account name and key in application.properties

**Comment by szymon-wlodarczyk** [comment] 2019-09-20 08:30
Hello,
Did you have a chance to take a look on this ?

**Comment by gapra-msft** [comment] 2019-09-20 19:14
Hi @szymon-wlodarczyk I'll get back to you on Monday. Thank you for your patience while we diagnose the issue.

**Comment by szymon-wlodarczyk** [comment] 2019-09-24 09:37
Hello,
Did you have a chance to investigate this issue?

**Comment by sima-zhu** [comment] 2019-09-24 17:58
Taking a look

**Comment by sima-zhu** [comment] 2019-09-24 19:36
@szymon-wlodarczyk Thanks for reporting the issue!
Storage service currently only accept all lower case string for metadata key. 
The test passed if you made changes in `prepareMetadata` method as following:
```java
  private Metadata prepareMetadata(UploadRequest uploadRequest) {
    return new Metadata(
        Map.of(
            "deviceuuid",
            uploadRequest.getDeviceUuid(),
            "containeruuid",
            uploadRequest.getContainerUuid()));
  }
```
It is an expected behavior for storage service. Let us know if you have further questions.
Thanks!

**Comment by szymon-wlodarczyk** [comment] 2019-09-24 19:45
Thanks for investigation. I will change implementation and let you know if that helps.
For your information test successfully passes for com.microsoft.azure:azure-storage-blob:11.0.0 SDK. This is regression or intentional change of implementation ?

All the best
Szymon

**Comment by sima-zhu** [comment] 2019-09-24 19:46
@gapra-msft 
She is the best contact for the question. I will hand off to her.

**Comment by gapra-msft** [comment] 2019-09-24 22:14
Hi @szymon-wlodarczyk Thank you for reporting the issue. 

This definitely appears to be a bug on our end in how we sign the metadata. We will work on fixing this issue and the fix should be in an upcoming preview. 

Thank you for your patience.

**Comment by sima-zhu** [comment] 2019-09-24 23:08
The bug fix has checked in [`414e5f7`](https://github.com/Azure/azure-sdk-for-java/commit/414e5f7ca27a35b20c52dc5eb608c567e99496de)

Let us know if the fix is not working.

**Comment by szymon-wlodarczyk** [comment] 2019-09-25 08:55
When preview 4 will be released with this bug fix?

**Comment by szymon-wlodarczyk** [comment] 2019-09-25 17:56
Or maybe question should be when final version will be released ? :)
I can confirm that container with metadata like: device_uuid and deviceuuid was created.

**Comment by gapra-msft** [comment] 2019-09-25 19:48
Our previews release in a monthly cadence. You can expect this fix to come early next month.

**Comment by joshfree** [comment] 2019-09-30 20:11
Closing issue as the fix will be available in the October preview, com.azure:azure-storage-blob:12.0.0-preview.4

**Closed by joshfree** 2019-09-30 20:11 UTC
Labels: Client, Storage, customer-reported
