### ISSUE TITLE
[BUG] Eventhubs client not recovering from errors

### ISSUE THREAD

**Issue by chance-cyphers** [Azure/azure-sdk-for-java#12397] opened 2020-06-22 20:52 UTC
**Describe the bug**
Every now and then we'll see errors from our servers using the java eventhubs client and a sudden drop-off of messages being written. This continues until we manually restart the kubernetes pods these services are running on. 

This has happened a few times in the past couple months. The errors are not always exactly the same. In some cases we see `com.microsoft.azure.eventhubs.CommunicationException: Connection reset by peer`. We've also seen this triggered by `EventHub produce encountered an exception exitCode=6`. These errors repeat and no messages are written until we restart the pod.

***Exception or Stack Trace***
In the `EventHub produce encountered an exception exitCode=6` case:
```
java.util.concurrent.ExecutionException: com.microsoft.azure.eventhubs.EventHubException: com.microsoft.azure.eventhubs.impl.AmqpException: The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 Reference:f701f607-ff58-46eb-9396-01fa0e92762c, TrackingId:45f56b43000000db0000016d5ea9f606_G0_B2, SystemTracker:feuschugehprod3:eventhub:chug~24319, Timestamp:2020-05-02T20:09:42, errorContext[NS: feuschugehprod3.servicebus.windows.net, PATH: chug, REFERENCE_ID: 4b6a85630a214fb9aced00138e5a1836_G0, LINK_CREDIT: 174]
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at io.reactivex.internal.functions.Functions$FutureAction.run(Functions.java:161)
	at io.reactivex.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:35)
	at io.reactivex.Completable.subscribe(Completable.java:2309)
	at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.microsoft.azure.eventhubs.EventHubException: com.microsoft.azure.eventhubs.impl.AmqpException: The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 Reference:f701f607-ff58-46eb-9396-01fa0e92762c, TrackingId:45f56b43000000db0000016d5ea9f606_G0_B2, SystemTracker:feuschugehprod3:eventhub:chug~24319, Timestamp:2020-05-02T20:09:42, errorContext[NS: feuschugehprod3.servicebus.windows.net, PATH: chug, REFERENCE_ID: 4b6a85630a214fb9aced00138e5a1836_G0, LINK_CREDIT: 174]
	at com.microsoft.azure.eventhubs.impl.ExceptionUtil.toException(ExceptionUtil.java:49)
	at com.microsoft.azure.eventhubs.impl.MessageSender.onSendComplete(MessageSender.java:567)
	at com.microsoft.azure.eventhubs.impl.SendLinkHandler.onDelivery(SendLinkHandler.java:103)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:185)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.eventhubs.impl.MessagingFactory$RunReactor.run(MessagingFactory.java:633)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	... 3 common frames omitted
Caused by: com.microsoft.azure.eventhubs.impl.AmqpException: The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 Reference:f701f607-ff58-46eb-9396-01fa0e92762c, TrackingId:45f56b43000000db0000016d5ea9f606_G0_B2, SystemTracker:feuschugehprod3:eventhub:chug~24319, Timestamp:2020-05-02T20:09:42
	... 14 common frames omitted
```
**To Reproduce**
We were not able to reproduce this error, as it seems to be triggered by eventhub server issues. 

However, we believe it could be reproduced by sending a tcp RST packet from the eventhub server, causing the `connection reset by peer` case.

***Code Snippet***
(code is written in kotlin)

client setup:
```
val retryPolicy = RetryExponential(
   Duration.ofSeconds(1),
   Duration.ofSeconds(5),
   3,
   "EventHubRetry"
)

EventHubClient.createFromConnectionStringSync(
            connectionString,
            retryPolicy,
            Executors.newScheduledThreadPool(8)
```

client usage:
```
 return Completable.fromFuture(this.client.send(eventData))
     .subscribeOn(Schedulers.io())
```

**Expected behavior**
Services can publish to an event hub indefinitely without manual intervention.

**Setup (please complete the following information):**
 - OS: Debian GNU/Linux 9
 - IDE : IntelliJ
 - azure-eventhubs:3.2.0

**Additional context**
For some reason restarting our pod by killing the app process doesn't seem to solve the issue, but killing and recreating the kubernetes pod does.

**Comment by srnagar** [comment] 2020-06-22 21:10
@chance-cyphers  Thanks for reporting this issue. 
@JamesBirdsall - could you please take a look at this?

**Comment by JamesBirdsall** [comment] 2020-06-25 21:38
There are a couple things going on here. 1) The original error with the big call stack is a transient internal error on the service side, which happens occasionally for a number of different reasons. The normal response is to retry, which may include creating a new TCP connection if the existing one was closed. 2) When the client attempts the retry, it gets a socket error that becomes the CommunicationException. It retries that, and gets another socket error, etc.

Underneath it all the client is just making a call to the Java sockets APIs. It's possible that something in the process has gotten into a weird state, but you say that killing and restarting the process doesn't help, which seems to rule that out. The fact that recreating the pod does help tends to indicate that something in the Kubernetes network stack has gotten into a bad state. The Event Hubs team would be glad to work with someone who knows Kubernetes networking to determine whether the problem is triggered by something in the way our service closes the connection, but we don't have the expertise to lead that effort.

**Comment by ndubetz** [comment] 2020-07-06 14:55
Thanks for the response @JamesBirdsall. @chance-cyphers and I's team have high-level k8s experience but not the deeper context to effectively troubleshoot at the network stack level. We do have such experts on another team at our company. Would it be possible to exchange information over an email thread? cc @eherde

**Comment by JamesBirdsall** [comment] 2020-07-06 21:42
Sure! You can contact me directly at jbird at microsoft dot com.

**Comment by JamesBirdsall** [comment] 2020-07-22 16:53
Update: @ndubetz contacted me directly in email on 7/7, and I responded to let him know he had reached me successfully. The thread was then waiting for input from the k8s experts on his end and I haven't seen anything to date.

**Comment by samuelkoppes** [comment] 2020-10-27 04:12
Closing as the issue is being handled offline.

**Closed by samuelkoppes** 2020-10-27 04:12 UTC
Labels: Client, Event Hubs, Service Attention, Track 1, customer-reported, question, tenet-reliability
