### ISSUE TITLE
[BUG] Unable to insert into CosmosDB with long partition key

### ISSUE THREAD

**Issue by yevster** [Azure/azure-sdk-for-java#10580] opened 2020-04-28 21:37 UTC
**Describe the bug**
Failure to do simple CosmosDB insert with `4.0.1-beta2`.

***Exception or Stack Trace***
```
BadRequestException{error={"Errors":["The input name '1.7977969654600919e+018' is invalid. Ensure to provide a unique non-empty string less than '1024' characters."]}, resourceAddress='null', statusCode=400, message=["The input name '1.7977969654600919e+018' is invalid. Ensure to provide a unique non-empty string less than '1024' characters."], {"requestLatency":11032,"requestStartTimeUTC":"28 Apr 2020 21:30:33.111","requestEndTimeUTC":"28 Apr 2020 21:30:44.143","connectionMode":"DIRECT","responseStatisticsList":[{"storeResult":{"storePhysicalAddress":{"uri":"rntbd://cdb-ms-prod-westus2-fd26.documents.azure.com:14017/apps/db2a149b-bdb4-4755-b26e-56d1a86cdd4e/services/dc4b7a8b-ca87-4327-b3c1-e00293d79ecd/partitions/032f07b4-931d-4212-aba3-6a200373ec0c/replicas/132323128684640428p/","uriasString":"rntbd://cdb-ms-prod-westus2-fd26.documents.azure.com:14017/apps/db2a149b-bdb4-4755-b26e-56d1a86cdd4e/services/dc4b7a8b-ca87-4327-b3c1-e00293d79ecd/partitions/032f07b4-931d-4212-aba3-6a200373ec0c/replicas/132323128684640428p/"},"lsn":132,"globalCommittedLsn":132,"partitionKeyRangeId":"0","isValid":true,"statusCode":400,"subStatusCode":0,"isGone":false,"isNotFound":false,"isInvalidPartition":false,"requestCharge":1.24,"itemLSN":-1,"sessionToken":"-1#132","exception":"[\"The input name '1.7977969654600919e+018' is invalid. Ensure to provide a unique non-empty string less than '1024' characters.\"]","transportRequestTimeline":null},"requestResponseTime":"28 Apr 2020 21:30:44.143"}],"supplementalResponseStatisticsList":[],"addressResolutionStatistics":{"7e1788d1-8997-11ea-9e6d-23dc7052476e":{"startTime":"28 Apr 2020 21:30:33.676","endTime":"28 Apr 2020 21:30:33.764"}},"regionsContacted":["https://sclabc-spva6my4jtfcm-westus2.documents.azure.com:443/"],"retryContext":{"retryCount":0,"statusAndSubStatusCodes":null,"retryLatency":0},"metadataDiagnosticsContext":{"metadataDiagnosticList":[{"metaDataName":"CONTAINER_LOOK_UP","startTimeUTC":"28 Apr 2020 21:30:33.154","endTimeUTC":"28 Apr 2020 21:30:33.257","durationinMS":103},{"metaDataName":"PARTITION_KEY_RANGE_LOOK_UP","startTimeUTC":"28 Apr 2020 21:30:33.306","endTimeUTC":"28 Apr 2020 21:30:33.665","durationinMS":359},{"metaDataName":"SERVER_ADDRESS_LOOKUP","startTimeUTC":"28 Apr 2020 21:30:33.676","endTimeUTC":"28 Apr 2020 21:30:33.764","durationinMS":88}]},"serializationDiagnosticsContext":{"serializationDiagnosticsList":[{"serializationType":"ITEM_SERIALIZATION","startTimeUTC":"28 Apr 2020 21:30:33.113","endTimeUTC":"28 Apr 2020 21:30:33.149","durationInMicroSec":36000},{"serializationType":"PARTITION_KEY_FETCH_SERIALIZATION","startTimeUTC":"28 Apr 2020 21:30:33.265","endTimeUTC":"28 Apr 2020 21:30:33.268","durationInMicroSec":3000}]},"gatewayStatistics":null,"systemInformation":{"usedMemory":"89131 KB","availableMemory":"3622869 KB","processCpuLoad":"14.457044304711006 %","systemCpuLoad":"0.0 %"}}, causeInfo=null, responseHeaders={x-ms-current-replica-set-size=4, x-ms-last-state-change-utc=Sat, 25 Apr 2020 18:27:59.066 GMT, x-ms-session-token=0:-1#132, lsn=132, x-ms-request-charge=1.24, x-ms-schemaversion=1.9, x-ms-transport-request-id=1, x-ms-number-of-read-regions=0, x-ms-current-write-quorum=3, x-ms-cosmos-quorum-acked-llsn=132, x-ms-quorum-acked-lsn=132, x-ms-activity-id=7dc71edd-8997-11ea-9e6d-23dc7052476e, x-ms-xp-role=1, x-ms-global-Committed-lsn=132, x-ms-cosmos-llsn=132, x-ms-serviceversion= version=2.10.0.0}, requestHeaders=null}
	at com.azure.cosmos.implementation.directconnectivity.rntbd.RntbdRequestManager.messageReceived(RntbdRequestManager.java:742)
	at com.azure.cosmos.implementation.directconnectivity.rntbd.RntbdRequestManager.channelRead(RntbdRequestManager.java:175)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1470)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1219)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1266)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Unknown Source)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1664)
		at com.azure.cosmos.CosmosContainer.mapItemResponseAndBlock(CosmosContainer.java:228)
		at com.azure.cosmos.CosmosContainer.createItem(CosmosContainer.java:155)
		at repro.TestCosmosConnect.testInsert(TestCosmosConnect.java:73)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		at java.lang.reflect.Method.invoke(Unknown Source)
		at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675)
		at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:125)
		at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:132)
		at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:124)
		at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:74)
		at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
		at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:104)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:62)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:43)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:35)
		at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
		at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:202)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:198)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:69)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
		at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
		. . .
```

**To Reproduce**
Run the unit test below

***Code Snippet***
****TestCosmosConnect.java****
```java
package repro;

import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;

import org.apache.commons.lang3.RandomStringUtils;
import org.apache.commons.lang3.RandomUtils;
import org.apache.commons.lang3.StringUtils;
import org.junit.jupiter.api.Test;

import com.azure.cosmos.CosmosClient;
import com.azure.cosmos.CosmosClientBuilder;
import com.azure.cosmos.CosmosContainer;
import com.azure.cosmos.models.CosmosContainerResponse;

public class TestCosmosConnect {
	private static class Person {
		private final String firstName;
		private final String lastName;
		private final long id;

		public static Person newRandom() {
			return new Person(RandomStringUtils.randomAlphabetic(10), "Mc" + RandomStringUtils.randomAlphabetic(12),
					RandomUtils.nextLong());
		}

		private Person(String firstName, String lastName, long id) {
			this.firstName = firstName;
			this.lastName = lastName;
			this.id = id;
		}

		public String getFirstName() {
			return firstName;
		}

		public String getLastName() {
			return lastName;
		}

		public long getId() {
			return id;
		}

		@Override
		public String toString() {
			return "[" + id + "]" + getFirstName() + " " + getLastName();
		}
	}

	@Test
	public void testInsert() {
		String key = System.getenv("cosmos_key");
		String endpoint = System.getenv("cosmos_endpoint");
		String databaseName = System.getenv("cosmos_database");
		String containerName = "sinktasktest" + RandomUtils.nextInt() % 10000;

		assertTrue(StringUtils.isNotBlank(key));
		assertTrue(StringUtils.isNotBlank(endpoint));
		assertTrue(StringUtils.isNotBlank(databaseName));

		CosmosClient cosmosClient = new CosmosClientBuilder().endpoint(endpoint).key(key).buildClient();
		CosmosContainerResponse containerResponse = cosmosClient.getDatabase(databaseName)
				.createContainer(containerName, "/id");
		CosmosContainer container = containerResponse.getContainer();

		Person person = Person.newRandom();
		System.out.println("Writing person " + person);
		try {
			container.createItem(person);
		} catch (Throwable t) {
			t.printStackTrace(System.err);
			fail(t);
		} finally {
			container.delete();
		}
	}
}
```

****pom.xml****

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.yevster.repro</groupId>
	<artifactId>repro</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
	</properties>
	<dependencies>

		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-cosmos</artifactId>
			<version>4.0.1-beta.2</version>
		</dependency>

		<!-- Apache commons -->

		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-collections4</artifactId>
			<version>4.4</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.10</version>
		</dependency>


		<!-- Test -->
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<version>5.5.2</version>
			<scope>test</scope>
		</dependency>

	</dependencies>
</project>
```

**Expected behavior**
Test passes and the new item gets written to CosmosDB

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : IntelliJ and Eclipse
 - 4.0.1-beta2

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by kushagraThapar** [comment] 2020-04-29 21:59
@yevster The issue is not related to partition key, but in fact related to container name. In your case it is more than 1024 characters, which is causing it to fail. 
That's a backend limitation and not an SDK issue. Please use container names less than 2014 characters in length.

**Comment by yevster** [comment] 2020-05-13 22:35
@kushagraThapar, in the code example I provided, change the ID field from a Long to a String (and the get and set methods accordingly), and the problem goes away. What does that have to do with the length of container names?

**Comment by jongio** [comment] 2020-08-18 17:26
@joshfree - This has Client tag, but assigned to Cosmos team. Should it be assigned to someone on the Client team or is it mislabeled?  Thanks, Jon

**Comment by kushagraThapar** [comment] 2020-08-18 20:05
@yevster , Sorry about the confusion earlier, the issue is related to the `id` field being `long` type. `id` field can only be a `string`, which is why you are seeing that exception.

**Comment by joshfree** [comment] 2020-08-19 23:07
@jongio - `Client`, `EngSys`, `Mgmt` and `Engsys-Mgmt` are high-level category labels;  All client side SDK bugs also have a `Client` label.  It's not an either-or with `Client` versus an `SDK-Area` label.

**Closed** 2020-09-10 08:00 UTC
Labels: Client, Cosmos, bug, cosmos:v4-item, customer-reported, needs-author-feedback, no-recent-activity, question
