### ISSUE TITLE
[BUG] Spring Boot - AppInsight does not should the Application Map for RestTemplate with HttpClient

### ISSUE THREAD

**Issue by Anand0583** [Azure/azure-sdk-for-java#23168] opened 2021-07-25 10:53 UTC
Hello Team,

I have created 2 microservices using Spring Boot and I am trying to create the Application Map using AppInsights. 
But in AppInsight we only see 2 Separate Spring Boot application and they are not connected.

![image](https://user-images.githubusercontent.com/35911769/126896413-32332829-3507-48b9-b71f-5cd039e32ecd.png)

I have followed all the steps which have been mentioned in the Microsoft Documentation but I am not able to get the Application Map.

Also there is another issue, with using Logback Logs too are not following to AppInsight. 

I am able to see the requests flowing to AppInsight but none of the traces are flowing to AppInsight.

Please note that I have masked the "instrumentation-key" on purpose.

Please find github links for the Source Code.
[https://github.com/Anand0583/order-service.git](url)
[https://github.com/Anand0583/customer-service.git](url)

To Test Invoke order-service [http://localhost:8084/order/v1?orderId=99055](url)

Help is much appreciated.

Thanks & Regards,

**Comment by joshfree** [comment] 2021-07-30 20:54
Hi @Anand0583, someone from the `azure-spring` team will follow up with you shortly.

/cc @stliu

**Comment by Anand0583** [comment] 2021-08-03 10:40
Thanks @joshfree @stliu  Please let me know when we can connect as it is blocking us from having it working for Spring-Boot Applications.

**Comment by trask** [comment] 2021-08-05 19:03
hey @Anand0583! this looks like a duplicate of https://github.com/microsoft/ApplicationInsights-Java/issues/1814, can we close this one?

**Comment by stliu** [comment] 2021-08-06 01:53
duplicated by https://github.com/microsoft/ApplicationInsights-Java/issues/1814

**Closed by stliu** 2021-08-06 01:53 UTC
Labels: question, Client, customer-reported, azure-spring
