### ISSUE TITLE
AutoRest : Main thread does not terminate.

### ISSUE THREAD

**Issue by m-moris** [Azure/azure-sdk-for-java#622] opened 2016-03-22 13:40 UTC
I have tried 1.0 beta.
When I use an asynchronous method, main thread does not terminate.
It looks like OkHttp threads are still remain.

Does anyone know any solution?

```
package sample.autorest;

import java.io.IOException;

import com.microsoft.azure.CloudException;
import com.microsoft.azure.credentials.ApplicationTokenCredentials;
import com.microsoft.azure.management.compute.ComputeManagementClient;
import com.microsoft.azure.management.compute.ComputeManagementClientImpl;
import com.microsoft.azure.management.compute.models.VirtualMachine;
import com.microsoft.rest.ServiceCall;
import com.microsoft.rest.ServiceCallback;
import com.microsoft.rest.ServiceResponse;

import okhttp3.logging.HttpLoggingInterceptor;

public class App3 {

    public static void main(String[] args) throws CloudException, IllegalArgumentException, IOException, InterruptedException {

        String subscriptionId = "<<your subscription id>>";
        String tenantId = "<<your tenant id>>";
        String clientId = "<<your client id>>";
        String clientKey = "<<your client key>>";

        ApplicationTokenCredentials credentials = new ApplicationTokenCredentials(
                clientId, tenantId, clientKey, null);

        ComputeManagementClient client = new ComputeManagementClientImpl(credentials);
        client.setSubscriptionId(subscriptionId);
        client.setLogLevel(HttpLoggingInterceptor.Level.BODY);

        String rg = "your resource-group-name";
        String rs = "your vm name";

        ServiceCallback<VirtualMachine> serviceCallback = new ServiceCallback<VirtualMachine>() {
            @Override
            public void failure(Throwable t) {
                System.err.println("failed");
            }

            @Override
            public void success(ServiceResponse<VirtualMachine> result) {
                VirtualMachine vm = result.getBody();
                System.out.println(vm.getId());
            }
        };
        ServiceCall async = client.getVirtualMachinesOperations().getAsync(rg, rs, "instanceview", serviceCallback);
        System.out.println("done");
    }
}
```

**Comment by jianghaolu** [comment] 2016-04-01 17:10
Hi @m-moris 

This is reproduced and 2 issues are involved here:
1) a bug fixed in https://github.com/Azure/autorest/pull/908 that ADAL auth executor was not shutdown.
2) Retrofit uses a non-daemon thread for calling callbacks, which JVM will wait until it finishes. Otherwise JVM might terminate before the success() callback is called. But there is a timeout - so if you wait for ~ 1 min JVM would shut down.
To eliminate this 1 min, _supposedly_ you need to create daemon threads and manage on your own. But when I gave it a try looks like it's not working.

**Comment by jianghaolu** [comment] 2016-04-01 17:34
@normalian

**Comment by jianghaolu** [comment] 2016-04-01 17:45
Found a solution:

Create your own executor service with daemon threads:
```java
final ExecutorService executor = Executors.newCachedThreadPool(new ThreadFactory() {
    public Thread newThread(Runnable r) {
        Thread thread = new Thread(r);
        thread.setDaemon(true);
        return thread;
    }
});
```
and register it in OkHttpClient buider:
```java
final OkHttpClient client = new OkHttpClient.Builder().dispatcher(new Dispatcher(executor)).build();
```
and pass that into `ComputeManagementClientImpl`'s constructor.

By doing so your JVM will exit before your callbacks are called, so create a `CountDownLatch` of value 1 and count it down in your callbacks. call `await()` before `main()` terminates.
```java
final CountDownLatch latch = new CountDownLatch(1);
ServiceCallback<VirtualMachine> serviceCallback = new ServiceCallback<VirtualMachine>() {
    @Override
    public void failure(Throwable t) {
        System.err.println("failed");
        latch.countDown();
    }
   @Override
    public void success(ServiceResponse<VirtualMachine> result) {
        VirtualMachine vm = result.getBody();
        System.out.println(vm.getId());
        latch.countDown();
    }
};
ServiceCall async = client.getVirtualMachinesOperations().getAsync(rg, rs, "instanceview", serviceCallback);
System.out.println("done");
latch.await();
```

**Closed by jianghaolu** 2016-04-01 17:45 UTC

**Comment by m-moris** [comment] 2016-04-07 01:42
Hi @jianghaolu  @normalian

Thank you for your help.

I executed my sample programs and it looks like working properly. I think it is a little bit troublesome to use CountDownLatch class. I continue to try and investigate the easiest way to async method.

Thanks.

**Comment by jianghaolu** [comment] 2016-04-07 16:34
@m-moris 
There is really no reconciliation in this. You either run it in a daemon thread and wait with something like CountDownLatch (otherwise JVM will exit before callback is called), or run it in a non-daemon thread, then JVM will wait with a timeout.

**Comment by jianghaolu** [comment] 2016-04-07 16:36
@m-moris 
But if you find something better than CountDownLatch, please let us know. I would like to know that too :) Or feel free to open a pull request with a sample. :)
