### ISSUE TITLE
Revisit getToken sync implementations

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#29746] opened 2022-07-01 05:52 UTC
we should have todo/work item to revisit this later. this one seems to be simpler than identity.

_Originally posted by @kasobol-msft in https://github.com/Azure/azure-sdk-for-java/pull/29730#discussion_r911468067_

**Comment by g2vinay** [comment] 2023-02-07 20:46
duplicate of #30581

**Closed by g2vinay** 2023-02-07 20:46 UTC
Labels: Client, Azure.Core
