### ISSUE TITLE
[BUG] Delayed event hub partition claiming of EventProcessorClient

### ISSUE THREAD

**Issue by thomasstoermer** [Azure/azure-sdk-for-java#31672] opened 2022-10-21 17:03 UTC
**Describe the bug**
We are using Azure Event Hub Service. We tested new version `com.azure:azure-messaging-eventhubs-checkpointstore-blob:1.16.0` and are observing delayed partition claiming, which in the end causes event processing delay.

***Exception or Stack Trace***
```
com.azure.storage.blob.models.BlobStorageException: Status code 412, \"<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>ConditionNotMet</Code><Message>The condition specified using HTTP conditional header(s) is not met.
RequestId:......
Time:2022-10-21T15:45:32.6413117Z</Message></Error>\"
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
	at com.azure.core.implementation.http.rest.ResponseExceptionConstructorCache.invoke(ResponseExceptionConstructorCache.java:56)
	at com.azure.core.implementation.http.rest.RestProxyBase.instantiateUnexpectedException(RestProxyBase.java:367)
	at com.azure.core.implementation.http.rest.AsyncRestProxy.lambda$ensureExpectedStatus$1(AsyncRestProxy.java:115)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113)
	... 77 common frames omitted
Wrapped by: java.lang.IllegalStateException: Error while claiming checkpoints
	at com.azure.messaging.eventhubs.PartitionBasedLoadBalancer.lambda$claimOwnership$24(PartitionBasedLoadBalancer.java:478)
	at reactor.core.publisher.LambdaMonoSubscriber.doError(LambdaMonoSubscriber.java:155)
	at reactor.core.publisher.LambdaMonoSubscriber.onError(LambdaMonoSubscriber.java:150)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onError(MonoCollectList.java:114)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:842)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:608)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:588)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.innerError(FluxFlatMap.java:863)
	at reactor.core.publisher.FluxFlatMap$FlatMapInner.onError(FluxFlatMap.java:990)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:842)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:608)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:588)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onError(FluxFlatMap.java:451)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:416)
	at reactor.core.publisher.DrainUtils.postCompleteDrain(DrainUtils.java:136)
	at reactor.core.publisher.DrainUtils.postComplete(DrainUtils.java:187)
	at reactor.core.publisher.FluxMapSignal$FluxMapSignalSubscriber.onError(FluxMapSignal.java:192)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:142)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onError(FluxContextWrite.java:121)
	at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onError(FluxDoOnEach.java:195)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:192)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:259)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:142)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:171)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2194)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2068)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
	at reactor.core.publisher.FluxDelaySubscription$DelaySubscriptionMainSubscriber.onNext(FluxDelaySubscription.java:189)
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onNext(FluxTimeout.java:180)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:292)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:187)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:174)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2664)
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:180)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:260)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:128)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:152)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1817)
	at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:160)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:220)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:275)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:400)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:419)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:473)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:703)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1373)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1247)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1287)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:519)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:458)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**To Reproduce**
- Use EventProcessorClient for partition processing (32 partitions)
- Define Greedy loadbalancing
- Produce on all partitions an incoming event
- Start the EventProcessorClient and observe how some partitions are starting to process events several minutes delayed ( up to 6-16 minutes )
- After all partitions are claimed and started processing, the exceptions are stopping

***Code Snippet***

**Expected behavior**
- EventProcessorClients should directly claim all partitions without delay (especially with GREEDY loadbalancing)
- Old version works as expected: `com.azure:azure-messaging-eventhubs-checkpointstore-blob:1.12.2`

**Screenshots**

**Setup (please complete the following information):**
 - OS: Docker `eclipse-temurin:11`
 - Library/Libraries:
 ```
[INFO] +- com.azure:azure-messaging-eventhubs:jar:5.14.0:compile
[INFO] |  +- (com.azure:azure-core:jar:1.33.0:compile - omitted for duplicate)
[INFO] |  \- com.azure:azure-core-amqp:jar:2.7.2:compile
[INFO] |     \- (com.azure:azure-core:jar:1.33.0:compile - omitted for duplicate)
[INFO] +- com.azure:azure-storage-blob:jar:12.20.0:compile
[INFO] |  +- (com.azure:azure-core:jar:1.33.0:compile - omitted for duplicate)
[INFO] |  +- com.azure:azure-core-http-netty:jar:1.12.6:compile
[INFO] |  |  \- (com.azure:azure-core:jar:1.33.0:compile - omitted for duplicate)
[INFO] |  +- com.azure:azure-storage-common:jar:12.19.0:compile
[INFO] |  |  +- (com.azure:azure-core:jar:1.33.0:compile - omitted for duplicate)
[INFO] |  |  \- (com.azure:azure-core-http-netty:jar:1.12.6:compile - omitted for duplicate)
[INFO] |  \- com.azure:azure-storage-internal-avro:jar:12.5.0:compile
[INFO] |     +- (com.azure:azure-core:jar:1.33.0:compile - omitted for duplicate)
[INFO] |     +- (com.azure:azure-core-http-netty:jar:1.12.6:compile - omitted for duplicate)
[INFO] |     \- (com.azure:azure-storage-common:jar:12.19.0:compile - omitted for duplicate)
[INFO] +- com.azure:azure-messaging-eventhubs-checkpointstore-blob:jar:1.16.0:compile
[INFO] |  +- (com.azure:azure-messaging-eventhubs:jar:5.14.0:compile - omitted for duplicate)
[INFO] |  \- (com.azure:azure-storage-blob:jar:12.20.0:compile - omitted for duplicate)
[INFO] +- com.azure:azure-identity:jar:1.6.1:compile
[INFO] |  +- (com.azure:azure-core:jar:1.33.0:compile - omitted for duplicate)
[INFO] |  \- (com.azure:azure-core-http-netty:jar:1.12.6:compile - omitted for duplicate)
[INFO] \- com.azure:azure-core:jar:1.33.0:compile
```
 - Java version: 11
 - App Server/Environment: Dropwizard, k8s
 - Frameworks: 

**Additional context**

**Information Checklist**
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by conniey** [comment] 2022-10-24 22:02
Do you have a code snippet of how you are building the processor?

**Comment by h-okhs** [comment] 2022-10-25 18:52
I'm facing the same problem by using EventHubs component of Apache Camel.
It's also reproducible on EventHub which has only one partition.

**Comment by liukun-msft** [comment] 2022-10-28 06:53
@conniey I encountered the same error when I ran the stress test. I can check this issue if you havn't done it.

**Comment by conniey** [comment] 2022-10-28 17:06
@liukun-msft I have not checked this out yet. Please feel free to

**Comment by zhtang-li** [comment] 2022-11-03 03:47
@conniey we had this exact same behavior as well. we will try to downgrade `com.azure:azure-messaging-eventhubs-checkpointstore-blob` to 1.12.2 to see if we can resolve these 412 issues. Please let us know what the root cause and what we should do to avoid exceptions like this.

**Comment by liukun-msft** [comment] 2022-11-03 06:30
Updates for this issue: 

Starting from June releases (`azure-messaging-eventhubs-checkpointstore-blob` 1.13.0), we changed the behavior of claimOwnership method from return empty to return error when encountering errors ([CHANGELOG](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs-checkpointstore-blob/CHANGELOG.md#1130-2022-06-10)). However, the 412 error is normal as part of load balance, we shouldn't return and log this error to user (It could be debug level log and return empty() for this specific error).

In Sept release, there was a partitial rollback to ensure that eventhubs continued to work when the 412 error ocurred (Issue [#29927](https://github.com/Azure/azure-sdk-for-java/issues/29927#issuecomment-1218291275)). But it still has processor start-up latency impact as we doesn't revert the changes in `azure-messaging-eventhubs-checkpointstore-blob`. 

I'll keep working on this issue. Until we fix this issue, you can use the lastest version and just ignore the 412 error in logs. Or if you can't accept the partition start-up delay, try to downgrade `azure-messaging-eventhubs-checkpointstore-blob` to 1.12.2.

**Comment by zhtang-li** [comment] 2022-11-03 07:03
@liukun-msft by `lastest version`, do you mean the latest version of `azure-messaging-eventhubs-checkpointstore-blob` or `azure-messaging-eventhubs`? and in that latest version, if I understand correctly, the 412 error will not be passed to the error consumer, which is the root cause of those exceptions.
Alternatively, we could just downgrade `azure-messaging-eventhubs-checkpointstore-blob` to 1.12.2, correct?
Thanks!

**Comment by liukun-msft** [comment] 2022-11-03 07:14
Hi @zhtang-li Both `azure-messaging-eventhubs-checkpointstore-blob` and `azure-messaging-eventhubs` need to use the latest version. 

The downgrade is not recommended. It could be fine to only downgrade `azure-messaging-eventhubs-checkpointstore-blob` to 1.12.2, but it is better also change the `azure-messaging-eventhubs` to 5.12.0 to avoid dependency incompatiable issue. 

We will notify you after we release a fix version for this issue.

**Comment by zhtang-li** [comment] 2022-11-03 08:01
just adding some context, @liukun-msft , the versions that we see problems (412 errors passed into error consumer) are `azure-messaging-eventhubs:5.13.1` and `azure-messaging-eventhubs-checkpointstore-blob:1.15.1`  and from the change logs of both sdks, I do not see any fix related to the that makes `eventhubs continued to work when the 412 error ocurred`. 
Could you elaborate more about what has been addressed and has not here? thanks.

**Comment by liukun-msft** [comment] 2022-11-03 16:23
@zhtang-li The fix PR for [#Issue 29927](https://github.com/Azure/azure-sdk-for-java/issues/29927) was released as `azure-messaging-eventhubs 5.13.1` (2022-09-11). Sorry for not mentioning it in the changelog, I will add it soon. If you use `azure-messaging-eventhubs:5.13.1` and `azure-messaging-eventhubs-checkpointstore-blob:1.15.1` or later version, eventhub will continue to work.

**Comment by liukun-msft** [comment] 2022-11-18 05:53
We have reverted the incorrect changes as a quick fix. Please upgrade your eventhubs to the lastest version (current is `azure-messaging-eventhubs:5.15.0` and `azure-messaging-eventhubs-checkpointstore-blob:1.16.1`) to solve this issue.

**Comment by thomasstoermer** [comment] 2022-12-12 09:40
I can confirm, that the issue is fixed for us after switching to the latest provided versions.

**Closed** 2022-12-12 10:18 UTC
Labels: question, Event Hubs, customer-reported, issue-addressed
