### ISSUE TITLE
[QUERY] com.azure:azure-storage-blob versions prior to 12.7.0 are not accessible in maven repositories

### ISSUE THREAD

**Issue by alexsmithMSFT** [Azure/azure-sdk-for-java#23562] opened 2021-08-13 21:01 UTC
A customer reported to me that our previously supported version of 'com.azure:azure-storage-blob:jar:12.4.0' is not accessible anymore.

As of this post, the latest documented version of Azure storage SDKs for Java on Azure Stack Hub was 12.4.0- 
https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-storage-dev?view=azs-2102#2008-update

> Java    12.4.0

And it's still listed in the mainfest- https://repo1.maven.org/maven2/com/azure/azure-storage-blob/maven-metadata.xml
But the subdirectory and .JAR file for the **azure-storage-blob** library for that version became unavailable recently (404 errors)-
https://repo1.maven.org/maven2/com/azure/azure-storage-blob/12.4.0/  (404 error)

We found the same in the Apache repo- https://repo.maven.apache.org/maven2/com/azure/azure-storage-blob/12.4.0/

https://mvnrepository.com/artifact/com.azure/azure-storage-blob/12.4.0 is from Feb 12, 2020
The earliest version I can access is 12.7.0. Were the earlier versions removed intentionally?

**Comment by bganapa** [comment] 2021-08-14 00:25
@joshfree Do you know whether we delist a package in Maven? Is this an issue with Maven itself? apologies for tagging you. We have a customer escalation, trying to find the cause.

**Comment by JonathanGiles** [comment] 2021-08-14 10:16
@amishra-dev will provide context here.

**Comment by hwride** [comment] 2021-08-16 08:34
This is also the case for azure-storage-blob-12.2.0.jar, and in fact for quite a lot of the old versions if you try and find them.

**Comment by hwride** [comment] 2021-08-16 08:35
This is also an issue for us, would appreciate some clarification if the old versions are intended to be removed.

**Comment by LizhangX** [comment] 2021-08-17 16:44
Hi, we are getting the same issue here with 12.6.0.

**Comment by dougwettlaufer** [comment] 2021-08-20 19:15
Any news on this? We're impacted as well.

**Comment by amishra-dev** [comment] 2021-08-21 22:29
We discovered an issue in older versions listed below of the SDKs for Storage which we have removed from Maven. To upgrade to the latest version please change the dependency version in your pom.xml to a newer one listed below. We strongly recommend moving to the latest SDK if you are using any of these affected versions.
 
If you need to use an older Azure Storage REST API version, please read the sample [here](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/samples/java/com/azure/storage/blob/ServiceVersionExample.java) about using an older Service Version with a newer SDK. We apologize for the inconvenience this may have caused.

| SDK                         	| Versions Removed 	| Recommended Version 	|
|-----------------------------	|------------------	|---------------------	|
| Azure Storage Blob          	| 12.0 to 12.6.1   	| 12.13               	|
| Azure Storage File Datalake 	| 12.0 to 12.1.2   	| 12.6                	|
| Azure Storage File Share    	| 12.0 to 12.4.1   	| 12.10               	|

**Comment by ghartz-hz** [comment] 2021-09-03 12:15
What is the status of this?  This is such a critical problem, I'm shocked no one at Microsoft was making people work overnight to get it back up. This isn't a bug, this is a critical service outage. 

Upgrading is not an option because, like most Azure libraries it seems, Microsoft has not maintained API-level compatibility and binary compatibility with the updated versions of these libraries.  "Upgrade to 12.13.0" is not an acceptable option when it entails a set of dependency upgrades that cascades to other 3rd party libraries not being compatible. 

This is an issue that means its no longer possible for people running existing, fully tested and deployed code to rebuild that code. The problem is not the API versions, its the library versions. "We found an issue" -- what issue? Where is the CVE or other documentation about what was found? Why is it not being left up to the customer to decide the impact of that issue and when to mitigate it? And if there was an issue that legitimately required pulling those versions, why was it not patched in a way that was drop-in compatible with the existing libraries? Pulling in new versions of both Microsoft and 3rd party libraries in these updated jars means not one library needs to be updated, but potentially dozens. And those may or may not have cross-compatibility. (For example, these updated libraries do not work properly with Spring Boot 2.2.)

Is there an ETA for getting these restored, or is Microsoft's official stance at this point "we don't care if we maintain compatibility"?  Because, in the latter case, we're not going to invest money on fixing the issue and risk this happening again, we'll spend the money removing the Azure dependencies entirely.

**Comment by amishra-dev** [comment] 2021-09-08 23:04
@ghartz-hz we do apologize for the inconvenience this has caused. 
please create a ticket at aka.ms/azsupt.

Issue Type: Technical
Service Type: Blob Storage
Summary: #JavaSDKv12
Problem type: Development
Problem subtype: Client library or SDK

**Closed** 2024-03-15 18:04 UTC
Labels: Storage
