### ISSUE TITLE
Ref docs issue

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-java#30292] opened 2022-08-05 07:16 UTC
Error:

> ##[error]java2yaml '"cmd.exe" /c mvn dependency:copy-dependencies -P !azure-mgmt-sdk-test-jar -DoutputDirectory=D:\a\_work\1\s\target_repo\src\docs-ref-autogen\azure-resourcemanager\Dependency' failed. [ERROR] Failed to execute goal on project azure-resourcemanager: Could not resolve dependencies for project com.azure.resourcemanager:azure-resourcemanager:jar:2.16.0: com.azure.resourcemanager:azure-resourcemanager-test:jar:2.0.0-beta.1 was not found in https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-java/maven/v1 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of azure-sdk-for-java has elapsed or updates are forced -> [Help 1]  [ERROR]   [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.  [ERROR] Re-run Maven using the -X switch to enable full debug logging.  [ERROR]   [ERROR] For more inform

For more details check here:

- https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=309896&view=results

@danieljurek for notification.

**Comment by danieljurek** [comment] 2022-08-05 18:23
@sima-zhu -- Looks like there's a failure in Java docs builds. Similar messages have happened in the most recent 3 builds.

**Comment by sima-zhu** [comment] 2022-08-05 18:36
Remove the azure-sdk-template packages as they are not needed. 
https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=310065&view=results

**Comment by weidongxu-microsoft** [comment] 2022-08-10 01:01
`com.azure.resourcemanager:azure-resourcemanager-test:jar` is not published to maven, as it is only used for testing.

I am not sure why the CI need `dependency:copy-dependencies`, but if you need it, exclude the package via `-P !azure-mgmt-sdk-test-jar` in `mvn` ([pom](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/azure-resourcemanager/pom.xml#L228)).

**Comment by sima-zhu** [comment] 2022-08-17 04:33
I think I fixed the issue. If not, could you share the failed pipeline?

**Comment by v-xuto** [comment] 2023-03-10 05:51
Close this issue as it is no longer reproduced.

**Closed by v-xuto** 2023-03-10 05:51 UTC
Labels: EngSys
