### ISSUE TITLE
[BUG] Returning BlobItem from a REST call gives an Error due to Creation-Time is a non-Seralizable class (DateTimeRfc1123).

### ISSUE THREAD

**Issue by millerna26** [Azure/azure-sdk-for-java#4936] opened 2019-08-10 00:39 UTC
Returning a BlobItem from a REST call gives an Error due to Creation-Time type not being serializable. Values are there, but error when trying to return on API. 

Sample Code:

    @RequestMapping("/listblobs")
    public @ResponseBody List<BlobItem> listBlobs(String containerName) {

        ContainerClient containerClient = getContainerClient(containerName);
        ListBlobsOptions options = new ListBlobsOptions();
        options.maxResults(10);
        Iterable<BlobItem> blobs = containerClient.listBlobsFlat(options, null);

        List<BlobItem> blobList = new ArrayList<BlobItem>();
        blobs.forEach(item->blobList.add(item));

        return blobList;
    }

Error Message:
    "message": "Type definition error: [simple type, class com.azure.core.implementation.DateTimeRfc1123]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class com.azure.core.implementation.DateTimeRfc1123 and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.ArrayList[0]->com.azure.storage.blob.models.BlobItem[\"Properties\"]->com.azure.storage.blob.models.BlobProperties[\"Creation-Time\"])",

**Comment by rickle-msft** [comment] 2019-08-12 17:22
@millerna26 thank you for reporting this. Just to clarify, if you're seeing deserialization issues, I imagine that's happening on the line where you call listBlobsFlat?

**Comment by rickle-msft** [comment] 2019-08-13 00:05
@jianghaolu or @alzimmermsft any insight on this?

**Comment by millerna26** [comment] 2019-08-13 01:05
Everything actually works until the return. I believe it is a compatibility issue with Spring Boot framework. I see the value in debug up to the return call. When I turn the setting off per error message, I just get an empty date field on the return, but everything else works.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by alzimmermsft** [comment] 2019-08-13 17:47
@millerna26 Which version of azure-storage-blob are you using in this example?

**Comment by millerna26** [comment] 2019-08-13 21:14
@alzimmermsft 12.0.0-preview.2

**Comment by alzimmermsft** [comment] 2019-08-15 18:00
I created this simple reproduction to investigate this issue, was this similar to what you were using? 

[Debugging Projects.zip](https://github.com/Azure/azure-sdk-for-java/files/3506638/Debugging.Projects.zip)

**Comment by millerna26** [comment] 2019-08-15 19:57
Yes, that looks very similar to the code I have.

**Comment by rickle-msft** [comment] 2019-08-21 00:20
@millerna26 Have you been able to make any progress on this? From some discussions over here, it looks like it might be an issue with Spring more than the Storage SDK, but if you think otherwise, we can take a look at this again tomorrow.

**Comment by millerna26** [comment] 2019-08-21 17:44
One workaround I did was to create my own class that I will be copying fields I need from BlobItem then use that class in the return.

custom class Blob:

	import java.time.OffsetDateTime;
	import com.fasterxml.jackson.annotation.JsonAutoDetect;
	
	@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.ANY)
	public class Blob {
		private final String name;
		private final OffsetDateTime createDate;
		private final Long size;
	…
	Have public getters for each.


In API Controller Instead of this:

	//List<BlobItem> blobList = new ArrayList<BlobItem>();
	//blobs.forEach(item->blobList.add(item));

Load to Custom Class and return.

	List<Blob> blobList = new ArrayList<Blob>();
	blobs.forEach(item->blobList.add(new Blob(item.name(), item.properties().creationTime(), item.properties().contentLength())));
	return blobList;

**Comment by rickle-msft** [comment] 2019-08-21 21:59
Hey, @millerna26. We're having some trouble repro-ing this issue. If you'd like to continue investigating this, could send us the output of `mvn dependency:tree ` so we can try to mimic your environment more exactly? If you are satisfied with this work around, we'll ask that you please close the issue.

**Closed** 2019-08-21 22:07 UTC
Labels: Client, Storage, customer-reported
