### ISSUE TITLE
It would be great if there was also a VS compatible extension.

### ISSUE THREAD

**Issue by TonyHCIR** [Azure/azure-sdk-for-java#34384] opened 2023-04-10 06:29 UTC
It would be great if there was also a VS compatible extension.

_Originally posted by @castdrian in https://github.com/ukoloff/win-ca/issues/50_

_Originally posted by @TonyHCIR in https://github.com/Azure/azure-sdk-for-java/issues/34383_

**Comment by alzimmermsft** [comment] 2023-04-10 12:20
Duplicate of #34383

**Closed by alzimmermsft** 2023-04-10 12:20 UTC
Labels: question, customer-reported, needs-triage
