### ISSUE TITLE
[BUG] RSS memory keeps going up

### ISSUE THREAD

**Issue by MarkoVk95** [Azure/azure-sdk-for-java#22500] opened 2021-06-24 16:37 UTC
**Describe the bug**
azure-messaging-eventhubs simple app that listens for events will continuously increase its RSS memory.

I've tried with multiple version of the SDK from 5.3.x to 5.7.x

`eventReceiver.consumeMessage();`

```
    public void consumeMessage(){
        try {
            EventProcessorClient eventProcessorClient = new EventProcessorClientBuilder()
                    .consumerGroup(EventHubClientBuilder.DEFAULT_CONSUMER_GROUP_NAME)
                    .connectionString(connectionString,"ns8003")
                    .processEvent(eventContext -> {
                    	System.out.println("Processed: ->" + eventContext.getEventData().getBodyAsString());
                    })
                    .processError(errorContext -> {
                        System.out.println(errorContext.getThrowable().getMessage());
                    })
                    .buildEventProcessorClient();
            
            System.out.println("start1");
            eventProcessorClient.start();
          
            
        }
        catch (Exception se){
            se.printStackTrace();
        }
       }
```

The app is ran through this DOCKERFILE

```
FROM mcr.microsoft.com/java/jre-headless:11-zulu-alpine
RUN addgroup -S intakegroup && adduser -S intakeuser -G intakegroup
USER intakeuser
ARG JAR_FILE=target/standalone-event-hub-receiver-1.0.0.0.jar
COPY ${JAR_FILE} standalone-event-hub-receiver.jar
ENTRYPOINT ["java","-jar","/standalone-event-hub-receiver.jar"]
```

And you can verify the RSS through the following command:

`docker exec -it 5d2a42b2ec1e ps -o pid,user,vsz,rss,comm,args`

I've also tried with another base image, Debian based.

```
FROM openjdk:11.0-jdk-buster
ARG JAR_FILE=target/standalone-event-hub-receiver-1.0.0.0.jar
COPY ${JAR_FILE} standalone-event-hub-receiver.jar
RUN apt-get update
RUN apt-get install -y procps
ENTRYPOINT ["java", \
"-Dcom.sun.management.jmxremote=true", \
"-Dcom.sun.management.jmxremote.port=9010", \
"-Dcom.sun.management.jmxremote.local.only=false", \
"-Dcom.sun.management.jmxremote.authenticate=false", \
"-Dcom.sun.management.jmxremote.ssl=false", \
"-Dcom.sun.management.jmxremote.rmi.port=9010", \
"-Djava.rmi.server.hostname=localhost", \
"-XX:+UnlockExperimentalVMOptions", \
"-XX:MaxRAMPercentage=50.0", \
"-XX:+UseContainerSupport", \
"-jar", \
"/standalone-event-hub-receiver.jar"]
```

For example, here are the logs when I run the second Debian Buster with OpenJDK11 image:

```
C:\Users\a-markov\Downloads\cases\04186\standaloneeventhubreceiver updated\standalone-event-hub-receiver>docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                    NAMES
30073b1407e0        markovk/sb-jdk11-buster   "java -Dcom.sun.mana…"   8 seconds ago       Up 6 seconds        0.0.0.0:8081->8080/tcp   jovial_hertz

C:\Users\a-markov\Downloads\cases\04186\standaloneeventhubreceiver updated\standalone-event-hub-receiver>docker exec -it 300 ps -e -o pid,user,vsz,rss,comm,args
  PID USER        VSZ   RSS COMMAND         COMMAND
    1 root     10417904 597796 java         java -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=   58 root       9388  3104 ps              ps -e -o pid,user,vsz,rss,comm,args

C:\Users\a-markov\Downloads\cases\04186\standaloneeventhubreceiver updated\standalone-event-hub-receiver>docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                    NAMES
30073b1407e0        markovk/sb-jdk11-buster   "java -Dcom.sun.mana…"   3 minutes ago       Up 3 minutes        0.0.0.0:8081->8080/tcp   jovial_hertz

C:\Users\a-markov\Downloads\cases\04186\standaloneeventhubreceiver updated\standalone-event-hub-receiver>docker exec -it 300 ps -e -o pid,user,vsz,rss,comm,args
  PID USER        VSZ   RSS COMMAND         COMMAND
    1 root     10417904 629936 java         java -Dcom.sun.management.jmxremote=
   63 root       9388  3112 ps              ps -e -o pid,user,vsz,rss,comm,args

C:\Users\a-markov\Downloads\cases\04186\standaloneeventhubreceiver updated\standalone-event-hub-receiver>docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                    NAMES
30073b1407e0        markovk/sb-jdk11-buster   "java -Dcom.sun.mana…"   35 minutes ago      Up 35 minutes       0.0.0.0:8081->8080/tcp   jovial_hertz

C:\Users\a-markov\Downloads\cases\04186\standaloneeventhubreceiver updated\standalone-event-hub-receiver>docker exec -it 300 ps -e -o pid,user,vsz,rss,comm,args
  PID USER        VSZ   RSS COMMAND         COMMAND
    1 root     10417904 641924 java         java -Dcom.sun.management.jmxremote=
   68 root       9388  3112 ps              ps -e -o pid,user,vsz,rss,comm,args

C:\Users\a-markov\Downloads\cases\04186\standaloneeventhubreceiver updated\standalone-event-hub-receiver>docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                    NAMES
30073b1407e0        markovk/sb-jdk11-buster   "java -Dcom.sun.mana…"   57 minutes ago      Up 57 minutes       0.0.0.0:8081->8080/tcp   jovial_hertz

C:\Users\a-markov\Downloads\cases\04186\standaloneeventhubreceiver updated\standalone-event-hub-receiver>docker exec -it 300 ps -e -o pid,user,vsz,rss,comm,args
  PID USER        VSZ   RSS COMMAND         COMMAND
    1 root     10417904 642984 java         java -Dcom.sun.management.jmxremote=
   74 root       9388  2992 ps              ps -e -o pid,user,vsz,rss,comm,args

C:\Users\a-markov\Downloads\cases\04186\standaloneeventhubreceiver updated\standalone-event-hub-receiver>docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                    NAMES
30073b1407e0        markovk/sb-jdk11-buster   "java -Dcom.sun.mana…"   About an hour ago   Up About an hour    0.0.0.0:8081->8080/tcp   jovial_hertz

C:\Users\a-markov\Downloads\cases\04186\standaloneeventhubreceiver updated\standalone-event-hub-receiver>docker exec -it 300 ps -e -o pid,user,vsz,rss,comm,args
  PID USER        VSZ   RSS COMMAND         COMMAND
    1 root     10417904 641356 java         java -Dcom.sun.management.jmxremote=
   79 root       9388  3112 ps              ps -e -o pid,user,vsz,rss,comm,args

C:\Users\a-markov\Downloads\cases\04186\standaloneeventhubreceiver updated\standalone-event-hub-receiver>docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                    NAMES
30073b1407e0        markovk/sb-jdk11-buster   "java -Dcom.sun.mana…"   2 hours ago         Up 2 hours          0.0.0.0:8081->8080/tcp   jovial_hertz

C:\Users\a-markov\Downloads\cases\04186\standaloneeventhubreceiver updated\standalone-event-hub-receiver>docker exec -it 300 ps -e -o pid,user,vsz,rss,comm,args
  PID USER        VSZ   RSS COMMAND         COMMAND
    1 root     10417904 642000 java         java -Dcom.sun.management.jmxremote=
   85 root       9388  3064 ps              ps -e -o pid,user,vsz,rss,comm,args

C:\Users\a-markov\Downloads\cases\04186\standaloneeventhubreceiver updated\standalone-event-hub-receiver>docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                    NAMES
30073b1407e0        markovk/sb-jdk11-buster   "java -Dcom.sun.mana…"   2 hours ago         Up 2 hours          0.0.0.0:8081->8080/tcp   jovial_hertz

C:\Users\a-markov\Downloads\cases\04186\standaloneeventhubreceiver updated\standalone-event-hub-receiver>docker exec -it 300 ps -e -o pid,user,vsz,rss,comm,args
  PID USER        VSZ   RSS COMMAND         COMMAND
    1 root     10417904 642372 java         java -Dcom.sun.management.jmxremote=
   90 root       9388  3108 ps              ps -e -o pid,user,vsz,rss,comm,args

C:\Users\a-markov\Downloads\cases\04186\standaloneeventhubreceiver updated\standalone-event-hub-receiver>docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                    NAMES
30073b1407e0        markovk/sb-jdk11-buster   "java -Dcom.sun.mana…"   2 hours ago         Up 2 hours          0.0.0.0:8081->8080/tcp   jovial_hertz

C:\Users\a-markov\Downloads\cases\04186\standaloneeventhubreceiver updated\standalone-event-hub-receiver>docker exec -it 300 ps -e -o pid,user,vsz,rss,comm,args
  PID USER        VSZ   RSS COMMAND         COMMAND
    1 root     10417904 642372 java         java -Dcom.sun.management.jmxremote=
   95 root       9388  3116 ps              ps -e -o pid,user,vsz,rss,comm,args

C:\Users\a-markov\Downloads\cases\04186\standaloneeventhubreceiver updated\standalone-event-hub-receiver>docker exec -it 300 ps -e -o pid,user,vsz,rss,comm,args
  PID USER        VSZ   RSS COMMAND         COMMAND
    1 root     10417904 642372 java         java -Dcom.sun.management.jmxremote=
  100 root       9388  2936 ps              ps -e -o pid,user,vsz,rss,comm,args

C:\Users\a-markov\Downloads\cases\04186\standaloneeventhubreceiver updated\standalone-event-hub-receiver>docker exec -it 300 ps -e -o pid,user,vsz,rss,comm,args
  PID USER        VSZ   RSS COMMAND         COMMAND
    1 root     10417904 642372 java         java -Dcom.sun.management.jmxremote=
  106 root       9388  3116 ps              ps -e -o pid,user,vsz,rss,comm,args

C:\Users\a-markov\Downloads\cases\04186\standaloneeventhubreceiver updated\standalone-event-hub-receiver>docker exec -it 300 ps -e -o pid,user,vsz,rss,comm,args
  PID USER        VSZ   RSS COMMAND         COMMAND
    1 root     10417904 642372 java         java -Dcom.sun.management.jmxremote=
  111 root       9388  3064 ps              ps -e -o pid,user,vsz,rss,comm,args

C:\Users\a-markov\Downloads\cases\04186\standaloneeventhubreceiver updated\standalone-event-hub-receiver>docker exec -it 300 ps -e -o pid,user,vsz,rss,comm,args
  PID USER        VSZ   RSS COMMAND         COMMAND
    1 root     10417904 642632 java         java -Dcom.sun.management.jmxremote=
  116 root       9388  3104 ps              ps -e -o pid,user,vsz,rss,comm,args

C:\Users\a-markov\Downloads\cases\04186\standaloneeventhubreceiver updated\standalone-event-hub-receiver>docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                    NAMES
30073b1407e0        markovk/sb-jdk11-buster   "java -Dcom.sun.mana…"   2 hours ago         Up 2 hours          0.0.0.0:8081->8080/tcp   jovial_hertz

C:\Users\a-markov\Downloads\cases\04186\standaloneeventhubreceiver updated\standalone-event-hub-receiver>docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                    NAMES
30073b1407e0        markovk/sb-jdk11-buster   "java -Dcom.sun.mana…"   3 hours ago         Up 3 hours          0.0.0.0:8081->8080/tcp   jovial_hertz

C:\Users\a-markov\Downloads\cases\04186\standaloneeventhubreceiver updated\standalone-event-hub-receiver>docker exec -it 300 ps -e -o pid,user,vsz,rss,comm,args
  PID USER        VSZ   RSS COMMAND         COMMAND
    1 root     10417904 642632 java         java -Dcom.sun.management.jmxremote=
  121 root       9388  2968 ps              ps -e -o pid,user,vsz,rss,comm,args

C:\Users\a-markov\Downloads\cases\04186\standaloneeventhubreceiver updated\standalone-event-hub-receiver>
```

What happens is that if I don't comment the consumeMessage() line out then the RSS memory will shoot up, although is almost logarithmic as it has an initial relatively high increase and then it keeps tapering down.

If I comment the function then the RSS memory starts and remains at a constant value. I've noticied that by changing the base image and by not using a checkpointStore the increase is noticeably lower, however, it's still there and over a longer period of time(weeks) it becomes noticeable.

I've also tried with the consumer.receiveFromPartition() method and with another popular Java docker image, and the issue is still there.

Is this behavior expected ?

**Comment by joshfree** [comment] 2021-06-28 17:59
Thanks for reporting this @MarkoVk95, @conniey could you please follow up?

/cc @YijunXieMS @mikeharder

**Comment by conniey** [comment] 2021-06-30 18:59
Thanks for reporting this... It is something we need to look into.

**Comment by gandhirajan** [comment] 2021-07-06 17:10
@conniey were you able to reproduce the issue at your end? Do you have any plans to address this in upcoming release? we could see this issue not only in event listening but also during event sending.

**Comment by conniey** [comment] 2021-07-06 17:27
@gandhirajan Hey. I am currently working on another performance issue with 5.7.0 but this is on our backlog to examine.

**Comment by gandhirajan** [comment] 2021-07-06 17:30
@conniey Thanks for the update. We will add all our findings on this shortly. But we would like you to prioritize this as well. Thanks again.

**Comment by conniey** [comment] 2021-07-27 18:17
We investigated and ran a sample application for several days. The RSS size does increase as the JVM is generating code, jitting, etc. but it does flatten out and stay constant over time.

> "-XX:MaxRAMPercentage=50.0", \

Choosing 50% of the RAM may not be ideal because you may be running on environments with constrained RAM.  You want memory to be at least: `Total Memory = Java Heap Size + At least Half a GB`. 

In general, you want to run your application in a production environment for several days to understand what the memory requirements are first before optimising or constraining it.

What we need is more information:
* Can you run your application with parameters: `-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=<path to dump file> -Xlog:gc*,gc+ref=debug,gc+phases=debug,gc+age=trace,safepoint:file=<path to GC.log file>`
    * This will generate a GC.log and a heap dump.

**Comment by gandhirajan** [comment] 2021-08-05 13:32
Hi @conniey , we tested out the behavior in our other application which sends messages to the event hub and we were able to simulate OOM error which in turn restarted the pods. The same application which runs old flavour (azure-eventhub - 3.2.0) of event hub SDK doesn't seems to have any issues.

The test details are as follows:

1) During the start of the test, the heap memory was 128 MB. The max limit was set to 1GB and RSS memory was set to 4GB.
2) When we started our perf test which sends messages to the event hub, the heap memory increased to 800 MB from 128 MB. Have attached the screenshot for the same - https://imgur.com/a/zeBaMQB
3) When we monitored the live objects in heap, we saw 2 leak candidates in the reference tree. Have attached the screenshot for the same - https://imgur.com/7d3IAqf
4) We kept the application idle for 8 hours and started the test again the next day, the heap memory was stable at 870 MB. Have attached the screenshot for the same - https://imgur.com/a/96qsisu
5) Again we kept the application idle for 8 hours and started the test again the next day, the heap memory increased to 1GB and the application crashed due to OOO error and the pods are restarted.

Please let us know if you are looking for any additional info.

**Comment by conniey** [comment] 2021-08-05 16:27
@gandhirajan What is the frequency at which you are sending messages? Are there periods of idleness in your application?

@ki1729 and I are looking into a bug that may be related to producing events. #20660

**Comment by gandhirajan** [comment] 2021-08-05 16:58
Hi @conniey  Thanks for the response. We send messages within loop continuously for testing. We kept the application idle to monitor the heap memory behavior. But in the actual production environment, we will be sending 6M messages per day and no defined frequency for the same as clients across the globe will hit the application endpoint. Also in production environment, there is no idleness. Also in our case, we are caching EventHubProducerClient object and not recreating it. So i m not sure how this is related to #20660

We have MSFT support case opened for this. Will it be possible for you guys to get on to call with us so that we can show the problem and discuss more?

**Comment by conniey** [comment] 2021-08-06 22:45
This could be related to: https://github.com/Azure/azure-sdk-for-java/pull/23381 since you mentioned the producer.

**Comment by ramya-rao-a** [comment] 2021-09-14 22:44
@conniey the linked PR #23381 has been merged for a while. Did we release an update with the fix? If so, should we declare this issue to be addressed?

**Comment by conniey** [comment] 2021-09-14 22:46
We released an update for this mid-August. So it should be addressed.

**Closed by conniey** 2021-09-14 22:46 UTC
Labels: question, Event Hubs, Client, customer-reported, pillar-performance
