### ISSUE TITLE
[BUG] Blob Storage's downloadToFile deletes files after `toFuture` is called

### ISSUE THREAD

**Issue by hongee** [Azure/azure-sdk-for-java#8716] opened 2020-03-05 03:05 UTC
**Describe the bug**
After calling `downloadToFile` (with or without overwrite = true), the operation succeeds, and the file, for a brief moment, is successfully downloaded and persisted on disk. However, if a `toFuture` subscriber is attached and then subsequently converted to a Scala Future (using either Scala's built in compat, or via Reactor's Scala extensions), a `cancel` signal is fired, and the handler here fires and deletes the file:
 https://github.com/Azure/azure-sdk-for-java/blob/b59f999110e7a12004b51918b04b7ede444824a5/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/BlobAsyncClientBase.java#L1039 

**edit** - quick update - Mono's `toFuture` does indeed fire off a cancel: https://github.com/reactor/reactor-core/blob/c6b75f2578ee5f201ac06add2239322cc5b7bfcd/reactor-core/src/main/java/reactor/core/publisher/MonoToCompletableFuture.java#L59, which makes the `downloadToFile` methods impossible to use if a CompletableFuture is desired. May I suggest loosening the check for deletion? 😄 

I'm not very familiar with Reactor, and would be happy to find out if I'm doing something wrong, or if there's a workaround. We are on a Scala codebase that relies heavily on Futures, so not using a Future is not quite an option.

***Exception or Stack Trace***
N/A

**To Reproduce**
See the following snippet

***Code Snippet***
```
blobContainerClient
  .getBlobAsyncClient(myBlobKey)
  .downloadToFile("my/path")
  .onComplete { ...file is fine here... }
  .doFinally { ... eventually `cancel` is fired instead of `complete` ... }
  .toFuture.asScala.map { ... file disappears ... }
```

**Expected behavior**
Don't delete my file :(

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: macOS Catalina
 - IDE : Intellij Ultimate
 - Version of the Library used: 12.4.0

**Additional context**
Could be related to https://github.com/spring-projects/spring-framework/issues/22952, even though this appears to be fixed?

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by rickle-msft** [comment] 2020-03-09 18:47
@hongee Thank you for reporting this, and sorry for the delay! I am just now noticing we haven't responded.

We do need to delete files in the case of cancellation because we don't want to leave unwanted/incomplete/corrupted files hanging around on the disk. So our best path forward is to try to understand why Reactor has this behavior when being converted to a Future. @anuchandy, do you have any insight into why Reactor would be doing this? Or if perhaps there is another safe way of cleaning up resources that would permit customers to use Futures more readily?

**Comment by hongee** [comment] 2020-03-10 18:33
Thanks for looking into this! :) Yeah it doesn't seem like wrong behavior - just not sure why toFuture sends a close signal after complete, and why those aren't mutually exclusive. Not familiar enough to say how possible this is, but perhaps a flag can be set if the completion signal is received, and a close coming after complete could be ignored?

Currently we're using a hacky workaround where we pass a symlink of the desired path to the method so at least we don't lose the downloaded file :)

**Comment by rickle-msft** [comment] 2020-03-10 18:36
That's a good suggestion. I can investigate that a bit along with trying to understand Reactor's behavior a bit better.

**Comment by anuchandy** [comment] 2020-03-10 19:53
@rickle-msft - I've opened an issue/question https://github.com/reactor/reactor-core/issues/2070 to understand more about this behavior.

**Comment by anuchandy** [comment] 2020-03-11 16:12
The issue is fixed in the reactor-core.

**Comment by Petermarcu** [comment] 2020-07-30 15:18
Can this issue be closed?

**Closed** 2020-07-31 02:53 UTC
Labels: Client, Service Attention, Storage, customer-reported
