### ISSUE TITLE
[BUG] JacksonAdapter Failed to Retrieve MethodHandles

### ISSUE THREAD

**Issue by garantir-km** [Azure/azure-sdk-for-java#23130] opened 2021-07-22 04:49 UTC
**Describe the bug**
Cannot instantiate ClientSecretCredential via ClientSecretCredentialBuilder.build()

***Exception or Stack Trace***
```
21:27:13.053 [main] DEBUG com.azure.core.util.serializer.JacksonAdapter - Failed to retrieve MethodHandles used to set coercion configurations. Setting coercion configurations will be skipped.
java.lang.NoSuchMethodException: no such method: com.fasterxml.jackson.databind.ObjectMapper.coercionConfigDefaults()MutableCoercionConfig/invokeVirtual
	at java.lang.invoke.MemberName.makeAccessException(MemberName.java:871)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1003)
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1386)
	at java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:861)
	at com.azure.core.util.serializer.JacksonAdapter.<clinit>(JacksonAdapter.java:81)
	at com.azure.identity.implementation.IdentityClient.<clinit>(IdentityClient.java:96)
	at com.azure.identity.implementation.IdentityClientBuilder.build(IdentityClientBuilder.java:113)
	at com.azure.identity.ClientSecretCredential.<init>(ClientSecretCredential.java:50)
	at com.azure.identity.ClientSecretCredentialBuilder.build(ClientSecretCredentialBuilder.java:76)
	at azure.keyvault.CreateKeyPair.main(CreateKeyPair.java:24)
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ObjectMapper.coercionConfigDefaults()Lcom/fasterxml/jackson/databind/cfg/MutableCoercionConfig;
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000)
	... 8 common frames omitted
Exception in thread "main" java.lang.VerifyError: Bad return type
Exception Details:
  Location:
    com/fasterxml/jackson/databind/cfg/MapperBuilder.streamFactory()Lcom/fasterxml/jackson/core/TokenStreamFactory; @7: areturn
  Reason:
    Type 'com/fasterxml/jackson/core/JsonFactory' (current frame, stack[0]) is not assignable to 'com/fasterxml/jackson/core/TokenStreamFactory' (from method signature)
  Current Frame:
    bci: @7
    flags: { }
    locals: { 'com/fasterxml/jackson/databind/cfg/MapperBuilder' }
    stack: { 'com/fasterxml/jackson/core/JsonFactory' }
  Bytecode:
    0x0000000: 2ab4 0002 b600 08b0                    

	at com.fasterxml.jackson.databind.json.JsonMapper.builder(JsonMapper.java:114)
	at com.azure.core.util.serializer.JacksonAdapter.<init>(JacksonAdapter.java:130)
	at com.azure.core.util.serializer.JacksonAdapter.createDefaultSerializerAdapter(JacksonAdapter.java:189)
	at com.azure.identity.implementation.IdentityClient.<clinit>(IdentityClient.java:96)
	at com.azure.identity.implementation.IdentityClientBuilder.build(IdentityClientBuilder.java:113)
	at com.azure.identity.ClientSecretCredential.<init>(ClientSecretCredential.java:50)
	at com.azure.identity.ClientSecretCredentialBuilder.build(ClientSecretCredentialBuilder.java:76)
	at azure.keyvault.CreateKeyPair.main(CreateKeyPair.java:24)
```
**To Reproduce**
Include azure-identity version 1.3.3 as the only entry in pom.xml. Then attempt to build a ClientSecretCredential object via a ClientSecretCredentialBuilder.

***Code Snippet***
```java
ClientSecretCredential credential = new ClientSecretCredentialBuilder()
                .tenantId(tenantId)
                .clientId(clientId)
                .clientSecret(clientSecret)
                .build();
```

**Expected behavior**
Successfully create the credential without any error.

**Setup (please complete the following information):**
 - OS: Windows
 - IDE: Eclipse
 - Library/Libraries: com.azure:azure-identity:1.3.3 

**Additional context**
I have seen the other bug reports on here about the Jackson library conflict but none of the recommendations have worked for me. I only have com.azure:azure-identity:1.3.3 in my pom.xml and I have done a clean on the environment. My other Azure code works fine (when I revert my pom.xml) so I don't think there is an issue with my IDE or computer.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ X] Bug Description Added
- [ X] Repro Steps Added
- [ X] Setup information Added

**Comment by alzimmermsft** [comment] 2021-07-22 16:01
Thank you for reporting this issue @garantir-km, I'll take a look into what is causing this but I have one question before starting. When running your application is it hosted in a non-JVM runtime such as Databricks, Spark, Spring, etc? Where there is a potential that the runtime has opinionated dependencies already including which could be altering the final classpath.

**Comment by garantir-km** [comment] 2021-07-22 16:32
Thanks for the quick response! No non-JVM runtime but I was doing my tests in Eclipse. Interestingly, if I revert to version 1.2.0 everything works fine.

**Comment by alzimmermsft** [comment] 2021-07-22 17:02
Lowering the `azure-identity` dependency to `1.2.0` makes sense on resolving this issue. Starting with `azure-identity` `1.2.5`, the underlying `azure-core` library began supporting both Jackson `2.11` and `2.12` which required the, failing in this issue, reflection calls to enable configuring `2.12` without breaking on class not found or method not found exceptions when Jackson is resolved to `2.11`.

This error reported in this issue is a bit odd to me though, as this is failing on `JsonFactory` isn't assignable to type `TokenStreamFactory`. Looking at `JsonFactory` it began sub-typing from `TokenStreamFactory` beginning in Jackson `2.10`:

- Jackson 2.9 JsonFactory: https://www.javadoc.io/doc/com.fasterxml.jackson.core/jackson-core/2.9.0/com/fasterxml/jackson/core/JsonFactory.html
- Jackson 2.10 JasonFactory: https://www.javadoc.io/doc/com.fasterxml.jackson.core/jackson-core/2.10.0/com/fasterxml/jackson/core/JsonFactory.html

**Comment by garantir-km** [comment] 2021-07-22 17:27
I see. Is the recommendation to stay with 1.2.0 for right now or do I have something wrong in my environment?

**Comment by alzimmermsft** [comment] 2021-07-22 18:00
Is it possible to run your tests using Maven in the command line? This should help verify whether or not the Eclipse testing environment has configurations affecting the classpath. If it still fails here I'd recommend downgrading until the root of this issue is found and resolved. But if Maven is able to run the tests without error there is likely a configuration in Eclipse resulting in the error.

**Comment by saikirangit** [comment] 2021-07-26 19:49
@alzimmermsft I have same issue with my environment. I did downgrade to 1.2.0 but issue still exists

Azure Identity Version: 1.2.0
azure-security-keyvault-certificates: 4.2.1

Spring boot Version 2.5.3

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.http.converter.xml.MappingJackson2XmlHttpMessageConverter]: Factory method 'mappingJackson2XmlHttpMessageConverter' threw exception; nested exception is java.lang.NoSuchMethodError: com.fasterxml.jackson.dataformat.xml.XmlMapper.coercionConfigDefaults()Lcom/fasterxml/jackson/databind/cfg/MutableCoercionConfig;
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 149 more
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.dataformat.xml.XmlMapper.coercionConfigDefaults()Lcom/fasterxml/jackson/databind/cfg/MutableCoercionConfig;
	at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:176)
	at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:145)
	at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:141)
	at org.springframework.http.converter.json.Jackson2ObjectMapperBuilder$XmlObjectMapperInitializer.create(Jackson2ObjectMapperBuilder.java:914)
	at org.springframework.http.converter.json.Jackson2ObjectMapperBuilder.build(Jackson2ObjectMapperBuilder.java:673)
	at org.springframework.boot.autoconfigure.http.JacksonHttpMessageConvertersConfiguration$MappingJackson2XmlHttpMessageConverterConfiguration.mappingJackson2XmlHttpMessageConverter(JacksonHttpMessageConvertersConfiguration.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 150 more

**Comment by garantir-km** [comment] 2021-07-26 20:31
I ran the test from the command line and I could have sworn I had one successful run. However, now when I run it I get the error. I definitely have something strange going on with my environment but everything else is working fine so I am not sure I can fully say that the environment is the cause.

**Comment by alzimmermsft** [comment] 2021-07-27 15:56
Thank you for checking @garantir-km, and thank you for the additional scenario @saikirangit. I'll get back to you soon with an update on the investigation.

**Comment by garantir-km** [comment] 2021-08-02 19:36
Interesting find. Unfortunately it did affect the runtime of the application as well. I have noticed some strange issues with Eclipse but even when I ran the code outside of my IDE things didn't work correctly. Interestingly, when I ran the code outside of Eclipse I didn't see the DEBUG error but the code did not work correctly. When I changed the version of the library then everything worked both in Eclipse as well as from the command line.

**Comment by alzimmermsft** [comment] 2021-08-04 00:12
@garantir-km, in your application `azure-identity` is the only dependencies? And this isn't being ran in Azure Functions or a similar environment, right?

**Comment by garantir-km** [comment] 2021-08-04 03:47
That is correct, just the azure-identity as the dependency. The application is just run on my laptop from the command line or from within Eclipse. It was just a simple little test harness to isolate the problem and figure out what was causing the error in our actual application.

**Comment by alzimmermsft** [comment] 2021-08-04 18:26
Could you include a dependency tree of your application as using `azure-identity` alone I'm not able to reproduce the issue.

**Closed** 2021-08-31 08:02 UTC
Labels: question, Client, Azure.Core, customer-reported, needs-author-feedback, no-recent-activity
