### ISSUE TITLE
[QUERY] CosmosTemplate ignores CosmosPageRequest's offset

### ISSUE THREAD

**Issue by sburlyaev** [Azure/azure-sdk-for-java#17924] opened 2020-12-02 09:05 UTC
**Question**
Why does `com.azure.spring.data.cosmos.core.CosmosTemplate::paginationQuery` ignore `com.azure.spring.data.cosmos.core.query.CosmosPageRequest`'s `offset` argument?

***Why is this not a Bug or a feature Request?***
Maybe it is.

**Setup:**
 - com.azure:azure-spring-data-cosmos:3.1.0

**Comment by kushagraThapar** [comment] 2020-12-02 17:32
@mbhaskar  - please take a look at this issue.

**Comment by kushagraThapar** [comment] 2021-03-09 21:29
@sburlyaev  - this issue seems to be a duplicate of this https://github.com/Azure/azure-sdk-for-java/issues/17927

**Comment by kushagraThapar** [comment] 2021-03-09 21:29
Closing it here.

**Closed by kushagraThapar** 2021-03-09 21:29 UTC
Labels: Client, azure-spring-cosmos, customer-reported, question
