### ISSUE TITLE
Upload data via getBlobOutputStream cause to java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by ihudedi** [Azure/azure-sdk-for-java#18313] opened 2020-12-22 13:09 UTC
Hi ,
I am using azure blob storage version 12.9.0
I am trying to upload data to azure using the code
byte []bytes= taken from input stream.
BlobOutputStream blobOutputStream =  blobClient.getBlockBlobClient().getBlobOutputStream(true);
I am getting byte[] in a loop to upload
I invoke blobOutputStream.write(bytes);
This call only save the bytes in buffer in memory.
Only close method will send all buffer to azure.
When I have big data to transfer  I am getting OutOfMemory
How can write the data to the server in the middle of the transfer.
flush doesn't do anything.
Thanks,
Itay

**Comment by rickle-msft** [comment] 2020-12-22 18:32
Hi, @ihudedi. Thanks for opening this issue. You are correct that flush at the moment doesn't do anything #6310 is tracking that, and there are some details of the internals that make it a bit tricky. We can use this issue as an impetus for getting to that fix, though. 

That said, the output stream still should only be holding up to a couple blocks of memory at a time before it sends data to the service and reuses the buffer. Are you setting any heap memory constraints on your jvm? Or is there anything else going on in the jvm instance that might be consuming memory as well?

I'd recommend configuring the ParallelTransferOptions inside of the BlockBlobOutputStream options. The javadocs should explain this more fully, but some of the parameters available on these options should allow you to effectively limit how much memory we'll use at once. You might also look over [this](https://github.com/Azure/azure-sdk-for-java/issues/10823#issuecomment-626082185) issue and solution to see if it might help.

**Comment by ihudedi** [comment] 2020-12-22 20:28
Hi @rickle-msft 
I am using -XX:+UseG1GC -Xmx512m
The issue that only close method send the all buffer,It doesn;t create file in the middle of the transfer.
If I trying to upload big file from the azure portal nothing is uploaded until action is completed,Don;t see any file in the transfer.

**Comment by rickle-msft** [comment] 2020-12-22 21:15
I see. Yea so settng the heap size to 512 was consistent with the configuration in #10823, so I think the solutions there might be helpful. Have you tried looking through that thread yet?

As for when the file is created, this actually possibly won't change if/when we add flush. The reason being is that the method works via a series of stageBlock calls followed by a commitBlockList. Even if we flush the data to the service by staging a block, the file won't show up in the portal until we commit the block list, which currently happens in close.

We can explore the route of flush also committing blocks as well, but (and this is sort of just dev notes for the discussion on my team at this point, feel free to ignore...) we would have to probably then lock on the etag for a future commit, and also either store or retrieve the block list. We'd also have to ensure that even if a small amount of data is flushed at the beginning that we'd do a stage block call rather than a put blob so we can reuse the block in a future commit. Further, this also makes the flush/close pattern really poor for small files as it'll convert it from a single request to multiple requests (possibly even four+ in this paradigm. flush would do at least a stage and commit. Then close would also probably have to flush to be non breaking which is another stage and commit). So we should probably not commit on flush and only stage. And then for people with small files recommend skipping flush. This might actually be breaking if we add it without guarding it behind a flag, too.

**Comment by ihudedi** [comment] 2020-12-22 21:40
Hi @rickle-msft 
I tried to add
            ParallelTransferOptions parallelTransferOptions = new ParallelTransferOptions().setBlockSizeLong(Long.valueOf(BlobClient.BLOB_DEFAULT_UPLOAD_BLOCK_SIZE)).setMaxSingleUploadSizeLong(Long.valueOf(BlobClient.BLOB_DEFAULT_UPLOAD_BLOCK_SIZE)).setMaxConcurrency(1);
to the blockBlobOutputStreamOptions with no success.still it buffer all the file (800MB) and throw
java.lang.OutOfMemoryError: Java heap space
Maybe I need another params.I am using streaming to upload the file via getBlobOutputStream and then write byte array.
Thanks,
Itay

**Comment by rickle-msft** [comment] 2020-12-22 22:49
The relevant comment from the other thread I mentioned is

> System.setProperty("reactor.bufferSize.small", "5")
System.setProperty("reactor.bufferSize.x", "5")
// The upload code here, blocksize set to 4MB
// ParallelTransferOptions(4 * 1024 * 1024, null, { println("Uploaded $it") }, null), null, null, null, null,null)

Have you tried setting those system properties at all? 

Additionally, if you could try using BlobClient.upload instead, that would also be interesting information for this investigation

**Comment by ihudedi** [comment] 2020-12-23 12:52
Hi @rickle-msft 
When I try blobClient.upload(inputStream,length) - I am getting OOM when I defined xmx512
When I add the System.setProperty("reactor.bufferSize.small", "5")
System.setProperty("reactor.bufferSize.x", "5")
It's succeeded

**Comment by rickle-msft** [comment] 2020-12-23 19:24
In general, I will not be able to tell you what the correct values are. Configuration options that deal with concurrency and memory usage are highly application dependent, so it will be up to you to experiment with what performs optimally in your environment. I recommend setting up testing a fairly large variety of combinations of these configurations and concluding what is best from that. 

As for ParallelTransferOptions, I'll refer you to the [documentation](https://azuresdkdocs.blob.core.windows.net/$web/java/azure-storage-blob/12.9.0/index.html). The description of each of these fields details how it affects the network/parallel behavior of the sdk. Using that information should help give a direction for your testing. 

For the reactor system properties, again there is no "correct" value. If you are seeing that your application is succeeding, then I would say it is approaching "correct" for your environment. There is an asynchronous framework sitting underneath the sdk. Those system properties define how large the queus are for holding requests/response items that help determine how eagerly the framework should be creating/processing requests.

**Comment by ihudedi** [comment] 2020-12-23 21:00
Hi @rickle-msft 
I understand but what is the meaning of 
reactor.bufferSize.small
reactor.bufferSize.x
Thanks,
Itay

**Comment by rickle-msft** [comment] 2020-12-23 21:12
Those system properties define how large the queus are for holding requests/response items that help determine how eagerly the framework should be creating/processing requests. Documentation for them is [here](https://github.com/reactor/reactor-core/blob/a8022380f7d1eb9ef5bdcf0a9e0366d3dad534df/reactor-core/src/main/java/reactor/util/concurrent/Queues.java#L85)

**Comment by ihudedi** [comment] 2020-12-31 14:45
Hi @rickle-msft 
The main issue is that I can transfer large file but when it uploaded completely the memory isn't released/decreased only
after a long time or when I run System.gc() manually after some time.
Is this a default behaviour?
If the memory isn't released in the next treansfer I am getting heap space error.
Thanks,
Itay

**Comment by gapra-msft** [comment] 2021-03-17 16:53
This question looks to be a duplicate of https://github.com/Azure/azure-sdk-for-java/issues/18655. @ihudedi Can we close this issue and continue the conversation on the other thread?

**Comment by ihudedi** [comment] 2021-03-18 08:29
Hi @gapra-msft
It's the same issue.
Thanks,
Itay

**Closed** 2021-03-18 17:03 UTC
Labels: Client, Storage, customer-reported, question

**Comment by d-schmidt** [comment] 2021-06-22 07:27
Combining low blocksize and the reactor.bufferSize properties was the only way to keep my app from below 500MB heap. Blocksize or the properties alone didn't help, because reactor still acts like a fat kid at a Chinese all-you-can-eat buffet.

**Comment by d-schmidt** [comment] 2021-06-22 07:35
According to the linked reactor [Queues](https://github.com/reactor/reactor-core/blob/a8022380f7d1eb9ef5bdcf0a9e0366d3dad534df/reactor-core/src/main/java/reactor/util/concurrent/Queues.java#L79) class, this is the possible minimum:

        System.setProperty("reactor.bufferSize.small", "16"); // limit concurrency
        System.setProperty("reactor.bufferSize.x", "8"); // limit prefetch
