### ISSUE TITLE
Unable to instantiate with DefaultAzureCredential despite setting required Environment Variables

### ISSUE THREAD

**Issue by noemi616** [Azure/azure-sdk-for-java#10539] opened 2020-04-28 00:31 UTC
**Describe the bug**
Trying to run this [AKV client sample app](https://docs.microsoft.com/en-us/azure/key-vault/secrets/quick-create-java) but instead getting " Unable to initialize main class com.keyvault.quickstart.App" error.  It seems like DefaultAzureCredentialBuilder could not instantiate an instance of DefaultAzureCredential.

***Exception or Stack Trace***
PS C:\Users\xxxx\akv-java> java -cp target/akv-java-1.0-SNAPSHOT.jar com.keyvault.quickstart.App -verbose
Error: Unable to initialize main class com.keyvault.quickstart.App
Caused by: java.lang.NoClassDefFoundError: com/azure/core/credential/TokenCredential

**To Reproduce**
Followed the steps in the [tutorial](https://docs.microsoft.com/en-us/azure/key-vault/secrets/quick-create-java), as follows:

1. Created the Maven project and AKV resource.
2. Created service principal.
3. Added access policy to the service principal.
![image](https://user-images.githubusercontent.com/16081468/80433022-211e5a80-8939-11ea-9d4e-36f1afa9572a.png)
4. Configured all environment variables.
![image](https://user-images.githubusercontent.com/16081468/80433217-a7d33780-8939-11ea-911a-b50375f5a462.png)
5. Source code looks something like below:
![image](https://user-images.githubusercontent.com/16081468/80433375-14e6cd00-893a-11ea-90b6-2addb7e11253.png)
6. pom.xml:
![image](https://user-images.githubusercontent.com/16081468/80433399-2a5bf700-893a-11ea-8b80-067d1a778cbd.png)

***Code Snippet***
See above.

**Expected behavior**
Calling DefaultAzureCredential.build() should succeed, and would be used to authenticate to AKV.

**Screenshots**
See above

**Setup (please complete the following information):**
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Program Files\Maven\apache-maven-3.6.3\bin\..
Java version: 11.0.6, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-11.0.6
Default locale: en_AU, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Additional context**
None

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment] 2020-04-29 18:11
@alzimmermsft @g2vinay could you please assist with getting this app sample running (dependency version mismatch?)

**Comment by alzimmermsft** [comment] 2020-04-29 18:26
Hi @noemi616, the listed versions of Azure Identity (1.0.5) and KeyVault Secrets (4.1.0) have different common dependency versions, would you mind trying KeyVault Secrets 4.1.2 which has dependency versions aligned with the Identity version being used. Another option would be using the Azure client BOM (`azure-sdk-bom`) which has verified common dependencies of the modules listed.

**azure-sdk-bom Example**

```xml
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-sdk-bom</artifactId>
      <version>1.0.0</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>
  
<dependencies>
  <dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-identity</artifactId>
  </dependency>
  <dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-security-keyvault-secrets</artifactId>
  </dependency>
</dependencies>
```

https://search.maven.org/artifact/com.azure/azure-sdk-bom/1.0.0/pom

**Comment by alzimmermsft** [comment] 2020-05-06 21:08
@noemi616 was the comment above able to resolve this issue or are you still running into problems?

**Comment by noemi616** [comment] 2020-05-13 01:54
@alzimmermsft - sorry for the delay - let me try this out.

**Comment by g2vinay** [comment] 2020-07-13 17:17
@noemi616.
Hopefully that resolved the issue for you.
We're closing this issue now.
Feel free to let us know If you'd like to reopen this issue.
Thank you,
Vinay.

**Closed by g2vinay** 2020-07-13 17:17 UTC
Labels: Azure.Identity, customer-reported, question

**Comment by rishabhgpt** [comment] 2021-01-08 15:56
Issue still exists
Caused by: java.lang.ClassNotFoundException: io.netty.handler.logging.LoggingHandler

dep tree:

`[INFO] +- com.azure:azure-identity:jar:1.0.5:compile
[INFO] |  +- com.azure:azure-core:jar:1.4.0:compile
[INFO] |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.9.7:compile
[INFO] |  |  |  +- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.9.7:compile
[INFO] |  |  |  +- org.codehaus.woodstox:stax2-api:jar:3.1.4:compile
[INFO] |  |  |  \- com.fasterxml.woodstox:woodstox-core:jar:5.0.3:compile
[INFO] |  |  +- io.projectreactor:reactor-core:jar:3.1.10.RELEASE:compile
[INFO] |  |  |  \- org.reactivestreams:reactive-streams:jar:1.0.2:compile
[INFO] |  |  \- io.netty:netty-tcnative-boringssl-static:jar:2.0.27.Final:compile
[INFO] |  +- com.microsoft.azure:msal4j:jar:0.5.0-preview:compile
[INFO] |  |  \- org.apache.commons:commons-lang3:jar:3.7:compile
[INFO] |  +- com.nimbusds:oauth2-oidc-sdk:jar:6.14:compile
[INFO] |  |  +- com.github.stephenc.jcip:jcip-annotations:jar:1.0-1:compile
[INFO] |  |  \- com.nimbusds:lang-tag:jar:1.5:compile (version selected from constraint [1.4.3,))
[INFO] |  +- org.nanohttpd:nanohttpd:jar:2.3.1:compile
[INFO] |  \- net.java.dev.jna:jna-platform:jar:4.5.2:compile
[INFO] |     \- net.java.dev.jna:jna:jar:4.5.2:compile
[INFO] \- com.azure:azure-security-keyvault-secrets:jar:4.1.2:compile
[INFO]    \- com.azure:azure-core-http-netty:jar:1.5.0:compile
[INFO]       +- io.netty:netty-handler:jar:4.1.29.Final:compile
[INFO]       |  +- io.netty:netty-transport:jar:4.1.29.Final:compile
[INFO]       |  |  \- io.netty:netty-resolver:jar:4.1.29.Final:compile
[INFO]       |  \- io.netty:netty-codec:jar:4.1.29.Final:compile
[INFO]       +- io.netty:netty-handler-proxy:jar:4.1.29.Final:compile
[INFO]       |  \- io.netty:netty-codec-socks:jar:4.1.29.Final:compile
[INFO]       +- io.netty:netty-buffer:jar:4.1.29.Final:compile
[INFO]       |  \- io.netty:netty-common:jar:4.1.29.Final:compile
[INFO]       +- io.netty:netty-codec-http:jar:4.1.29.Final:compile
[INFO]       +- io.netty:netty-codec-http2:jar:4.1.29.Final:compile
[INFO]       +- io.netty:netty-transport-native-unix-common:jar:4.1.29.Final:compile
[INFO]       +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.29.Final:compile
[INFO]       \- io.projectreactor.netty:reactor-netty:jar:0.9.5.RELEASE:compile
`

**Comment by RethinkLedgers** [comment] 2022-01-03 00:18
I ran into a similar issue
java -cp test-App.jar com.keyvault.secrets.quickstart.App
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/azure/core/credential/TokenCredential
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.azure.core.credential.TokenCredential
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 7 more
