### ISSUE TITLE
Azure stored file has different MD5 checksum than local file?? 

### ISSUE THREAD

**Issue by harisingh-highq** [Azure/azure-sdk-for-java#17758] opened 2020-11-23 09:30 UTC
If I compare Azure stored file getContentMd5() with local file (same file) MD5, it is not matched. Is it valid behavior? 

Can anyone please clarify it?

**Comment by gapra-msft** [comment] 2020-11-23 19:19
Hi @harisingh-highq 

Thanks for posting this question.

Could you please provide a code sample so we can try to reproduce what you are seeing? The md5 of the data should match that returned by getContentMd5()

**Comment by harisingh-highq** [comment] 2020-11-24 07:07
Hi @gapra-msft 

Thank you for your quick response.

FYI, I calculate local file MD5 with [online utility](http://onlinemd5.com/)  OR using command prompt
![image](https://user-images.githubusercontent.com/33862788/100059821-b17e3880-2e51-11eb-8c68-889029e29581.png)


I tried with below code solutions, no one is matched with local file MD5:-

1st Try:-
java.security.MessageDigest md5 = java.security.MessageDigest.getInstance("MD5");
md5.update(blobClient.getProperties().getContentMd5());
StringBuilder uploadedFileMD5= new StringBuilder();
if (md5 != null) {
for (byte b : md5.digest()) {
uploadedFileMD5.append(String.format("%02x", b));
}
}

2nd Try:-
String uploadedFileMD5= Base64.encodeBase64String(prop.getContentMd5());

3rd Try:-
String uploadedFileMD5= Base64.encodeBase64String(MessageDigest.getInstance("MD5").digest(prop.getContentMd5()));

**Comment by harisingh-highq** [comment] 2020-11-25 15:43
Hi @gapra-msft

I would like to inform you that now local file MD5 and azure store file MD is getting matched with above solution.

Thank you so much for detailed solution. Really your help is appreciable.

**Comment by gapra-msft** [comment] 2020-11-25 17:02
@harisingh-highq Great to hear! Since your issue seems to have been resolved, I will go ahead and close this issue.

**Closed by gapra-msft** 2020-11-25 17:02 UTC
Labels: Client, Storage, customer-reported, question
