### ISSUE TITLE
[FEATURE REQ] Add on behalf of token support in identity library

### ISSUE THREAD

**Issue by jialindai** [Azure/azure-sdk-for-java#6924] opened 2019-12-17 09:12 UTC
**Is your feature request related to a problem? Please describe.**
Currently azure spring boot integration use on behalf of token to query graph API:
1. Use user token (together with client credential) to get one access token to graph API
2. Call graph API with the access token

This feature is needed for azure spring boot integration to upgrade to identity library.

**Describe the solution you'd like**
Identity library should provide same functionality. 

**Additional context**
The code of azure spring boot which utilize the on behalf of token can be found at:
https://github.com/microsoft/azure-spring-boot/blob/master/azure-spring-boot/src/main/java/com/microsoft/azure/spring/autoconfigure/aad/AADOAuth2UserService.java

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by jianghaolu** [comment] 2019-12-17 21:14
Hi @jialindai, for now you will need to use the msal4j library to complete the on-behalf flow: https://github.com/AzureAD/microsoft-authentication-library-for-java. We will also integrate the feature in the azure-identity library in an upcoming release.

**Comment by jialindai** [comment] 2019-12-26 02:43
Thanks for the information, we will target msal lib.

**Comment by jialindai** [comment] 2019-12-26 02:44
In the meantime, is there a timeline about the release containing on behalf flow?

**Comment by joshfree** [comment] 2019-12-28 04:35
Reopening issue to track the OBO auth flow support request

**Comment by jianghaolu** [comment] 2021-08-27 23:52
I believe this is being worked on by @g2vinay - please close & link if duplicate

**Comment by g2vinay** [comment] 2021-09-03 17:59
This is a duplicate of https://github.com/Azure/azure-sdk-for-java/issues/22363
We will be shipping this out in the September beta release of Identity SDK.

**Closed by g2vinay** 2021-09-03 17:59 UTC
Labels: Client, Azure.Identity, feature-request
