### ISSUE TITLE
[BUG] The SDK should shutdown the callback servicing threadpool, if the related topic or subscription is deleted

### ISSUE THREAD

**Issue by piyushnayak** [Azure/azure-sdk-for-java#11137] opened 2020-05-13 09:07 UTC
**Describe the bug**
The SDK should shutdown the callback servicing threadpool, if the related topic or subscription is deleted

***Exception or Stack Trace***
05/06 14:58:58 [pool-9-thread-9] INFO  Completeing all pending receive and updateState operation on the receiver to 'test-get-subs-msg/Subscriptions/subscription-send-receive'
05/06 14:58:58 [pool-9-thread-9] ERROR Receiving message from entity 'test-get-subs-msg/Subscriptions/subscription-send-receive' failed.
com.microsoft.azure.servicebus.primitives.MessagingEntityNotFoundException: The messaging entity 'sb://psbsspace.servicebus.windows.net/test-get-subs-msg/Subscriptions/subscription
-send-receive' could not be found. To know more visit https://aka.ms/sbResourceMgrExceptions.  TrackingId:5c6ec785-b880-4c72-9fe9-c62b7e35817d_G21, SystemTracker:psbsspace.serviceb
us.windows.net:test-get-subs-msg/Subscriptions/subscription-send-receive, Timestamp:2020-05-06T09:29:24
        at com.microsoft.azure.servicebus.primitives.ExceptionUtil.toException(ExceptionUtil.java:29)
        at com.microsoft.azure.servicebus.primitives.RequestResponseUtils.generateExceptionFromError(RequestResponseUtils.java:92)
        at com.microsoft.azure.servicebus.primitives.RequestResponseUtils.genereateExceptionFromResponse(RequestResponseUtils.java:88)
        at com.microsoft.azure.servicebus.primitives.CommonRequestResponseOperations.lambda$sendCBSTokenAsync$1(CommonRequestResponseOperations.java:84)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
05/06 14:58:58 [pool-9-thread-9] INFO  Recreating receive link to 'test-get-subs-msg/Subscriptions/subscription-send-receive'
May 6, 2020 14:58:58 PM Error [pool-11-thread-10] -
05/06 14:59:00 [pool-9-thread-9] ERROR Sending CBS Token to 'amqp://psbsspace.servicebus.windows.net/test-get-subs-msg/Subscriptions/subscription-send-receive' failed
05/06 14:59:00 [pool-9-thread-7] WARN  Sending CBS Token for amqp://psbsspace.servicebus.windows.net/test-get-subs-msg/Subscriptions/subscription-send-receive failed.
com.microsoft.azure.servicebus.primitives.MessagingEntityNotFoundException: The messaging entity 'sb://psbsspace.servicebus.windows.net/test-get-subs-msg/Subscriptions/subscription
-send-receive' could not be found. To know more visit https://aka.ms/sbResourceMgrExceptions.  TrackingId:c8363320-fc3a-4772-8b1d-1adac2db80d4_G21, SystemTracker:psbsspace.serviceb
us.windows.net:test-get-subs-msg/Subscriptions/subscription-send-receive, Timestamp:2020-05-06T09:29:25
        at com.microsoft.azure.servicebus.primitives.ExceptionUtil.toException(ExceptionUtil.java:29)
        at com.microsoft.azure.servicebus.primitives.RequestResponseUtils.generateExceptionFromError(RequestResponseUtils.java:92)
        at com.microsoft.azure.servicebus.primitives.RequestResponseUtils.genereateExceptionFromResponse(RequestResponseUtils.java:88)
        at com.microsoft.azure.servicebus.primitives.CommonRequestResponseOperations.lambda$sendCBSTokenAsync$1(CommonRequestResponseOperations.java:84)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
05/06 14:59:00 [pool-9-thread-9] ERROR Sending SAS Token to 'test-get-subs-msg/Subscriptions/subscription-send-receive' failed.
com.microsoft.azure.servicebus.primitives.MessagingEntityNotFoundException: The messaging entity 'sb://psbsspace.servicebus.windows.net/test-get-subs-msg/Subscriptions/subscription
-send-receive' could not be found. To know more visit https://aka.ms/sbResourceMgrExceptions.  TrackingId:c8363320-fc3a-4772-8b1d-1adac2db80d4_G21, SystemTracker:psbsspace.serviceb
us.windows.net:test-get-subs-msg/Subscriptions/subscription-send-receive, Timestamp:2020-05-06T09:29:25
        at com.microsoft.azure.servicebus.primitives.ExceptionUtil.toException(ExceptionUtil.java:29)
        at com.microsoft.azure.servicebus.primitives.RequestResponseUtils.generateExceptionFromError(RequestResponseUtils.java:92)
        at com.microsoft.azure.servicebus.primitives.RequestResponseUtils.genereateExceptionFromResponse(RequestResponseUtils.java:88)
        at com.microsoft.azure.servicebus.primitives.CommonRequestResponseOperations.lambda$sendCBSTokenAsync$1(CommonRequestResponseOperations.java:84)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
05/06 14:59:00 [pool-9-thread-9] INFO  Completeing all pending receive and updateState operation on the receiver to 'test-get-subs-msg/Subscriptions/subscription-send-receive'
05/06 14:59:00 [pool-9-thread-9] ERROR Receiving message from entity 'test-get-subs-msg/Subscriptions/subscription-send-receive' failed.
com.microsoft.azure.servicebus.primitives.MessagingEntityNotFoundException: The messaging entity 'sb://psbsspace.servicebus.windows.net/test-get-subs-msg/Subscriptions/subscription
-send-receive' could not be found. To know more visit https://aka.ms/sbResourceMgrExceptions.  TrackingId:c8363320-fc3a-4772-8b1d-1adac2db80d4_G21, SystemTracker:psbsspace.serviceb
us.windows.net:test-get-subs-msg/Subscriptions/subscription-send-receive, Timestamp:2020-05-06T09:29:25
        at com.microsoft.azure.servicebus.primitives.ExceptionUtil.toException(ExceptionUtil.java:29)
        at com.microsoft.azure.servicebus.primitives.RequestResponseUtils.generateExceptionFromError(RequestResponseUtils.java:92)
        at com.microsoft.azure.servicebus.primitives.RequestResponseUtils.genereateExceptionFromResponse(RequestResponseUtils.java:88)
        at com.microsoft.azure.servicebus.primitives.CommonRequestResponseOperations.lambda$sendCBSTokenAsync$1(CommonRequestResponseOperations.java:84)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
05/06 14:59:00 [pool-9-thread-9] INFO  Recreating receive link to 'test-get-subs-msg/Subscriptions/subscription-send-receive'
May 6, 2020 14:59:00 PM Error [pool-11-thread-12] -
05/06 14:59:00 [ReactorThread22940ea3-e1d2-492a-a817-810d75514e5f] INFO  Closed internal send link of requestresponselink to $cbs
05/06 14:59:00 [ReactorThread22940ea3-e1d2-492a-a817-810d75514e5f] INFO  Closing connection to host

**To Reproduce**
create topic
subscribe to it (by registering a callback handler)
delete the topic.

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
When registering a handler for a subscription, one of the parameters is a threadpoolexecutor to process the callbacks (Ref. registerMessageHandler method in  https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/servicebus/microsoft-azure-servicebus/src/main/java/com/microsoft/azure/servicebus/SubscriptionClient.java
)

The serviceBus Client SDK does not terminate the threadpool passed to it when the subscription is terminated or topic is deleted.
As a result, the JVM ends up with threads that keep polling the cloud for messaging entities that are no longer there. See the threads below. This is causing resource outages in our application JVM.
We expect the SDK to shutdown the threadpool when the topic or the subscription that it was created to service, is terminated.

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. iOS] : windows x64
 - IDE : [e.g. IntelliJ] n/a
 - Java SDK 3.0

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by lilyjma** [comment] 2020-06-16 07:35
@hemanttanwar @conniey please take a look

**Comment by ramya-rao-a** [comment] 2020-10-15 05:03
@yvgopal Can you please help with the above?

**Comment by yvgopal** [comment] 2021-11-18 05:37
This has got nothing to do with the service.
I see this is not a bug, but a feature request. I believe the client application can easily close the QueueClient or SubscritionClient when a queue or subscription is deleted. This SDK is deprecated and we are not adding any new features. If multiple customers want this feature, then we will consider it in Track 2. I am closing this for now.

**Closed by yvgopal** 2021-11-18 05:37 UTC
Labels: question, Service Bus, Service Attention, Client, customer-reported, feature-request, needs-team-attention
