### ISSUE TITLE
[Verification]Validate correct deserialization is happening

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-java#8148] opened 2020-02-12 20:56 UTC
Response deserialization
- dropUnnecessaryFields in SearchTestBase -- Somehow @search.score is ending up in additionalProperties. Follow up with AutoRest/azure.core.
- How is INF and -INF working (LookupTests, roundtrip static etc.)

**Comment by sima-zhu** [comment] 2020-02-20 18:37
Will follow up if it needs to fit in Preview 1

**Comment by sima-zhu** [comment] 2020-02-20 20:52
@search.score deserializer has a bug.

**Comment by sima-zhu** [comment] 2020-02-20 22:10
* @search.score is ending up in additionalProperties. Follow up with AutoRest/azure.core.

This is by design, we put all fields into additional properties. 
Refer: [Link](https://github.com/Azure/azure-sdk-for-java/blob/6a6d10208856e63e1731fb057a463b342e64d9c0/sdk/core/azure-core/src/main/java/com/azure/core/util/serializer/AdditionalPropertiesDeserializer.java#L64)

Suggest no change for the following reasons:
1.  The property exists in both field(score and additionalProperty), and it does not affect customer 
use

1. This is a breaking change to other client library.

**Comment by sima-zhu** [comment] 2020-02-20 22:44
* How is INF and -INF working (LookupTests, roundtrip static etc.)

This is Jackson double deserializer work. 

For testing purpose, I added the double for checking:
```
        Double[] expectedDoubles = expected.doubles();
        Double[] actualDoubles = actual.doubles();
        for (int i = 0; i < expectedDoubles.length; i++) {
            Assert.assertEquals(expectedDoubles[i], actualDoubles[i]);
            System.out.println(actualDoubles[i]);
        }
```

The test still can pass.

The deserization happens in jackson databind library. 
For details, checking [here](https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/deser/std/NumberDeserializers.java#L653)

**Comment by sima-zhu** [comment] 2020-02-20 22:47
@brjohnstmsft Could you please double check if the above statement address your concern?
If so, I will close the issue.

**Comment by brjohnstmsft** [comment] 2020-03-03 02:25
@sima-zhu Thanks for confirming the `NaN`, `INF`, and `-INF` cases -- that's good news.

Regarding `additionalProperties`:

> - @search.score is ending up in additionalProperties. Follow up with AutoRest/azure.core.
>
> This is by design, we put all fields into additional properties.

The C# generator doesn't copy known properties into the dictionary, so I find it odd that the Java generator does.

Also, I disagree with this:

> The property exists in both field(score and additionalProperty), and it does not affect customer
use

It has the potential to affect customer use, unless we write custom code to specifically remove these properties. In general, an OData-compliant service like ours can return annotations for many reasons. Although we document the known cases for today, it's possible we will return new annotations in the future, and every time we do, we'd need to modify the SDK code because AutoRest won't do it for us.

Ultimately this is a question of what maintenance burden you're willing to accept. Personally, I think the more code that AutoRest can generate (correctly) for you, the better.

Regarding this:

> This is a breaking change to other client library.

The change to AutoRest could be made with a new config flag to avoid backcompat issues. Again, how much you want to pursue this depends on what maintenance burden you're willing to accept for custom SDK code. But to be 100% clear, in the customer-facing SDK surface area, *only properties not defined in the Swagger* should go in the `additionalProperties` map/dictionary.

**Comment by sima-zhu** [comment] 2020-03-13 16:10
Confirmed this is a bug in azure core. I have open a PR to fix it. Thanks, @brjohnstmsft !
https://github.com/Azure/azure-sdk-for-java/pull/9052

**Closed** 2020-03-13 22:59 UTC
Labels: Client, Search
