### ISSUE TITLE
[QUERY] How to fetch refresh token from Azure Identity?

### ISSUE THREAD

**Issue by ivanmaria** [Azure/azure-sdk-for-java#21106] opened 2021-05-03 10:45 UTC
**Query/Question**
I see that the following feature will be added in the upcoming release. 
Ref: https://github.com/Azure/azure-sdk-for-java/issues/19734

> Request: Add support for fetching an access token from a refresh token

Along with this feature, will there also be a way to get the refresh token from AuthorizationCodeCredential?

***Why is this not a Bug or a feature Request?***
NA

**Setup (please complete the following information if applicable):**
 NA

 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [X] Setup information Added

**Comment by joshfree** [comment] 2021-05-03 17:17
Hi @ivanmaria, thanks for filing this request.  I'm closing this as a duplicate of https://github.com/Azure/azure-sdk-for-java/issues/21104.  Thanks again.

**Closed by joshfree** 2021-05-03 17:17 UTC
Labels: Azure.Identity, Client, customer-reported, question
