### ISSUE TITLE
[BUG] Subsequent calls to CryptographyClient::sign throws NPE

### ISSUE THREAD

**Issue by rain-on** [Azure/azure-sdk-for-java#13799] opened 2020-08-05 02:38 UTC
**Describe the bug**
When attempting to sign using a **SECP256k1** key (with a SigningAlgorithm of "ECDSA256") - a Null Pointer Exception is thrown on second (or subsequent) signing attempts.

***Exception or Stack Trace***
`
java.lang.NullPointerException: stdName must not be null
	at java.util.Objects.requireNonNull(Objects.java:246) ~[?:?]
	at java.security.spec.NamedParameterSpec.<init>(NamedParameterSpec.java:69) ~[?:?]
	at java.security.spec.ECGenParameterSpec.<init>(ECGenParameterSpec.java:53) ~[?:?]
	at com.azure.security.keyvault.keys.models.JsonWebKey.toEc(JsonWebKey.java:771) ~[azure-security-keyvault-keys-4.1.5.jar:?]
	at com.azure.security.keyvault.keys.cryptography.EcKeyCryptographyClient.<init>(EcKeyCryptographyClient.java:47) ~[azure-security-keyvault-keys-4.1.5.jar:?]
	at com.azure.security.keyvault.keys.cryptography.CryptographyAsyncClient.initializeCryptoClients(CryptographyAsyncClient.java:120) ~[azure-security-keyvault-keys-4.1.5.jar:?]
	at com.azure.security.keyvault.keys.cryptography.CryptographyAsyncClient.ensureValidKeyAvailable(CryptographyAsyncClient.java:639) ~[azure-security-keyvault-keys-4.1.5.jar:?]
	at com.azure.security.keyvault.keys.cryptography.CryptographyAsyncClient.sign(CryptographyAsyncClient.java:334) ~[azure-security-keyvault-keys-4.1.5.jar:?]
	at com.azure.security.keyvault.keys.cryptography.CryptographyClient.sign(CryptographyClient.java:264) ~[azure-security-keyvault-keys-4.1.5.jar:?]
`
**To Reproduce**

***Code Snippet***
```
import static org.assertj.core.api.Assertions.assertThat;

import com.azure.identity.ClientSecretCredential;
import com.azure.identity.ClientSecretCredentialBuilder;
import com.azure.security.keyvault.keys.KeyClient;
import com.azure.security.keyvault.keys.KeyClientBuilder;
import com.azure.security.keyvault.keys.cryptography.CryptographyClient;
import com.azure.security.keyvault.keys.cryptography.CryptographyClientBuilder;
import com.azure.security.keyvault.keys.cryptography.models.SignResult;
import com.azure.security.keyvault.keys.cryptography.models.SignatureAlgorithm;
import com.azure.security.keyvault.keys.models.KeyVaultKey;
import org.junit.jupiter.api.Test;

public class AzureApi {

  static final String clientId = System.getenv("AZURE_CLIENT_ID");
  static final String clientSecret = System.getenv("AZURE_CLIENT_SECRET");
  static final String keyVaultName = System.getenv("AZURE_KEY_VAULT_NAME");
  static final String tenantId = System.getenv("AZURE_TENANT_ID");

  @Test
  public void azureCanSignDataTwice() {
    final ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
        .clientId(clientId)
        .clientSecret(clientSecret)
        .tenantId(tenantId)
        .build();

    final String vaultUrl = String.format("https://%s.vault.azure.net", keyVaultName);
    final KeyClient keyClient =
        new KeyClientBuilder().vaultUrl(vaultUrl).credential(clientSecretCredential).buildClient();

    final KeyVaultKey key = keyClient.getKey("TestKey");
    final String keyId = key.getId();

    final CryptographyClient cryptoClient = new CryptographyClientBuilder()
        .credential(clientSecretCredential)
        .keyIdentifier(keyId)
        .buildClient();

    final byte[] dataHash = new byte[32];

    final SignResult result = cryptoClient.sign(SignatureAlgorithm.fromString("ECDSA256"), dataHash);
    // This call will throw
    final SignResult result2 = cryptoClient.sign(SignatureAlgorithm.fromString("ECDSA256"), dataHash);

    assertThat(result).isEqualTo(result2);
  }
}
```

**Expected behavior**
Receive a valid signature.

**Screenshots**
N/A

**Setup (please complete the following information):**
OS = MacOS (10.15.5)
JRE = 11
IDE = Intellij
Library version = 4.1.5

**Comment by joshfree** [comment] 2020-08-06 17:15
Thanks for reporting this bug in the v4.1.5 Key Vault Client Library, @rain-on.  @vcolin7 can you please investigate this and follow up?

**Comment by vcolin7** [comment] 2020-09-23 01:13
It took a little debugging but I found the cause of the issue:

1. The `CryptographyAsyncClient` tries to check if the given key is available locally when calling `sign()`.
2. The first time this occurs, said key will not available locally, so it will attempt to get it from the service and then use a local cryptography client (`EcKeyCryptographyClient` in this case) to sign it. The problem is that the Azure Key Vault service [uses the name "P-256K" for key curve "SECP256k1"](https://docs.microsoft.com/en-us/rest/api/keyvault/createkey/createkey#jsonwebkeycurvename), and [so does the `KeyCurveName` enum](https://github.com/Azure/azure-sdk-for-java/blob/f26a0d7f7689e6b5f73ddc5540d8dde1afa78bf5/sdk/keyvault/azure-security-keyvault-keys/src/main/java/com/azure/security/keyvault/keys/models/KeyCurveName.java#L35), which is used by the `EcKeyCryptographyClient` constructor to create a `KeyPair` from a given `JsonWebKey`.
3. Since there is no enum entry for "SECP256k1", a `KeyCurveName` instance cannot be created and a call to `new ECGenParameterSpec()` is made with a `null` parameter, causing a `NullPointerException` to be thrown in [`JsonWebKey.toEC()`](https://github.com/Azure/azure-sdk-for-java/blob/f26a0d7f7689e6b5f73ddc5540d8dde1afa78bf5/sdk/keyvault/azure-security-keyvault-keys/src/main/java/com/azure/security/keyvault/keys/models/JsonWebKey.java#L771) and caught by the `CryptographyAsyncClient`.
4. Because of this, the `EcKeyCryptographyClient` could not be instantiated and the key cannot be locally signed, causing the `CryptographyAsyncClient` to sign the key by making a service call instead.
5. After signing for the first time, since the key is now locally available for the `CryptographyAsyncClient` it will automatically try to sign it with the local cryptography client, which could never be instantiated and is thus `null`, causing the `NullPointerException` you see.

I am working on a fix to prevent this exception from bubbling up in cases like this.

Regardless of the issue reported, what I recommend you do is create these type of keys using the curve name "P-256K". Some examples:

- With the Azure Portal:

    ![image](https://user-images.githubusercontent.com/5799331/93952960-004b0d00-fcff-11ea-9c08-7475c07fbea4.png)

- With the Azure SDK:

    ```java
    final KeyVaultKey key =
        keyClient.createEcKey(new CreateEcKeyOptions("TestKey").setCurveName(KeyCurveName.P_256K));
    ```

And then sign it by using `SignatureAlgorithm.ES256K`, which is the name [used by the Azure Key Vault Service](https://docs.microsoft.com/en-us/rest/api/keyvault/sign/sign#jsonwebkeysignaturealgorithm) for algorithm "ECDSA256":

```java
final SignatureAlgorithm signatureAlgorithm = SignatureAlgorithm.ES256K;
```

**Comment by vcolin7** [comment] 2020-09-23 02:00
As an additional note, the starting with version `4.2.0`, the Key Vault Keys SDK does not allow signing keys with an signing algorithm name other than the ones specified [here](https://docs.microsoft.com/en-us/rest/api/keyvault/sign/sign#jsonwebkeysignaturealgorithm).

**Comment by vcolin7** [comment] 2020-09-28 20:57
I'm closing this issue for the time being but please feel free to contact me if it persists or if there is something I might have misunderstood. Have a great day :)

**Closed by vcolin7** 2020-09-28 20:57 UTC
Labels: Client, KeyVault, bug, customer-reported
