### ISSUE TITLE
[BUG] Race condition when creating simple EventHubs receive event console client

### ISSUE THREAD

**Issue by mnriem** [Azure/azure-sdk-for-java#22941] opened 2021-07-13 17:07 UTC
**Describe the bug**

The JVM cannot exit because the Java SDK creates threads that are not created as daemon threads and the EventHubConsumerClient.close method does not cleanup those threads.

**To Reproduce**

1. Copy https://github.com/Azure-Samples/java-on-azure-examples/blob/main/eventhubs/receive-event/src/main/java/examples/azure/eventhubs/receiveevent/ReceiveEvent.java
2. Remove System.exit(0) 
3. Execute the example 

**Expected behavior**
The JVM should exit without needing the System.exit(0) call.

**Setup (please complete the following information):**

Maven dependency:

```
       <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-messaging-eventhubs</artifactId>
            <version>5.8.0</version>
        </dependency>
```

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [*] Bug Description Added
- [*] Repro Steps Added
- [*] Setup information Added

**Comment by mnriem** [comment] 2021-07-13 18:34
Please use https://github.com/Azure-Samples/java-on-azure-examples/blob/cc4b440a9c41c2d07c1089b2a17d5e5eedecd6eb/eventhubs/receive-event/src/main/java/examples/azure/eventhubs/receiveevent/ReceiveEvent.java instead of the link mentioned above

**Comment by conniey** [comment] 2021-07-27 17:53
This is a duplicate of: #21852 because they use the same underlying library.

**Closed by conniey** 2021-07-27 17:53 UTC
Labels: Event Hubs
