### ISSUE TITLE
Spring Boot 3.3.0 support

### ISSUE THREAD

**Issue by dmarsh26** [Azure/azure-sdk-for-java#40346] opened 2024-05-24 14:46 UTC
Spring Boot 3.3.0 has now been released, can it be added to the compatibility list?
https://github.com/spring-projects/spring-boot/releases

Compatible versions:
https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Versions-Mapping

**Comment by metron2** [comment] 2024-05-25 15:43
This compatibility check is an anti-pattern. Can't it just be removed? If the library doesn't work, it won't work.

**Comment by dmarsh26** [comment] 2024-05-25 15:51
Yeah, I think documentation of tested combinations should be enough.

________________________________

**Comment by saragluna** [comment] 2024-05-28 09:12
> This compatibility check is an anti-pattern. Can't it just be removed? If the library doesn't work, it won't work.

Yes, I think we could remove this. The compatibility check is more like a protection for ourselves.

**Comment by thibaut129** [comment] 2024-05-29 06:52
Hi,

Any updates on this issue? Currently, we can’t migrate our project to Spring Boot 3.3.0 due to this functionality.

Thanks a lot.

**Comment by LennartHaggkvist** [comment] 2024-05-29 07:45
Hi,
We got problems since we are using Dependabot to manage our dependency updates - and dependabot updated to latest Spring Boot (3.3.0, and not 3.2.6) in our parent project and then we got the above error in our 25+ microservices...

**Comment by mnhock** [comment] 2024-05-29 17:58
Hi!

We are currently unable to migrate our projects to Spring Boot 3.3.0 due to this functionality. Any updates on this?

Thank you very much!

**Comment by davidkarlsen** [comment] 2024-05-30 01:44
@LennartHaggkvist U need to control the dependency chain independently if you really do "micro-services" :) You're dependabot PRs might break, but that should be it. 
@mnhock the change on azure side will probably be nothing else than bumping the spring version, as confirmed in https://github.com/Azure/azure-sdk-for-java/issues/40346#issuecomment-2134723138 and seen in previous releases on this subject - this issue is really an invented issue, it either works or it doesn't: https://github.com/Azure/azure-sdk-for-java/issues/40346#issuecomment-2131312723

**Comment by saragluna** [comment] 2024-05-30 02:52
We are working on this change and a new release will be out early next week if everything goes fine. And in the next version, we will disable the compatibility verifier by default.

**Comment by Netyyyy** [comment] 2024-05-31 00:29
Disabled in https://github.com/Azure/azure-sdk-for-java/pull/40407

**Comment by KrohnicDev** [comment] 2024-06-04 05:23
To anyone who is currently blocked by this: You can just set `spring.cloud.azure.compatibility-verifier.enabled=false` to disable that compatibility check.

**Comment by mhalbritter** [comment] 2024-06-07 07:12
[5.13.0](https://search.maven.org/artifact/com.azure.spring/spring-cloud-azure-autoconfigure/5.13.0/jar) has been released with support for Spring Boot 3.3.x.

**Comment by Netyyyy** [comment] 2024-06-07 07:33
close for released

**Closed by Netyyyy** 2024-06-07 07:33 UTC
Labels: question, Client, customer-reported, needs-team-attention, azure-spring
