### ISSUE TITLE
OLTP Connector 3 is unable to infer schema correctly schema and thus failing with number-format-exception for particular cosmos-collection 

### ISSUE THREAD

**Issue by tyagi420** [Azure/azure-sdk-for-java#21818] opened 2021-05-25 10:48 UTC
CODE : 
val cosmosEndpoint = <>
val cosmosMasterKey = <>
val cosmosDatabaseName = <>
val cosmosContainerName2 = <particular-collection>

val cfgWithAutoSchemaInference2 = Map("spark.cosmos.accountEndpoint" -> cosmosEndpoint,
  "spark.cosmos.accountKey" -> cosmosMasterKey,
  "spark.cosmos.database" -> cosmosDatabaseName,
  "spark.cosmos.container" -> cosmosContainerName2,
  "spark.cosmos.read.inferSchema.enabled" -> "true"
)

var df2 = spark.read.format("cosmos.oltp").options(cfgWithAutoSchemaInference2).load()

df2.printSchema()

RESULT Provided by cosmos connector 3 : 
root
 |-- dataDetails: string (nullable = true)
 |-- sensorDetails: string (nullable = false)
 |-- partitionKey: string (nullable = false)
 |-- id: string (nullable = false)
 |-- msgSchema: struct (nullable = false)
 |    |-- msgVersion: string (nullable = false)

Expected Result (tested out from cosmos connector 2) : 
root
 |-- _attachments: string (nullable = true)
 |-- _etag: string (nullable = true)
 |-- _rid: string (nullable = true)
 |-- _self: string (nullable = true)
 |-- _ts: integer (nullable = true)
 |-- id: string (nullable = true)
 |-- msgSchema: struct (nullable = true)
 |    |-- msgVersion: string (nullable = true)
 |-- dataDetails: struct (nullable = true)
 |    |-- rackName: string (nullable = true)
 |    |-- caseName: string (nullable = true)
 |    |-- circuitName: string (nullable = true)
 |    |-- sensorDescription: string (nullable = true)
 |-- partitionKey: string (nullable = true)
 |-- sensorData: struct (nullable = true)
 |    |-- networkType: string (nullable = true)
 |    |-- sensorStatus: struct (nullable = true)
 |    |    |-- mappedReading: null (nullable = true)
 |    |    |-- reading: string (nullable = true)
 |    |    |-- units: string (nullable = true)
 |    |    |-- unResolvedReading: string (nullable = true)
 |    |-- rackIndex: integer (nullable = true)
 |    |-- vendorType: string (nullable = true)
 

Query - display(df)
RESULT :  
NumberFormatException: For input string: "3612611867"

NOTE : CONNECTOR 2 is working fine for same cosmos collection (JAVA SDK older version is working fine but SDK 4 is also throwing same exception)

**Comment by kushagraThapar** [comment] 2021-05-26 18:25
@moderakh  - please take a look at this issue.

**Comment by moderakh** [comment] 2021-05-26 21:54
@ealsur spark schema related. could you please take a look at this one?

**Comment by ealsur** [comment] 2021-05-27 17:27
@tyagi420 What is the configuration you used on Spark2?

**Comment by ealsur** [comment] 2021-05-27 17:28
`|-- dataDetails: string (nullable = true)`

The fact that `dataDetails` is being detected as `string` means you have documents with `dataDetails` of different types, is this the case?

**Comment by tyagi420** [comment] 2021-05-28 08:07
@ealsur

> @tyagi420 What is the configuration you used on Spark2?


For spark 2 :
Cluster runtime  : 6.4 (includes Apache Spark 2.4.5, Scala 2.11)


Code to test :
// Import Necessary Libraries
import com.microsoft.azure.cosmosdb.spark.schema._
import com.microsoft.azure.cosmosdb.spark._
import com.microsoft.azure.cosmosdb.spark.config.Config

// Read Configuration
val readConfig = com.microsoft.azure.cosmosdb.spark.config.Config(Map(
  "Endpoint" -> <>,
  "Masterkey" -> <>,
  "Database" -> <>,

  "Collection" -> <>"

));

import org.apache.spark.sql.functions.{col, concat, isnan, lit, when}
// Connect via azure-cosmosdb-spark to create Spark DataFrame
val df = spark.read.cosmosDB(readConfig)

// working fine
display(df)
df.printSchema()

**Comment by tyagi420** [comment] 2021-05-28 08:17
The fact that dataDetails is being detected as string means you have documents with dataDetails of different types, is this the case?

this should be the case with spark connector 2 also but it is working fine , moreover i have tried with infer schema and without infer schema , and providing custom schema but it never worked , not even once .

Moreover , we have 2 collections and here what we have found :
collection 1 :  connector 2  display correct schema , display records  
                       connector 3  display wrong schema , display records  but few fields are missing and few have omitted information
collection 2 : connector 2 display correct schema , display records   
                       connector 3  display wrong schema , doesn't display records : fails with numberformat exception

**Comment by ealsur** [comment] 2021-05-28 13:29
> this should be the case with spark connector 2 also but it is working fine 

What is your expectation in this case? If you have documents with the same property that has different types, what do you expect to get out in the schema? Let's say one document has it as a number and another property has it as a JSON object (as you show in Spark 2), are you expecting it to be detected us? Do you apply any filtering afterwards or are you simply listing records?

> , moreover i have tried with infer schema and without infer schema , and providing custom schema but it never worked , not even once .

When schema inference was disabled, what was the error? It cannot be the same error as disabling schema inference just outputs raw Json.

**Comment by ealsur** [comment] 2021-05-28 15:46
I think I might have found the difference. Spark Connector 2 uses this helper https://github.com/Azure/azure-cosmosdb-spark/blob/19561f0d42eaa91f9e4793fbdf30b62b22829868/src/main/scala/com/microsoft/azure/cosmosdb/spark/schema/CosmosDBSchema.scala#L102 to decide which type to use, and in Spark Connector 3 we are just using StringType without going into any of the other cases. I think we can port this same logic and improve here.

**Comment by ealsur** [comment] 2021-05-28 16:56
@tyagi420 Found the gap in the logic and there is a linked PR to this Issue now that should fix it.

**Comment by ealsur** [comment] 2021-05-28 18:43
@tyagi420 The error in the number parsing is unrelated to Spark, but an underlying issue on the Cosmos SDK that should be also fixed on the second linked PR.

**Closed** 2021-05-28 18:46 UTC
Labels: Client, Cosmos, customer-reported, question

**Comment by tyagi420** [comment] 2021-06-01 05:04
thanks guys , i assume its a available in 4.2.0-beta.1 (Unreleased)

**Comment by tyagi420** [comment] 2021-06-01 05:05
i was trying to build n test 4.2 but its failing due to error : [ERROR] Failed to execute goal on project azure-cosmos-spark_3-1_2-12: Could not resolve dependencies for project com.azure.cosmos.spark:azure-cosmos-spark_3-1_2-12:jar:4.2.0-beta.1: Could not find artifact com.azure:azure-cosmos:jar:4.16.0-beta.2 in ossrh (https://oss.sonatype.org/content/repositories/snapshots/) . could you please check once for above dependency ?

**Comment by ealsur** [comment] 2021-06-01 15:40
@tyagi420 if you want to build a local package for the updated branch, I used to do:

`mvn -f pom.xml -Ppackage-assembly -DskipTests -Dgpg.skip -Dmaven.javadoc.skip=true -Dcheckstyle.skip=true -Dspotbugs.skip=true -Drevapi.skip=true -pl com.azure:azure-cosmos,com.azure.cosmos.spark:azure-cosmos-spark_3-1_2-12 clean package`

**Comment by tyagi420** [comment] 2021-06-01 20:36
Thanks ealsur that worked : after that i have to use azure-cosmos-spark_3-1_2-12-4.2.0-beta.1.jar inside azure-cosmos-spark_3-1_2-12 /target folder ?
let me try it in databricks.

**Comment by ealsur** [comment] 2021-06-01 21:15
Correct on the jar in the folder

**Comment by tyagi420** [comment] 2021-06-02 04:25
With 4.2 beta i am receiving correct schema but its unable to fetch the data and failing with unknown exception :
Memory is available .
Controller/Heasder size all seems to be in range.

Here is full error mssg :
SparkException: Job aborted due to stage failure: Task 230 in stage 18.0 failed 4 times, most recent failure: Lost task 230.3 in stage 18.0 (TID 2661) (172.50.16.22 executor 3): {"ClassName":"InternalServerErrorException","userAgent":"azsdk-java-cosmos/4.16.0-beta.2 Linux/5.4.0-1046-azure JRE/1.8.0_282","statusCode":500,"resourceAddress"<RESOURCE_ADDRESS>","error":"{\"Errors\":[\"An unknown error occurred while processing this request. If the issue persists, please contact Azure Support: http://aka.ms/azure-support\"]}","innerErrorMessage":"[\"An unknown error occurred while processing this request. If the issue persists, please contact Azure Support: http://aka.ms/azure-support\"]","causeInfo":null,"responseHeaders":"{x-ms-last-state-change-utc=Wed, 02 Jun 2021 01:43:34.260 GMT, x-ms-request-duration-ms=1.539, x-ms-session-token=665:-1#3674337816, lsn=3674337816, x-ms-request-charge=1.00, x-ms-schemaversion=1.11, x-ms-transport-request-id=888, x-ms-number-of-read-regions=1, x-ms-activity-id=c6f36eb7-c359-11eb-9049-05376fb39d45, x-ms-xp-role=1, x-ms-global-Committed-lsn=3674337813, x-ms-cosmos-llsn=3674337816, x-ms-serviceversion= version=2.14.0.0}","cosmosDiagnostics":{"userAgent":"azsdk-java-cosmos/4.16.0-beta.2 Linux/5.4.0-1046-azure JRE/1.8.0_282","requestLatencyInMs":61,"requestStartTimeUTC":"2021-06-02T04:19:52.228Z","requestEndTimeUTC":"2021-06-02T04:19:52.289Z","responseStatisticsList":[{"storeResult":{"storePhysicalAddress":<ADDRESS>,"lsn":3674337816,"globalCommittedLsn":3674337813,"partitionKeyRangeId":"665","isValid":true,"statusCode":500,"subStatusCode":0,"isGone":false,"isNotFound":false,"isInvalidPartition":false,"isThroughputControlRequestRateTooLarge":false,"requestCharge":1.0,"itemLSN":-1,"sessionToken":"-1#3674337816","backendLatencyInMs":1.539,"exception":"[\"An unknown error occurred while processing this request. If the issue persists, please contact Azure Support: http://aka.ms/azure-support\"]","transportRequestTimeline":[{"eventName":"created","startTimeUTC":"2021-06-02T04:19:52.228Z","durationInMicroSec":0},{"eventName":"queued","startTimeUTC":"2021-06-02T04:19:52.228Z","durationInMicroSec":0},{"eventName":"channelAcquisitionStarted","startTimeUTC":"2021-06-02T04:19:52.228Z","durationInMicroSec":1000},{"eventName":"pipelined","startTimeUTC":"2021-06-02T04:19:52.229Z","durationInMicroSec":0},{"eventName":"transitTime","startTimeUTC":"2021-06-02T04:19:52.229Z","durationInMicroSec":60000},{"eventName":"received","startTimeUTC":"2021-06-02T04:19:52.289Z","durationInMicroSec":0},{"eventName":"completed","startTimeUTC":"2021-06-02T04:19:52.289Z","durationInMicroSec":0}],"rntbdRequestLengthInBytes":609,"rntbdResponseLengthInBytes":331,"requestPayloadLengthInBytes":150,"responsePayloadLengthInBytes":null,"channelTaskQueueSize":1,"pendingRequestsCount":1,"serviceEndpointStatistics":{"availableChannels":2,"acquiredChannels":0,"executorTaskQueueSize":0,"inflightRequests":1,"lastSuccessfulRequestTime":"2021-06-02T04:19:50.694Z","lastRequestTime":"2021-06-02T04:19:52.069Z","createdTime":"2021-06-02T04:19:50.695Z","isClosed":false}},"requestResponseTimeUTC":"2021-06-02T04:19:52.289Z","requestResourceType":"Document","requestOperationType":"Query"}],"supplementalResponseStatisticsList":[],"addressResolutionStatistics":{},"regionsContacted":[<Region Address>],"retryContext":{"statusAndSubStatusCodes":null,"retryCount":0,"retryLatency":0},"metadataDiagnosticsContext":{"metadataDiagnosticList":null},"serializationDiagnosticsContext":{"serializationDiagnosticsList":null},"gatewayStatistics":null,"systemInformation":{"usedMemory":"1187020 KB","availableMemory":"5443380 KB","systemCpuLoad":"(2021-06-02T04:19:26.384Z 10.6%), (2021-06-02T04:19:31.384Z 9.5%), (2021-06-02T04:19:36.384Z 11.6%), (2021-06-02T04:19:41.384Z 10.4%), (2021-06-02T04:19:46.384Z 10.6%), (2021-06-02T04:19:51.384Z 12.7%)","availableProcessors":4},"clientCfgs":{"id":0,"connectionMode":"DIRECT","numberOfClients":1,"connCfg":{"rntbd":"(cto:PT5S, rto:PT5S, icto:PT0S, ieto:PT1H, mcpe:130, mrpc:30, cer:false)","gw":"(cps:1000, rto:PT5S, icto:null, p:false)","other":"(ed: true, cs: false)"},"consistencyCfg":"(consistency: Eventual, mm: true, prgns: [])"}}}

**Comment by tyagi420** [comment] 2021-06-02 04:26
meanwhile connector 2 is working fine as expected

**Comment by ealsur** [comment] 2021-06-02 15:41
@tyagi420 - This error is a service error (not from the Spark connector), the request sent is getting an error response from the service.

**Comment by tyagi420** [comment] 2021-06-03 04:51
Hi @ealsur : I don't think its service error because :

WIth OLTP 3 (in same notebook) : for both collection its able to read schema but when we do display(dataFrame), it always fail with above unknown error. (if it was service error why it would have been able to fetch schema but unable to fetch data each n every trial)

With OLTP 2 :  each and every single time data is there with display(dataFrame) 

both of connectors are querying same instance of cosmos.

**Comment by ealsur** [comment] 2021-06-03 14:28
@tyagi420 It was a service error, we confirmed it on the telemetry, we found the HTTP 500 being returned by the service on at least 25 query request during an hour on the affected account, the error you share is the Java SDK (which runs under the Spark Connector) surfacing the service response.

When you execute display(dataFrame) then the actual queries are executed, those are the request failing on the service. Fetching the schema does not use any filters, just grabs the first 1000 documents and uses them to infer it.

This might be some service issue on the type of query being executed.

If you can repro it consistently, what is the result of `explain` on the dataframe before attempting to display it? (for example `print(df.explain())`). Are you applying any type of filtering?

**Comment by tyagi420** [comment] 2021-06-04 07:28
Thanks @ealsur :  I agree there could be issue with connecting servers but it couldn't be happening always i start querying with OLTP3 ?

i just connected with same connection string using same filter condition by using OLTP3 and OLTP2 Simultaneously and here are results :

OLTP3 : failed every single time.
OLTP2 : works every single time.

As the query/filter condition is same for both thus physical plan should be similar.

Also, query/filter condition doesn't have to do anything with error : dataframe.limit(10) or query on different collection yields same error by OLTP3 whereas it always works with OLTP3.

**Comment by ealsur** [comment] 2021-06-04 14:17
@tyagi420 Could you please share the filter and/or the `explain()` as mentioned before? Trying to understand if the issue is the type of query being pushed down from Spark to the service and any difference between 2 and 3.

**Comment by tyagi420** [comment] 2021-06-05 16:03
@ealsur please find physical plan as :
OLTP3 : 
== Physical Plan ==
*(1) Project [normalizationDetails#231, sensorDetails#232, partitionKey#233, id#234, msgSchema#235]
+- BatchScan[normalizationDetails#231, sensorDetails#232, partitionKey#233, id#234, msgSchema#235] Cosmos ItemsScan: telemetry.<collectionName>
 - Cosmos Query: SELECT * FROM r WHERE r['partitionKey']=@param0
 > param: @param0 = <partKey>


 OLTP2 :
== Physical Plan ==
*(1) Filter (isnotnull(partitionKey#28) && (partitionKey#28 = <PartKey>))
+- *(1) Scan com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRelation@74aa89e [_attachments#20,_etag#21,_rid#22,_self#23,_ts#24,id#25,msgSchema#26,normalizationDetails#27,partitionKey#28,sensorDetails#29] PushedFilters: [IsNotNull(partitionKey), EqualTo(partKey)], ReadSchema: struct<_attachments:string,_etag:string,_rid:string,_self:string,_ts:int,id:string,msgSchema:stru...
()

**Comment by tyagi420** [comment] 2021-06-05 16:12
Please ,let me know if anything else is required .One of our dev activity is depended upon this

**Comment by ealsur** [comment] 2021-06-07 14:44
@tyagi420 from the explain on version 3, it looks like the param you are using for the filter is `null`:

![image](https://user-images.githubusercontent.com/1633401/121036486-a3479800-c763-11eb-9481-1f7cbb804b48.png)

Is this correct? Are you filtering by `null` or empty values? What happens if you filter by a non-empty/non-null value?

**Comment by tyagi420** [comment] 2021-06-08 05:43
@ealsur  With not null , null filter , without any filter OLTP3 always fails with same error.

**Comment by ealsur** [comment] 2021-06-08 13:55
@tyagi420 

I'm trying to repro the scenario and so far I could not. You mention that it happens even when you do not use any filter at all?

```
val cfgWithAutoSchemaInference2 = Map("spark.cosmos.accountEndpoint" -> cosmosEndpoint,
"spark.cosmos.accountKey" -> cosmosMasterKey,
"spark.cosmos.database" -> cosmosDatabaseName,
"spark.cosmos.container" -> cosmosContainerName2,
"spark.cosmos.read.inferSchema.enabled" -> "true"
)

var df2 = spark.read.format("cosmos.oltp").options(cfgWithAutoSchemaInference2).load()
```

This also fails with the same error?

What is the filter expression you use for the `explain()` information you shared?
