### ISSUE TITLE
[BUG] Spring Boot Application hangs during startup while retrieving Key Vault secrets

### ISSUE THREAD

**Issue by charles-c-mastercard** [Azure/azure-sdk-for-java#14909] opened 2020-09-08 17:35 UTC
**Describe the bug**
Spring Boot Application hangs during startup while retrieving secrets from Key Vault. Similar to following issues:

[https://github.com/microsoft/azure-spring-boot/issues/909](https://github.com/microsoft/azure-spring-boot/issues/909)
[https://github.com/microsoft/azure-spring-boot/issues/853](https://github.com/microsoft/azure-spring-boot/issues/853)

***Exception or Stack Trace***
No error/exceptions shown

*** Reproduce Steps***
1. Create a spring boot project
2. Add maven dependencies as shown below
3. Create a SecretClient Bean by providing credential from MenagedIdentityCredential. 
```
@Bean
    public ManagedIdentityCredential createAzureMSICredential() {
        return new ManagedIdentityCredentialBuilder().clientId(properties.getClientId()).build();
    }
```
```
 @Bean
    public SecretClient secretClient() {
        return new SecretClientBuilder().vaultUrl(properties.getUri())
                .credential(msi)
                .buildClient();
    }
```
4. Use secret client to get secret. 
```
KeyVaultSecret secret = secretClient.getSecret(properties.getKey());
```

**Expected behavior**
Expected to have secrets retrieved successfully and continue the spring boot startup. 

**Setup (please complete the following information):**
 - Spring Boot: 2.2.5.RELEASE
 - Project Maven related dependencies:
```
       <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-identity</artifactId>
            <version>1.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-security-keyvault-secrets</artifactId>
            <version>4.2.0</version>
        </dependency>
```

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment] 2020-09-08 18:47
Thanks for reporting this issue @charles-ethoca.  @vcolin7 can you please take a look and follow up?

**Comment by charles-ethoca** [comment] 2020-09-09 14:45
Adding more info. 

For the environment that works:
- Azure App Service (deployed directly from maven plugin)
- Managed Identity
- Key Vault
with Spring Boot 2.3.3.RELEASE

For the environment that fails:
- Azure VMSS
- Managed Identity
- Key Vault
with Spring Boot 2.2.5.RELEASE

**Comment by charles-ethoca** [comment] 2020-09-09 14:58
Update with some stacktrace:

```
2020-09-09T14:55:32.275097218Z 2020-09-09 14:55:32.274  INFO 123 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 80 (http)
2020-09-09T14:55:32.383798582Z 2020-09-09 14:55:32.383  INFO 123 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-09-09T14:55:32.393206413Z 2020-09-09 14:55:32.393  INFO 123 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.31]
2020-09-09T14:55:32.867302699Z 2020-09-09 14:55:32.861  INFO 123 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-09-09T14:55:32.876929331Z 2020-09-09 14:55:32.869  INFO 123 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 14926 ms
2020-09-09T14:55:36.178920079Z 2020-09-09 14:55:36.168  INFO 123 --- [           main] c.a.s.k.secrets.SecretAsyncClient        : Retrieving secret - redis-key
2020-09-09T14:55:47.201386705Z 2020-09-09 14:55:47.200 ERROR 123 --- [or-http-epoll-1] c.a.identity.implementation.MSIToken     : For input string: "09/10/2020 14:55:45 +00:00"
2020-09-09T14:55:47.229044597Z 2020-09-09 14:55:47.222  INFO 123 --- [or-http-epoll-1] c.a.identity.ManagedIdentityCredential   : Azure Identity => Managed Identity environment: MSI_ENDPOINT
2020-09-09T14:55:47.230708003Z 2020-09-09 14:55:47.230  INFO 123 --- [or-http-epoll-1] c.a.identity.ManagedIdentityCredential   : Azure Identity => getToken() result for scopes [https://vault.azure.net/.default]: SUCCESS
2020-09-09T14:55:47.951056818Z 2020-09-09 14:55:47.950  INFO 123 --- [or-http-epoll-1] c.a.s.k.secrets.SecretAsyncClient        : Retrieved secret - redis-key
```

**Comment by charles-ethoca** [comment] 2020-09-15 13:53
@vcolin7 

```
2020-09-09T14:55:36.178920079Z 2020-09-09 14:55:36.168  INFO 123 --- [           main] c.a.s.k.secrets.SecretAsyncClient        : Retrieving secret - redis-key

/// THEN GO TO MSI ASK FOR TOKEN

2020-09-09T14:55:47.951056818Z 2020-09-09 14:55:47.950  INFO 123 --- [or-http-epoll-1] c.a.s.k.secrets.SecretAsyncClient        : Retrieved secret - redis-key
```

Most of the time, my application wouldn't go further after the main thread one (before going to MSI steps). It just hung there. 

Hope it helps.

**Comment by vcolin7** [comment] 2020-09-19 05:34
Hi @charles-ethoca,

Just as a quick clarification: `getSecret()` only retrieves one secret from the Key Vault. In order to list all your secrets you need to use `listPropertiesOfSecrets()` :)

I tried reproducing the issue on a VM with "managed identity" enabled using `ManagedIdentityCredential` but was not able to reproduce it. My application was able to successfully list and retrieve values of all the secrets in my Key Vault. Here's the code I used:

```java
import com.azure.core.credential.TokenCredential;
import com.azure.core.http.policy.HttpLogDetailLevel;
import com.azure.core.http.policy.HttpLogOptions;
import com.azure.identity.DefaultAzureCredential;
import com.azure.identity.DefaultAzureCredentialBuilder;
import com.azure.identity.ManagedIdentityCredentialBuilder;
import com.azure.security.keyvault.secrets.SecretClient;
import com.azure.security.keyvault.secrets.SecretClientBuilder;
import com.azure.security.keyvault.secrets.models.KeyVaultSecret;
import com.azure.security.keyvault.secrets.models.SecretProperties;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Configurable;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@SpringBootApplication
public class Issue14909Repro implements CommandLineRunner {
    @Autowired
    private TokenCredential azureCredential;

    @Autowired
    private SecretClient secretClient;

    @Bean
    public TokenCredential createAzureCredential() {
        return new ManagedIdentityCredentialBuilder().build(); // clientId is not necessary when using a VM with managed identity enabled
    }

    @Bean
    public SecretClient createSecretClient() {
        return new SecretClientBuilder()
                .vaultUrl("https://vicolina-keyvault-tests.vault.azure.net/")
                .credential(azureCredential)
                .httpLogOptions(new HttpLogOptions().setLogLevel(HttpLogDetailLevel.BODY_AND_HEADERS)) // Very useful for debugging
                .buildClient();
    }

    public static void main(String[] args) {
        SpringApplication.run(Issue14909Repro.class, args);
    }

    public void run(String... varl) throws Exception {
        for (SecretProperties secretProperties : secretClient.listPropertiesOfSecrets()) {
            if (secretProperties.isEnabled()) {
                KeyVaultSecret secret = secretClient.getSecret(secretProperties.getName());
                System.out.printf("Retrieved secret with name: %s and value:\n%s\n", secret.getName(), secret.getValue());
            } else {
                System.out.printf("Cannot retrieve disabled secret with name: %s\n", secretProperties.getName());
            }
        }
    }
}
```

The application will hang after retrieving all secrets because that's all it does really. I could use `System.exit(1)` to terminate the process but I doubt you want to do that.

I don't believe problem is cause by whether using `clientid` or not when creating the credential object. Maybe you can enable debugging on the "body and headers" level to see what's going on (see code above). It could be possible you are trying to issue too many requests in a very short timeframe and the service is limiting you. Changing the logging policy will help us figure out what's going on :)

**Comment by charles-ethoca** [comment] 2020-09-21 19:24
Hi @vcolin7 ,

Thank you very much for taking a look at the problem.

We are using UserAssignedManagedIdentity, so clientId I think it's required. 

I did not try to list all the secrets. All I did was to get one secret. Code as following:

```
@Bean
    public JedisConnectionFactory jedisConnectionFactory() {
        KeyVaultSecret secret = secretClient.getSecret(properties.getKey());
        RedisStandaloneConfiguration config = new RedisStandaloneConfiguration();
        config.setHostName(properties.getHost());
        config.setPort(properties.getPort());
        config.setPassword(secret.getValue());
        JedisClientConfiguration clientConfig = JedisClientConfiguration.builder().useSsl().and().connectTimeout(Duration.ofSeconds(15)).build();
        return new JedisConnectionFactory(config, clientConfig);
    }
```

I turned on the logging as you suggested. Here's the info (sorry I had to remove some sensitive info)
[keyvault-hang.txt](https://github.com/Azure/azure-sdk-for-java/files/5257693/keyvault-hang.txt)

There isn't much happening before the log, only initializing the SSLContext. 

Hope the log help.

**Comment by vcolin7** [comment] 2020-09-25 00:08
I tested again with the code shared above but this time using User Assigned Managed Identity on my VM and could consistently list and retrieve all secrets in my Key Vault. I had a brief chat with @g2vinay about this and we suspect the issue might be related to a dependency conflict that causes an internal issue which is not properly being logged by the logging framework.

It would be really helpful if you can share the results of running `mvn dependency:tree` in the directory where your POM file is located, or if you can share the POM itself.

@g2vinay will later share how to change the logging to catch the other possible issues I mentioned.

**Comment by charles-c-mastercard** [comment] 2020-10-06 13:31
@vcolin7 , Thank you for the follow up again.

There are some company dependencies that we are using. I am afraid I am not able to share them here due to the company policies.  

Would you mind to tell me how to change the logging to see other issues? Or see if we can arrange a meeting I can do some screen share with you?

**Comment by g2vinay** [comment] 2020-10-06 21:05
@charles-c-mastercard 

To enable application logging you can add this dependency to your application pom file:
```
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-simple</artifactId>
    <version>1.7.29</version>
</dependency>
```

This should enable the logging and you should see logs in the console/command line. You can share these logs with us.
Also on which Azure Platform are you running your application ? is it an Azure VM or Azure Functions or Azure App service etc ?

**Comment by vcolin7** [comment] 2020-10-06 21:10
Adding @jialindai from the Spring team.

**Comment by charles-c-mastercard** [comment] 2020-10-07 15:37
@g2vinay , it's on a VMSS using User Assigned Managed Identity to access Kay Vault. 

I believe we have `slf4j` in dependencies, but I didn't see any logging. I have attached the `TRACE` logs in previous reply.

**Comment by jonasbark** [comment] 2020-11-13 10:42
This happens to me again and again for different versions without a clear idea what's causing it.
This time it happens on upgrading to Spring Boot 2.4.0. In integrated the keyvault-starter, added the necessary application properties and it hangs during startup:

![image](https://user-images.githubusercontent.com/1151304/99063740-4311be80-25a5-11eb-9e3b-0bb1d1efb520.png)

**Comment by jonasbark** [comment] 2020-11-13 12:23
I could even reproduce it in a new project from start.spring.io (Spring Boot 2.4.0) with the following dependencies:
```
implementation(platform("com.microsoft.azure:azure-spring-boot-bom:2.3.5"))
implementation(group = "com.microsoft.azure", name = "azure-keyvault-secrets-spring-boot-starter")
```
and adding 
```
azure.keyvault.uri = https://***.vault.azure.net/
azure.keyvault.client-id = ***
azure.keyvault.client-key = ***
azure.keyvault.tenant-id = ***
```
to application-default.properties.

App doesn't start.

**Comment by jonasbark** [comment] 2020-11-16 08:02
@vcolin7 should I open up a new ticket for this? I think this will be a blocker for a few companies that want to use Spring Boot 2.4 and Keyvaults

**Comment by vcolin7** [comment] 2020-11-17 02:44
Hi @jonasbark, thanks for reporting this and sorry for the late response. I think a new GitHub issue would help with tracking since these seem to be different conditions, please feel free to create it and assign it to me. I will look into this in the meantime.

**Comment by jonasbark** [comment] 2020-11-17 06:46
Hi @vcolin7 - thanks for the reply! I created a new ticket here: https://github.com/Azure/azure-sdk-for-java/issues/17617

**Comment by vcolin7** [comment] 2020-12-10 00:27
Hi @charles-c-mastercard, I understand your some privacy concerns for not sharing your dependency tree, I wonder if it would be possible to share a sample project stripped off of the things you are not able to share where this can be reproduced. I have not been successful in reproducing this issue on my end so far.

**Comment by onkobu** [comment] 2020-12-21 16:05
Same here. I'm using a plain simple Spring Boot application with `azure-keyvault-secrets-spring-boot-starter`. The intention is to map secrets into Spring's ApplicationContext. Does definitely not work/ block in KeyVaultOperation.fillSecretsList@125 (2.2.5) resp. KeyVaultOperation.refreshProperties@132 (2.3.5). As far as I can see from the sources there's also no timeout.

Reverting Spring Boot version from 2.4.0 back to 2.2.6.RELEASE brings back regular behavior. 

When I hand in a totally useless azure.keyvault.url the blocking variant gives up after 15 tries and throws an exception. With the correct URL it blocks again infinitely.

I can reproduce this in any environment with different JDKs version 11: local (Windows) machine with OpenJDK as well as inside Docker (latest OpenJDK-image) on K8s in Azure Cloud.

**Comment by jonasbark** [comment] 2020-12-21 16:21
@onkobu the issue you are facing is this: https://github.com/Azure/azure-sdk-for-java/issues/17617
there's a workaround included

**Comment by onkobu** [comment] 2020-12-21 16:37
> there's a workaround included

Magnificent…should've read more carefully the comments above.

**Closed** 2021-01-26 08:00 UTC
Labels: Client, azure-spring, azure-spring-keyvault, customer-reported, needs-author-feedback, no-recent-activity, tenet-reliability
