### ISSUE TITLE
[QUERY] Create Java Filesystem object for ADLS Gen2

### ISSUE THREAD

**Issue by ms-oyo** [Azure/azure-sdk-for-java#28510] opened 2022-04-25 07:00 UTC
**Query/Question**
Create Java Filesystem object for ADLS Gen2 to delete certain directories or a similar azure code.

***Why is this not a Bug or a feature Request?***
We are trying to follow this documentation - [DOC](https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-directory-file-acl-java), but facing several issues. Basically, we want the replacement of the following codepiece with adls- 
`FileSystem fileSystem = new S3AFileSystem();
Configuration configuration = new Configuration();
fileSystem.initialize(URI.create('s3://bucket-path'), configuration);`

**Setup (please complete the following information if applicable):**
 - OS: iOS
 - IDE: IntelliJ
 - Library/Libraries: azure-storage-file-datalake:12.9.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by joshfree** [comment] 2022-04-25 17:00
Hi @ms-oyo thank you for reaching out to us via this GitHub issue.  Someone from the Storage SDK team will follow up with you shortly.

/cc @rickle-msft

**Comment by rickle-msft** [comment] 2022-04-25 20:27
@ms-oyo I am not very familiar with these methods in S3. Can you please describe more about what the behavior of these methods is? And can you also share more about what issues you're facing when trying to follow the doc you linked?

**Comment by ibrahimrabab** [comment] 2022-08-19 22:17
Hi @ms-oyo , just following up on this thread. Is this still an issue? If so, would you be able to provide details on what behavior these methods have, and what issues you're facing? If this is no longer an issue, we can close this. Thanks!

**Comment by ibrahimrabab** [comment] 2022-08-23 03:33
Since there is no customer engagement after a few months, we are unable to reproduce the behavior without any code samples. Based on the question above, it seems like blob-nio may be an appropriate package to look into which could allow you to create file system objects. Please let us know if you have any other questions or want to share any code snippets.

Thanks!

**Closed by ibrahimrabab** 2022-08-23 03:33 UTC
Labels: question, Storage, Client, customer-reported
