### ISSUE TITLE
"The specifed resource name contains invalid characters" not informative

### ISSUE THREAD

**Issue by ppalaga** [Azure/azure-sdk-for-java#19548] opened 2021-03-02 09:37 UTC
Getting the following error message is not very helpful

```
com.azure.storage.file.datalake.models.DataLakeStorageException: Status code 400, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidResourceName</Code><Message>The specifed resource name contains invalid characters.
RequestId:06170e15-001e-007e-6746-0fcf01000000
Time:2021-03-02T09:25:47.4135513Z</Message></Error>"
        at com.azure.storage.file.datalake.implementation.util.DataLakeImplUtils.transformBlobStorageException(DataLakeImplUtils.java:30)
        at com.azure.storage.file.datalake.implementation.util.DataLakeImplUtils.returnOrConvertException(DataLakeImplUtils.java:38)
        at com.azure.storage.file.datalake.DataLakeFileSystemClient.createWithResponse(DataLakeFileSystemClient.java:217)
```

I wish I the message contained the resource name that caused the problem and a hint what should I do to fix it. Something like 

```
Invalid resource name 'Abc-123'; expected resource name consisting only of ..., see <url> for more details.
```

**Comment by joshfree** [comment] 2021-03-04 21:15
@gapra-msft @rickle-msft could you please follow up with @ppalaga

**Comment by gapra-msft** [comment] 2021-03-04 21:17
Hi @ppalaga Thank you for reporting this issue. I will take a look into what cause this problem.

**Comment by gapra-msft** [comment] 2021-03-04 21:27
It looks like the issue is that container/file system names must follow [this](https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#container-names) specification. I will also reach out to folks that work on the service to see if the error message can be improved.

**Comment by gapra-msft** [comment] 2021-03-08 18:16
I will close this issue as I have created a backlog item internally for the service to address.

Please feel free to open new issues if you hit any other problems.

**Closed by gapra-msft** 2021-03-08 18:16 UTC
Labels: Client, Storage, customer-reported, question

**Comment by ppalaga** [comment] 2021-03-08 21:51
> I will close this issue

Hm... and how will I figure out that it got fixed in the service? Is there a public service issue that could watch?

**Comment by gapra-msft** [comment] 2021-03-08 22:02
@ppalaga Good question. 
We will update this thread once the fix is made, however we will keep this issue in the closed state as this is not an SDK issue.
