### ISSUE TITLE
[FEATURE REQ] Support for Spring Boot 3.4.x

### ISSUE THREAD

**Issue by ajpogue** [Azure/azure-sdk-for-java#43298] opened 2024-12-09 18:33 UTC
**Is your feature request related to a problem? Please describe.**
Yes, SDK compatibility

**Describe the solution you'd like**
Support added for Spring boot 3.4.x - 

We would like to know when to expect the Azure library updates to support Spring Boot version 3.4.0 

**Describe alternatives you've considered**
none at this time

**Additional context**
We continuously update java and spring dependencies to be aligned with quality and security rules, 
We currently deploy custom containers on Azure App Services. (not Azure Spring Apps or ACA) 

Spring Boot recently released version 3.4.0 and we note that some of the Azure libraries (Azure Cosmos, Azure Key Vault, Azure Storage, ...) are not compatible with new version

We would like to know when to expect the Azure library updates in order to plan our upgrades to Spring Boot version 3.4.0 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by davidkarlsen** [comment] 2024-12-10 01:49
Duplicate of #43085

**Comment by saragluna** [comment] 2024-12-16 12:28
https://github.com/Azure/azure-sdk-for-java/pull/43420

**Comment by saragluna** [comment] 2024-12-17 03:13
Spring Cloud Azure 5.19.0 has been released.

**Closed** 2024-12-20 02:41 UTC
Labels: question, Client, customer-reported, needs-team-attention, azure-spring
