### ISSUE TITLE
OLTP Connector 3 is unable to infer schema correctly and thus failing with number-format-exception for particular cosmos-collection

### ISSUE THREAD

**Issue by tyagi420** [Azure/azure-sdk-for-java#21819] opened 2021-05-25 10:50 UTC
CODE : 
val cosmosEndpoint = <>
val cosmosMasterKey = <>
val cosmosDatabaseName = <>
val cosmosContainerName2 = <particular-collection>

val cfgWithAutoSchemaInference2 = Map("spark.cosmos.accountEndpoint" -> cosmosEndpoint,
  "spark.cosmos.accountKey" -> cosmosMasterKey,
  "spark.cosmos.database" -> cosmosDatabaseName,
  "spark.cosmos.container" -> cosmosContainerName2,
  "spark.cosmos.read.inferSchema.enabled" -> "true",
)

var df2 = spark.read.format("cosmos.oltp").options(cfgWithAutoSchemaInference2).load()

df2.printSchema()

RESULT Provided by cosmos connector 3 : 
root
 |-- dataDetails: string (nullable = true)
 |-- sensorDetails: string (nullable = false)
 |-- partitionKey: string (nullable = false)
 |-- id: string (nullable = false)
 |-- msgSchema: struct (nullable = false)
 |    |-- msgVersion: string (nullable = false)

Expected Result (tested out from cosmos connector 2) : 
root
 |-- _attachments: string (nullable = true)
 |-- _etag: string (nullable = true)
 |-- _rid: string (nullable = true)
 |-- _self: string (nullable = true)
 |-- _ts: integer (nullable = true)
 |-- id: string (nullable = true)
 |-- msgSchema: struct (nullable = true)
 |    |-- msgVersion: string (nullable = true)
 |-- dataDetails: struct (nullable = true)
 |    |-- rackName: string (nullable = true)
 |    |-- caseName: string (nullable = true)
 |    |-- circuitName: string (nullable = true)
 |    |-- sensorDescription: string (nullable = true)
 |-- partitionKey: string (nullable = true)
 |-- sensorData: struct (nullable = true)
 |    |-- networkType: string (nullable = true)
 |    |-- sensorStatus: struct (nullable = true)
 |    |    |-- mappedReading: null (nullable = true)
 |    |    |-- reading: string (nullable = true)
 |    |    |-- units: string (nullable = true)
 |    |    |-- unResolvedReading: string (nullable = true)
 |    |-- rackIndex: integer (nullable = true)
 |    |-- vendorType: string (nullable = true)
 

Query - display(df)
RESULT :  
NumberFormatException: For input string: "3612611867"

NOTE : CONNECTOR 2 is working fine for same cosmos collection (JAVA SDK older version is working fine but SDK 4 is also throwing same exception)

**Comment by joshfree** [comment] 2021-05-26 18:16
Hi @tyagi420 I am closing this as a duplicate of https://github.com/Azure/azure-sdk-for-java/issues/21818 which appears to have the exact same text.

**Closed by joshfree** 2021-05-26 18:16 UTC
Labels: customer-reported, needs-triage, question
