### ISSUE TITLE
[QUERY] Why so many "Cannot create receive link from a closed session" errors?

### ISSUE THREAD

**Issue by elFarto** [Azure/azure-sdk-for-java#38528] opened 2024-01-29 17:00 UTC
**Query/Question**
We're seeing a lot of `Cannot create receive link from a closed session` errors in our application while receiving messages on a service bus. It seems to be correlated with the frequency of the messages we receive, higher amount of messages received - fewer errors, lower amount of messages - more errors.

The first error we receive is:
```
2024-01-29T15:42:23.017Z ERROR 26440 --- [ctor-executor-1] c.a.c.a.implementation.ReactorSession    : {
  "az.sdk.message":"","exception":"Cannot create receive link from a closed session., errorContext[NAMESPACE: custom-domain.com. ERROR CONTEXT: N/A, PATH: xxx/subscriptions/yyy]",
  "connectionId":"MF_87da75_1706542589306",
  "sessionName":"xxx/subscriptions/yyy",
  "entityPath":"xxx/subscriptions/yyy",
  "linkName":"xxx/subscriptions/yyy_cf4289_1706542589377"
}
```

This is quickly followed by:
```
2024-01-29T15:42:27.042Z ERROR 26440 --- [ctor-executor-1] reactor.core.publisher.Operators         : Operator called default onErrorDropped

reactor.core.Exceptions$ErrorCallbackNotImplemented: com.azure.core.amqp.exception.AmqpException: connection aborted, errorContext[NAMESPACE: custom-domain.com. ERROR CONTEXT: N/A]
Caused by: com.azure.core.amqp.exception.AmqpException: connection aborted, errorContext[NAMESPACE: custom-domain.com. ERROR CONTEXT: N/A]
	at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:85) ~[azure-core-amqp-2.9.0.jar:2.9.0]
	at com.azure.core.amqp.implementation.handler.ConnectionHandler.notifyErrorContext(ConnectionHandler.java:362) ~[azure-core-amqp-2.9.0.jar:2.9.0]
	at com.azure.core.amqp.implementation.handler.ConnectionHandler.onTransportError(ConnectionHandler.java:259) ~[azure-core-amqp-2.9.0.jar:2.9.0]
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191) ~[proton-j-0.33.8.jar:na]
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) ~[proton-j-0.33.8.jar:na]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324) ~[proton-j-0.33.8.jar:na]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291) ~[proton-j-0.33.8.jar:na]
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:91) ~[azure-core-amqp-2.9.0.jar:2.9.0]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.5.8.jar:3.5.8]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.5.8.jar:3.5.8]
```
Here's the error rate over a couple of weeks (it's not quite as bad as it looks, as a single error produces multiple lines that are captured):
![image](https://github.com/Azure/azure-sdk-for-java/assets/2325080/a1d7aa08-5566-4e30-9d87-a12412f1c89e)

<details>

<summary>Full log</summary>

```
2024-01-29T15:41:03.004Z  INFO 26440 --- [       Thread-1] a.s.u.core.service.PersistenceService    : Message Processed
2024-01-29T15:42:23.005Z  WARN 26440 --- [ctor-executor-1] c.a.c.a.i.h.WebSocketsConnectionHandler  : {"az.sdk.message":"onTransportError","connectionId":"MF_87da75_1706542589306","errorCondition":"amqp:connection:framing-error","errorDescription":"connection aborted","hostName":"xxx-frontmessagebus.servicebus.windows.net"}
2024-01-29T15:42:23.008Z  INFO 26440 --- [ctor-executor-1] c.a.c.a.i.ReactorConnection              : {"az.sdk.message":"Disposing of ReactorConnection.","connectionId":"MF_87da75_1706542589306","isTransient":false,"isInitiatedByClient":false,"shutdownMessage":"connection aborted, errorContext[NAMESPACE: custom-domain.com. ERROR CONTEXT: N/A]"}
2024-01-29T15:42:23.015Z  INFO 26440 --- [ctor-executor-1] c.a.c.a.i.h.WebSocketsConnectionHandler  : {"az.sdk.message":"onConnectionUnbound","connectionId":"MF_87da75_1706542589306","hostName":"xxx-frontmessagebus.servicebus.windows.net","state":"CLOSED","remoteState":"ACTIVE"}
2024-01-29T15:42:23.015Z  INFO 26440 --- [ctor-executor-1] c.a.c.a.i.handler.ReceiveLinkHandler     : {"az.sdk.message":"onLinkFinal","connectionId":"MF_87da75_1706542589306","linkName":"xxx/subscriptions/yyy_cf4289_1706542589377","entityPath":"xxx/subscriptions/yyy"}
2024-01-29T15:42:23.016Z  INFO 26440 --- [ctor-executor-1] c.a.m.s.i.ServiceBusReceiveLinkProcessor : Receive link endpoint states are closed. Requesting another.
2024-01-29T15:42:23.016Z  INFO 26440 --- [ctor-executor-1] c.a.m.s.i.ServiceBusReceiveLinkProcessor : Requesting a new AmqpReceiveLink from upstream.
2024-01-29T15:42:23.017Z ERROR 26440 --- [ctor-executor-1] c.a.c.a.implementation.ReactorSession    : {"az.sdk.message":"","exception":"Cannot create receive link from a closed session., errorContext[NAMESPACE: custom-domain.com. ERROR CONTEXT: N/A, PATH: xxx/subscriptions/yyy]","connectionId":"MF_87da75_1706542589306","sessionName":"xxx/subscriptions/yyy","entityPath":"xxx/subscriptions/yyy","linkName":"xxx/subscriptions/yyy_cf4289_1706542589377"}
2024-01-29T15:42:23.018Z  INFO 26440 --- [ctor-executor-1] c.a.c.a.i.handler.SessionHandler         : {"az.sdk.message":"onSessionFinal.","connectionId":"MF_87da75_1706542589306","sessionName":"xxx/subscriptions/yyy"}
2024-01-29T15:42:23.018Z  INFO 26440 --- [ctor-executor-1] c.a.c.a.i.handler.SendLinkHandler        : {"az.sdk.message":"onLinkFinal","connectionId":"MF_87da75_1706542589306","linkName":"cbs:sender","entityPath":"$cbs"}
2024-01-29T15:42:23.018Z  INFO 26440 --- [ctor-executor-1] c.a.c.a.i.handler.ReceiveLinkHandler     : {"az.sdk.message":"onLinkFinal","connectionId":"MF_87da75_1706542589306","linkName":"cbs:receiver","entityPath":"$cbs"}
2024-01-29T15:42:23.018Z  INFO 26440 --- [ctor-executor-1] c.a.c.a.i.AmqpChannelProcessor           : {"az.sdk.message":"Channel is closed. Requesting upstream.","connectionId":"MF_87da75_1706542589306","entityPath":"$cbs"}
2024-01-29T15:42:23.018Z  INFO 26440 --- [ctor-executor-1] c.a.c.a.i.AmqpChannelProcessor           : {"az.sdk.message":"Connection not requested, yet. Requesting one.","connectionId":"MF_87da75_1706542589306","entityPath":"$cbs"}
2024-01-29T15:42:23.019Z  INFO 26440 --- [ctor-executor-1] c.a.c.a.i.ReactorConnection              : {"az.sdk.message":"Emitting new response channel.","connectionId":"MF_87da75_1706542589306","entityPath":"$cbs","linkName":"cbs"}
2024-01-29T15:42:23.019Z  INFO 26440 --- [ctor-executor-1] c.a.c.a.i.AmqpChannelProcessor           : {"az.sdk.message":"Setting next AMQP channel.","connectionId":"MF_87da75_1706542589306","entityPath":"$cbs"}
2024-01-29T15:42:23.019Z  INFO 26440 --- [ctor-executor-1] c.a.c.a.i.AmqpChannelProcessor           : {"az.sdk.message":"Upstream connection publisher was completed. Terminating processor.","connectionId":"MF_87da75_1706542589306","entityPath":"$cbs"}
2024-01-29T15:42:23.020Z  INFO 26440 --- [ctor-executor-1] c.a.c.a.i.handler.SessionHandler         : {"az.sdk.message":"onSessionFinal.","connectionId":"MF_87da75_1706542589306","sessionName":"cbs-session"}
2024-01-29T15:42:23.020Z  INFO 26440 --- [ctor-executor-1] c.a.c.a.i.h.WebSocketsConnectionHandler  : {"az.sdk.message":"onConnectionFinal","connectionId":"MF_87da75_1706542589306","errorCondition":"amqp:resource-limit-exceeded","errorDescription":"local-idle-timeout expired","hostName":"xxx-frontmessagebus.servicebus.windows.net"}
2024-01-29T15:42:23.022Z  INFO 26440 --- [ctor-executor-1] c.a.c.a.i.ReactorConnection              : {"az.sdk.message":"Closing executor.","connectionId":"MF_87da75_1706542589306"}
2024-01-29T15:42:23.022Z  INFO 26440 --- [ctor-executor-1] c.a.c.a.i.handler.SendLinkHandler        : {"az.sdk.message":"Sender link was never active. Closing endpoint states.","connectionId":"MF_87da75_1706542589306","linkName":"cbs","entityPath":"$cbs"}
2024-01-29T15:42:23.022Z  INFO 26440 --- [ctor-executor-1] c.a.c.a.i.handler.ReceiveLinkHandler     : {"az.sdk.message":"Receiver link was never active. Closing endpoint states","connectionId":"MF_87da75_1706542589306","entityPath":"$cbs","linkName":"cbs"}
2024-01-29T15:42:23.022Z  INFO 26440 --- [ctor-executor-1] c.a.c.a.i.AmqpChannelProcessor           : {"az.sdk.message":"Channel is disposed.","connectionId":"MF_87da75_1706542589306","entityPath":"$cbs"}
2024-01-29T15:42:27.037Z  INFO 26440 --- [ctor-executor-1] c.a.c.a.implementation.ReactorExecutor   : {"az.sdk.message":"Processing all pending tasks and closing old reactor.","connectionId":"MF_87da75_1706542589306"}
2024-01-29T15:42:27.038Z  INFO 26440 --- [ctor-executor-1] c.a.c.a.i.ReactorDispatcher              : {"az.sdk.message":"Reactor selectable is being disposed.","connectionId":"MF_87da75_1706542589306"}
2024-01-29T15:42:27.038Z  INFO 26440 --- [ctor-executor-1] c.a.c.a.i.ReactorConnection              : {"az.sdk.message":"onConnectionShutdown. Shutting down.","connectionId":"MF_87da75_1706542589306","isTransient":false,"isInitiatedByClient":false,"shutdownMessage":"connectionId[MF_87da75_1706542589306] Reactor selectable is disposed.","namespace":"custom-domain.com"}
2024-01-29T15:42:27.042Z ERROR 26440 --- [ctor-executor-1] reactor.core.publisher.Operators         : Operator called default onErrorDropped

reactor.core.Exceptions$ErrorCallbackNotImplemented: com.azure.core.amqp.exception.AmqpException: connection aborted, errorContext[NAMESPACE: custom-domain.com. ERROR CONTEXT: N/A]
Caused by: com.azure.core.amqp.exception.AmqpException: connection aborted, errorContext[NAMESPACE: custom-domain.com. ERROR CONTEXT: N/A]
	at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:85) ~[azure-core-amqp-2.9.0.jar:2.9.0]
	at com.azure.core.amqp.implementation.handler.ConnectionHandler.notifyErrorContext(ConnectionHandler.java:362) ~[azure-core-amqp-2.9.0.jar:2.9.0]
	at com.azure.core.amqp.implementation.handler.ConnectionHandler.onTransportError(ConnectionHandler.java:259) ~[azure-core-amqp-2.9.0.jar:2.9.0]
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191) ~[proton-j-0.33.8.jar:na]
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) ~[proton-j-0.33.8.jar:na]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324) ~[proton-j-0.33.8.jar:na]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291) ~[proton-j-0.33.8.jar:na]
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:91) ~[azure-core-amqp-2.9.0.jar:2.9.0]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.5.8.jar:3.5.8]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.5.8.jar:3.5.8]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2024-01-29T15:42:27.046Z  INFO 26440 --- [ctor-executor-1] c.a.m.s.i.ServiceBusConnectionProcessor  : {"az.sdk.message":"Transient error occurred. Retrying.","exception":"connection aborted, errorContext[NAMESPACE: custom-domain.com. ERROR CONTEXT: N/A]","entityPath":"N/A","tryCount":0,"intervalMs":1800}
2024-01-29T15:42:27.046Z  INFO 26440 --- [ctor-executor-1] c.a.c.a.i.ReactorConnection              : {"az.sdk.message":"onConnectionShutdown. Shutting down.","connectionId":"MF_87da75_1706542589306","isTransient":false,"isInitiatedByClient":false,"shutdownMessage":"Finished processing pending tasks.","namespace":"custom-domain.com"}
2024-01-29T15:42:28.861Z  INFO 26440 --- [     parallel-4] c.a.m.s.i.ServiceBusConnectionProcessor  : {"az.sdk.message":"Requesting from upstream.","entityPath":"N/A","tryCount":0}
2024-01-29T15:42:28.861Z  INFO 26440 --- [     parallel-4] c.a.m.s.i.ServiceBusConnectionProcessor  : {"az.sdk.message":"Connection not requested, yet. Requesting one.","entityPath":"N/A"}
2024-01-29T15:42:28.862Z  INFO 26440 --- [     parallel-4] c.a.m.s.i.ServiceBusConnectionProcessor  : {"az.sdk.message":"Setting next AMQP channel.","entityPath":"N/A"}
2024-01-29T15:42:28.862Z  INFO 26440 --- [     parallel-4] c.a.c.a.i.ReactorConnection              : {"az.sdk.message":"Creating and starting connection.","connectionId":"MF_f668fa_1706542948861","hostName":"custom-domain.com","port":443}
2024-01-29T15:42:28.867Z  INFO 26440 --- [     parallel-4] c.a.c.a.implementation.ReactorExecutor   : {"az.sdk.message":"Starting reactor.","connectionId":"MF_f668fa_1706542948861"}
2024-01-29T15:42:28.867Z  INFO 26440 --- [     parallel-4] c.a.m.s.i.ServiceBusConnectionProcessor  : {"az.sdk.message":"Next AMQP channel received.","entityPath":"N/A","subscriberId":"un_860614_1706542947896"}
2024-01-29T15:42:28.870Z  INFO 26440 --- [ctor-executor-2] c.a.c.a.i.h.WebSocketsConnectionHandler  : {"az.sdk.message":"onConnectionInit","connectionId":"MF_f668fa_1706542948861","hostName":"custom-domain.com","namespace":"xxx-frontmessagebus.servicebus.windows.net"}
2024-01-29T15:42:28.870Z  INFO 26440 --- [ctor-executor-2] c.a.c.a.i.handler.ReactorHandler         : {"az.sdk.message":"reactor.onReactorInit","connectionId":"MF_f668fa_1706542948861"}
2024-01-29T15:42:28.870Z  INFO 26440 --- [ctor-executor-2] c.a.c.a.i.h.WebSocketsConnectionHandler  : {"az.sdk.message":"onConnectionLocalOpen","connectionId":"MF_f668fa_1706542948861","hostName":"xxx-frontmessagebus.servicebus.windows.net"}
2024-01-29T15:42:28.870Z  INFO 26440 --- [ctor-executor-2] c.a.c.a.i.h.WebSocketsConnectionHandler  : {"az.sdk.message":"onConnectionBound","connectionId":"MF_f668fa_1706542948861","hostName":"custom-domain.com","peerDetails":"custom-domain.com:443"}
2024-01-29T15:42:28.870Z  INFO 26440 --- [ctor-executor-2] c.a.c.a.i.h.WebSocketsConnectionHandler  : {"az.sdk.message":"Adding web socket layer","connectionId":"MF_f668fa_1706542948861"}
2024-01-29T15:42:29.126Z  INFO 26440 --- [ctor-executor-2] c.a.c.a.i.h.WebSocketsConnectionHandler  : {"az.sdk.message":"onConnectionRemoteOpen","connectionId":"MF_f668fa_1706542948861","hostName":"xxx-frontmessagebus.servicebus.windows.net","remoteContainer":"d9317470da9341bc97bba18cc5a7d12d_G11"}
2024-01-29T15:42:29.126Z  INFO 26440 --- [ctor-executor-2] c.a.m.s.i.ServiceBusConnectionProcessor  : {"az.sdk.message":"Channel is now active.","entityPath":"N/A"}
2024-01-29T15:42:29.169Z  INFO 26440 --- [ctor-executor-2] c.a.c.a.i.handler.SessionHandler         : {"az.sdk.message":"onSessionRemoteOpen","connectionId":"MF_f668fa_1706542948861","sessionName":"xxx/subscriptions/yyy","sessionIncCapacity":0,"sessionOutgoingWindow":2147483647}
2024-01-29T15:42:29.170Z  INFO 26440 --- [ctor-executor-2] c.a.c.a.i.ReactorConnection              : {"az.sdk.message":"Setting CBS channel.","connectionId":"MF_f668fa_1706542948861"}
2024-01-29T15:42:29.208Z  INFO 26440 --- [ctor-executor-2] c.a.c.a.i.handler.SessionHandler         : {"az.sdk.message":"onSessionRemoteOpen","connectionId":"MF_f668fa_1706542948861","sessionName":"cbs-session","sessionIncCapacity":0,"sessionOutgoingWindow":2147483647}
2024-01-29T15:42:29.209Z  INFO 26440 --- [ctor-executor-2] c.a.c.a.i.ReactorConnection              : {"az.sdk.message":"Emitting new response channel.","connectionId":"MF_f668fa_1706542948861","entityPath":"$cbs","linkName":"cbs"}
2024-01-29T15:42:29.209Z  INFO 26440 --- [ctor-executor-2] c.a.c.a.i.AmqpChannelProcessor           : {"az.sdk.message":"Setting next AMQP channel.","connectionId":"MF_f668fa_1706542948861","entityPath":"$cbs"}
2024-01-29T15:42:29.209Z  INFO 26440 --- [ctor-executor-2] c.a.c.a.i.AmqpChannelProcessor           : {"az.sdk.message":"Next AMQP channel received.","connectionId":"MF_f668fa_1706542948861","entityPath":"$cbs","subscriberId":"un_4f33de_1706542949170"}
2024-01-29T15:42:29.210Z  INFO 26440 --- [onPool-worker-3] c.m.a.msal4j.AcquireTokenSilentSupplier  : Returning token from cache
2024-01-29T15:42:29.210Z  INFO 26440 --- [onPool-worker-3] c.azure.identity.ClientSecretCredential  : Azure Identity => getToken() result for scopes [https://servicebus.azure.net/.default]: SUCCESS
2024-01-29T15:42:29.254Z  INFO 26440 --- [ctor-executor-2] c.a.c.a.i.handler.SendLinkHandler        : {"az.sdk.message":"onLinkRemoteOpen","connectionId":"MF_f668fa_1706542948861","linkName":"cbs:sender","entityPath":"$cbs","remoteTarget":"Target{address='$cbs', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, capabilities=null}"}
2024-01-29T15:42:29.255Z  INFO 26440 --- [ctor-executor-2] c.a.c.a.i.AmqpChannelProcessor           : {"az.sdk.message":"Channel is now active.","connectionId":"MF_f668fa_1706542948861","entityPath":"$cbs"}
2024-01-29T15:42:29.255Z  INFO 26440 --- [ctor-executor-2] c.a.c.a.i.handler.ReceiveLinkHandler     : {"az.sdk.message":"onLinkRemoteOpen","connectionId":"MF_f668fa_1706542948861","entityPath":"$cbs","linkName":"cbs:receiver","remoteSource":"Source{address='$cbs', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, distributionMode=null, filter=null, defaultOutcome=null, outcomes=null, capabilities=null}"}
2024-01-29T15:42:29.739Z  INFO 26440 --- [ctor-executor-2] c.a.c.a.i.ActiveClientTokenManager       : {"az.sdk.message":"Scheduling refresh token task.","scopes":"https://servicebus.azure.net/.default"}
2024-01-29T15:42:29.740Z  INFO 26440 --- [ctor-executor-2] c.a.c.a.implementation.ReactorSession    : {"az.sdk.message":"Creating a new receiver link.","connectionId":"MF_f668fa_1706542948861","sessionName":"xxx/subscriptions/yyy","linkName":"xxx/subscriptions/yyy_cf4289_1706542589377"}
2024-01-29T15:42:29.740Z  INFO 26440 --- [ctor-executor-2] c.a.m.s.i.ServiceBusReceiveLinkProcessor : {"az.sdk.message":"Setting next AMQP receive link.","linkName":"xxx/subscriptions/yyy_cf4289_1706542589377","entityPath":"xxx/subscriptions/yyy"}
2024-01-29T15:42:29.780Z  INFO 26440 --- [ctor-executor-2] c.a.c.a.i.handler.ReceiveLinkHandler     : {"az.sdk.message":"onLinkRemoteOpen","connectionId":"MF_f668fa_1706542948861","entityPath":"xxx/subscriptions/yyy","linkName":"xxx/subscriptions/yyy_cf4289_1706542589377","remoteSource":"Source{address='xxx/subscriptions/yyy', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, distributionMode=null, filter=null, defaultOutcome=null, outcomes=null, capabilities=null}"}
2024-01-29T15:42:33.007Z  INFO 26440 --- [       Thread-1] a.s.u.core.service.PersistenceService    : Message Processed
```
</details>

***Why is this not a Bug or a feature Request?***
I don't think this is a bug, but it might be. We don't control the server-side of this, so there may be a setting there that explains this.

**Setup (please complete the following information if applicable):**
 - OS: Linux
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-messaging-servicebus:7.15.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment] 2024-01-29 22:24
Hi @elFarto someone from the `service bus` sdk crew will follow up with you shortly via GitHub.  Please note that if this is an urgent issue, we recommend requesting assistance via an Azure support ticket: https://github.com/Azure/azure-sdk-for-java/blob/main/SUPPORT.md#how-to-file-issues-and-get-help-

/cc @anuchandy @Azure/azsdk-sb-java

**Comment by anuchandy** [comment] 2024-01-29 22:50
Hello @elFarto, these logs are the transient error messages which the library will retry. 

The reason for this to happen is – if the underlying TCP connection is idle for a period, then the service by design will proactively close the library connection. My observation is - the service idle timeout for the connection is 30 minutes and for link it’s 10 minutes. Your note on seeing this transient log under low receive frequency explains the reason for connection/link hitting idle timeout.

Additionally, it is possible that the host environment (e.g. AKS) in which the client is running may have a shorter idle timeout for TCP connections. 

Both idle timeouts are outside the control of the library, but the library will do necessary retries when this happens.

Hope this clarifies.

**Comment by elFarto** [comment] 2024-01-30 07:57
That does seem to correlate to what I'm seeing, but here the idle timeout seems to be ~80 seconds which is suspiciously low. I'll follow up with the service that we're using to confirm what they have the idle timeout set to.

However, the main issue we have here is that having these errors constantly printed in the log files makes it tricky for us to detect if there's some other problem with our application (we monitor how many ERROR log entries are printed). Having the library print ERRORs on what is a retryable condition (a WARN at best) is somewhat misleading.
We have considered suppressing that logger completely, but that would likely hide real connection errors.

Is there any way that the ERROR messages logged while attempting a retry could be changed to WARN, and only ERROR if the retry fails?

**Comment by elFarto** [comment] 2024-02-07 09:43
I've received a reply back from the group that runs that message bus and they say they have no timeout configured, which I take to mean they haven't changed any of the timeout options (I don't know if there even are any timeout options available to change).

So I've done a bit more digging. The application that's normally connected to that message bus runs in AWS and runs through a NAT gateway for internet access. NAT GWs have an idle connection timeout of 350 seconds, so it's possible but unlikely that is the cause.

I can also reproduce this on my local PC, and managed to capture it occuring with Wireshark. The connection dropped after just 2 minutes of the application running, and only 20 seconds since the last message was received, at which point the server just sent a FIN packet and closed the connection.

![image](https://github.com/Azure/azure-sdk-for-java/assets/2325080/8561ecb6-1444-4e40-8134-4f47b213643b)

I don't think this is a client issue, but there's definetaly something amiss here.

**Comment by anuchandy** [comment] 2024-03-04 21:08
In the logs, I noticed that there is a custom domain (custom-domain.com) that works as a host between Service Bus and the SDK. Can we try locally if frequent disconnect-reconnect happens when we connect directly to the Service Bus without this intermediate host? i.e., using the host in the Service Bus connection string (which will look like this: “<namespace>.servicebus.windows.net”)

**Comment by anuchandy** [comment] 2024-03-25 18:12
Closing this. The current theory is that the TCP close (FIN) segment is coming from an intermediate host in the host networking. Please reopen if disconnect is rooted as coming from the Service Bus endpoint, which should be followed with the Service Team owning Service Bus.

**Closed by anuchandy** 2024-03-25 18:12 UTC
Labels: question, Service Bus, Client, customer-reported, needs-team-triage
