### ISSUE TITLE
Azure KeyVault SDK - getSecret - improve/fix the misleading info message

### ISSUE THREAD

**Issue by razidare** [Azure/azure-sdk-for-java#3797] opened 2019-06-03 11:11 UTC
**Query/Question**
When sending multiple getSecret requests from a Java application to Azure KeyVault, random behavior appears:

INFO  c.m.a.k.KeyVaultClientBase getSecret - <-- HTTP FAILED: java.net.SocketException: Connection reset

Although the body states failure and socketException, the secret value IS RETURNED correctly and the message is printed with INFO.

This made us investigate quite a lot in our production environment to understand this behavior. We had an ongoing Microsoft case - 119051422001422 -  in which we tried to reproduce and understand this behavior.

We want to understand why is this INFO message so misleading and what is the designed behavior of it? If getSecret succeeds returning the secret, why do we still print this message?

***Why is this not a Bug or a feature Request?***
We just seek understanding of this behavior, as we do not see this issue as a bug, but more like a wrongful message being printed.

**Setup (please complete the following information if applicable):**
 - OS: [e.g. iOS] N/A
 - IDE : [e.g. IntelliJ] N/A 
 - we used a JAVA mock loop which was calling getSecret every 500 ms against an Azure KeyVault and the described behavior was intermittent and random
 - Version of the Library used: 1.2.0

**Comment by kurtzeborn** [comment] 2019-06-03 18:26
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

CC: @g2vinay

**Comment by joshfree** [comment] 2019-07-10 21:27
@g2vinay could you please take a look at this issue to understand why the INFO: ... Connection Reset is occurring?

**Comment by g2vinay** [comment] 2019-07-24 18:12
SocketConnectionException is getting logged as INFO.
Here is my initial investigation: 
upon further reading about this (https://support.esri.com/en/technical-article/000012876)
1. Socket Exception can happen when a RST packet is received from the remote service.
2. Socket is abruptly closed when there is data to read in the receive buffer or to send in the send buffer.

Since customer got the secret back successfully, one of these cases might've happened and an info message got logged as it didn't cause failures.
Getting this error doesn't always mean that the service response backfired, abruptly closing the socket on client side causes this too.

**Comment by joshfree** [comment] 2019-10-28 16:50
Updating title to better reflect the action that is required - improve the logging messages in Azure KeyVault SDK for Java

**Comment by linehammer** [comment] 2019-12-17 05:23
Connection reset [socket](http://net-informations.com/java/net/socket.htm) error occurs when the opponent is forcibly terminated without calling close(). This  simply means that a TCP RST was received. TCP RST packet is that the remote side telling you the connection on which the previous TCP packet is sent is not recognized, maybe the connection has closed, maybe the port is not open, and something like these. A reset packet is simply one with no payload and with the RST bit set in the TCP header flags. There are several possible causes.

- The other end has deliberately reset the connection, in a way which I will not document here. It is rare, and generally incorrect, for application software to do this, but it is not unknown for commercial software.

- More commonly, it is caused by writing to a connection that the other end has already closed normally. In other words an application protocol error.

- It can also be caused by closing a socket when there is unread data in the socket receive buffer.

**Comment by g2vinay** [comment] 2020-04-09 19:29
@razidare 
This info level message is driven by the network behavior in KV Track 1.
In error producing cases where application code breaks, the log level would be Error.

We've shipped next gen KV SDKs, the v4.x azure-security-keyvault-* libraries are the latest supported SDK libraries for KeyVault. We do recommend upgrading to this latest stable, supported release. Packages and more information can be found here:
1. https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-secrets
2. https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/keyvault/azure-security-keyvault-keys/README.md
3. https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-certificates

**Comment by razidare** [comment] 2020-04-13 07:13
@g2vinay thank you for your reply.
We will be following your advice and use the latest version of the libraries

Cheers,
Radu

**Comment by g2vinay** [comment] 2020-05-12 18:36
@razidare 
Do file issues if you run into any problems with the new KV libraries. 
Thanks for moving to new libraries.

**Closed by g2vinay** 2020-05-12 18:36 UTC
Labels: Client, KeyVault, bug, customer-reported
