### ISSUE TITLE
[BUG] Json parse exception while request OpenAI API in java 

### ISSUE THREAD

**Issue by cuongnguyengit** [Azure/azure-sdk-for-java#35731] opened 2023-07-04 02:24 UTC
**Describe the bug**
Hi Microsoft Dev Team,
I had an exception when i requested to your openai azure api.
I used the sample code 
final List<ChatMessage> messages = new ArrayList<>();
        messages.add(new.ChatMessage(ChatRole.USER).setContent("tôi cần gì đâu"));

        com.azure.ai.openai.models.ChatCompletionsOptions options = new com.azure.ai.openai.models.ChatCompletionsOptions(messages);
        options.setModel("gpt-35-turbo");
        options.setStream(false);
        options.setN(1);
        options.setMaxTokens(256);
        options.setLogitBias(new HashMap<>());
ChatCompletions chatCompletions = client.getChatCompletions("***", options);

***Exception or Stack Trace***
09:14:44.921 [main] ERROR com.azure.core.implementation.serializer.DefaultJsonSerializer - com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'data': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false') at [Source: (byte[])"data: {"id":"chatcmpl-7YPqqfztcROs341l4dOLDvFXvFOlv","object":"chat.completion.chunk","created":1688436880,"model":"gpt-35-turbo","choices":[{"index":0,"finish_reason":null,"delta":{"role":"assistant"}}],"usage":null}data: {"id":"chatcmpl-7YPqqfztcROs341l4dOLDvFXvFOlv","object":"chat.completion.chunk","created":1688436880,"model":"gpt-35-turbo","choices":[{"index":0,"finish_reason":null,"delta":{"content":"L"}}],"usage":null}data: {"id":"chatcmpl-7YPqqfztcROs341l4dOLDvFXvFOlv","object":"chat"[truncated 26688 bytes]; line: 1, column: 6]
java.io.UncheckedIOException: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'data': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (byte[])"data: {"id":"chatcmpl-7YPqqfztcROs341l4dOLDvFXvFOlv","object":"chat.completion.chunk","created":1688436880,"model":"gpt-35-turbo","choices":[{"index":0,"finish_reason":null,"delta":{"role":"assistant"}}],"usage":null}

data: {"id":"chatcmpl-7YPqqfztcROs341l4dOLDvFXvFOlv","object":"chat.completion.chunk","created":1688436880,"model":"gpt-35-turbo","choices":[{"index":0,"finish_reason":null,"delta":{"content":"L"}}],"usage":null}

data: {"id":"chatcmpl-7YPqqfztcROs341l4dOLDvFXvFOlv","object":"chat"[truncated 26688 bytes]; line: 1, column: 6]
	at com.azure.core.implementation.serializer.DefaultJsonSerializer.deserializeFromBytes(DefaultJsonSerializer.java:34)
	at com.azure.core.implementation.util.FluxByteBufferContent.toObject(FluxByteBufferContent.java:94)
	at com.azure.core.util.BinaryData.toObject(BinaryData.java:1241)
	at com.azure.core.util.BinaryData.toObject(BinaryData.java:1003)
	at com.azure.ai.openai.OpenAIClient.getChatCompletions(OpenAIClient.java:384)

**Comment by alzimmermsft** [comment] 2023-07-05 12:56
Closing this as it's a duplicate of #35734 (and while this issue was created first the other specifies which library has an issue).

**Closed by alzimmermsft** 2023-07-05 12:56 UTC
Labels: question, customer-reported, needs-triage
