### ISSUE TITLE
[BUG] Service Bus Web socket connection frame size too small

### ISSUE THREAD

**Issue by elFarto** [Azure/azure-sdk-for-java#37409] opened 2023-10-26 09:21 UTC
**Describe the bug**
I've noticed some situations where reading messages from a service bus can get stuck, especially when retrieving a large amount of maxMessages. When this happens the CPU usage of the process jumps to 100% of one core. I believe I've traced this issue back to the frame size of the websocket connection being limited to 4,224bytes, rather than the 262,144 or 1,048,576 bytes that Service Bus supports.

The process seems to be locked up in an endless loop of trying to copy bytes to a ByteBuffer that's already full, so it continually copies 0 bytes. The underlying Qpid library does now support passing a custom max frame size, so the code should be modified to use that.

**To Reproduce**
Attempt to recieve a message larger than 4,224 bytes.

**Expected behavior**
A large frame should not lock up the process.

**Setup (please complete the following information):**
 - OS: Windows
 - Library/Libraries: com.azure:azure-messaging-servicebus:7.14.3
 - Java version: 17
 - Frameworks: Spring Boot

**Comment by anuchandy** [comment] 2024-04-23 22:11
I'm trying to reproduce this with the below code that uses web-socket, but it is able to send-receive messages bigger than 4.224 bytes, I've tried 1MB and 2 MB.
 
```java
        final byte[] payload = "this is a circular payload that is used to fill up the message".getBytes(StandardCharsets.UTF_8);
        final int messageSize = 1048576; // 1MB
        final StringBuilder body = new StringBuilder(messageSize);
        for (int i = 0; i < messageSize; i++) {
            body.append(payload[i % payload.length]);
        }
        final BinaryData bodyToSend = BinaryData.fromString(body.toString());

        final ServiceBusSenderClient sender = new ServiceBusClientBuilder()
                .transportType(AmqpTransportType.AMQP_WEB_SOCKETS)
                .connectionString(CONN_STR) // Premium namespace to send-receive big messages.
                .sender()
                .queueName(queueName)
                .buildClient();

        final ServiceBusMessageBatch batch = sender.createMessageBatch();
        if (!batch.tryAddMessage(new ServiceBusMessage(bodyToSend))) {
            throw new RuntimeException("Message size exceeds the maximum size of a batch");
        }
        sender.sendMessages(batch);

        TimeUnit.SECONDS.sleep(10);

        final ServiceBusReceiverClient receiver = new ServiceBusClientBuilder()
                .transportType(AmqpTransportType.AMQP_WEB_SOCKETS)
                .connectionString(CONN_STR)
                .receiver()
                .receiveMode(ServiceBusReceiveMode.PEEK_LOCK)
                .disableAutoComplete()
                .queueName(queueName)
                .buildClient();

        IterableStream<ServiceBusReceivedMessage> messages = receiver.receiveMessages(1);
        messages.stream().collect(Collectors.toList()).forEach(m -> {
            final BinaryData receivedBody = m.getBody();
            if (receivedBody.toString().equals(bodyToSend.toString())) {
                System.out.println("Message received successfully");
            } else {
                System.out.println("Message received is not the same as sent");
            }
            receiver.complete(m);
        });
```

Did I miss anything?

**Comment by anuchandy** [comment] 2024-05-01 00:42
Closing this since no repro. Please re-open when/if additional info is available to investigate this.

**Closed by anuchandy** 2024-05-01 00:42 UTC
Labels: question, Service Bus, Client, customer-reported, needs-author-feedback, backlog
