### ISSUE TITLE
[BUG] jarsigner + jca reports that entries in certificate chain are invalid

### ISSUE THREAD

**Issue by 3millionminds** [Azure/azure-sdk-for-java#41832] opened 2024-09-12 16:22 UTC
### Describe the bug
When using a valid, DigiCert issued, non-exportable Azure Key Vault certificate to sign a `.jar` file with `jarsigner + jca 2.8.2` OR `jarsigner + jca 2.9.0-beta.3`, the file is signed with apparently no issues.
```
>>> Signer
    X.509, CN=██████████ Limited, O=██████████ Limited, L=London, C=GB
    [trusted certificate]

jar signed.
```

However, upon verifying the file, a warning is produced:
```
This jar contains entries whose certificate chain is invalid.
Reason:
    PKIX path building failed:
        sun.security.provider.certpath.SunCertPathBuilderException:
            unable to find valid certification path to requested target
```

This prevents the jar file to run on high-security systems, and we are unable to run the applications.

### Exception or Stack Trace
[jca282_signing.log](https://github.com/user-attachments/files/16982576/jca282_signing.log)
[jca282_verify.log](https://github.com/user-attachments/files/16982577/jca282_verify.log)
[jca282_environment.log](https://github.com/user-attachments/files/16982578/jca282_environment.log)

[jca290_signing.log](https://github.com/user-attachments/files/16982580/jca290_signing.log)
[jca290_verify.log](https://github.com/user-attachments/files/16982581/jca290_verify.log)
[jca290_environment.log](https://github.com/user-attachments/files/16982585/jca290_environment.log)

### To Reproduce
1. Sign a JAR file with `jarsigner` and `azure-security-keyvault-jca-2.8.2.jar` (or 2.9.0-beta.3), *with a valid certificate issued by DigiCert* and stored in AzKV.
    ```
    $ jarsigner -keystore NONE -storetype AzureKeyVault \
            -signedjar SIGNED_SignMe.jar SignMe.jar "██████████CodeSigning" \
            -verbose -storepass "" \
            -tsa "http://timestamp.digicert.com/" \
            -providerName AzureKeyVault \
            -providerClass com.azure.security.keyvault.jca.KeyVaultJcaProvider \
            -J-Dazure.keyvault.uri="██████████" \
            -J-Dazure.keyvault.tenant-id="██████████" \
            -J-Dazure.keyvault.client-id="██████████" \
            -J-Dazure.keyvault.client-secret="██████████" 
    [lines omitted]
    >>> Signer
        X.509, CN=██████████ Limited, O=██████████ Limited, L=London, C=GB
        [trusted certificate]
    
    jar signed.
    ```

2. Verify it's signature
    ```
        $ jarsigner -verify SIGNED_SignMe.jar 

        jar verified.

        Warning: 
        This jar contains entries whose certificate chain is invalid.
        Reason:
            PKIX path building failed:
                sun.security.provider.certpath.SunCertPathBuilderException:
                    unable to find valid certification path to requested target

    ```

**Expected behavior**
There `.jar` should be signed, and there should be no warnings when verifying the signature.

**Screenshots**
![image](https://github.com/user-attachments/assets/967d04d8-6ee3-4856-adc7-05f39afe02fc)

**Setup (please complete the following information):**
 - OS: (containerized) Red Hat Enterprise Linux release 8.10 (Ootpa)
 - IDE: N/A
 - Library/Libraries:
   - `com.azure:azure-security-keyvault-jca:2.8.2`
   - `com.azure:azure-security-keyvault-jca:2.9.0-beta.3` (built from rev [ac9ee6330b6](https://github.com/Azure/azure-sdk-for-java/commit/ac9ee6330b688f1b3eeea77548f1897be25782da))
 - Java version: openjdk-1.8.0_422 
 - App Server/Environment: N/A
 - Frameworks: N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by vcolin7** [comment] 2024-09-12 22:49
HI @3millionminds, thank you for filing this issue, I'll pass it along to the team.

@saragluna, @rujche Could you take a look when you get a chance? Thanks!

**Comment by rujche** [comment] 2024-09-13 01:49
Hi, @3millionminds 

Thanks for reaching out.

It's weird that when you sign the jar, the signer only has one cert, and the cert is trusted
> ![image](https://github.com/user-attachments/assets/0e79a55c-f501-4817-ad91-bb128dd07d1c)

In my understanding, it should be a chain, and only the root cert is trusted. Here is an example: https://github.com/Azure/azure-sdk-for-java/pull/41303#issuecomment-2257325521
> ![image](https://github.com/user-attachments/assets/32c5f59e-999c-4f38-a568-61ccbc0ee78f)



Could you please add `verbose` to the verify command and share the output log? Here is an example of adding `verbose`: 
```shell
jarsigner -verify -verbose -certs SIGNED_SignMe..jar
```
**Caution**: remove private information when upload the log file, just like you did above.

**Comment by 3millionminds** [comment] 2024-09-13 05:33
Hello @rujche, thank you for picking up this issue.

Here are the logs:
[jca282_verbose_verify.log](https://github.com/user-attachments/files/16988939/jca282_verbose_verify.log)
[jca290_verbose_verify.log](https://github.com/user-attachments/files/16988940/jca290_verbose_verify.log)

I will try and import the root ca into the local keystore first and then follow the signing&verification process.
The `-keystore NONE` makes it a bit misleading since the assumption is that it is not using the local keystore at all.

I will return with the results.

**Comment by 3millionminds** [comment] 2024-09-13 05:58
@rujche if import the DigiCert CA into the local keystore it works on the machine where it is imported in the keystore.
If I verify on a different machine, same thing as before happens.

```
    Warning: 
    This jar contains entries whose certificate chain is invalid.
    Reason:
        PKIX path building failed:
            sun.security.provider.certpath.SunCertPathBuilderException:
                unable to find valid certification path to requested target
```

Same thing if I import only our certificate.

**Comment by rujche** [comment] 2024-09-14 06:23
Hi, @3millionminds 

### 1. About importing the DigiCert CA into the local keystore

>  if import the DigiCert CA into the local keystore it works on the machine where it is imported in the keystore.
If I verify on a different machine, same thing as before happens.

By saying `import the DigiCert CA into the local keystore`, do you mean adding to `cacerts` like this:

```shell
keytool -import -alias digicertca -keystore $JAVA_HOME/jre/lib/security/cacerts -file DigiCertCA.crt
```

### 2. Root CA cert should be added into cacerts
To verify a jar signed by a cert, the cert's root CA cert should be added in to `$JAVA_HOME/jre/lib/security/cacerts`. In your case, it's `DigiCert CA`. In some cases, the `DigiCert CA` was already added into cacerts when install Java. If cacerts not include `DigiCert CA` then you should add it manually. Refs: https://knowledge.digicert.com/general-information/importing-digicert-pki-ca-certificates-into-java-ca-certificates-keystore

### 3. Seems there is only one cert in the cert chain.
As mentioned above https://github.com/Azure/azure-sdk-for-java/issues/41832#issuecomment-2347881074, it's weird that in your provided log, the signer only has one cert, is this cert self-signed? it shouldn't be. It should be signed by DigiCert CA. 

> ![image](https://github.com/user-attachments/assets/7abbd2ca-de61-4315-b415-c15d0f7a215b)

In my test case (https://github.com/Azure/azure-sdk-for-java/pull/41303#issuecomment-2257325521), both sign and verify showed 3 certs in the cert chain:

> ![image](https://github.com/user-attachments/assets/c82c42bf-4e9a-40b2-8a30-c69272c8a083)

> ![image](https://github.com/user-attachments/assets/14237722-3139-4d2e-9f79-46c5383654fc)

**Comment by 3millionminds** [comment] 2024-09-15 08:24
Hi @rujche 

1. Yes, that is exactly how I import it.
2. Yes, I have imported the DigiCert CA into `cacerts`.
3. The certificate is not self-signed, it is signed by DigiCert themselves.

After installing the DigiCert CA on the machine where I do the signing, I can verify the jar file, it no longer complains about the certificate chain.

But, as mentioned [here](https://github.com/Azure/azure-sdk-for-java/issues/41832#issuecomment-2348092820), when trying to verify the jar on a different machine, the issue returns. I imagine if they had the certificate in their `cacerts` it would also work for them.

Our usecase is the following: the jars are built, signed, and then packaged into a larger application, which is delivered to the end clients. This software is then deployed on hundreds of computers where, due to security restrictions, it cannot run.

Before switching to Azure Key Vault, a local PFX certificate was used for signing.
Signing was done by Maven during the build, by leveraging the `maven-jarsigner-plugin`.
I have asked around and nobody is aware of us delivering any certificates, or keystores, or anything else except the packaged software itself.
However, when using this method, the packages could be verified and run on these client systems.

**Comment by rujche** [comment] 2024-09-18 01:22
Hi, @3millionminds 


### 1. About the cert chain

> 3. The certificate is not self-signed, it is signed by DigiCert themselves.

In my understanding, if it is signed by DigiCert, then the cert chain should have more than one cert. When sign and verify jar file using the cert, it should display all the certs in the cert chain. But your log only show one cert. I'm confused about this. 

### 2. About your use case.

> Before switching to Azure Key Vault, a local PFX certificate was used for signing.
Signing was done by Maven during the build, by leveraging the maven-jarsigner-plugin.
I have asked around and nobody is aware of us delivering any certificates, or keystores, or anything else except the packaged software itself.
However, when using this method, the packages could be verified and run on these client systems.

Now I understand your case. Now I'm also confused why it work with the local pfx file but not work with Azure Key Vault method.

### 3. How to do next step?

I suggest you do these things:
1. Show the cert chain by method like this: https://serverfault.com/questions/1011294/how-to-view-certificate-chain-using-openssl The cert chain should have more than one cert. If the cert chain only has one cert, investigate why it only has one cert. 
2. Sign the jar file by both local method and Key Vault method, and confirm the cert chain is the same with step 1. The cert chain should have more than one cert. If the cert chain only has one cert, investigate why it only has one cert. 
3. Verify the signed jar, and confirm the cert chain is the same with step 1. The cert chain should have more than one cert. If the cert chain only has one cert, investigate why it only has one cert. 

If the problem still can not be solved after above steps, please share related log, and let's think about how to do next step.

**Comment by rujche** [comment] 2024-09-19 01:47
Hi, @3millionminds 

### 1. About DigiCert root CA.

> 1. Here is the certificate chain:

In your screenshot, the root cert seems already included in the `cacerts`.
I confirmed by this command:
```shell
 keytool -list -keystore "C:\Program Files\Microsoft\jdk-17.0.11.9-hotspot\lib\security\cacerts"
```
Here is the output:
```shell
...
cn=digicert_trusted_root_g4,ou=www.digicert.com,o=digicert_inc,c=us, 13 Mar 2024, trustedCertEntry,
Certificate fingerprint (SHA-256): 55:2F:7B:DC:F1:A7:AF:9E:6C:E6:72:01:7F:4F:12:AB:F7:72:40:C7:8E:76:1A:C2:03:D1:D9:D2:0A:C8:99:88
...
```

**Could you please confirm that the DigiCert root cert already included in your cacerts too?**

### 2. Sign by the cert provided by DigiCert.

> Unfortunately I can no longer sign it locally, since I don't have the PFX keystore. It is not provided by DigiCert.

I found this doc: https://knowledge.digicert.com/tutorials/export-your-ssl-certificate-using-the-digicert-certificate-utility-pfx-format

To sign a jar file, a private key is necessary. For security reason, sometimes the private key is not exportable. We can ignore the part of `sign it locally` for now.

### 3. What to do next step?

Please confirm these things:
1. Confirm the DigiCert root cert included in the `cacerts` in your environment.
2. If the root cert included in `cacerts` by default, why import manually is necessary as described below:

> if import the DigiCert CA into the local keystore it works on the machine where it is imported in the keystore.
If I verify on a different machine, same thing as before happens.

**Comment by 3millionminds** [comment] 2024-09-27 08:53
Hello @rujche 

Sorry for the delay, we had to stop debugging this issue for a while in order to manually sign, with a hardware token, a product release.

So, I have checked that the DigiCert root CA is included in the cacerts.
The output is below. There seem to be quite a few digicert related certificates there.
DigiCertCA is the alias of the one imported by me.
```
digicertassuredidrootca, Sep 10, 2024, trustedCertEntry, 
Certificate fingerprint (SHA-256): 3E:90:99:B5:01:5E:8F:48:6C:00:BC:EA:9D:11:1E:E7:21:FA:BA:35:5A:89:BC:F1:DF:69:56:1E:3D:C6:32:5C
digicertassuredidrootg2, Sep 10, 2024, trustedCertEntry, 
Certificate fingerprint (SHA-256): 7D:05:EB:B6:82:33:9F:8C:94:51:EE:09:4E:EB:FE:FA:79:53:A1:14:ED:B2:F4:49:49:45:2F:AB:7D:2F:C1:85
digicertassuredidrootg3, Sep 10, 2024, trustedCertEntry, 
Certificate fingerprint (SHA-256): 7E:37:CB:8B:4C:47:09:0C:AB:36:55:1B:A6:F4:5D:B8:40:68:0F:BA:16:6A:95:2D:B1:00:71:7F:43:05:3F:C2
digicertca, Sep 27, 2024, trustedCertEntry, 
Certificate fingerprint (SHA-256): 46:01:1E:DE:1C:14:7E:B2:BC:73:1A:53:9B:7C:04:7B:7E:E9:3E:48:B9:D3:C3:BA:71:0C:E1:32:BB:DF:AC:6B
digicertglobalrootca, Sep 10, 2024, trustedCertEntry, 
Certificate fingerprint (SHA-256): 43:48:A0:E9:44:4C:78:CB:26:5E:05:8D:5E:89:44:B4:D8:4F:96:62:BD:26:DB:25:7F:89:34:A4:43:C7:01:61
digicertglobalrootg2, Sep 10, 2024, trustedCertEntry, 
Certificate fingerprint (SHA-256): CB:3C:CB:B7:60:31:E5:E0:13:8F:8D:D3:9A:23:F9:DE:47:FF:C3:5E:43:C1:14:4C:EA:27:D4:6A:5A:B1:CB:5F
digicertglobalrootg3, Sep 10, 2024, trustedCertEntry, 
Certificate fingerprint (SHA-256): 31:AD:66:48:F8:10:41:38:C7:38:F3:9E:A4:32:01:33:39:3E:3A:18:CC:02:29:6E:F9:7C:2A:C9:EF:67:31:D0
digicerthighassuranceevrootca, Sep 10, 2024, trustedCertEntry, 
Certificate fingerprint (SHA-256): 74:31:E5:F4:C3:C1:CE:46:90:77:4F:0B:61:E0:54:40:88:3B:A9:A0:1E:D0:0B:A6:AB:D7:80:6E:D3:B1:18:CF
digicerttlseccp384rootg5, Sep 10, 2024, trustedCertEntry, 
Certificate fingerprint (SHA-256): 01:8E:13:F0:77:25:32:CF:80:9B:D1:B1:72:81:86:72:83:FC:48:C6:E1:3B:E9:C6:98:12:85:4A:49:0C:1B:05
digicerttlsrsa4096rootg5, Sep 10, 2024, trustedCertEntry, 
Certificate fingerprint (SHA-256): 37:1A:00:DC:05:33:B3:72:1A:7E:EB:40:E8:41:9E:70:79:9D:2B:0A:0F:2C:1D:80:69:31:65:F7:CE:C4:AD:75
digicerttrustedrootg4, Sep 10, 2024, trustedCertEntry, 
Certificate fingerprint (SHA-256): 55:2F:7B:DC:F1:A7:AF:9E:6C:E6:72:01:7F:4F:12:AB:F7:72:40:C7:8E:76:1A:C2:03:D1:D9:D2:0A:C8:99:88
```

For your second point, "investigate why import manually is necessary", I can relate the following:
1. When we sign `.exe`/`.dll` files with `AzureSignTool`, they get signed with the entire chain of certificates. We don't do anything else on the signing machines, or the "end-user" machines. We don't import any certificates, nothing. We just sign it, and the signature is valid.
See here:
![image](https://github.com/user-attachments/assets/c9fcc88b-32e3-402c-99a4-7fc6c5d19d4c)

2. When we sign `.jar` files, with jarsigner and a **DigiCert Hardware eToken**, the entire certificate chain appears when verifying the signatures of the classes:
```
[entry was signed on 24.09.2024, 14:16]
>>> Signer
X.509, CN=██████████ Limited, O=██████████ Limited, L=London, C=GB
Signature algorithm: SHA256withRSA, 4096-bit key
[certificate is valid from 18.09.2024, 03:00 to 05.04.2027, 02:59]
C=US
Signature algorithm: SHA384withRSA, 4096-bit key
[certificate is valid from 29.04.2021, 03:00 to 29.04.2036, 02:59]
X.509, CN=DigiCert Trusted Root G4, OU=www.digicert.com, O=DigiCert Inc, C=US
Signature algorithm: SHA384withRSA, 4096-bit key
[trusted certificate]
>>> TSA
X.509, CN=DigiCert Timestamp 2023, O="DigiCert, Inc.", C=US
Signature algorithm: SHA256withRSA, 4096-bit key
[certificate is valid from 14.07.2023, 03:00 to 14.10.2034, 02:59]
X.509, CN=DigiCert Trusted G4 RSA4096 SHA256 TimeStamping CA, O="DigiCert, Inc.", C=US
Signature algorithm: SHA256withRSA, 4096-bit key
[certificate is valid from 23.03.2022, 02:00 to 23.03.2037, 01:59]
X.509, CN=DigiCert Trusted Root G4, OU=www.digicert.com, O=DigiCert Inc, C=US
Signature algorithm: SHA384withRSA, 4096-bit key
[certificate is valid from 01.08.2022, 03:00 to 10.11.2031, 01:59]
```

When signing the `.jar` with this hardware token, we are also able to verify the signatures on any other devices, without having to install _any_ certificates on the systems.
I also did not install _any_ other extra certificates on my local machine in order to sign. Not the DigiCert CA, not even our certificate.

So my guess is there is something not working properly in the way the certificates are retrieved from Azure KeyVault.
I don't understand, otherwise, how signing `.exe`/`.dll` with the same KeyVault but with a different tool works, and signing `.jar` with the same certificates from a local hardware token also works, but not from KV.

**Comment by rujche** [comment] 2024-10-02 02:28
Hi, @3millionminds 

Sorry for late response.

> When we sign .jar files, with jarsigner and a DigiCert Hardware eToken, the entire certificate chain appears when verifying the signatures of the classes:

> 
> Signer
X.509, CN=██████████ Limited, O=██████████ Limited, L=London, C=GB
Signature algorithm: SHA256withRSA, 4096-bit key
[certificate is valid from 18.09.2024, 03:00 to 05.04.2027, 02:59]
C=US
Signature algorithm: SHA384withRSA, 4096-bit key
[certificate is valid from 29.04.2021, 03:00 to 29.04.2036, 02:59]
X.509, CN=DigiCert Trusted Root G4, OU=www.digicert.com, O=DigiCert Inc, C=US
Signature algorithm: SHA384withRSA, 4096-bit key
[trusted certificate]

This looks good because the whole chain appeared when sign the file.

## What to do next

1. Now I guess the problem only happens when the cert is non-exportable, but not confirmed yet.
2. Out team is in Shanghai office, now we are on holiday until October 8. If you are available, could you please help to confirm this: This problem only happens when the cert is non-exportable. When the cert is exportable, it will not have this problem.

**Comment by 3millionminds** [comment] 2024-10-14 07:43
Hello @rujche 

I can confirm points 1.1 and 1.2.

For 1.3:
Our problem occurs when using the certificates from Azure Key Vault.
When using the hardware token everything is OK: we can sign with no issues, and it can be verified properly on any system.

The token was requested _after_ we reported this issue.

Thank you.

**Comment by rujche** [comment] 2024-10-17 13:55
Hi, @moarychan .
Could you please help to investigate this issue?

**Comment by saragluna** [comment] 2024-10-28 02:32
Closing this issue now, please reopen it if the issue is not resolved.

**Comment by dacron** [comment] 2024-10-29 14:53
@saragluna this still doesn't work, please could you reopen?

If you use a standard RSA key it works with a self-signed multi-tier openssl-based certificate authority.

If you use a key of type RSA-HSM and a DigiCert signed certificate it does not work. I'm working to recreate my CA environment so that $company_name is not in the subject name. Once done I will post extra debug information here.

**Comment by 3millionminds** [comment] 2024-10-30 09:31
> [@3millionminds](https://github.com/3millionminds) did this work for you?

Hello,

Unfortunately we have been unable to test.
We are unable to merge new certificates on top of the ones we already have in Azure Key Vault.

We have opened a MS ticket to see what options we have here.

**Comment by dacron** [comment] 2024-10-30 11:05
More data points. Given an exportable RSA key type with the self-signed setup the output of verify is:

```
[removed]@[removed] AzureKeyVault % jarsigner -verify helloworld.signed.jar -verbose

s        166 Wed Oct 30 10:52:08 GMT 2024 META-INF/MANIFEST.MF
         299 Wed Oct 30 10:52:08 GMT 2024 META-INF/2024OVCS.SF
        5017 Wed Oct 30 10:52:08 GMT 2024 META-INF/2024OVCS.RSA
           0 Wed Jan 15 14:43:32 GMT 2020 META-INF/
sm       446 Wed Jan 15 14:21:40 GMT 2020 HelloWorld.class

  s = signature was verified 
  m = entry is listed in manifest
  k = at least one certificate was found in keystore

- Signed by "[REMOVED]"
    Digest algorithm: SHA256
    Signature algorithm: SHA256withRSA, 3072-bit key

jar verified.`
```

This is good.

Extracting the signed jar and running META-INF/2024OVCS.RSA through openssl:

```
adacre@macVY6HY6GQP1 AzureKeyVault % openssl pkcs7 -in extracted/META-INF/2024OVCS.RSA -inform DER -print | grep subject: -A6
          subject: [REMOVED - DN OF SIGNING CERT]
          key:           X509_PUBKEY: 
            algor: 
              algorithm: rsaEncryption (1.2.840.113549.1.1.1)
              parameter: NULL
            public_key:  (0 unused bits)
              0000 - 30 82 01 8a 02 82 01 81-00 b6 e2 bc 72 52   0...........rR
--
          subject: [REMOVED - DN OF INTERMEDIATE CA]
          key:           X509_PUBKEY: 
            algor: 
              algorithm: rsaEncryption (1.2.840.113549.1.1.1)
              parameter: NULL
            public_key:  (0 unused bits)
              0000 - 30 82 02 0a 02 82 02 01-00 97 bc 2f d6 63   0........../.c
--
          subject: [REMOVED - DN OF ROOT CA]
          key:           X509_PUBKEY: 
            algor: 
              algorithm: rsaEncryption (1.2.840.113549.1.1.1)
              parameter: NULL
            public_key:  (0 unused bits)
              0000 - 30 82 02 0a 02 82 02 01-00 e9 3d 47 f7 b1   0.........=G..
```

Notice the order: LEAF => INTERMEDIATE => ROOT. The signed CSR was imported in to a Key Vault as merge operation. The PEM file used contained the full chain in this order: ROOT => INTERMEDIATE => LEAF.

If I do the same process as above for a HSM backed key using the same openssl multi-tier CA we get different results. The output of verify is:

```
[removed]@[removed] AzureKeyVault % jarsigner -verify helloworld.signed.jar -verbose

         166 Wed Oct 30 11:00:32 GMT 2024 META-INF/MANIFEST.MF
         299 Wed Oct 30 11:00:32 GMT 2024 META-INF/SSMULTI.SF
        5014 Wed Oct 30 11:00:32 GMT 2024 META-INF/SSMULTI.RSA
           0 Wed Jan 15 14:43:32 GMT 2020 META-INF/
 m  ?    446 Wed Jan 15 14:21:40 GMT 2020 HelloWorld.class

  s = signature was verified 
  m = entry is listed in manifest
  k = at least one certificate was found in keystore
  ? = unsigned entry

- Signed by "[REMOVED - DN OF INTERMEDIATE CA]"
    Digest algorithm: SHA256
    Signature algorithm: SHA256withRSA, 4096-bit key
```
This is bad. It has attempted to sign with the intermediate CA and not the leaf.

Extracting the signed jar and running at META-INF/SSMULTI.RSA file through openssl:

```
[removed]@[removed] AzureKeyVault % openssl pkcs7 -in extracted/META-INF/SSMULTI.RSA -inform DER -print | grep subject: -A6
          subject: [REMOVED - DN OF SIGNING CERT]
          key:           X509_PUBKEY: 
            algor: 
              algorithm: rsaEncryption (1.2.840.113549.1.1.1)
              parameter: NULL
            public_key:  (0 unused bits)
              0000 - 30 82 01 8a 02 82 01 81-00 99 b0 01 de 9d   0.............
--
          subject: [REMOVED - DN IF INTERMEDIATE CA]
          key:           X509_PUBKEY: 
            algor: 
              algorithm: rsaEncryption (1.2.840.113549.1.1.1)
              parameter: NULL
            public_key:  (0 unused bits)
              0000 - 30 82 02 0a 02 82 02 01-00 97 bc 2f d6 63   0........../.c
--
          subject: [REMOVED - DN OF ROOT CA]
          key:           X509_PUBKEY: 
            algor: 
              algorithm: rsaEncryption (1.2.840.113549.1.1.1)
              parameter: NULL
            public_key:  (0 unused bits)
              0000 - 30 82 02 0a 02 82 02 01-00 e9 3d 47 f7 b1   0.........=G..
```

Its all in the same order...

The issue seems to be: the signing operation is picking the wrong certificate when it is a HSM backed key.

**Comment by moarychan** [comment] 2024-11-08 02:46
> > [@3millionminds](https://github.com/3millionminds) did this work for you?
> 
> Hello,
> 
> Unfortunately we have been unable to test. We are unable to merge new certificates on top of the ones we already have in Azure Key Vault.
> 
> We have opened a MS ticket to see what options we have here.

@3millionminds  is your problem solved?

Once a certificate operation is completed, you cannot merge another certificate (exported by DigiCert). If you need to merge again, please re-create the certificate in Key Vault, re-apply on DigiCert and then merge.

**Comment by moarychan** [comment] 2024-11-08 05:03
Hi @dacron ,  thanks for your update!

> If you use a key of type RSA-HSM and a DigiCert signed certificate it does not work. It doesn't work if I self sign a RSA-HSM backed cert either via the previously mentioned openssl-based CA. The verify of the DigiCert RSA-HSM cert shows:
> 

I cannot generate a certificate with key type RSA-HSM on Azure Portal,
![Image](https://github.com/user-attachments/assets/a4081386-71af-433e-8e04-b6241a38e5af)

For a premium Key Vault, it supports to generate a key with key type RSA-HSM,

![Image](https://github.com/user-attachments/assets/4048272a-6776-4c85-861a-593ce86403c2)

but how to generate a certificate using an existing key (RSA-HSM type)?  Could you help provider more detail steps to create a cert chain with key type RSA-HSM on Azure Key Vault? This will be very helpful to verify this scenario.

**Comment by dacron** [comment] 2024-11-08 09:35
We are using Premium Key Vault Vault:

![Image](https://github.com/user-attachments/assets/92d3c68c-5268-46fe-9b1b-dac69903d770)

We then send the resulting CSR over the DigiCert and merge the signed certificate back.

**Comment by moarychan** [comment] 2024-11-11 02:02
Strange, I am using premium Key Vault, but I cannot see the Key Type with RSA-HSM when generating certificate.

![Image](https://github.com/user-attachments/assets/d43dcfff-4a7a-4754-93b3-82789032e3fe)

![Image](https://github.com/user-attachments/assets/4b740895-456e-436f-bdc7-426ff98f109f)

Did you do any other settings?

**Comment by saragluna** [comment] 2024-11-11 02:25
@moarychan I can help you with this

**Comment by moarychan** [comment] 2024-11-13 05:16
Hi @dacron, thanks for your update!

I can use the private key type RSA-HSM and key size 3072 to generate a cert and signed with DiGiCert, it works well, could you follow below steps to retry?

1. Select key type RSA-HSM (when select No for exportable private key the RSA-HSM is avaiable) and key size 3072 to generate a cert in Azure portal, then select `Create`.
    ![Image](https://github.com/user-attachments/assets/93d54739-c8e4-4822-97da-b3ceb765877e)


2. Download CSR file.
    ![Image](https://github.com/user-attachments/assets/6c2e1219-dc03-4ad3-be80-71fe934449ab)

3. Sign on DiGiCert and download the single file containing all the certs.
    ![Image](https://github.com/user-attachments/assets/9f4b6dc9-f9ae-4332-afb5-06858e747a7f)

4. Manuualy reorder the certs
    View the cert file
    ![Image](https://github.com/user-attachments/assets/358a11bf-d9c1-4e40-bf7f-a550026f1a7c)

    Reorder, ROOT => INTERMEDIATE => LEAF
    ![Image](https://github.com/user-attachments/assets/a8855915-3827-4c4f-aef9-0231cfea5194)

5. Merge the signed cert
    ![Image](https://github.com/user-attachments/assets/e75f3072-27a5-452b-af6b-63b3ecedcfa8)

6. Sign jar
    
    ```shell
    jarsigner \
    -keystore NONE \
    -storetype AzureKeyVault \
    -signedjar signerjar.jar unsigned.jar rsa-hsm-3072-reorder-certs \
    -verbose  \
    -storepass "" \
    -providerName AzureKeyVault \
    -providerClass com.azure.security.keyvault.jca.KeyVaultJcaProvider \
	-debug \
    -J--module-path="/xxx/com/azure/azure-security-keyvault-jca/2.10.0-beta.1/azure-security-keyvault-jca-2.10.0-beta.1.jar" \
    -J--add-modules="com.azure.security.keyvault.jca" \
    -J-Dazure.keyvault.uri=https://xxxkeyvaulthsm.vault.azure.net/ \
    -J-Dazure.keyvault.tenant-id=xxx \
    -J-Dazure.keyvault.client-id=xxx \
    -J-Dazure.keyvault.client-secret=xxx \
    -J-Djava.security.debug=jar
    ```
   ![Image](https://github.com/user-attachments/assets/8936bc73-92a5-46b4-86dc-73fd36dd6f2c)

 7. Verify jar
     ```shell
     jarsigner -verify -verbose -J-Djava.security.debug=jar -certs signerjar.jar
     ```

     ![Image](https://github.com/user-attachments/assets/3eb45a64-3064-4ec5-ba10-5c7b53848344)

**Comment by rujche** [comment] 2024-11-19 01:21
Hi, @dacron 
By saying `beta release of 2.10`, do you mean `beta version of 2.10 packaged by yourself`? 

I can't see `2.10` it in maven repository:
https://repo1.maven.org/maven2/com/azure/azure-security-keyvault-jca/
> ![Image](https://github.com/user-attachments/assets/7b3c5bd1-ba59-4472-b7e2-6ef304a46f8b)

Now I plan to release ` 2.9.1` with this bug fixed. Current plan is to release `2.9.1` around the end of this month.

**Comment by dacron** [comment] 2024-11-19 09:26
Yes - I built 2.10.0 beta 1 from source. Getting 2.9.1 out of the door would be much appreciated.

**Comment by dacron** [comment] 2024-11-19 10:28
@rujche are you able to let me know which commit fixes the bug?

**Comment by tanzim** [comment] 2024-11-20 10:49
> [@dacron](https://github.com/dacron) This one: [#42522](https://github.com/Azure/azure-sdk-for-java/pull/42522)

Is that the correct PR? It doesn't make a lot of sense on surface at least, unless there's key vaults on MSFT side with certificates in name?

**Comment by rujche** [comment] 2024-11-21 01:45
@dacron 
Sorry, my mistake. It should be this one: https://github.com/Azure/azure-sdk-for-java/pull/41303

**Comment by tanzim** [comment] 2024-11-21 09:32
> [@dacron](https://github.com/dacron) Sorry, my mistake. It should be this one: [#41303](https://github.com/Azure/azure-sdk-for-java/pull/41303)

This implies 2.9 beta 2 should have the change?

**Comment by rujche** [comment] 2024-11-22 05:54
@dacron 
Our plan updated. Here is the new plan: 
1. Release 2.10.0 around the end of this month. 
2. No patch release (2.9.1).

**Comment by moarychan** [comment] 2024-11-28 06:23
JCA 2.10.0 is available on Maven Central, please try it! Thanks!

**Closed by moarychan** 2024-11-28 06:23 UTC
Labels: bug, customer-reported, needs-team-attention, azure-spring-jca

**Comment by DavidM29** [comment] 2024-12-26 09:29
I am getting this error when trying to sign an apk file using JCA 2.10.0.

**Comment by saragluna** [comment] 2024-12-27 02:01
@DavidM29 could you help provide more information, or anything can help us reproduce the issue?
