### ISSUE TITLE
[FEATURE REQ]Support Spring reactive stack for Key Vault Secrets starter

### ISSUE THREAD

**Issue by gpa168** [Azure/azure-sdk-for-java#18270] opened 2020-12-18 17:28 UTC
**Describe the bug**
We have Spring Boot Reactive WebFlux application accessing Azure Key vault. When the application starts, spring boot makes two parallel calls to Azure key vault api to download the secrets. One of the call passes and other one always fails with 401 Unauthorized exception. Note that these two calls are made in two separate threads. 

***Exception or Stack Trace***
kvazewpreprod.vault.azure.net
Duration:20 ms Response code:401 Dependency name:GET /secrets/businesrulespostgresdbhost/

**To Reproduce**
Start the Spring Boot reactive application with azure key vault dependency in pom and key vault config in the applicaiton.yml file.

***Code Snippet***
Maven dependencies - pom.xml:
```
<dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>azure-keyvault-secrets-spring-boot-starter</artifactId>
      <version>2.3.3</version>
 </dependency>
<dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-webflux</artifactId>
       <version>2.3.1.RELEASE</version>
</dependency>
```

Application properties - application.yml:

```
azure:
  keyvault:
    enabled: true
    uri: https://kvazewpreprod.vault.azure.net/
    tenant-id: xxxx-xxx-xxxxx-xxx-xxxxxxx
```

WebApp access to Azure key vault is handled through managed identity. There fore clientId and Secret key is not passed from application.yml config.

**Expected behavior**
There should be only one call to download each secret from Azure key vault. The additional failing call to Azure key vault is causing issue with actual spring reactive api.

**Screenshots**
Spring Boot logs showing two request being sent with two separate threads
![image](https://user-images.githubusercontent.com/71377704/102640970-986c5d00-415b-11eb-9d9a-6124444b9aed.png)

Logs showing one of the request was success with 200 status code and other one failed with 401 status code
![image](https://user-images.githubusercontent.com/71377704/102640720-37448980-415b-11eb-8c3a-9688ddac8017.png)

**Setup (please complete the following information):**
This issue is occurring after deployment of spring boot reactive application on Azure WebApp.

**Additional context**
It looks like the Azure key vault maven dependency currently does not support spring reactive application. Could you please help me with the Azure key vault - Spring Boot reactive supported dependency to fix this issue. Thanks

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by fatimamookhtiarmaersk** [comment] 2020-12-18 22:36
Could someone please help here and clarify whether the web flux version is supported.

**Comment by joshfree** [comment] 2021-01-05 18:26
Thanks for filing this question on github @fatimamookhtiarmaersk.  @jialindai could you please help route this `azure-spring` question?

**Comment by fatimamookhtiarmaersk** [comment] 2021-01-07 20:35
Any update guys? This is causing us plenty of issues in PROD.

**Comment by chenrujun** [comment] 2021-01-11 01:25
Hi, @gpa168 , @fatimamookhtiarmaersk .

Sorry that currently `azure-keyvault-secrets-spring-boot-starter` does not support `webflux` yet.

**Comment by fatimamookhtiarmaersk** [comment] 2021-01-11 01:33
Any alternatives you could recommend please?

**Comment by chenrujun** [comment] 2021-01-11 02:24
@fatimamookhtiarmaersk , please use `spring-boot-starter-web` instead of `spring-boot-starter-webflux`.

**Comment by gpa168** [comment] 2021-01-11 14:25
@chenrujun - by changing from **spring-boot-starter-webflux** to **spring-boot-starter-web** are you suggesting to covert Reactive api's to non reactive api's! That's not possible as it will be big change in how api's have been designed.
We have tried below two dependencies but we are getting the same 401 error. Could you suggest other dependency which support spring-webflux. 

```
<dependency>
	<groupId>com.microsoft.azure</groupId>
	<artifactId>azure-spring-boot-starter</artifactId>
</dependency>
<dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>azure-keyvault-secrets-spring-boot-starter</artifactId>
</dependency>
```

We are seeing another issue with multiple threads causing Web App to go down. The availability drops from 100% to below 25% and eventually we notice the Web app instance freezing. The only thing which seems to resolve the issue is by doing a hard restart of the Web app which make me wonder if these two issues are related as WebFlux is not supported yet? The support ticket number for the second issue which may be related is 121010725001583.
Appreciate a prompt response as we have live issue in production impacting this issue.

**Comment by chenrujun** [comment] 2021-01-14 06:36
Hi, @gpa168 .

Sorry for late response.

# My sample project

I created a branch to reproduce your problem:
 - Branch: https://github.com/chenrujun/azure-sdk-for-java/tree/issue-18270-investigation
 - Commit used in current comment: https://github.com/chenrujun/azure-sdk-for-java/tree/9625c3b92205fcb26d079bdf232df8ad19ee5bf5
 - Folder: https://github.com/chenrujun/azure-sdk-for-java/tree/9625c3b92205fcb26d079bdf232df8ad19ee5bf5/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-keyvault-secrets

Here is the execution log:

![image](https://user-images.githubusercontent.com/13167207/104552438-ccac3e00-5673-11eb-9629-48caa30d4ed5.png)

# Your concerns

### You mentioned that
```
Note that these two calls are made in two separate threads.
```
In my understanding, it's not a problem. it's expected behavior.
In you screenshot:

![image](https://user-images.githubusercontent.com/13167207/104552662-2d3b7b00-5674-11eb-9748-a8f668796911.png)

2 thread is also expected behavior.
And `Retrieved secret - businesrulespostgresdbhost` means get the secret successfully, I think.

### And you mentioned that
```
Logs showing one of the request was success with 200 status code and other one failed with 401 status code
```
![image](https://user-images.githubusercontent.com/13167207/104552925-ab981d00-5674-11eb-9f70-247db7314e66.png)
I don't know how to get the log.


# My request

 - Please tell me where did you get the log about 401?
 - Please try to use my sample to reproduce your problem: https://github.com/chenrujun/azure-sdk-for-java/tree/9625c3b92205fcb26d079bdf232df8ad19ee5bf5/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-keyvault-secrets

**Comment by gpa168** [comment] 2021-03-02 15:41
This issue still exist. One of the calls to Azure key vault fails with 401 status code and other one passes with 200 status code. Ideally both requests should have been success with 200 status code.

**Comment by chenrujun** [comment] 2021-03-03 00:05
Hi, @gpa168 , could you please check [my last comment](https://github.com/Azure/azure-sdk-for-java/issues/18270#issuecomment-759960024)?

**Comment by tjuchniewicz** [comment] 2021-05-05 10:54
We have the same issue for Spring Webmvc. Every 30 minutes we have two calls. First always fails with 401 and second one that is 200.

**Comment by fatimamookhtiarmaersk** [comment] 2021-05-05 10:59
We ended up ignoring the failed call, as after lots of attempts with MS support engineers couldn't solve the problem or identify the root cause. I believe the reactive version doesn't gel too well.

**Comment by gpa168** [comment] 2021-05-06 08:34
We have moved away from using azure-keyvault-secrets-spring-boot-starter as it does not support spring boot web flux.

**Comment by chenrujun** [comment] 2021-05-11 00:30
@gpa168 Sorry for bring you trouble. Now fully supporting web flux is in our roadmap. (cc: @stliu , @seanli1988 , FYI.)

**Comment by stliu** [comment] 2021-05-11 02:51
@chenrujun do we have an issue opened for supporting webflux in all our libs?

**Comment by chenrujun** [comment] 2021-05-11 03:07
@stliu 
I created a issue just now: https://github.com/Azure/azure-sdk-for-java/issues/21290
We can create sub issue when we start to support webflux.

**Comment by chenrujun** [comment] 2021-08-20 02:02
Closing this issue, use this issue instead: https://github.com/Azure/azure-sdk-for-java/issues/21581

**Comment by shweta5595** [comment] 2022-08-16 08:31
Hi , which dependency for reading secrets from key-vault is supported with spring-webflux.

**Comment by stliu** [comment] 2022-08-16 09:09
@shweta5595 Hi I just tried and it works fine with the  latest Spring Cloud Azure KeyVault support, could you try [this setup](https://start.spring.io/#!type=maven-project&language=java&platformVersion=2.7.2&packaging=jar&jvmVersion=1.8&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=azure-keyvault,webflux,actuator)

**Comment by shweta5595** [comment] 2022-08-17 06:35
hi @stliu , This setup worked for me . Thanks
Although I do not see logs like Retrieving Secret and Retrieved Secret on application startup. Neither a connection logs to azure-key vault. Can we enable this somehow ?

**Comment by chenrujun** [comment] 2022-08-18 02:54
Hi, @shweta5595 

> Although I do not see logs like Retrieving Secret and Retrieved Secret on application startup. Neither a connection logs to azure-key vault. Can we enable this somehow ?

Log like `Retrieving secret` and `Retrieved secret` appears in [SecretAsyncClient](https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure-autoconfigure_4.3.0/sdk/keyvault/azure-security-keyvault-secrets/src/main/java/com/azure/security/keyvault/secrets/SecretAsyncClient.java#L346-L347). You can use the following property to enable debug log:

```yml
logging:
  level:
    com.azure.security.keyvault.secrets.SecretAsyncClient: DEBUG
```

But when `SecretAsyncClient` is called in [KeyVaultEnvironmentPostProcessor](https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure-autoconfigure_4.3.0/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/keyvault/environment/KeyVaultEnvironmentPostProcessor.java) the log cannot be outputted. It's a known issue. Refer [this question](https://stackoverflow.com/questions/42839798/how-to-log-errors-in-a-environmentpostprocessor-execution) to get more information: 

We already used `DeferredLog`, but `DeferredLog ` can not be passed into `SecretAsyncClient`. So `SecretAsyncClient`'s log can't be outputted when `SecretAsyncClient` is called in `KeyVaultEnvironmentPostProcessor`.

If you set this:
```
spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-source-enabled: true
          property-sources:
            - name: key-vault-property-source-1
              endpoint: https://xxx.vault.azure.net/
              refresh-interval: 5s
```

Then logs like `Retrieving secret` and `Retrieved secret` will appeared every 5 seconds. Because SecretAsyncClient is not called in `KeyVaultEnvironmentPostProcessor` anymore, it's called in another thread.

Here is the log in my localhost:

```log
2022-08-18 10:40:57.804 DEBUG 12744 --- [        Timer-0] c.a.s.k.secrets.SecretAsyncClient        : Listing secrets
2022-08-18 10:40:58.129 DEBUG 12744 --- [ctor-http-nio-1] c.a.s.k.secrets.SecretAsyncClient        : Listed secrets
2022-08-18 10:40:58.129 DEBUG 12744 --- [        Timer-0] c.a.s.k.secrets.SecretAsyncClient        : Retrieving secret - sampleProperty1
2022-08-18 10:40:58.433 DEBUG 12744 --- [ctor-http-nio-1] c.a.s.k.secrets.SecretAsyncClient        : Retrieved secret - sampleProperty1
2022-08-18 10:40:58.433 DEBUG 12744 --- [        Timer-0] c.a.s.k.secrets.SecretAsyncClient        : Retrieving secret - sampleProperty2
2022-08-18 10:40:58.748 DEBUG 12744 --- [ctor-http-nio-1] c.a.s.k.secrets.SecretAsyncClient        : Retrieved secret - sampleProperty2
2022-08-18 10:40:58.748 DEBUG 12744 --- [        Timer-0] c.a.s.k.secrets.SecretAsyncClient        : Retrieving secret - samplePropertyInMultipleKeyVault
2022-08-18 10:40:59.064 DEBUG 12744 --- [ctor-http-nio-1] c.a.s.k.secrets.SecretAsyncClient        : Retrieved secret - samplePropertyInMultipleKeyVault
2022-08-18 10:41:02.801 DEBUG 12744 --- [        Timer-0] c.a.s.k.secrets.SecretAsyncClient        : Listing secrets
2022-08-18 10:41:03.142 DEBUG 12744 --- [ctor-http-nio-1] c.a.s.k.secrets.SecretAsyncClient        : Listed secrets
2022-08-18 10:41:03.142 DEBUG 12744 --- [        Timer-0] c.a.s.k.secrets.SecretAsyncClient        : Retrieving secret - sampleProperty1
2022-08-18 10:41:03.442 DEBUG 12744 --- [ctor-http-nio-1] c.a.s.k.secrets.SecretAsyncClient        : Retrieved secret - sampleProperty1
2022-08-18 10:41:03.442 DEBUG 12744 --- [        Timer-0] c.a.s.k.secrets.SecretAsyncClient        : Retrieving secret - sampleProperty2
2022-08-18 10:41:03.757 DEBUG 12744 --- [ctor-http-nio-1] c.a.s.k.secrets.SecretAsyncClient        : Retrieved secret - sampleProperty2
2022-08-18 10:41:03.757 DEBUG 12744 --- [        Timer-0] c.a.s.k.secrets.SecretAsyncClient        : Retrieving secret - samplePropertyInMultipleKeyVault
2022-08-18 10:41:04.074 DEBUG 12744 --- [ctor-http-nio-1] c.a.s.k.secrets.SecretAsyncClient        : Retrieved secret - samplePropertyInMultipleKeyVault
2022-08-18 10:41:07.802 DEBUG 12744 --- [        Timer-0] c.a.s.k.secrets.SecretAsyncClient        : Listing secrets
2022-08-18 10:41:08.148 DEBUG 12744 --- [ctor-http-nio-1] c.a.s.k.secrets.SecretAsyncClient        : Listed secrets
2022-08-18 10:41:08.148 DEBUG 12744 --- [        Timer-0] c.a.s.k.secrets.SecretAsyncClient        : Retrieving secret - sampleProperty1
2022-08-18 10:41:08.453 DEBUG 12744 --- [ctor-http-nio-1] c.a.s.k.secrets.SecretAsyncClient        : Retrieved secret - sampleProperty1
2022-08-18 10:41:08.453 DEBUG 12744 --- [        Timer-0] c.a.s.k.secrets.SecretAsyncClient        : Retrieving secret - sampleProperty2
2022-08-18 10:41:08.766 DEBUG 12744 --- [ctor-http-nio-1] c.a.s.k.secrets.SecretAsyncClient        : Retrieved secret - sampleProperty2
2022-08-18 10:41:08.766 DEBUG 12744 --- [        Timer-0] c.a.s.k.secrets.SecretAsyncClient        : Retrieving secret - samplePropertyInMultipleKeyVault
2022-08-18 10:41:09.065 DEBUG 12744 --- [ctor-http-nio-1] c.a.s.k.secrets.SecretAsyncClient        : Retrieved secret - samplePropertyInMultipleKeyVault
2022-08-18 10:41:12.811 DEBUG 12744 --- [        Timer-0] c.a.s.k.secrets.SecretAsyncClient        : Listing secrets
2022-08-18 10:41:13.158 DEBUG 12744 --- [ctor-http-nio-1] c.a.s.k.secrets.SecretAsyncClient        : Listed secrets
2022-08-18 10:41:13.158 DEBUG 12744 --- [        Timer-0] c.a.s.k.secrets.SecretAsyncClient        : Retrieving secret - sampleProperty1
2022-08-18 10:41:13.525 DEBUG 12744 --- [ctor-http-nio-1] c.a.s.k.secrets.SecretAsyncClient        : Retrieved secret - sampleProperty1
2022-08-18 10:41:13.527 DEBUG 12744 --- [        Timer-0] c.a.s.k.secrets.SecretAsyncClient        : Retrieving secret - sampleProperty2
2022-08-18 10:41:13.828 DEBUG 12744 --- [ctor-http-nio-1] c.a.s.k.secrets.SecretAsyncClient        : Retrieved secret - sampleProperty2
2022-08-18 10:41:13.844 DEBUG 12744 --- [        Timer-0] c.a.s.k.secrets.SecretAsyncClient        : Retrieving secret - samplePropertyInMultipleKeyVault
2022-08-18 10:41:14.158 DEBUG 12744 --- [ctor-http-nio-1] c.a.s.k.secrets.SecretAsyncClient        : Retrieved secret - samplePropertyInMultipleKeyVault
2022-08-18 10:41:17.806 DEBUG 12744 --- [        Timer-0] c.a.s.k.secrets.SecretAsyncClient        : Listing secrets
2022-08-18 10:41:18.136 DEBUG 12744 --- [ctor-http-nio-1] c.a.s.k.secrets.SecretAsyncClient        : Listed secrets
2022-08-18 10:41:18.136 DEBUG 12744 --- [        Timer-0] c.a.s.k.secrets.SecretAsyncClient        : Retrieving secret - sampleProperty1
2022-08-18 10:41:18.450 DEBUG 12744 --- [ctor-http-nio-1] c.a.s.k.secrets.SecretAsyncClient        : Retrieved secret - sampleProperty1
2022-08-18 10:41:18.450 DEBUG 12744 --- [        Timer-0] c.a.s.k.secrets.SecretAsyncClient        : Retrieving secret - sampleProperty2
2022-08-18 10:41:18.761 DEBUG 12744 --- [ctor-http-nio-1] c.a.s.k.secrets.SecretAsyncClient        : Retrieved secret - sampleProperty2
2022-08-18 10:41:18.761 DEBUG 12744 --- [        Timer-0] c.a.s.k.secrets.SecretAsyncClient        : Retrieving secret - samplePropertyInMultipleKeyVault
2022-08-18 10:41:19.060 DEBUG 12744 --- [ctor-http-nio-1] c.a.s.k.secrets.SecretAsyncClient        : Retrieved secret - samplePropertyInMultipleKeyVault
```

**Comment by shweta5595** [comment] 2022-08-18 03:19
Hi @chenrujun , Thankyou so much !!

**Comment by shweta5595** [comment] 2022-08-22 07:24
hi @chenrujun  , Awaiting your reply to the previous comment.

**Comment by chenrujun** [comment] 2022-08-22 07:29
Hi, @shweta5595 

1. Not get all secrets:
```
spring.cloud.azure.keyvault.secret.property-sources[0].secret-keys=sample-key-1
```
Refs: https://microsoft.github.io/spring-cloud-azure/4.3.0/reference/html/index.html#not-retrieve-all-secrets-in-key-vault


2. Disable auto refresh:
```
spring.cloud.azure.keyvault.secret.property-sources[0].refresh-interval=0
```
Refs: https://microsoft.github.io/spring-cloud-azure/4.3.0/reference/html/index.html#setting-refresh-interval

**Comment by andros0689** [comment] 2022-11-24 05:26
Hi @chenrujun , how are you?

Please, see that I am using this configuration in my application.properties with the "com.azure.spring/spring-cloud-azure-starter-keyvault-secrets/4.4.1" implementation, Fuse 7.11.0.fuse-sb2-7_11_0-00028-redhat-00001, SpringBoot v2.5.13 and Java 11:

`spring.cloud.azure.keyvault.secret.property-source-enabled=true`
`spring.cloud.azure.keyvault.secret.property-sources[0].secret-keys=somesecret1,somsecret2`
`spring.cloud.azure.keyvault.secret.property-sources[0].credential.client-id=********`
`spring.cloud.azure.keyvault.secret.property-sources[0].credential.client-secret=********`
`spring.cloud.azure.keyvault.secret.property-sources[0].profile.tenant-id=********`
`spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=********`
`spring.cloud.azure.keyvault.secret.property-sources[0].case-sensitive=false`
`spring.cloud.azure.keyvault.secret.property-sources[0].refresh-interval=5s`

I can get the secrets without problem but I can't see the "Retrieving Secret and Retrieved Secret" log. Neither at the start of the application nor during its execution. COuld you please help me to find what's wrong in my configuration?

This is my app log:

> [INFO] Scanning for projects...
[INFO] 
[INFO] ----------------< wk-updateinopsseats >-----------------
[INFO] Building :: Integrations :: Spring-Boot :: Camel QUARTZ / SQL 1.0.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] >>> spring-boot-maven-plugin:7.11.0.fuse-sb2-7_11_0-00028-redhat-00001:run (default-cli) > test-compile @ wk-updateinopsseats >>>
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.2:prepare-agent (default) @ wk-updateinopsseats ---
[INFO] argLine set to -javaagent:/home/dzapata/.m2/repository/org/jacoco/org.jacoco.agent/0.8.2/org.jacoco.agent-0.8.2-runtime.jar=destfile=/home/dzapata/Proyectos/repositorios/lops/Eupdateflights/target/jacoco.exec
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ wk-updateinopsseats ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 7 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ wk-updateinopsseats ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ wk-updateinopsseats ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 6 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ wk-updateinopsseats ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] <<< spring-boot-maven-plugin:7.11.0.fuse-sb2-7_11_0-00028-redhat-00001:run (default-cli) < test-compile @ wk-updateinopsseats <<<
[INFO] 
[INFO] 
[INFO] --- spring-boot-maven-plugin:7.11.0.fuse-sb2-7_11_0-00028-redhat-00001:run (default-cli) @ wk-inopsseats
[INFO] Attaching agents: []
#logback.classic pattern: %d [%-15.15t] %-5p %-10.10c{1} - %-10.10X{camel.exchangeId} - %-20.20X{camel.routeId} - %m%n
#logback.classic pattern: %d [%-15.15t] %-5p %-10.10c{1} - %-10.10X{camel.exchangeId} - %-20.20X{camel.routeId} - %m%n
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::               (v2.5.13)
2022-11-24 00:04:47,034 [kground-preinit] INFO  .u.Version -            -                      - HV000001: Hibernate Validator 6.0.23.Final-redhat-00001
2022-11-24 00:04:47,050 [main           ] INFO  pplication -            -                      - Starting Application using Java 11.0.11 on andros with PID 319140 (/home/dzapata/Proyectos/repos...
2022-11-24 00:04:47,051 [main           ] INFO  pplication -            -                      - No active profile set, falling back to 1 default profile: "default"
2022-11-24 00:04:47,729 [main           ] WARN  perScanner -            -                      - No MyBatis mapper was found in '[com.avianca.esb.wkupdateinopsseats]' package. Please check your configuration.
2022-11-24 00:04:48,035 [main           ] INFO  sorChecker -            -                      - Bean 'org.apache.camel.spring.boot.CamelAutoConfiguration' of type [org.apache.camel.spring.boot.CamelAutoConfiguration$$EnhancerBySpringCGLIB$$ecb96c1f] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-11-24 00:04:48,211 [main           ] INFO  tWebServer -            -                      - Tomcat initialized with port(s): 8080 (http)
2022-11-24 00:04:48,218 [main           ] INFO  ioProtocol -            -                      - Initializing ProtocolHandler ["http-nio-0.0.0.0-8080"]
2022-11-24 00:04:48,219 [main           ] INFO  ardService -            -                      - Starting service [Tomcat]
2022-11-24 00:04:48,219 [main           ] INFO  dardEngine -            -                      - Starting Servlet engine: [Apache Tomcat/9.0.59]
2022-11-24 00:04:48,299 [main           ] INFO  .C.[.[.[/] -            -                      - Initializing Spring embedded WebApplicationContext
2022-11-24 00:04:48,299 [main           ] INFO  ionContext -            -                      - Root WebApplicationContext: initialization completed in 1223 ms
2022-11-24 00:04:48,638 [main           ] INFO  eConverter -            -                      - Type converters loaded (core: 195, classpath: 1)
2022-11-24 00:04:48,907 [main           ] INFO  derFactory -            -                      - Will configure the default credential of type DefaultAzureCredential for class com.azure.identity.DefaultAzureCredentialBuilder.
2022-11-24 00:04:49,247 [main           ] INFO  ioProtocol -            -                      - Starting ProtocolHandler ["http-nio-0.0.0.0-8080"]
2022-11-24 00:04:49,258 [main           ] INFO  tWebServer -            -                      - Tomcat started on port(s): 8080 (http) with context path ''
2022-11-24 00:04:49,279 [main           ] INFO  sCollector -            -                      - Loading additional Camel XML routes from: classpath:camel/*.xml
2022-11-24 00:04:49,280 [main           ] INFO  sCollector -            -                      - Loading additional Camel XML rests from: classpath:camel-rest/*.xml
2022-11-24 00:04:49,288 [main           ] INFO  melContext -            -                      - Apache Camel 2.23.2.fuse-7_11_0-00037-redhat-00001 (CamelContext: camel-1) is starting
2022-11-24 00:04:49,288 [main           ] INFO  melContext -            -                      - StreamCaching is enabled on CamelContext: camel-1
2022-11-24 00:04:49,288 [main           ] INFO  melContext -            -                      - MDC logging is enabled on CamelContext: camel-1
2022-11-24 00:04:49,289 [main           ] INFO  ntStrategy -            -                      - JMX is enabled
2022-11-24 00:04:49,437 [main           ] INFO  zComponent -            -                      - Setting org.quartz.scheduler.jmx.export=true to ensure QuartzScheduler(s) will be enlisted in JMX.
2022-11-24 00:04:49,437 [main           ] INFO  zComponent -            -                      - Create and initializing scheduler.
2022-11-24 00:04:49,450 [main           ] INFO  lerFactory -            -                      - Using default implementation for ThreadExecutor
2022-11-24 00:04:49,451 [main           ] INFO  ThreadPool -            -                      - Job execution threads will use class loader of thread: main
2022-11-24 00:04:49,457 [main           ] INFO  gnalerImpl -            -                      - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2022-11-24 00:04:49,457 [main           ] INFO  zScheduler -            -                      - Quartz Scheduler v.2.3.2 created.
2022-11-24 00:04:49,457 [main           ] INFO  AMJobStore -            -                      - RAMJobStore initialized.
2022-11-24 00:04:49,461 [main           ] INFO  zScheduler -            -                      - Scheduler meta-data: Quartz Scheduler (v2.3.2) 'DefaultQuartzScheduler-camel-1' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.
2022-11-24 00:04:49,461 [main           ] INFO  lerFactory -            -                      - Quartz scheduler 'DefaultQuartzScheduler-camel-1' initialized from an externally provided properties instance.
2022-11-24 00:04:49,461 [main           ] INFO  lerFactory -            -                      - Quartz scheduler version: 2.3.2
2022-11-24 00:04:49,494 [main           ] INFO  ngStrategy -            -                      - StreamCaching in use with spool directory: /tmp/camel/camel-tmp-e8c84a17-7b95-4f11-a01f-7a6cf37f46c7 and rules: [Spool > 128K body size]
2022-11-24 00:04:49,550 [main           ] INFO  tzEndpoint -            -                      - Job Camel_camel-1.quartzInops (triggerType=CronTriggerImpl, jobClass=CamelJob) is scheduled. Next fire date is Thu Nov 24 23:40:00 COT 2022
2022-11-24 00:04:49,577 [main           ] INFO  zComponent -            -                      - Starting scheduler.
2022-11-24 00:04:49,577 [main           ] INFO  zScheduler -            -                      - Scheduler DefaultQuartzScheduler-camel-1_$_NON_CLUSTERED started.
2022-11-24 00:04:49,579 [main           ] INFO  melContext -            -                      - Route: wkinopsseats_consultarworkordersabiertas started and consuming from: direct://consultarWorkOrdersAbiertas
2022-11-24 00:04:49,580 [main           ] INFO  melContext -            -                      - Route: insertarworkordersabiertas started and consuming from: direct://insertarWorkOrdersAbiertas
2022-11-24 00:04:49,580 [main           ] INFO  melContext -            -                      - Route: wkinopsseats_quartz2_consumer started and consuming from: quartz2://quartzInops?cron=0+40+23+1%2F1+*+%3F+*
2022-11-24 00:04:49,581 [main           ] INFO  melContext -            -                      - Route: wkinopsseats_process started and consuming from: direct://procesarRegistros
2022-11-24 00:04:49,581 [main           ] INFO  melContext -            -                      - Total 4 routes, of which 4 are started
2022-11-24 00:04:49,582 [main           ] INFO  melContext -            -                      - Apache Camel 2.23.2.fuse-7_11_0-00037-redhat-00001 (CamelContext: camel-1) started in 0.293 seconds
2022-11-24 00:04:49,585 [main           ] INFO  pplication -            -                      - Started Application in 5.312 seconds (JVM running for 5.845)

**Comment by chenrujun** [comment] 2022-11-24 05:34
Hi, @andros0689 .
Thanks for reaching out.

1. To see the logs like `Retrieving secret -`, please try this way: adding the following properties in your `application.yml` file:

```yml
logging:
  level:
    com.azure.security.keyvault.secrets.SecretAsyncClient: DEBUG
```

2. BYW, the problem you described is not related to current issue. Next time, please create a new issue for similar requirement.

**Closed** 2024-03-18 18:05 UTC
Labels: Client, customer-reported, feature-request, needs-team-attention, azure-spring, azure-spring-keyvault
