### ISSUE TITLE
[BUG]Possible memory leak in Azure Tables client library for Java

### ISSUE THREAD

**Issue by saajanjha** [Azure/azure-sdk-for-java#29481] opened 2022-06-15 09:47 UTC
**Describe the bug**
Hi team, for one of our application we're using azure table storage and [azure tables client library](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/tables/azure-data-tables/README.md) for performing operations on the same. We have an API fetching a list of records from table storage, the total number of records on average would be around 400. Now, on average through out weekdays, the API is called for around 5k times and what we have noticed is steady increase in the memory usage such that it reaches close to 100% and restarts and again goes till 100% and restarts, the cycle continues for 2-3 times until users stop using it at EOD.

After running into this incident we did an investigation and tested each component separately and have found out issue with the aforementioned API, specifically the method call to fetch the table entities from table storage.

***Exception or Stack Trace***
We don't see any exception regarding this, since the application instance forces itself to restart the moment memory usage percentage is close to 100%.

**To Reproduce**
To reproduce you can have around 100 records in your table storage and start making continuous call to fetch the same from around 50 users for 2-3 hrs. You will start noticing increase in memory usage.

We're using `tableClient.listEntities().streamByPage()`, you can also do it without `streamByPage()` and still notice increase in memory usage

***Code Snippet***
As mentioned above we've tried two approaches
```
tableEntities.streamByPage()
        .flatMap(resp ->
            resp.getElements().stream()
                .map(this::someMappingMethod)
        ).collect(Collectors.toList());
```
and

```
for (TableEntity entity : tableClient.listEntities(options, null, null)) {
    Map<String, Object> properties = entity.getProperties();
   //some mapping logic
}
```
**Expected behavior**
Stable memory usage

**Screenshots**

Memory usage on one instance

![memory-1](https://user-images.githubusercontent.com/107533688/173766937-57154829-87c6-42c8-8a6f-30044a11ff20.png)

We increased the instance to two then,

![memory-2](https://user-images.githubusercontent.com/107533688/173767346-72566b0e-4e27-4e8e-867e-ca6f65e1fb0a.png)
'
To stabilize our application we've four instances now due to which the frequency of restart is less but yet there is steady increase in memory with comparatively less restarts.

![memory-3](https://user-images.githubusercontent.com/107533688/173767793-c4844f08-c2fe-4a34-b777-f901ad2d299d.png)

 
**Setup (please complete the following information):**
 - OS: Linux
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-data-tables:12.1.1 (we also tried v12.3.0 but still faced memory leak issue)
 - Java version: 11
 - App Server/Environment: Azure App Service with P1V2 plan.
 - Frameworks: SpringBoot

**Additional context**
- On investigating about this issue we came across this [bug](https://github.com/Azure/azure-sdk-for-java/issues/12453) and it looks very similar to our case.

- Due to firewall settings we can't connect to our table storage from local therefore we never reprod this in our local env and investigated the same in our lower envs.

**Information Checklist**

- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by anuchandy** [comment] 2022-06-15 19:08
Note: the same issue is being tracked through the support. The support is working on collecting more data since the attempt to repro this by using the fetch API for 13hr didn't show leak symptoms.

<img width="800" alt="TableFetchHeap" src="https://user-images.githubusercontent.com/1471612/173905206-b450a9bc-34f5-4a2a-9d04-dfee0144be79.png">

**Comment by saajanjha** [comment] 2022-06-16 06:38
Hi @anuchandy, would like to know on how you are reproducing it. The table size ? The row size? frequency of requests? total no. of requests? 

> Note: the same issue is being tracked through the support. The support is working on collecting more data since the attempt to repro this by using the fetch API for 13hr didn't show leak symptoms.
> 
> <img alt="TableFetchHeap" width="800" src="https://user-images.githubusercontent.com/1471612/173905206-b450a9bc-34f5-4a2a-9d04-dfee0144be79.png">

**Comment by anuchandy** [comment] 2022-06-19 16:47
We captured the above heap by running a console-app which fetches 200K entities (using Azure Table Client) and iterates through it; I repeated this fetching+iteration cycle for ~13hrs. I mentioned these details in the support case. Probably you received it after my above comment. From your response to support after reviewing the above console-app, it looks like the API usage in the console-app matches your scenario. 


Based on the additional data you provided in the git description and recent information from support, I reworked it further to match your usage scenario better.

1. Created a table with 400 entities, each row having 15 columns (information from support).
2. Created a Java11 Spring test-web-app deployed to Azure App Service P1V2. The test-web-app exposes an API that fetches 400 entities using Azure Table Client and iterate (information from git).
3. You pointed, on average, the production-web-app API is called 5K times / Daily (information from git).
   - From a client VM, I called test-web-app API 450K times over 24hrs.
4. From your observation, the production-web-app's memory doesn't free up, i.e., it stays constant even if no one is using the API (information from support). 
   - To simulate this in my test-web-app setup, I had split the 24hrs into 10-minute slices, two types - 10min_traffic_slice and 10min_no_traffic_slice.
      - During 10min_traffic_slice - the client VM made ~600-650 test-web-app API calls per minute.
      - During 10min_no_traffic_slice - the client VM didn't make any API call.
      - The 10min_traffic_slice and 10min_no_traffic_slice alternated for 24hrs.


--------------------------------

Below is the memory usage pattern observed for 24hrs of the run; as we can see, during 10min_no_traffic_slices, i.e., when no one calls the API, the usage is coming down. It is not exhibiting a constant increase in retained memory.

(I can bump up the memory usage by increasing requests during 10min_traffic_slice or increasing the row size, but the memory still comes down during the no_traffic slice, i.e., no linear growth in retained memory showing leak.)

<img width="1675" alt="SpringAppMemory" src="https://user-images.githubusercontent.com/1471612/174470790-05ce314e-450d-429d-b1f3-7506a574a6b2.png">

Here is the request arrival pattern for the 24hrs (i.e., ~600 requests per min for 10 mins during 10min_traffic_slice followed by 10min_traffic_slice)

<img width="1674" alt="ClientAPICalls" src="https://user-images.githubusercontent.com/1471612/174470841-72808e7e-0234-4689-ade4-f68507edad7d.png">

So the above isolated tests (using Table Client API directly) do not show leak symptom.

I understand you're observing a leak in the application component, which uses Table Service Client, but I don't have enough evidence that the root cause is Table Service Client.

From the support notes, I read you can now repro on your lower environments. Do you see a growth in retained memory over time, leading to OOM? If so, can we extract a minimal repro? I suggest taking multiple heap dumps and compare them to observe GC roots retaining the memory leading to leaks.

I'll share some notes in the support case. Let's have communication in the support case rather than duplicating it here and there (So that all parties are on the same page /, we don't diverge or don't have to jump back and forth to collect information from two sources).

**Comment by anuchandy** [comment] 2022-06-19 18:31
Hello @saajanjha, we captured the above heap by running a console-app which fetches 200K entities (using Azure Table Client) and iterates through it; I repeated this fetching+iteration cycle for ~13hrs. I mentioned these details in the support case. Probably you received it after my above comment. From your response to support after reviewing the above console-app, it looks like the API usage in the console-app matches your scenario. 

--------------------------------

Based on the additional data you provided in the git description and recent information from support, I reworked it further to match your usage scenario better.

1. Created a table with 400 entities, each row having 15 columns (information from support).
2. Created a Java11 Spring test-web-app deployed to Azure App Service P1V2. The test-web-app exposes an API that fetches 400 entities using Azure Table Client and iterate (information from git).
3. On average, the production-web-app API is called 5K times / daily (information from git).
   - From a client VM, I called test-web-app API 450K times over 24hrs.
4. From your observation, the production-web-app's memory doesn't free up, i.e., it stays constant even if no one is using the API (information from support). 
   - To simulate this in my test-web-app setup, I had split the 24hrs into 10-minute slices, two types - 10min_traffic_slice and 10min_no_traffic_slice.
      - During 10min_traffic_slice - the client VM made ~600-650 test-web-app API calls per minute.
      - During 10min_no_traffic_slice - the client VM didn't make any API call.
      - The 10min_traffic_slice and 10min_no_traffic_slice alternated for 24hrs.


--------------------------------

### Request arrival pattern

Here is the request arrival pattern for the 24hrs (i.e., ~600 requests per min for 10 mins during 10min_traffic_slice followed by 10min_no_traffic_slice).

<img width="1674" alt="ClientAPICalls" src="https://user-images.githubusercontent.com/1471612/174470841-72808e7e-0234-4689-ade4-f68507edad7d.png">

### Memory usage pattern

Below is the corresponding  memory usage pattern observed for 24hrs of the run; as we can see, during 10min_no_traffic_slices, i.e., when no one calls the API, the usage is coming down. It is not exhibiting a constant increase in retained memory.

I can bump up the memory usage by increasing requests during 10min_traffic_slice or increasing the row size, but the memory still comes down during the no_traffic slice, i.e., no linear growth in retained memory.

<img width="1675" alt="SpringAppMemory" src="https://user-images.githubusercontent.com/1471612/174470790-05ce314e-450d-429d-b1f3-7506a574a6b2.png">

I left my test-web-app running so that we can see if memory pattern changes in the next few days. 

So the above isolated tests (using Table Client API directly) do not show leak symptom.

--------------------------------

I understand you're observing a leak in the application component, which uses Table Service Client, but I don't have enough evidence/repro that it is coming from Table Service Client to unblock investigation.

From the support notes, I read you can now repro on your lower environments. Do you see a growth in retained memory over time, leading to OOM? If so, can we extract a minimal repro? I suggest taking multiple heap dumps and compare them to observe GC roots retaining the memory leading to leaks.

I'll share some notes in the support case. Let's have communication in the support case rather than duplicating it here and there (so we don't diverge or don't have to jump back and forth to collect information from two sources).

**Comment by saajanjha** [comment] 2022-06-21 08:04
Hi @anuchandy , thanks for your detailed investigation and explanation :) For further communication as you suggested let's connect on support channel. Do let me know your support mail so that I can loop you in.

**Comment by anuchandy** [comment] 2022-06-21 19:03
Hi @saajanjha, there is MS support team engaged; the support engineer will collect data from you and keep the case note up to date, which I've access to.

**Comment by anuchandy** [comment] 2022-06-24 19:12
From the case note, the application insight [issue](https://github.com/microsoft/ApplicationInsights-Java/issues/2074) we discussed seems to be the root cause of this. After upgrading the AI agent to the latest, you don't appear to observe the leak in the lower environment.

I'm closing this GitHub ticket with the root cause as a leak in an older AI agent (3.0.3) combined with HTTP calls that resulted in retained memory.

As a reference linking the projects I used to investigate this

1. The Spring App uses the Azure Table Client [link](https://github.com/anuchandy/az-table-spring/tree/main/spring-web-app)
2. The PowerShell Script to load test the Spring App [link](https://github.com/anuchandy/az-table-spring/blob/main/pwsh-script/hitendpoint.ps1)
3. The Console App to populate the Azure Table for Spring App to read [link](https://github.com/anuchandy/az-table-spring/tree/main/console-app)

**Closed by anuchandy** 2022-06-24 19:12 UTC
Labels: question, Client, customer-reported, Tables
