### ISSUE TITLE
Azure Validation failing.

### ISSUE THREAD

**Issue by ImranBijapuri** [Azure/azure-sdk-for-java#1949] opened 2017-10-16 13:41 UTC
I am using Java SDK and since this morning the Validation started failing with this exception 

`CloudException: Status code 401, {"error":{"code":"InvalidAuthenticationTokenAudience","message":"The access token has been obtained from wrong audience or resource 'https://management.core.windows.net'. It should exactly match (including forward slash) with one of the allowed audiences 'https://management.core.windows.net/','https://management.azure.com/'."}} for target engineering.management.core.windows.net`

I have been using this SDK for more than 6 months now and I have encountered this issue for the first time. I don't pass any URL's as suggested in the error message and hence I don't understand which URL it is referring to.

**Comment by martinsawicki** [comment] 2017-10-23 22:08
@jianghaolu another instance of a Maven behavior picking up snapshot builds where it's not supposed to. Can you pls respond to this with the POM edit workaround?

**Comment by jianghaolu** [comment] 2017-10-25 18:48
Hi @ImranBijapuri Make sure you are getting `azure-client-runtime` 1.1.1+. The issue is fixed in 1.1.1.

**Closed by jianghaolu** 2017-10-25 18:48 UTC

**Comment by ImranBijapuri** [comment] 2017-10-26 09:51
@jianghaolu and @martinsawicki Thanks guys.

The issue is we use azure java sdk 1.1.2 as a dependency which internally use these dependencies, so we have no control over it. Moreover they are not specified as a fixed version but as a range. So the latest one gets picked (which is also an issue because its the trunk version which is subject to change).

I don't understand why would someone add a trunk dependency to a stable version of azure java sdk.

**Comment by jianghaolu** [comment] 2017-10-26 17:41
@ImranBijapuri Yes I understand. There were benefits in the beginning where we could push "fixes" in the runtime into SDK users without asking them to upgrade their SDK version. But now we realize it's a mistake. We will use a fixed version in 1.4 SDK coming next month. Apologize for the inconvenience.
