### ISSUE TITLE
[BUG] Monitor query: executing a query with custom endpoint (Azure China) throws 404.

### ISSUE THREAD

**Issue by zhangyunbo1994** [Azure/azure-sdk-for-java#36070] opened 2023-07-25 03:42 UTC
**Describe the bug**
I am using Java SDK azure-monitor-query 1.2.1 to connect to Azure China to do Monitor Log query. But we encounter error.
We found there is same error in js and python SDK, but for Java, seems not be fixed:

- [Monitor query: executing a query with custom endpoint throws 404. · Issue #22408 · Azure/azure-sdk-for-js (github.com)](https://github.com/Azure/azure-sdk-for-js/issues/22408)
- [[Monitor][Query] Support non-public clouds by pvaneck · Pull Request #29602 · Azure/azure-sdk-for-python (github.com)](https://github.com/Azure/azure-sdk-for-python/pull/29602)

***Exception or Stack Trace***
```
Exception in thread "main" com.azure.core.exception.ClientAuthenticationException: DefaultAzureCredential authentication failed. ---> EnvironmentCredential authentication failed. Error Details: AADSTS500011: The resource principal named https://api.loganalytics.azure.cn/v1 was not found in the tenant named XXXXXXXXXXXXXXXXXXX. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
Trace ID: 8de34f91-0899-489e-8db1-4bb68d8b9000
Correlation ID: cbe86b7e-e95b-47b1-a01d-d77f75acda9a
Timestamp: 2023-07-25 03:35:17Z
	at com.azure.identity.ChainedTokenCredential.lambda$getToken$1(ChainedTokenCredential.java:90)
	at reactor.core.publisher.Mono.lambda$onErrorResume$32(Mono.java:3887)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onError(FluxPeekFuseable.java:234)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:258)
	at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onError(FluxPeekFuseable.java:903)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:2065)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:142)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:192)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:259)
	at reactor.core.publisher.MonoCompletionStage.lambda$subscribe$0(MonoCompletionStage.java:90)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1742)
		at com.azure.core.implementation.AccessTokenCache.getTokenSync(AccessTokenCache.java:77)
		at com.azure.core.http.policy.BearerTokenAuthenticationPolicy.setAuthorizationHeaderHelperSync(BearerTokenAuthenticationPolicy.java:183)
		at com.azure.core.http.policy.BearerTokenAuthenticationPolicy.authorizeRequestSync(BearerTokenAuthenticationPolicy.java:62)
		at com.azure.core.http.policy.BearerTokenAuthenticationPolicy.processSync(BearerTokenAuthenticationPolicy.java:131)
		at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41)
		at com.azure.core.http.policy.CookiePolicy.processSync(CookiePolicy.java:50)
		at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41)
		at com.azure.core.http.policy.AddDatePolicy.processSync(AddDatePolicy.java:45)
		at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41)
		at com.azure.core.http.policy.RetryPolicy.attemptSync(RetryPolicy.java:164)
		at com.azure.core.http.policy.RetryPolicy.attemptSync(RetryPolicy.java:176)
		at com.azure.core.http.policy.RetryPolicy.attemptSync(RetryPolicy.java:176)
		at com.azure.core.http.policy.RetryPolicy.attemptSync(RetryPolicy.java:176)
		at com.azure.core.http.policy.RetryPolicy.processSync(RetryPolicy.java:114)
		at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41)
		at com.azure.core.http.policy.AddHeadersFromContextPolicy.processSync(AddHeadersFromContextPolicy.java:60)
		at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41)
		at com.azure.core.http.policy.RequestIdPolicy.processSync(RequestIdPolicy.java:60)
		at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41)
		at com.azure.core.http.policy.HttpPipelineSyncPolicy.processSync(HttpPipelineSyncPolicy.java:42)
		at com.azure.core.http.policy.UserAgentPolicy.processSync(UserAgentPolicy.java:153)
		at com.azure.core.http.HttpPipelineNextSyncPolicy.processSync(HttpPipelineNextSyncPolicy.java:41)
		at com.azure.core.http.HttpPipeline.sendSync(HttpPipeline.java:131)
		at com.azure.core.implementation.http.rest.SyncRestProxy.send(SyncRestProxy.java:54)
		at com.azure.core.implementation.http.rest.SyncRestProxy.invoke(SyncRestProxy.java:75)
		at com.azure.core.implementation.http.rest.RestProxyBase.invoke(RestProxyBase.java:109)
		at com.azure.core.http.rest.RestProxy.invoke(RestProxy.java:91)
		at jdk.proxy2/jdk.proxy2.$Proxy3.executeSync(Unknown Source)
		at com.azure.monitor.query.implementation.logs.QueriesImpl.executeWithResponse(QueriesImpl.java:505)
		at com.azure.monitor.query.LogsQueryClient.queryWorkspaceWithResponseInternal(LogsQueryClient.java:208)
		at com.azure.monitor.query.LogsQueryClient.queryWorkspaceWithResponse(LogsQueryClient.java:169)
		at com.azure.monitor.query.LogsQueryClient.queryWorkspace(LogsQueryClient.java:88)
		at org.example.Main.main(Main.java:27)
```

***Code Snippet***
Create logsQueryClient object and do query:
```
        LogsQueryClient logsQueryClient = new LogsQueryClientBuilder()
                .credential(new DefaultAzureCredentialBuilder().authorityHost(AzureAuthorityHosts.AZURE_CHINA).build())
                .endpoint("https://api.loganalytics.azure.cn/v1")
                .buildClient();
        LogsQueryResult queryResults = logsQueryClient.queryWorkspace("20xxxxxxxxxxxxxxxxxxxxxxxxxcc", "AppTraces | take 10",
                new QueryTimeInterval(Duration.ofDays(2)));
```

**Setup (please complete the following information):**
 - OS: [e.g. iOS] Windows 
 - IDE: [e.g. IntelliJ]  IntelliJ 
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]  azure-monitor-query 1.2.1
 - Java version: [e.g. 8]  17
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] NA

**Additional context**
In debug mode, if I edit the variable in AzureLogAnalyticsImplBuilder class at line 158, to change the variable localhost from https://api.loganalytics.azure.cn/v1/.default to https://api.loganalytics.azure.cn/.default, the query will work fine.
![image](https://github.com/Azure/azure-sdk-for-java/assets/44389598/ae588cf3-3ff0-4465-a179-bcfdb9824e67)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by DanishKhan1492** [comment] 2023-07-25 11:50
According to your this comment:
`In debug mode, if I edit the variable in AzureLogAnalyticsImplBuilder class at line 158, to change the variable localhost from https://api.loganalytics.azure.cn/v1/.default to https://api.loganalytics.azure.cn/.default, the query will work fine.`
While the above snippet you provided, in the endpoint it has v1. Can you remove v1 from the endpoint and check if it works.|
`
LogsQueryClient logsQueryClient = new LogsQueryClientBuilder()
                .credential(new DefaultAzureCredentialBuilder().authorityHost(AzureAuthorityHosts.AZURE_CHINA).build())
                .endpoint("https://api.loganalytics.azure.cn/v1")
                .buildClient();
`
to

`
LogsQueryClient logsQueryClient = new LogsQueryClientBuilder()
                .credential(new DefaultAzureCredentialBuilder().authorityHost(AzureAuthorityHosts.AZURE_CHINA).build())
                .endpoint("https://api.loganalytics.azure.cn")
                .buildClient();
`

**Comment by zhangyunbo1994** [comment] 2023-07-26 01:55
Hi @DanishKhan1492 if remove v1, still can not work. Error is:
```
Exception in thread "main" com.azure.monitor.query.implementation.logs.models.ErrorResponseException: Status code 404, "{"error":{"message":"The requested path does not exist","code":"PathNotFoundError","correlationId":"ffb560ba-b36b-41d2-b37e-c3748465e4f8"}}"
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at com.azure.core.implementation.http.rest.ResponseExceptionConstructorCache.invoke(ResponseExceptionConstructorCache.java:56)
	at com.azure.core.implementation.http.rest.RestProxyBase.instantiateUnexpectedException(RestProxyBase.java:356)
	at com.azure.core.implementation.http.rest.SyncRestProxy.ensureExpectedStatus(SyncRestProxy.java:130)
	at com.azure.core.implementation.http.rest.SyncRestProxy.handleRestReturnType(SyncRestProxy.java:213)
	at com.azure.core.implementation.http.rest.SyncRestProxy.invoke(SyncRestProxy.java:81)
	at com.azure.core.implementation.http.rest.RestProxyBase.invoke(RestProxyBase.java:109)
	at com.azure.core.http.rest.RestProxy.invoke(RestProxy.java:91)
	at jdk.proxy2/jdk.proxy2.$Proxy3.executeSync(Unknown Source)
	at com.azure.monitor.query.implementation.logs.QueriesImpl.executeWithResponse(QueriesImpl.java:505)
	at com.azure.monitor.query.LogsQueryClient.queryWorkspaceWithResponseInternal(LogsQueryClient.java:208)
	at com.azure.monitor.query.LogsQueryClient.queryWorkspaceWithResponse(LogsQueryClient.java:169)
	at com.azure.monitor.query.LogsQueryClient.queryWorkspace(LogsQueryClient.java:88)
	at org.example.Main.main(Main.java:27)

Process finished with exit code 1
```

**Comment by jairmyree** [comment] 2023-07-27 18:44
@zhangyunbo1994 This issue was being followed and has been addressed in this PR. https://github.com/Azure/azure-sdk-for-python/pull/29602. Once it is released, I will update here and close this issue. Thank you for reaching out!

**Comment by jairmyree** [comment] 2023-07-27 18:47
Hello @zhangyunbo1994,

Thank you for reaching out, this issue was being followed and has been addressed in [this PR](https://github.com/Azure/azure-sdk-for-java/pull/36063l). Once it is released, I will update here and close this issue.

**Comment by zhangyunbo1994** [comment] 2023-07-28 02:03
Hi @jairmyree thanks for your support.

I reviewed your changes, and has some findings:
1、For Azure China, when we build credential, we should specify authorityHost, for example:
![image](https://github.com/Azure/azure-sdk-for-java/assets/44389598/65a8094a-3ec5-4712-b3ae-5cfb0c465ce5)
You can update your doc:
https://github.com/Azure/azure-sdk-for-java/pull/36063/files#diff-c77b3a62a00d6cc214932909255ef638f10d9734893599ace601217eb5d9a573R142

2、And we also found LogsIngestionClient also has this error, couls you please help check? as this class is belong to [com.azure:azure-monitor-ingestion:1.0.4](https://search.maven.org/artifact/com.azure/azure-monitor-ingestion/1.0.4/jar), if needed I can help open a new issue.
![image](https://github.com/Azure/azure-sdk-for-java/assets/44389598/5918158a-eeb9-4248-a100-c26adb1f5f3a)

**Comment by zhangyunbo1994** [comment] 2023-07-31 11:46
Hi @joshfree hope you are doing well, could you please help answer my above questions? Thanks for your support.

**Comment by jairmyree** [comment] 2023-07-31 20:25
Hello @zhangyunbo1994, azure-monitor-query 1.2.3 has been released, and testing has confirmed sovereign cloud support for China endpoints. Please update to the latest version of azure-monitor-query.

**Closed by jairmyree** 2023-07-31 20:25 UTC
Labels: Client, needs-team-triage, Monitor - Query

**Comment by jairmyree** [comment] 2023-07-31 20:51
@zhangyunbo1994 Thank you for pointing this out, I will open an issue to address the documentation regarding the authority host. As for monitor-ingestion, monitor ingestion does not share the implementation with monitor query that resulted in the bug. Our testing indicates that Sovereign cloud support for Monitor Ingestion works as intended. If you've identified a bug with our Monitor Ingestion SDK, please open an issue containing logs and reproduction steps.
