### ISSUE TITLE
[BUG] AzureResourceManager throws NullPointerException in context of ContainerGroup

### ISSUE THREAD

**Issue by sparsick** [Azure/azure-sdk-for-java#27083] opened 2022-02-14 14:50 UTC
**Describe the bug**
When using many Azure container instances with private IP address, then the AzureResourceManager throws time to time NullPointerException in context of ContainerGroup.

***Exception or Stack Trace***
```text
2022-02-11 09:01:42.674+0000 [id=74]    WARNING c.m.j.c.aci.AciCloud#lambda$provision$1: AciCloud: Provision agent test-private-n4s69 failed: java.lang.NullPointerException
java.lang.NullPointerException
        at com.azure.resourcemanager.containerinstance.implementation.ContainerGroupImpl.initializeChildrenFromInner(ContainerGroupImpl.java:217)
        at com.azure.resourcemanager.resources.fluentcore.arm.models.implementation.GroupableParentResourceImpl.<init>(GroupableParentResourceImpl.java:32)
        at com.azure.resourcemanager.containerinstance.implementation.ContainerGroupImpl.<init>(ContainerGroupImpl.java:73)
        at com.azure.resourcemanager.containerinstance.implementation.ContainerGroupsImpl.wrapModel(ContainerGroupsImpl.java:43)
        at com.azure.resourcemanager.containerinstance.implementation.ContainerGroupsImpl.wrapModel(ContainerGroupsImpl.java:24)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
        at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
        at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
        at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
        at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
        at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
        at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398)
        at reactor.core.publisher.MonoFlatMap$FlatMapInner.onSubscribe(MonoFlatMap.java:238)
        at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)
```

**To Reproduce**
Steps to reproduce the behavior: see issue https://github.com/jenkinsci/azure-container-agents-plugin/issues/101

***Code Snippet***
see
* https://github.com/jenkinsci/azure-container-agents-plugin/blob/a22f04771da02f714abab78022efdb38c8bc1fe3/src/main/java/com/microsoft/jenkins/containeragents/aci/AciCloud.java#L201
* https://github.com/jenkinsci/azure-container-agents-plugin/blob/a22f04771da02f714abab78022efdb38c8bc1fe3/src/main/java/com/microsoft/jenkins/containeragents/aci/AciCloud.java#L177

**Expected behavior**
No NullPointerException is thrown.

**Setup (please complete the following information):**
 - OS: Ubuntu 18.04
 - Library/Libraries: com.azure.resourcemanager:azure-resourcemanager-containerinstance:2.9.0
 - Java version: 11
 - Frameworks: Jenkins Plugin [Azure Container Agent](https://github.com/jenkinsci/azure-container-agents-plugin)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by XiaofeiCao** [comment] 2022-02-15 08:28
@sparsick 
Hi, it would help if you can provide additional logging information by initializing  `ContainerInstanceManager `  using something like the code below:
```java
ContainerInstanceManager manager = ContainerInstanceManager.configure()
  .withLogOptions(newHttpLogOptions().setLogLevel(HttpLogDetailLevel.BODY_AND_HEADERS)) // for adding log support
  .authenticate(credential, profile);
```
and log the response for 
```java
ContainerGroup containerGroup =
                    azureResourceManager.containerGroups().getByResourceGroup(resourceGroup, agent.getNodeName());
```
when the exception occurs.
(exception probably occur after actually receiving the response from remote server, so log information should be present)

And redact any sensitive information, thanks!

**Comment by XiaofeiCao** [comment] 2022-02-15 08:36
There's a default log size limit, so if the upper code snippet can't log the response in complete, you can use following code to bypass it:
```java
AzureResourceManager azureResourceManager = AzureResourceManager
        .configure()
        .withLogOptions(new HttpLogOptions()
            .setLogLevel(HttpLogDetailLevel.BODY_AND_HEADERS)
            .setResponseLogger((logger, loggingOptions) -> {
                final HttpResponse response = loggingOptions.getHttpResponse();

                String contentLengthString = response.getHeaderValue("Content-Length");
                String bodySize = (CoreUtils.isNullOrEmpty(contentLengthString))
                    ? "unknown-length body"
                    : contentLengthString + "-byte body";

                StringBuilder responseLogMessage = new StringBuilder();
                responseLogMessage.append("<-- ")
                    .append(response.getStatusCode())
                    .append(" ")
                    .append(response.getRequest().getUrl())
                    .append(" (")
                    .append(loggingOptions.getResponseDuration().toMillis())
                    .append(" ms, ")
                    .append(bodySize)
                    .append(")")
                    .append(System.lineSeparator());

                HttpResponse bufferedResponse = response.buffer();
                ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
                WritableByteChannel bodyContentChannel = Channels.newChannel(outputStream);
                return bufferedResponse.getBody()
                    .flatMap(byteBuffer -> {
                        try {
                            bodyContentChannel.write(byteBuffer.duplicate());
                            return Mono.just(byteBuffer);
                        } catch (IOException ex) {
                            return Mono.error(ex);
                        }
                    })
                    .doFinally(ignored -> {
                        responseLogMessage.append(", Response body:")
                            .append(System.lineSeparator())
                            .append(outputStream.toString(StandardCharsets.UTF_8))
                            .append(System.lineSeparator())
                            .append(" <-- END HTTP");

                        logger.info(responseLogMessage.toString());

                    }).then(Mono.just(bufferedResponse));

            })
        )
        .authenticate(credential, profile)
```

**Comment by sparsick** [comment] 2022-02-16 14:40
@XiaofeiCao the log information with your requested log level:

````shell
2022-02-16 14:09:29.645+0000 [id=79]    INFO    c.m.j.c.a.AciCleanTask$DeploymentRegistrar#registerDeployment: AzureAciCleanUpTask: registerDeployment: Registering deployment test-private-d3zld1qx in jenkins-rg
2022-02-16 14:09:29.890+0000 [id=79]    INFO    c.m.j.c.aci.AciService#createDeployment: Waiting for deployment test-private-d3zld1qx
2022-02-16 14:09:29.892+0000 [id=79]    INFO    c.a.c.util.logging.ClientLogger#info: --> GET https://management.azure.com/subscriptions/subscriptionId/resourcegroups/jenkins-rg/providers/Microsoft.Resources/deployments/test-private-d3zld1qx?api-version=REDACTEDTry count: 1(empty body)--> END GET
2022-02-16 14:09:39.959+0000 [id=79]    INFO    c.a.c.util.logging.ClientLogger#info: --> GET https://management.azure.com/subscriptions/subscriptionId/resourcegroups/jenkins-rg/providers/Microsoft.Resources/deployments/test-private-d3zld1qx?api-version=REDACTEDTry count: 1(empty body)--> END GET
2022-02-16 14:09:50.012+0000 [id=79]    INFO    c.a.c.util.logging.ClientLogger#info: --> GET https://management.azure.com/subscriptions/subscriptionId/resourcegroups/jenkins-rg/providers/Microsoft.Resources/deployments/test-private-d3zld1qx?api-version=REDACTEDTry count: 1(empty body)--> END GET
2022-02-16 14:10:00.043+0000 [id=79]    INFO    c.a.c.util.logging.ClientLogger#info: --> GET https://management.azure.com/subscriptions/subscriptionId/resourcegroups/jenkins-rg/providers/Microsoft.Resources/deployments/test-private-d3zld1qx?api-version=REDACTEDTry count: 1(empty body)--> END GET
2022-02-16 14:10:10.069+0000 [id=79]    INFO    c.a.c.util.logging.ClientLogger#info: --> GET https://management.azure.com/subscriptions/subscriptionId/resourcegroups/jenkins-rg/providers/Microsoft.Resources/deployments/test-private-d3zld1qx?api-version=REDACTEDTry count: 1(empty body)--> END GET
2022-02-16 14:10:20.100+0000 [id=79]    INFO    c.a.c.util.logging.ClientLogger#info: --> GET https://management.azure.com/subscriptions/subscriptionId/resourcegroups/jenkins-rg/providers/Microsoft.Resources/deployments/test-private-d3zld1qx?api-version=REDACTEDTry count: 1(empty body)--> END GET
2022-02-16 14:10:20.132+0000 [id=79]    INFO    c.m.j.c.aci.AciService#createDeployment: Deployment test-private-d3zld1qx succeed
2022-02-16 14:10:20.132+0000 [id=79]    INFO    c.m.j.c.aci.AciCloud#waitToOnline: Waiting agent test-private-5s16p to online
2022-02-16 14:10:20.133+0000 [id=79]    INFO    c.a.c.util.logging.ClientLogger#info: --> GET https://management.azure.com/subscriptions/subscriptionId/resourceGroups/jenkins-rg/providers/Microsoft.ContainerInstance/containerGroups/test-private-5s16p?api-version=REDACTEDTry count: 1(empty body)--> END GET
2022-02-16 14:10:20.272+0000 [id=79]    WARNING c.m.j.c.aci.AciCloud#waitToOnline: Waiting for Agent test-private-5s16p produces a NullPointerException, but it is ignored.
2022-02-16 14:10:35.519+0000 [id=79]    INFO    c.a.c.util.logging.ClientLogger#info: --> GET https://management.azure.com/subscriptions/subscriptionId/resourceGroups/jenkins-rg/providers/Microsoft.ContainerInstance/containerGroups/test-private-5s16p?api-version=REDACTEDTry count: 1(empty body)--> END GET
````

I added a [workaround](https://github.com/jenkinsci/azure-container-agents-plugin/blob/f18b5bf95fe69e0bc24441065ebb214473bde8f0/src/main/java/com/microsoft/jenkins/containeragents/aci/AciCloud.java#L247). Therefore, the log message looks a bit different from the original post.

**Comment by XiaofeiCao** [comment] 2022-02-17 05:57
Hi @sparsick ,
Thanks for providing the information!
However, I don't see response body in your provided log, so I believe the response body exceeds the log limit size so the logger won't log it...
Please try the second code snippet:
```java
AzureResourceManager azureResourceManager = AzureResourceManager
        .configure()
        .withLogOptions(new HttpLogOptions()
            .setLogLevel(HttpLogDetailLevel.BODY_AND_HEADERS)
            .setResponseLogger((logger, loggingOptions) -> {
                final HttpResponse response = loggingOptions.getHttpResponse();

                String contentLengthString = response.getHeaderValue("Content-Length");
                String bodySize = (CoreUtils.isNullOrEmpty(contentLengthString))
                    ? "unknown-length body"
                    : contentLengthString + "-byte body";

                StringBuilder responseLogMessage = new StringBuilder();
                responseLogMessage.append("<-- ")
                    .append(response.getStatusCode())
                    .append(" ")
                    .append(response.getRequest().getUrl())
                    .append(" (")
                    .append(loggingOptions.getResponseDuration().toMillis())
                    .append(" ms, ")
                    .append(bodySize)
                    .append(")")
                    .append(System.lineSeparator());

                HttpResponse bufferedResponse = response.buffer();
                ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
                WritableByteChannel bodyContentChannel = Channels.newChannel(outputStream);
                return bufferedResponse.getBody()
                    .flatMap(byteBuffer -> {
                        try {
                            bodyContentChannel.write(byteBuffer.duplicate());
                            return Mono.just(byteBuffer);
                        } catch (IOException ex) {
                            return Mono.error(ex);
                        }
                    })
                    .doFinally(ignored -> {
                        responseLogMessage.append(", Response body:")
                            .append(System.lineSeparator())
                            .append(outputStream.toString(StandardCharsets.UTF_8))
                            .append(System.lineSeparator())
                            .append(" <-- END HTTP");

                        logger.info(responseLogMessage.toString());

                    }).then(Mono.just(bufferedResponse));

            })
        )
        .authenticate(credential, profile)

```
The log should look like :
```shell
13:41:13.035 [reactor-http-nio-2] INFO com.azure.resourcemanager.containerinstance.implementation.ContainerGroupsClientImpl$ContainerGroupsService.getByResourceGroup - <-- 200 https://management.azure.com/subscriptions/subscriptionId/resourceGroups/jenkins-rg/providers/Microsoft.ContainerInstance/containerGroups/test-private-5s16p?api-version=REDACTED (4701 ms, 3003-byte body)Response body:XXXXXX
```
Thanks!

**Comment by sparsick** [comment] 2022-02-17 13:26
@XiaofeiCao I'm sorry. I misinterpret ` 1(empty body)` in the log. 

The log output  after I add your second suggestion:

````text
2022-02-17 13:18:19.301+0000 [id=81]    INFO    c.m.j.c.aci.AciCloud#waitToOnline: Waiting agent test-private-0lq3r to online
2022-02-17 13:18:19.305+0000 [id=81]    INFO    c.a.c.util.logging.ClientLogger#info: --> GET https://management.azure.com/subscriptions/xxxx/resourceGroups/jenkins-rg/providers/Microsoft.ContainerInstance/containerGroups/test-private-0lq3r?api-version=REDACTEDTry count: 1(empty body)--> END GET
2022-02-17 13:18:19.305+0000 [id=90]    INFO    c.a.c.util.logging.ClientLogger#info: <-- 200 https://management.azure.com/subscriptions/xxxx/resourcegroups/jenkins-rg/providers/Microsoft.Resources/deployments/test-private-2v2wkf80?api-version=2021-01-01 (24 ms, 879-byte body), Response body:{"id":"/subscriptions/xxxx/resourceGroups/jenkins-rg/providers/Microsoft.Resources/deployments/test-private-2v2wkf80","name":"test-private-2v2wkf80","type":"Microsoft.Resources/deployments","properties":{"templateHash":"6734600995672867068","parameters":{},"mode":"Incremental","provisioningState":"Succeeded","timestamp":"2022-02-17T13:18:18.9495614Z","duration":"PT1M19.9967061S","correlationId":"630d4912-8605-4b80-b69c-8131ecbf72f6","providers":[{"namespace":"Microsoft.ContainerInstance","resourceTypes":[{"resourceType":"containerGroups","locations":["northeurope"]}]}],"dependencies":[],"outputs":{"containerIPv4Address":{"type":"String","value":"10.0.2.5"}},"outputResources":[{"id":"/subscriptions/xxxx/resourceGroups/jenkins-rg/providers/Microsoft.ContainerInstance/containerGroups/test-private-0lq3r"}]}} <-- END HTTP
2022-02-17 13:18:19.342+0000 [id=146]   INFO    c.a.c.util.logging.ClientLogger#info: --> GET https://management.azure.com/subscriptions/xxxx/resourcegroups/jenkins-rg/providers/Microsoft.Resources/deployments/test-private-5ldm3h8l?api-version=REDACTEDTry count: 1(empty body)--> END GET
2022-02-17 13:18:19.374+0000 [id=91]    INFO    c.a.c.util.logging.ClientLogger#info: <-- 200 https://management.azure.com/subscriptions/xxxx/resourcegroups/jenkins-rg/providers/Microsoft.Resources/deployments/test-private-5ldm3h8l?api-version=2021-01-01 (29 ms, 623-byte body), Response body:{"id":"/subscriptions/xxxx/resourceGroups/jenkins-rg/providers/Microsoft.Resources/deployments/test-private-5ldm3h8l","name":"test-private-5ldm3h8l","type":"Microsoft.Resources/deployments","properties":{"templateHash":"9904916279829693374","parameters":{},"mode":"Incremental","provisioningState":"Running","timestamp":"2022-02-17T13:18:13.1465396Z","duration":"PT33.9710325S","correlationId":"7ac877a2-fda0-4399-a19e-dafd77dcd35d","providers":[{"namespace":"Microsoft.ContainerInstance","resourceTypes":[{"resourceType":"containerGroups","locations":["northeurope"]}]}],"dependencies":[]}} <-- END HTTP
2022-02-17 13:18:19.464+0000 [id=81]    WARNING c.m.j.c.aci.AciCloud#waitToOnline: Waiting for Agent test-private-0lq3r produces a NullPointerException, but it is ignored.
2022-02-17 13:18:19.467+0000 [id=81]    INFO    c.a.c.util.logging.ClientLogger#info: --> GET https://management.azure.com/subscriptions/xxxx/resourceGroups/jenkins-rg/providers/Microsoft.ContainerInstance/containerGroups/test-private-0lq3r?api-version=REDACTEDTry count: 1(empty body)--> END GET
2022-02-17 13:18:19.475+0000 [id=92]    INFO    c.a.c.util.logging.ClientLogger#info: <-- 200 https://management.azure.com/subscriptions/xxxx/resourceGroups/jenkins-rg/providers/Microsoft.ContainerInstance/containerGroups/test-private-0lq3r?api-version=2021-09-01 (67 ms, 2703-byte body), Response body:{"properties":{"sku":"Standard","provisioningState":"Succeeded","containers":[{"name":"test-private-0lq3r","properties":{"image":"jenkins/inbound-agent","command":["jenkins-agent","-url","http://104.46.15.57:8080/","3161fbd2d27f9ce7108eccbdfc37e59f1942e2902242bbd9988088350ff75755","test-private-0lq3r"],"ports":[{"port":80}],"environmentVariables":[],"instanceView":{"restartCount":0,"currentState":{"state":"Running","startTime":"2022-02-17T13:18:02Z","detailStatus":""},"events":[{"count":1,"firstTimestamp":"2022-02-17T13:17:33Z","lastTimestamp":"2022-02-17T13:17:33Z","name":"Pulling","message":"Pulling image \"jenkins/inbound-agent\"","type":"Normal"},{"count":1,"firstTimestamp":"2022-02-17T13:18:01Z","lastTimestamp":"2022-02-17T13:18:01Z","name":"Pulled","message":"Successfully pulled image \"jenkins/inbound-agent\" in 28.259915764s","type":"Normal"},{"count":1,"firstTimestamp":"2022-02-17T13:18:02Z","lastTimestamp":"2022-02-17T13:18:02Z","name":"Created","message":"Created container test-private-0lq3r","type":"Normal"},{"count":1,"firstTimestamp":"2022-02-17T13:18:02Z","lastTimestamp":"2022-02-17T13:18:02Z","name":"Started","message":"Started container test-private-0lq3r","type":"Normal"}]},"resources":{"requests":{"memoryInGB":1.5,"cpu":1.0}}}}],"initContainers":[],"imageRegistryCredentials":[],"ipAddress":{"ports":[{"port":80}],"ip":"10.0.2.5","type":"Private","dnsNameLabelReusePolicy":"Unsecure"},"osType":"Linux","instanceView":{"events":[{"count":1,"firstTimestamp":"2022-02-17T13:17:05Z","lastTimestamp":"2022-02-17T13:17:05Z","name":"PrepareNetwork","message":"Prepare network succeeded.","type":"Normal"},{"count":1,"firstTimestamp":"2022-02-17T13:17:06Z","lastTimestamp":"2022-02-17T13:17:06Z","name":"JoinNetwork","message":"Join network succeeded.","type":"Normal"},{"count":1,"firstTimestamp":"2022-02-17T13:17:06Z","lastTimestamp":"2022-02-17T13:17:06Z","name":"DelegateSubnet","message":"Delegate subnet succeeded.","type":"Normal"},{"count":1,"firstTimestamp":"2022-02-17T13:17:11Z","lastTimestamp":"2022-02-17T13:17:11Z","name":"ProvisionNetworkInterface","message":"Provision network interface succeeded.","type":"Normal"}],"state":"Running"},"subnetIds":[{"id":"/subscriptions/xxxx/resourceGroups/jenkins-vnet-rg/providers/Microsoft.Network/virtualNetworks/jenkins-vnet/subnets/jenkins-agent-subnet"}]},"id":"/subscriptions/xxxx/resourceGroups/jenkins-rg/providers/Microsoft.ContainerInstance/containerGroups/test-private-0lq3r","name":"test-private-0lq3r","type":"Microsoft.ContainerInstance/containerGroups","location":"northeurope","tags":{"JenkinsInstance":"00f3038298bbb562b8f4196bc587cd3a"}} <-- END HTTP
2022-02-17 13:18:19.562+0000 [id=81]    WARNING c.m.j.c.aci.AciCloud#addIpEnv: During asking for IP address of Agent test-private-0lq3r NullPointerException is thrown,but it is ignored.
2022-02-17 13:18:19.566+0000 [id=90]    INFO    c.a.c.util.logging.ClientLogger#info: <-- 200 https://management.azure.com/subscriptions/xxxx/resourceGroups/jenkins-rg/providers/Microsoft.ContainerInstance/containerGroups/test-private-0lq3r?api-version=2021-09-01 (89 ms, 2703-byte body), Response body:{"properties":{"sku":"Standard","provisioningState":"Succeeded","containers":[{"name":"test-private-0lq3r","properties":{"image":"jenkins/inbound-agent","command":["jenkins-agent","-url","http://104.46.15.57:8080/","3161fbd2d27f9ce7108eccbdfc37e59f1942e2902242bbd9988088350ff75755","test-private-0lq3r"],"ports":[{"port":80}],"environmentVariables":[],"instanceView":{"restartCount":0,"currentState":{"state":"Running","startTime":"2022-02-17T13:18:02Z","detailStatus":""},"events":[{"count":1,"firstTimestamp":"2022-02-17T13:17:33Z","lastTimestamp":"2022-02-17T13:17:33Z","name":"Pulling","message":"Pulling image \"jenkins/inbound-agent\"","type":"Normal"},{"count":1,"firstTimestamp":"2022-02-17T13:18:01Z","lastTimestamp":"2022-02-17T13:18:01Z","name":"Pulled","message":"Successfully pulled image \"jenkins/inbound-agent\" in 28.259915764s","type":"Normal"},{"count":1,"firstTimestamp":"2022-02-17T13:18:02Z","lastTimestamp":"2022-02-17T13:18:02Z","name":"Created","message":"Created container test-private-0lq3r","type":"Normal"},{"count":1,"firstTimestamp":"2022-02-17T13:18:02Z","lastTimestamp":"2022-02-17T13:18:02Z","name":"Started","message":"Started container test-private-0lq3r","type":"Normal"}]},"resources":{"requests":{"memoryInGB":1.5,"cpu":1.0}}}}],"initContainers":[],"imageRegistryCredentials":[],"ipAddress":{"ports":[{"port":80}],"ip":"10.0.2.5","type":"Private","dnsNameLabelReusePolicy":"Unsecure"},"osType":"Linux","instanceView":{"events":[{"count":1,"firstTimestamp":"2022-02-17T13:17:05Z","lastTimestamp":"2022-02-17T13:17:05Z","name":"PrepareNetwork","message":"Prepare network succeeded.","type":"Normal"},{"count":1,"firstTimestamp":"2022-02-17T13:17:06Z","lastTimestamp":"2022-02-17T13:17:06Z","name":"JoinNetwork","message":"Join network succeeded.","type":"Normal"},{"count":1,"firstTimestamp":"2022-02-17T13:17:06Z","lastTimestamp":"2022-02-17T13:17:06Z","name":"DelegateSubnet","message":"Delegate subnet succeeded.","type":"Normal"},{"count":1,"firstTimestamp":"2022-02-17T13:17:11Z","lastTimestamp":"2022-02-17T13:17:11Z","name":"ProvisionNetworkInterface","message":"Provision network interface succeeded.","type":"Normal"}],"state":"Running"},"subnetIds":[{"id":"/subscriptions/xxxx/resourceGroups/jenkins-vnet-rg/providers/Microsoft.Network/virtualNetworks/jenkins-vnet/subnets/jenkins-agent-subnet"}]},"id":"/subscriptions/xxxx/resourceGroups/jenkins-rg/providers/Microsoft.ContainerInstance/containerGroups/test-private-0lq3r","name":"test-private-0lq3r","type":"Microsoft.ContainerInstance/containerGroups","location":"northeurope","tags":{"JenkinsInstance":"00f3038298bbb562b8f4196bc587cd3a"}} <-- END HTTP
2022-02-17 13:18:20.099+0000 [id=36]    INFO    c.m.j.c.s.ContainerOnceRetentionStrategy#done: terminating test-private-0lq3r since PlaceholderExecutable:ExecutorStepExecution.PlaceholderTask{runId=test-private#81,label=test-private-0lq3r,context=CpsStepContext[3:node]:Owner[test-private/81:test-private #81],cookie=7969ac64-afda-4129-9100-c568e2ca4930,auth=null} seems to be finished
2022-02-17 13:18:20.104+0000 [id=128]   INFO    j.s.DefaultJnlpSlaveReceiver#channelClosed: Computer.threadPoolForRemoting [#38] for test-private-0lq3r terminated: java.nio.channels.ClosedChannelException
2022-02-17 13:18:20.295+0000 [id=196]   INFO    c.a.c.util.logging.ClientLogger#performLogging: Azure Identity => getToken() result for scopes [https://management.core.windows.net//.default]: SUCCESS
2022-02-17 13:18:20.296+0000 [id=196]   INFO    c.a.c.util.logging.ClientLogger#info: Acquired a new access token.
2022-02-17 13:18:20.296+0000 [id=196]   INFO    c.a.c.util.logging.ClientLogger#info: --> DELETE https://management.azure.com/subscriptions/xxxx/resourceGroups/jenkins-rg/providers/Microsoft.ContainerInstance/containerGroups/test-private-0lq3r?api-version=REDACTEDTry count: 1(empty body)--> END DELETE
2022-02-17 13:18:20.885+0000 [id=125]   INFO    c.m.j.c.aci.AciService#deleteAciContainerGroup: Delete ACI Container Group: test-private-0lq3r successfully

````

**Comment by XiaofeiCao** [comment] 2022-02-18 02:28
@sparsick It's fine, `(empty body)` is a little misleading.

I can see now from your log that the `ports` parameter in your `ipAddress` section has a port definition `{"port":80}` which does not contain the `protocol`. I've confirmed that ArmTemplate deployments allow this to happen [as defined here](https://docs.microsoft.com/en-us/azure/templates/microsoft.containerinstance/containergroups?tabs=bicep#ipaddress) and our sdk does not deal with this situation propertly. 

I think we can safely assume that missing of `protocol` means defaults to `tcp`. Will add a protection method there.

**Comment by sparsick** [comment] 2022-02-18 07:44
@XiaofeiCao Thank you. I recheck our ARM Template that we use for [creating the deploymen](https://github.com/jenkinsci/azure-container-agents-plugin/blob/f18b5bf95fe69e0bc24441065ebb214473bde8f0/src/main/java/com/microsoft/jenkins/containeragents/aci/AciService.java#L25)t. We set the protocol to `TCP`

A sample of our ARM Template for creating the deployment

```json
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {},
  "variables": {
    "containerName": "fancyname",
    "containerImage": "helloworld",
    "cpu": "cpu",
    "memory": "memory",
    "osType": "linux",
    "jenkinsInstance": "instanceId",
    "ipType": "Private",
    "vnetResourceGroupName": "vnetResourceGroup",
    "vnetName": "vnet",
    "subnetName": "subnet"
  },
  "resources": [
    {
      "name": "[variables('containerName')]",
      "type": "Microsoft.ContainerInstance/containerGroups",
      "apiVersion": "2021-09-01",
      "tags": {
        "JenkinsInstance": "[variables('jenkinsInstance')]"
      },
      "location": "[resourceGroup().location]",
      "properties": {
        "containers": [
          {
            "name": "[variables('containerName')]",
            "properties": {
              "command": [
                "command"
              ],
              "image": "[variables('containerImage')]",
              "resources": {
                "requests": {
                  "cpu": "[variables('cpu')]",
                  "memoryInGb": "[variables('memory')]"
                }
              },
              "ports": [
                {
                  "port": "80"
                }
              ],
              "environmentVariables": [],
              "volumeMounts": []
            }
          }
        ],
        "osType": "[variables('osType')]",
        "volumes": [],
        "ipAddress": {
          "type": "[variables('ipType')]",
          "ports": [
            {
              "protocol": "tcp",
              "port": "80"
            }
          ]
        },
        "imageRegistryCredentials": [],
        "subnetIds": [
          {
            "id": "[resourceId(variables('vnetResourceGroupName'), 'Microsoft.Network/virtualNetworks/subnets', variables('vnetName'), variables('subnetName'))]"
          }
        ]
      }
    }
  ],
  "outputs": {
    "containerIPv4Address": {
      "type": "string",
      "value": "[reference(resourceId('Microsoft.ContainerInstance/containerGroups/', variables('containerName'))).ipAddress.ip]"
    }
  }
}
```

**Comment by XiaofeiCao** [comment] 2022-02-18 08:22
@sparsick Thanks for your template sample and yes it's actually setting the protocol...

Since you mentioned that the NPE is from time to time and the templates are constructed dynamically, can it be that some of them are without `protocol` ?

To be sure whether this is the case, a log for the actual ARM template used [here](https://github.com/jenkinsci/azure-container-agents-plugin/blob/f18b5bf95fe69e0bc24441065ebb214473bde8f0/src/main/java/com/microsoft/jenkins/containeragents/aci/AciService.java#L41) before the NPE will be of great help!

**Comment by timja** [comment] 2022-02-18 08:25
@sparsick feel free to just add that to the plugin in general, it can be useful for debugging, see pattern in the virtual machines plugin: https://github.com/jenkinsci/azure-vm-agents-plugin/blob/master/src/main/java/com/microsoft/azure/vmagent/AzureVMManagementServiceDelegate.java#L595-L599

**Comment by sparsick** [comment] 2022-02-18 12:13
@timja 👍 I will prepare a PR with your suggestion. 

@XiaofeiCao I will prepare a new logout where the ARM template is also logged.

**Comment by XiaofeiCao** [comment] 2022-02-19 10:01
@sparsick Thanks, the log is great! I can tell from your log that the templates are actually the same. I'll add some protections for this situation. You can expect it to be fixed in the next sdk release.

In the meanwhile, if you want, you can add a `protocol` to the [container port](https://github.com/jenkinsci/azure-container-agents-plugin/blob/master/src/main/resources/com/microsoft/jenkins/containeragents/aci/deployTemplate.json#L39) in your template. I believe this will also resolve this issue.

**Closed** 2022-02-22 09:22 UTC
Labels: question, ARM, Mgmt, customer-reported

**Comment by XiaofeiCao** [comment] 2022-03-11 11:24
@sparsick Hi, new SDK has just been released, you can try it out!
https://search.maven.org/artifact/com.azure.resourcemanager/azure-resourcemanager-containerservice/2.13.0/jar

**Comment by sparsick** [comment] 2022-03-11 12:12
@XiaofeiCao Thank you for mentioning me. I opened a [PR](https://github.com/jenkinsci/azure-sdk-plugin/pull/113) in https://github.com/jenkinsci/azure-sdk-plugin/. After releasing this plugin, I can test it in the original plugin.
