### ISSUE TITLE
[Question] In the Service bus SDK, when I use the `ServiceBusProcessorClient` to create a client, I use the wrong queue name or topic name, the SDK does not give an exception, but keeps retrying. Is it reasonable for this behavior?

### ISSUE THREAD

**Issue by ZhuXiaoBing-cn** [Azure/azure-sdk-for-java#23041] opened 2021-07-19 05:06 UTC
**Query/Question**
In the Service bus SDK, when I use the `ServiceBusProcessorClient` to create a client, I use the wrong queue name or topic name, the SDK does not give an exception but keeps retrying. Is it reasonable for this behavior?

**Setup (please complete the following information if applicable):**
 - Library/Libraries: [ azure-messaging-servicebus:7.2.3(groupId:artifactId:version)]
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and check off the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by ki1729** [comment] 2021-07-20 21:03
Hi @ZhuXiaoBing-cn ! Yea that is really strange. Investigating more on this

**Comment by ramya-rao-a** [comment] 2021-08-30 21:02
@ZhuXiaoBing-cn,
 
The client does not do any checks on whether a queue/topic/subscription exists when attempting to make a connection. We rely on the service to throw an error if they don't. If needed, you can make the check using the `ServiceBusAdministrationClient` before using the processor client

@ki1729 A few things to check
- What error do we see when we do this with the sender or receiver client? Do we get a retryable error or a non retryable error?
- The processor client was designed use the "run forever" approach. The onus is on the user to keep an eye in the process error call back to see if they want to exit. Please sync with @JoshLove-msft to confirm this. He would have insights on the same processor client but in .NET

**Comment by JoshLove-msft** [comment] 2021-08-30 21:04
> The processor client was designed use the "run forever" approach.

The one caveat to this is that if the `ServiceBusClient` was closed, the processor will stop itself rather than continually trying to run forever.

**Comment by ki1729** [comment] 2022-03-01 18:27
@ZhuXiaoBing-cn 
As Ramya has mentioned, the processor client does not check weather that entity exists. Using the adminstration client to verify that you have correct configuration would work. As this expected path forward, I will optimistically go ahead and close the issue. Please feel free to re-open / file a new issue as needed

@ramya-rao-a  : We do throw a non-retryable error internally. `"az.sdk.message":"Non-retryable error occurred in AMQP receive link.","exception":"The messaging entity 'sb://rndNamespace.servicebus.windows.net/entityName' could not be found.`
But because it is the processor client, we keep trying to Create a valid consumer, which makes the attempt to connect again, with a frequency of about once every 1 second or so. (Not a high enough frequency to cause throttling on the server side, so we should be good).

**Closed by ki1729** 2022-03-01 18:27 UTC
Labels: question, Service Bus, Client
