### ISSUE TITLE
[BUG] OutOfMemoryError while get events  from Azure EventHub  and   thread.sleep(1000*100)

### ISSUE THREAD

**Issue by liujinminggithub** [Azure/azure-sdk-for-java#30909] opened 2022-09-11 14:21 UTC
run the code , and the program occur  OutOfMemoryError .
I use thread.sleep(1000*100) to replace my code cost time.

```java
import com.azure.messaging.eventhubs.EventData;
import com.azure.messaging.eventhubs.EventProcessorClient;
import com.azure.messaging.eventhubs.EventProcessorClientBuilder;
import com.azure.messaging.eventhubs.checkpointstore.blob.BlobCheckpointStore;
import com.azure.storage.blob.BlobContainerAsyncClient;
import com.azure.storage.blob.BlobServiceClientBuilder;

import java.time.Duration;

public class TestEventHub {
    private static final String connectionString = "XXXXXXXXXXXXXXXXXX";
    private static final String eventHubName = "XXXXXXXX";

    public static void main(String[] args) {
        readEvents();
    }


    public static void readEvents() {

        String eventHubName = "XXXX";
        String connectionString = "
        String consumerGroupName = "XXXX";
        String eventHubPointBlobConnStr = "XXXX";
        String eventHubPointContainerName = "XXXX";

        BlobContainerAsyncClient blobContainerAsyncClient = new BlobServiceClientBuilder().connectionString(eventHubPointBlobConnStr).buildAsyncClient().getBlobContainerAsyncClient(eventHubPointContainerName);
        EventProcessorClientBuilder eventProcessorClientBuilder = new EventProcessorClientBuilder();
        eventProcessorClientBuilder.connectionString(connectionString, eventHubName)
                .processEventBatch(batchContext -> {
                    for (EventData eventData : batchContext.getEvents()) {
                        if (eventData.getSequenceNumber() % 100 == 0) {
                            batchContext.updateCheckpoint();
                        }
                    }
                    try {
                        Thread.sleep(150 * 1000);
                    } catch (InterruptedException e) {
                        throw new RuntimeException(e);
                    }
                }, 200, Duration.ofSeconds(5))
                .processError(errorContext -> {
                    System.out.printf("Error occurred in partition processor for partition %s, %s%n",
                            errorContext.getPartitionContext().getPartitionId(),
                            errorContext.getThrowable());
                })
                .prefetchCount(5000)
                .checkpointStore(new BlobCheckpointStore(blobContainerAsyncClient))
                .consumerGroup(consumerGroupName);
        EventProcessorClient eventProcessorClient = eventProcessorClientBuilder.buildEventProcessorClient();
        eventProcessorClient.start();
    }
}
```

pom.xml

```xml
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-messaging-eventhubs</artifactId>
            <version>5.13.0</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/io.projectreactor/reactor-core -->
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-core</artifactId>
            <version>3.4.18</version>
        </dependency>

        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-messaging-eventhubs-checkpointstore-blob</artifactId>
            <version>1.12.0</version>
        </dependency>
```

jvm options:
-Xms1000M -Xmx1000M -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=jvm_dudmp.log

**Comment by joshfree** [comment] 2022-09-14 17:35
Resolving as duplicate of https://github.com/Azure/azure-sdk-for-java/issues/30907, we will use https://github.com/Azure/azure-sdk-for-java/issues/30907 to continue the discussion

**Closed by joshfree** 2022-09-14 17:35 UTC
Labels: question, customer-reported, needs-triage
