### ISSUE TITLE
[FEATURE REQ] Add Support for custom logging logic / transforms.

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-java#11660] opened 2020-06-02 03:40 UTC
we need to add support for users to specify custom logging logic and the two techniques which can achieve this are:

1. Function based hooks (passed via HttpLogOptions) 
2. Ability to Extend HttpLoggingPolicy / AbstractBase and override logRequest and logResponse methods.

Option 1 is preferred currently (given the requests and use cases we've been seeing from the users.)

**Comment by alzimmermsft** [comment] 2020-06-02 06:16
Appears to be a duplicate of #11477.

**Comment by alzimmermsft** [comment] 2020-06-03 16:43
Closing as duplicate of #11477

**Closed by alzimmermsft** 2020-06-03 16:43 UTC
Labels: Azure.Core, Client
