### ISSUE TITLE
[QUESTION] Keyvault secrets not updating on Azure spring apps

### ISSUE THREAD

**Issue by gnandyala123** [Azure/azure-sdk-for-java#36164] opened 2023-07-28 14:56 UTC
**Describe the bug**
Not seeing the recent key secrets updated on runtime env after the refresh on key vault side , we need to manually do restart to get this changes In Azure spring Apps environment.

**To Reproduce**
-- We have tried to load it in the runtime but using spring.cloud.azure.keyvault.secret.property-sources[].refresh-interval but the secrets are not refreshing until and manual restart is done.

https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/secret-management#setting-refresh-interval

-- We tried this and printed for every 30 secs but still the refreshed secret from keyvault is not updating in runtime environment
***Code Snippet***
Add the code snippet that causes the issue.

![image](https://github.com/Azure/azure-sdk-for-java/assets/97708385/75f1a8ce-6d1d-4a38-896c-24ad6b6f166f)

**Expected behavior**
Token to be updated on runtime

**Screenshots**

**Comment by Netyyyy** [comment] 2023-08-03 01:19
Hi @gnandyala123 , thanks for reaching out.
We have received your submission and will take it into consideration. We appreciate your input and will review this matter as soon as possible.
Please feel free to provide any additional information or context that you think may be helpful. We'll keep you updated on the progress of our review.
Thank you for your contribution to improving our project.

**Comment by moarychan** [comment] 2023-08-17 01:51
Related issue https://github.com/Azure/azure-sdk-for-java/issues/26356

**Comment by moarychan** [comment] 2024-09-06 05:28
Hi @gnandyala123 , I cannot reproduce this issue via ASA-E app + KV + Managed Identity, I used the version spring-cloud-azure-starter-keyvault:5.14.0; if you only use one key vault property source, then it should work fine.

There's linked PR to support multiple key vault property source, the new version can show more logs for each property source loading.

**Comment by moarychan** [comment] 2024-09-20 01:20
Hi @gnandyala123 , you can try to use the new version [5.16.0](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/CHANGELOG.md#5160-2024-09-09). I am going to close this issue, please reopen this issue or create a new one if you still encounter related issues.

**Closed by moarychan** 2024-09-20 01:20 UTC
Labels: question, Client, customer-reported, needs-author-feedback, azure-spring, azure-spring-keyvault
