### ISSUE TITLE
Need to change DocumentDB to CosmosDB.

### ISSUE THREAD

**Issue by alvadb** [Azure/azure-sdk-for-java#1754] opened 2017-06-12 22:57 UTC
The name documentdb needs to be changed to cosmosdb.  Also, the collection name for DocumentDB which is currently documentDBs needs to include the suffix Accounts.

**Comment by martinsawicki** [comment] 2017-06-12 23:11
closing as dupe of https://github.com/Azure/azure-sdk-for-java/issues/1749

**Closed** 2017-06-12 23:11 UTC
