### ISSUE TITLE
[API] Unable to delete a value with an "`" or "è" by API on CosmoDB - 500 INTERNAL_SERVER_ERROR

### ISSUE THREAD

**Issue by fred-go** [Azure/azure-sdk-for-java#19973] opened 2021-03-19 10:58 UTC
Hi, We cannot delete a name with a "`" or "è" with an API call : 

2021-03-19T09:13:17.010176459Z 2021-03-19 09:13:17.009 DEBUG 124 --- [-nio-80-exec-21] .w.s.m.a.ResponseStatusExceptionResolver : Resolved [org.springframework.web.server.ResponseStatusException: 500 INTERNAL_SERVER_ERROR "error during SolutionPC delete : Failed to delete item; nested exception is CosmosClientException{error={"code":"Unauthorized","message":"null, StatusCode: Unauthorized","additionalErrorInfo":null}, resourceAddress='null', statusCode=401, message=null, StatusCode: Unauthorized, causeInfo=null, responseHeaders={Transfer-Encoding=chunked, Strict-Transport-Security=max-age=31536000, Server=Microsoft-HTTPAPI/2.0, Content-Location=https://pzbdcdtd01-francecentral.documents.azure.com/dbs/solutions/colls/postedetravail/docs/Ard%20Acc%C3%83%C2%A8s, x-ms-gatewayversion=version=2.11.0, Date=Fri, 19 Mar 2021 09:13:16 GMT, x-ms-activity-id=d79ddfe8-a8bf-47f1-ac1f-12184c0b082a, Content-Type=application/json}, requestHeaders={authorization=type%3Dmaster%26ver%3D1.0%26sig%3DExdjZ%2FlrVjm7Ejn%2FwNQYKOkjmPp8x8fIRnAzlGZG3OI%3D, Accept=application/json, x-ms-session-token=0:0#85231#15=-1, x-ms-date=Fri, 19 Mar 2021 09:13:16 GMT, x-ms-documentdb-partitionkey=["Ard Acc\u00E8s"], x-ms-consistency-level=Session}}"; nested exception is com.microsoft.azure.spring.data.cosmosdb.exception.CosmosDBAccessException: Failed to delete item; nested exception is CosmosClientException{error={"code":"Unauthorized","message":"null, StatusCode: Unauthorized","additionalErrorInfo":null}, resourceAddress='null', statusCode=401, message=null, StatusCode: Unauthorized, causeInfo=null, responseHeaders={Transfer-Encoding=chunked, Strict-Transport-Security=max-age=31536000, Server=Microsoft-HTTPAPI/2.0, Content-Location=https://pzbdcdtd01-francecentral.documents.azure.com/dbs/solutions/colls/postedetravail/docs/Ard%20Acc%C3%83%C2%A8s, x-ms-gatewayversion=version=2.11.0, Date=Fri, 19 Mar 2021 09:13:16 GMT, x-ms-activity-id=d79ddfe8-a8bf-47f1-ac1f-12184c0b082a, Content-Type=application/json}, requestHeaders={authorization=type%3Dmaster%26ver%3D1.0%26sig%3DExdjZ%2FlrVjm7Ejn%2FwNQYKOkjmPp8x8fIRnAzlGZG3OI%3D, Accept=application/json, x-ms-session-token=0:0#85231#15=-1, x-ms-date=Fri, 19 Mar 2021 09:13:16 GMT, x-ms-documentdb-partitionkey=["Ard Acc\u00E8s"], x-ms-consistency-level=Session}}]

2021-03-19T09:13:17.010716961Z 2021-03-19 09:13:17.010 DEBUG 124 --- [-nio-80-exec-21] o.s.web.servlet.DispatcherServlet        : Completed 500 INTERNAL_SERVER_ERROR

Arctifact JAVA use : 
    com.microsoft.azure:spring-data-cosmosdb:2.3.0
    org.springframework.boot:spring-boot-starter:2.3.7.RELEASE

**Comment by yiliuTo** [comment] 2021-03-24 02:23
Hi @kushagraThapar could you help to look into this issue? Thanks~

**Comment by kushagraThapar** [comment] 2021-03-24 05:42
@fred-go - I think the exception is a little bit misleading, but the real issue could be because of the characters "`" and "è" in the name of the items. Can you try deleting these items through azure cosmos db portal ?

**Comment by fred-go** [comment] 2021-04-14 07:28
Hi @kushagraThapar, I’m pretty sure it comes from the characters "`" and "è" in the name of the items.
Obviously I can remove these items through azure cosmos db portal but it's NOT a BUGFIX or a PATCH !!
Could you solve this issue please ?

**Comment by kushagraThapar** [comment] 2021-04-27 18:42
@fred-go - It is not a SDK issue, however the issue is at the backend service. Since these characters are not allowed in the names, but for some reason, they still went through the backend, and now when retrieving them / or deleting them, backend is throwing the exception. 

There is nothing that we can solve on the SDK side for these.

**Comment by kushagraThapar** [comment] 2021-06-03 17:17
@fred-go  - I am closing this issue, as mentioned above, this is not SDK issue. For more information, please take a look at this guide on how to delete those documents with invalid IDs - https://docs.microsoft.com/en-us/azure/cosmos-db/troubleshoot-not-found#invalid-character-in-an-item-id

**Closed by kushagraThapar** 2021-06-03 17:17 UTC
Labels: Cosmos, azure-spring-cosmos, customer-reported, question
