### ISSUE TITLE
Getting com.wm.util.ServerException: com.wm.app.b2b.server.InvokeException: java.lang.reflect.InvocationTargetException: Could not initialize class com.azure.identity.implementation.IdentityClient

### ISSUE THREAD

**Issue by naveen-dan** [Azure/azure-sdk-for-java#21702] opened 2021-05-20 23:24 UTC
I am trying to make a call to ADL using java code.

package TestAzure.Tester;

import com.wm.data.*;
import com.wm.util.Values;
import com.wm.app.b2b.server.Service;
import com.wm.app.b2b.server.ServiceException;
import com.azure.identity.ClientSecretCredential;
import com.azure.identity.ClientSecretCredentialBuilder;
import com.azure.storage.file.datalake.DataLakeServiceClientBuilder;
import com.azure.storage.file.datalake.DataLakeServiceClient;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import com.azure.storage.file.datalake.DataLakeFileSystemClient;
import com.azure.storage.file.datalake.DataLakeDirectoryClient;
import com.azure.storage.file.datalake.DataLakeFileClient;
import com.fasterxml.jackson.databind.cfg.MutableCoercionConfig;

public final class wMToAzureDataLake_SVC

{

	/** 
	 * The primary method for the Java service
	 *
	 * @param pipeline
	 *            The IData pipeline
	 * @throws ServiceException
	 */
	public static final void wMToAzureDataLake(IData pipeline) throws ServiceException {
		IDataCursor pipelineCursor = pipeline.getCursor();
		String	accountName = IDataUtil.getString( pipelineCursor, "accountName" );
		String	clientId = IDataUtil.getString( pipelineCursor, "clientId" );
		String	ClientSecret = IDataUtil.getString( pipelineCursor, "ClientSecret" );
		String	tenantID = IDataUtil.getString( pipelineCursor, "tenantID" );
		pipelineCursor.destroy();
		
		String endpoint = "https://abcdeededed.blob.core.windows.net";
		
		ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
		.clientId(clientId)
		.clientSecret(ClientSecret)
		.tenantId(tenantID)
		.build();
		
		// DataLakeServiceClientBuilder builder = new DataLakeServiceClientBuilder();
		// DataLakeServiceClient datalakeServiceClient = builder.credential(clientSecretCredential).endpoint(endpoint).buildClient();
		 
		 //Create a container
		 //DataLakeFileSystemClient fileSystemClient = datalakeServiceClient.createFileSystem("wMTest-file-system" + String.valueOf(System.currentTimeMillis()));
		 
		 //Create a directory
		 //DataLakeDirectoryClient directoryClient = fileSystemClient.createDirectory("wM-directory");
		 
		 //Create a file
		 //DataLakeFileClient fileClient = directoryClient.createFile("uploaded-file.txt");
		 //File file = new File("C:\\Users\\testusera\\mytestfile.txt");
		
		//   InputStream targetStream = new FileInputStream(file);
		 //IDataCursor pipelineCursor_1;
		
		 //try{
		//	 InputStream targetStream = new BufferedInputStream(new FileInputStream(file));
		// long fileSize = file.length();
		//	fileClient.append(targetStream, 0, fileSize);
		//	fileClient.flush(fileSize);
		//		pipelineCursor_1 = pipeline.getCursor();
		//	IDataUtil.put( pipelineCursor_1, "status", "Bussu" );
		//	IDataUtil.put( pipelineCursor_1, "statusMsg", "some status" );
		//	pipelineCursor_1.destroy();
		//} catch (Exception e){
		// System.out.println(e.getMessage());
		//	String status = "FAILED";
		//	pipelineCursor_1 = pipeline.getCursor();
		//	IDataUtil.put( pipelineCursor_1, "status", status );
		//	IDataUtil.put( pipelineCursor_1, "statusMsg", e.getMessage());
		//	pipelineCursor_1.destroy();
		//}
		
		 
			
	}
	
	// --- <<IS-BEGIN-SHARED-SOURCE-AREA>> ---
	
	
	
	// --- <<IS-END-SHARED-SOURCE-AREA>> ---

	final static wMToAzureDataLake_SVC _instance = new wMToAzureDataLake_SVC();

	static wMToAzureDataLake_SVC _newInstance() { return new wMToAzureDataLake_SVC(); }

	static wMToAzureDataLake_SVC _cast(Object o) { return (wMToAzureDataLake_SVC)o; }

}

I am trying to execute the first section but getting that error. I am writing this code from webmethods tool. I have the following jars imported.

azure-core-1.16.0.jar
azure-identity-1.3.0.jar
azure-storage-common-12.11.1.jar
azure-storage-file-datalake-12.5.1.jar
jackson-annotations-2.12.3.jar
jackson-core-2.12.3.jar
jackson-databind-2.12.3.jar
jackson-dataformat-xml-2.12.3.jar
jackson-datatype-jsr310-2.9.3.jar
msal4j-1.10.0.jar
jackson-databind-2.12.3-javadoc.jar
jackson-databind-2.12.3-sources.jar

Can someone please let me know if anything is missing.

**Comment by naveen-dan** [comment] 2021-05-20 23:25
This is the error I get:

com.wm.util.ServerException: com.wm.app.b2b.server.InvokeException: java.lang.reflect.InvocationTargetException: Could not initialize class com.azure.identity.implementation.IdentityClient

**Comment by joshfree** [comment] 2021-05-24 17:22
Hi @naveen-dan this is a dependency conflict issue caused by using mismatched versions of SDKs together.  @alzimmermsft can you please point @naveen-dan to the BOM and guidance on matching SDK versions.

**Comment by naveen-dan** [comment] 2021-05-24 19:19
Thanks @joshfree. @alzimmermsft if you can point us to the right ones, that will be really helpful. Right now, we're stuck and no where to go, appreciate any quick response. thanks again!

**Comment by naveen-dan** [comment] 2021-05-25 13:44
@alzimmermsft @joshfree any guidance here pls, can you please point to the right jars where we can download. our tasks have been blocked due to this.

**Comment by alzimmermsft** [comment] 2021-05-25 15:45
Hi @naveen-dan, this is our [Getting Started Guide](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/boms/azure-sdk-bom#getting-started) on using `azure-sdk-bom` as a dependency management mechanism for Java Azure SDKs. `azure-sdk-bom` is comprised of production ready, GA'd Azure SDKs as well as common dependencies used by the SDKs such as Jackson, Netty, and Reactor. `azure-sdk-bom`, currently, doesn't ship at the same cadence that stand-alone SDKs do, instead it is shipping on a periodic cycle. So, the dependencies managed by it may trail the latest available SDKs, we are actively working on shipping more often and should have a new version shipped in the next few weeks.

Based on the dependencies you mentioned above, the following would be the POM configuration. 

```xml
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-sdk-bom</artifactId>
      <version>1.0.3</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>

<dependencies>
  <dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-core</artifactId>
  </dependency>

  <dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-identity</artifactId>
  </dependency>

  <dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-storage-common</artifactId>
  </dependency>

  <dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-storage-file-datalake</artifactId>
  </dependency>

  <dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-annotations</artifactId>
  </dependency>

  <dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-core</artifactId>
  </dependency>

  <dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-databind</artifactId>
  </dependency>

  <dependency>
    <groupId>com.fasterxml.jackson.dataformat</groupId>
    <artifactId>jackson-dataformat-xml</artifactId>
  </dependency>

  <dependency>
    <groupId>com.fasterxml.jackson.datatype</groupId>
    <artifactId>jackson-datatype-jsr310</artifactId>
  </dependency>

  <dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>msal4j</artifactId>
  </dependency>
</dependencies>
```

**Comment by naveen-dan** [comment] 2021-05-25 16:10
@alzimmermsft  Thank you, so just want to know that our application can only accept jars. So, I want to know if there is any jar missing from my end? Is this artifactId       <artifactId>azure-sdk-bom</artifactId> some kind of a jar?

**Comment by alzimmermsft** [comment] 2021-05-25 17:12
@naveen-dan by "our application can only accept JARs" do you mean that it is creating a bundled JAR containing all dependencies or that the application is configured based on JARs injected into the classpath?

**Comment by naveen-dan** [comment] 2021-05-25 17:15
@alzimmermsft : we have to inject all the dependant jars in a common place so that the server during runtime will read them. can you let me know your suggestions on getting the jars if anything is missing.

**Comment by alzimmermsft** [comment] 2021-05-25 19:05
@naveen-dan leveraging a Maven POM with configurations similar to what I posted above and running the following command will download all JARs required by a project during runtime into its relative folder `/target/dependency`.

```
mvn -f <path to pom> dependency:copy-dependencies -DincludeScope=compile
```

**Comment by naveen-dan** [comment] 2021-06-01 16:53
@alzimmermsft : In my case, our application doesn't allow maven setup, is there a way you can point to the jars or attach all the jars here?

**Comment by alzimmermsft** [comment] 2021-06-01 23:27
Hi @naveen-dan, sure I can post all of the transitive dependencies used based on the configuration I gave above. 

Using

```
azure-core-1.16.0.jar
azure-identity-1.3.0.jar
azure-storage-common-12.11.1.jar
azure-storage-file-datalake-12.5.1.jar
```

I resolved the following runtime dependencies:

```
com.azure:azure-core-http-netty:jar:1.9.2
com.azure:azure-core:jar:1.16.0
com.azure:azure-identity:jar:1.3.0
com.azure:azure-storage-blob:jar:12.11.1
com.azure:azure-storage-common:jar:12.11.1
com.azure:azure-storage-file-datalake:jar:12.5.1
com.azure:azure-storage-internal-avro:jar:12.0.4
com.fasterxml.jackson.core:jackson-annotations:jar:2.12.2
com.fasterxml.jackson.core:jackson-core:jar:2.12.2
com.fasterxml.jackson.core:jackson-databind:jar:2.12.2
com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.12.2
com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.12.2
com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.12.2
com.fasterxml.woodstox:woodstox-core:jar:6.2.4
com.fasterxml:aalto-xml:jar:1.0.0
com.github.stephenc.jcip:jcip-annotations:jar:1.0-1
com.google.guava:guava:jar:19.0
com.madgag.spongycastle:core:jar:1.54.0.0
com.microsoft.azure:msal4j-persistence-extension:jar:1.1.0
com.microsoft.azure:msal4j:jar:1.10.0
com.nimbusds:content-type:jar:2.1
com.nimbusds:lang-tag:jar:1.5
com.nimbusds:nimbus-jose-jwt:jar:9.8.1
com.nimbusds:oauth2-oidc-sdk:jar:9.4
commons-codec:commons-codec:jar:1.10
io.netty:netty-buffer:jar:4.1.63.Final
io.netty:netty-codec-dns:jar:4.1.63.Final
io.netty:netty-codec-http2:jar:4.1.63.Final
io.netty:netty-codec-http:jar:4.1.63.Final
io.netty:netty-codec-socks:jar:4.1.63.Final
io.netty:netty-codec:jar:4.1.63.Final
io.netty:netty-common:jar:4.1.63.Final
io.netty:netty-handler-proxy:jar:4.1.63.Final
io.netty:netty-handler:jar:4.1.63.Final
io.netty:netty-resolver-dns-native-macos:jar:osx-x86_64:4.1.63.Final
io.netty:netty-resolver-dns:jar:4.1.63.Final
io.netty:netty-resolver:jar:4.1.63.Final
io.netty:netty-tcnative-boringssl-static:jar:2.0.38.Final
io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.63.Final
io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.63.Final
io.netty:netty-transport-native-unix-common:jar:4.1.63.Final
io.netty:netty-transport:jar:4.1.63.Final
io.projectreactor.netty:reactor-netty-core:jar:1.0.6
io.projectreactor.netty:reactor-netty-http:jar:1.0.6
io.projectreactor.netty:reactor-netty:jar:1.0.6
io.projectreactor:reactor-core:jar:3.4.5
jakarta.activation:jakarta.activation-api:jar:1.2.1
jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.2
net.java.dev.jna:jna-platform:jar:5.6.0
net.java.dev.jna:jna:jar:5.5.0
net.minidev:accessors-smart:jar:2.4.2
net.minidev:json-smart:jar:2.4.2
org.apache.httpcomponents:httpcore:jar:4.4.5
org.codehaus.woodstox:stax2-api:jar:4.2.1
org.jetbrains:annotations:jar:15.0
org.linguafranca.pwdb:KeePassJava2-dom:jar:2.1.4
org.linguafranca.pwdb:KeePassJava2-jaxb:jar:2.1.4
org.linguafranca.pwdb:KeePassJava2-kdb:jar:2.1.4
org.linguafranca.pwdb:KeePassJava2-kdbx:jar:2.1.4
org.linguafranca.pwdb:KeePassJava2-simple:jar:2.1.4
org.linguafranca.pwdb:KeePassJava2:jar:2.1.4
org.linguafranca.pwdb:database:jar:2.1.4
org.ow2.asm:asm:jar:8.0.1
org.reactivestreams:reactive-streams:jar:1.0.3
org.simpleframework:simple-xml:jar:2.7.1
org.slf4j:slf4j-api:jar:1.7.30
stax:stax-api:jar:1.0.1
stax:stax:jar:1.2.0
xpp3:xpp3:jar:1.1.3.3
```

The most notable difference compared to the dependencies listed above is

```
com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.12.2
```

compared to

```
com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.9.3
```

as listed above.

**Comment by naveen-dan** [comment] 2021-06-02 15:13
@alzimmermsft so these 4 jars are enough to resolve the 

com.wm.util.ServerException: com.wm.app.b2b.server.InvokeException: java.lang.reflect.InvocationTargetException: Could not initialize class com.azure.identity.implementation.IdentityClient


azure-core-1.16.0.jar
azure-identity-1.3.0.jar
azure-storage-common-12.11.1.jar
azure-storage-file-datalake-12.5.1.jar

Even after downloading all these jars, I am still getting the same error. So, not sure what is missing.

**Comment by alzimmermsft** [comment] 2021-06-03 21:54
This looks to be similar to this issue #22028, I will continue investigating and will reply back to both once I've root caused the problem.

**Comment by alzimmermsft** [comment] 2021-06-04 23:57
Hi @naveen-dan, are there other dependencies such as Spring in your application? #22028 was resolved with a few dependency changes, but it was using Spring. Using a Maven configuration of the four dependencies you listed I wasn't able to replicate the exceptions you are seeing.

**Closed** 2021-08-25 08:02 UTC
Labels: question, Client, Azure.Core, customer-reported, needs-author-feedback, no-recent-activity, dependency-issue
