### ISSUE TITLE
[QUERY] - SBQ CBS Token Timeouts

### ISSUE THREAD

**Issue by pete-carey** [Azure/azure-sdk-for-java#12044] opened 2020-06-10 15:46 UTC
## Actual Behavior
We're running load testing, and have six micro-services listening to a set of SBQs, which are defined as endpoints in our IoT hub. Two of these services have recently been stuck in an exception loop of the form:
```2020-06-10 14:58:23 [pool-9-thread-3] INFO  c.m.a.s.p.RequestResponseLink - Request with id:request:27635 timed out
2020-06-10 14:58:23 [pool-8-thread-3460] INFO  c.m.a.s.primitives.MessagingFactory - Sending CBS Token for amqp://[redacted].servicebus.windows.net/[redacted] failed.
com.microsoft.azure.servicebus.primitives.TimeoutException: Request timed out.
	at com.microsoft.azure.servicebus.primitives.RequestResponseLink.lambda$scheduleRequestTimeout$11(RequestResponseLink.java:442)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-06-10 14:58:23 [pool-8-thread-3460] INFO  c.m.a.s.primitives.MessagingFactory - Will retry sending CBS Token for amqp://[redacted].servicebus.windows.net/[redacted] after 5 seconds.
```
Does this mean that the SBQ in the stack trace is inaccessible to the service on which these exceptions are occurring? Obviously it's a timeout issue, but the other queues listened to by this service are currently unaffected. We've been happily using the IoT Hub and SBQs for quite some time now, and I've never seen this.

Any help on this would be greatly appreciated!

## Expected Behavior
1. We don't see this exception, every 5 seconds, in the logs.

## Versions  
- OS platform and version: Debian Slim 10.3 (base docker image)
- Maven package version or commit ID: Azure Service Bus 3.2.0
```java -version
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)
```

**Comment by axisc** [comment] 2020-06-30 23:44
@pete-carey Thanks for raising this issue. 
Could you share for how long does the issue persists? Does it only resolve once the service has been restarted?

**Comment by chutch1122** [comment] 2020-08-05 23:55
@axisc 

I am seeing a similar issue with `com.microsoft.azure:azure-servicebus:3.4.0`

The issue is only resolved once the service has been restarted.

```
2020-08-05T23:51:23.888917586Z 2020-08-05 23:51:23.888  INFO 123 --- [pool-3-thread-4] c.m.a.s.primitives.CoreMessageReceiver   : No messages received from '[redacted]'. Pending receive request timed out. Returning null to the client.
2020-08-05T23:51:23.889901830Z 2020-08-05 23:51:23.889 DEBUG 123 --- [ool-2-thread-26] c.m.a.servicebus.MessageAndSessionPump   : Receive from entity '[redacted]' returned no messages.


2020-08-05T23:51:32.342430198Z 2020-08-05 23:51:32.342  INFO 123 --- [pool-3-thread-4] c.m.a.s.primitives.RequestResponseLink   : Request with id:request:77 timed out
2020-08-05T23:51:32.351623180Z 2020-08-05 23:51:32.351  INFO 123 --- [ool-2-thread-22] c.m.a.s.primitives.MessagingFactory      : Sending CBS Token for amqp://[redacted].servicebus.windows.net/[redacted] failed.
2020-08-05T23:51:32.351666183Z
2020-08-05T23:51:32.351673684Z com.microsoft.azure.servicebus.primitives.TimeoutException: Request timed out.
2020-08-05T23:51:32.351678584Z  at com.microsoft.azure.servicebus.primitives.RequestResponseLink.lambda$scheduleRequestTimeout$11(RequestResponseLink.java:442) ~[azure-servicebus-3.4.0.jar!/:na]
2020-08-05T23:51:32.351683484Z  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_232]
2020-08-05T23:51:32.351687885Z  at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_232]
2020-08-05T23:51:32.351692385Z  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_232]
2020-08-05T23:51:32.351696985Z  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_232]
2020-08-05T23:51:32.351701385Z  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_232]
2020-08-05T23:51:32.351705686Z  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_232]
2020-08-05T23:51:32.351709886Z  at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_232]
2020-08-05T23:51:32.351714686Z
2020-08-05T23:51:32.352298323Z 2020-08-05 23:51:32.352  INFO 123 --- [ool-2-thread-22] c.m.a.s.primitives.MessagingFactory      : Will retry sending CBS Token for amqp://[redacted].servicebus.windows.net/[redacted] after 5 seconds.
```

**Comment by dariohvega** [comment] 2020-09-24 15:19
Hi guys! 
I have the same issue. Did you find a workaround for this?
Regards!

**Comment by yvgopal** [comment] 2021-11-18 06:16
@pete-carey A timeout may occur when a gateway node on the service is rebooting or a connection attempt times out. But timeouts shouldn't persist. Did the timeouts continue in your case? If so, how long did they continue? Did it not recover until your application is restarted?
@chutch1122 Thanks for capturing the logs. Is this still happening? If so, could you capture DEBUG level logs during the time and attach them to this issue?

If your application doesn't recover from this timeouts, it is likely a bug. I fixed a race condition causing this long time ago. But I haven't see this kind of bug in a long time with Track 1 SDK. Could you guys try with the latest version of the SDK? If you run into the issue again, please add repro steps and upload traces. Without a repro/traces, I can't do much. I have assigned this to myself and closing it for now. If you have a repro and/or traces, please reopen the issue.

**Closed by yvgopal** 2021-11-18 06:16 UTC
Labels: question, Service Bus, Service Attention, Client, customer-reported, needs-team-attention, Track 1
