### ISSUE TITLE
[FEATURE REQ] Provide a health indicator for Service Bus Spring starter

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#21976] opened 2021-06-01 06:14 UTC
### Context
In Spring Cloud Azure 4.0, we added a starter for Azure Service Bus. Each client should have one health indicator for it, and it's the same for the Service Bus clients.

### Goal
 With this health indicator, users shall be able to check the health status of Service Bus clients.

**Comment by saragluna** [comment] 2021-06-01 06:15
closing in favor of #21544.

**Comment by saragluna** [comment] 2021-09-28 06:22
Reopen it for the Service Bus health indicator hasn't been added for auto-configuration.

**Comment by saragluna** [comment] 2021-11-18 02:16
@yiliuTo there's no health indicator for level 1 service bus SDK client.

**Comment by saragluna** [comment] 2021-11-24 02:04
The service bus sdk client doesn't expose any interfaces for us to check the status of it, so putting this issue to backlog.

**Comment by saragluna** [comment] 2022-02-21 00:52
https://github.com/Azure/azure-sdk-for-net/issues/8561

**Comment by stliu** [comment] 2022-11-22 15:58
https://github.com/Azure/azure-sdk-for-java/issues/30507

**Comment by AndreasPetersen** [comment] 2022-12-30 08:20
I'm sorry, I'm a bit confused with all these issues being linked throughout.

Is it possible to get health indicators through the service bus clients, or is this still in the backlog?

**Comment by saragluna** [comment] 2023-01-03 01:48
Sorry @AndreasPetersen, it's still in the backlog. We will look into the tracing implementation in #30507 to see whether it can provide the health info, but this task is a lower priority now.

**Comment by AndreasPetersen** [comment] 2023-04-24 13:18
I see that #30507, being marked as a duplicate of #26269 which is also closed as completed. Where does that leave this issue?

**Comment by saragluna** [comment] 2023-04-25 02:20
The tracer will collect information whenever sending or receiving messages, but what if an application with a sender or receiver but has no messages flowing, should we consider the application is healthy? So for a health indicator we should not depend on the messages flowing on the connection, metrics like active connection might be more suitable in this case.

**Comment by AndreasPetersen** [comment] 2023-07-31 10:54
Would it be possible to send a ping message to check the health of the connection? The lack of a health indicator is a huge issue for us given https://github.com/Azure/azure-sdk-for-java/issues/34588 .

**Comment by Netyyyy** [comment] 2023-08-03 07:12
Hi @AndreasPetersen , the service bus sdk client doesn't expose any interfaces for us to check the status of it, so it's still blocked.

**Comment by AndreasPetersen** [comment] 2023-08-03 07:15
> Hi @AndreasPetersen , the service bus sdk client doesn't expose any interfaces for us to check the status of it, so it's still blocked.

Thank you for the reply @Netyyyy . Is there an issue on exposing any such interfaces?

**Comment by Netyyyy** [comment] 2023-08-03 08:14
> > Hi @AndreasPetersen , the service bus sdk client doesn't expose any interfaces for us to check the status of it, so it's still blocked.
> 
> Thank you for the reply @Netyyyy . Is there an issue on exposing any such interfaces?

Sorry, I have no idea about that. Maybe @anuchandy could help you.

**Closed** 2024-03-18 18:04 UTC
Labels: Client, feature-request, azure-spring, azure-spring-servicebus, azure-spring-boot
