### ISSUE TITLE
[QUERY] Cosmos Query Metrics No Longer Logged

### ISSUE THREAD

**Issue by azizabah** [Azure/azure-sdk-for-java#31238] opened 2022-09-30 19:02 UTC
**Query/Question**
In versions of the SDK before migration to com.azure.spring:spring-cloud-azure-dependencies:4.0.0, when we set the appropriate property azure.cosmos.populate-query-metrics to true, we would see the query metrics outputted in the logs. 

After migrating to the above listed version and setting the property of spring.cloud.azure.cosmos.populate-query-metrics to true, we are not seeing the query metrics outputted in the log.

Where did they go / how do we easily access them during development?

***Why is this not a Bug or a feature Request?***
Most likely a configuration or logging issue on our end.

**Setup (please complete the following information if applicable):**
 - OS: MacOS + Linux
 - IDE: IntelliJ
 - Library/Libraries: com.azure.spring:spring-cloud-azure-dependencies:4.0.0, com.azure.spring:spring-cloud-azure-starter-data-cosmos, Spring Boot 2.6.7.
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Setup information Added

**Comment by kushagraThapar** [comment] 2022-10-03 18:01
@saragluna  can someone from your team take a look at this?
@azizabah - after setting the populate-query-metrics flag, are you still instantiating the `ResponseDiagnosticsProcessor`? Since that is the implementation which will log the diagnostics which contain query metrics.

**Comment by azizabah** [comment] 2022-10-03 18:46
@kushagraThapar - We didn't change anything on our code related to that (AFAIK) so was that instantiation being done for us as part of the auto config and it no longer is?

**Comment by kushagraThapar** [comment] 2022-10-03 20:53
@azizabah - yeah that's what I wanted to confirm. Looks like something changed in the new spring version which is affecting the instantiation. @saragluna  will follow up on this, thanks!

**Comment by saragluna** [comment] 2022-10-09 08:15
@azizabah sorry for the delayed response due to our National Holiday. I will look into it.

**Comment by Netyyyy** [comment] 2022-10-17 07:41
Hi @azizabah , thanks for reporting this, I reproduced your problem when migrating from 3.14.0 to 4.0.0 without any codes changes, it was caused by missing `ResponseDiagnosticsProcessor` bean, but I'm not sure if it is the same reason for your problem.

Here is a temporary solution to this problem, add the following class to your codes:
```java
import com.azure.spring.data.cosmos.core.ResponseDiagnostics;
import com.azure.spring.data.cosmos.core.ResponseDiagnosticsProcessor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

@Component
public class MyResponseDiagnosticsProcessor implements ResponseDiagnosticsProcessor {

    private static final Logger LOGGER = LoggerFactory.getLogger(MyResponseDiagnosticsProcessor.class);
    @Override
    public void processResponseDiagnostics(ResponseDiagnostics responseDiagnostics) {
        LOGGER.info("Response Diagnostics {}", responseDiagnostics);
    }
}
```
Could you please help to try this solution? If it works, we will fix it in the next release. If it doesn't work, please help with more detailed codes and info, thanks!

**Comment by azizabah** [comment] 2022-10-17 14:03
@Netyyyy - That worked perfectly when I added it in.

**Comment by Netyyyy** [comment] 2022-10-18 00:21
> @Netyyyy - That worked perfectly when I added it in.

Thanks, it will be fixed in the next release and the temporary code can be deleted normally.

**Closed by Netyyyy** 2022-10-18 00:21 UTC
Labels: question, Cosmos, Client, customer-reported, needs-team-attention, azure-spring-cosmos
