### ISSUE TITLE
Downloading the Azure container in samples with v12 using SAS token is missing

### ISSUE THREAD

**Issue by samrajcse** [Azure/azure-sdk-for-java#7761] opened 2020-01-28 08:22 UTC
Hi Team,

I got a eDiscovery export information with container URL and SAS token. I am trying to use v12 java SDK and I don't find complete guidance to download the entire container. Please guide US to download entire blob storage container. Need more documentation for v12.

Eg.:I have below Container URL and SAS token (Credentials masked)
"Container url: https://accnamefromsecandcompliance.blob.core.windows.net/f8aa5c1d-0d05-4a4c-b813-081234567890; SAS token: ?sv=2014-02-14&sr=c&si=eDiscoveryBlobPolicy9%7C0&sig=<someToken>;

**Comment by gapra-msft** [comment] 2020-01-28 17:43
Hi @samrajcse 

We have samples on how to use a SAS token, list containers, and download blobs in our [README](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/README.md). In addition we also provide [samples ](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-blob/src/samples)in the repo. 

Let me know in case you need further guidance.

**Comment by samrajcse** [comment] 2020-01-28 18:54
Hi Gauri,

I hope you have seen my example. Those sad token and container url was
taken at the time of secuirty and compliance export. I can't able to
download via Java API. When I am trying to do listblob it throws object not
found error.

**Comment by gapra-msft** [comment] 2020-01-28 19:26
Hi @samrajcse,

Could you please provide a code sample of what you're trying to do?

**Comment by samrajcse** [comment] 2020-01-29 01:56
Hi Gauri,

Please find the snippet and error log. Error log occurred at the time of
iteration in foreach. As i told you I have got this value from security and
compliance export and I am trying to download via API instead of
unfiedexportclient.exe

*Snippet*:

BlobServiceClient storageClient = new
BlobServiceClientBuilder().endpoint("https://<accid>.blob.core.windows.net
").sasToken("hHSpqVUfHfZYTftZSWr5RaqedkZwk=").buildClient();

BlobContainerClient blobContainerClient =
storageClient.getBlobContainerClient("f8aa5c1d-0d05-4a4c-b813-12344444");

PagedIterable<BlobItem> blobs = blobContainerClient.listBlobs();
blobs.forEach(blob -> {
System.out.println("Name: "+blob.getName() );
});



*Error log:*

com.azure.storage.blob.models.BlobStorageException: Status code 404,
"?<?xml version="1.0"
encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The
specified resource does not exist.
RequestId:1beb2aa3-c01e-0050-7846-d62427000000
Time:2020-01-29T01:53:16.7850498Z</Message></Error>"
Regards,
*SAMRAJ.K*

**Comment by gapra-msft** [comment] 2020-01-29 17:37
Hi @samrajcse , The SAS token you provide in the .sasToken() method needs to be the full SAS token, including the signed version and resource. From your code snippet it looks like you're providing only the sig part.

**Comment by samrajcse** [comment] 2020-01-30 02:27
Hi Gowri,

I already tried like this and I am not getting authenticated. Here is how i
provided.

.sasToken("sv=2014-02-14&sr=c&si=eDiscoveryBlobPolicy9|0&sig=hHSpqVUf8KeX8Xjz5RaqedkZwk=")

Error log:
http-nio-1] reactor.netty.resources.PooledConnectionProvider 254- [id:
0xcdb85e0b, L:/192.168.0.102:62015 - R:
argiediscnam.blob.core.windows.net/40.116.232.96:443] Channel cleaned, now
0 active connections and 1 inactive connections
com.azure.storage.blob.models.BlobStorageException: Status code 403,
"?<?xml version="1.0"
encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server
failed to authenticate the request. Make sure the value of Authorization
header is formed correctly including the signature.
RequestId:114ad90e-401e-004a-7714-d70b48000000
Time:2020-01-30T02:25:24.6341832Z</Message><AuthenticationErrorDetail>Signature
fields not well formed.</AuthenticationErrorDetail></Error>"



Regards,
*SAMRAJ.K*

**Comment by gapra-msft** [comment] 2020-01-30 18:53
@samrajcse 
I noticed that in your original post the | character in the si component of the SAS token was URL encoded, however in your latest post it looks like you're passing it in the raw form. 

This error indicates that the service is unable to recognize your sas token due to the addition of the | character.

**Comment by gapra-msft** [comment] 2020-02-05 21:42
Hi @samrajcse 

Were you able to download the blobs in your container?

**Comment by samrajcse** [comment] 2020-02-06 05:52
Hi Gauri,
Thanks for your help. I can able to listdown and download the blobs. But I
can't able to convert that blob to real files. in 8.x we have cloud blob
object conversion. But in 12.x api i can't able to get the original emails
and csv report from blob object. Any example to download real files or
objects?.

Regards,
*SAMRAJ.K*

**Comment by gapra-msft** [comment] 2020-02-06 17:07
@samrajcse 
Does [this](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/src/samples/java/com/azure/storage/blob/FileTransferExample.java) sample help?

Part of the sample shows you how to use the downloadToFile API that we offer on blobs, which seems like your use case. 

Let me know if this helps.

**Comment by samrajcse** [comment] 2020-02-07 13:13
Hi Gowri,

I have already tried and it downloads only metadata file. Here is the
sample code and results.

BlobServiceClient storageClient = new BlobServiceClientBuilder().endpoint("
https://argiediscnam.blob.core.windows.net
").sasToken("sv=2014-02-14&sr=c&si=eDiscoveryBlobPolicy9%7C0&sig=hHSpqVUf8KeX8XHfZYTftZSWrZh%2BzNCjz5RaqedkZwk%3D").buildClient();

BlobContainerClient blobContainerClient =
storageClient.getBlobContainerClient("f8aa5c1d-0d05-4a4c-b813-08d7a321a389");

PagedIterable<BlobItem> blobs = blobContainerClient.listBlobs();
BlobClient blobClient = null;
for (BlobItem blobItem : blobs) {

blobClient = blobContainerClient.getBlobClient(blobItem.getName());//
.getProperties().getBlobSequenceNumber());

if (blobClient != null) {
// blobClient.openInputStream();
BlobProperties blobProperties = blobClient.getProperties();

String filePath="D:\\tempz\\Tempz\\1\\" + blobItem.getName();
FileUtils.forceMkdirParent(new File(filePath));

String bloburl=blobClient.getBlobUrl();

System.out.println(bloburl + " - " + blobProperties.getBlobType().name());
}
}


Result:

https://argiediscnam.blob.core.windows.net/f8aa5c1d-0d05-4a4c-b813-08d7a321a389/data%2FAll%2FRoot.meta
- BLOCK_BLOB
https://argiediscnam.blob.core.windows.net/f8aa5c1d-0d05-4a4c-b813-08d7a321a389/data%2FExchange%2FRoot.meta
- BLOCK_BLOB
https://argiediscnam.blob.core.windows.net/f8aa5c1d-0d05-4a4c-b813-08d7a321a389/data%2Ffef4d86e-8eb0-4b89-927b-46a91b498d76%2FFLDR1369375761697341441%2FFolder.meta
- BLOCK_BLOB
https://argiediscnam.blob.core.windows.net/f8aa5c1d-0d05-4a4c-b813-08d7a321a389/data%2Ffef4d86e-8eb0-4b89-927b-46a91b498d76%2FFLDR2162009296114548737%2FFolder.meta
- BLOCK_BLOB
https://argiediscnam.blob.core.windows.net/f8aa5c1d-0d05-4a4c-b813-08d7a321a389/data%2Ffef4d86e-8eb0-4b89-927b-46a91b498d76%2FFLDR2234066890152476673%2FFolder.meta
- BLOCK_BLOB
https://argiediscnam.blob.core.windows.net/f8aa5c1d-0d05-4a4c-b813-08d7a321a389/data%2Ffef4d86e-8eb0-4b89-927b-46a91b498d76%2FFLDR2522297266304188417%2FFolder.meta
- BLOCK_BLOB
https://argiediscnam.blob.core.windows.net/f8aa5c1d-0d05-4a4c-b813-08d7a321a389/data%2Ffef4d86e-8eb0-4b89-927b-46a91b498d76%2FFLDR5764888998010945537%2FFolder.meta
- BLOCK_BLOB
https://argiediscnam.blob.core.windows.net/f8aa5c1d-0d05-4a4c-b813-08d7a321a389/data%2Ffef4d86e-8eb0-4b89-927b-46a91b498d76%2FFLDR576742227280134145%2FFolder.meta
- BLOCK_BLOB
https://argiediscnam.blob.core.windows.net/f8aa5c1d-0d05-4a4c-b813-08d7a321a389/data%2Ffef4d86e-8eb0-4b89-927b-46a91b498d76%2FFLDR5836946592048873473%2FFolder.meta
- BLOCK_BLOB
https://argiediscnam.blob.core.windows.net/f8aa5c1d-0d05-4a4c-b813-08d7a321a389/data%2Ffef4d86e-8eb0-4b89-927b-46a91b498d76%2FFLDR720857415355990017%2FFolder.meta
- BLOCK_BLOB
https://argiediscnam.blob.core.windows.net/f8aa5c1d-0d05-4a4c-b813-08d7a321a389/data%2Ffef4d86e-8eb0-4b89-927b-46a91b498d76%2FFLDR72339069014638593%2FFolder.meta
- BLOCK_BLOB
https://argiediscnam.blob.core.windows.net/f8aa5c1d-0d05-4a4c-b813-08d7a321a389/data%2Ffef4d86e-8eb0-4b89-927b-46a91b498d76%2FFLDR864972603431845889%2FFolder.meta
- BLOCK_BLOB
https://argiediscnam.blob.core.windows.net/f8aa5c1d-0d05-4a4c-b813-08d7a321a389/data%2Ffef4d86e-8eb0-4b89-927b-46a91b498d76%2FFLDRBatch%2FFolder.meta
- BLOCK_BLOB
https://argiediscnam.blob.core.windows.net/f8aa5c1d-0d05-4a4c-b813-08d7a321a389/data%2Ffef4d86e-8eb0-4b89-927b-46a91b498d76%2FHeartbeat.meta
- BLOCK_BLOB
https://argiediscnam.blob.core.windows.net/f8aa5c1d-0d05-4a4c-b813-08d7a321a389/data%2Ffef4d86e-8eb0-4b89-927b-46a91b498d76%2FRoot.meta
- BLOCK_BLOB
https://argiediscnam.blob.core.windows.net/f8aa5c1d-0d05-4a4c-b813-08d7a321a389/lease%2F399.meta
- BLOCK_BLOB
https://argiediscnam.blob.core.windows.net/f8aa5c1d-0d05-4a4c-b813-08d7a321a389/lease%2F482.meta
- BLOCK_BLOB
https://argiediscnam.blob.core.windows.net/f8aa5c1d-0d05-4a4c-b813-08d7a321a389/lease%2F609.meta
- BLOCK_BLOB
https://argiediscnam.blob.core.windows.net/f8aa5c1d-0d05-4a4c-b813-08d7a321a389/lease%2F897.meta
- BLOCK_BLOB
https://argiediscnam.blob.core.windows.net/f8aa5c1d-0d05-4a4c-b813-08d7a321a389/metadata%2Ffef4d86e-8eb0-4b89-927b-46a91b498d76%2FFLDRBatch%2FBATCH0000%2FMSG0.batch
- BLOCK_BLOB
https://argiediscnam.blob.core.windows.net/f8aa5c1d-0d05-4a4c-b813-08d7a321a389/metadata%2Ffef4d86e-8eb0-4b89-927b-46a91b498d76%2FFLDRBatch%2FBATCH0000%2FMSG1.batch
- BLOCK_BLOB
https://argiediscnam.blob.core.windows.net/f8aa5c1d-0d05-4a4c-b813-08d7a321a389/status%2Ffef4d86e-8eb0-4b89-927b-46a91b498d76%2F637157237478063616.meta
- BLOCK_BLOB
https://argiediscnam.blob.core.windows.net/f8aa5c1d-0d05-4a4c-b813-08d7a321a389/status%2Ffef4d86e-8eb0-4b89-927b-46a91b498d76%2F637157237500181161.meta
- BLOCK_BLOB
https://argiediscnam.blob.core.windows.net/f8aa5c1d-0d05-4a4c-b813-08d7a321a389/status%2Ffef4d86e-8eb0-4b89-927b-46a91b498d76%2F637157237524137675.meta
- BLOCK_BLOB
https://argiediscnam.blob.core.windows.net/f8aa5c1d-0d05-4a4c-b813-08d7a321a389/status%2Ffef4d86e-8eb0-4b89-927b-46a91b498d76%2FCompleted.meta
- BLOCK_BLOB
https://argiediscnam.blob.core.windows.net/f8aa5c1d-0d05-4a4c-b813-08d7a321a389/status%2Ffef4d86e-8eb0-4b89-927b-46a91b498d76%2FStarted.meta
- BLOCK_BLOB

[image: image.png]

[image: image.png]
Regards,
*SAMRAJ.K*

**Comment by gapra-msft** [comment] 2020-02-07 23:50
Hi @samrajcse 

I might be missing something but from the snippet you provided has no call to `BlobClient.downloadToFile(filePath)`

If you replace `FileUtils.forceMkdirParent(new File(filePath));` with `blobClient.downloadToFile(filePath);`,
it should work.

**Comment by samrajcse** [comment] 2020-02-08 06:52
Sorry I have unfortunately removed that line while removing commented code.
I have this like only. But nothing works. Only metadata file is
downloading. How can i download the BLOCK_BLOB object to regular file?

FileUtils.forceMkdirParent(new File(filePath));
blobClient.downloadToFile(filePath);
Regards,
*SAMRAJ.K*

**Comment by rickle-msft** [comment] 2020-02-10 19:21
@samrajcse Can you please explain what you mean by "metadata file"? We don't really have a concept of a metadata file in the SDK or on the service, so I'm not exactly sure what you're seeing.

From the couple lines you shared in your last comment, it looks like you are creating the local file before downloading it. The download to file method actually expects to create the local file for you, and unless you give it specific permission to overwrite the local file, it will fail. Can you please either specify overwrite=true in your download to file call or remove the line that creates the file before the download and let us know if that changes anything?

**Comment by samrajcse** [comment] 2020-02-14 13:32
Hi Rick,

I can explain my use case. I have created a eDisocovery export and I am
trying to download the file using Java API. I have SAS token and endpoint
URL. I am using below code with Azure storage v12 api and it is downloading
the file as simple metadata file and original files are not downloading.
How can I download the original export file that contain pst and other
files?

*Code sample:*

BlobServiceClient storageClient = new BlobServiceClientBuilder().endpoint("
https://argiediscnam.blob.core.windows.net
").sasToken("sv=2014-02-14&sr=c&si=eDiscoveryBlobPolicy9%7C0&sig=hHSpqVUf8KeX8XHfZYTftZSWrZh%2BzNCjz5RaqedkZwk%3D").buildClient();

BlobContainerClient blobContainerClient =
storageClient.getBlobContainerClient("f8aa5c1d-0d05-4a4c-b813-08d7a321a389");
/*
* BlobListDetails blobListDetails = new BlobListDetails();
blobListDetails.setRetrieveCopy(true);
blobListDetails.setRetrieveDeletedBlobs(true);
blobListDetails.setRetrieveMetadata(true);
blobListDetails.setRetrieveSnapshots(true);
blobListDetails.setRetrieveUncommittedBlobs(true); ListBlobsOptions
blobsOptions = new ListBlobsOptions();
blobsOptions.setDetails(blobListDetails);
blobsOptions.setMaxResultsPerPage(10); // PagedIterable<BlobItem> blobList
= blobContainerClient.listBlobs(blobsOptions, Duration.ofMinutes(1)); //
System.out.println(blobList);
System.out.println(blobContainerClient.getAccessPolicy().toString());
*/
PagedIterable<BlobItem> blobs = blobContainerClient.listBlobs();
BlobClient blobClient = null;
for (BlobItem blobItem : blobs) {
//System.out.println(blobItem.getName() + " - " + blobItem.getVersionId() +
" - " + blobItem.getSnapshot());
blobClient = blobContainerClient.getBlobClient(blobItem.getName());//
.getProperties().getBlobSequenceNumber());

if (blobClient != null) {
blobClient.openInputStream();
// blobClient.openInputStream();
BlobProperties blobProperties = blobClient.getProperties();

String filePath="D:\\temp\\" + blobItem.getName();
FileUtils.forceMkdirParent(new File(filePath));
blobClient.downloadToFile(filePath);
//blobClient.getBlockBlobClient().downloadToFile(filePath);
BlockBlobClient blobClient2=blobClient.getBlockBlobClient();
//blobClient2.downloadToFile(filePath);

String bloburl=blobClient.getBlobUrl();

//blobProperties.

System.out.println(bloburl + " - " + blobProperties.getBlobType().name()
+":: Size: "+blobProperties.getBlobSize()+" ::
"+blobProperties.getCopyId()+" :: "+blobProperties.getCopySource());
}
}


List of screenshots:

[image: image.png]

Inside Data folder:

[image: image.png]

[image: image.png]

[image: image.png]

[image: image.png]

I hope it explain more to you.

Regards,
*SAMRAJ.K*

**Comment by rickle-msft** [comment] 2020-02-14 17:45
Thank you for the code snippet. We are going to work on running this code to see if we can reproduce what you're seeing.

In the meantime, do you think you could try reuploading the screenshots? They don't seem to be showing up.

**Comment by gapra-msft** [comment] 2020-02-14 18:42
@samrajcse I tried running your code with one of my containers and was unable to reproduce what you are seeing - I got back the same file types as was in the container. 

We'll wait for your screenshots so we can try to diagnose further. If there's any other information you think might help us, please do share.

**Comment by samrajcse** [comment] 2020-03-03 09:53
Hi Gauri,

In very simple, I can say i have created an export with one email. I need
to download this export. How can I download this?

?sv=2014-02-14&sr=c&si=eDiscoveryBlobPolicy9%7C0&sig=M%2BS3ur%2BQ5Zo4wO%2BaZwkoDi7gyrO5unw9apANxz7dxjU%3D

This is the Export key. If we use that in eDsivoery export tool. It will
work. I need to do it with Java SDK. Please guide me with examples.

Regards,
*SAMRAJ.K*

**Comment by gapra-msft** [comment] 2020-03-03 17:17
Hi @samrajcse 
Here is a code snippet to download all the blobs in a container. 

```
    public static void main( String[] args ) throws IOException {
        String containerName = "<containerName>";
        String sasToken =  "<sasToken>";

        BlobServiceClient storageClient = new BlobServiceClientBuilder()
            .endpoint("https://storageaccount.blob.core.windows.net")
            .sasToken(sasToken).buildClient();

        BlobContainerClient blobContainerClient =
            storageClient.getBlobContainerClient(containerName);

        PagedIterable<BlobItem> blobs = blobContainerClient.listBlobs();
        BlobClient blobClient = null;
        for (BlobItem blobItem : blobs) {
            blobClient = blobContainerClient.getBlobClient(blobItem.getName());

            if (blobClient != null) {
                blobClient.openInputStream();
                BlobProperties blobProperties = blobClient.getProperties();

                String filePath="D:\\temp\\" + blobItem.getName();
                FileUtils.forceMkdirParent(new File(filePath));
                blobClient.downloadToFile(filePath);
            }
        }
    }
```

**Comment by samrajcse** [comment] 2020-03-04 01:22
Hi Team,

I have tried this and it is downloading .meta files. How to convert that to
real files. In the above SAS token, we have a pst containing one email.

I tried with ediscovery export tool and it is working fine. I want to do
same kind of work without that tool using only with java code

**Comment by rickle-msft** [comment] 2020-03-04 18:10
@samrajcse I don't think we understand what you mean by ".meta" files. The SDK only writes to the path you provide it. We don't create or operate on .meta files unless that happens to be in the path you are providing. Further, we have no relationship to an ediscovery export tool, nor is it clear what is meant by "a pst containing one email". 

Given that we are able to run your code successfully with the desired results and that we have provided sample code that has been tested many times over, we must ask that you investigate the possibility of errors external to the Storage SDK. It seems there is some larger application logic that is not correct here, and focusing too hard on the logic of the SDK is distracting from errors that I believe lie elsewhere. 

I suggest you consider adding some logging to determine the destination paths for your file operations or that you investigate this ediscover tool further too see what other logic it may have that you are not replicating completely with the Java SDK. 

I am going to close this issue for now as the issue and scenario have been discussed at length, and we (the SDK team) have concluded that there is not sufficient reason to believe there is a problem with the SDK. If you investigate further and are able to provide more evidence that there is indeed a bug in the SDK, please feel free to reopen this issue or start a new thread. We wish you the best with sorting out this workflow, and hope to engage with you again in the future.

**Closed by rickle-msft** 2020-03-04 18:10 UTC
Labels: Client, Storage
