### ISSUE TITLE
Getting AMQP errors (broken pipe, framing-error) while listening to event hub - spring-cloud-azure-eventhubs-stream-binder - 1.2.7

### ISSUE THREAD

**Issue by nikhil-muriki-by** [Azure/azure-sdk-for-java#15857] opened 2020-10-01 14:54 UTC
I am getting AMQP errors (broken pipe, framing-error) while listening to event hub. I am using the following library - **spring-cloud-azure-eventhubs-stream-binder - 1.2.7**. We are deploying our service in AKS, initially, I am able to receive the events without any issue, but after a while may after couple of days I am below errors in my logs and not able to receive any events. I am getting the 

***Exception or Stack Trace***

Framing error:
--------------------
Error occurred on partition: NONE. Error: {}

com.azure.core.amqp.exception.AmqpException: 'amqp:connection:framing-error' is not a known ErrorCondition., TrackingId: 1af1d56b-6150-44dc-b120-33d7fe752f32, at: 2020-09-26T00:06:03.187Z[GMT], errorContext[NAMESPACE: evhn-by-pd-lpa-dev.servicebus.windows.net]
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:122)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: 'amqp:connection:framing-error' is not a known ErrorCondition.
	at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:42)
	at com.azure.core.amqp.implementation.handler.ConnectionHandler.notifyErrorContext(ConnectionHandler.java:265)
	at com.azure.core.amqp.implementation.handler.ConnectionHandler.onTransportError(ConnectionHandler.java:157)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:82)
	... 8 common frames omitted

Broken Pipe Stack trace:
------------------------
Error occurred on partition: NONE. Error: {}

com.azure.core.amqp.exception.AmqpException: Broken pipe, errorContext[NAMESPACE: evhn-by-pd-lpa-dev.servicebus.windows.net]
	at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:77)
	at com.azure.core.amqp.implementation.handler.ConnectionHandler.notifyErrorContext(ConnectionHandler.java:265)
	at com.azure.core.amqp.implementation.handler.ConnectionHandler.onTransportError(ConnectionHandler.java:157)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:82)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Steps to reproduce the behavior:**
Getting this error after a couple of days after my service deployed in AKS and I am not able to receive any events later.

***My Event Hanlder**
 
  
     @Override
    @StreamListener(HierarchyMetadataMessageStreams.DIMENSION_LEVEL_INGESTOR)
    public void handleEvent(Message<DimensionLevelMessageContract> message) throws Exception {
    try {
      DimensionLevelMessageContract dimensionLevelMessageContract = message.getPayload();
      LOGGER.debug("Received data payload: {}", JsonConfiguration.asJson(dimensionLevelMessageContract));
      String correlationId = dimensionLevelMessageContract.getCorrelationId();
      List<DimensionLevelContract> entities = dimensionLevelMessageContract.getEntities();
      if (entities == null || entities.isEmpty()) {
        LOGGER.debug("correlationId: {} :::: There are no entities in the message", correlationId);
        return;
      }
      EventType eventType = dimensionLevelMessageContract.getEventType();

      if (eventType.equals(EventType.CREATE)) {
        List<DimensionLevel> dimensionLevels = constructDimensionLevels(entities, correlationId);

        LOGGER.debug("correlationId: {} :::: No. of entities in the input {}", correlationId, entities.size());
        LOGGER.debug("correlationId: {} :::: No. of valid dimension levels {}", correlationId, dimensionLevels.size());

        if (dimensionLevels.size() > 0) {
          dimensionLevelService.save(dimensionLevels);
        }
      } else {
        LOGGER.warn("correlationId: {} :::: Invalid eventType {} is provided", correlationId, eventType);
      }
      // CSOFF: IllegalCatch
    } catch (Exception ex) {
      LOGGER.error("Exception occurred while importing: ", ex);
      throw ex;
    }
   }
    @override
@serviceactivator(inputChannel = HierarchyMetadataMessageStreams.DIMENSION_LEVEL_ERROR_TOPIC)
protected void handleError(ErrorMessage errorMessage) throws Exception {
try {
processError(errorMessage);
} catch (Exception e) {
LOGGER.error("Failed to handle attribute group attribute error message {}", errorMessage, e);
throw e;
}
}

**Config:**
 cloud:
    azure:
      msi-enabled: false
      auto-create-resources: false
      eventhub:
        namespace: evhn-by-pd-lpa-dev
        connection-string: Endpoint=sb://evhn-by-pd-lpa-dev.servicebus.windows.net/;SharedAccessKeyName=*****;SharedAccessKey=****
        checkpoint-storage-account: azuremigrationv2
        checkpoint-access-key: ******
        checkpoint-container: checkpoint-container
    stream:
      default-binder: eventhub
      bindings:
        dimensionLevelIngestor:
          destination: private.la.dimension-level.ingest
          group: $Default
          content-type: application/json
          nativeEncoding: true
          consumer:
            concurrency: 1
            valueSerde: JsonSerde
      eventhub:
        bindings:
          dimensionLevelIngestor:
            consumer:
              checkpoint-mode: MANUAL

**Expected behavior**
Should not see these errors and should be able to receive the events.

**Screenshots**

**Setup (please complete the following information):**
 - AKS
 - Version of the Library used: spring-cloud-azure-eventhubs-stream-binder - 1.2.7

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by conniey** [comment] 2020-10-01 22:33
Thanks for reporting this! 1.2.7 uses an old version of com.azure:azure-messaging-eventhubs-checkpointstore-blob (1.0.2). 1.2.8 should have pulled in a later version.

This problem was fixed in: https://github.com/Azure/azure-sdk-for-java/pull/11776

**Comment by nikhilmuriki** [comment] 2020-10-05 05:24
Thank you Conniey for your quick response. We are also getting broken pipe error in our logs, will that also be fixed if we upgrade to 1.2.8 version of the library?

**Comment by conniey** [comment] 2020-10-05 17:22
@nikhilmuriki What broke pipe error are you getting in your logs? We have another big reliability fix coming up in our October release eventhubs, as well.

**Comment by anujanirula** [comment] 2020-10-06 04:44
Hi connie, 

below is the broken pipe error:
Error occurred on partition: NONE. Error: {}

com.azure.core.amqp.exception.AmqpException: Broken pipe, errorContext[NAMESPACE: evhn-by-pd-lpa-dev.servicebus.windows.net]
at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:77)
at com.azure.core.amqp.implementation.handler.ConnectionHandler.notifyErrorContext(ConnectionHandler.java:265)
at com.azure.core.amqp.implementation.handler.ConnectionHandler.onTransportError(ConnectionHandler.java:157)
at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191)
at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:82)
at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

**Comment by conniey** [comment] 2020-10-13 20:03
Do you have repro for this? It looks like an exception coming from our underlying library, proton-j..

**Comment by nikhilmuriki** [comment] 2020-10-14 05:52
@conniey  As I mentioned before I was getting broken pipe error after a couple of days after my service deployed in AKS. I don't have any specific reproduction steps. 
But after started using the 1.2.8 version, I did not notice that error logged in our logs until now, but I am not completely sure if that issue is fixed in the 1.2.8 version or no.

**Comment by nikhil-muriki-by** [comment] 2021-03-09 07:44
Thanks for checking, we don't see that **framing-error** error in our logs after upgrading to 1.2.8. But sometimes we are noticing events are not being received by the handlers, a week later after service got deployed to AKS, I don't see any exceptions or errors in our logs. We will have to kill the pods and event listening is being resumed.

**Comment by ramya-rao-a** [comment] 2021-09-14 22:56
@nikhil-muriki-by We will close this issue as the original problem around the framing-error is resolved. Please open a new issue if you are still seeing problems in receiving messages

**Closed by ramya-rao-a** 2021-09-14 22:56 UTC
Labels: bug, Event Hubs, Client, customer-reported, pillar-reliability, needs-team-attention
