### ISSUE TITLE
[BUG] - Out Of memory issues when sending messages to Service bus topics 

### ISSUE THREAD

**Issue by ashokerram** [Azure/azure-sdk-for-java#23721] opened 2021-08-23 21:37 UTC
WE have a java program that sends messages to Azure Service bus topic  and we are using Azure service bus 3.6.2 libraries. 
The application runs fine for 10-12 days then it gets out of memory problem. application has a max heap size of 1024 MB.
The program also is setting some custom properties on the message that is being sent to topic. 
The program on startup creates a topic client object for a given topic then all process instances reuse that topic client to send message to SB Topic. We also suspect that this issue is only  happening when custom properties are set for a message.

We have collected the heap dump and analyzed it using Eclipse Memory Analyzer 1.11.0 and it seems  that **org.apache.qpid.proton.engine.impl.TransportImpl**  has memory leak or memory is not being released. 

***Exception or Stack Trace***
30 instances of "org.apache.qpid.proton.engine.impl.TransportImpl", loaded by "sun.misc.Launcher$AppClassLoader @ 0xc011b7c0" occupy 32,289,592 (56.82%) bytes. 
Biggest instances:
•	org.apache.qpid.proton.engine.impl.TransportImpl @ 0xc2996438 - 2,479,144 (4.36%) bytes. 
•	org.apache.qpid.proton.engine.impl.TransportImpl @ 0xc2e31ae0 - 2,457,880 (4.33%) bytes. 
•	org.apache.qpid.proton.engine.impl.TransportImpl @ 0xc29f3008 - 2,450,808 (4.31%) bytes. 
•	org.apache.qpid.proton.engine.impl.TransportImpl @ 0xc320d2a0 - 2,419,304 (4.26%) bytes. 
•	org.apache.qpid.proton.engine.impl.TransportImpl @ 0xc2532f68 - 2,397,728 (4.22%) bytes. 
•	org.apache.qpid.proton.engine.impl.TransportImpl @ 0xc2d81158 - 1,398,520 (2.46%) bytes. 
•	org.apache.qpid.proton.engine.impl.TransportImpl @ 0xc34ba090 - 1,380,488 (2.43%) bytes. 
•	org.apache.qpid.proton.engine.impl.TransportImpl @ 0xc2397750 - 1,358,976 (2.39%) bytes. 
•	org.apache.qpid.proton.engine.impl.TransportImpl @ 0xc23e3610 - 1,345,416 (2.37%) bytes. 
•	org.apache.qpid.proton.engine.impl.TransportImpl @ 0xc30c2fd0 - 1,313,640 (2.31%) bytes. 
•	org.apache.qpid.proton.engine.impl.TransportImpl @ 0xc147e678 - 1,292,896 (2.28%) bytes. 
•	org.apache.qpid.proton.engine.impl.TransportImpl @ 0xc3680558 - 951,656 (1.67%) bytes. 
•	org.apache.qpid.proton.engine.impl.TransportImpl @ 0xc21b4428 - 862,504 (1.52%) bytes. 
•	org.apache.qpid.proton.engine.impl.TransportImpl @ 0xc20e07c8 - 848,472 (1.49%) bytes. 
•	org.apache.qpid.proton.engine.impl.TransportImpl @ 0xc1ca53c8 - 826,808 (1.45%) bytes. 
•	org.apache.qpid.proton.engine.impl.TransportImpl @ 0xc2099198 - 820,280 (1.44%) bytes. 
•	org.apache.qpid.proton.engine.impl.TransportImpl @ 0xc1b147c8 - 818,128 (1.44%) bytes. 
•	org.apache.qpid.proton.engine.impl.TransportImpl @ 0xc1f43ad0 - 808,880 (1.42%) bytes. 
•	org.apache.qpid.proton.engine.impl.TransportImpl @ 0xc1e7e610 - 795,328 (1.40%) bytes. 
•	org.apache.qpid.proton.engine.impl.TransportImpl @ 0xc1be0f08 - 784,760 (1.38%) bytes. 
•	org.apache.qpid.proton.engine.impl.TransportImpl @ 0xc179d798 - 776,184 (1.37%) bytes. 
These instances are referenced from one instance of "java.util.HashMap$Node[]", loaded by "<system class loader>", which occupies 1,328 (0.00%) bytes.

Keywords
org.apache.qpid.proton.engine.impl.TransportImpl
sun.misc.Launcher$AppClassLoader @ 0xc011b7c0
java.util.HashMap$Node[]

Threadstack 

ReactorThread0d08ce15-3880-4d2e-a70a-2678aaf8745b
  at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(JI[I[I[IJ)I (Native Method)
  at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll()I (WindowsSelectorImpl.java:296)
  at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Lsun/nio/ch/WindowsSelectorImpl$SubSelector;)I (WindowsSelectorImpl.java:278)
  at sun.nio.ch.WindowsSelectorImpl.doSelect(J)I (WindowsSelectorImpl.java:159)
  at sun.nio.ch.SelectorImpl.lockAndDoSelect(J)I (SelectorImpl.java:86)
  at sun.nio.ch.SelectorImpl.select(J)I (SelectorImpl.java:97)
  at org.apache.qpid.proton.reactor.impl.SelectorImpl.select(J)V (SelectorImpl.java:126)
  at org.apache.qpid.proton.reactor.impl.IOHandler.handleQuiesced(Lorg/apache/qpid/proton/reactor/Reactor;Lorg/apache/qpid/proton/reactor/Selector;)V (IOHandler.java:57)
  at org.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(Lorg/apache/qpid/proton/engine/Event;)V (IOHandler.java:390)
  at org.apache.qpid.proton.engine.BaseHandler.onReactorQuiesced(Lorg/apache/qpid/proton/engine/Event;)V (BaseHandler.java:87)
  at org.apache.qpid.proton.engine.BaseHandler.handle(Lorg/apache/qpid/proton/engine/Event;)V (BaseHandler.java:206)
  at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(Lorg/apache/qpid/proton/engine/Handler;)V (EventImpl.java:108)
  at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(Lorg/apache/qpid/proton/engine/Event;Lorg/apache/qpid/proton/engine/Handler;)V (ReactorImpl.java:324)
  at org.apache.qpid.proton.reactor.impl.ReactorImpl.process()Z (ReactorImpl.java:292)
  at com.microsoft.azure.servicebus.primitives.MessagingFactory$RunReactor.run()V (MessagingFactory.java:556)
  at java.lang.Thread.run()V (Thread.java:745)

**To Reproduce**
Create a java program with 500K-600k volume every day and 
on startup, use method public void createTopicClient(String connectionString, String topicName) to create a topic client. This will set the static variable for the class topicClient. 
Then for each message use method public String sendMessagesAsync(String Payload, String contentType,String properties) to write to SB topic. 

***Code Snippet***
package com.alaskaair.azureservicebusproducer;
import com.microsoft.azure.servicebus.Message;
import com.microsoft.azure.servicebus.TopicClient;
import com.microsoft.azure.servicebus.primitives.ConnectionStringBuilder;
import java.util.HashMap;
import java.util.Map;
//import java.util.concurrent.CompletableFuture;

public class ServiceBusProducer {
    public static TopicClient topicClient = null; 
    public String buildConnectionString(String nameSpace,String SharedAccessKeyName,String KeyValue)
    {
        String connectionString = "Endpoint=sb://"+nameSpace+".servicebus.windows.net/;SharedAccessKeyName="+ SharedAccessKeyName+";SharedAccessKey="+KeyValue;        
        return connectionString;
    }

    public static TopicClient getTopicClient() 
    {
        return topicClient;
    }

    public  static void setTopicClient(TopicClient topicClient)
    {
        ServiceBusProducer.topicClient = topicClient;
    }

    public void createTopicClient(String connectionString, String topicName) throws Exception
    {
        TopicClient sendClient;
        sendClient = new TopicClient(new ConnectionStringBuilder(connectionString, topicName));
        setTopicClient(sendClient);        
    }

// -- This method writes messase without topic client argument
public String sendMessagesAsync(String Payload, String contentType,String properties)
{

    Message message = new Message(Payload);
       message.setContentType(contentType);           
       /*https://crunchify.com/java-stringtokenizer-and-string-split-example*/
       String[] Tokens= properties.split(";");
       int tokenCount = Tokens.length;

       Map<String,Object> msgHdrMap =   new HashMap<>(tokenCount);            

       for (int j = 0; j < tokenCount; j++)
       {                    
            String msgHdr= Tokens[j];                 
            msgHdrMap.put(msgHdr.substring(0, msgHdr.indexOf("-")), msgHdr.substring(msgHdr.indexOf("-")+1,msgHdr.length()));  

       } 

       message.setProperties(msgHdrMap);
       getTopicClient().sendAsync(message);

       //sendClient.closeAsync();      
       //System.out.printf("Message sending: Id = %s\n", message.getMessageId());
       return(message.getMessageId());
}

// -- This method writes messase with message properties.
public String sendMessagesAsync(TopicClient sendClient, String Payload, String contentType,String properties)
{

    Message message = new Message(Payload);
       message.setContentType(contentType);           
       /*https://crunchify.com/java-stringtokenizer-and-string-split-example*/
       String[] Tokens= properties.split(";");
       int tokenCount = Tokens.length;

       Map<String,Object> msgHdrMap =   new HashMap<>(tokenCount);            

       for (int j = 0; j < tokenCount; j++)
       {                    
            String msgHdr= Tokens[j];                 
            msgHdrMap.put(msgHdr.substring(0, msgHdr.indexOf("-")), msgHdr.substring(msgHdr.indexOf("-")+1,msgHdr.length()));  

       } 

       message.setProperties(msgHdrMap);       
       sendClient.sendAsync(message);

       //sendClient.closeAsync();      
       //System.out.printf("Message sending: Id = %s\n", message.getMessageId());
       return(message.getMessageId());
}

// -- This method writes messase without any properties 
public static String sendMessagesAsync(TopicClient sendClient, String Payload, String contentType) 
{
       Message message = new Message(Payload);
       message.setContentType(contentType);                        
            //System.out.printf("Message sending: Id = %s\n", message.getMessageId());
            sendClient.sendAsync(message);
       //sendClient.closeAsync();
       return(message.getMessageId());
}

**Expected behavior**
Objects needs to be released from memory.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows Server 2012 R2
 - IDE: 
 - Library/Libraries: <groupId>com.microsoft.azure</groupId> 
            <artifactId>azure-servicebus</artifactId> 
            <version>3.6.2</version>
            <type>jar</type>
 - Java version: 1.8.0_112-b15  
 - App Server/Environment: Tomcat 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please provide
- dependency tree (`mvn dependency:tree -Dverbose`)
  
**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by ashokerram** [comment] 2021-09-01 05:00
Hi,

The message payload has two sections in our case - message content and custom properties. We don’t see any errors and for each message posted to SB, our application logs the SB message id.  This message ID, I guess,  is generated by Service bus and is an indicator for us that message is successfully posted to SB topic and 99.9% of messages are having this message ID. There are few messages that may not be having msgID, but our logs do not capture any debug level errors for these and we dint go this route to spend more time.

Yea, the code snippet do not catch the returned variable but I have tried another version of the same code that catches the return variable and that also has this out of memory issue.

We suspect that this out of memory is happening only when we add custom properties to message and we have other versions of apps that do not add custom properties and there is no issue there.

Few questions;
Is the heap dump analyzed from your end? Any insights on that ? Can the SDK code be reviewed where it is adding custom properties to message and find if there are any objects that are kept in memory there?

Ashok.

________________________________

**Comment by ashokerram** [comment] 2021-09-01 05:14
+

***@***.***

________________________________

**Comment by ashokerram** [comment] 2021-09-03 05:37
> @master-mck Your issue is very likely a different one. EH SDK and Service Bus SDK are not exactly same, even though they both use the same proton-j library underneath.
> @ashokerram I have been trying to reproduce the issue and couldn't. Under normal conditions (including typical network errors or idle links or idle connections), there are no leaks. Here is what I suspect. Your message payload is probably causing some other issue. But I am not sure. Could you answer this question? Do you see any send failures? I strongly suspect some of your sends are failing. The code you pasted here calls and sendAsync() and doesn't care for the result. Do you track if the send operation succeeds or fails? If yes, how many failures do you see per day? Do you capture logs from your application, including the logs generated by the service bus SDK? If yes, could you share the logs from the time you captured the memory dump?

Hi,

The message payload has two sections in our case - message content and custom properties. We don’t see any errors and for each message posted to SB, our application logs the SB message id.  This message ID, I guess,  is generated by Service bus and is an indicator for us that message is successfully posted to SB topic and 99.9% of messages are having this message ID. There are few messages that may not be having msgID, but our logs do not capture any debug level errors for these and we dint go this route to spend more time.

Yea, the code snippet do not catch the returned variable but I have tried another version of the same code that catches the return variable and that also has this out of memory issue.

We suspect that this out of memory is happening only when we add custom properties to message and we have other versions of apps that do not add custom properties and there is no issue there.

Few questions;
Is the heap dump analyzed from your end? Any insights on that ? Can the SDK code be reviewed where it is adding custom properties to message and find if there are any objects that are kept in memory there?

Ashok.

**Comment by ashokerram** [comment] 2021-09-07 18:52
@yvgopal  I have provided some more info for your questions in above thread. 
I am open for a working session this week to provide more inputs, if needed. I think that will help speed up the resolution.

**Comment by yvgopal** [comment] 2021-09-07 23:36
@ashokerram Since I asked you for more info, I spent more time with the dump you shared and tried multiple ways to reproduce this problem. I am glad to say that I reproduced it. I am working on a fix. It will be released sometime this month.

A leak occurs only when the network connection drops, I mean the physical network connection. I could reproduce memory leak only when I unplug my network cable or disable my network adapter. This means your network is dropping connections at least few times a day. Nevertheless, I will release a fix in the next 3 or 4 weeks.

**Comment by ashokerram** [comment] 2021-09-08 00:13
@yvgopal ..thank you for this update.   We will look forward for newer version.

**Comment by ashokerram** [comment] 2021-09-08 04:30
@yvgopal .. Just curious, were you able to pin point the objects that are not getting released in this scenario ? Was it matching with the heap dump stack ? And we have exact same program that writes to SB topics without any custom properties. Why is this not an issue there ? Is the leak happening in custom properties code ?

**Comment by ashokerram** [comment] 2021-10-12 20:49
Hi @yvgopal .. any update for us on this bug ? Also, any findings on the above question ?

**Closed** 2021-11-11 23:16 UTC
Labels: question, bug, customer-reported

**Comment by yvgopal** [comment] 2021-11-11 23:51
Fixed in version 3.6.6

**Comment by ashokerram** [comment] 2021-12-02 22:27
Hi @yvgopal .. 

I tried to use the new version 3.6.6 in my code, but below imports are not available in it. My code is using these packages.. 
How should I fix this ?

import com.microsoft.azure.servicebus.Message;
import com.microsoft.azure.servicebus.TopicClient;
import com.microsoft.azure.servicebus.primitives.ConnectionStringBuilder

![image](https://user-images.githubusercontent.com/25232434/144513253-a289bf31-160c-468a-8f6c-aa4df2b1734d.png)
