### ISSUE TITLE
[BUG] Signature does not match when accepting a marketplace ordering agreement

### ISSUE THREAD

**Issue by notdryft** [Azure/azure-sdk-for-java#6206] opened 2019-11-07 13:04 UTC
**Describe the bug**

Before using a marketplace Azure VM image, you need to accept its agreement terms. This can be done using the cli, which uses in background the API:

```bash
az vm image terms accept -p $publisher -f $offer --plan $sku
```

The Java SDK uses the same API, but end up with a failure.

***Exception or Stack Trace***

```
Exception in thread "main" com.microsoft.azure.management.marketplaceordering.v2015_06_01.ErrorResponseException: Status code 400, {"error":{"code":"BadRequest","message":"Signature does not match. Please request terms again and request acceptance."}}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:122)
	at com.microsoft.azure.AzureResponseBuilder.build(AzureResponseBuilder.java:56)
	at com.microsoft.azure.management.marketplaceordering.v2015_06_01.implementation.MarketplaceAgreementsInner.createDelegate(MarketplaceAgreementsInner.java:281)
	at com.microsoft.azure.management.marketplaceordering.v2015_06_01.implementation.MarketplaceAgreementsInner.access$100(MarketplaceAgreementsInner.java:40)
	at com.microsoft.azure.management.marketplaceordering.v2015_06_01.implementation.MarketplaceAgreementsInner$5.call(MarketplaceAgreementsInner.java:268)
	at com.microsoft.azure.management.marketplaceordering.v2015_06_01.implementation.MarketplaceAgreementsInner$5.call(MarketplaceAgreementsInner.java:264)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120)
	at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.subscribe(Observable.java:10423)
	at rx.Observable.subscribe(Observable.java:10390)
	at rx.Observable.subscribe(Observable.java:10298)
	at org.dryft.azure.Agreements$.acceptTerms(Agreements.scala:102)
	at org.dryft.azure.Agreements$.$anonfun$main$2(Agreements.scala:128)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**To Reproduce**

1. Get an agreement from a (publisher, offer, plan) triplet
2. Modify the accepted boolean of the returned agreement
3. Update the agreement

***Code Snippet***

Simplified async pseudo-code:

```scala
val terms = client.marketplaceAgreements.getAsync(publisher, offer, sku)
client.marketplaceAgreements.createAsync(publisher, offer, sku, terms.inner.withAccepted(true))
```

**Additional context**

Similar issue on node sdk: https://github.com/Azure/azure-sdk-for-node/issues/2423

For some reason, the date is not formatted properly and skips some milliseconds. Milliseconds that changes the signature of the query and makes it fail.

Returned agreement after the first GET query:

```json
{
  "properties": {
    "retrieveDatetime": "2019-11-07T12:19:46.796698Z",
    "signature": "SOME_SIGNATURE",
    "accepted": false
  }
}
```

Updated agreement for the PUT query:

```json
{
  "properties": {
    "retrieveDatetime": "2019-11-07T12:19:46.796Z",
    "signature": "SAME_SIGNATURE",
    "accepted": true
  }
}
```

The `698` missing part just before the `Z` of the `retrieveDatetime` is the issue.

**Comment by joshfree** [comment] 2019-11-07 23:08
Thanks for reporting this issue.  Someone from the `Management` Plane will take a look and get back to you.

**Comment by Benjiiim** [comment] 2020-02-13 13:58
Hi @joshfree 
Can we have an update on this one?
Thanks.

**Comment by yungezz** [comment] 2020-04-20 13:47
hi @xccc-msft could you pls help to have a look? thanks

**Comment by xccc-msft** [comment] 2020-04-21 09:02
@notdryft This is caused by the [DateTimeSerializer](https://github.com/Azure/autorest-clientruntime-for-java/blob/master/client-runtime/src/main/java/com/microsoft/rest/serializer/DateTimeSerializer.java#L41-L42). We will need some time to figure out whether this should be fixed from server side or SDK side.

cc: @jianghaolu

**Comment by jianghaolu** [comment] 2020-04-21 18:05
For track 1 in order to support Java 7 we only have millisecond support through joda time. Microseconds require Java 8 and above. See this post for details: https://stackoverflow.com/a/33487917

For now you may have to change the type of the field to a string manually. In track 2 we are targeting Java 8 and uses java.time with microseconds support.

**Comment by xccc-msft** [comment] 2020-04-22 02:19
@jianghaolu Thanks for sharing this.
@notdryft I just checked the service swagger. It looks there were changes for [date time format](https://github.com/Azure/azure-rest-api-specs/commit/122be610007ff2890a1229749722115cd943102b#diff-e7cdc6af547c46a2438c7374544904bc), and later the changes got [reverted](https://github.com/Azure/azure-rest-api-specs/commit/c830a70612c9403ce7c855a8f6714f4ff7b6f3a5#diff-e7cdc6af547c46a2438c7374544904bc). I just add label of `Service Attention`. We need help from service team to confirm whether it should be only a manual fix on Java or a common fix on swagger. After that, we could apply the changes and plan for new release.

**Comment by slandelle** [comment] 2020-06-05 07:14
Any update on this?

**Comment by prbansa** [comment] 2020-06-05 07:33
Adding ILDC folks for further updates here.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by prbansa** [comment] 2020-06-07 08:47
This is one of the more cryptic message that I have got lately …… 😊 I am not sure what is need here and what is the ask , and not even sure at what area.

**Comment by xccc-msft** [comment] 2020-06-08 03:02
@prbansa It looks a common issue across the SDKs like [Node](https://github.com/Azure/azure-sdk-for-node/issues/2423), [Python](https://github.com/Azure/azure-rest-api-specs/issues/2307) and now Java. 
The ask is: 
Can we change the date-time format in swagger for fixing the unsupported precision in SDK clients?

**Comment by lilyjma** [comment] 2020-08-27 18:59
@prbansa: any updates?

**Comment by yungezz** [comment] 2021-02-23 00:41
> @prbansa It looks a common issue across the SDKs like [Node](https://github.com/Azure/azure-sdk-for-node/issues/2423), [Python](https://github.com/Azure/azure-rest-api-specs/issues/2307) and now Java.
> The ask is:
> Can we change the date-time format in swagger for fixing the unsupported precision in SDK clients?

hi @prbansa do you have enough information to help on the issue? PIng us if you need more info. cc @weidongxu-microsoft

**Closed** 2022-01-05 08:02 UTC
Labels: bug, Marketplace Ordering, Service Attention, Mgmt, customer-reported, needs-author-feedback, no-recent-activity
