### ISSUE TITLE
v12 Preview download is not streaming file content

### ISSUE THREAD

**Issue by mwm-twx** [Azure/azure-sdk-for-java#5574] opened 2019-09-27 18:46 UTC
**Describe the bug**
Using `BlockBlobAsyncClient.download()`, the resulting `Flux<ByteBuffer>` only fires a single time with all content.  If that is the intended behavior, it should probably be `Mono<ByteBuffer` instead.

**Steps to Reproduce**
Use the `BlockBlobAsyncClient` to download a large file.  See code snippet below.
For a ~80MB file, I expected to receive a bunch of small buffers, but instead got a single 80MB buffer.

***Code Snippet***
```java
CountDownLatch latch = new CountDownLatch(1);
try {
    BlobServiceAsyncClient blobServiceAsyncClient = new BlobServiceClientBuilder()
        .endpoint(endpoint)
        .credential(new SharedKeyCredential(accountName, accountKey))
        .httpClient(HttpClient.createDefault())
        .buildAsyncClient();

    ContainerAsyncClient containerClient = blobServiceAsyncClient.getContainerAsyncClient(containerName);
    BlockBlobAsyncClient blobClient = containerClient.getBlockBlobAsyncClient(blobId);

    blobClient
        .download()
        .doOnSubscribe(subscription -> System.out.println("Download file triggered"))
        .subscribe(fluxResponse -> {
            System.out.println("Download file started");

            Flux<ByteBuffer> bufferFlux = fluxResponse.value()
                .map(byteBuffer -> {
                    System.out.printf("Received buffer of %d bytes", byteBuffer.remaining());
                    return byteBuffer;
                });
            bufferFlux
                .doOnComplete(latch::countDown)
                .subscribe();
        }, throwable -> {
            System.out.println("Download file failed.");
            throwable.printStackTrace();
        });
    latch.await();
} catch (Exception exc) {
    exc.printStackTrace();
}
```

**Expected behavior**
I expected the `Flux<ByteBuffer>` to be trigger multiple times as data comes in on the socket.  I need to stream the content of the file to another destination and do not want to buffer the entire contents in memory.

Aside from this download call, there is a downloadToFile, but that takes a string filename; is there a way to get partial data as it arrives from azure?

**Setup (please complete the following information):**
 - OS: Linux
 - IDE : IntelliJ
 - Version of the Library used:  12.0.0-preview.2  (.3 behaves the same)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by JonathanGiles** [comment] 2019-09-29 22:56
Thank you for letting us know @mwm-twx. We will take a look at this immediately and let you know of our findings. @alzimmermsft Could you please take a look at this ASAP? Thanks!

**Comment by rickle-msft** [comment] 2019-09-30 23:03
@mwm-twx It is the designed behavior that download() only makes one rest call. The reason why it returns a Flux is because we don't make guarantees on how the data will be chunked upon return. Depending on the size of your download and the network behavior of your application, the downloaded data will be chunked differently, so the return type has to be able to handle this different behavior. If you try downloading a several GB you will see that the Flux fires numerous events. 

Because the chunking behavior is largely dependent on reactorNetty, I don't know that we can offer a ton of customization around the size of the ByteBuffers you get back. If you really want to force small buffers, one potential workaround is to make several range download calls (there's an overload that accepts a BlobRange) and concat those responses together into one flux where each event is the result of the smaller range download. It will make more service requests, which will perhaps be more costly in terms of perf and transaction costs, but it doesn't sound like that's an issue for you. If you want more support developing that solution, let me know.

@alzimmermsft can you confirm my comments on the configurability of buffer sizes when streaming?

**Comment by srnagar** [comment] 2019-10-01 06:15
@mwm-twx @rickle-msft @alzimmermsft 
Here are my findings on this issue.

I tested preview 2 and preview 3 in isolation and I was able to reproduce the reported issue with preview 2 - the entire blob of 150 MB was downloaded as a single ByteBuffer. 

However, when I switched to preview 3, the download happened in chunks of 8KB and I received a flux of ByteBuffers as expected. 

@mwm-twx You had mentioned that you noticed this in preview 3 as well but could you please try again and confirm? The download response has changed in preview 3 and the above code will not compile ( `fluxResponse.value().map(...)` is now just `fluxResponse.map(...)`) So, it would be great if you can please try the code I have pasted below for preview 3 and let me know if you are still able to reproduce this issue.

**Preview 3**
```
    CountDownLatch latch = new CountDownLatch(1);
    try {
      BlobServiceAsyncClient blobServiceAsyncClient = new BlobServiceClientBuilder()
          .endpoint(endpoint)
          .credential(new SharedKeyCredential(accountName, accountKey))
          .httpClient(HttpClient.createDefault())
          .buildAsyncClient();

      ContainerAsyncClient containerClient = blobServiceAsyncClient.getContainerAsyncClient(containerName);
      BlockBlobAsyncClient blobClient = containerClient.getBlockBlobAsyncClient(blobId);

      blobClient
          .download()
          .doOnSubscribe(subscription -> System.out.println("Download file triggered"))
          .subscribe(fluxResponse -> {
            System.out.println("Download file started");

            Flux<ByteBuffer> bufferFlux = fluxResponse
                .map(byteBuffer -> {
                  System.out.println("Received buffer of bytes = " + byteBuffer.remaining());
                  return byteBuffer;
                });
            bufferFlux
                .doOnComplete(latch::countDown)
                .subscribe();
          }, throwable -> {
            System.out.println("Download file failed.");
            throwable.printStackTrace();
          });
      latch.await();
    } catch (Exception exc) {
      exc.printStackTrace();
    }
```
**Preview 3 Output**
```
Download file triggered
Download file started
Received buffer of bytes = 8192
Received buffer of bytes = 7593
Received buffer of bytes = 8192
Received buffer of bytes = 8192
Received buffer of bytes = 8192
Received buffer of bytes = 8192
....
....
```

Preview 2 code is exactly the same as reported by @mwm-twx 
**Preview 2 Output:**
```
Download file triggered
Download file started
Received buffer of bytes = 158309744

Process finished with exit code 0
```
As you can see above, the preview 2 blob storage download API downloaded 150MB blob into a single ByteBuffer while preview 3 download API received several chunks of ByteBuffers each approx 8KB.

**Comment by mwm-twx** [comment] 2019-10-01 15:26
@srnagar Thanks, I see the same behavior with preview 3.  I messed up changing the version and was still building against preview 2.

Apologies for the wasted time, you can close this issue.

**Comment by srnagar** [comment] 2019-10-01 15:44
@mwm-twx Thank you for the confirmation! Glad to know that the issue is resolved. I'll close this issue. 

Please feel free to reach out to us if you have any questions or issues regarding Azure SDKs.

**Closed by srnagar** 2019-10-01 15:44 UTC
Labels: Client, Storage, customer-reported
