### ISSUE TITLE
[BUG] Java File Share Download API Performance Investigation

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-java#19625] opened 2021-03-04 20:06 UTC
**Describe the bug**
Java Storage File Share Download API Performance test throughput varies greatly and is significantly slower compared to storage blob.
Investigate the root causes and possible improvements to the impl code.

**Comment by mikeharder** [comment] 2021-03-04 20:17
I believe the issue is File Share has service throttles, but they are per share not per account:

> * Baseline IOPS: 400 + 1 IOPS per GiB, up to 100,000
> * IOPS bursting: Max (4000,3x IOPS per GiB), up to 100,000
> 
> https://docs.microsoft.com/en-us/azure/storage/files/storage-files-scale-targets#azure-file-share-scale-targets

.NET uses one share per test instance, so it doesn't hit the throttles.  But Java currently uses one share across all test instances:

.NET (one share per instance): https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Files.Shares/perf/Azure.Storage.Files.Shares.Perf/Scenarios/DownloadFile.cs#L55
 
Java (one share for all instances): https://github.com/g2vinay/azure-sdk-for-java/blob/add-storage-file-share-perf-test/sdk/storage/azure-storage-perf/src/main/java/com/azure/storage/file/share/perf/core/ShareTest.java#L29

I think Java should be updated to align with .NET.

**Comment by gapra-msft** [comment] 2021-05-06 22:47
@jaschrep-msft you investigated this earlier right? Could you please update your findings on this thread and close the issue if applicable?

**Comment by mikeharder** [comment] 2021-05-06 23:01
@gapra-msft: Java has been updated to use one share per test instance (aligning with .NET):

https://github.com/Azure/azure-sdk-for-java/blob/1a50a0dd6fa7fd88ebfcd8e868561a247a646702/sdk/storage/azure-storage-perf/src/main/java/com/azure/storage/file/share/perf/core/ShareTest.java#L22

Java FileShare Download perf is now comparable to Java Blob Download and .NET FileShare Download.

**Closed** 2021-05-06 23:02 UTC
Labels: Client, Storage, tenet-performance
