### ISSUE TITLE
[QUERY] Cannot authenticate in Azure Container App using DefaultAzureCredentialBuilder

### ISSUE THREAD

**Issue by Rohi-spark** [Azure/azure-sdk-for-java#42800] opened 2024-11-05 11:13 UTC
**Query/Question**
Not able to authenticate in azure container app using DefaultAzureCredentialBuilder.
Previously working with version 1.13.1

***Why is this not a Bug or a feature Request?***
NA

**Setup (please complete the following information if applicable):**
 - OS: linux
 - IDE: intellij
 - Library/Libraries: azure-identity 1.14.0
 -
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by g2vinay** [comment] 2024-11-05 16:09
Hi @Rohi-spark 

Can you share more details about the failure such as error stack trace and what type of authentication you are using and on which azure platform is your container app deployed ?

**Comment by lxchinh97** [comment] 2024-11-12 08:40
Hi @g2vinay , Could you please check the issue below.
**Cosmos Authentication Fails on Azure Container App After Upgrading spring-cloud-azure from 5.17.1 to 5.18.0**

Issue Summary:
After upgrading to spring-cloud-azure version 5.18.0, Cosmos DB authentication fails in our Azure Container App. Downgrading azure-identity from 1.14.0 to 1.13.3 resolves the issue. 

Environment:
Spring Cloud Azure version: 5.18.0
Spring Cloud Azure Starter Data Cosmos version: 5.18.0
Azure Identity version: 1.14.0 (works as expected with 1.13.3)
Azure Platform: Azure Container App

Config: application.yml: 
```
spring:
  cloud:
    cosmos:
      enabled: true
      database: placeholder
      endpoint: placeholder
      credential:
        client-id: placeholder
        managed-identity-enabled: true
```

Steps to Reproduce:
Configure Cosmos DB in application.yml as shown above.
Deploy the application to an Azure Container App with spring-cloud-azure:5.18.0 azure-identity:1.14.0.
Call cosmosRepository.findById("") to trigger Cosmos authentication.

- Here is the log after upgrading spring-cloud-azure from 5.17.1 to 5.18.0

`c.a.identity.ManagedIdentityCredential   : Azure Identity => Managed Identity environment: **Managed Identity**
2024-11-08T14:42:55.395Z  INFO [spring-boot-application,,] 7 --- [spring-boot-application] [onPool-worker-1] [                                                 ] c.a.core.credential.SimpleTokenCache     : {"az.sdk.message":"Acquired a new access token"}
...
com.azure.spring.data.cosmos.exception.CosmosAccessException: Failed to find item
	at com.azure.spring.data.cosmos.exception.CosmosExceptionUtils.findAPIExceptionHandler(CosmosExceptionUtils.java:71)
	at com.azure.spring.data.cosmos.core.CosmosTemplate.lambda$findById$8(CosmosTemplate.java:427)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:180)
	at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:187)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

	Suppressed: [CIRCULAR REFERENCE: com.azure.cosmos.implementation.UnauthorizedException: {"innerErrorMessage":"[\"Provided AAD token is intended for [https://cosmos-account-dev.documents.azure.com/]. This database account accepts tokens intended for [https://cosmos-account-dev.documents.azure.com, https://cosmos-account-dev.sql.cosmos.azure.com, https://cosmos-account-dev.sqlx.cosmos.azure.com, https://cosmos.azure.com].\"]","cosmosDiagnostics":{"userAgent":"azsdk-java-cosmos/4.64.0 Linux/5.15.164.1-1.cm2 JRE/21.0.5 az-sd-cos/5.18.0az-sp-cos/5.18.0","activityId":"534c4a26-897c-47c1-990c-3f4e80a15849","requestLatencyInMs":675,"requestStartTimeUTC":"2024-11-08T14:43:08.194789889Z","requestEndTimeUTC":"2024-11-08T14:43:08.870767895Z","responseStatisticsList":[{"storeResult":{"storePhysicalAddress":"rntbd://cosmos-account-dev-eastus.documents.azure.com:22631/apps/e2702296-aabc-4e9d-b90c-244c9ed0e64e/services/32b9f59a-3d83-42f9-ae4e-2f68c905ba48/partitions/4ae573c8-7f9c-401c-9314-fcea00a291c8/replicas/133722465642354367s/","lsn":39,"quorumAckedLSN":-1,"currentReplicaSetSize":-1,"globalCommittedLsn":39,"partitionKeyRangeId":null,"isValid":true,"statusCode":401,"subStatusCode":5008,"isGone":false,"isNotFound":false,"isInvalidPartition":false,"isThroughputControlRequestRateTooLarge":false,"requestCharge":0.0,"itemLSN":-1,"sessionToken":":1#39","backendLatencyInMs":0.282,"retryAfterInMs":null,"exceptionMessage":"[\"Provided AAD token is intended for [https://cosmos-account-dev.documents.azure.com/]. This database account accepts tokens intended for [https://cosmos-account-dev.documents.azure.com, https://cosmos-account-dev.sql.cosmos.azure.com, https://cosmos-account-dev.sqlx.cosmos.azure.com, https://cosmos.azure.com].\"]","exceptionResponseHeaders":"{x-ms-last-state-change-utc=Fri, 25 Oct 2024 09:05:31.247 GMT, x-ms-request-duration-ms=0.282, x-ms-session-token=:1#39, lsn=39, x-ms-schemaversion=1.18, x-ms-transport-request-id=1, x-ms-number-of-read-regions=0, x-ms-activity-id=534c4a26-897c-47c1-990c-3f4e80a15849, x-ms-xp-role=2, x-ms-global-Committed-lsn=39, x-ms-cosmos-llsn=39, x-ms-serviceversion= version=2.14.0.0, x-ms-substatus=5008}","replicaStatusList":{"Ignoring":[],"Attempting":["22512:S:Unknown","22631:S:Unknown","22872:P:Unknown","22840:S:Unknown"]},"transportRequestTimeline":[{"eventName":"created","startTimeUTC":"2024-11-08T14:43:08.591604172Z","durationInMilliSecs":18.292815},{"eventName":"queued","startTimeUTC":"2024-11-08T14:43:08.609896987Z","durationInMilliSecs":0.076003},{"eventName":"channelAcquisitionStarted","startTimeUTC":"2024-11-08T14:43:08.609972990Z","durationInMilliSecs":120.801361},{"eventName":"pipelined","startTimeUTC":"2024-11-08T14:43:08.730774351Z","durationInMilliSecs":103.374285},{"eventName":"transitTime","startTimeUTC":"2024-11-08T14:43:08.834148636Z","durationInMilliSecs":1.422931},{"eventName":"decodeTime","startTimeUTC":"2024-11-08T14:43:08.835571567Z","durationInMilliSecs":3.168781},{"eventName":"received","startTimeUTC":"2024-11-08T14:43:08.838740348Z","durationInMilliSecs":28.483199},{"eventName":"completed","startTimeUTC":"2024-11-08T14:43:08.867223547Z","durationInMilliSecs":0.053464}],"rntbdRequestLengthInBytes":1990,"rntbdResponseLengthInBytes":493,"requestPayloadLengthInBytes":0,"responsePayloadLengthInBytes":493,"channelStatistics":{"channelId":"31eb59ae","channelTaskQueueSize":0,"pendingRequestsCount":0,"lastReadTime":"2024-11-08T14:43:08.724853206Z","waitForConnectionInit":true},"serviceEndpointStatistics":{"availableChannels":0,"acquiredChannels":0,"executorTaskQueueSize":0,"inflightRequests":1,"lastSuccessfulRequestTime":"2024-11-08T14:43:08.596Z","lastRequestTime":"2024-11-08T14:43:08.596Z","createdTime":"2024-11-08T14:43:08.596927715Z","isClosed":false,"cerMetrics":{}}},"requestResponseTimeUTC":"2024-11-08T14:43:08.870767895Z","requestStartTimeUTC":"2024-11-08T14:43:08.591604172Z","requestResourceType":"Document","requestOperationType":"Read","requestSessionToken":null,"e2ePolicyCfg":null,"excludedRegions":null,"sessionTokenEvaluationResults":[],"locationToLocationSpecificHealthContext":{"v":null}}],"supplementalResponseStatisticsList":[],"addressResolutionStatistics":{"84adafd4-70dc-46e6-a468-14bf705191bb":{"startTimeUTC":"2024-11-08T14:43:08.453648284Z","endTimeUTC":"2024-11-08T14:43:08.499859486Z","targetEndpoint":"https://cosmos-account-dev-eastus.documents.azure.com:443/addresses/?$resolveFor=dbs%2F0y5PAA%3D%3D%2Fcolls%2F0y5PAOga9DQ%3D%2Fdocs&$filter=protocol%20eq%20rntbd&$partitionKeyRangeIds=0","exceptionMessage":null,"forceRefresh":false,"forceCollectionRoutingMapRefresh":false,"inflightRequest":false}},"regionsContacted":["east us"],"retryContext":{"statusAndSubStatusCodes":null,"retryLatency":0,"retryCount":0},"metadataDiagnosticsContext":{"metadataDiagnosticList":[{"metaDataName":"CONTAINER_LOOK_UP","startTimeUTC":"2024-11-08T14:43:08.203025421Z","endTimeUTC":"2024-11-08T14:43:08.346896127Z","durationinMS":143},{"metaDataName":"PARTITION_KEY_RANGE_LOOK_UP","startTimeUTC":"2024-11-08T14:43:08.352517193Z","endTimeUTC":"2024-11-08T14:43:08.432794166Z","durationinMS":80},{"metaDataName":"SERVER_ADDRESS_LOOKUP","startTimeUTC":"2024-11-08T14:43:08.453675473Z","endTimeUTC":"2024-11-08T14:43:08.499803943Z","durationinMS":46}]},"serializationDiagnosticsContext":{"serializationDiagnosticsList":null},"gatewayStatisticsList":[],"samplingRateSnapshot":1.0,"bloomFilterInsertionCountSnapshot":0,"systemInformation":{"usedMemory":"58403 KB","availableMemory":"854301 KB","systemCpuLoad":"(2024-11-08T14:42:54.080929324Z 66.6%), (2024-11-08T14:42:59.080780566Z 37.3%), (2024-11-08T14:43:04.080757096Z 5.4%)","availableProcessors":1},"clientCfgs":{"id":1,"machineId":"uuid:8324217a-fe97-4ab3-a6c1-29acc65eb65e","connectionMode":"DIRECT","numberOfClients":3,"excrgns":"[]","clientEndpoints":{"https://cosmos-account-dev.documents.azure.com":3},"connCfg":{"rntbd":"(cto:PT5S, nrto:PT5S, icto:PT0S, ieto:PT1H, mcpe:130, mrpc:30, cer:true)","gw":"(cps:1000, nrto:PT1M, icto:PT1M, p:false)","other":"(ed: true, cs: false, rv: true)"},"consistencyCfg":"(consistency: null, mm: true, prgns: [])","proactiveInitCfg":"","e2ePolicyCfg":"","sessionRetryCfg":"","partitionLevelCircuitBreakerCfg":"(cb: false, type: CONSECUTIVE_EXCEPTION_COUNT_BASED, rexcntt: 10, wexcntt: 5)"}}}]
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:104)
		at reactor.core.publisher.Mono.block(Mono.java:1779)
		at com.azure.spring.data.cosmos.core.CosmosTemplate.findById(CosmosTemplate.java:429)
		at com.azure.spring.data.cosmos.core.CosmosTemplate.findById(CosmosTemplate.java:447)
		at com.azure.spring.data.cosmos.repository.support.SimpleCosmosRepository.findById(SimpleCosmosRepository.java:203)
		at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
		at java.base/java.lang.reflect.Method.invoke(Method.java:580)
		at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
		at org.springframework.data.repository.core.support.RepositoryMethodInvoker$RepositoryFragmentMethodInvoker.lambda$new$0(RepositoryMethodInvoker.java:277)
		at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:170)
		at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:158)
		at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:516)
		at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:285)
		at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:628)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
		at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:173)
		at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:148)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
		at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
		at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:223)
		at jdk.proxy2/jdk.proxy2.$Proxy145.findById(Unknown Source)
		at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
		at java.base/java.lang.reflect.Method.invoke(Method.java:580)
		at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
		at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:138)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
		at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:223)
		at jdk.proxy2/jdk.proxy2.$Proxy145.findById(Unknown Source)`

- Here is the log after downgrading azure-identity version from 1.14.0 to 1.13.3
```
2024-11-08T14:37:41.272Z  INFO [springboot-application,,] 7 --- [springboot-application] [onPool-worker-1] [                                                 ] c.a.identity.ManagedIdentityCredential   : Azure Identity => Managed Identity environment: **AZURE APP SERVICE MSI/IDENTITY ENDPOINT**
2024-11-08T14:37:41.272Z  INFO [springboot-application,,] 7 --- [springboot-application] [onPool-worker-1] [                                                 ] c.a.core.credential.SimpleTokenCache     : {"az.sdk.message":"Acquired a new access token"}
```

We found code changes in the Azure SDK for Java (PR #[42164](https://github.com/Azure/azure-sdk-for-java/pull/42164/files#diff-82a6bcdabb37c147d9903853d7c2ec436c1019347474212438ae810cc0ae0523L144)) that may have modified the managed identity authentication flow.
- [azure-identity:1.14.0 ](https://github.com/Azure/azure-sdk-for-java/blob/azure-identity_1.14.0/sdk/identity/azure-identity/src/main/java/com/azure/identity/ManagedIdentityMsalCredential.java#L36)
- [azure-identity:1.13.3](https://github.com/Azure/azure-sdk-for-java/blob/azure-identity_1.13.3/sdk/identity/azure-identity/src/main/java/com/azure/identity/AppServiceMsiCredential.java#L54C31-L54C80)

**Comment by Rohi-spark** [comment] 2024-11-12 08:58
@g2vinay
@billwert 

I am using below code to authenticate in Container App using credential builder -  


```
AzureProfile profile;
DefaultAzureCredential credential;
public void init()
{
        this.profile = new AzureProfile(tenantID, subscriptionID, AzureEnvironment.AZURE);
        this.credential = new DefaultAzureCredentialBuilder().build();
}
```

This is working fine when I deploy the code. I have created user assigned MSI for container app.

I have defined Identity version 1.13.1 in pom.xml

If I switched to latest version then I will face below issue -

com.azure.identity.CredentialUnavailableException: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/java/identity/environmentcredential/troubleshoot WorkloadIdentityCredential authentication unavailable. The workload options are not fully configured. See the troubleshooting guide for more information. https://aka.ms/azsdk/java/identity/workloadidentitycredential/troubleshoot Managed Identity authentication is not available. SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache. IntelliJ authentication not available. Please login with the Azure Toolkit for IntelliJ. You may also need to upgrade to a newer version of the Azure Toolkit for IntelliJ. This authentication is supported on version 3.53 and higher. Please see https://aka.ms/azsdk/java/identity/intellijcredential/troubleshoot for more information. AzureCliCredential authentication unavailable. Azure CLI not installed.To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/java/identity/azclicredential/troubleshoot Encountered error when deserializing response from Azure Power Shell. AzureDeveloperCliCredential authentication unavailable. Azure Developer CLI not installed.To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/java/identity/azdevclicredential/troubleshootTo mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azure-identity-java-default-azure-credential-troubleshoot [com.azure.identity.ChainedTokenCredential.lambda$getToken$4(ChainedTokenCredential.java:108),

**Comment by runforrestrun** [comment] 2024-11-13 15:50
@lxchinh97 we are having the same problem with CosmosDb.

**Comment by simplyanything** [comment] 2024-11-13 19:13
@lxchinh97, we're observing the same problem after upgrading Spring Cloud Azure to `5.18.0` with the same exact inner error message (also for Cosmos). Downgrading to `5.17.1` indeed resolves it. Could this be investigated please, @g2vinay ?

**Comment by billwert** [comment] 2024-11-13 19:41
We're actively looking at this one today folks - will get back to you asap.

**Comment by g2vinay** [comment] 2024-11-16 03:50
We shipped a fix related to this in  version1.14.2, try it out folks and let us know if you run into any issues.

```java
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-identity</artifactId>
    <version>1.14.2</version>
</dependency>
```

@simplyanything @runforrestrun @Rohi-spark @lxchinh97

**Comment by simplyanything** [comment] 2024-11-18 18:55
Thanks for the quick fix @g2vinay, it works!

**Comment by g2vinay** [comment] 2024-11-21 06:35
Closing as issue is resolved.

**Closed by g2vinay** 2024-11-21 06:35 UTC
Labels: question, Client, customer-reported, Azure.Identity, needs-team-attention

**Comment by Rohi-spark** [comment] 2024-11-22 05:32
@g2vinay Its working for me. Thank you for the update.
