### ISSUE TITLE
[BUG] NullPointerException calling BlobBatchClient.submitBatchWithResponse()

### ISSUE THREAD

**Issue by lightningrob** [Azure/azure-sdk-for-java#7256] opened 2020-01-08 00:45 UTC
**Describe the bug**
When calling BlobBatchClient.submitBatchWithResponse() containing a batch of deletions, throws the NPE below.  This does not always happen, maybe 10% of the time.

***Exception or Stack Trace***
java.lang.NullPointerException
                at com.azure.storage.blob.batch.BlobBatch.getContentLength(BlobBatch.java:339)
                at com.azure.storage.blob.batch.BlobBatchAsyncClient.submitBatchWithResponse(BlobBatchAsyncClient.java:120)
                at com.azure.storage.blob.batch.BlobBatchClient.submitBatchWithResponse(BlobBatchClient.java:87)
                at com.github.ambry.cloud.azure.BatchBlobDeletionTest.purgeBlobs(BatchBlobDeletionTest.java:126)
                at com.github.ambry.cloud.azure.BatchBlobDeletionTest.testBatchDeletion(BatchBlobDeletionTest.java:113)
                at com.github.ambry.cloud.azure.BatchBlobDeletionTest.main(BatchBlobDeletionTest.java:66)

**To Reproduce**
Run the attached main class (executes in a loop) until the exception occurs.

***Code Snippet***
BlobBatch blobBatch = blobBatchClient.getBlobBatch();
List<Response> responseList = new ArrayList<>();
for (String blobName : blobNames) {
responseList.add(blobBatch.deleteBlob(containerName, blobName));
}
int purgeCount = 0;
blobBatchClient.submitBatchWithResponse(blobBatch, false, Duration.ofHours(1), Context.NONE);

**Expected behavior**
Expect the call to succeed.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: MacOS 10.15.2
 - IDE : IntelliJ
 - Version of the Library used:  azure-storage-blob-12.0.0.jar

**Additional context**
Need to supply program with system property azure.storage.connection.string pointing to your Azure storage account.
Note: The same program sometimes fails with  UnsupportedOperationException. (See issue #7255.)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Bug Description Added
- [ x] Repro Steps Added
- [x ] Setup information Added

[BatchBlobDeletionTest.java.txt](https://github.com/Azure/azure-sdk-for-java/files/4033112/BatchBlobDeletionTest.java.txt)

**Comment by alzimmermsft** [comment] 2020-01-09 19:04
@lightningrob I have tried to replicate this issue given the code sample given, haven't hit the case where this comes up. This may be resolved by the changes made based on the investigation of #7255 

At a high level the cause of this would be a `null` value being added to the internal batch queue, but what is interesting is that all add calls are using `ByteBuffer.wrap` which should return a `ByteBuffer` or throw a `NullPointerException` if the `byte[]` being wrapped is `null`. My hypothesis is that, given the investigation of #7255, multiple threads are mutating the not thread-safe queue resulting in a size increment without adding an element.

**Comment by alzimmermsft** [comment] 2020-01-15 19:19
This issue should be resolved by the most recently release version of [Azure Storage Blob Batch](https://search.maven.org/artifact/com.azure/azure-storage-blob-batch/12.2.0/jar).

**Comment by alzimmermsft** [comment] 2020-01-22 18:43
Resolved by PR #6882

**Closed by alzimmermsft** 2020-01-22 18:43 UTC
Labels: Client, Storage, customer-reported
