### ISSUE TITLE
VM tests should not rely on hardcoded behavior of createStorageAccount in StorageHelper.java

### ISSUE THREAD

**Issue by jmspring** [Azure/azure-sdk-for-java#504] opened 2015-08-21 17:54 UTC
In StorageHelper.java, the implementation of createStorageAccount calls the blocking call to create a storage account then proceeds to poll while retrieving the storage accounts.  The actual method of creating a storage account in the resource-management library already blocks on the creation.

For some reason, if you change this behavior, a number of VM tests start to fail.

**Comment by xindzhan** [comment] 2015-08-24 20:36
This seems more like a service internal dependency/propagation issue that the storage account has to be available when the VM creation request is submitted. Another solution is to provide an existing storage account in the resource context to bypass this step.

**Comment by jianghaolu** [comment] 2015-10-16 17:17
@xindzhan Could you provide update on this?

**Comment by xindzhan** [comment] 2015-10-16 17:59
I looked at this again and it seems like it's more likely a bug in the storage client creation call where it suppose to be blocked until the storage account becomes available. Maybe another enum/status case mismatch kind of bug?

**Comment by jianghaolu** [comment] 2015-10-16 18:08
This will be addressed in the next minor release. Please check if this is resolved when 0.8.4 is out.

**Comment by xindzhan** [comment] 2015-10-16 18:11
Thanks @jianghaolu , what would be the release date for 0.8.4? Are the same changes going to be merged into dev branch as well?

**Comment by mayurid** [comment] 2015-10-23 18:05
@jmspring : 0.9.0. is released. Can you verify if the issue is fixed for you now.
Please reopen if you still see this.

**Closed by mayurid** 2015-10-23 18:05 UTC
