### ISSUE TITLE
[BUG] Could not find com.azure:azure-storage-blob:12.4.0.

### ISSUE THREAD

**Issue by jonasbark** [Azure/azure-sdk-for-java#23616] opened 2021-08-17 06:11 UTC
**Describe the bug**
Could not find com.azure:azure-storage-blob:12.4.0.

**To Reproduce**
1. Generate the project using
https://start.spring.io/#!type=gradle-project&language=kotlin&platformVersion=2.5.3&packaging=jar&jvmVersion=11&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo
2. clear local gradle and maven cache
3. add dependency
```
implementation("com.azure:azure-storage-blob:12.4.0")
```
4. observe error

- This also happens on Azure Devops CI, so it's not a local cache issue.
- The artifacts still seem to be available on Maven Central. 
- The builds have worked fine before (last successful on 18th July)
- I can't update the dependency as it's a transitive dependency
- it also happens with e.g. 12.6.0

**Comment by SilviuCucu** [comment] 2021-08-17 14:03
We also experienced the same problem with our build.
It seems that for all versions prior to 12.7.0 only the metadata remains in Maven Central. The actual artifacts (pom, jar, javadoc.jar, sources.jar etc) are all gone.
This can be seen by browsing the contents of https://repo1.maven.org/maven2/com/azure/azure-storage-blob. The maven-metadata.xml and folder hierarchy in the repo still contain the older versions, however, the folders corresponding to all versions prior to 12.7.0 are empty.

**Comment by rickle-msft** [comment] 2021-08-17 16:33
Hi, all. I am closing as this is a duplicate of #23562 Please see that other issue for information as it comes out. We are aware of this and will have more complete guidance soon. 

In the meantime, we recommend upgrading to latest. Please feel free to reopen this issue or create another one if you need assistance there

**Closed by rickle-msft** 2021-08-17 16:33 UTC
Labels: question, customer-reported, needs-triage
