### ISSUE TITLE
[BUG] Issue in reading bytes from blob storage using InputStream

### ISSUE THREAD

**Issue by ashokmor** [Azure/azure-sdk-for-java#13811] opened 2020-08-05 10:07 UTC
**Bug**
When we read bytes using BlobInputStream it returns -1 as number of bytes red!

**Steps to reproduce:**	
***1) Get input stream of blob stored on azure using following way :***

		//credential
		StorageSharedKeyCredential storageCreds = new StorageSharedKeyCredential(accountName, accountKey);

		//endpoint using account name
		String endPoint = "https://<accountName>.blob.core.windows.net/<containerName>";

		BlobContainerClient blobContainerClient = new BlobContainerClientBuilder().endpoint(endPoint).credential(storageCreds).buildClient();

		BlobClient blobClient = BlobClient client = blobContainerClient.getBlobClient(blobReferencePath);

		InputStream inputStream = blobClient.getBlockBlobClient().openInputStream();

***2) Read into bytes from input stream :***
	
		//File size on azure blob is 6+ mb //6393519

		//define byte array of 10mb // 10393519
                byte[] bytes = new byte[10393519];

		//read from input stream into bytes
    	        long count = inputStream.read(bytes);
	
***3) Issue :***

		Count is -1 despite it has read 6393519  bytes!!
	
**Solution :**
Issue is in StorageInputStream.java file line no : 291, it should return numOfBytesRead instead of -1 !	
			`
                        if (results == -1)  {
				return -1;
			}
                       `

[https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/StorageInputStream.java#L291](url)

**Comment by rickle-msft** [comment] 2020-08-05 15:53
Hi, @ashokmor. Thank you for reporting this! I have confirmed the behavior you're seeing. It looks like it only happens when the input array is bigger than the blob size and when multiple reads are dispatched because then the last chunk read comes back with -1 from readInternal and numberOfBytesRead is ignored and -1 is returned instead. I also double checked the docs and ByteArrayInputStream and am seeing the expected behavior you described. 

I think we'll need to actually do something like 
```
if (results == -1) {
  return numberOfBytesRead == 0 ? -1 : numberOfBytesRead
}
```
to account for the case where 0 bytes were actually read

Thank you for taking the time to describe the issue and the root cause so thoroughly. We'll work on putting out a fix for this soon

**Comment by ashokmor** [comment] 2020-08-06 02:16
Hi @rickle-msft 
You are welcome and thank you for the acknowledgement, much appreciated.

The real impact of the issue is big, say I have 106mb file, and byte array size is 10mb. (the byte array size is relative to blob size) Then it reads the file properly upto 100mb but skip the last 6mb data, hence partially file is read!

Issue is replicable while youtube publish and reading file from input stream of azure blob.

**Comment by rickle-msft** [comment] 2020-08-06 19:10
@ashokmor Yes, this behavior fits with what I was describing before. Thank you again for pointing this out, and we'll work on getting a fix at least for the next scheduled release if not a hotfix before then

**Closed** 2020-08-10 19:24 UTC
Labels: Client, Storage, customer-reported

**Comment by mattcasters** [comment] 2021-03-18 11:42
The file metadata contains the size. Surely you can cap read(), available() methods at that length in BlobInputStream?
