### ISSUE TITLE
Azure Java ServiceBus Queue Java receive or complete messages in batch for better performance

### ISSUE THREAD

**Issue by shezratnani** [Azure/azure-sdk-for-java#23776] opened 2021-08-26 14:48 UTC
**Query/Question**

I am trying to receive messages from a queue and had experimented with different methods and was facing performance issues. Below are the metrics for each type of run:

- Receive Mode = peek and lock; 1000 messages took 2.5 minutes as I had to complete each message one by one
- Receive Mode = receive and delete; 1000 messages took an average of 1.5 mins.
- Receive Mode = receive and delete (with prefetch count as 100); 1000 messages took 3 seconds but I ended up losing the 100 messages which were in the buffer at the time of execution end
- Receive Mode = peek and lock (with prefetch count as 100); 1000 message took 2 minutes as I had to again complete each message. It would have been a problem solver only if there was a way to complete them in batch.

Below is my code for reference:

```java
ServiceBusSessionReceiverClient sessionReceiverClient = new ServiceBusClientBuilder()
            .connectionString(System.getenv("QueueConnectionString"))
            .sessionReceiver()
            .maxAutoLockRenewDuration(Duration.ofMinutes(2))
            .receiveMode(ServiceBusReceiveMode.PEEK_LOCK)
            .queueName(queueName)
            .buildClient();
ServiceBusReceiverClient receiverClient = sessionReceiverClient.acceptSession(System.getenv("QueueSessionName"));
ObjectMapper objectMapper = new ObjectMapper();
    do {
        receiverClient.receiveMessages((int) prefetchCount).stream().forEach(message -> {
            try {
                String str = message.getBody().toString();
                final T dataDto = objectMapper.readValue(message.getBody().toString(), returnType);
                dataDtoList.add(dataDto);
                receiverClient.complete(message);
            } catch (Exception e) {
                AzFaUtil.getLogger().severe("Message processing failed.  Error: " + e.getMessage() + e + "\n Payload: "
                            + message);
            }
        });
    } while (dataDtoList.size() < numberOfMessages);
receiverClient.close();
sessionReceiverClient.close();`
```

Possible solutions that I can think of:

- If there is a way to complete messages in batch instead of completing 1 by 1.
- If there is a way to requeue the messages back to the queue which are sitting in the prefetch buffer.
- If there is a way to set autocomplete on ServiceBusReceiverClient

**Note: I just experimented with 1000 entries but I am working with 30000 entries so performance matters. Also the queue is session enabled and also partition enabled**

***Why is this not a Bug or a feature Request?***
Maybe there is a feature that I am not aware of.

**Setup (please complete the following information if applicable):**
 - OS: [e.g. iOS] Windows 10
 - IDE: [e.g. IntelliJ] Intellij
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by shezratnani** [comment] 2021-08-30 15:54
@anuchandy Please let me know if you need more information or have any questions for me. Thanks

**Comment by anuchandy** [comment] 2021-08-31 00:45
@shezratnani Thank you for trying the SDK and reaching out.


This page will give an excellent summary of the trade-off when choosing a higher prefetch value: https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-prefetch?tabs=dotnet#why-is-prefetch-not-the-default-option i.e.higher prefetch gains higher throughput, the trade-off is - the possibility of message lost OR redelivery of messages. The behavior you observed correlate with the trade-off described in the doc. 

Copy-Pasting few bullet points that I think relevant for your case:

* If you need a high degree of reliability for message processing, and processing takes significant work and time, we recommend that you use the Prefetch feature conservatively, or not at all.

* If you need high throughput and message processing is commonly cheap, prefetch yields significant throughput benefits.

* The maximum prefetch count and the lock duration configured on the queue or subscription need to be balanced such that the lock timeout at least exceeds the cumulative expected message processing time for the maximum size of the prefetch buffer, plus one message. At the same time, the lock timeout shouldn't be so long that messages can exceed their maximum time to live when they're accidentally dropped, and so requiring their lock to expire before being redelivered.


To answer your questions -

[Q1] "complete messages in batch instead of completing 1 by 1" - There is no such batching feature from the SB service side. Each message has to be acknowledged separately.

[Q2]: "If there is a way to re-queue the messages back to the queue which is sitting in the prefetch buffer" - If the message is received with peak-lock and the server lock of the message in the prefetch queue expires, it will be automatically redelivered by the service at a later point. With receive-and-delete receive mode, it is not a reliable design to have SDK or application to re-queue, these messages are in-memory, and restart/crash of the container can cause loss of those messages.

[Q3]: "If there is a way to set autocomplete on ServiceBusReceiverClient", unless app calls `disableAutoComplete()`, the auto complete is enabled.

I believe the best way to achieve scalability is by taking advantage of the SB service session feature, i.e., distribute messages evenly across sessions so that the processing also can be scaled (without data loss)

We'll be doing perf analysis on SB libraries. We recently started it for EH, and our team is building a framework for perf analyzing the messaging libraries across various languages (\\cc @mikeharder)

**Comment by shezratnani** [comment] 2021-08-31 20:15
@anuchandy Unfortunately the answers don't help my case as if I use peek lock with prefetch count as your answer to Q2 then we run into perform acknowledgement of each message like Q1 and that causes performance issues. I tried to use peek lock and the messages do not autocomplete. I can still see the count of the active messages in the queue unchanged. They only change when I use the complete() function for each message. Please help me. Thanks in advance. (\cc @joshfree)

**Comment by anuchandy** [comment] 2021-09-01 00:38
> I tried to use peek lock and the messages do not autocomplete

I should have clarified it, sorry, - so the `autoComplete` works only for async-client (i.e., via callback). When the callback returns, the SDK completes the message, i.e., the assumption is the completion of callback means completion of the message. There is no such assumption we can make when using sync-client, so the app needs to call complete explicitly. 

Note that whether its app calls `complete()` explicitly or async-client calls `complete()` internally when the callback returns, the completion is strictly a single operation, there is nothing like batching involved.

**Comment by shezratnani** [comment] 2021-09-21 14:10
@ramya-rao-a Has this issue been resolved?

**Comment by ramya-rao-a** [comment] 2021-09-21 17:03
@shezratnani I believe your questions have been addressed. Do you have any follow up questions here?

There are service limitations due to which we cannot complete messages in a batch. The service allows completing only 1 message at a time. This is by design as per the AMQP spec

I believe your other questions were around prefetch which @anuchandy has already addressed

**Comment by shezratnani** [comment] 2021-09-21 17:16
@ramya-rao-a My main issue was the service bus queue performance. Those (completing in batch, accessing the prefetch buffer) were just potential fixes if they exist. As a temporary fix, I have used JMS with a non-session and unpartitioned queue to maintain FIFO and have achieved a great performance boost. But the issue with JMS is that it doesn't work for the session-based queues. I suggest that the service bus client/receiver needs to be tested for its performance as compared to JMS it is very slow. And @anuchandy said that this is in the backlog. Yes, my question has been answered but it is not resolved yet. Thanks

**Comment by ramya-rao-a** [comment] 2021-09-21 17:45
Thanks for the clarification @shezratnani 

In that case, it would be better if you were to subscribe to the issue we are using to track perf improvements across Event Hubs and Service Bus because most of our effort is in improving the underlying AMQP layer that both the SDKs use.

@anuchandy What would be a good issue for @shezratnani to subscribe to here so that we can close this current issue?

**Comment by anuchandy** [comment] 2021-09-22 20:46
Here is the work item to add perf benchmark for SB https://github.com/Azure/azure-sdk-for-java/issues/20852 and analyze the numbers. Additionally, as you said, there will be other improvements in the common-layer, which we document in the change log as we release them. [Closing this issue in favor of more generic work item 20852]

**Closed by anuchandy** 2021-09-22 20:46 UTC
Labels: Service Bus, Client, customer-reported, pillar-performance, issue-addressed
