### ISSUE TITLE
[SB Track2] Do not close receive link after each sync receive

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#9786] opened 2020-04-02 16:10 UTC
Do not close receive link after each receive operation on the synchronous client.

**Comment by conniey** [comment] 2020-04-06 18:09
Depends on #9792 being fixed.

**Comment by hemanttanwar** [comment] 2020-05-08 21:56
duplicate of another issue which is already fixed.

**Closed by hemanttanwar** 2020-05-08 21:56 UTC
Labels: Client, Service Bus
