### ISSUE TITLE
In azure blob container and client creation don't require to close resources/connections?

### ISSUE THREAD

**Issue by harisingh-highq** [Azure/azure-sdk-for-java#17903] opened 2020-12-01 12:40 UTC
**Here is sample code snippet to create blob container and client to upload a file:-**

BlobClient blobClient = AzureHelper.getBlobContainerClient(AzureHelper.getBlobServiceClient(serviceEndpoint, account, key), container).getBlobClient(destFile);
![image](https://user-images.githubusercontent.com/33862788/100740626-07795000-33ff-11eb-851d-71c5c88faeb6.png)

blobClient.upload(bin, length, true);

In azure blob storage java library, we create blob container and blob client to perform upload/download operations.
I don't find any close/shutdown method for container client object close once operation is finished.

So **my question is as per below:-**

- azure blob client don't require to release any resources that might be held open?
- Also there is no any max limit to open container client object.(As many as number of client we can open?)
- In high concurrent upload/download scenarios, it may create issue?

Can anyone clarify this? 
Thanks

**Comment by rickle-msft** [comment] 2020-12-01 15:56
Hi, @harisingh-highq. Thank you for your questions.

- There is no need to explicitly close or release any resources when working with our clients. All the connections are managed by the underlying netty connection pool.
- There is no limit to the number of client objects you can create. The limitation will come more from the number of requests you issue concurrently. So if you create a million clients but only issue requests from one at a time, you won't hit any issues. On the other hand, if you share a single client and issue a million requests from the one client at once, you'll see more congestion this way. Again, this is due to the underlying shared netty connection pool. 
- These clients are designed to support highly concurrent scenarios. That said, there is a limit based on the resources of your machine and possibly your httpClient or environment configuration. You can't issue infinite requests at once, but we've done a lot of work to ensure there is good support for highly concurrent workloads

**Comment by rakhmvi** [comment] 2020-12-10 09:49
Hi @rickle-msft ,
my application tries to upload data  (about 256 MB) using default settings (blocksize, maxConcurrency, etc.), however it starts to receive multiple warnings one by one: 
[hybrid] [2020-12-10T14:56:15,700] [WARN ] reactor.netty.http.client.HttpClientConnect[id: 0x210f3791, L:/172.16.76.10:51510 - R:hybridblobtest.blob.core.windows.net/100.64.1.2:443] The connection observed an error io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms
	at io.netty.handler.ssl.SslHandler$5.run(SslHandler.java:2062)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

And finally exception has been thrown: 

Exception :reactor.core.Exceptions$ReactiveException
Exception detail :reactor.core.Exceptions$ReactiveException: io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms
	at reactor.core.Exceptions.propagate(Exceptions.java:393)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)
	at reactor.core.publisher.Mono.block(Mono.java:1680)
	at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:99)
	at com.azure.storage.blob.BlobClient.uploadWithResponse(BlobClient.java:231)
	at com.hybridintegration.repository.AzureRepo.uploadFile(AzureRepo.java:248)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.hybridintegration.servlet.FileUploadServlet.uploadFile(FileUploadServlet.java:875)
	at com.hybridintegration.servlet.FileUploadServlet.uploadFileOpr(FileUploadServlet.java:785)
	at com.hybridintegration.servlet.FileUploadServlet.handleExceptionInFileUpload(FileUploadServlet.java:1307)
	at com.hybridintegration.servlet.FileUploadServlet.doPost(FileUploadServlet.java:592)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hqahybrid.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)

**Comment by rickle-msft** [comment] 2020-12-10 23:38
@harisingh-highq Does this happen on every request? And out of curiosity, if you use http instead of https does the request succeed?

**Comment by rakhmvi** [comment] 2020-12-11 08:20
Hi @rickle-msft , 
seems it was network issues as today (after reboot) I have no any warnings in logs. 

Thank you

**Comment by rickle-msft** [comment] 2020-12-11 18:48
Wonderful. I am going to close this issue as it sounds like the questions were answered and the issue is no longer present.

**Closed** 2020-12-11 18:48 UTC
Labels: Client, Storage, customer-reported, question
