### ISSUE TITLE
[BUG] Azure Storage Blob SDK generates bad signature when using generateSas 

### ISSUE THREAD

**Issue by jonasbark** [Azure/azure-sdk-for-java#17902] opened 2020-12-01 11:18 UTC
**Describe the bug**
The SAS token results in the following issue:
```
<Error>
<Code>AuthenticationFailed</Code>
<Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:1ad42470-001e-0063-79d2-c7d88a000000 Time:2020-12-01T11:07:14.4122346Z</Message>
<AuthenticationErrorDetail>Signature fields not well formed.</AuthenticationErrorDetail>
</Error>
```

**To Reproduce**
Generate a SAS Token and open it in browser

***Code Snippet***
```
val blobServiceClient = BlobServiceClientBuilder()
        .endpoint(blobProperties.endpoint)
        .sasToken(blobProperties.sasToken)
        .apply {
            if (blobProperties.accountName != null && blobProperties.accountKey != null) {
                credential(StorageSharedKeyCredential(blobProperties.accountName, blobProperties.accountKey))
            }
        }
        .buildAsyncClient()

    val start = OffsetDateTime.now()
    val expiry = start.plusMinutes(10)

    val permissions = BlobSasPermission.parse("r")
    val sasSignatureValues = BlobServiceSasSignatureValues(expiry, permissions)
    sasSignatureValues.startTime = start
    val asyncClient = blobServiceClient
        .getBlobContainerAsyncClient(blobProperties.containerName)
        .getBlobAsyncClient(this)
    val sas = asyncClient.generateSas(sasSignatureValues)

    return "${blobProperties.endpoint}/${blobProperties.containerName}/$this?$sas"
```
produces this example URL:
https://stoaccdataieuwe****.blob.core.windows.net/containerName/210827.00--719704148.pdf?sv=2019-12-12&ss=f&srt=o&sp=r&se=2020-12-01T11%253A12%253A20Z&st=2020-12-01T11%253A02%253A20Z&spr=https&sig=ENl7tNx***253D

For reference a URL that was generated by Microsoft Azure Storage Explorer (and works):
https://stoaccdataieuwe****.blob.core.windows.net/containerName/210827.00--719704148.pdf?sv=2019-12-12&st=2020-12-01T11%3A00%3A06Z&se=2020-12-02T11%3A00%3A06Z&sr=b&sp=r&sig=****KmCx0Fucpup6fu4tp1leIPJDosyWwzZWHbc%3D

The encoding of the se part is also weird to me.

**Expected behavior**
The generated SAS token is valid

**Screenshots**

**Setup (please complete the following information):**
 - Version of the Library used: com.azure:azure-storage-blob:12.9.0

**Comment by rickle-msft** [comment] 2020-12-01 15:47
Hi, @jonasbark. Thank you for posting this issue. The first thing I'm noticing is that the sas you said was generated by the code snippet is an account sas authorizing access to the File service. But the code snippet uses BlobSasSignatureValues. This type actually can't generate the sas you shared as it has no knowledge of several of the query parameters such as srt or the file service. Can you please double check that the first sas you shared actually does come from the code you shared?

For the record, this is why authorization is failing--the sas you're using isn't authorized for blobs

**Comment by jonasbark** [comment] 2020-12-01 16:06
Hi @rickle-msft - thanks for replying!

Yes, I can confirm that the SAS token from my initial post was created by that exact code. To be sure I just recreated this method and tried it again.

For unknown reasons (which makes me question my sanity) the newly generated tokens all seem valid. I also tried it using the exact same code that failed me this morning.

In any case I can confirm that using BlobServiceSasSignatureValues seem to work fine here.

**Comment by rickle-msft** [comment] 2020-12-01 16:11
@jonasbark well I certainly understand code causing us to question our sanity!! But I'm glad to hear it's working now. 

 I'll leave the issue open for the time being, but feel free to close it if you think the issue is resolved. If you see another failure, can you please share the sas token again?

**Closed** 2021-01-19 23:09 UTC
Labels: Client, Storage, bug, customer-reported
