### ISSUE TITLE
[BUG] Null Pointer Transforms.toFieldValueObject

### ISSUE THREAD

**Issue by toniDoku** [Azure/azure-sdk-for-java#22781] opened 2021-07-05 10:48 UTC
java.lang.NullPointerException
        at com.azure.ai.formrecognizer.Transforms.toFieldValueObject(Transforms.java:448)

**Comment by JonathanGiles** [comment] 2021-07-05 22:00
Thanks for the report - I've assigned this to @samvaity and @mssfang to take a look at. If you have any further test cases or sample code that you can share, please do take a moment to update this issue with that information. Thank!

**Comment by samvaity** [comment] 2021-07-06 06:28
Hello @toniDoku, if you could share the sample/use case that you tried that results in the error, it should help us understand this more. Thank you !

**Comment by toniDoku** [comment] 2021-07-06 06:42
[Factura_ES3332425495.pdf](https://github.com/Azure/azure-sdk-for-java/files/6767845/Factura_ES3332425495.pdf)

**Comment by samvaity** [comment] 2021-07-06 16:52
Hey @toniDoku, I was able to get a successful data extraction for the above-provided document using the `beginRecognizeInvoices` endpoint.
Could you tell us more about the use-case and the specific endpoint that results in this failure?

**Comment by toniDoku** [comment] 2021-07-09 08:50
With version 3.1.1 We have this error

10:41:37.832 [reactor-http-nio-4] ERROR c.azure.ai.formrecognizer.Transforms - Value was extracted from the form, but cannot be normalized to date type. Consider accessing the `valueData.text` property for a textual representation of the value.
java.lang.RuntimeException: Value was extracted from the form, but cannot be normalized to date type. Consider accessing the `valueData.text` property for a textual representation of the value.
	at com.azure.ai.formrecognizer.Transforms.setFormField(Transforms.java:370)
	at com.azure.ai.formrecognizer.Transforms.lambda$getLabeledFieldMap$6(Transforms.java:322)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at com.azure.ai.formrecognizer.Transforms.getLabeledFieldMap(Transforms.java:307)
	at com.azure.ai.formrecognizer.Transforms.toRecognizedForm(Transforms.java:101)
	at com.azure.ai.formrecognizer.FormRecognizerAsyncClient.lambda$beginRecognizeInvoices$87(FormRecognizerAsyncClient.java:1249)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:73)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
	at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:61)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:73)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2397)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2193)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2067)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:337)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:354)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2397)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:110)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:143)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
	at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onNext(FluxDoOnEach.java:173)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:173)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2663)
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:180)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:260)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:150)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:150)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
	at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:159)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:145)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:212)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:269)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:401)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:416)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:470)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:685)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:94)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)

With the same file in version 3.1.0 we don't have error

![image](https://user-images.githubusercontent.com/31290943/125051633-6db80680-e0a3-11eb-90be-886fa59d3204.png)

**Comment by samvaity** [comment] 2021-07-09 18:25
Hey @toniDoku, I think we have resolved this error in our [azure-ai-formrecognizer-3.1.2](https://oss.sonatype.org/service/local/repositories/releases/content/com/azure/azure-ai-formrecognizer/3.1.2/azure-ai-formrecognizer-3.1.2.jar) latest release.

Do give it a try and let us know if that works.

**Comment by samvaity** [comment] 2021-07-13 21:52
Hey @toniDoku, could you confirm if this bug is being resolved?

**Comment by samvaity** [comment] 2021-09-14 21:42
Hey @toniDoku, we are unable to reproduce this bug. I will be closing this issue, in case of further assistance feel free to open a new issue.

**Closed by samvaity** 2021-09-14 21:42 UTC
Labels: question, customer-reported, Cognitive - Form Recognizer
