### ISSUE TITLE
Stoping to receive events from event hub after some time[BUG]

### ISSUE THREAD

**Issue by AT92** [Azure/azure-sdk-for-java#15976] opened 2020-10-06 11:34 UTC
**Describe the bug**
After some time, our service stops to receive events from the eventhub. A restart of the whole application helps us and the service starts to receive events again, and stops suddenly after some time (1 to 3 days interval). We got following error i:  

***Exception or Stack Trace***

 
```
com.azure.core.amqp.exception.AmqpException: The link 'G17:20180521:all_0959d0_1601882047407-29' is force detached. Code: ServerError. Details: InnerMessageReceiver was faulted. TrackingId:87d7be930001afe8002108ec5f7ac7ca_G17_B7, SystemTracker:OUR SYSTEM TRACKER, Timestamp:2020-10-06T08:48:36, errorContext[NAMESPACE: proxypath.americas.svc.corpintra.net, PATH: vehicle.data/ConsumerGroups/dfn/Partitions/29, REFERENCE_ID: all_0959d0_1601882047407-29, LINK_CREDIT: 202]
	at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:78)
	at com.azure.core.amqp.implementation.handler.LinkHandler.processOnClose(LinkHandler.java:90)
	at com.azure.core.amqp.implementation.handler.LinkHandler.handleRemoteLinkClosed(LinkHandler.java:108)
	at com.azure.core.amqp.implementation.handler.LinkHandler.onLinkRemoteClose(LinkHandler.java:50)
	at com.azure.core.amqp.implementation.handler.ReceiveLinkHandler.onLinkRemoteClose(ReceiveLinkHandler.java:18)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:82)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

After that exception the consumer are getting closed for all partitions with following log statements:

```
connectionId[MF_56a383_1601882047129] sessionName[vehicle.data/ConsumerGroups/dfn/Partitions/24]: Complete. Removing and disposing session.
Disposing of session.
onSessionRemoteClose connectionId, entityName[MF_56a383_1601882047129], condition[Error{condition=null, description='null', info=null}]
 onSessionRemoteClose closing a local session for connectionId[MF_56a383_1601882047129], entityName[vehicle.data/ConsumerGroups/dfn/Partitions/25], condition[null], description[null]
 Connection state: CLOSED

```

***Code Snippet***

We connect to the eventhub in following way:
```
EventHubClientBuilder eventHubClientBuilder = new EventHubClientBuilder()
                    .connectionString(eventHubConnectionString)
                    .transportType(AmqpTransportType.AMQP_WEB_SOCKETS)
                    .consumerGroup(consumerGroup);
            eventHubClientBuilder
                    .proxyOptions(new ProxyOptions(ProxyAuthenticationType.NONE,
                            new Proxy(Proxy.Type.HTTP, new InetSocketAddress(proxyHost, Integer.parseInt(proxyPort))),
                            null,
                            null));
            consumer = eventHubClientBuilder.buildAsyncConsumerClient();
            subscription = consumer.receive()
                    .subscribe(partitionEvent -> {
                                try {
                                    EventData event = partitionEvent.getData();
                                    messageHandler.handleGzipEvents(event);
                                } catch (EventHubRuntimeException e) {
                                    log.error("Received an error during eventhub message handling", e);
                                }
                            }, error -> log.error("An error occurred during the subscription to eventHub {}", error.toString()),
                            () -> log.info("Closed `connection"));
```

**Expected behavior**
After subscribing to the eventhub, the events come in without failures, so no restart of the application is necessary.

**Setup (please complete the following information):**
We use following library:
```
<dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>spring-integration-eventhubs</artifactId>
            <version>1.2.8</version>
</dependency>
```

We run our service on a kubernetes cluster in version v1.18.6.

**Comment by joshfree** [comment] 2020-10-06 18:36
Related https://github.com/Azure/azure-sdk-for-java/issues/15857 

@conniey can you please investigate?

**Comment by anujanirula** [comment] 2020-10-09 03:45
Hi @joshfree / @conniey, 

Does that mean the broken-pipeline error mentioned in #15857  would be resolved in the November release?

**Comment by conniey** [comment] 2020-10-13 19:58
@anujanirula I have not experienced that issue yet. Do you have a reliable repro for this broken pipeline issue?

**Comment by conniey** [comment] 2021-02-20 00:22
Closed as a duplicate of https://github.com/Azure/azure-sdk-for-java/issues/18070

**Closed by conniey** 2021-02-20 00:22 UTC
Labels: Client, Event Hubs, customer-reported, customer-response-expected, question, tenet-reliability
