### ISSUE TITLE
AsyncCacheNonBlocking - Improve availability during replica movement

### ISSUE THREAD

**Issue by kushagraThapar** [Azure/azure-sdk-for-java#25353] opened 2021-11-11 20:04 UTC
Port this to Java V4 SDK - https://msdata.visualstudio.com/CosmosDB/_git/CosmosDB/pullrequest/677284

**Comment by xinlian12** [comment] 2022-04-15 18:40
duplicate of https://github.com/Azure/azure-sdk-for-java/issues/28276

**Closed** 2022-04-15 18:40 UTC
Labels: Cosmos, Client, cosmos:v4-copper, cosmos:v4-item
