### ISSUE TITLE
Azure Blob Storage SDK async upload large files consuming very high heap memory and not releasing it 

### ISSUE THREAD

**Issue by bipin-kumar-maersk** [Azure/azure-sdk-for-java#34808] opened 2023-05-05 12:25 UTC
**Query/Question**
We are using azureBlobAysncClient upload method for large files like 5-10 mb in springboot microservice .when we are putting some load on the same api ,its consuming high memory like 1.5gb (whatever heap memory we assign it consumes all) and even load is coming back to normal,this heap memory never gets release which is a big issue we are facing currently. 

we tried parellel transfer and concurrency  as well,data is getting uploaded in chunks  but that dint help in memory spike issue.
we analysed heap dump as well which clearly shows 

- Off-heap memory used by java.nio.DirectByteBuffers
- Humongous (bigger than 1MB) objects

Could you please help us to resolve this SDK issue

***Why is this not a Bug or a feature Request?***
Feature wise functionlaity is working ,files are getting uploaded but memory usage wise its not good ,it can give OUT OF MEMORY anytime .

**Setup (please complete the following information if applicable):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:12.22.0 (groupId:artifactId:version)]
 
     <dependency>
          <groupId>com.azure</groupId>
          <artifactId>azure-storage-blob</artifactId>
          <version>12.22.0</version>
      </dependency>

**Comment by jairmyree** [comment] 2023-05-08 15:21
Hello @bipin-kumar-maersk, thank you for identifying this issue. Someone from the Storage team will follow up shortly.

**Comment by alzimmermsft** [comment] 2023-05-08 15:56
Hi @bipin-kumar-maersk, have you found a scenario where an `OutOfMemoryError` is thrown that you can reproduce? If so, could you run that scenario with the JVM arguments `-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=<output location of hprof> -XX:+CrashOnOutOfMemoryError`, and use a throwaway account in case HPROFs capture any sensitive data. This will help us determine where any allocations aren't being freed. With the HPROF could you also include the sample application used to capture the HPROF, as this will help us scope the investigation to the specific APIs being used.

**Comment by bipin-kumar-maersk** [comment] 2023-05-09 04:11
Hi @alzimmermsft ,we din't gave that much load to get OOM till now...once it reached to 99% heap ,we stopped the load to the service,and we waited that if heap memory comes down ,but heap memory never came down. ..so whatever memory we assign as heap like 1 gb or 1.5 gb , with same load it always reaching to 97-98% memory and never comes down and never gets released.

we generated heap dump as well using different tool simmilar like HPROF and we found that Off-heap memory used by java.nio.DirectByteBuffers is too high .

this memory utilization is completely dependent  on file size for smaller file size it grows slow but bigger file size it grows very fast and reach to 97-98% .

and our upload code is very simple ,its just a simple upload with azureblob async-client. its blocking us to release our product ..please suggest

**Comment by bipin-kumar-maersk** [comment] 2023-05-11 05:59
we haven't configured any specific http client to upload and its using default azure-core-http-netty and we are uploading 5mb file .
our usecase is to upload 5-10 mb file

**Comment by alzimmermsft** [comment] 2023-05-12 13:59
Nothing in the code sample given seems out of place nor does the configuration of Netty and the OS being used. Is the Java application automatically getting terminated once a certain heap usage is reached?

We run daily stress testing where we upload 100s of GB of data without seeing out of memory issues, and the heap will be periodically garbage collected when needed.

<img width="1707" alt="image" src="https://github.com/Azure/azure-sdk-for-java/assets/48699787/062ec2e7-bb8d-43c9-8f05-954998db8c3f">

If `domainRequest.getMultipartFile` is an actual `File` on the system I'd recommend using the `BlobAsyncClient.uploadFromFile` method as it offers some optimizations that may reduce the amount of memory used.

Also, are you talking about committed heap size or used heap size? Committed heap doesn't shrink as readily as used heap as not all garbage collections will reduce committed heap but they will reduce used heap.

**Comment by bipin-kumar-maersk** [comment] 2023-05-16 05:21
we already tried this BlobAsyncClient.uploadFromFile method but there was no improvement as such.
NOTE: domainRequest.getMultipartFile is not on the system,its getting uploaded via client .

we are checking RSS usage ,it always reaching to max level at high load with bigger files and RSS usage never comes down

**Comment by alzimmermsft** [comment] 2023-05-18 17:15
@bipin-kumar-maersk since I don't have insight into how the methods `getFileBytes` and `domainRequest.getMultipartFile()` work could you try simplifying the `Flux.just` being used to upload to test out with a local `byte[]` getting wrapped equivalent to a common size of file you are uploading. This should help determine if the issue is happening with the `azure-storage-blob` SDK or within one of those methods, on in the way they're interacting with each other.

**Comment by bipin-kumar-maersk** [comment] 2023-06-05 05:28
we tried this as well @alzimmermsft ,but dint get any success .

**Closed** 2023-07-08 01:35 UTC
Labels: bug, Storage, Client, customer-reported, needs-author-feedback, no-recent-activity
