### ISSUE TITLE
[FEATURE REQ] Connecting to Azure-AD via proxy

### ISSUE THREAD

**Issue by stephanpelikan** [Azure/azure-sdk-for-java#26493] opened 2022-01-14 07:59 UTC
**Is your feature request related to a problem? Please describe.**

We want to use Azure-AD authentication in a Spring Boot application as shown here:
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/azure-spring-boot-starter-active-directory/README.md
Our system is in a private cloud and only allowed to connect to internet via proxy. Using Azure-AD oauth the application receives an token via redirect after login and that token needs to be validated. For this validation http-requests are sent to Azure-AD and for those requests there is no possibility to configure a http-proxy.

At least for this use case I could identify 2 (or maybe also 3) usages of Spring's RestTemplate to connect to Azure-AD:

1. Request to fetch the token: For this one can add this code to the configuration class (extending AADWebSecurityConfigurerAdapter) but that needs to duplicate code from `DefaultAuthorizationCodeTokenResponseClient#DefaultAuthorizationCodeTokenResponseClient()`:
```java
    protected OAuth2AccessTokenResponseClient<OAuth2AuthorizationCodeGrantRequest> accessTokenResponseClient() {
        final var result = super.accessTokenResponseClient();
        if (result instanceof DefaultAuthorizationCodeTokenResponseClient) {
            ((DefaultAuthorizationCodeTokenResponseClient) result)
                    .setRestOperations(oauth2ClientRestOperations());
        }
        return result;
    }

    @Bean
    public RestOperations oauth2ClientRestOperations() {
        final var restTemplate = new RestTemplate(
                Arrays.asList(new FormHttpMessageConverter(),
                new OAuth2AccessTokenResponseHttpMessageConverter()));
        restTemplate.setErrorHandler(new OAuth2ErrorResponseErrorHandler());
        if (StringUtils.isNotBlank(proxyHost)
                && (proxyPort != -1)) {
            restTemplate.setRequestFactory(proxyAwareRequestFactory());
        }
        return restTemplate;
    }

    private ClientHttpRequestFactory proxyAwareRequestFactory() {
        return new HttpComponentsClientHttpRequestFactory(
                HttpClientBuilder.create().setProxy(new HttpHost(proxyHost, proxyPort, "http")).build());
    }
```
2. Request(s) for validating the token: For this I could find two places in which RestTemplates are created without any possibility to customize them:
https://github.com/Azure/azure-sdk-for-java/blob/2cd30e97440042b17a94db3438865ed530fb4c08/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/aad/AADIssuerJWSKeySelector.java#L73
https://github.com/Azure/azure-sdk-for-java/blob/2cd30e97440042b17a94db3438865ed530fb4c08/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/aad/AADJwtDecoderProviderConfiguration.java#L26

**Describe the solution you'd like**

There should be one easy and centralized configuration for all RestTemplates used for Azure-AD authentication. There are two possibilities for RestTemplate customization (see https://www.baeldung.com/spring-rest-template-builder). Anyone is fine and should be predefined like this:
```java
public abstract class AADWebSecurityConfigurerAdapter extends WebSecurityConfigurerAdapter {
    protected RestTemplateBuilder azureAdRestTemplateBuilder() {
        return new RestTemplateBuilder();
    }
```
This Builder needs to be used by the code mentioned above and can be overwritten by the deriving class like this:
```java
@Configuration
public class AzureAdOAuth2Configuration extends AADWebSecurityConfigurerAdapter {
    @Value("${azure.activedirectory.proxyHost:}")
    private String proxyHost;
    @Value("${azure.activedirectory.proxyPort:-1}")
    private int proxyPort;

    protected RestTemplateBuilder azureAdRestTemplateBuilder() {
        return super.azureAdRestTemplateBuilder()
                  .requestFactory(proxyAwareRequestFactory());
    }

    private ClientHttpRequestFactory proxyAwareRequestFactory() {
        return new HttpComponentsClientHttpRequestFactory(
                HttpClientBuilder.create().setProxy(new HttpHost(proxyHost, proxyPort, "http")).build());
    }
```

**Describe alternatives you've considered**

As an alternative I tried to use System properties `http.proxyHost` and `http.proxyPort` but that didn't work.

**Additional context**
No additional context.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by chenrujun** [comment] 2022-01-18 00:23
Hi, @stephanpelikan , thanks for reaching out.

Added this issue into backlog. We will consider to implement it in the future.

**Comment by pavan5000** [comment] 2022-03-03 16:27
@stephanpelikan  I'm in the same boat as you in this topic, and my springboot application is unable to access AzureAD over proxy. Could you please explain how you went about achieving this?

**Comment by stephanpelikan** [comment] 2022-03-03 18:06
As mentioned in the description there are different situations in which requests are sent to Azure-AD. Unfortunately, only for one is a possibility to set a proxy by adding some code (see bullet-point 1 in the description). For the others (bullet-point 2) it is not possible to adopt the RestTemplate. Therefore I didn't achieve to get access via proxy. Unless the proposed solution or something similar is implemented it is not possible to do authentication via Azure-AD behind a proxy.

**Comment by pavan5000** [comment] 2022-03-03 20:47
Thanks for the information @stephanpelikan .  I tried all the possible ways override but no luck so far. I hope, AzureSDK team will add this feature soon.

**Comment by stephanpelikan** [comment] 2022-04-06 08:37
Until this issue is resolved, maybe this helps: Using these JVM parameters I could use Azure-AD login:

> -Dhttps.proxyHost=192.168.56.1 -Dhttps.proxyPort=3128  -Dhttp.proxyHost=192.168.56.1 -Dhttp.proxyPort=3128 -DproxySet=true

Of course you need to adopt this to your proxy's IP address and port.

This is only a workaround for testing Azure-AD login. Other http(s) connections of your application will also use that proxy and therefore might fail. For me it is crucial to be able to set proxy configuration for each http-client of my application independently.

**Comment by stliu** [comment] 2022-08-14 12:17
I create a PR for this https://github.com/Azure/azure-sdk-for-java/pull/30456 issue @stephanpelikan would you please take a look, thanks

**Comment by chenrujun** [comment] 2022-09-05 01:56
Reopen this issue, because of https://github.com/Azure/azure-sdk-for-java/pull/30456#issuecomment-1236470413

**Comment by chenrujun** [comment] 2022-09-09 05:23
Closing in favor of https://github.com/Azure/azure-sdk-for-java/pull/30786

**Comment by chenrujun** [comment] 2022-09-09 05:30
Link to PR of updating reference doc: https://github.com/Azure/azure-sdk-for-java/pull/30882

**Comment by HNE74** [comment] 2022-09-20 07:26
It's really great that the proxy issue will be resolved. Would there any more information available about how to implement the  `RestTemplateCustomizer` bean?
I wonder if customzing the RestTemplate will also help for carrying out the authorization code flow. In Azure SDK 4.2.0, during token validation, the class com.azure.spring.cloud.autoconfigure.aad.implementation.graph.GraphClient is used to verify the user's groups. This class doesn't use the RestTemplate but a java.net.HttpURLConnection for access the Microsoft Graph service.

**Comment by chenrujun** [comment] 2022-09-20 08:07
Hi, @HNE74 

> Would there any more information available about how to implement the RestTemplateCustomizer bean?

Here is an example about how to configure a `RestTemplateCustomizer` bean:

```java
    @Configuration
    static class RestTemplateProxyCustomizerConfiguration {

        static final SimpleClientHttpRequestFactory FACTORY = createProxyFactory();

        static SimpleClientHttpRequestFactory createProxyFactory() {
            Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("localhost", 8080));
            SimpleClientHttpRequestFactory factory = new SimpleClientHttpRequestFactory();
            factory.setProxy(proxy);
            return factory;
        }

        @Bean
        public RestTemplateCustomizer proxyRestTemplateCustomizer() {
            return (RestTemplate restTemplate) -> restTemplate.setRequestFactory(FACTORY);
        }
    }
```

**Comment by chenrujun** [comment] 2022-09-20 08:17
@HNE74

> class com.azure.spring.cloud.autoconfigure.aad.implementation.graph.GraphClient is used to verify the user's groups. This class doesn't use the RestTemplate but a java.net.HttpURLConnection for access the Microsoft Graph service.

Good point. I missed that one. I'll try to use **RestTemplate** instead of **HttpURLConnection** in GraphClient .

**Comment by HNE74** [comment] 2022-09-20 08:49
Great, many thanks for providing the configuration example 👍

**Comment by chenrujun** [comment] 2022-09-20 08:59
> @HNE74
> 
> > class com.azure.spring.cloud.autoconfigure.aad.implementation.graph.GraphClient is used to verify the user's groups. This class doesn't use the RestTemplate but a java.net.HttpURLConnection for access the Microsoft Graph service.
> 
> Good point. I missed that one. I'll try to use **RestTemplate** instead of **HttpURLConnection** in GraphClient .

Reopen this issue. Need to replace all **HttpURLConnection** by **RestTemplate** used in Azure AD related http requests.

**Comment by chenrujun** [comment] 2022-09-26 02:53
Closing this issue in favor of https://github.com/Azure/azure-sdk-for-java/pull/31048

**Closed** 2022-09-26 02:55 UTC
Labels: Client, customer-reported, feature-request, azure-spring, azure-spring-aad, azure-spring-copper

**Comment by chenrujun** [comment] 2022-09-29 01:14
Closing this issue because It's fixed in spring-cloud-azure 4.4.0. https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/CHANGELOG.md#440-2022-09-26

**Comment by chenrujun** [comment] 2022-11-21 01:17
Hi, @martfol 
Thanks for reaching out.

> not sure if this is the right place for my question but we're currently really struggling with connecting our spring boot application to azure AD via proxy

In this case, my suggestion is to create a new issue.

> I was following [this tutorial](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure?tabs=maven#connecting-to-azure-ad-via-proxy) and I also found [this list of global properties](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure-appendix#global-properties), which apparently also contain some proxy-relevant settings.

Sorry to make you confused. Currently, the global properties didn't work for Azure AD. To enable the proxy function, you should config a bean described in [this tutorial](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure?tabs=maven#connecting-to-azure-ad-via-proxy) .

> java.lang.ClassCastException: class org.springframework.security.authentication.UsernamePasswordAuthenticationToken cannot be cast to class org.springframework.security.oauth2.client.authentication.OAuth2LoginAuthenticationToken

I'm not sure why this happened. If the problem still exists after you used the method described [this tutorial](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure?tabs=maven#connecting-to-azure-ad-via-proxy) , please provide a simple project to reproduce this problem.

> what's the difference between the functionality of the spring.cloud.azure.proxy.* properties versus the functionality of the proxyRestTemplateCustomizer bean?

Currently, `spring.cloud.azure.proxy.*` didn't take effect for all features provided by `spring-cloud-azure-starter-active-directory`. Please use `proxyRestTemplateCustomizer` instead.

**Comment by martfol** [comment] 2022-11-21 09:44
Hi @chenrujun , thanks for your quick reply! Maybe we're able to solve this with just one more comment :-) As I've mentioned, we need to provide a username/password for the proxy server. I tried adding it to the resttemplate using a ClientHttpRequestInterceptor, however it does not seem to work. The Azure AD Login works fine, but when redirected back to the application, the following response is shown:

_Login with OAuth 2.0
[authorization_request_not_found]_

Here's our current code:

```
@Configuration
public class AzureConfig {

  @Bean
  public RestTemplateCustomizer proxyRestTemplateCustomizer() {
    return (RestTemplate restTemplate) -> {
      Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress(PROXY_HOST, PROXY_PORT));
      SimpleClientHttpRequestFactory requestFactory = new SimpleClientHttpRequestFactory();
      requestFactory.setProxy(proxy);
      restTemplate.setRequestFactory(requestFactory);
      restTemplate.setInterceptors(Collections.singletonList(new ProxyAuthHeaderReqeustInterceptor()));
    };
  }

  class ProxyAuthHeaderReqeustInterceptor implements ClientHttpRequestInterceptor {

    @Override
    public ClientHttpResponse intercept(HttpRequest request, byte[] body,
        ClientHttpRequestExecution execution) throws IOException {
      HttpHeaders headers = request.getHeaders();
      headers.add(HttpHeaders.PROXY_AUTHORIZATION,
          "Basic " + Base64.getEncoder().encodeToString((PROXY_USER + ':' + PROXY_PW).getBytes(
              StandardCharsets.UTF_8)));
      return execution.execute(request, body);
    }
  }

}
```

Could you please provide some official preferred/recommended way for your _proxyRestTemplateCustomizer_ solution to implement also a username/password for the proxy server? (Maybe extending the reference documentation with this could also help others in the future.)

Thanks a lot in advance!

**Comment by martfol** [comment] 2022-11-21 13:38
UPDATE - this solution worked for us to establish a connection to Azure AD via proxy using username/password: https://stackoverflow.com/questions/31273236/spring-resttemplate-and-proxy-auth

(thanks @chenrujun for you time)

**Comment by chenrujun** [comment] 2022-11-22 01:03
@martfol 

Glad to hear that.
Thanks for sharing the information.
