### ISSUE TITLE
OpenAIClient.getChatCompletionsStream()， found that there are garbled characters in the returned data.

### ISSUE THREAD

**Issue by Ch-BlackR** [Azure/azure-sdk-for-java#35522] opened 2023-06-19 09:49 UTC
**Query/Question**
I am using the OpenAIClient.getChatCompletionsStream() method and found that there are garbled characters in the returned data. I tried to set the header of httpClient with the following code:

```
        this.CLIENT = new OpenAIClientBuilder()
            .httpClient(HttpClient.createDefault(new HttpClientOptions()
                .setHeaders(Collections.singletonList(new Header("Accept-Charset", "utf-8")))))
            .endpoint(ENDPOINT)
            .credential(new AzureKeyCredential(AZURE_OPENAI_KEY))
            .buildClient();
```

However, it still cannot solve the problem of garbled characters. What should I do to solve this issue?

**Setup (please complete the following information if applicable):**
 - OS: centos
 - IDE: IntelliJ
 - Library/Libraries: 
```
       <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-ai-openai</artifactId>
            <version>1.0.0-beta.1</version>
        </dependency>
```

**Comment by mssfang** [comment] 2023-06-20 16:29
@Ch-BlackR Thanks for sharing the output. Do you mind sharing the input with us or a simple sample that I can use to reproduce the issue locally?

**Comment by Ch-BlackR** [comment] 2023-06-21 03:56
> @Ch-BlackR感谢您分享输出。您介意与我们分享输入内容或我可以用来在本地重现问题的简单示例吗？

Here is the unit testing code based on springboot2.7.6. I tried to run it locally in IntelliJ IDEA five times and encountered garbled characters once.

```
@SpringBootTest
public class AzureGptServiceTest {

@Test
void getChatCompletionsStream() {
    OpenAIClient CLIENT = new OpenAIClientBuilder()
        .httpClient(HttpClient.createDefault(new HttpClientOptions()
            .setHeaders(Collections.singletonList(new Header("Accept-Charset", "utf-8")))))
        .endpoint(ENDPOINT)
        .credential(new AzureKeyCredential(AZURE_OPENAI_KEY))
        .buildClient();

    ChatCompletionsOptions options = new ChatCompletionsOptions(Collections.singletonList(new ChatMessage(ChatRole.USER).setContent("Write a year-end summary report")));

    IterableStream<ChatCompletions> completionsStream = CLIENT.getChatCompletionsStream("chatgpt3-5", options);

    completionsStream.forEach(completion -> {
        for (ChatChoice choice : completion.getChoices()) {
            ChatMessage message = choice.getDelta();
            if (message != null && message.getContent() != null) {
                System.out.print(message.getContent());
            }
        }
    });
}
}
```

![image](https://github.com/Azure/azure-sdk-for-java/assets/38206082/058433d6-566a-4bb5-adf5-b6f33c577fdb)

**Comment by mssfang** [comment] 2023-06-21 23:34
@Ch-BlackR Thanks for sharing it. I also can reproduce the garbled characters now. Will take time to investigate it.

**Comment by mssfang** [comment] 2023-07-10 23:13
PR is merged and we target to release it next week.

**Closed by mssfang** 2023-07-10 23:13 UTC
Labels: question, Client, customer-reported, pillar-reliability, needs-team-attention, OpenAI

**Comment by mssfang** [comment] 2023-07-19 02:41
Updates: 1.0.0-beta.3 released

https://repo1.maven.org/maven2/com/azure/azure-ai-openai/1.0.0-beta.3/

**Comment by liuyu-struggle** [comment] 2023-07-19 02:58
> 更新：1.0.0-beta.3 发布
> 
> https://repo1.maven.org/maven2/com/azure/azure-ai-openai/1.0.0-beta.3/

@mssfang  Thank you very much for publishing！But currently, I still cannot rely on the beta 3 version in my program。

**Comment by mssfang** [comment] 2023-07-19 05:55
> rely
Thanks @liuyu-struggle 
Does the same issue still exist? Is the reason to block using it?

**Comment by liuyu-struggle** [comment] 2023-07-19 06:02
> 谢谢@liuyu-struggle 同样的问题还存在吗？是阻止使用它的原因吗？

@mssfang Currently, it still exists, I don't know if it's related to my environment，
![image](https://github.com/Azure/azure-sdk-for-java/assets/37584392/9eb452a4-df25-4fa4-8b23-46663aa57460)

**Comment by liuyu-struggle** [comment] 2023-07-20 02:15
> > > 谢谢@liuyu-struggle 同样的问题还存在吗？是阻止使用它的原因吗？
> > 
> > 
> > @mssfang Currently, it still exists, I don't know if it's related to my environment， ![image](https://user-images.githubusercontent.com/37584392/254477632-9eb452a4-df25-4fa4-8b23-46663aa57460.png)
> 
> It should be something wrong in your environment. Please let me know if the garbled characters issue still exist.

@mssfang  Thank you! Try again today and you can rely on the latest version，Yesterday, it was possible that we had a cache here.
