### ISSUE TITLE
[BUG] BlobBatchClient::deleteBlobs does not raise BlobBatchStorageException on failure

### ISSUE THREAD

**Issue by clarkbreyman-yammer** [Azure/azure-sdk-for-java#18507] opened 2021-01-08 06:53 UTC
**Describe the bug**
If one or more blob deletes submitted via the batch client fails, no exception is raised unless the result object status codes are inspected. 

***Exception or Stack Trace***
The problem is not that an exception is raised but rather the failure is silent until I go looking for it. 

**To Reproduce**
1. Create a blob
2. Take a 60s lease on the blob
3. Attempt to delete it via `BlobBatchClient::deleteBlobs` operation BEFORE lease expiry
4. Note that no exception is thrown
5. Examine the response object
6. Note that the exception is thrown AFTER the response object is examined, not on return from deleteBlobs. 

***Code Snippet***
```
  @Test(expected = BlobBatchStorageException.class)
  public void testBatchDeleteExceptions() {
    final String CONTAINER_NAME = "batch-delete-bug-" + System.currentTimeMillis();
    final String BLOB_NAME = "leased-blob";
    final byte[] BLOB_DATA = "test content".getBytes(StandardCharsets.UTF_8);
    final String connectionString =("DefaultEndpointsProtocol=https"
        + ";AccountName="
        + ACCOUNT_NAME
        + ";AccountKey="
        + ACCOUNT_KEY);

    BlobServiceClient serviceClient = new BlobServiceClientBuilder()
        .connectionString(connectionString)
        .buildClient();

    //-- create container
    BlobContainerClient containerClient = serviceClient.getBlobContainerClient(CONTAINER_NAME);

    try {
      containerClient.create();

      //-- create blob
      BlobClient blobClient = containerClient.getBlobClient(BLOB_NAME);
      blobClient.upload(new ByteArrayInputStream(BLOB_DATA), BLOB_DATA.length);

      //-- lease blob
      BlobLeaseClient leaseClient = new BlobLeaseClientBuilder()
          .blobClient(blobClient)
          .buildClient();
      leaseClient.acquireLease(60);

      //-- batch delete blob
      BlobBatchClient batchClient = new BlobBatchClientBuilder(serviceClient).buildClient();
      PagedIterable<Response<Void>> responses = batchClient
          .deleteBlobs(
              Collections.singletonList(containerClient.getBlobContainerUrl() + "/" + BLOB_NAME),
              DeleteSnapshotsOptionType.INCLUDE
          );

      // THIS SHOULD NOT BE REQUIRED assertEquals(new Integer(200), responses.stream().map(r -> r.getStatusCode()).findFirst().get());

      //-- ensure blob is delete - failure indicates silent error
      assertFalse(blobClient.exists());
    } finally{
      containerClient.delete();
    }
  }
```

**Expected behavior**
I would expect a BlobBatchStorageException to be thrown ***without*** needing to inspect the status code.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: reproed on Linux and MacOs
 - IDE : Intellij and command line maven 
 - Version of the Library used 12.7.0

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by clarkbreyman-yammer** [comment] 2021-01-08 06:59
The exception is raised on the PagedIterable::stream() call, not the deleteBlobs call.

**Comment by rickle-msft** [comment] 2021-01-11 17:57
@clarkbreyman-yammer Thanks for opening this issue. Although your confusion is understandable, I believe this behavior is actually by design. The reason is that there are really two different "phases" to a batch operation. One is sending/receiving the batch itself, the other is processing the requests/responses that comprise the batch. If the overall batch operation fails, you'll get an exception on the top level. If one of the component requests fails, you'll only see that when you go to inspect the individual responses. This is to support "fire and forget" scenarios, which are common with batching.

I think it might be a reasonable request to ask for a configuration on the builder or something similar that allows you to indicate you want us to throw if any of the component requests fail. Let me know if that's a direction you'd like to head.

@alzimmermsft FYI to fact check my explanation

**Comment by alzimmermsft** [comment] 2021-01-11 19:17
@rickle-msft is correct, the behavior is to eagerly throw an exception when the top-level batch request is rejected/malformed/etc and to throw sub-level batch operation exceptions when they are inspected to allow for handling them individually.

This would be a good area for enhancements as we already offer support for eagerly throwing an exception if any batch operation fails when using the [`BlobBatchClient.submitBatchWithResponse`](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob-batch/src/main/java/com/azure/storage/blob/batch/BlobBatchClient.java#L85) API.

**Comment by rickle-msft** [comment] 2021-01-19 23:07
@clarkbreyman-yammer I am going to close this issue as I think the question has been addressed with the option alan pointed out. If you need further assistance or clarification, feel free to reach out

**Closed** 2021-01-19 23:08 UTC
Labels: Client, Storage, customer-reported
