### ISSUE TITLE
[FEATURE REQ] Provide a convenient method in EventProcessorClientBuilder to configure initialPartitionEventPosition for all partitions

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#26432] opened 2022-01-12 11:01 UTC
**Is your feature request related to a problem? Please describe.**
The EventProcessorClientBuilder provides a `initialPartitionEventPosition` to configure the initial event position for each partition. But there're cases when users simply want to start from `earliest` or `latest` for each partition. In such cases, they have to duplicate this configuration for the number of partitions times. And if users are configuring these positions from a Spring Boot property file, they have to write such properties multiple times. In Spring Cloud Stream, we can provide a convenient way for users to specify `earliest` or `latest` for all partitions, but we need to find the number of partitions an event hub has before passing it to the builder.

**Describe the solution you'd like**
The EventProcessorClientBuilder provides such a convenient method to configure the initial event position for all partitions.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by joshfree** [comment] 2022-01-13 19:49
@saragluna could you and @conniey chat and make sure we prioritize this at the right level to support spring?

**Comment by conniey** [comment] 2022-01-18 23:46
This seems like a duplicate of #11431

**Closed** 2022-01-18 23:47 UTC
Labels: Event Hubs, Client, feature-request
