### ISSUE TITLE
[Core] Convert InputStream to Flux<ByteBuffer> 

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk-for-java#10337] opened 2020-04-17 16:53 UTC
https://github.com/Azure/azure-sdk-for-java/pull/9953#discussion_r406831450

Consider to add a helper method that convert InputStream to Flux<ByteBuffer> in FluxUtil class.

**Comment by alzimmermsft** [comment] 2020-04-20 17:01
Closing as a duplicate of #9716

**Closed by alzimmermsft** 2020-04-20 17:01 UTC
Labels: Azure.Core
