### ISSUE TITLE
[BUG] Update all Track 1 packages to point to new versions

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-java#9972] opened 2020-04-08 16:23 UTC
When you search for any package on mvnrepository.com you see this:

https://mvnrepository.com/search?q=eventhubs&sort=popular
![image](https://user-images.githubusercontent.com/2163001/78808486-5529df80-797a-11ea-8694-2799f216146e.png)

We need to go through all old packages and update the description to point to the new versions.

**Comment by g2vinay** [comment] 2020-04-08 16:27
Use the description tag and not relocation tag with this message:
Update the package links accordingly in the sample below.

This library has been replaced by the following new Azure SDKs. You can read about the new Azure SDKs at https://aka.ms/azsdkvalueprop.
        The latest libraries to interact with the Azure KeyVault service are:
        * https://search.maven.org/artifact/com.azure/azure-security-keyvault-keys
        * https://search.maven.org/artifact/com.azure/azure-security-keyvault-secrets
        * https://search.maven.org/artifact/com.azure/azure-security-keyvault-certificates
        It is recommended that you move to the new package.

**Comment by joshfree** [comment] 2020-04-14 21:26
Duplicate of https://github.com/Azure/azure-sdk-for-java/issues/7968

/cc @conniey

**Closed by joshfree** 2020-04-14 21:26 UTC
Labels: Client, common
