### ISSUE TITLE
[BUG] ProxyOptions passed in BlobServiceClientBuilder.clientOptions() has no effect

### ISSUE THREAD

**Issue by turcsanyip** [Azure/azure-sdk-for-java#28900] opened 2022-05-17 08:41 UTC
**Describe the bug**

`ProxyOptions` object can be passed in `BlobServiceClientBuilder` but it has no effect, no proxy settings will be used.

***Code Snippet***
```
BlobServiceClientBuilder clientBuilder = new BlobServiceClientBuilder();
ProxyOptions proxyOptions = ...
ClientOptions clientOptions = new HttpClientOptions().setProxyOptions(proxyOptions);
clientBuilder.clientOptions(clientOptions);
```

**Expected behavior**
`ProxyOptions` passed in `BlobServiceClientBuilder.clientOptions()` should work.

It seems to me that the root cause is that `BuilderHelper` gets `ClientOptions ` object but does not pass it forward to `HttpPipelineBuilder`:
https://github.com/Azure/azure-sdk-for-java/blob/957740dbb168bf41261158e2aa5014d320733125/sdk/storage/azure-storage-queue/src/main/java/com/azure/storage/queue/implementation/util/BuilderHelper.java#L156-L220

**Comment by joshfree** [comment] 2022-05-17 16:09
Hi @turcsanyip thanks for reaching out to us via this GitHub issue.  Someone from the `Storage SDK` team will follow up shortly.

**Comment by rickle-msft** [comment] 2022-05-17 21:34
Hi, @turcsanyip. Thank you for reporting this. I believe this is a duplicate of #28783. If so, I'll close this issue and contain the conversation to the other one.

**Comment by turcsanyip** [comment] 2022-05-17 21:52
Sure, thanks!
I did not find that one but they are the same. Looked for "ProxyOptions" only but yeah, it is a more generic issue with "ClientOptions". Will follow https://github.com/Azure/azure-sdk-for-java/issues/28783. Thanks

**Closed** 2022-05-17 21:54 UTC
Labels: question, Storage, Client, customer-reported
