### ISSUE TITLE
[BUG] ChangeFeedProcessor causes out of memory error due to slow consumer

### ISSUE THREAD

**Issue by zhouchong90** [Azure/azure-sdk-for-java#7077] opened 2020-01-02 19:26 UTC
**Describe the bug**
When we have a slow consumer using the change feed processor, it goes out of memory very soon.

**To Reproduce**
``` java
public void startFeedProcessor() {
        ChangeFeedProcessor changeFeedProcessorInstance = getChangeFeedProcessor(hostName, organizationCosmosFeedContainer, cosmosLeaseContainer);
        changeFeedProcessorInstance.start().subscribe();
    }

    private ChangeFeedProcessor getChangeFeedProcessor(String hostName, CosmosContainer feedContainer, CosmosContainer leaseContainer) {
        ChangeFeedProcessorOptions changeFeedProcessorOptions = new ChangeFeedProcessorOptions();
        changeFeedProcessorOptions.leasePrefix(changeFeedProcessorConnection.getOrganizationLeasePrefix());
        changeFeedProcessorOptions.feedPollDelay(Duration.ofMillis(changeFeedProcessorConnection.getOrganizationFeedPollDelay()));
        changeFeedProcessorOptions.maxItemCount(changeFeedProcessorConnection.getOrganizationMaxItemCount());
        return ChangeFeedProcessor.Builder()
                .hostName(hostName)
                .feedContainer(feedContainer)
                .leaseContainer(leaseContainer)
                .options(changeFeedProcessorOptions)
                .handleChanges(docs -> {
                    try {
                        log.info("See doc:" + docs);
                        Thread.sleep(10000);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                })
                .build();
    }
```

**Expected behavior**
The change feed processor should pull the next document only when the previous document has been processed.

**Setup (please complete the following information):**
 - OS: [e.g. iOS] . Mac
 - IDE : [e.g. IntelliJ] . IntelliJ
 - Version of the Library used  
```
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-cosmos</artifactId>
            <version>3.5.0</version>
        </dependency>
```

**Additional context**
In the source code, I see this code snippet in PartitionControllerImpl class:

https://github.com/Azure/azure-sdk-for-java/blob/fe2039f0bc4255c6ffaf6c89e5adc1b8526778a5/sdk/cosmos/microsoft-azure-cosmos/src/main/java/com/azure/data/cosmos/internal/changefeed/implementation/PartitionControllerImpl.java#L141

It seems that the WorkerTask is being scheduled and subscribed in the background in an elastic thread pool, and the producer of change feed document in PartitionLoadBalancerImpl will keep producing regardless of the downstream consumer's status.
It'll be better if the producer will wait for the WorkerTask to complete then process the next item.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by milismsft** [comment] 2020-01-09 20:18
The PartitionLoadBalancerImpl job is to schedule workers for each partition on the targeted feed conatiner/collection, not for each document being processed. The interesting code line you should look at is https://github.com/Azure/azure-sdk-for-java/blob/fe2039f0bc4255c6ffaf6c89e5adc1b8526778a5/sdk/cosmos/microsoft-azure-cosmos/src/main/java/com/azure/data/cosmos/internal/changefeed/implementation/PartitionProcessorImpl.java#L69, and as you can see, we are pausing and wait until we process the whole batch before we pick another. There are multiple documents in the batch and you can control the size of it via the maxItemCount.

However that will not explain the out-of-memory issue you were seeing. I will try to reproduce it locally though and let you know.

**Comment by milismsft** [comment] 2020-06-03 07:28
Closing as we are unable to reproduce this issue using latest Cosmos SDK 4.x.

**Closed by milismsft** 2020-06-03 07:28 UTC
Labels: Client, Cosmos
