### ISSUE TITLE
[BUG] NoClassDefFoundError com/fasterxml/jackson/databind/AnnotationIntrospector$XmlExtensions while calling azure data lake

### ISSUE THREAD

**Issue by git831458** [Azure/azure-sdk-for-java#28686] opened 2022-05-06 13:56 UTC
I am getting below exception while connecting to the azure data lake using service principle.

Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/AnnotationIntrospector$XmlExtensions
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at com.fasterxml.jackson.dataformat.xml.XmlMapper.<clinit>(XmlMapper.java:113)

**Below is the dependency tree**:
)
[INFO] com.msci.esg.esgm2:all-data-feeds:jar:1.0-SNAPSHOT
[INFO] +- com.msci.esg.esgm2:feeds-common-lib:jar:1.0-SNAPSHOT:compile
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.11:compile
[INFO] |  \- com.databricks:dbutils-api_2.11:jar:0.0.3:compile
[INFO] +- com.msci.esg.esgm2:records-resolver-client:jar:1.0-SNAPSHOT:compile
[INFO] |  \- com.google.code.gson:gson:jar:2.8.5:compile
[INFO] +- com.msci.esg.esgm2:dataset-resolver-client:jar:1.0-SNAPSHOT:compile
[INFO] |  +- org.slf4j:slf4j-log4j12:jar:1.7.30:compile
[INFO] |  |  +- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO] |  |  \- log4j:log4j:jar:1.2.17:compile
[INFO] |  \- com.google.guava:guava:jar:20.0:compile
[INFO] +- com.msci.esg.esgm2:wsdata-service-client:jar:1.0-SNAPSHOT:compile
[INFO] +- com.msci.esg.esgm2:esg-data-service-client:jar:1.0-SNAPSHOT:compile
[INFO] +- com.azure:azure-identity:jar:1.5.0:compile
[INFO] |  +- com.azure:azure-core:jar:1.27.0:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.13.2:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-core:jar:2.13.2:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.13.2:compile
[INFO] |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.13.2:compile
[INFO] |  |  |  +- org.codehaus.woodstox:stax2-api:jar:4.2.1:compile
[INFO] |  |  |  \- com.fasterxml.woodstox:woodstox-core:jar:6.2.7:compile
[INFO] |  |  +- io.projectreactor:reactor-core:jar:3.4.14:compile
[INFO] |  |  |  \- org.reactivestreams:reactive-streams:jar:1.0.3:compile
[INFO] |  |  \- io.netty:netty-tcnative-boringssl-static:jar:2.0.47.Final:compile
[INFO] |  |     \- io.netty:netty-tcnative-classes:jar:2.0.47.Final:compile
[INFO] |  +- com.azure:azure-core-http-netty:jar:1.11.9:compile
[INFO] |  |  +- io.netty:netty-handler:jar:4.1.73.Final:compile
[INFO] |  |  +- io.netty:netty-handler-proxy:jar:4.1.73.Final:compile
[INFO] |  |  |  \- io.netty:netty-codec-socks:jar:4.1.73.Final:compile
[INFO] |  |  +- io.netty:netty-codec-http:jar:4.1.73.Final:compile
[INFO] |  |  +- io.netty:netty-codec-http2:jar:4.1.73.Final:compile
[INFO] |  |  +- io.netty:netty-transport-native-unix-common:jar:4.1.73.Final:compile
[INFO] |  |  +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.73.Final:compile
[INFO] |  |  |  \- io.netty:netty-transport-classes-epoll:jar:4.1.73.Final:compile
[INFO] |  |  +- io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.73.Final:compile
[INFO] |  |  |  \- io.netty:netty-transport-classes-kqueue:jar:4.1.73.Final:compile
[INFO] |  |  \- io.projectreactor.netty:reactor-netty-http:jar:1.0.15:compile
[INFO] |  |     +- io.netty:netty-resolver-dns:jar:4.1.72.Final:compile
[INFO] |  |     |  \- io.netty:netty-codec-dns:jar:4.1.72.Final:compile
[INFO] |  |     +- io.netty:netty-resolver-dns-native-macos:jar:osx-x86_64:4.1.72.Final:compile
[INFO] |  |     |  \- io.netty:netty-resolver-dns-classes-macos:jar:4.1.72.Final:compile
[INFO] |  |     \- io.projectreactor.netty:reactor-netty-core:jar:1.0.15:compile
[INFO] |  +- com.microsoft.azure:msal4j:jar:1.11.3:compile
[INFO] |  |  \- com.nimbusds:oauth2-oidc-sdk:jar:9.22.1:compile
[INFO] |  |     +- com.github.stephenc.jcip:jcip-annotations:jar:1.0-1:compile
[INFO] |  |     +- com.nimbusds:content-type:jar:2.2:compile
[INFO] |  |     +- com.nimbusds:lang-tag:jar:1.5:compile
[INFO] |  |     \- com.nimbusds:nimbus-jose-jwt:jar:9.15.2:compile
[INFO] |  +- com.microsoft.azure:msal4j-persistence-extension:jar:1.1.0:compile
[INFO] |  |  \- net.java.dev.jna:jna:jar:5.5.0:compile
[INFO] |  +- net.java.dev.jna:jna-platform:jar:5.6.0:compile
[INFO] |  \- net.minidev:json-smart:jar:2.4.7:compile
[INFO] |     \- net.minidev:accessors-smart:jar:2.4.7:compile
[INFO] |        \- org.ow2.asm:asm:jar:9.1:compile
[INFO] +- com.azure:azure-storage-file-datalake:jar:12.9.0:compile
[INFO] |  \- com.azure:azure-storage-blob:jar:12.16.0:compile
[INFO] |     +- com.azure:azure-storage-common:jar:12.15.1:compile
[INFO] |     \- com.azure:azure-storage-internal-avro:jar:12.2.1:compile
[INFO] +- org.projectlombok:lombok:jar:1.18.16:compile
[INFO] +- com.msci.esg.esgm2:feeds-transformation-common-lib:jar:1.0-SNAPSHOT:compile
[INFO] +- org.apache.spark:spark-sql_2.12:jar:3.0.1:compile
[INFO] |  +- com.univocity:univocity-parsers:jar:2.9.0:compile
[INFO] |  +- org.apache.spark:spark-sketch_2.12:jar:3.0.1:compile
[INFO] |  +- org.apache.spark:spark-core_2.12:jar:3.0.1:compile
[INFO] |  |  +- com.thoughtworks.paranamer:paranamer:jar:2.8:compile
[INFO] |  |  +- org.apache.avro:avro:jar:1.8.2:compile
[INFO] |  |  |  +- org.apache.commons:commons-compress:jar:1.8.1:compile
[INFO] |  |  |  \- org.tukaani:xz:jar:1.5:compile
[INFO] |  |  +- org.apache.avro:avro-mapred:jar:hadoop2:1.8.2:compile
[INFO] |  |  |  \- org.apache.avro:avro-ipc:jar:1.8.2:compile
[INFO] |  |  +- com.twitter:chill_2.12:jar:0.9.5:compile
[INFO] |  |  |  \- com.esotericsoftware:kryo-shaded:jar:4.0.2:compile
[INFO] |  |  |     +- com.esotericsoftware:minlog:jar:1.3.0:compile
[INFO] |  |  |     \- org.objenesis:objenesis:jar:2.5.1:compile
[INFO] |  |  +- com.twitter:chill-java:jar:0.9.5:compile
[INFO] |  |  +- org.apache.hadoop:hadoop-client:jar:2.7.4:compile
[INFO] |  |  |  +- org.apache.hadoop:hadoop-common:jar:2.7.4:compile
[INFO] |  |  |  |  +- commons-cli:commons-cli:jar:1.2:compile
[INFO] |  |  |  |  +- xmlenc:xmlenc:jar:0.52:compile
[INFO] |  |  |  |  +- commons-httpclient:commons-httpclient:jar:3.1:compile
[INFO] |  |  |  |  +- commons-io:commons-io:jar:2.4:compile
[INFO] |  |  |  |  +- org.mortbay.jetty:jetty-sslengine:jar:6.1.26:compile
[INFO] |  |  |  |  +- javax.servlet.jsp:jsp-api:jar:2.1:runtime
[INFO] |  |  |  |  +- commons-configuration:commons-configuration:jar:1.6:compile
[INFO] |  |  |  |  |  \- commons-digester:commons-digester:jar:1.8:compile
[INFO] |  |  |  |  +- org.apache.hadoop:hadoop-auth:jar:2.7.4:compile
[INFO] |  |  |  |  |  \- org.apache.directory.server:apacheds-kerberos-codec:jar:2.0.0-M15:compile
[INFO] |  |  |  |  |     +- org.apache.directory.server:apacheds-i18n:jar:2.0.0-M15:compile
[INFO] |  |  |  |  |     +- org.apache.directory.api:api-asn1-api:jar:1.0.0-M20:compile
[INFO] |  |  |  |  |     \- org.apache.directory.api:api-util:jar:1.0.0-M20:compile
[INFO] |  |  |  |  +- org.apache.curator:curator-client:jar:2.7.1:compile
[INFO] |  |  |  |  \- org.apache.htrace:htrace-core:jar:3.1.0-incubating:compile
[INFO] |  |  |  +- org.apache.hadoop:hadoop-hdfs:jar:2.7.4:compile
[INFO] |  |  |  |  +- org.mortbay.jetty:jetty-util:jar:6.1.26:compile
[INFO] |  |  |  |  \- xerces:xercesImpl:jar:2.9.1:compile
[INFO] |  |  |  |     \- xml-apis:xml-apis:jar:1.3.04:compile
[INFO] |  |  |  +- org.apache.hadoop:hadoop-mapreduce-client-app:jar:2.7.4:compile
[INFO] |  |  |  |  +- org.apache.hadoop:hadoop-mapreduce-client-common:jar:2.7.4:compile
[INFO] |  |  |  |  |  +- org.apache.hadoop:hadoop-yarn-client:jar:2.7.4:compile
[INFO] |  |  |  |  |  \- org.apache.hadoop:hadoop-yarn-server-common:jar:2.7.4:compile
[INFO] |  |  |  |  \- org.apache.hadoop:hadoop-mapreduce-client-shuffle:jar:2.7.4:compile
[INFO] |  |  |  +- org.apache.hadoop:hadoop-yarn-api:jar:2.7.4:compile
[INFO] |  |  |  +- org.apache.hadoop:hadoop-mapreduce-client-core:jar:2.7.4:compile
[INFO] |  |  |  |  \- org.apache.hadoop:hadoop-yarn-common:jar:2.7.4:compile
[INFO] |  |  |  |     +- javax.xml.bind:jaxb-api:jar:2.2.2:compile
[INFO] |  |  |  |     |  \- javax.xml.stream:stax-api:jar:1.0-2:compile
[INFO] |  |  |  |     +- org.codehaus.jackson:jackson-jaxrs:jar:1.9.13:compile
[INFO] |  |  |  |     \- org.codehaus.jackson:jackson-xc:jar:1.9.13:compile
[INFO] |  |  |  +- org.apache.hadoop:hadoop-mapreduce-client-jobclient:jar:2.7.4:compile
[INFO] |  |  |  \- org.apache.hadoop:hadoop-annotations:jar:2.7.4:compile
[INFO] |  |  +- org.apache.spark:spark-launcher_2.12:jar:3.0.1:compile
[INFO] |  |  +- org.apache.spark:spark-kvstore_2.12:jar:3.0.1:compile
[INFO] |  |  |  \- org.fusesource.leveldbjni:leveldbjni-all:jar:1.8:compile
[INFO] |  |  +- org.apache.spark:spark-network-common_2.12:jar:3.0.1:compile
[INFO] |  |  +- org.apache.spark:spark-network-shuffle_2.12:jar:3.0.1:compile
[INFO] |  |  +- org.apache.spark:spark-unsafe_2.12:jar:3.0.1:compile
[INFO] |  |  +- javax.activation:activation:jar:1.1.1:compile
[INFO] |  |  +- org.apache.curator:curator-recipes:jar:2.7.1:compile
[INFO] |  |  |  \- org.apache.curator:curator-framework:jar:2.7.1:compile
[INFO] |  |  +- org.apache.zookeeper:zookeeper:jar:3.4.14:compile
[INFO] |  |  |  \- org.apache.yetus:audience-annotations:jar:0.5.0:compile
[INFO] |  |  +- javax.servlet:javax.servlet-api:jar:3.1.0:compile
[INFO] |  |  +- org.apache.commons:commons-math3:jar:3.4.1:compile
[INFO] |  |  +- com.google.code.findbugs:jsr305:jar:3.0.0:compile
[INFO] |  |  +- org.slf4j:jul-to-slf4j:jar:1.7.30:compile
[INFO] |  |  +- org.slf4j:jcl-over-slf4j:jar:1.7.30:compile
[INFO] |  |  +- com.ning:compress-lzf:jar:1.0.3:compile
[INFO] |  |  +- org.xerial.snappy:snappy-java:jar:1.1.7.5:compile
[INFO] |  |  +- org.lz4:lz4-java:jar:1.7.1:compile
[INFO] |  |  +- com.github.luben:zstd-jni:jar:1.4.4-3:compile
[INFO] |  |  +- org.roaringbitmap:RoaringBitmap:jar:0.7.45:compile
[INFO] |  |  |  \- org.roaringbitmap:shims:jar:0.7.45:compile
[INFO] |  |  +- commons-net:commons-net:jar:3.1:compile
[INFO] |  |  +- org.scala-lang.modules:scala-xml_2.12:jar:1.2.0:compile
[INFO] |  |  +- org.scala-lang:scala-reflect:jar:2.12.10:compile
[INFO] |  |  +- org.json4s:json4s-jackson_2.12:jar:3.6.6:compile
[INFO] |  |  |  \- org.json4s:json4s-core_2.12:jar:3.6.6:compile
[INFO] |  |  |     +- org.json4s:json4s-ast_2.12:jar:3.6.6:compile
[INFO] |  |  |     \- org.json4s:json4s-scalap_2.12:jar:3.6.6:compile
[INFO] |  |  +- org.glassfish.jersey.core:jersey-client:jar:2.30:compile
[INFO] |  |  |  +- jakarta.ws.rs:jakarta.ws.rs-api:jar:2.1.6:compile
[INFO] |  |  |  \- org.glassfish.hk2.external:jakarta.inject:jar:2.6.1:compile
[INFO] |  |  +- org.glassfish.jersey.core:jersey-common:jar:2.30:compile
[INFO] |  |  |  +- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
[INFO] |  |  |  \- org.glassfish.hk2:osgi-resource-locator:jar:1.0.3:compile
[INFO] |  |  +- org.glassfish.jersey.core:jersey-server:jar:2.30:compile
[INFO] |  |  |  +- org.glassfish.jersey.media:jersey-media-jaxb:jar:2.30:compile
[INFO] |  |  |  \- jakarta.validation:jakarta.validation-api:jar:2.0.2:compile
[INFO] |  |  +- org.glassfish.jersey.containers:jersey-container-servlet:jar:2.30:compile
[INFO] |  |  +- org.glassfish.jersey.containers:jersey-container-servlet-core:jar:2.30:compile
[INFO] |  |  +- org.glassfish.jersey.inject:jersey-hk2:jar:2.30:compile
[INFO] |  |  |  +- org.glassfish.hk2:hk2-locator:jar:2.6.1:compile
[INFO] |  |  |  |  +- org.glassfish.hk2.external:aopalliance-repackaged:jar:2.6.1:compile
[INFO] |  |  |  |  +- org.glassfish.hk2:hk2-api:jar:2.6.1:compile
[INFO] |  |  |  |  \- org.glassfish.hk2:hk2-utils:jar:2.6.1:compile
[INFO] |  |  |  \- org.javassist:javassist:jar:3.25.0-GA:compile
[INFO] |  |  +- io.netty:netty-all:jar:4.1.47.Final:compile
[INFO] |  |  +- com.clearspring.analytics:stream:jar:2.9.6:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-core:jar:4.1.1:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-jvm:jar:4.1.1:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-json:jar:4.1.1:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-graphite:jar:4.1.1:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-jmx:jar:4.1.1:compile
[INFO] |  |  +- com.fasterxml.jackson.module:jackson-module-scala_2.12:jar:2.10.0:compile
[INFO] |  |  |  \- com.fasterxml.jackson.module:jackson-module-paranamer:jar:2.10.0:compile
[INFO] |  |  +- org.apache.ivy:ivy:jar:2.4.0:compile
[INFO] |  |  +- oro:oro:jar:2.0.8:compile
[INFO] |  |  +- net.razorvine:pyrolite:jar:4.30:compile
[INFO] |  |  +- net.sf.py4j:py4j:jar:0.10.9:compile
[INFO] |  |  \- org.apache.commons:commons-crypto:jar:1.0.0:compile
[INFO] |  +- org.apache.spark:spark-catalyst_2.12:jar:3.0.1:compile
[INFO] |  |  +- org.scala-lang.modules:scala-parser-combinators_2.12:jar:1.1.2:compile
[INFO] |  |  +- org.codehaus.janino:janino:jar:3.0.16:compile
[INFO] |  |  +- org.codehaus.janino:commons-compiler:jar:3.0.16:compile
[INFO] |  |  +- org.antlr:antlr4-runtime:jar:4.7.1:compile
[INFO] |  |  \- org.apache.arrow:arrow-vector:jar:0.15.1:compile
[INFO] |  |     +- org.apache.arrow:arrow-format:jar:0.15.1:compile
[INFO] |  |     +- org.apache.arrow:arrow-memory:jar:0.15.1:compile
[INFO] |  |     \- com.google.flatbuffers:flatbuffers-java:jar:1.9.0:compile
[INFO] |  +- org.apache.spark:spark-tags_2.12:jar:3.0.1:compile
[INFO] |  +- org.apache.orc:orc-core:jar:1.5.10:compile
[INFO] |  |  +- org.apache.orc:orc-shims:jar:1.5.10:compile
[INFO] |  |  +- com.google.protobuf:protobuf-java:jar:2.5.0:compile
[INFO] |  |  +- commons-lang:commons-lang:jar:2.6:compile
[INFO] |  |  +- io.airlift:aircompressor:jar:0.10:compile
[INFO] |  |  \- org.threeten:threeten-extra:jar:1.5.0:compile
[INFO] |  +- org.apache.orc:orc-mapreduce:jar:1.5.10:compile
[INFO] |  +- org.apache.hive:hive-storage-api:jar:2.7.1:compile
[INFO] |  +- org.apache.parquet:parquet-column:jar:1.10.1:compile
[INFO] |  |  +- org.apache.parquet:parquet-common:jar:1.10.1:compile
[INFO] |  |  \- org.apache.parquet:parquet-encoding:jar:1.10.1:compile
[INFO] |  +- org.apache.parquet:parquet-hadoop:jar:1.10.1:compile
[INFO] |  |  +- org.apache.parquet:parquet-format:jar:2.4.0:compile
[INFO] |  |  +- org.apache.parquet:parquet-jackson:jar:1.10.1:compile
[INFO] |  |  +- org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13:compile
[INFO] |  |  \- org.codehaus.jackson:jackson-core-asl:jar:1.9.13:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.10.0:compile
[INFO] |  +- org.apache.xbean:xbean-asm7-shaded:jar:4.15:compile
[INFO] |  \- org.spark-project.spark:unused:jar:1.0.0:compile
[INFO] +- com.opencsv:opencsv:jar:5.3:compile
[INFO] |  +- org.apache.commons:commons-text:jar:1.9:compile
[INFO] |  +- commons-beanutils:commons-beanutils:jar:1.9.4:compile
[INFO] |  |  \- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] |  \- org.apache.commons:commons-collections4:jar:4.4:compile
[INFO] +- org.apache.httpcomponents:httpclient:jar:4.5.13:compile
[INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.4.13:compile
[INFO] |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  \- commons-codec:commons-codec:jar:1.11:compile
[INFO] +- junit:junit:jar:4.11:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- com.msci.esg.esgm2:vertical-transformation-feeds:jar:1.0-SNAPSHOT:compile
[INFO] +- io.netty:netty-codec:jar:4.1.63.Final:compile
[INFO] |  +- io.netty:netty-common:jar:4.1.63.Final:compile
[INFO] |  +- io.netty:netty-buffer:jar:4.1.63.Final:compile
[INFO] |  \- io.netty:netty-transport:jar:4.1.63.Final:compile
[INFO] |     \- io.netty:netty-resolver:jar:4.1.63.Final:compile
[INFO] +- com.msci.esg.esgm2:permission-service-client:jar:1.0-SNAPSHOT:compile
[INFO] +- com.msci.esg.esgm2:token-service-client:jar:1.0-SNAPSHOT:compile
[INFO] \- com.amazon.deequ:deequ:jar:1.2.2-spark-3.0:compile
[INFO]    +- org.scala-lang:scala-library:jar:2.12.10:compile
[INFO]    \- org.scalanlp:breeze_2.12:jar:0.13.2:compile
[INFO]       +- org.scalanlp:breeze-macros_2.12:jar:0.13.2:compile
[INFO]       +- com.github.fommil.netlib:core:jar:1.1.2:compile
[INFO]       +- net.sourceforge.f2j:arpack_combined_all:jar:0.1:compile
[INFO]       +- net.sf.opencsv:opencsv:jar:2.3:compile
[INFO]       +- com.github.rwl:jtransforms:jar:2.4.0:compile
[INFO]       +- org.spire-math:spire_2.12:jar:0.13.0:compile
[INFO]       |  +- org.spire-math:spire-macros_2.12:jar:0.13.0:compile
[INFO]       |  \- org.typelevel:machinist_2.12:jar:0.6.1:compile
[INFO]       \- com.chuusai:shapeless_2.12:jar:2.3.2:compile
[INFO]          \- org.typelevel:macro-compat_2.12:jar:1.1.1:compile

****Code snippet**:**

static public DataLakeServiceClient GetDataLakeServiceClient
    (String accountName, String clientId, String ClientSecret, String tenantID){

    String endpoint = "https://" + accountName + ".dfs.core.windows.net";
    
    ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
    .clientId(clientId)
    .clientSecret(ClientSecret)
    .tenantId(tenantID)
    .build();
       
    DataLakeServiceClientBuilder builder = new DataLakeServiceClientBuilder();
    return builder.credential(clientSecretCredential).endpoint(endpoint).buildClient();
}
public DataLakeDirectoryClient CreateDirectory
(DataLakeServiceClient serviceClient, String fileSystemName){

    DataLakeFileSystemClient fileSystemClient =
    serviceClient.getFileSystemClient(fileSystemName);

    DataLakeDirectoryClient directoryClient =
        fileSystemClient.createDirectory("my-directory");

    return directoryClient.createSubdirectory("my-subdirectory");
}

**Comment by alzimmermsft** [comment] 2022-05-06 14:16
Thank you for filing this issue @git831458, looking through the dependencies you've included it appears that the following versions of Jackson are being resolved:

```
com.fasterxml.jackson.core:jackson-databind:jar:2.10.0:compile

com.fasterxml.jackson.core:jackson-annotations:jar:2.13.2:compile
com.fasterxml.jackson.core:jackson-core:jar:2.13.2:compile
com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.13.2:compile
com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.13.2:compile

com.fasterxml.jackson.module:jackson-module-scala_2.12:jar:2.10.0:compile
com.fasterxml.jackson.module:jackson-module-paranamer:jar:2.10.0:compile
```

[`AnnotationIntrospector.XmlExtensions`](https://github.com/FasterXML/jackson-databind/blob/2.14/src/main/java/com/fasterxml/jackson/databind/AnnotationIntrospector.java#L99) appears to have been added in `jackson-databind` `2.13`, which is the dependency version for the `jackson-dataformat-xml` library listed above. Though, it appears that the Scala module is resolving `jackson-databind` to `2.10`, which is resulting in the `NoClassDefFoundError` to be thrown.

A solution to this problem would be including an explicit version of `jackson-databind` that resolves the error, or upgrading the version of the Scala module. A last solution would be downgrading the other Jackson dependencies to versions that the SDK supports such as 2.12.

**Comment by git831458** [comment] 2022-05-06 14:38
Thanks @alzimmermsft for quick attention.

So i just tried the solution of adding jackson-databind explicitly as below.
<dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.13.2.2</version>
        </dependency>

Now the above original error is gone but is coming a new one:

Exception in thread "main" java.lang.NoSuchMethodError: io.netty.util.internal.ObjectUtil.checkNonEmptyAfterTrim(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
	at io.netty.handler.codec.http.HttpMethod.<init>(HttpMethod.java:123)
	at io.netty.handler.codec.http.HttpMethod.<clinit>(HttpMethod.java:36)
	at reactor.netty.http.client.HttpClientConfig.<init>(HttpClientConfig.java:333)
	at reactor.netty.http.client.HttpClientConnect.<init>(HttpClientConnect.java:85)
	at reactor.netty.http.client.HttpClient.create(HttpClient.java:393)

**Comment by alzimmermsft** [comment] 2022-05-06 14:56
@git831458, this issue appears to be coming from the version mismatches in the Netty libraries included in the project. There appears to be a few which are using version 4.1.73, 4.1.72, and 4.1.63. I know less about the Netty APIs, but my assumption is that the issue is coming from `netty-common` being 4.1.63 and one of the other Netty dependencies on 4.1.72/4.1.73 are dependent upon functionality added in a newer version of `netty-common`.

**Comment by alzimmermsft** [comment] 2022-05-31 18:03
@git831458 was what I mentioned abled to resolve the second dependency conflict issue you were seeing?

**Closed** 2022-06-22 08:03 UTC
Labels: question, Client, customer-reported, needs-team-attention, needs-author-feedback, no-recent-activity, dependency-issue, dependency-issue-jackson
