### ISSUE TITLE
VM does not have a valid MAC address when it's de-allocated

### ISSUE THREAD

**Issue by puneet101** [Azure/azure-sdk-for-java#1328] opened 2016-12-14 22:47 UTC
VM shows a valid MAC address but it is null when the VM is powered-off (de-allocted)

Is this by design or a bug?

**Comment by puneet101** [comment] 2016-12-18 03:56
Any feedback?

**Comment by martinsawicki** [comment] 2016-12-19 13:33
@anuchandy I believe that's just the server-side behavior

**Comment by anuchandy** [comment] 2016-12-27 20:37
yes, this is the behavior of compute service. On de-allocate all the associated resources will be released.

**Comment by martinsawicki** [comment] 2016-12-28 14:10
by design then

**Closed by martinsawicki** 2016-12-28 14:10 UTC
