### ISSUE TITLE
Acquire blob lease gives IllegalStateException

### ISSUE THREAD

**Issue by tomasbonnedahl** [Azure/azure-sdk-for-java#12030] opened 2020-06-10 07:30 UTC
We're experiencing sporadical `IllegalStateExceptions` being thrown when acquiring a lease using the following and a lease acquire timeout of 3000ms. 

```
        return blobLeaseClient.acquireLeaseWithResponse(
            leaseTime,
            (RequestConditions) null,
            timeout,
            Context.NONE
        ).getValue();
```

Also, why is the `IllegalStateException` not wrapped in a `BlobStorageException`, like most/all other exceptions?

We've also seen that we get an `IllegalStateException` even though the lease is acquired, which means we retry and since the duration is longer than the retry period, we're locked out the second time. Would it be possible to know if a lease was indeed acquired, regardless of the `IllegalStateException`?

Using SDK 12.4.0.
 
Thanks

**Comment by rickle-msft** [comment] 2020-06-10 23:05
This may also be related to #11375

**Comment by tomasbonnedahl** [comment] 2020-06-11 07:17
First of all, thank you for a very quick and valuable response. I've been in contact with MSFT support regarding this matter, and not been getting any answers at all.

You are right with regard to the network issues. I forgot to mention that we run the code in the Azure cloud, which at least should eliminate any out connection outside Azure. 

The reasoning `IllegalStateException` vs `BlobStorageException` makes sense, thanks!

What would you say is the recommended way to handle the `IllegalStateException` which is thrown when a timeout for the lease acquire happens? I can see the following options:
a) Assume that the lease was indeed acquired and use the blob. Handle possible commit/write issue later on.
b) Assume the lease was not acquired and retry to acquire the lease. Will most likely (my experience) result in that the second attempt fails since the lease is actually acquired by the first attempt.
b) Use `properties` and base the decision on the `leaseStatus`. 
d) Try to break the lease regardless if we acquired it or not, and retry acquiring the lease.

It seems the `leaseId` (hash) cannot be used to determine if a lease was acquired or not, as that field is set regardless of the lease being acquired. 

Thanks,
Tomas

**Comment by rickle-msft** [comment] 2020-06-11 17:56
Sure thing! We are happy to help get your development on its way! 

I'm not sure a) is really viable because if you didn't get the proper response for acquiring the lease, you won't know what the leaseId is and therefore won't be able to include it in your requests, causing failures. b) will likely result in errors as you mentioned and similarly d) risks hitting further errors (You can see [here](https://docs.microsoft.com/en-us/rest/api/storageservices/lease-blob#outcomes-of-lease-operations-on-blobs-by-lease-state) that if the lease was NOT acquired, trying to break will fail). In that sense, I think c) is your best bet. It may be the most expensive recovery case because in the worst case you have to getProperties, breakLease, acquireLease, but I think it will be the safest option. 

What do you think?

**Comment by rickle-msft** [comment] 2020-06-11 18:08
Side note: As I'm thinking about this more, it strikes me as odd that these operations aren't getting retried automatically. If they were, you'd either successfully acquire the lease on retry or see some error about trying to acquire an already leased blob, which would indicated to you that you do need to break.

**Comment by tomasbonnedahl** [comment] 2020-06-12 12:32
Hi, thanks for getting back.

Agree that c) is the option that makes most sense even though it would include som boiler plate code that could be included in the SDK (ref your second comment). 

However, I'm not able to get properties from `BlockBlobClient` for a new file that should be written. I haven't found a way of getting (blob) properties in order to validate `leaseStatus` and `leaseState`. A `com.azure.storage.blob.models.BlobStorageException: Status code 404, (empty body)` is thrown when getting properties.

Do you have any suggestion on how to move forward with c), or how to get the properties for a not yet written file.

**Comment by rickle-msft** [comment] 2020-06-12 16:51
Can you please explain more about the overall workflow you're trying to build? If the blob isn't written yet, you wouldn't be able to get a lease on it either, I don't think, so I'm not quire sure how these things are fitting together, which makes it hard for me to advise here.

**Comment by tomasbonnedahl** [comment] 2020-06-15 07:10
Thanks for asking. Might be that I've misunderstood something, but I expect to be able to acquire a lease on a not-yet-existing file that I'm about to write. If I hold that lease, other processes would not be able to write to the same path/filename. Does that make sense (even though the SDK might not support it)? 

What would be the outcome be if it is like you say, that it's not possible to get a lease on a non-existing file? I guess the first process would go ahead as there is no file yet and the other process would try to acquire the lease. Would that acquire be successful as there is no lease given to the first process, or would it somehow be an implicit fail of that acquire since the first process is writing, or about to write? How would it know that if the first process has not started to write?

**Comment by rickle-msft** [comment] 2020-06-15 20:41
It does make sense. Unfortunately, I don't think this is supported even by the service. There has to actually be a resource present in order to acquire a lease. It can even be as simple as an uncommitted block or an empty blob, but there does have to be something there. 

There are two common ways of solving this problem depending on what information is available to you. First is to always attempt to put an empty blob at the target path and then acquire a lease on that blob. This way, since everything attempts to put an empty blob first, it's ok if there's a race to create the blob since it'll always be the same. You'll also have to handle errors in both steps in case another blob has a acquired a lease on the empty blob at any point. 

Alternatively, and I think more commonly, you can use etags to manage concurrency instead of leases. In this case, you can use an `If-None-Match:"*"` condition to ensure you're not overwriting any existing data. From that point on, you can save the etag value from all your update operations and always pass that to `If-Match:<etag value>` to ensure you're always operating on a consistent view of the blob.

ither a combination of etags and leases or put an empty blob and acquire a lease on that

**Comment by tomasbonnedahl** [comment] 2020-06-16 11:50
Thanks, agree that your two alternatives are what will probably solve this. I will do some testing and see what it looks like. Will report back.

Thanks again!

**Comment by rickle-msft** [comment] 2020-07-13 18:59
I am going to close this issue as it seems it has been resolved. 

@tomasbonnedahl Please feel free to share your findings even after the issue is closed and reach out again if you need more support.

**Closed by rickle-msft** 2020-07-13 18:59 UTC
Labels: Client, Storage, customer-reported

**Comment by tomasbonnedahl** [comment] 2020-07-17 11:55
> I am going to close this issue as it seems it has been resolved.
> 
> @tomasbonnedahl Please feel free to share your findings even after the issue is closed and reach out again if you need more support.

Thanks for your help @rickle-msft. Agree that you can close this. 

I ended up just changing the timeout for the acquiring the lease to 30 seconds. The very few (compared to when the timeout was 3 seconds) exceptions still caught are handled in a retry, essentially trying to acquire the lease again.

Thanks
