### ISSUE TITLE
[BUG] After upgrading to Spring Boot 2.4, kafka binder stopped working: NoClassDefFoundError: com.nimbusds.oauth2.sdk.http.CommonContentTypes

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#18929] opened 2021-02-02 11:41 UTC
Copied from https://github.com/microsoft/spring-cloud-azure/issues/763. @vprudnikov 

**Describe the bug**

I upgraded my app:

Spring boot 2.3 -> Spring Boot 2.4
spring-cloud-starter-azure-eventhubs-kafka:1.2.7 -> azure-spring-cloud-starter-eventhubs-kafka:2.0.0-beta.1
After that, the app stopped working because of app context failure:

```
Caused by: java.lang.NoClassDefFoundError: com.nimbusds.oauth2.sdk.http.CommonContentTypes
	at com.microsoft.aad.adal4j.AdalTokenRequest.toOAuthRequest(AdalTokenRequest.java:158) ~[adal4j-1.6.4.jar:1.6.4]
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:86) ~[adal4j-1.6.4.jar:1.6.4]
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:930) ~[adal4j-1.6.4.jar:1.6.4]
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:70) ~[adal4j-1.6.4.jar:1.6.4]
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:38) ~[adal4j-1.6.4.jar:1.6.4]
	at com.microsoft.aad.adal4j.AdalCallable.call(AdalCallable.java:47) ~[adal4j-1.6.4.jar:1.6.4]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:851) ~[na:na]
Caused by: java.lang.ClassNotFoundException: com.nimbusds.oauth2.sdk.http.CommonContentTypes
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:788) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1081) ~[na:na]
	... 10 common frames omitted
```

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by saragluna** [comment] 2021-02-02 11:45
Copied @chenrujun's comment here:

@vprudnikov .
Sorry that spring-boot-2.4 is not supported yet. Please wait for next release.

**Comment by tiberiuvs** [comment] 2021-02-10 18:59
Hi, is there a time frame or ETA for this next release with support for spring-boot 2.4?

**Comment by chenrujun** [comment] 2021-02-18 01:32
We will support `spring-boot 2.4` before `2021-03-31`.

**Comment by saragluna** [comment] 2021-03-25 12:57
@vprudnikov

We've shipped the starter which is compatible with Spring Boot 2.4.x, please try it out https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-cloud-starter-eventhubs-kafka/CHANGELOG.md#230-2021-03-22.

**Comment by geoco84** [comment] 2021-03-29 15:31
Hi everyone,

I have the same problem when my application try to connect on azure.
I used spring 2.4.3 and 
 <dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>azure</artifactId>
      <version>1.40.0</version>
    </dependency>
    
   Any way to fixed this problem ?

**Comment by chenrujun** [comment] 2021-03-30 00:03
Hi, @geoco84 , could you please share your pom?

**Comment by geoco84** [comment] 2021-03-30 07:07
from my main

```
  <properties>
    <java.version>11</java.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>${java.version}</maven.compiler.source>
    <maven.compiler.target>${java.version}</maven.compiler.target>
    <springBoot.version>2.4.3</springBoot.version>
  </properties>


  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>${springBoot.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-devtools</artifactId>
      </dependency>
      
    </dependencies>
  </dependencyManagement>
  
```
  
  Module where dependency to azure :
```
  
      <!-- Microsoft Azure -->
    <dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>azure</artifactId>
      <version>1.40.0</version>
    </dependency>
```

stacktrace
```

..

Caused by: java.lang.RuntimeException: java.io.IOException: java.lang.NoClassDefFoundError: com/nimbusds/oauth2/sdk/http/CommonContentTypes
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.observables.BlockingObservable.last(BlockingObservable.java:226) ~[rxjava-1.3.8.jar:1.3.8]
	at com.microsoft.azure.management.resources.fluentcore.arm.collection.implementation.GroupableResourcesImpl.getByResourceGroup(GroupableResourcesImpl.java:110) ~[azure-mgmt-resources-1.40.0.jar:1.40.0]
	at com.microsoft.azure.management.resources.fluentcore.arm.collection.implementation.GroupableResourcesImpl.getByResourceGroup(GroupableResourcesImpl.java:34) ~[azure-mgmt-resources-1.40.0.jar:1.40.0]
Caused by: java.io.IOException: java.lang.NoClassDefFoundError: com/nimbusds/oauth2/sdk/http/CommonContentTypes
	at com.microsoft.azure.credentials.ApplicationTokenCredentials.getToken(ApplicationTokenCredentials.java:188) ~[azure-client-authentication-1.7.12.jar:na]
	at com.microsoft.azure.credentials.AzureTokenCredentials.getToken(AzureTokenCredentials.java:74) ~[azure-client-runtime-1.7.12.jar:na]
	at com.microsoft.azure.credentials.AzureTokenCredentialsInterceptor.intercept(AzureTokenCredentialsInterceptor.java:36) ~[azure-client-runtime-1.7.12.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
	at com.microsoft.azure.management.resources.fluentcore.utils.ResourceManagerThrottlingInterceptor.intercept(ResourceManagerThrottlingInterceptor.java:56) ~[azure-mgmt-resources-1.40.0.jar:1.40.0]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
	at com.microsoft.azure.management.resources.fluentcore.utils.ProviderRegistrationInterceptor.intercept(ProviderRegistrationInterceptor.java:40) ~[azure-mgmt-resources-1.40.0.jar:1.40.0]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
	at com.microsoft.rest.interceptors.BaseUrlHandler.intercept(BaseUrlHandler.java:43) ~[client-runtime-1.7.12.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
	at com.microsoft.rest.interceptors.RequestIdHeaderInterceptor.intercept(RequestIdHeaderInterceptor.java:29) ~[client-runtime-1.7.12.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229) ~[okhttp-3.14.9.jar:na]
	at okhttp3.RealCall.execute(RealCall.java:81) ~[okhttp-3.14.9.jar:na]
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:188) ~[retrofit-2.6.4.jar:na]
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:40) ~[adapter-rxjava-2.6.4.jar:na]
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24) ~[adapter-rxjava-2.6.4.jar:na]
	at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:32) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:22) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.Observable.subscribe(Observable.java:10423) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.Observable.subscribe(Observable.java:10390) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:443) ~[rxjava-1.3.8.jar:1.3.8]
	... 16 common frames omitted
Caused by: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/nimbusds/oauth2/sdk/http/CommonContentTypes
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205) ~[na:na]
	at com.microsoft.azure.credentials.ApplicationTokenCredentials.getToken(ApplicationTokenCredentials.java:181) ~[azure-client-authentication-1.7.12.jar:na]
	... 57 common frames omitted
Caused by: java.lang.NoClassDefFoundError: com/nimbusds/oauth2/sdk/http/CommonContentTypes
	at com.microsoft.aad.adal4j.AdalTokenRequest.toOAuthRequest(AdalTokenRequest.java:158) ~[adal4j-1.6.4.jar:1.6.4]
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:86) ~[adal4j-1.6.4.jar:1.6.4]
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:930) ~[adal4j-1.6.4.jar:1.6.4]
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:70) ~[adal4j-1.6.4.jar:1.6.4]
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:38) ~[adal4j-1.6.4.jar:1.6.4]
	at com.microsoft.aad.adal4j.AdalCallable.call(AdalCallable.java:47) ~[adal4j-1.6.4.jar:1.6.4]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.lang.ClassNotFoundException: com.nimbusds.oauth2.sdk.http.CommonContentTypes
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[na:na]
	... 11 common frames omitted

```
In my dependencies, CommonContentTypes don't exists

![image](https://user-images.githubusercontent.com/9726408/112944284-e87f9600-9132-11eb-9948-81de1e44f2c4.png)

or maven dependencies tree

```
mvn dependency:tree -Dincludes=com.nimbusds
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< com.guardis:cortex-core >-----------------------
[INFO] Building Cortex Core 1.82.2-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ cortex-core ---
[INFO] com.guardis:cortex-core:jar:1.82.2-SNAPSHOT
[INFO] \- com.microsoft.azure:azure:jar:1.40.0:compile
[INFO]    \- com.microsoft.azure:azure-client-authentication:jar:1.7.12:compile
[INFO]       \- com.microsoft.azure:adal4j:jar:1.6.4:compile
[INFO]          \- com.nimbusds:oauth2-oidc-sdk:jar:8.36:compile
[INFO]             +- com.nimbusds:content-type:jar:2.1:compile
[INFO]             +- com.nimbusds:lang-tag:jar:1.4.4:compile
[INFO]             \- com.nimbusds:nimbus-jose-jwt:jar:8.20.2:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.992 s
[INFO] Finished at: 2021-03-30T09:06:09+02:00
[INFO] ------------------------------------------------------------------------
cousing:~/workspace/cortex/cortex-core(azure)$ 

```

**Comment by saragluna** [comment] 2021-03-30 09:12
@geoco84 

Why `com.microsoft.azure:azure` 1.40.0 is being used? This module is not compatible with our latest releases.

**Comment by geoco84** [comment] 2021-03-30 09:39
@saragluna 

what ? there is a new ?

**Comment by saragluna** [comment] 2021-04-02 03:48
@geoco84 sorry for the late response, please check this comment https://github.com/Azure/azure-sdk-for-java/issues/18121#issuecomment-810706871.

**Comment by geoco84** [comment] 2021-04-06 07:04
@saragluna thanks. I found this comment last week and now it's fixed. But the documentation on this it's very difficult to find (migration)

**Comment by vprudnikov** [comment] 2021-04-09 09:19
@saragluna , I check a new version of the azure library:
spring-boot-starter-parent: 2.4.4
azure-spring-cloud-starter-eventhubs-kafka: 2.3.0

However, my application cannot start:
```
java.lang.NoSuchMethodError: com/azure/core/util/FluxUtil.collectBytesFromNetworkResponse(Lreactor/core/publisher/Flux;Lcom/azure/core/http/HttpHeaders;)Lreactor/core/publisher/Mono; (loaded from file:/app/lib/azure-core-1.13.0.jar by jdk.internal.loader.ClassLoaders$AppClassLoader@82edcbea) called from class com.azure.core.http.netty.NettyAsyncHttpClient (loaded from file:/app/lib/azure-core-http-netty-1.9.0.jar by jdk.internal.loader.ClassLoaders$AppClassLoader@82edcbea).[user-deployment-6968bb9596-q56t6 user]
at com.azure.core.http.netty.NettyAsyncHttpClient.lambda$responseDelegate$5(NettyAsyncHttpClient.java:148) ~[azure-core-http-netty-1.9.0.jar:na][user-deployment-6968bb9596-q56t6 user]
at com.azure.core.http.netty.NettyAsyncHttpClient$$Lambda$1631/00000000F0009790.apply(Unknown Source) ~[na:na][user-deployment-6968bb9596-q56t6 user]
at reactor.netty.http.client.HttpClientFinalizer.lambda$responseConnection$4(HttpClientFinalizer.java:102) ~[reactor-netty-http-1.0.5.jar:1.0.5][user-deployment-6968bb9596-q56t6 user]
at reactor.netty.http.client.HttpClientFinalizer$$Lambda$1632/00000000F000A7E0.apply(Unknown Source) ~[na:na][user-deployment-6968bb9596-q56t6 user]
at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:163) ~[reactor-core-3.4.4.jar:3.4.4][user-deployment-6968bb9596-q56t6 user]
at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99) ~[reactor-core-3.4.4.jar:3.4.4][user-deployment-6968bb9596-q56t6 user]
at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:173) ~[reactor-core-3.4.4.jar:3.4.4][user-deployment-6968bb9596-q56t6 user]
at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:160) ~[reactor-core-3.4.4.jar:3.4.4][user-deployment-6968bb9596-q56t6 user]
at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.onStateChange(HttpClientConnect.java:387) ~[reactor-netty-http-1.0.5.jar:1.0.5][user-deployment-6968bb9596-q56t6 user]
at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:654) ~[reactor-netty-core-1.0.5.jar:1.0.5][user-deployment-6968bb9596-q56t6 user]
at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onStateChange(DefaultPooledConnectionProvider.java:210) ~[reactor-netty-core-1.0.5.jar:1.0.5][user-deployment-6968bb9596-q56t6 user]
at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnection.onStateChange(DefaultPooledConnectionProvider.java:466) ~[reactor-netty-core-1.0.5.jar:1.0.5][user-deployment-6968bb9596-q56t6 user]
at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:629) ~[reactor-netty-http-1.0.5.jar:1.0.5][user-deployment-6968bb9596-q56t6 user]
at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:94) ~[reactor-netty-core-1.0.5.jar:1.0.5][user-deployment-6968bb9596-q56t6 user]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final][user-deployment-6968bb9596-q56t6 user]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final][user-deployment-6968bb9596-q56t6 user]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final][user-deployment-6968bb9596-q56t6 user]
at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final][user-deployment-6968bb9596-q56t6 user]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[netty-codec-4.1.60.Final.jar:4.1.60.Final][user-deployment-6968bb9596-q56t6 user]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) ~[netty-codec-4.1.60.Final.jar:4.1.60.Final][user-deployment-6968bb9596-q56t6 user]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) ~[netty-codec-4.1.60.Final.jar:4.1.60.Final][user-deployment-6968bb9596-q56t6 user]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.60.Final.jar:4.1.60.Final][user-deployment-6968bb9596-q56t6 user]
at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final][user-deployment-6968bb9596-q56t6 user]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final][user-deployment-6968bb9596-q56t6 user]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final][user-deployment-6968bb9596-q56t6 user]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final][user-deployment-6968bb9596-q56t6 user]
at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1534) ~[netty-handler-4.1.60.Final.jar:4.1.60.Final][user-deployment-6968bb9596-q56t6 user]
at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1295) ~[netty-handler-4.1.60.Final.jar:4.1.60.Final][user-deployment-6968bb9596-q56t6 user]
at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1332) ~[netty-handler-4.1.60.Final.jar:4.1.60.Final][user-deployment-6968bb9596-q56t6 user]
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508) ~[netty-codec-4.1.60.Final.jar:4.1.60.Final][user-deployment-6968bb9596-q56t6 user]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447) ~[netty-codec-4.1.60.Final.jar:4.1.60.Final][user-deployment-6968bb9596-q56t6 user]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.60.Final.jar:4.1.60.Final][user-deployment-6968bb9596-q56t6 user]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final][user-deployment-6968bb9596-q56t6 user]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final][user-deployment-6968bb9596-q56t6 user]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final][user-deployment-6968bb9596-q56t6 user]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final][user-deployment-6968bb9596-q56t6 user]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final][user-deployment-6968bb9596-q56t6 user]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final][user-deployment-6968bb9596-q56t6 user]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final][user-deployment-6968bb9596-q56t6 user]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[netty-transport-native-epoll-4.1.60.Final-linux-x86_64.jar:4.1.60.Final][user-deployment-6968bb9596-q56t6 user]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[netty-transport-native-epoll-4.1.60.Final-linux-x86_64.jar:4.1.60.Final][user-deployment-6968bb9596-q56t6 user]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.60.Final-linux-x86_64.jar:4.1.60.Final][user-deployment-6968bb9596-q56t6 user]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.60.Final.jar:4.1.60.Final][user-deployment-6968bb9596-q56t6 user]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.60.Final.jar:4.1.60.Final][user-deployment-6968bb9596-q56t6 user]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.60.Final.jar:4.1.60.Final][user-deployment-6968bb9596-q56t6 user]
at java.base/java.lang.Thread.run(Thread.java:851) ~[na:na][user-deployment-6968bb9596-q56t6 user][user-deployment-6968bb9596-q56t6 user] 2021-04-09 09:14:58.926  WARN 1 --- [or-http-epoll-3] reactor.netty.channel.FluxReceive        : [id:d9acb257-1, L:/10.167.42.94:59770 ! R:management.azure.com/13.69.114.0:443] An exception has been observed post termination, use DEBUG level to see the full stack: java.lang.NoSuchMethodError: com/azure/core/util/FluxUtil.collectBytesFromNetworkResponse(Lreactor/core/publisher/Flux;Lcom/azure/core/http/HttpHeaders;)Lreactor/core/publisher/Mono; (loaded from file:/app/lib/azure-core-1.13.0.jar by jdk.internal.loader.ClassLoaders$AppClassLoader@82edcbea) called from class com.azure.core.http.netty.NettyAsyncHttpClient (loaded from file:/app/lib/azure-core-http-netty-1.9.0.jar by jdk.internal.loader.ClassLoaders$AppClassLoader@82edcbea).
```

Could you please advise?
Thank you in advance!

**Comment by vprudnikov** [comment] 2021-04-15 06:55
Hi @saragluna ,

Are you able to reproduce the issue? 
I can also create a new github issue if you think it's better.

Thank you!

**Comment by saragluna** [comment] 2021-04-16 02:17
@vprudnikov sorry for the late response.

Yes, I did reproduce the issue and the solution is to add this to your pom file:

[10:15] Xiaobing Zhu (CSI Interfusion Inc)
    
```xml
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-core</artifactId>
      <version>1.14.1</version> <!-- {​​​​​​x-version-update;com.azure:azure-core;dependency}​​​​​​ -->
    </dependency>
  </dependencies>
</dependencyManagement>
```

**Comment by trainitek** [comment] 2021-04-21 15:51
@saragluna thanks! It solved the issue :)

**Comment by vprudnikov** [comment] 2021-04-21 15:52
@saragluna , thanks! It solved the issue :)

**Comment by chenrujun** [comment] 2021-04-25 02:01
Closing this issue because issue solved.

**Closed by chenrujun** 2021-04-25 02:01 UTC
Labels: Client, azure-spring, azure-spring-dependency, azure-spring-eventhubs-kafka, customer-reported, question

**Comment by sumitpal-singh** [comment] 2021-07-10 19:49
> ```
> <dependency>
>       <groupId>com.azure</groupId>
>       <artifactId>azure-core</artifactId>
>       <version>1.14.1</version>
>     </dependency>
> ```

Not working for me
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.5.2</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>in.sps-tech</groupId>
	<artifactId>cloud-file-analyser</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>cloud-file-analyser</name>
	<description>File analyser for cloud files</description>
	<properties>
		<java.version>1.8</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>com.microsoft.graph</groupId>
			<artifactId>microsoft-graph-core</artifactId>
			<version>2.0.2</version>
		</dependency>
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>msal4j</artifactId>
			<version>1.7.1</version>
		</dependency>
		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-core</artifactId>
			<version>1.14.1</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
```

**Comment by sumitpalsingh007** [comment] 2021-07-10 20:00
> @vprudnikov sorry for the late response.
> 
> Yes, I did reproduce the issue and the solution is to add this to your pom file:
> 
> ```
> <dependencyManagement>
>   <dependencies>
>     <dependency>
>       <groupId>com.azure</groupId>
>       <artifactId>azure-core</artifactId>
>       <version>1.14.1</version>
>     </dependency>
>   </dependencies>
> </dependencyManagement>
> ```

This didn't work for me. What worked for me is the revert to an old version of Spring boot:- ```<version>2.2.13.RELEASE</version>```

**Comment by saragluna** [comment] 2022-10-13 13:57
Hi @rahul-mb, some of the Azure libraries you use are end-of-support and don't work with Spring Boot 2.6.x. 

```xml
<properties>
  <azure.springboot.bom.version>2.3.5</azure.springboot.bom.version>
  <azure-sdk-bom.version>1.0.1</azure-sdk-bom.version>
  <spring-starter-azure-storage.version>1.2.8</spring-starter-azure-storage.version>
  <applicationinsights-version>2.6.2</applicationinsights-version>
</properties>
```

For more information about Spring Cloud Azure versions, see https://aka.ms/spring/versions. 

The latest Spring Cloud Azure version that is compatible with Spring Boot 2.6.x is 4.4.0, the legacy version will encounter dependency conflicts with Spring Boot 2.6.x. Is it an option for you to upgrade to Spring Cloud Azure 4.x (which has some breaking changes, but you could refer to https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html#migration-guide-for-4-0)?

**Comment by rahul-mb** [comment] 2022-10-17 11:11
@saragluna Thanks for looking into the question. I updated the dependencies and it worked fine with small changes.
