### ISSUE TITLE
[BUG] java.lang.reflect.InaccessibleObjectException - Defining a CosmosDB entity bean with BigDecimal

### ISSUE THREAD

**Issue by amidukr** [Azure/azure-sdk-for-java#35345] opened 2023-06-06 23:28 UTC
The similar is just closed without any resolution, however it is blocker for me to use, CosmosDB together with JDK 17 and Spring boot.
https://github.com/Azure/azure-sdk-for-java/issues/33980 

Not sure if my corporate policy allows me to share stack trace, however, following the stack trace, the issue coming from `com.azure.spring.data.cosmos.core.convert.MappingCosmosConverter` - which uses `mappingContext` for only purpose, to get the ID attribute of the document, so if you can get ID attribute with other means, deep scanning for ID attribute of the bean shouldn't be a big deal, the issue will be solved. This converter mainly relies on `JacksonMapper` which works perfectly fine with latest JDK.

The issue can be reproduced by adding `BigDecimal` to the CosmosDB spring data entity, with JDK 17 or later.

I've tried to use `--add-opens java.base/java.math=ALL-UNNAMED`, however, it is an ugly way of doing things.

The latest Spring Boot 3.0.0 is officially supported JDK 17 as the minimum version, it seems that the CosmosDB spring data module is not compatible with Spring Boot 3.0.0.

Reported a similar issue to spring boot support: https://github.com/spring-projects/spring-data-commons/issues/2844

Looking forward to your help.

**Comment by kushagraThapar** [comment] 2023-06-07 16:08
@amidukr thanks for opening this issue. As Mark mentioned on the above spring-data-commons github issue, entities need deep reflection in order to process the data and spring magic behind the scenes. So if opening java.base/java.math to ALL-UNNAMED solves this problem for you, I would consider it a good solution. FYI - we also open a lot of them for our own internal testing (because of java 11 and 17 issues) - https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/azure-spring-data-cosmos/pom.xml#L26

Regarding spring-boot 3 support, it is planned to be released by the end of this month. So you should be able to use the new spring-data-cosmos module later this month which will have the support for spring-boot-3.

**Comment by kushagraThapar** [comment] 2023-06-07 16:14
@trande4884 can you try reproducing this and see if there is any other way to solve it, thanks!

**Comment by amidukr** [comment] 2023-06-07 17:58
> @amidukr thanks for opening this issue. As Mark mentioned on the above spring-data-commons GitHub issue, entities need deep reflection in order to process the data and spring magic behind the scenes. So if opening java.base/java.math to ALL-UNNAMED solves this problem for you, I would consider it a good solution. FYI - we also open a lot of them for our own internal testing (because of Java 11 and 17 issues) - https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/azure-spring-data-cosmos/pom.xml#L26
> 
> Regarding spring-boot 3 support, it is planned to be released by the end of this month. So you should be able to use the new spring-data-cosmos module later this month which will have the support for spring-boot-3.

Ok, thank you for giving me the blessing to use `--add-opens java.base/java.math=ALL-UNNAMED`, now I will have something to tell my team. 

I was looking through the internet quite a bit, and it seems that it is really a spring boot issue, people reporting a similar thing for MongoDB spring data module, which is officially supported by the spring community. 
 https://stackoverflow.com/questions/69352207/jdk-17-spring-boot-unable-to-make-private-java-time-localdatetime

My original ticket to spring community was closed, so I open a new one, trying to find the best solution:
https://github.com/spring-projects/spring-data-commons/issues/2845

They suggested to register some `Converter`, however, I don't see that converter ever used with `AbstractMappingContext`.

**Comment by trande4884** [comment] 2023-06-08 16:08
@amidukr so with this being more of a spring issue and the --add-opens option can we close this ticket? Or is there anything else needed on our end?

**Comment by amidukr** [comment] 2023-06-08 17:06
> @amidukr so with this being more of a spring issue and the --add-opens option can we close this ticket? Or is there anything else needed on our end?

Thank you very much for your help, the --add-opens works, it solves my issue, I was able to put it into boot jar META-INF file, and it really seems spring boot data issue.

**Comment by kushagraThapar** [comment] 2023-07-26 22:23
@amidukr - do we still need to keep this issue open? Given the problem is on the spring boot side. Let me know, I am fine either way.

**Comment by amidukr** [comment] 2023-07-26 23:26
@kushagraThapar  If you ask me, I've already moved with `--add-opens java.base/java.math=ALL-UNNAMED` as a fix.

**Comment by kushagraThapar** [comment] 2023-07-27 00:33
Yeah, I think that's the right fix for this, we use the same internally to avoid this issue. I will close this issue now, thanks!

**Closed by kushagraThapar** 2023-07-27 00:33 UTC
Labels: question, Cosmos, Client, customer-reported, needs-team-attention
