### ISSUE TITLE
LeaseIdMismatchWithBlobOperation with copyFromUrlWithResponse when specifying a valid leaseId on leased destination blob

### ISSUE THREAD

**Issue by PbALpi7xEX** [Azure/azure-sdk-for-java#19326] opened 2021-02-19 18:10 UTC
Currently using SDK 12.10.0 and Spring Boot 2.3.8... trying to copy a source blob to leased target blob but getting LeaseIdMismatchWithBlobOperation on copy. Copy works fine without a leased target.

```
String sasToken = srcBlob.generateUserDelegationSas(blobServiceSasSignatureValues, userDelegationKey);
BlobRequestConditions reqConditions = new BlobRequestConditions().setLeaseId(leaseId);

Response<String> resp = destBlob.copyFromUrlWithResponse(
				new BlobCopyFromUrlOptions(String.format("%s?%s", srcBlob.getBlobUrl(), sasToken))
						.setDestinationRequestConditions(reqConditions),
				null, null);

```

**Comment by rickle-msft** [comment] 2021-02-22 17:36
Hi, @PbALpi7xEX I've tested this and I'm not able to reproduce the issue. Could you share the code for how you retrieve the leaseId that you're setting? And possibly enable logs (being sure to set x-ms-lease-id as an allowed header) and share those for a run of this code snippet?

**Comment by PbALpi7xEX** [comment] 2021-02-22 18:57
Hi @rickle-msft,

Code that retrieves the leaseId:

```
BlobAcquireLeaseOptions leaseOptions = new BlobAcquireLeaseOptions(timeout);
		BlobLeaseRequestConditions reqConditions = new BlobLeaseRequestConditions();

		if (etag != null) {
			reqConditions.setIfMatch(etag);
		}
		leaseOptions.setRequestConditions(reqConditions);

		log.info("<< lock");

		return this.getBlobLeaseClient(containerName, filename).acquireLeaseWithResponse(leaseOptions, null, null)
				.getValue();
```

Here is the HTTP log of the lock:

`PUT https://******.blob.core.windows.net/*****/en%2Fatl-article%2F2020%2F07%2Fcopy-of2_portraits_testing_image_placement_1596021694005.shtml?comp=leaseDate:REDACTEDAuthorization:REDACTEDContent-Length:REDACTEDx-ms-version:REDACTEDx-ms-proposed-lease-id:REDACTEDx-ms-lease-duration:REDACTEDx-ms-lease-action:REDACTEDx-ms-client-request-id:REDACTEDUser-Agent:REDACTED(empty body)--> END PUT`

returns: **539c730b-84ca-47f4-aa78-17894630fb5c**

Here is log output with leaseId header exposed... with above leaseId:

`PUT https://*****.blob.core.windows.net/****/en%2Fatl-article%2F2020%2F07%2Fcopy-of2_portraits_testing_image_placement_1596021694005.shtmlDate:REDACTEDAuthorization:REDACTEDContent-Length:REDACTEDx-ms-version:REDACTEDx-ms-copy-source:REDACTEDx-ms-lease-id:539c730b-84ca-47f4-aa78-17894630fb5cx-ms-requires-sync:REDACTEDx-ms-client-request-id:REDACTEDUser-Agent:REDACTED(empty body)--> END PUT`

**Comment by rickle-msft** [comment] 2021-02-23 18:20
That looks fine on it's own. Can you share all the code together--the code that retrieves the lease and then passes the lease to the copy operation? And the logs for those respective requests? I'd like to verify that the lease id we're seeing returned from the call to acquire is getting properly set as the destination lease id

**Comment by PbALpi7xEX** [comment] 2021-02-23 21:42
So interesting finding... I tested my code using another container and blob path, and it worked with the leaseId.

Tried again with the blob and container above, fails with LeaseIdMismatch exception.

Apparent difference I can see between the two, apart from different container and blob path, is the blob path length...

Here is the log from the working blob copy:

PUT https://****.blob.core.windows.net/samplesite/docs%2Feng%2Ftest34.htmlDate:REDACTEDAuthorization:REDACTEDContent-Length:REDACTEDx-ms-version:REDACTEDx-ms-copy-source:REDACTED**x-ms-lease-id:de1fbabf-f930-4720-8c97-f82596fd42b8**x-ms-requires-sync:REDACTEDx-ms-client-request-id:REDACTEDUser-Agent:REDACTED(empty body)--> END PUT

And the log from the failed attempt with the other container and longer blob path:

PUT https://****.blob.core.windows.net/site-prv/en%2Fatl-article%2F2020%2F07%2Fcopy-of2_portraits_testing_image_placement_1596021694005.shtmlDate:REDACTEDAuthorization:REDACTEDContent-Length:REDACTEDx-ms-version:REDACTEDx-ms-copy-source:REDACTED**x-ms-lease-id:40bafda2-931d-4550-8d7a-288e8e6df2c8**x-ms-requires-sync:REDACTEDx-ms-client-request-id:REDACTEDUser-Agent:REDACTED(empty body)--> END PUT

Anything I should be looking at on the container that could be causing the error?

**Comment by rickle-msft** [comment] 2021-02-24 00:05
@PbALpi7xEX That's interesting and a little unexpected. Can we try using the different blob names but putting both destinations in the same container?

**Comment by PbALpi7xEX** [comment] 2021-02-24 13:45
Seems container related... created another container, same blob path... works fine. Checked my role assignments, inherited from SA... not sure what else to check and what could be preventing copy with valid leaseId to not work in this specific container.

**Comment by rickle-msft** [comment] 2021-02-24 15:42
@PbALpi7xEX Hm. Can you get the x-ms-request-id returned by one of the failed requests and share it here?

**Comment by PbALpi7xEX** [comment] 2021-02-24 16:04
Here is one: 714aa208-101e-0050-28b3-0a53d2000000

**Comment by rickle-msft** [comment] 2021-02-24 22:08
@PbALpi7xEX It looks like there is one IP address that acquired the lease and another IP address that attempted the failed copy blob. Is that expected? If it's not, let me know, and I can give you my email address so I can send you the IPs which are making the respective requests

**Comment by PbALpi7xEX** [comment] 2021-02-25 15:47
Hmm.. that isn't expected... I am using PostMan to call our api, which is running on localhost for now... all done through corporate VPN (working remote)... I do know they have implemented some split tunneling policies implemented... wondering if perhaps this is why different IPs are being detected... 

I will further test off the VPN to confirm later.

**Comment by rickle-msft** [comment] 2021-03-19 16:23
@PbALpi7xEX Sorry for the delay. I was out of the office for a couple weeks

I just got back and saw this on an internal thread: "There's a service bug where if a customer makes a blob using Put Block List / Commit Block List and then attempt to use that blob as a source blob when calling Copy From URL with a lease on the destination blob they will cause a LeaseIdMismatchWithBlobOperation. https://github.com/Azure/azure-sdk-for-net/issues/19094"

So it seems you are hitting the same issue and it is being worked on on the service end. Would you mind in that case if I close this issue as I think there is no work for the client to be done and it is already being tracked elsewhere on the service?

**Closed** 2021-04-17 08:00 UTC
Labels: Client, Storage, customer-reported, needs-author-feedback, no-recent-activity
