### ISSUE TITLE
Java SDK 12. Problem with beginCopy between 2 storage accounts

### ISSUE THREAD

**Issue by ashafique2** [Azure/azure-sdk-for-java#21051] opened 2021-04-29 12:24 UTC
Facing `CannotVerifyCopySource` with `destBlobclient.beginCopy(sasurl,null)` using azure-storage-blob version: 12.6.0

Following is the code I'm using:

```
1. for(BlobItem blobItem: sourceContainerClient.listBlobs()){
2.     BlobClient srcBlob = srcContainerClient.getBlobClient(blobItem.getName());
3.     BlobClient destBlob = destContainerClient.getBlobClient(blobItem.getName());
3.     OffsetDateTime expiryTime = OffsetDateTime.now().plusDays(1);
4.     BlobContainerSasPermission permission = new BlobContainerSasPermission().setReadPermission(true);
5.     BlobServiceSasSignatureValues values = new BlobServiceSasSignatureValues(expiryTime, permission).setStartTime(OffsetDateTime.now());
6.     String sas = blobClient.generateSas(values);
7.     String sasUrl = blobClient.getUrl + "?" + sas;
8.     destBlob.beginCopy(sasUrl, Duration.ofSeconds(2));
9.     }
```
Following is the error I get in the Exception block on line 8:
`<Error><Code>CannotVerifyCopySource</Code><Message>This request is not authorized to perform this operation
`
Another point to notice is that the URL generated on line 7 can be accessed through the browser and see the blob contents just fine.

Source and destinations are both standard storage account

**Comment by joshfree** [comment] 2021-04-29 17:34
@gapra-msft could you please follow up with @ashafique2

**Comment by gapra-msft** [comment] 2021-04-29 17:35
Hi @ashafique2 
Thank you for reporting this question. I will take a look at what may be going wrong.

**Comment by ashafique2** [comment] 2021-04-29 17:44
@gapra-msft  if it helps, I am facing the same issue while using Azcopy and Storage Explorer as well

**Comment by gapra-msft** [comment] 2021-04-29 17:45
@ashafique2 Could you share the request id that the service sends back with the error detail if possible?

**Comment by ashafique2** [comment] 2021-04-29 17:47
Sure, here are the details:

```
RESPONSE Status: 403 This request is not authorized to perform this operation.
   Content-Length: [246]
   Content-Type: [application/xml]
   Date: [Thu, 29 Apr 2021 17:28:07 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [9cd41f98-dc56-4bb1-583a-4e266edfbd08]
   X-Ms-Error-Code: [AuthorizationFailure]
   X-Ms-Request-Id: [fe040ba0-401e-005e-621d-3df3da000000]
   X-Ms-Version: [2019-12-12]
```

**Comment by gapra-msft** [comment] 2021-04-29 19:40
From the service logs it looks like the source IP does not match the specified signed IP in the SAS. 

Here is more information on what a valid SAS signed IP can be https://docs.microsoft.com/en-us/rest/api/storageservices/create-service-sas#specifying-ip-address-or-ip-range. Please also pay special attention to the Note in case that is applicable.

**Comment by gapra-msft** [comment] 2021-05-04 22:26
Hi @ashafique2 are you still hitting this issue? Please feel free to close the issue once you've confirmed your question has been resolved.

**Closed** 2021-05-06 23:06 UTC
Labels: Client, Storage, customer-reported, needs-author-feedback, question
