### ISSUE TITLE
[BUG] Cannot create mysql through java sdk 

### ISSUE THREAD

**Issue by andxu** [Azure/azure-sdk-for-java#17660] opened 2020-11-18 23:28 UTC
I write some lines of code to create mysql server in java, it creates mysql server successfully but reporting:
```
Exception in thread "main" com.microsoft.azure.CloudException: Service is temporarily busy and the operation cannot be performed. Please try again later.: Service is temporarily busy and the operation cannot be performed. Please try again later.
	at com.microsoft.azure.AzureClient.createExceptionFromResponse(AzureClient.java:798)
	at com.microsoft.azure.AzureClient.access$100(AzureClient.java:34)
	at com.microsoft.azure.AzureClient$3.call(AzureClient.java:161)
	at com.microsoft.azure.AzureClient$3.call(AzureClient.java:158)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120)
	at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:81)
	at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:27)
	at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:39)
	at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:27)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153)
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:32)
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:22)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: retrofit2.Response.class
	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
```

My dependency and code:
```java
ServerPropertiesForCreate properties = new ServerPropertiesForDefaultCreate().withAdministratorLogin("andy").withAdministratorLoginPassword("xxx");
properties.withVersion(ServerVersion.fromString("5.7"));
Sku sku = new Sku().withName("GP_Gen5_4").withFamily("Gen5").withSize("" + (5 * 1024)).withTier(SkuTier.GENERAL_PURPOSE);
        Server s = manager.servers().define("andxu-mysql-demo3").withRegion("westus").withExistingResourceGroup("andxu-demo-rg2").withProperties(properties).withSku(sku).create();
```

```xml
<dependency>
	<groupId>com.microsoft.azure.mysql.v2017_12_01</groupId>
	<artifactId>azure-mgmt-mysql</artifactId>
	<version>1.0.0-beta-4</version>
</dependency>
```

**Comment by weidongxu-microsoft** [comment] 2020-11-22 06:40
Appears works fine in track2 Lite test CI.

Maybe the issue is really "temporarily" on server side.

api-version=2017-12-01

```
        Server server = mySqlManager.servers().define(serverName)
                .withRegion(region)
                .withExistingResourceGroup(rgName)
                .withProperties(
                        new ServerPropertiesForDefaultCreate()
                            .withAdministratorLogin(username)
                            .withAdministratorLoginPassword(pasword)
                            .withVersion(ServerVersion.fromString("5.7"))
                )
                .withSku(
                        new Sku()
                            .withName("GP_Gen5_4")
                            .withFamily("Gen5")
                            .withSize("" + (5 * 1024))
                            .withTier(SkuTier.GENERAL_PURPOSE))
                .create();
```

**Comment by shenqianjin** [comment] 2020-11-30 02:34
@weidongxu-microsoft Hi Weidong, I tried dozens of times. It is not only a "temporarily" issue, it also has almost 75% chance of failure. That doesn't make sense. could you help to keep investigating on it ?

**Comment by weidongxu-microsoft** [comment] 2020-11-30 02:55
@ChenTanyi Please take a look when you have time.

**Comment by ChenTanyi** [comment] 2020-11-30 06:08
@shenqianjin After my test, the `temporarily busy` appears when you do another create before the previous one finished. (I have only tested with same MySql server name, not sure about what if you create with different server name.)
I would add the `Service Attention`, but I think it is a feature not a bug.

**Comment by ChenTanyi** [comment] 2020-11-30 06:15
@ambhatna, @savjani Except the above problem, I have tested with another issue: sometimes, the service will return 404 after the long-running operation succeeded.
![image](https://user-images.githubusercontent.com/15213781/100574888-f274c200-3315-11eb-97ea-077ea469bd4d.png)

You can see the above screenshot.

I PUT to `/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/resourceGroups/slkdjflskdjf/providers/Microsoft.DBforMySQL/servers/slkdjflsdjklf?api-version=2017-12-01` and GET LRO until succeeded returned. Then, the next GET operation for same PUT resources return 404. 
This appears during my test. My test is just doing a for loop with create and delete the same server. Some GET returns 404 and some GET returns 200. It seems just random event.

**Comment by savjani** [comment] 2020-12-01 03:02
@ChenTanyi @andxu - Ack on this. Let me get back to you on this

**Comment by savjani** [comment] 2020-12-01 09:14
Hi @ChenTanyi , @andxu - @mksuni is following up on this one

**Comment by ArthurMa1978** [comment] 2021-09-14 01:48
> Hi @ChenTanyi , @andxu - @mksuni is following up on this one

Thanks @savjani, so I'd like to remove the mgmt label and assign this issue to you.

**Comment by andxu** [comment] 2021-09-14 02:18
We have already migrate to track2 api to create mysql. This issue seems invalid now.

**Closed as not planned** 2024-03-18 18:07 UTC
Labels: MySQL, Service Attention
