### ISSUE TITLE
[BUG] Breaking change in Azure Data Tables 12.4.0 from 12.3.20 - column reported as string not DateTime

### ISSUE THREAD

**Issue by knubonrk** [Azure/azure-sdk-for-java#39710] opened 2024-04-15 11:55 UTC
**Describe the bug**
Data in a TableEntity stored as OffsetDateTime is returned as String and not proper data type.

***Exception or Stack Trace***
N/A

**To Reproduce**
Store a OffsetDateTime in a TableEntity and try to obtain it.

***Code Snippet***
tableEntity.getProperty("latestEventTime") as OffsetDateTime

**Expected behavior**
tableEntity.getProperty("latestEventTime") as OffsetDateTime works.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - Java 21
 - com.azure:azure-data-tables from 12.4.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by jairmyree** [comment] 2024-04-15 17:39
@knubonrk I was unable to reproduce the issue you described with the information provided. I tested both version 12.4.0 and 12.3.20 of azure-data-tables and did not observe any changes is the return value of `TableEntity.getProperty(String key)` for an `OffsetDateTime` property.

One thing I'd like to note:
`TableEntity.getProperty(String key)` returns `Object`, not `String`. Any returned properties must be casted to their appropriate types.

So that I'm able to better assist you, **please provide a detailed code snippet for the issue you encountered**.

**Comment by knubonrk** [comment] 2024-04-16 07:09
So after some digging in our code, we see that it is related to a query, and not simple get/set.

`    val tableClient = TableStoreClient(tableNamePrefix = "test",  tableNames = listOf("CastBug"))

    val client = tableClient.getTableClient("CastBug")

    //client.createTable()

//    val entity = TableEntity("default", "bug")
//    entity.addProperty("a_timestamp", OffsetDateTime.now())
//    client.createEntity(entity)

    val options = ListEntitiesOptions()
        .setFilter("PartitionKey eq '$DEFAULT_PARTITION_KEY'")
        .setSelect(listOf("a_timestamp"))
        .setTop(1)

    val entity = client.listEntities(options, null, null ).lastOrNull()

   // val entity = client.getEntity("default", "bug")

    val t: OffsetDateTime = entity?.getProperty("a_timestamp") as OffsetDateTime
    println(t)
`

This code crashes. Using getEntity works.

**Comment by knubonrk** [comment] 2024-04-16 07:10
Exception in thread "main" java.lang.ClassCastException: class java.lang.String cannot be cast to class java.time.OffsetDateTime (java.lang.String and java.time.OffsetDateTime are in module java.base of loader 'bootstrap')
	at no.nrk.tjenesteplattform.common.core.tablestore.TableStoreCallerKt.main(TableStoreCaller.kt:28)
	at no.nrk.tjenesteplattform.common.core.tablestore.TableStoreCallerKt.main(TableStoreCaller.kt)

**Comment by jairmyree** [comment] 2024-04-19 18:03
Thank you @knubonrk for providing additional information, I will look into this and reply shortly.

**Comment by jairmyree** [comment] 2024-04-19 18:31
@knubonrk Please note, the above code snippet that you have provided above is not valid Java 21 code using the standard libraries. I will do my best to make assumptions using the code snippet you have provided, but to be able to better assist you, I would ask that you provide **a valid Java 21 codesnippet including import statements so that I can properly configure my testing environment to reflect your scenario.**

**Comment by jairmyree** [comment] 2024-04-19 18:42
@knubonrk I have been able to identify the issue. I will begin working on a resolution.

**Comment by jairmyree** [comment] 2024-06-13 22:52
@knubonrk A fix for this issue has been included in azure-data-table 12.4.2. Please update to the latest SDK version. Thank you for reporting this issue to us.

**Closed by jairmyree** 2024-06-13 22:52 UTC
Labels: question, Client, customer-reported, Tables, needs-team-attention
