### ISSUE TITLE
Can you increase the version of the dependency com.fasterxml.jackson.dataformat:jackson-dataformat-xml above 2.15.3 ?

### ISSUE THREAD

**Issue by TreasureM** [Azure/azure-sdk-for-java#39295] opened 2024-03-19 13:54 UTC
**Query/Question**
At the moment the  library uses the dependency com.fasterxml.jackson.dataformat:jackson-dataformat-xml in version 2.13.5, which is quite behind the actual version or the version used by Spring Boot 3.

Unfortunately any version higher than 2.15.3 leads to a crash of the library. I add a file with the crash report. Please see below.

However Spring Boot 3 enforces a higher version.

So could you please increase the version for com.fasterxml.jackson.dataformat:jackson-dataformat-xml used by the library?

***Why is this not a Bug or a feature Request?***
Its a bit of a grey area here, I fear.

**Setup (please complete the following information if applicable):**
 - OS: Windows
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-storage-file-datalake:12.18.2
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added
- [exception.txt](https://github.com/Azure/azure-sdk-for-java/files/14651431/exception.txt)

**Comment by joshfree** [comment] 2024-03-19 17:06
@alzimmermsft will this be resolved by moving Storage to `azure-xml` ?

**Comment by alzimmermsft** [comment] 2024-03-19 17:09
Hi @TreasureM, thanks for filing this issue and including a stack trace of the exception thrown.

This doesn't appear to be an issue with the dependencies being used by the Storage SDK, as the exception shows that later versions than 2.13.5 are being used, the issue is that there is a dependency issue with the Jackson dependencies aligning on a version. The exception that `Java.isIterationType` is due to this as it was added in Jackson Databind 2.16.0, aligning the Jackson dependencies should resolve this.

@joshfree, yes, switching to `azure-xml` would resolve this as Jackson would no longer be used to serialize XML, removing the `jackson-dataformat-xml` dependency.

**Comment by TreasureM** [comment] 2024-03-20 08:52
/unresolve

We have a version conflict from our Spring Boot Application when we request the  dependency com.fasterxml.jackson.dataformat:jackson-dataformat-xml with the message 

"Caused by: java.lang.ClassCastException: class com.fasterxml.jackson.dataformat.yaml.YAMLFactory cannot be cast to class com.fasterxml.jackson.dataformat.xml.XmlFactory (com.fasterxml.jackson.dataformat.yaml.YAMLFactory and com.fasterxml.jackson.dataformat.xml.XmlFactory are in unnamed module of loader 'app')"

Can we resolve this by using azure-xml or do we have to wait till you change those dependencies?

**Comment by TreasureM** [comment] 2024-03-20 12:38
//resolve

We found the core problem. But it would still be intersting to know, when azure-xml will come in use here. ;)

**Comment by alzimmermsft** [comment] 2024-03-20 12:41
(Was just in the process of replying to the previous comment, but glad you found the solution to that)

I'll need to discuss the timeline with the owners of the Java Storage SDKs, and can update here once there is more concrete information. The backing dependency for this migration is still in beta (`azure-xml`) but we're actively validating it with beta releases of `azure-data-tables` and the admin portion of `azure-messaging-servicebus`. Roughly, if those go well `azure-xml` should be nearing GA status and then will come the work to migrate the Storage libraries to it.

**Closed** 2024-03-28 22:31 UTC
Labels: question, Storage, Client, customer-reported, issue-addressed, dependency-issue-jackson
