### ISSUE TITLE
[BUG] ServiceBusAdministrationClient.getQueueExists throws ResourceNotFoundException if queue does not exist

### ISSUE THREAD

**Issue by p4p4** [Azure/azure-sdk-for-java#32220] opened 2022-11-17 11:18 UTC
**Describe the bug**

Instead of returning false, the method throws an exception:

***Exception or Stack Trace***
```
...
Caused by: com.azure.core.exception.ResourceNotFoundException: Queue 'local-colorblob-queue' does not exist.
        at com.azure.messaging.servicebus.administration.ServiceBusAdministrationClient.getQueueWithResponse(ServiceBusAdministrationClient.java:682) ~[azure-messaging-servicebus-7.12.1.jar:7.12.1]
        at com.azure.messaging.servicebus.administration.ServiceBusAdministrationClient.getQueueExistsWithResponse(ServiceBusAdministrationClient.java:721) ~[azure-messaging-servicebus-7.12.1.jar:7.12.1]
        at com.azure.messaging.servicebus.administration.ServiceBusAdministrationClient.getQueueExists(ServiceBusAdministrationClient.java:703) ~[azure-messaging-servicebus-7.12.1.jar:7.12.1]

```
**To Reproduce**

call `adminTools.getQueueExists("some-non-existant-queue")`

**Expected behavior**
return false 

**Setup (please complete the following information):**

`implementation group:  ‘com.azure’, name: ‘azure-messaging-servicebus’, version: ‘7.12.1’`
failed

`implementation group:  ‘com.azure’, name: ‘azure-messaging-servicebus’, version: ‘7.11.0’`
worked

**Information Checklist**

- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by p4p4** [comment] 2022-11-17 12:04
closed as duplicate: https://github.com/Azure/azure-sdk-for-java/issues/32219

**Comment by alzimmermsft** [comment] 2022-11-17 13:29
Closing, duplicate of #32219

**Closed by alzimmermsft** 2022-11-17 13:29 UTC
Labels: question, customer-reported, needs-triage
