### ISSUE TITLE
maxConcurrency > 0 required but it was 0 in CosmosContainer.readMany(<<List<CosmosItemIdentity> >>,<<Classname>>.class)

### ISSUE THREAD

**Issue by adu11188** [Azure/azure-sdk-for-java#33681] opened 2023-02-23 10:50 UTC
We are getting Exception with below message frequently 

`java.lang.IllegalArgumentException: maxConcurrency > 0 required but it was 0    at reactor.core.publisher.FluxMergeSequential.<init>(FluxMergeSequential.java:78)    at reactor.core.publisher.FluxMergeSequential.<init>(FluxMergeSequential.java:64)    at reactor.core.publisher.Flux.mergeSequential(Flux.java:10065)    at reactor.core.publisher.Flux.mergeSequential(Flux.java:1734)    at com.azure.cosmos.implementation.query.ParallelDocumentQueryExecutionContext.drainAsync(ParallelDocumentQueryExecutionContext.java:446)    at com.azure.cosmos.implementation.query.PipelinedQueryExecutionContext.executeAsync(PipelinedQueryExecutionContext.java:120)    at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:386)    at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)    at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2397)    at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:169)    at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371)    at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96)    at reactor.core.publisher.FluxJust.subscribe(FluxJust.java:68)    at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)    at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)    at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)    at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)    at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)    at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2397)    at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2193)    at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onSubscribe(FluxOnErrorResume.java:74)    at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:192)    at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)    at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)    at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)    at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)    at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)    at reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2659)    at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:180)    at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:846)    at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:608)    at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:588)    at reactor.core.publisher.FluxFlatMap$FlatMapMain.onComplete(FluxFlatMap.java:465)    at reactor.core.publisher.DrainUtils.postCompleteDrain(DrainUtils.java:131)    at reactor.core.publisher.DrainUtils.postComplete(DrainUtils.java:186)    at reactor.core.publisher.FluxMapSignal$FluxMapSignalSubscriber.onComplete(FluxMapSignal.java:219)    at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)    at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:151)    at reactor.core.publisher.Mono.subscribe(Mono.java:4135)    at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:200)    at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)    at reactor.core.publisher.Mono.subscribe(Mono.java:4135)    at reactor.core.publisher.Mono.block(Mono.java:1702)    at com.azure.cosmos.CosmosContainer.blockFeedResponse(CosmosContainer.java:260)    at com.azure.cosmos.CosmosContainer.readMany(CosmosContainer.java:405)    at com.azure.cosmos.CosmosContainer.readMany(CosmosContainer.java:388)    at`

On investigation we found we need 
We need to use below properties to get/set the concurrency in java sdk for Azure Cosmos DB:
getMaxDegreeOfParallelism 
setMaxDegreeOfParallelism

But for API **CosmosContainer.readMany(<<List<CosmosItemIdentity> >>,<<Classname>>.class)**

We cannot do this setting.

Also we saw the source code as below where it is hardocded to -1

![image](https://user-images.githubusercontent.com/31798624/220886005-0da83d18-860c-4e3f-8de6-099b6f5c2c93.png)

How do we avoid this frequent exception in production. Do we need to not use this readMany API?

CosmodDB version
 <dependency>
		    <groupId>com.azure</groupId>
		    <artifactId>azure-cosmos</artifactId>
		    <version>4.39.0</version>
		</dependency>

**Comment by jeet1995** [comment] 2023-02-23 22:25
Hi @adu11188, this exception can be thrown if `itemIdentityList` is an empty list. Is that the case? 

If it is so, a fix for this has been shipped in `v4.40.0` of `azure-cosmos`. If not, would it be possible to share a code snippet which we can reproduce?

**Comment by adu11188** [comment] 2023-02-28 07:43
Hi @jeet1995  We do have the check added for empty list check. But we see the same exception occurring multiple times.

**Comment by jeet1995** [comment] 2023-02-28 13:49
Hi @adu11188, thanks for reaching out! Could you share a code snippet so that I can reproduce the exception and investigate it further?

**Comment by kushagraThapar** [comment] 2023-05-26 01:37
Closing because of inactivity.

**Closed by kushagraThapar** 2023-05-26 01:37 UTC
Labels: question, Cosmos, customer-reported, cosmos:v4-item, needs-team-attention
