### ISSUE TITLE
NPE during serialization of tags map of resource object 

### ISSUE THREAD

**Issue by dserdyuk** [Azure/azure-sdk-for-java#14722] opened 2020-09-02 04:24 UTC
**Describe the bug**

***Exception or Stack Trace***
java.lang.NullPointerException
	at com.microsoft.rest.serializer.AdditionalPropertiesDeserializer.deserialize(AdditionalPropertiesDeserializer.java:101)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4482)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434)
	at com.microsoft.rest.serializer.JacksonAdapter.deserialize(JacksonAdapter.java:137)
	at com.microsoft.rest.ServiceResponseBuilder.buildBody(ServiceResponseBuilder.java:216)
	at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:110)
	at com.microsoft.azure.AzureResponseBuilder.build(AzureResponseBuilder.java:56)
	at com.microsoft.azure.management.datafactory.v2018_06_01.implementation.FactoriesInner.getByResourceGroupDelegate(FactoriesInner.java:876)
	at com.microsoft.azure.management.datafactory.v2018_06_01.implementation.FactoriesInner.access$500(FactoriesInner.java:51)
	at com.microsoft.azure.management.datafactory.v2018_06_01.implementation.FactoriesInner$25.call(FactoriesInner.java:779)
	at com.microsoft.azure.management.datafactory.v2018_06_01.implementation.FactoriesInner$25.call(FactoriesInner.java:775)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120)
	at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153)
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:32)
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:22)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10423)
	at rx.Observable.subscribe(Observable.java:10390)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:443)
	at rx.observables.BlockingObservable.last(BlockingObservable.java:226)
	at com.microsoft.azure.arm.resources.collection.implementation.GroupableResourcesCoreImpl.getByResourceGroup(GroupableResourcesCoreImpl.java:110)
	at com.microsoft.azure.arm.resources.collection.implementation.GroupableResourcesCoreImpl.getByResourceGroup(GroupableResourcesCoreImpl.java:34)
	at com.blueprint.jgraph.POC$.adfServiceStatus(POC.scala:17)

**To Reproduce**
Create Azure data factory and try to retrieve it using sdk. REST API works via cUrl 

***Code Snippet***
   val credentials = AzureCliCredentials.create()
      val subscriptionId = "subscriptionId"
        val dataFactoryManager = DataFactoryManager.authenticate(credentials, subscriptionId)
      val adfName = "adf-name"
      val factory = dataFactoryManager.factories().getByResourceGroup("resource-group",
          adfName)

**Expected behavior**
factory object is retrived 
**Screenshots**

**Setup (please complete the following information):**
 - iOS
 - IntelliJ
 - Version : 1.0.0-beta-3, 1.0.0-beta-4

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by dserdyuk** [comment] 2020-09-02 04:24
<img width="1665" alt="Screen Shot 2020-09-01 at 9 17 47 PM" src="https://user-images.githubusercontent.com/304933/91931879-8abcc580-ec99-11ea-8ece-b3d27e39b5a0.png">
 debug screen

**Comment by dserdyuk** [comment] 2020-09-02 04:26
could be related to #5710

**Comment by joshfree** [comment] 2020-09-02 22:05
Thanks for reporting this issue @dserdyuk 😄 -- Someone from the `Mgmt` plane SDK team will follow up shortly.

/cc @yungezz

**Comment by yungezz** [comment] 2020-09-03 02:07
hi @xccc-msft could you pls help to look at this lite lib issue? thanks.

**Comment by xccc-msft** [comment] 2020-09-03 07:29
@dserdyuk I tried below code with `com.microsoft.azure.datafactory.v2018_06_01` 1.0.0-beta-3 and 1.0.0-beta-4:
```java
DataFactoryManager manager = DataFactoryManager.authenticate(credentials, credentials.defaultSubscriptionId());
Factory factory = manager.factories().getByResourceGroup("group", "factory");
for (String key: factory.tags().keySet()) {
    System.out.println(key + " : " +factory.tags().get(key));
}
```
Both work for me. I cannot reproduce

**Comment by dserdyuk** [comment] 2020-09-03 21:25
check this poc project
resource folder has console output and api response from https://docs.microsoft.com/en-us/rest/api/datafactory/factories/get

**Comment by dserdyuk** [comment] 2020-09-03 21:25
[poc-test.zip](https://github.com/Azure/azure-sdk-for-java/files/5171221/poc-test.zip)

**Comment by xccc-msft** [comment] 2020-09-04 03:18
@dserdyuk Just curious why you are using `azure-keyvault-secrets-spring-boot-starter`? If you only want to use `com.microsoft.azure.datafactory.v2018_06_01:azure-mgmt-datafactory`, the `azure-keyvault-secrets-spring-boot-starter` is not required.

For your issue, the issue comes from dependency conflict. To solve this, you can choose either as below:
- update azure.version from `2.3.1` to `2.3.3`, and then add `com.microsoft.azure:azure-client-authentication:1.7.5`.
- remove `azure-keyvault-secrets-spring-boot-starter` and related settings, and then add `com.microsoft.azure:azure-client-authentication:1.7.5`

**Comment by dserdyuk** [comment] 2020-09-04 17:09
Well, I'm using key-vault to get some properties from Azure KeyVault and I need boot-starter to be able to autowire it using @Value("${secretName}"). POC project doesn't have this code though

**Comment by xccc-msft** [comment] 2020-09-07 02:25
AzureCliCredentials is still available in 1.7.5. 
The dependency issue should come from `azure-keyvault-secrets-spring-boot-starter`. You may want to check what got updated from `2.3.1` to `2.3.3`.

**Comment by dserdyuk** [comment] 2020-09-08 20:36
thanks. I'll take a look. It's strange but I can't find it classpath.

**Comment by xccc-msft** [comment] 2020-09-10 02:30
Close this. Please feel free to reopen if you have any issue when using our SDK.

**Closed by xccc-msft** 2020-09-10 02:30 UTC
Labels: ARM, Mgmt, Track 1, bug, customer-reported
