### ISSUE TITLE
Rename vaultEndpoint to vaultUri/vaultUrl (idiomatic)

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-java#5999] opened 2019-10-22 21:53 UTC
After discussions with the arch board, we have decided to rename `vaultEndpoint` (parameters, properties, etc.) to `vaultUri` or `vaultUrl` (idiomatic). This is true for all clients and models where this exists across:

- [ ] Secrets
- [ ] Keys
- [ ] Certificates

**Comment by joshfree** [comment] 2019-10-24 18:28
Resolving as dupe of https://github.com/Azure/azure-sdk-for-java/issues/5772 as the PR for https://github.com/Azure/azure-sdk-for-java/issues/5772 also includes the vaultUri change.

**Closed by joshfree** 2019-10-24 18:28 UTC
Labels: Client, KeyVault, blocking-release
