### ISSUE TITLE
[FEATURE REQ] ProgressReceiver display total amount of bytes transfered before the transfer complete(parallel operation)

### ISSUE THREAD

**Issue by ihudedi** [Azure/azure-sdk-for-java#18389] opened 2020-12-29 19:51 UTC
Hi,
I am using ProgressReceiver to report progress of upload file.
It seems that the ProgressReceiver report on file transfered (according to the total amount)  but the file didn't transfer completely,
In case we are working with ParallelTransferOptions I can get many reporting that tell me the file trnasfered but actually it takes more time to finish.
The progress tells the bytes that are transferred now and not what  transfered in the past,
Thanks,
Itay

**Comment by gapra-msft** [comment] 2021-01-04 22:11
Hi @ihudedi 

Thank you for reporting this issue. Could you provide some sample code that reproduces this issue please?

**Comment by ihudedi** [comment] 2021-01-06 06:32
try (OutputStream outputStream =blobClient.getBlockBlobClient().getBlobOutputStream(blockBlobOutputStreamOptions){
                            bytesRead = -1;
                            byte[] bytesArray = new byte[jobUtilities.getBufferSize()];
                            while (!isInteruppted() && ((bytesRead = inputStream.read(bytesArray)) != -1)) {
                                outputStream.write(bytesArray, 0, bytesRead);
                            }
                        }
Seems that when I print the progress and it printed the total bytes as file size it takes more seconds to finish the close operation,
Thanks,
Itay

**Comment by gapra-msft** [comment] 2021-01-07 17:35
@ihudedi Thanks for the repro code. I will try to reproduce this issue and get back to you on our findings.

**Comment by gapra-msft** [comment] 2021-01-07 18:00
@ihudedi I have a reproduction set up. Could you provide a few more details?

What is the size of the file?
Could you share the values for ParallelTransferOptions?
What is the value for jobUtilities.getBufferSize()?

Thanks

**Comment by gapra-msft** [comment] 2021-01-08 19:34
@ihudedi So I thought about it a little more and here is what I think is happening. 

The buffered upload basically does a bunch of stageBlocks, followed by a commitBlockList. The progress reporting code measures the progress of the stageBlocks (every time a block is sent, we send that info over to the progress reporter). 
Hoewever, the data is only really written to the blob on the final commitBlockList, which can take some time depending on how many blocks have been written.

**Comment by ihudedi** [comment] 2021-01-12 06:25
jobUtilities.getBufferSize() = 32K
ParallelTransferOptions parallelTransferOptions = new ParallelTransferOptions();
//Maybe need to change those settings
int azureBlockUploadSize = 4194304;
int azureMaxSingleUploadSize = 4194304;
int azureMaxUploadConcurrency = 8;
boolean azureDisplayUploadProgress = true;

            parallelTransferOptions.setBlockSizeLong(Long.valueOf(azureBlockUploadSize));
        

            parallelTransferOptions.setMaxSingleUploadSizeLong(Long.valueOf(azureMaxSingleUploadSize));

            parallelTransferOptions.setMaxConcurrency(azureMaxUploadConcurrency);
        

            parallelTransferOptions.setProgressReceiver(new AzureProgressReceiver(azureFileCopy));
        
        blockBlobOutputStreamOptions.setParallelTransferOptions(parallelTransferOptions);

**Comment by ihudedi** [comment] 2021-01-21 00:14
Hi @gapra-msft 
You say above "every time a block is sent, we send that info over to the progress reporter"
Do you mean before the block is uploaded you report progress even if the upload didn't succeeed for this block or after the block 
uploaded successfully.
Beacuse I see that the time is from the block sent and not from the block upload suceessfully.
Thanks,
Itay

**Comment by ihudedi** [comment] 2021-01-21 21:19
Hi @rickle-msft 
Could you please look at this?
seems like a bug in the progress
Thanks,
Itay

**Comment by rickle-msft** [comment] 2021-01-21 21:29
The way the progress reporter works right now is it updates the count as data is going onto the wire. So it hasn't necessarily been confirmed successful yet. If a retry is issued on a given block, we will reduce the count to accommodate that and ensure data isn't counted twice.

We've been discussing the possibility of adding another method to the progress reporter that is something like a `onDataFinalized` that will be called when we have confirmed that the blob is actually committed rather than just when all the data is sent. Would that be helpful?

**Comment by ihudedi** [comment] 2021-01-21 22:24
Hi @rickle-msft 
So today the count is when sending the blob to the stage are and not when the blob arrive there.
After you stage the block can't you tell the progress that he staged or maybe when commit the block but I think you commit all blocks together?
Thanks,
Itay

**Comment by rickle-msft** [comment] 2021-01-21 23:11
We can't change the current behavior because it would be a breaking change, but we could explore the possibility of adding the method I mentioned above that would give a final report when it's done being committed. You are correct that we have to commit all blocks together, so we could only give one update as a final commit update. We could also look into adding a third method that accepts progress reports only when we have received a response from the stage request meaning it has been successfully accepted by the service. I can't make any promises about that at the moment though because it may be untenable with our current architecture.

**Comment by rickle-msft** [comment] 2021-02-01 18:55
@ihudedi Does this proposal look like it will suit your scenario?

**Comment by ihudedi** [comment] 2021-02-02 10:23
Hi @rickle-msft 
I think that if we know that block has been updated and not only sent it will be fine.
commit is operation on the end and not for every block so if we have method that inform that block was sent successfuly and not only being sent it will be fine,
Thanks,
Itay

**Comment by rickle-msft** [comment] 2021-02-02 21:44
Ok. I am going to change this to a feature request and we will have some internal discussions about whether we will be able to support this.

**Comment by rickle-msft** [comment] 2021-12-17 15:18
@ihudedi I'm taking another look at this and might have time to add this feature soon, but on reading the end of the conversation again, it's not entirely clear to me that the proposal I gave will work for you. Can you confirm that a dataFinalized method on ProgressReporter that is invoked when the blob is committed will suit your needs?

**Comment by ihudedi** [comment] 2021-12-18 19:46
Hi @rickle-msft
I would like to get progress after blob arrive to the stage area.getting an report that all blob committed not help me when using parallel operation.I would like to get report when blob arrived to stage and not when blob sent to stage.
Thanks,
Itay

**Comment by rickle-msft** [comment] 2021-12-20 20:15
Got it. Thank you for clarifying that before I started work on this. I'll do some research again to see if we can accommodate that.

**Comment by chenyuvm** [comment] 2022-02-15 05:26
Hi Azure blob expert,

I met one problem with the different blockSize or concurrency value, the process notification frequency keeps the same, it always transfer 65535 bytes every time. Here are my test code and test results. The 16.tar.gz is about 16M.

I would like to decrease the frequency to call function OnProgressReceived() during file uploading. Anyone can help is appreciated.

BlobAsyncClient client = new BlobClientBuilder()
.endpoint(url)
.blobName("16.tar.gz")
.buildAsyncClient();

long blockSize = 1 1024 1024L; // 1M
int maxConcurrency = 1;

ParallelTransferOptions parallelTransferOptions = new ParallelTransferOptions()
.setBlockSizeLong(blockSize)
.setMaxConcurrency(maxConcurrency)
.setProgressReceiver(bytesTransferred -> OnProgressReceived(bytesTransferred));

client.uploadFromFile(filePath, parallelTransferOptions, headers, null, AccessTier.HOT, null)
.doOnSuccess(success -> OnSuccess())
.doOnError(throwable -> OnError(throwable.getMessage()))
.subscribe();

private synchronized void OnProgressReceived(long bytesTransferred) {
count++;
bytes_transferred = bytesTransferred;
System.out.println(String.valueOf(count) + " " + new Date() + "uploaded: " + bytesTransferred);
}


The results:
1 Tue Feb 15 10:12:07 IRKT 2022uploaded: 65536
2 Tue Feb 15 10:12:07 IRKT 2022uploaded: 131072
3 Tue Feb 15 10:12:07 IRKT 2022uploaded: 196608
4 Tue Feb 15 10:12:07 IRKT 2022uploaded: 262144
.....
248 Tue Feb 15 10:12:52 IRKT 2022uploaded: 16252928
249 Tue Feb 15 10:12:52 IRKT 2022uploaded: 16318464
250 Tue Feb 15 10:12:52 IRKT 2022uploaded: 16384000
251 Tue Feb 15 10:12:52 IRKT 2022uploaded: 16391372

**Comment by rickle-msft** [comment] 2022-02-15 22:31
@chenyuvm Can you please file this as a separate issue and we can take a look at it? This is a different issue than the feature request on this thread.

**Closed** 2024-03-18 18:05 UTC
Labels: Storage, Client, customer-reported, feature-request
