### ISSUE TITLE
ShareDirectoryClient of root folder in File Share cannot access subdirectories [BUG]

### ISSUE THREAD

**Issue by lucaslilja** [Azure/azure-sdk-for-java#20811] opened 2021-04-20 07:00 UTC
**Describe the bug**
If a ShareDirectoryClient is created with the resource path "" (as in the root), it can then list files and directories in the root. But when a subdirectory is selected and used, then I get a 400 status code (see below).
If a ShareDirectoryClient is created with a subdirectory below root, then it is possible to access directories below it.

***Exception or Stack Trace***
Caused by: com.azure.storage.file.share.models.ShareStorageException: Status code 400, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidResourceName</Code><Message>The specifed resource name contains invalid characters.
RequestId:d5c7a2f4-901a-0092-43af-35e4ea000000
Time:2021-04-20T06:38:01.0929552Z</Message></Error>"
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[?:?]
	at com.azure.core.http.rest.RestProxy.instantiateUnexpectedException(RestProxy.java:337) ~[azure-core-1.12.0.jar:?]
	at com.azure.core.http.rest.RestProxy.lambda$ensureExpectedStatus$5(RestProxy.java:378) ~[azure-core-1.12.0.jar:?]

**To Reproduce**
Create a file share. Put one directory in the root of this file share called "subdir1" and another directory in "subdir1" called "subdir2".

***Code Snippet***
`
//This will throw a ShareStorageException
ShareDirectoryClient directoryClient = new ShareFileClientBuilder().connectionString(shareUrl)
                .shareName(fileShare).resourcePath("").buildDirectoryClient();
directoryClient.listFilesAndDirectories()
                .forEach((sfi) -> System.out.println(sfi.getName())); //This will print the directory name subdir1
directoryClient.getSubdirectoryClient("subdir1").exists(); //exists() causes the ShareStorageException
//This works
ShareDirectoryClient directoryClient = new ShareFileClientBuilder().connectionString(shareUrl)
                .shareName(fileShare).resourcePath("subdir1").buildDirectoryClient();
directoryClient.listFilesAndDirectories()
                .forEach((sfi) -> System.out.println(sfi.getName())); //This will print the directory name subdir2
directoryClient.getSubdirectoryClient("subdir2").exists(); //This will NOT throw any exceptions
`

**Expected behavior**
Accessing subdirectories from the "root" directory should not throw exceptions

**Setup (please complete the following information):**
 - OS: macOS Mojave
 - IDE : IntelliJ 2020.3
 - azure-storage-file-share 12.8.0

**Comment by jaschrep-msft** [comment] 2021-04-21 18:54
Hi @lucaslilja. Sorry for not responding earlier, but the cause of the issue was immediately found upon using your snippet and a fix is in the final stages of being merged. It will go out with the next release.

**Closed** 2021-04-22 20:11 UTC
Labels: Client, Storage, customer-reported, question
