### ISSUE TITLE
[BUG] CostManagement usage throw 400 when grouped by tag

### ISSUE THREAD

**Issue by Ramedlaw-knil** [Azure/azure-sdk-for-java#23350] opened 2021-08-04 14:14 UTC
**Describe the bug**
When you want to request the usage via the CostManagementManager (i use this function ".queries().usage(...)") and want to group your results by your self created tag, you get an 400.  It says that your dataset grouping is invalid. In "additional Information" i added  what i think causes this behaviour.

***Exception or Stack Trace***
```
com.azure.core.management.exception.ManagementException: Status code 400, "{"error":{"code":"BadRequest","message":"Invalid query definition: Invalid dataset grouping: 'myTag'; valid values: 'ResourceGroup','ResourceGroupName','ResourceLocation','ConsumedService','ResourceType','ResourceId','MeterId','BillingMonth','MeterCategory','MeterSubcategory','Meter','AccountName','DepartmentName','SubscriptionId','SubscriptionName','ServiceName','ServiceTier','EnrollmentAccountName','BillingAccountId','ResourceGuid','BillingPeriod','InvoiceNumber','ChargeType','PublisherType','ReservationId','ReservationName','Frequency','PartNumber','CostAllocationRuleName','MarkupRuleName','PricingModel',''.\r\n\r\n (Request ID: d63a6d26-c10a-423a-878b-086173bd84e8)"}}"
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at com.azure.core.http.rest.RestProxy.instantiateUnexpectedException(RestProxy.java:343)
	at com.azure.core.http.rest.RestProxy.lambda$ensureExpectedStatus$5(RestProxy.java:382)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:337)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:354)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onSubscribe(MonoCacheTime.java:293)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:192)
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:143)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:110)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:88)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:284)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:187)
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:174)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2664)
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:180)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onComplete(ScopePassingSpanSubscriber.java:102)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:260)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onComplete(ScopePassingSpanSubscriber.java:102)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:150)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:150)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1817)
	at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:159)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:145)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onComplete(ScopePassingSpanSubscriber.java:102)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:213)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onComplete(ScopePassingSpanSubscriber.java:102)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:142)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:400)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:419)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:473)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:684)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)
```

**To Reproduce**
1. Tag your resources
2. create an CostManagementManager with correct credentials and permissions
3. aggregate by totalCost and group by your created tag (the aggregation might me irrelevant)
4. do the request (you can see all in my code snippet)

***Code Snippet***
This is my complete code if you want to reproduce
``
        AzureProfile profile = new AzureProfile(AzureEnvironment.AZURE);
        TokenCredential credential = new DefaultAzureCredentialBuilder()
            .authorityHost(profile.getEnvironment().getActiveDirectoryEndpoint())
            .build();
        CostManagementManager  manager = CostManagementManager
            .authenticate(credential, profile);

        String scope = "subscriptions/XXXX-XXX-XXXXXXX";

        Map<String, QueryAggregation> aggregateByTotalCost = Map.of("totalCost", new QueryAggregation()
            .withName("Cost")
            .withFunction(FunctionType.SUM));

        List<QueryGrouping> groupByTag = Collections.singletonList(
            new QueryGrouping()
                .withType(QueryColumnType.TAG)
                .withName("myTag"));

        QueryDataset queryDataset = new QueryDataset()
            .withAggregation(
                aggregateByTotalCost)
            .withGrouping(
                groupByTag);

        QueryDefinition queryDefinition = new QueryDefinition()
            .withType(ExportType.ACTUAL_COST)
            .withTimeframe(TimeframeType.MONTH_TO_DATE)
            .withDataset(queryDataset);

        QueryResult usage = manager
            .queries()
            .usage(scope, queryDefinition);
``

**Expected behavior**
get the usage grouped by the specified tag

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows 10 
 - IDE: Intellij 2021.1.1
 - Library/Libraries: com.azure.resourcemanager:azure-resourcemanager-costmanagement 1.0.0-beta.3 and com.azure:azure-identity 1.3.4

**Additional context**
I think i already found the solution to the problem.
I already tried the same request in postman and got the correct response.
This was my requestBody
```json
{
    "type": "ActualCost",
    "dataSet": {
        "aggregation": {
            "totalCost": {
                "name": "Cost",
                "function": "Sum"
            }
        },
        "grouping": [
            {
                "type": "TagKey",
                "name": "myTag"
            }
        ]
    },
    "timeframe": "MonthToDate"
}
```

And here you can see that for grouping in the field "type" TagKey is specified, but in the code you use the enum value of "Tag".
Here a code snippet from the file QueryColumnType.java:
```
public final class QueryColumnType extends ExpandableStringEnum<QueryColumnType> {
    /** Static value Tag for QueryColumnType. */
    public static final QueryColumnType TAG = fromString("Tag");
```
I think there it should be "fromString("TagKey")".
Because when i change my postman request to use "Tag" instead of "TagKey" i get the same error message.

**Comment by joshfree** [comment] 2021-08-05 16:39
@weidongxu-microsoft could you please follow up with @Ramedlaw-knil?

**Comment by weidongxu-microsoft** [comment] 2021-08-06 03:00
@haolingdong-msft Could you check what is the different of the SDK payload and postman payload?

**Comment by haolingdong-msft** [comment] 2021-08-06 04:43
> @haolingdong-msft Could you check what is the different of the SDK payload and postman payload?

The difference is: the "type" field in "grouping" is "Tag" instead of "TagKey".  

See below payload for detail:
SDK payload
```
{
    "type": "ActualCost",
    "timeframe": "MonthToDate",
    "dataset": {
        "aggregation": {
            "totalCost": {
                "name": "Cost",
                "function": "Sum"
            }
        },
        "grouping": [
            {
                "type": "**Tag**",
                "name": "myTag"
            }
        ]
    }
}
```

postman payload
```
{
    "type": "ActualCost",
    "dataSet": {
        "aggregation": {
            "totalCost": {
                "name": "Cost",
                "function": "Sum"
            }
        },
        "grouping": [
            {
                "type": "**TagKey**",
                "name": "myTag"
            }
        ]
    },
    "timeframe": "MonthToDate"
}
```

**Comment by haolingdong-msft** [comment] 2021-08-09 06:45
Hi service team, the issue is caused by the swagger definition error in the "type" field in "grouping" in "dateSet". The type should be "TagKey" instead of "Tag" (Line 2880). Please refer to below swagger definition for detail.
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2019-11-01/costmanagement.json#L2876-L2887

**Comment by haolingdong-msft** [comment] 2021-08-09 06:47
@Ramedlaw-knil 
before service team doing the fix in swagger definition. You can try below code as a workaround:
```java
    String scope = "subscriptions/XXXX-XXX-XXXXXXX";

    Map<String, QueryAggregation> aggregateByTotalCost = Map.of("totalCost", new QueryAggregation()
        .withName("Cost")
        .withFunction(FunctionType.SUM));

    List<QueryGrouping> groupByTag = Collections.singletonList(
        new QueryGrouping()
            .withType(QueryColumnType.fromString("TagKey"))
            .withName("myTag"));

    QueryDataset queryDataset = new QueryDataset()
        .withAggregation(
            aggregateByTotalCost)
        .withGrouping(
            groupByTag);

    QueryDefinition queryDefinition = new QueryDefinition()
        .withType(ExportType.ACTUAL_COST)
        .withTimeframe(TimeframeType.MONTH_TO_DATE)
        .withDataset(queryDataset);

    QueryResult usage = manager
        .queries()
        .usage(scope, queryDefinition);
```

**Comment by Ramedlaw-knil** [comment] 2021-08-09 08:21
Thanks, workaround works fine!

**Comment by haolingdong-msft** [comment] 2021-08-10 01:43
> Thanks, workaround works fine!

@Ramedlaw-knil  It's good to know. Thanks for your feedback and trouble shooting.

**Comment by ShilpiGautam** [comment] 2021-09-02 20:45
@haolingdong-msft  it seems the issue has been resolved to customer satisfaction. Can you pls close the issue once you believe we have answered it.

@Ramedlaw-knil closing the issue . pls let us know if more info is needed.

**Closed by ShilpiGautam** 2021-09-02 20:45 UTC
Labels: question, Service Attention, Mgmt, customer-reported, Cost Management, Mgmt - Track 2, needs-team-attention

**Comment by weidongxu-microsoft** [comment] 2021-09-03 02:06
Root cause of the issue is on cost-management service @ms-premp, @ramaganesan-rg.
