### ISSUE TITLE
SSLHandshake Exception: corrupted stream - out of bounds length found

### ISSUE THREAD

**Issue by sfc-gh-magupta** [Azure/azure-sdk-for-java#32526] opened 2022-12-08 22:25 UTC
**Describe the bug**
AZURE_STORAGE : corrupted stream - out of bounds length found

Timestamp: 2022-11-04 13:38:29.991000+00:00
storageAccount = qi1sfusgvacustfdn024
Request: DeleteFile
package: com.azure.storage.blob, using BlobClient, version: V12.16
Method: BlobClient.Delete()

***Exception or Stack Trace***
javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.handshakeException(ReferenceCountedOpenSslEngine.java:1895)
	Suppressed: The stacktrace has been enhanced by Reactor, refer to additional information below: 
Assembly trace from producer [reactor.core.publisher.MonoCreate] :
	reactor.core.publisher.Mono.create
	reactor.netty.resources.PooledConnectionProvider.acquire(PooledConnectionProvider.java:122)
Error has been observed at the following site(s):
	*_____________Mono.create ⇢ at reactor.netty.resources.PooledConnectionProvider.acquire(PooledConnectionProvider.java:122)
	|_                        ⇢ at reactor.netty.http.client.HttpConnectionProvider.acquire(HttpConnectionProvider.java:48)
	*_____________Mono.create ⇢ at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:210)
	|_         Mono.retryWhen ⇢ at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:271)
	*__________Flux.concatMap ⇢ at reactor.util.retry.RetrySpec.generateCompanion(RetrySpec.java:356)
	*________________________ ⇢ at reactor.netty.http.client.HttpClientFinalizer._connect(HttpClientFinalizer.java:156)
	|_       Mono.flatMapMany ⇢ at reactor.netty.http.client.HttpClientFinalizer.responseConnection(HttpClientFinalizer.java:101)
	|_            Flux.single ⇢ at com.azure.core.http.netty.NettyAsyncHttpClient.send(NettyAsyncHttpClient.java:105)
	|_        Mono.onErrorMap ⇢ at com.azure.core.http.netty.NettyAsyncHttpClient.send(NettyAsyncHttpClient.java:106)
	|_         Mono.retryWhen ⇢ at com.azure.core.http.netty.NettyAsyncHttpClient.send(NettyAsyncHttpClient.java:117)
	|_           Mono.flatMap ⇢ at com.azure.storage.common.policy.ScrubEtagPolicy.process(ScrubEtagPolicy.java:37)
	*__________Flux.concatMap ⇢ at reactor.util.retry.RetrySpec.generateCompanion(RetrySpec.java:356)
	*_______________Mono.then ⇢ at com.azure.core.http.policy.HttpLoggingPolicy.process(HttpLoggingPolicy.java:119)
	|_           Mono.flatMap ⇢ at com.azure.core.http.policy.HttpLoggingPolicy.process(HttpLoggingPolicy.java:120)
	|_         Mono.doOnError ⇢ at com.azure.core.http.policy.HttpLoggingPolicy.process(HttpLoggingPolicy.java:122)
	|_               Mono.map ⇢ at com.azure.storage.common.policy.ResponseValidationPolicyBuilder$ResponseValidationPolicy.process(ResponseValidationPolicyBuilder.java:80)
	|_               Mono.map ⇢ at com.azure.storage.common.policy.ResponseValidationPolicyBuilder$ResponseValidationPolicy.process(ResponseValidationPolicyBuilder.java:80)
	|_                        ⇢ at com.azure.storage.common.policy.MetadataValidationPolicy.process(MetadataValidationPolicy.java:48)
	|_                        ⇢ at com.azure.core.http.policy.AddDatePolicy.lambda$process$0(AddDatePolicy.java:35)
	*______________Mono.defer ⇢ at com.azure.core.http.policy.AddDatePolicy.process(AddDatePolicy.java:28)
	|_           Mono.timeout ⇢ at com.azure.storage.common.policy.RequestRetryPolicy.attemptAsync(RequestRetryPolicy.java:120)
	|_ Mono.delaySubscription ⇢ at com.azure.storage.common.policy.RequestRetryPolicy.attemptAsync(RequestRetryPolicy.java:121)
	|_           Mono.flatMap ⇢ at com.azure.storage.common.policy.RequestRetryPolicy.attemptAsync(RequestRetryPolicy.java:122)
	|_     Mono.onErrorResume ⇢ at com.azure.storage.common.policy.RequestRetryPolicy.attemptAsync(RequestRetryPolicy.java:163)
	*______________Mono.error ⇢ at com.azure.storage.common.policy.RequestRetryPolicy.lambda$attemptAsync$1(RequestRetryPolicy.java:204)
	*______Mono.onErrorResume ⇢ at com.azure.storage.common.policy.RequestRetryPolicy.attemptAsync(RequestRetryPolicy.java:163)
	*______Mono.onErrorResume ⇢ at com.azure.storage.common.policy.RequestRetryPolicy.attemptAsync(RequestRetryPolicy.java:163)
	*______Mono.onErrorResume ⇢ at com.azure.storage.common.policy.RequestRetryPolicy.attemptAsync(RequestRetryPolicy.java:163)
	|_                        ⇢ at com.azure.storage.common.policy.RequestRetryPolicy.process(RequestRetryPolicy.java:50)
	|_                        ⇢ at com.azure.core.http.policy.RequestIdPolicy.process(RequestIdPolicy.java:55)
	|_                        ⇢ at com.azure.core.http.policy.UserAgentPolicy.process(UserAgentPolicy.java:123)
	|_                        ⇢ at com.azure.core.http.HttpPipeline.lambda$send$0(HttpPipeline.java:103)
	*______________Mono.defer ⇢ at com.azure.core.http.HttpPipeline.send(HttpPipeline.java:101)
	|_                        ⇢ at com.azure.core.http.HttpPipeline.send(HttpPipeline.java:89)
	|_                        ⇢ at com.azure.core.http.rest.RestProxy.send(RestProxy.java:119)
	|_               Mono.map ⇢ at com.azure.core.implementation.serializer.HttpResponseDecoder.decode(HttpResponseDecoder.java:38)
	|_           Mono.flatMap ⇢ at com.azure.core.http.rest.RestProxy.ensureExpectedStatus(RestProxy.java:366)
	|_          Mono.doOnEach ⇢ at com.azure.core.http.rest.RestProxy.handleRestReturnType(RestProxy.java:592)
	|_      Mono.contextWrite ⇢ at com.azure.core.http.rest.RestProxy.handleRestReturnType(RestProxy.java:593)
	|_           Mono.flatMap ⇢ at com.azure.core.http.rest.RestProxy.handleRestReturnType(RestProxy.java:603)
	|_                        ⇢ at com.azure.storage.blob.implementation.BlobsImpl.deleteWithResponseAsync(BlobsImpl.java:868)
	|_               Mono.map ⇢ at com.azure.storage.blob.specialized.BlobAsyncClientBase.deleteWithResponse(BlobAsyncClientBase.java:1686)
Original Stack Trace:
		at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.handshakeException(ReferenceCountedOpenSslEngine.java:1895)
		at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.wrap(ReferenceCountedOpenSslEngine.java:822)
		at java.base/javax.net.ssl.SSLEngine.wrap(SSLEngine.java:522)
		at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:1040)
		at io.netty.handler.ssl.SslHandler.wrapNonAppData(SslHandler.java:926)
		at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1408)
		at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1246)
		at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1286)
		at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
		at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
		at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
		at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:425)
		at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
		at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
		at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: java.security.cert.CertificateException: corrupted stream - out of bounds length found
	at io.netty.handler.ssl.util.LazyX509Certificate.unwrap(LazyX509Certificate.java:237)
	at io.netty.handler.ssl.util.LazyX509Certificate.getSubjectX500Principal(LazyX509Certificate.java:81)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:240)
	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:276)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:141)
	at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$ExtendedTrustManagerVerifyCallback.verify(ReferenceCountedOpenSslClientContext.java:234)
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify(ReferenceCountedOpenSslContext.java:773)
	at io.netty.internal.tcnative.CertificateVerifierTask.runTask(CertificateVerifierTask.java:36)
	at io.netty.internal.tcnative.SSLTask.run(SSLTask.java:48)
	at io.netty.internal.tcnative.SSLTask.run(SSLTask.java:42)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.runAndResetNeedTask(ReferenceCountedOpenSslEngine.java:1484)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.access$700(ReferenceCountedOpenSslEngine.java:94)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine$TaskDecorator.run(ReferenceCountedOpenSslEngine.java:1459)
	at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1548)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1394)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1246)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1286)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:425)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.security.cert.CertificateException: corrupted stream - out of bounds length found
	at org.bouncycastle.jcajce.provider.CertificateFactory.readCertificate(Unknown Source)
	at org.bouncycastle.jcajce.provider.CertificateFactory.engineGenerateCertificate(Unknown Source)
	at java.base/java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:355)
	at io.netty.handler.ssl.util.LazyX509Certificate.unwrap(LazyX509Certificate.java:234)
	... 38 more
Caused by: java.io.IOException: corrupted stream - out of bounds length found
	at org.bouncycastle.asn1.ASN1InputStream.readLength(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readObject(Unknown Source)
	at org.bouncycastle.asn1.DERSequenceParser.readObject(Unknown Source)
	at org.bouncycastle.jcajce.provider.CertificateFactory.readDERCertificate(Unknown Source)
	... 42 more

**To Reproduce**
Its not consistent reproducible issue.

***Code Snippet***
BlobClient.Delete()

**Expected behavior**
Successful client connection setup and delete request getting handled correctly.
Even if there is some connection/ssl errors, SDK should handle them properly and retry. 

**Screenshots**

**Setup (please complete the following information):**
 - OS: Linux
 - IDE: [e.g. IntelliJ] no ide, its on prod.
 - Library/Libraries: com.azure.storage.blob, using BlobClient, version: V12.16
 - Java version: [e.g. 8] 
 - App Server/Environment: Linux Machine, inside jetty server
 - Frameworks: 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by sfc-gh-magupta** [comment] 2022-12-14 00:08
Hi @alzimmermsft,
Thanks for looking into it. I would be more comfortable sharing it securely through Azure support secure file transfer or over email. I was already working with a Azure support person for this, let me ask them to create a secure share and share it with you. Can you also please share your email address? If other thing doen't work, I can email the file to you.

**Comment by alzimmermsft** [comment] 2022-12-14 16:11
> Hi @alzimmermsft, Thanks for looking into it. I would be more comfortable sharing it securely through Azure support secure file transfer or over email. I was already working with a Azure support person for this, let me ask them to create a secure share and share it with you. Can you also please share your email address? If other thing doen't work, I can email the file to you.

I received the dependencies and I'm looking through them and using them to determine a root cause now.

**Comment by ki1729** [comment] 2022-12-14 19:14
@sfc-gh-magupta  : Given the transient nature of the issue and the erroe message, the most likely cause for this would be a bad SSL cert / config on one of the servers of a load balanced endpoint. You can get the cert and check if it is valid by using openssl.
`openssl s_client -showcerts -connect <endpoint>` 
But if it is just one of the servers that have this problem, it will be hard to find the problem because of the load balancer

**Comment by sfc-gh-magupta** [comment] 2022-12-14 20:15
@ki1729 thanks for your response. As this is transient issue, its hard to do openssl validations on our side, when this happens.

Btw regarding the ask from @alzimmermsft I have shared the whole maven dependency through the Azure support secure file transfer. and Dan from Azure support should have shared it with you? Please see, if you can figure out something from the dependencies versions?

**Comment by alzimmermsft** [comment] 2022-12-14 20:58
I did get a chance to look at the dependencies and unfortunately there wasn't much I was able to find. Looking through the dependencies and the stack trace of the exception you included in the issue description the Azure SDKs don't touch any of that code stack. The only involvement the Azure SDKs have are using Reactor Netty/Netty as the default HTTP stack and the Storage SDK using that stack to make requests to the Storage service. Everything else is internals to how Netty consumes the classpath for SSL and what BouncyCastle is providing to the classpath. You may find a quicker solution working with those projects to see if they've seen cases like this in the past.

All that said, I do have a follow up I'll be investigating for request retrying. In my investigation above I realized that when this error occurs Netty wraps the exception thrown by BouncyCastle in an IllegalStateException which may not be getting retried by the SDKs as it should be, and this is due to how exceptions are being inspected for retrying. I should have something for this early next week.

**Comment by sfc-gh-magupta** [comment] 2022-12-16 03:35
@alzimmermsft sounds good. Yes SDK retrying such transient errors, would be pretty useful for the customers. Will be looking forward to the change. Thanks!

**Comment by alzimmermsft** [comment] 2023-02-03 19:51
@sfc-gh-magupta I'm going to close this as the SDKs now have better handling for inspecting whether an exception should be retried (changed in #32648). Aside from that everything else in this issue is outside of our code and we don't determine interactions with that code.

**Closed by alzimmermsft** 2023-02-03 19:51 UTC
Labels: question, Azure.Core, customer-reported, HttpClient

**Comment by sfc-gh-magupta** [comment] 2023-02-07 23:34
@alzimmermsft thanks for the fix. Can you please tell me, in which version of SDK, should I expect your change? And any ETA for that?
