### ISSUE TITLE
[BUG] com.microsoft.azure.servicebus.amqp.AmqpException: The link 'G8:15665319:Receiver_47a5f0_1ae2eed451734252a5c4e6128a4e1523_G8' is force detached. Code: consumer(link4236931)

### ISSUE THREAD

**Issue by marvinstorage** [Azure/azure-sdk-for-java#6280] opened 2019-11-12 11:11 UTC
I have created a small demo application to recreate the issue we are running into during production. 

We have _ServiceBusExceptionDemo_ running that is listening to a queue _demoinboxqueue_.  It can just recieve message fine. 
The problem occurs when we change the _Lock duration_  of the queue while the demo application is running.
I notice that an exception is rightfully thrown and that the library is then trying to recreate the receive link:
` primitives.CoreMessageReceiver - Receive link 'Receiver_47a5f0_1ae2eed451734252a5c4e6128a4e1523_G8' to 'demoinboxqueue', sessionId 'null' will be reopened after 'PT1S'`

**Bug:**  Connection/Reciever link is not correctly restored.  When there are new messages on the queue the demo application is unable to receive them. (after the _Lock duration_ via properties screen of queue in azure portal is changed)

```java package com.demo.servicebus;

import com.microsoft.azure.servicebus.*;
import com.microsoft.azure.servicebus.primitives.ConnectionStringBuilder;
import com.microsoft.azure.servicebus.primitives.ServiceBusException;
import java.time.Duration;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class ServiceBusExceptionDemo implements IMessageHandler {

    public static void main(String[] args) {
        ServiceBusExceptionDemo demo = new ServiceBusExceptionDemo();
        try {
            demo.setupQueueClient();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }

    private ExecutorService executorService = Executors.newSingleThreadExecutor();
    private String connectionString = "Endpoint=sb://demoExampleSB.servicebus.windows.net/;SharedAccessKeyName=Listen-demoinboxqueue;SharedAccessKey=1L2uJtU2OC7Ze8ojcIuzS783pHcN75ooCHpQ7BSCBYE=;EntityPath=demoinboxqueue";
    private IQueueClient client;

    public void setupQueueClient() throws InterruptedException {
        try {
            client = new QueueClient(new ConnectionStringBuilder(connectionString), ReceiveMode.PEEKLOCK);
            client.registerMessageHandler(
                this,
                new MessageHandlerOptions(5,
                    true,
                    Duration.ofMinutes(5L),
                    Duration.ofMinutes(60)
                ), executorService
            );

        } catch (ServiceBusException | InterruptedException e) {
            e.printStackTrace();
        }
    }

    @Override
    public CompletableFuture<Void> onMessageAsync(IMessage message) {
        System.out.println( "onMessageAsync: " + new String(message.getMessageBody().getBinaryData().get(0)));
        return CompletableFuture.completedFuture(null);
    }

    @Override
    public void notifyException(Throwable throwable, ExceptionPhase exceptionPhase) {
        throwable.printStackTrace();
    }
}
```
I get the following error:
```java 
2019-11-11 15:01:53.933 INFO   us.primitives.MessagingFactory - Creating messaging factory from connection string 'Endpoint=sb://demoExampleSB.servicebus.windows.net/;EntityPath=demoinboxqueue;'
2019-11-11 15:01:53.963 INFO   us.primitives.MessagingFactory - Creating messaging factory from namespace endpoint uri 'sb://demoExampleSB.servicebus.windows.net/'
2019-11-11 15:01:53.977 INFO   us.primitives.MessagingFactory - Creating and starting reactor
2019-11-11 15:01:54.047 INFO   us.primitives.MessagingFactory - Started reactor
2019-11-11 15:01:54.047 INFO   us.primitives.MessagingFactory - starting reactor instance.
2019-11-11 15:01:54.064 INFO   us.primitives.MessagingFactory - Creating connection to host 'demoExampleSB.servicebus.windows.net:5671'
2019-11-11 15:01:55.087 INFO   us.primitives.MessagingFactory - MessagingFactory opened.
2019-11-11 15:01:55.089 INFO   us.primitives.MessagingFactory - Connection opened to host.
2019-11-11 15:01:55.095 INFO   us.primitives.MessagingFactory - Creating CBS link to $cbs
2019-11-11 15:01:55.097 INFO   t.azure.servicebus.QueueClient - Created queue client to connection string 'Endpoint=sb://demoExampleSB.servicebus.windows.net/;EntityPath=demoinboxqueue;'
2019-11-11 15:01:55.098 INFO   rvicebus.MessageAndSessionPump - Registering message handler on entity 'demoinboxqueue' with 'MessageHandlerOptions - AutoComplete:true, MaxConcurrentCalls:5, MaxAutoRenewDuration:PT5M'
2019-11-11 15:01:55.107 INFO   ure.servicebus.MessageReceiver - Creating MessageReceiver to entity 'demoinboxqueue', ReceiveMode 'PEEKLOCK'
2019-11-11 15:01:55.117 INFO   primitives.CoreMessageReceiver - Creating core message receiver to 'demoinboxqueue'
2019-11-11 15:01:55.138 INFO   primitives.RequestResponseLink - Opened requestresponselink to $cbs
2019-11-11 15:01:55.139 INFO   us.primitives.MessagingFactory - Created CBS link to $cbs
2019-11-11 15:01:55.228 INFO   primitives.CoreMessageReceiver - Creating receive link to 'demoinboxqueue'
2019-11-11 15:01:55.251 INFO   primitives.CoreMessageReceiver - Receive link to 'demoinboxqueue' opened.
2019-11-11 15:01:55.251 INFO   ure.servicebus.MessageReceiver - Created MessageReceiver to entity 'demoinboxqueue'
2019-11-11 15:01:55.253 INFO   ure.servicebus.MessageReceiver - Created MessageBrowser to entity 'demoinboxqueue'
2019-11-11 15:01:55.254 INFO   rvicebus.MessageAndSessionPump - Created MessageReceiver to entity 'demoinboxqueue'
2019-11-11 15:02:16.474 WARN   primitives.CoreMessageReceiver - Receive link 'Receiver_47a5f0_1ae2eed451734252a5c4e6128a4e1523_G8' to 'demoinboxqueue', sessionId 'null' closed with error.
com.microsoft.azure.servicebus.primitives.ServiceBusException: com.microsoft.azure.servicebus.amqp.AmqpException: The link 'G8:15665319:Receiver_47a5f0_1ae2eed451734252a5c4e6128a4e1523_G8' is force detached. Code: consumer(link4236931). Details: InnerMessageReceiver was closed. TrackingId:67c04b850000001c0140a6835dc969d3_G8_B2, SystemTracker:demoExampleSB:Queue:demoinboxqueue, Timestamp:2019-11-11T14:02:16
	at com.microsoft.azure.servicebus.primitives.ExceptionUtil.toException(ExceptionUtil.java:53)
	at com.microsoft.azure.servicebus.primitives.CoreMessageReceiver.onClose(CoreMessageReceiver.java:784)
	at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.processOnClose(BaseLinkHandler.java:66)
	at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.onLinkRemoteClose(BaseLinkHandler.java:42)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.servicebus.primitives.MessagingFactory$RunReactor.run(MessagingFactory.java:491)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.microsoft.azure.servicebus.amqp.AmqpException: The link 'G8:15665319:Receiver_47a5f0_1ae2eed451734252a5c4e6128a4e1523_G8' is force detached. Code: consumer(link42326931). Details: InnerMessageReceiver was closed. TrackingId:67c04b850000001c0140a6835dc969d3_G8_B2, SystemTracker:demoExampleSB:Queue:demoinboxqueue, Timestamp:2019-11-11T14:02:16
	... 10 common frames omitted
2019-11-11 15:02:16.474 INFO   primitives.CoreMessageReceiver - Receive link 'Receiver_47a5f0_1ae2eed451734252a5c4e6128a4e1523_G8' to 'demoinboxqueue', sessionId 'null' will be reopened after 'PT1S'
2019-11-11 15:02:17.475 INFO   primitives.CoreMessageReceiver - Recreating receive link to 'demoinboxqueue'
2019-11-11 15:02:17.488 INFO   primitives.CoreMessageReceiver - Creating receive link to 'demoinboxqueue'
2019-11-11 15:02:17.499 INFO   primitives.CoreMessageReceiver - Receive link to 'demoinboxqueue' opened.

```
```xml 
<dependency>
   <groupId>com.microsoft.azure</groupId>
   <artifactId>azure-servicebus</artifactId>
   <version>3.0.0</version>
</dependency>
```

**Comment by hemanttanwar** [comment] 2019-11-14 20:29
@marvinstorage   Thank You fir the detail provided. It was helpful.  I am able to replicate the issue.
We will update you as we investigate this issue. 
This issue exists with  following version also.
<dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>azure-servicebus</artifactId>
      <version>3.1.2</version>
    </dependency>

**Comment by hemanttanwar** [comment] 2019-11-14 20:42
Here is more details when we change LockDuration for this queue in Azure portal. "Using 3.1.2" version of this library. The messages after this does not show up in existing Registered Message Handler.

3015DEBUG   2019-11-14 11:46:49,095 [ReactorThreadee44f1ee-57b8-4913-aeb3-5ffd9fc09bf9] com.microsoft.azure.servicebus.amqp.BaseLinkHandler  - link remote close. linkName:Receiver_2c7538_2a24d7c31cea451a8e01bc6a1fc74625_G24
DEBUG   2019-11-14 11:46:49,096 [ReactorThreadee44f1ee-57b8-4913-aeb3-5ffd9fc09bf9] com.microsoft.azure.servicebus.amqp.BaseLinkHandler  - linkName:Receiver_2c7538_2a24d7c31cea451a8e01bc6a1fc74625_G24, ErrorCondition:amqp:link:detach-forced, The link 'G24:4097883:Receiver_2c7538_2a24d7c31cea451a8e01bc6a1fc74625_G24' is force detached. Code: consumer(link21879947). Details: InnerMessageReceiver was closed. TrackingId:2ef8c89e0000001a014ddc8b5dcdae43_G24_B19, SystemTracker:servicebus-sdk-tests:Queue:demoinboxqueue, Timestamp:2019-11-14T19:46:49
DEBUG   2019-11-14 11:46:49,115 [ReactorThreadee44f1ee-57b8-4913-aeb3-5ffd9fc09bf9] com.microsoft.azure.servicebus.primitives.CoreMessageReceiver  - Cancelled SAS Token renew timer
WARN    2019-11-14 11:46:49,118 [ReactorThreadee44f1ee-57b8-4913-aeb3-5ffd9fc09bf9] com.microsoft.azure.servicebus.primitives.CoreMessageReceiver  - Receive link 'Receiver_2c7538_2a24d7c31cea451a8e01bc6a1fc74625_G24' to 'demoinboxqueue', sessionId 'null' closed with error.
com.microsoft.azure.servicebus.primitives.ServiceBusException: com.microsoft.azure.servicebus.amqp.AmqpException: The link 'G24:4097883:Receiver_2c7538_2a24d7c31cea451a8e01bc6a1fc74625_G24' is force detached. Code: consumer(link21879947). Details: InnerMessageReceiver was closed. TrackingId:2ef8c89e0000001a014ddc8b5dcdae43_G24_B19, SystemTracker:servicebus-sdk-tests:Queue:demoinboxqueue, Timestamp:2019-11-14T19:46:49
	at com.microsoft.azure.servicebus.primitives.ExceptionUtil.toException(ExceptionUtil.java:53)
	at com.microsoft.azure.servicebus.primitives.CoreMessageReceiver.onClose(CoreMessageReceiver.java:784)
	at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.processOnClose(BaseLinkHandler.java:66)
	at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.onLinkRemoteClose(BaseLinkHandler.java:42)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.servicebus.primitives.MessagingFactory$RunReactor.run(MessagingFactory.java:491)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.microsoft.azure.servicebus.amqp.AmqpException: The link 'G24:4097883:Receiver_2c7538_2a24d7c31cea451a8e01bc6a1fc74625_G24' is force detached. Code: consumer(link21879947). Details: InnerMessageReceiver was closed. TrackingId:2ef8c89e0000001a014ddc8b5dcdae43_G24_B19, SystemTracker:servicebus-sdk-tests:Queue:demoinboxqueue, Timestamp:2019-11-14T19:46:49
	... 10 more
INFO    2019-11-14 11:46:49,128 [ReactorThreadee44f1ee-57b8-4913-aeb3-5ffd9fc09bf9] com.microsoft.azure.servicebus.primitives.CoreMessageReceiver  - Receive link 'Receiver_2c7538_2a24d7c31cea451a8e01bc6a1fc74625_G24' to 'demoinboxqueue', sessionId 'null' will be reopened after 'PT1S'
DEBUG   2019-11-14 11:46:49,130 [ReactorThreadee44f1ee-57b8-4913-aeb3-5ffd9fc09bf9] com.microsoft.azure.servicebus.amqp.BaseLinkHandler  - local link close. linkName:Receiver_2c7538_2a24d7c31cea451a8e01bc6a1fc74625_G24
DEBUG   2019-11-14 11:46:49,134 [ReactorThreadee44f1ee-57b8-4913-aeb3-5ffd9fc09bf9] com.microsoft.azure.servicebus.amqp.SessionHandler  - onSessionLocalClose - entityName: demoinboxqueue, condition: Error{condition=null, description='null', info=null}
DEBUG   2019-11-14 11:46:49,204 [ReactorThreadee44f1ee-57b8-4913-aeb3-5ffd9fc09bf9] com.microsoft.azure.servicebus.amqp.SessionHandler  - onSessionRemoteClose - entityName: demoinboxqueue, condition: Error{condition=null, description='null', info=null}
INFO    2019-11-14 11:46:50,131 [pool-3-thread-5] com.microsoft.azure.servicebus.primitives.CoreMessageReceiver  - Recreating receive link to 'demoinboxqueue'
DEBUG   2019-11-14 11:46:50,132 [pool-3-thread-5] com.microsoft.azure.servicebus.primitives.MessagingFactory  - Sending token for amqp://servicebus-sdk-tests.servicebus.windows.net/demoinboxqueue
DEBUG   2019-11-14 11:46:50,133 [pool-2-thread-6] com.microsoft.azure.servicebus.primitives.SASUtil  - Generated SAS token for resource: amqp://servicebus-sdk-tests.servicebus.windows.net/demoinboxqueue with sas key name : demoinboxqueuePolicy
DEBUG   2019-11-14 11:46:50,134 [pool-2-thread-6] com.microsoft.azure.servicebus.primitives.CommonRequestResponseOperations  - Sending CBS Token of type 'servicebus.windows.net:sastoken' to 'amqp://servicebus-sdk-tests.servicebus.windows.net/demoinboxqueue'
DEBUG   2019-11-14 11:46:50,134 [pool-2-thread-6] com.microsoft.azure.servicebus.primitives.RequestResponseLink  - Sending request with id:request:2
DEBUG   2019-11-14 11:46:50,134 [ReactorThreadee44f1ee-57b8-4913-aeb3-5ffd9fc09bf9] com.microsoft.azure.servicebus.primitives.RequestResponseLink  - Starting requestResponseLink $cbs internal sender send loop
DEBUG   2019-11-14 11:46:50,134 [ReactorThreadee44f1ee-57b8-4913-aeb3-5ffd9fc09bf9] com.microsoft.azure.servicebus.primitives.RequestResponseLink  - RequestResponseLink $cbs internal sender sent a request. available credit :98
DEBUG   2019-11-14 11:46:50,134 [ReactorThreadee44f1ee-57b8-4913-aeb3-5ffd9fc09bf9] com.microsoft.azure.servicebus.primitives.RequestResponseLink  - RequestResponseLink $cbs internal sender send loop ending as there are no more requests enqueued.
DEBUG   2019-11-14 11:46:50,135 [ReactorThreadee44f1ee-57b8-4913-aeb3-5ffd9fc09bf9] com.microsoft.azure.servicebus.primitives.RequestResponseLink  - RequestResponseLink $cbs internal sender send loop stopped.
DEBUG   2019-11-14 11:46:50,203 [ReactorThreadee44f1ee-57b8-4913-aeb3-5ffd9fc09bf9] com.microsoft.azure.servicebus.amqp.ReceiveLinkHandler  - onDelivery: linkName:RequestResponseLink-Receiver_66c71b_2a24d7c31cea451a8e01bc6a1fc74625_G24, updatedLinkCredit:2147483646, remoteCredit:2147483645, remoteCondition:Error{condition=null, description='null', info=null}, delivery.isPartial:false
DEBUG   2019-11-14 11:46:50,203 [pool-2-thread-6] com.microsoft.azure.servicebus.primitives.RequestResponseLink  - RequestRespnseLink received response for request with id :request:2
DEBUG   2019-11-14 11:46:50,203 [pool-2-thread-6] com.microsoft.azure.servicebus.primitives.RequestResponseLink  - Response for request with id:request:2 has status code:202
DEBUG   2019-11-14 11:46:50,203 [pool-2-thread-6] com.microsoft.azure.servicebus.primitives.RequestResponseLink  - Completing request with id:request:2
DEBUG   2019-11-14 11:46:50,203 [pool-2-thread-7] com.microsoft.azure.servicebus.primitives.CommonRequestResponseOperations  - CBS Token of type 'servicebus.windows.net:sastoken' sent to 'amqp://servicebus-sdk-tests.servicebus.windows.net/demoinboxqueue'
DEBUG   2019-11-14 11:46:50,204 [pool-2-thread-6] com.microsoft.azure.servicebus.primitives.MessagingFactory  - Sent CBS token for amqp://servicebus-sdk-tests.servicebus.windows.net/demoinboxqueue and setting renew timer
INFO    2019-11-14 11:46:50,204 [ReactorThreadee44f1ee-57b8-4913-aeb3-5ffd9fc09bf9] com.microsoft.azure.servicebus.primitives.CoreMessageReceiver  - Creating receive link to 'demoinboxqueue'
DEBUG   2019-11-14 11:46:50,205 [ReactorThreadee44f1ee-57b8-4913-aeb3-5ffd9fc09bf9] com.microsoft.azure.servicebus.primitives.CoreMessageReceiver  - Receive link settle mode 'sender settle mode: UNSETTLED, receiver settle mode: SECOND'
DEBUG   2019-11-14 11:46:50,206 [ReactorThreadee44f1ee-57b8-4913-aeb3-5ffd9fc09bf9] com.microsoft.azure.servicebus.amqp.ReceiveLinkHandler  - onLinkLocalOpen: linkName:Receiver_292662_2a24d7c31cea451a8e01bc6a1fc74625_G24, localSource:Source{address='demoinboxqueue', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, distributionMode=null, filter=null, defaultOutcome=null, outcomes=null, capabilities=null}
DEBUG   2019-11-14 11:46:50,276 [ReactorThreadee44f1ee-57b8-4913-aeb3-5ffd9fc09bf9] com.microsoft.azure.servicebus.amqp.SessionHandler  - onSessionRemoteOpen - entityName: demoinboxqueue, sessionIncCapacity: 2147483647, sessionOutgoingWindow: 2147483647
DEBUG   2019-11-14 11:46:50,278 [ReactorThreadee44f1ee-57b8-4913-aeb3-5ffd9fc09bf9] com.microsoft.azure.servicebus.amqp.ReceiveLinkHandler  - onLinkRemoteOpen: linkName:Receiver_292662_2a24d7c31cea451a8e01bc6a1fc74625_G24, remoteSource:Source{address='demoinboxqueue', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, distributionMode=null, filter=null, defaultOutcome=null, outcomes=null, capabilities=null}
INFO    2019-11-14 11:46:50,278 [ReactorThreadee44f1ee-57b8-4913-aeb3-5ffd9fc09bf9] com.microsoft.azure.servicebus.primitives.CoreMessageReceiver  - Receive link to 'demoinboxqueue' opened.
DEBUG   2019-11-14 11:46:50,278 [ReactorThreadee44f1ee-57b8-4913-aeb3-5ffd9fc09bf9] com.microsoft.azure.servicebus.primitives.CoreMessageReceiver  - receiverPath:demoinboxqueue, linkname:Receiver_292662_2a24d7c31cea451a8e01bc6a1fc74625_G24, updated-link-credit:0, sentCredits:0

**Comment by yvgopal** [comment] 2019-11-14 22:49
It is not a bug. I ran the test myself. The issue is with the message handler options you passed in.

`new MessageHandlerOptions(5,
                    true,
                    Duration.ofMinutes(5L),
                    Duration.ofMinutes(60)
                )`

The last parameter says wait for one hour before a receive request is timed out. When a link is closed and reopened, already waiting receive requests are let to time out and new receive requests will send more credits to receive messages. (You can argue why it is doing like that, but that is a different issue). In your case, all 5 concurrent receive calls will timeout after 1 hour and then they will fire receive requests again. So after 1 hour, your application will start receiving messages again.

If you don't pass in any argument for that parameter, it will default to 1 minute. You can try your reproduction example with different wait times and see the difference for yourself.

I am closing it. Reopen the issue if you disagree.

**Closed by yvgopal** 2019-11-14 22:49 UTC
Labels: Client, Service Attention, Service Bus, customer-reported
