### ISSUE TITLE
Clean up Javadoc Comments in Storage Blobs

### ISSUE THREAD

**Issue by gapra-msft** [Azure/azure-sdk-for-java#5780] opened 2019-10-11 16:59 UTC
The Javadoc comments for Storage Blobs  do not seem to correspond with the SDK. For example, 
in BlobContainerAsynClient getBlobAsyncClient(String) it says, but it should refer to the builder.

```
/**
 * Creates a new BlobAsyncClient object by concatenating blobName to the end of ContainerAsyncClient's URL. The new
 * BlobAsyncClient uses the same request policy pipeline as the ContainerAsyncClient. To change the pipeline, create
 * the BlobAsyncClient and then call its WithPipeline method passing in the desired pipeline object. Or, call this
 * package's getBlobAsyncClient instead of calling this object's getBlobAsyncClient method.
 *
 * <p><strong>Code Samples</strong></p>
 *
 * {@codesnippet com.azure.storage.blob.BlobContainerAsyncClient.getBlobAsyncClient#String}
 *
 * @param blobName A {@code String} representing the name of the blob.
 * @return A new {@link BlobAsyncClient} object which references the blob with the specified name in this container.
 */
```

**Comment by rickle-msft** [comment] 2019-11-11 23:36
Duplicate of #4047. I will copy this case over to ensure it doesn't get lost.

**Closed by rickle-msft** 2019-11-11 23:36 UTC
Labels: Client, Storage
