### ISSUE TITLE
Spring Azure funcction Timer trigger is not working

### ISSUE THREAD

**Issue by debinaik** [Azure/azure-sdk-for-java#16355] opened 2020-10-15 05:17 UTC
Spring azure function for timer trigger is not working. I have reported the issue in Vmware support ,but they have asked us to contact azure as it's third party library not supported by Vmware officially.  Below is the reply from Spring-Vmware team.

Hence please help on the 

Reply from VMWARE
----------------------

Hi DebiPrasad,
 
From the sample app I see you are using Microsoft's library
 
import com.microsoft.azure.functions.annotation.HttpTrigger;
import com.microsoft.azure.functions.annotation.TimerTrigger;
This is considered third party libraries and we don't officially support it. For official list of Spring projects that we support please see:
 
https://tanzu.vmware.com/spring-runtime
 
Scroll at the bottom until you reach section "VMware Spring Runtime also comes with support services for these Spring projects"
 
Spring Cloud Azure is not on the list. I would suggest reaching out to Azure's community 
 
https://github.com/Azure/azure-sdk-for-java
 
This might be of help. You might want to put package com.microsoft.azure logging on debug mode on logging to give more info
 
https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-java?tabs=consumption#view-logs-and-trace
 
Regards,
Lou-ann

**Comment by joshfree** [comment] 2020-10-19 19:10
Hi @debinaik can you please provide the repro code and possibly the logging details, as Lou-ann mentioned above?

**Comment by debinaik** [comment] 2020-10-21 05:09
Hi @Joshfree 
Below is the source code reference of *HTTPTrigger* . There is no sample available for *TimerTrigger*. 
https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/getting-started-with-spring-cloud-function-in-azure

**Comment by debinaik** [comment] 2020-10-21 05:29
Cont...
Also I have added below sample code piece for TimerTrigger where it can't invoke Spring function. Please extract the code and test it directly on your system to reproduce the issue quickly.

[hello-spring-function-azure-timer-http-9-30-2020.zip](https://github.com/Azure/azure-sdk-for-java/files/5413458/hello-spring-function-azure-timer-http-9-30-2020.zip)

**Comment by lzc-1997-abel** [comment] 2020-10-22 09:13
Hi @joshfree 
These libraries do not belong to azure-sdk-for-java, but 
https://github.com/Azure/azure-functions-java-library. 
It might be more helpful to assign to them.

**Comment by debinaik** [comment] 2020-11-10 07:17
@joshfree and @lzc-1997-abel : Request your update please

**Comment by lzc-1997-abel** [comment] 2020-11-11 05:18
Hi @debinaik 
From the example application, I did not see the use of our library.

import com.microsoft.azure.functions.annotation.HttpTrigger;
import com.microsoft.azure.functions.annotation.TimerTrigger;
Both libraries are in this repository : https://github.com/Azure/azure-functions-java-library

I would suggest reaching out to this community
https://github.com/Azure/azure-functions-java-library.
This might be of help.

**Comment by chenrujun** [comment] 2020-11-18 00:48
Closing this issue, because the problem is not related to this repo.

**Closed by chenrujun** 2020-11-18 00:48 UTC
Labels: azure-spring, customer-reported, customer-response-expected, question
