### ISSUE TITLE
[FEATURE REQ] Keep BOM up to date

### ISSUE THREAD

**Issue by hochas** [Azure/azure-sdk-for-java#7762] opened 2020-01-28 14:40 UTC
**Is your feature request related to a problem? Please describe.**
Using the same version for key vault SDKs causes mismatch of core dependencies. I just spent an hour tracking this down. An updated BOM would have saved some headache.

The following will not work:

```
implementation "com.azure:azure-security-keyvault-certificates:4.0.0"
implementation "com.azure:azure-security-keyvault-secrets:4.0.0"
```
`azure-security-keyvault-certificates` pulls in `azure-core:1.2.0`, overriding `azure-security-keyvault-secrets` need for version `1.0.0` of the same lib. A crucial class `RestProxy` has moved from package `com.azure.core.implementation`  in version 1.0.0 to package `com.azure.core.http.rest` in 1.2.0, effectively making the the same version of an SDK break each other.

[The only BOM I can find is managed by Visual Studio China and it is incomplete.](https://github.com/VSChina/azure-dependencies-bom) Is this an official BOM?

It is missing, at least what I've noticed so far:
 * azure-security-keyvault-certificates
 * azure-security-keyvault-keys

**Describe the solution you'd like**
A centrally managed BOM aligning the use of libraries that work together.

**Comment by JonathanGiles** [comment] 2020-01-28 19:29
We are planning a new BOM for our 'next generation' client libraries, which will be coming in the next few months. You can track progress here: https://github.com/Azure/azure-sdk-for-java/issues/7280

I'll close this issue as a duplicate of #7280

**Closed by JonathanGiles** 2020-01-28 19:29 UTC
Labels: triage
