### ISSUE TITLE
LoadBalancer.update().withoutxxx(name).apply() not working

### ISSUE THREAD

**Issue by amit-dali** [Azure/azure-sdk-for-java#1456] opened 2017-02-13 09:46 UTC
Issue: LoadBalancer.update().withoutxxx(name).apply() is not removing Backend, Probe as well as LoadBalancingRule.

API's -
1)  <Lb object>.update().withoutProbe("name here").apply();
2)   <Lb object>.update().withoutProbe("name here").apply();
3)   <Lb object>.update().withoutBackend("name here").apply();

Observation: I executed above API's in December 2016,  at that time these API's worked, But now API is not removing required resource/configuration.

**Comment by martinsawicki** [comment] 2017-02-14 17:00
@amit-dali which versions of the SDK libraries were you using before and now?

**Comment by martinsawicki** [comment] 2017-02-14 19:25
This problem should repro only when the last child of a given type is deleted from the Load Balancer. If there is at least one child of a given type left after the deletion, it will work ok.

The root cause appears to be that the LB API on the networking service side has changed its behavior in breaking (and incorrect) ways between the previous API version supported by the SDK and the latest one we switched to in beta 4.1 -- it's treating null on the list of LB children as "no change". It should treat null as "no children", as it used to, and as it does in other networking services, and overall as required by ARM guidelines. So this issue should really be addressed on the service REST API side in Azure.

In the meantime, a workaround is being checked into master (https://github.com/Azure/azure-sdk-for-java/pull/1460/commits/1627af1538c9c032c38c2b0c349c6bdebdbdc8b3).

**Comment by amit-dali** [comment] 2017-02-22 09:18
Which java sdk version has this fix?

**Comment by martinsawicki** [comment] 2017-02-22 16:56
the fix is in master, so the next released version will have it.

**Comment by martinsawicki** [comment] 2017-04-26 00:27
fixed in v1.0.0

**Closed by martinsawicki** 2017-04-26 00:27 UTC
