### ISSUE TITLE
Azure Vault Access Via Standalone Java/Scala. 

### ISSUE THREAD

**Issue by dasari2828** [Azure/azure-sdk-for-java#22569] opened 2021-06-25 12:59 UTC
**Query/Question**
Unable to get access to Vault via Java/Scala API

***Why is this not a Bug or a feature Request?***
Suspecting this is a Maven Dependency Issue. Spoke with Microsoft support and they encouraged to create a GitHub issue here.

**Setup (please complete the following information if applicable):**
 - OS: iOS
 - IDE:  IntelliJ
 - Library/Libraries: 
 - libraryDependencies += "com.azure" % "azure-identity" % "1.3.1"
libraryDependencies += "com.azure" % "azure-security-keyvault-keys" % "4.3.0"
libraryDependencies += "com.azure" % "azure-security-keyvault-secrets" % "4.3.0"

Code:-
```scala
object BlobRead {
  def main(args: Array[String]): Unit = {

    val client_id = ""
    val client_secret = ""
    val tenant_id = ""

//    val keyVaultName = "blob-access"
//    val keyVaultUri = "https://" + keyVaultName + ".vault.azure.net"
    val keyVaultUri = "https://blob-access.vault.azure.net"

    try {

      val clientSecretCredential = new ClientSecretCredentialBuilder()
        .clientId(client_id)
        .clientSecret(client_secret)
        .tenantId(tenant_id)
        .build

      val secretClient = new SecretClientBuilder()
        .vaultUrl(keyVaultUri)
        .credential(clientSecretCredential)
        .buildClient

      val secret = secretClient.getSecret("storageKey")
      System.out.println(secret.getValue)

    } catch {
      case e: Exception => e.printStackTrace()
    }


  }
} 
```

Error:-
```java
15:25:05.566 [main] DEBUG reactor.util.Loggers - Using Slf4j logging framework
java.lang.IllegalStateException: A request was made to load the default HttpClient provider but one could not be found on the classpath. If you are using a dependency manager, consider including a dependency on azure-core-http-netty or azure-core-http-okhttp. Depending on your existing dependencies, you have the choice of Netty or OkHttp implementations. Additionally, refer to https://aka.ms/azsdk/java/docs/custom-httpclient to learn about writing your own implementation.
        at com.azure.core.implementation.http.HttpClientProviders.createInstance(HttpClientProviders.java:51)
        at com.azure.core.http.HttpClient.createDefault(HttpClient.java:50)
        at com.azure.core.http.HttpClient.createDefault(HttpClient.java:40)
        at com.azure.core.http.HttpPipelineBuilder.build(HttpPipelineBuilder.java:62)
        at com.azure.security.keyvault.secrets.SecretClientBuilder.buildAsyncClient(SecretClientBuilder.java:190)
        at com.azure.security.keyvault.secrets.SecretClientBuilder.buildClient(SecretClientBuilder.java:112)
        at com.iqvia.polaris.janus.misc.BlobRead$.main(BlobRead.scala:32)
        at com.iqvia.polaris.janus.misc.BlobRead.main(BlobRead.scala)
 ```

Java:-
pom.xml
```xml
        <dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-azure</artifactId>
            <version>3.2.2</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/com.microsoft.azure/azure-storage -->
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-storage</artifactId>
            <version>8.6.5</version>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-security-keyvault-secrets</artifactId>
            <version>4.2.3</version>
        </dependency>

        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-identity</artifactId>
            <version>1.2.0</version>
        </dependency>

        <dependency>
            <groupId>com.nimbusds</groupId>
            <artifactId>oauth2-oidc-sdk</artifactId>
            <version>7.4</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>2.5.1</version>
        </dependency>
```
```java
//import com.azure.identity.ClientSecretCredential;
//import com.azure.identity.ClientSecretCredentialBuilder;
import com.azure.identity.ClientSecretCredential;
import com.azure.identity.ClientSecretCredentialBuilder;
import org.apache.spark.sql.Dataset;
import org.apache.spark.sql.Row;
import org.apache.spark.sql.SparkSession;
import com.azure.identity.DefaultAzureCredentialBuilder;
import com.azure.security.keyvault.secrets.SecretClient;
import com.azure.security.keyvault.secrets.SecretClientBuilder;
import com.azure.security.keyvault.secrets.models.KeyVaultSecret;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class AzureBlobReadTest {

    public static void main(String[] args) {
        String storage_account_name = "polarisgraph";


        String keyVaultName = "blob-access";
        String keyVaultUri = "https://" + keyVaultName + ".vault.azure.net";

        //ExecutorService executorService = Executors.newCachedThreadPool();
        try{
            ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
                    .clientId("")
                    .clientSecret("")
                    .tenantId("")
                    //.executorService(executorService)
                    .build();
            SecretClient secretClient = new SecretClientBuilder().vaultUrl(keyVaultUri)
                    .credential(clientSecretCredential).buildClient();
            KeyVaultSecret retrievedSecret = secretClient.getSecret("storageKey");

//            final SecretClient secretClient = new SecretClientBuilder()
//                    .vaultUrl(keyVaultUri)
//                    .credential(new DefaultAzureCredentialBuilder().build())
//                    .buildClient();

//            KeyVaultSecret secret = secretClient.getSecret("storageKey");
            System.out.println(retrievedSecret.getValue());

        }catch(Exception ex){
            ex.printStackTrace();
        }finally{
            //executorService.shutdown();
        }
```

```java
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ser/std/ToStringSerializerBase
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at com.azure.core.util.serializer.JacksonAdapter.initializeObjectMapper(JacksonAdapter.java:289)
	at com.azure.core.util.serializer.JacksonAdapter.<init>(JacksonAdapter.java:74)
	at com.azure.core.util.serializer.JacksonAdapter.createDefaultSerializerAdapter(JacksonAdapter.java:112)
	at com.azure.identity.implementation.IdentityClient.<clinit>(IdentityClient.java:94)
	at com.azure.identity.implementation.IdentityClientBuilder.build(IdentityClientBuilder.java:113)
	at com.azure.identity.ClientSecretCredential.<init>(ClientSecretCredential.java:50)
	at com.azure.identity.ClientSecretCredentialBuilder.build(ClientSecretCredentialBuilder.java:62)
	at com.iqvia.janus.spark.AzureBlobReadTest.main(AzureBlobReadTest.java:34)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ser.std.ToStringSerializerBase
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 20 more
```

Java tried to keep resolving several dependencies issue, it seems cyclic or not able to find the right jar to use.
Scala also has http client issues.

Please let me know what is the best way to do this.
We were able to run this in python successfully with similar code. FYI.

**Comment by alzimmermsft** [comment] 2021-06-25 16:16
Thanks for submitting this issue @dasari2828.

For `Standalone Java/Scala` do you mean an application which injects JARs into the classpath? If that is the case, for the first question you'll need to include either `azure-core-http-netty` or `azure-core-http-okttp`, or a JAR containing your own implementation of our `HttpClient` SPI.

For the second issue it appears that the `hadoop-azure` dependency being used is providing `jackson-databind:2.9.10.4`. The missing `ToStringSerializerBase` class was added in `jackson-databind:2.10`, there appears to be a newer `hadoop-azure` version which uses a version of `jackson-databind` above `2.10`.

cc: @vcolin7 @jianghaolu

**Comment by srinivasseshu** [comment] 2021-06-28 23:57
We've updated our build.sbt as follows, and yet we run in to the same error:

`libraryDependencies += "org.apache.spark" %% "spark-core" % "2.4.5" % "provided"
libraryDependencies += "org.apache.spark" %% "spark-sql" % "2.4.5" % "provided"
libraryDependencies += "org.janusgraph" % "janusgraph-core" % "0.3.0"
libraryDependencies += "org.janusgraph" % "janusgraph-cql" % "0.5.3"
libraryDependencies += "org.apache.tinkerpop" % "gremlin-driver" % "3.3.3"

libraryDependencies += "com.azure" % "azure-identity" % "1.3.1"
libraryDependencies += "com.azure" % "azure-security-keyvault-keys" % "4.3.0"
libraryDependencies += "com.azure" % "azure-security-keyvault-secrets" % "4.3.0"
libraryDependencies += "com.azure" % "azure-core-http-okhttp" % "1.3.3"

assemblyOption in assembly := (assemblyOption in assembly).value.copy(includeScala = false)
assemblyShadeRules in assembly := Seq(
  ShadeRule.rename("com.google.**" -> "shaded.com.google.@1").inAll,
  ShadeRule.rename("io.netty.**" -> "shaded.io.netty.@1").inAll
)

assemblyMergeStrategy in assembly := {
  case PathList("META-INF", xs @ _*) => MergeStrategy.discard
  case x => MergeStrategy.first
}
`


Error:

`15:25:05.566 [main] DEBUG reactor.util.Loggers - Using Slf4j logging framework
java.lang.IllegalStateException: A request was made to load the default HttpClient provider but one could not be found on the classpath. If you are using a dependency manager, consider including a dependency on azure-core-http-netty or azure-core-http-okhttp. Depending on your existing dependencies, you have the choice of Netty or OkHttp implementations. Additionally, refer to https://aka.ms/azsdk/java/docs/custom-httpclient to learn about writing your own implementation.
        at com.azure.core.implementation.http.HttpClientProviders.createInstance(HttpClientProviders.java:51)
        at com.azure.core.http.HttpClient.createDefault(HttpClient.java:50)
        at com.azure.core.http.HttpClient.createDefault(HttpClient.java:40)
        at com.azure.core.http.HttpPipelineBuilder.build(HttpPipelineBuilder.java:62)
        at com.azure.security.keyvault.secrets.SecretClientBuilder.buildAsyncClient(SecretClientBuilder.java:190)
        at com.azure.security.keyvault.secrets.SecretClientBuilder.buildClient(SecretClientBuilder.java:112)
        at com.iqvia.polaris.janus.misc.BlobRead$.main(BlobRead.scala:32)
        at com.iqvia.polaris.janus.misc.BlobRead.main(BlobRead.scala)
`

**Comment by vcolin7** [comment] 2021-06-29 21:56
I'm not a Scala expert so this question comes from a place of curiosity for the most part: What's the difference in setting a dependency on the POM and on the `build.sbt` file? Is there a particular reason you didn't add the `com.azure:azure-core-http-okhttp:1.3.3` dependency in the former?

Also, I see you didn't mention the Jackson issue again, did updating to a newer version of `jackson-databind` (`2.10+`) like @alzimmermsft suggested solve that problem?

**Comment by alzimmermsft** [comment] 2021-06-29 23:28
Hi @srinivasseshu, thank you for the `build.sbt`, after reviewing this further, and familiarizing myself with Scala more, it looks like the issue is around this:

```
assemblyMergeStrategy in assembly := {
  case PathList("META-INF", xs @ _*) => MergeStrategy.discard
  case x => MergeStrategy.first
}
```

From my understanding, and please feel free to correct me, this is excluding all files contained in `META-INF` folders. This is creating the problem you are seeing as the KeyVault SDK, as well as most other Azure SDKs, use `ServiceProvider` functionality to load classpath based implementations of `HttpClient`, and this uses information contained in `META-INF` to determine the implementations.

If you need to continue excluding all `META-INF` files you'll need to configure the `HttpClient` instance to use directly in the client/service builders, an updated example using the Scala codesnippet originally posted would be:

```scala
object BlobRead {
  def main(args: Array[String]): Unit = {

    val client_id = Configuration.getGlobalConfiguration.get(Configuration.PROPERTY_AZURE_CLIENT_ID)
    val client_secret = Configuration.getGlobalConfiguration.get(Configuration.PROPERTY_AZURE_CLIENT_SECRET)
    val tenant_id = Configuration.getGlobalConfiguration.get(Configuration.PROPERTY_AZURE_TENANT_ID)
    val keyVaultUri = "<keyVaultUri>"
    val okHttpHttpClient = new OkHttpAsyncHttpClientBuilder().build()

        try {
          val clientSecretCredential = new ClientSecretCredentialBuilder()
            .clientId(client_id)
            .clientSecret(client_secret)
            .tenantId(tenant_id)
            .httpClient(okHttpHttpClient)
            .build

          val secretClient = new SecretClientBuilder()
            .vaultUrl(keyVaultUri)
            .credential(clientSecretCredential)
            .httpClient(okHttpHttpClient)
            .buildClient

          val secret = secretClient.getSecret("storageKey")
          System.out.println(secret.getValue)

        } catch {
          case e: Exception => e.printStackTrace()
        }
  }
}
```

**Comment by alzimmermsft** [comment] 2021-07-13 18:29
As a follow-up to the above, I've dug further into resolving the missing `META-INF` data in the uber JAR produced by the `assembly` job and it was indeed and issue with the `assemblyMergeStrategy`. Using SBT 0.15.5 I created the following `build.sbt` which maintains the necessary `META-INF` files to support using `ServiceLoader` functionality in Azure SDKs and other Java libraries:

```sbt
import sbtassembly.MergeStrategy

val defaultMergeStrategy: String => MergeStrategy = {
  case x if Assembly.isConfigFile(x) =>
    MergeStrategy.concat
  case PathList(ps @ _*) if Assembly.isReadme(ps.last) || Assembly.isLicenseFile(ps.last) =>
    MergeStrategy.rename
  case PathList("META-INF", xs @ _*) =>
    xs map {_.toLowerCase} match {
      case "manifest.mf" :: Nil | "index.list" :: Nil | "dependencies" :: Nil =>
        MergeStrategy.discard
      case ps @ _ :: _ if ps.last.endsWith(".sf") || ps.last.endsWith(".dsa") || ps.last.endsWith("rsa") =>
        MergeStrategy.discard
      case "plexus" :: _ =>
        MergeStrategy.discard
      case "services" :: _ =>
        MergeStrategy.filterDistinctLines
      case "spring.schemas" :: Nil | "spring.handlers" :: Nil =>
        MergeStrategy.filterDistinctLines
      case _ => MergeStrategy.last
    }
  case _ => MergeStrategy.last
}

lazy val settings = (project in file("."))
  .settings(
    name := "ScalaServiceProvider",
    version := "0.0.1",
    scalaVersion := "2.12.14",
    libraryDependencies ++= Seq(
      "org.apache.spark" %% "spark-core" % "2.4.5" % "provided",
      "org.apache.spark" %% "spark-sql" % "2.4.5" % "provided",
      "org.janusgraph" % "janusgraph-core" % "0.3.0",
      "org.janusgraph" % "janusgraph-cql" % "0.5.3",
      "org.apache.tinkerpop" % "gremlin-driver" % "3.3.3",
      "com.azure" % "azure-identity" % "1.3.1" exclude ("com.azure", "azure-core-http-netty"),
      "com.azure" % "azure-security-keyvault-keys" % "4.3.0" exclude ("com.azure", "azure-core-http-netty"),
      "com.azure" % "azure-security-keyvault-secrets" % "4.3.0" exclude ("com.azure", "azure-core-http-netty"),
      "com.azure" % "azure-core-http-okhttp" % "1.7.0"
    ),
    assembly / assemblyOption := (assembly / assemblyOption).value.withIncludeScala(includeScala = false),
    assembly / assemblyShadeRules := Seq(
      ShadeRule.rename("com.google.**" -> "shaded.com.google.@1").inAll,
      ShadeRule.rename("io.netty.**" -> "shaded.io.netty.@1").inAll
    ),
    assembly / assemblyMergeStrategy := defaultMergeStrategy
  )
```

For further information about the merge strategy, I used this documentation as a guide: https://github.com/sbt/sbt-assembly#merge-strategy

**Closed** 2021-07-20 22:01 UTC
Labels: Azure.Core, Azure.Identity, Client, KeyVault, customer-reported, issue-addressed, question
