### ISSUE TITLE
Leaked connection warning after rate limit error

### ISSUE THREAD

**Issue by ilooner** [Azure/azure-sdk-for-java#2790] opened 2018-12-14 03:12 UTC
After hitting a rate limit error, I start seeing a leaked connection error. The two errors are included below. The rate limit error is understandable since it is documented behavior, but the connection should not be leaked when hitting the rate limit.

## Azure sdk versions

```
    <dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>azure</artifactId>
      <version>1.16.0</version>
    </dependency>
    <dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>azure-mgmt-resources</artifactId>
      <version>1.16.0</version>
    </dependency>
```

## Rate limit error

```
Dec 14, 2018 2:44:53 AM okhttp3.internal.platform.Platform log
WARNING: A connection to https://management.azure.com/ was leaked. Did you forget to close a response body?
java.lang.Throwable: response.body().close()
	at okhttp3.internal.platform.Platform.getStackTraceForCloseable(Platform.java:148)
	at okhttp3.RealCall.captureCallStackTrace(RealCall.java:89)
	at okhttp3.RealCall.execute(RealCall.java:73)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:40)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10423)
	at rx.Observable.subscribe(Observable.java:10390)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:443)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.containerservice.implementation.ManagedClustersInner.getAccessProfile(ManagedClustersInner.java:462)
	at com.microsoft.azure.management.containerservice.implementation.KubernetesClustersImpl.getAdminKubeConfigContent(KubernetesClustersImpl.java:160)
```

## Connection leak error

```
Dec 14, 2018 2:44:53 AM okhttp3.internal.platform.Platform log
WARNING: A connection to https://management.azure.com/ was leaked. Did you forget to close a response body?
java.lang.Throwable: response.body().close()
	at okhttp3.internal.platform.Platform.getStackTraceForCloseable(Platform.java:148)
	at okhttp3.RealCall.captureCallStackTrace(RealCall.java:89)
	at okhttp3.RealCall.execute(RealCall.java:73)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:40)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10423)
	at rx.Observable.subscribe(Observable.java:10390)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:443)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.containerservice.implementation.ManagedClustersInner.getAccessProfile(ManagedClustersInner.java:462)
	at com.microsoft.azure.management.containerservice.implementation.KubernetesClustersImpl.getAdminKubeConfigContent(KubernetesClustersImpl.java:160)
```

**Comment by praries880** [comment] 2019-03-06 01:01
@anuchandy can you kindly take a look at this issue and see if you can reproduce it?

**Comment by bendeitch** [comment] 2019-04-09 07:22
I am also seeing this behaviour. I am using SDK version 1.20.1

**Comment by anuchandy** [comment] 2019-04-16 15:03
Related https://github.com/Azure/azure-sdk-for-java/issues/608

**Comment by anuchandy** [comment] 2019-04-17 14:14
@bendeitch, @ilooner thanks for reporting this issue. 

I see a place where we miss to close the response stream. We've a [retry interceptor](https://github.com/Azure/azure-libraries-for-java/blob/631ecd1cd45660b6a81b7d0dabdb6d196351c126/azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/utils/ResourceManagerThrottlingInterceptor.java#L72) to handle rate limit error, where we wait and retry upon receiving rate error (429). It looks like as part of handling 429, we're not closing the response stream.

We'll discuss this today within the team and come up with a plan to release the fix.

@ilooner Thanks again for exactly pin pointing that this happens during 429, it really helped the investigation.

**Comment by anuchandy** [comment] 2019-04-18 16:03
PR opened https://github.com/Azure/azure-libraries-for-java/pull/728

**Comment by lmazuel** [comment] 2019-04-29 18:05
Made it in 1.22

**Closed by lmazuel** 2019-04-29 18:05 UTC
Labels: Container Instance, Investigate, Mgmt
