### ISSUE TITLE
Monthly Patch release is blocked by no-changes API View tool

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk-for-java#21408] opened 2021-05-13 23:10 UTC
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=891850&view=logs&j=02b43782-5767-5741-285b-4998932e1f31&t=bda7a324-d94a-5283-7ca7-f378c2611161

EngSys discussion: https://teams.microsoft.com/l/message/19:59dbfadafb5e41c4890e2cd3d74cc7ba@thread.skype/1620854138743?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1620854138743&teamName=Azure%20SDK&channelName=Engineering%20System%20%F0%9F%9B%A0%EF%B8%8F&createdTime=1620854138743

Currently, Java monthly patch release process is blocked. It could be caused by APIView or EngSys bugs.  There is no API change between months, April and May.

**Comment by hemanttanwar** [comment] 2021-05-26 19:46
This pipeline was also blocked , it was created from a "feature" branch But there was no change in API but CI still complained about it.

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=913078&view=logs&j=9d510ff3-53a8-5192-bd2d-466ce830bc13&t=218eead3-a49b-5d68-15bf-c5ac80bc57d4&s=ddaaefcb-0011-5d5e-c1b5-66d7d425c046

**Comment by YijunXieMS** [comment] 2021-05-26 20:58
I got the same error for azure-core-amqp release and servicebus from feature branch.

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=913078&view=logs&j=9d510ff3-53a8-5192-bd2d-466ce830bc13&t=218eead3-a49b-5d68-15bf-c5ac80bc57d4&s=ddaaefcb-0011-5d5e-c1b5-66d7d425c046

and

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=913088&view=logs&j=9d510ff3-53a8-5192-bd2d-466ce830bc13&t=6487c6b0-1fc1-53e6-490a-681cc0192a2c&s=ff05ad62-bb9a-53b6-ce9f-72f329a63e7c

**Comment by kurtzeborn** [comment] 2021-06-21 20:46
https://github.com/Azure/azure-sdk-tools/issues/1547 appears to be a symptom/duplicate of this.

**Comment by praveenkuttappan** [comment] 2021-08-17 17:47
We have API status check against all approved revisions as opposed to latest revision only and this change should resolve issues during hotfix releases from feature branch.

**Closed** 2021-08-17 17:47 UTC
Labels: EngSys, Central-EngSys
