### ISSUE TITLE
[BUG] copyFromUrlWithResponse fails with 404 CannotVerifyCopySource if blob name contains %20

### ISSUE THREAD

**Issue by daolis** [Azure/azure-sdk-for-java#11204] opened 2020-05-15 06:28 UTC
**Scanario**

- Copying Container of **Blobstore A** to Container of **Blobstore B**.
- A Blob exists with the name `my%20testfile.txt`. You see this name in the AzurePortal (Its not the URL Encoded name)

**Application functionality**:

1. Get list of all Blobs from **Blobstore A**
1. Create a BlockBlobClient with the name from the source blob (containerClient.getBlobClient(name) 
1. Add a SASToken to the BlobURL
1. Trigger server side copy process to create Blob in **Blobstore B** with URL from source blob

Example:
1. Get blob with name `my%20testfile.txt` 
1. Create BlockBlobClient: \
URL is e.g. `https://xyz.blob.core.windows.net/container/my testfile.txt` (URL Encoding)
1. Add SAS Token
1. Trigger server side copy: -> **404, because it tries to copy the file `my testfile.txt`**

***Error***
**Exception**: com.azure.storage.blob.models.BlobStorageException: Status code 404
**Errorcode**: CannotVerifyCopySource
**Message**: The specified blob does not exist.

**Reproduce**
- Create a blob with `%20` in its name.
- Create a BlockBlobClient with this name
- Optional: Add a SAS Token if not public readable
- Trigger Copy Process with: `targeBlockBlobClient.copyFromUrlWithResponse(...)`

**Expected behavior**
Successful copy of the file

**Workaround**
.. for now is to replace the character `%` with `%20`.
1.  `my%20testfile.txt` to  `my%2020testfile.txt`
1. URL of BlockBlobClient: `https://xyz.blob.core.windows.net/container/my%20testfile.txt`
1. Copy successful

**Comment by alzimmermsft** [comment] 2020-05-15 16:45
@gapra-msft @rickle-msft I have a suspicion that this is related to #11183

**Comment by rickle-msft** [comment] 2020-05-15 17:13
@daolis Thank you for reporting this.

@alzimmermsft I suspsect you are right about the connection. @gapra-msft Can you be sure to test this case for blobs while you're working on files?

**Comment by gapra-msft** [comment] 2020-06-01 19:48
Hi @daolis 

I'm having a little trouble reproducing the issue you are seeing based off the steps you provided. Could you please provide a code sample so I can further investigate?

**Comment by daolis** [comment] 2020-06-02 06:51
Hi @gapra-msft 
I created a repo reproducing this issue.
https://github.com/daolis/azureBlobCopy404Example

**Comment by gapra-msft** [comment] 2020-06-02 22:12
Hi @daolis, Thank you for your repro code. 

I believe the issue is that when you call **listBlobs**, it returns the raw, not encoded blob name. However, the **getBlobClient** method expects a url encoded blob name (especially when the blob name could possibly look url encoded).

Our recommendation is for you to first url encode the blob name before you pass it in the getBlobClient method. We have a utility method that does just that if you'd like to use it. - Utility.urlEncode

Please let me know if you have further questions/concerns.

**Comment by rickle-msft** [comment] 2020-06-23 17:56
I am going to close this issue as we have given a recommendation on how to appropriately resolve the problem and there has been no follow up.

Please feel free to reach back out to us if you need further support.

**Closed by rickle-msft** 2020-06-23 17:56 UTC
Labels: Storage, customer-reported, question
