### ISSUE TITLE
[BUG] App Configuration doesn't work in Azure Function

### ISSUE THREAD

**Issue by mrm9084** [Azure/azure-sdk-for-java#8392] opened 2020-02-21 22:17 UTC
**Describe the bug**
When attempting to create an Azure Function a dependency conflict with netty results in an NoSuchMethodError. I have attempted a shared jar to resolve the issue, but it doesn't help.

***Exception or Stack Trace***
```console
[2/21/2020 9:42:14 PM] Executed 'Functions.hello' (Failed, Id=24c8735c-df65-45ea-a857-8ac83005b7fa)
[2/21/2020 9:42:14 PM] System.Private.CoreLib: Exception while executing function: Functions.hello. System.Private.CoreLib: Result: Failure
Exception: NoSuchMethodError: io.netty.handler.ssl.SslProvider.isAlpnSupported(Lio/netty/handler/ssl/SslProvider;)Z
Stack: java.lang.reflect.InvocationTargetException
[2/21/2020 9:42:14 PM]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2/21/2020 9:42:14 PM]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2/21/2020 9:42:14 PM]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2/21/2020 9:42:14 PM]  at java.lang.reflect.Method.invoke(Method.java:498)
[2/21/2020 9:42:14 PM]  at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
[2/21/2020 9:42:14 PM]  at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:54)
[2/21/2020 9:42:14 PM]  at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:53)
[2/21/2020 9:42:14 PM]  at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
[2/21/2020 9:42:14 PM]  at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[2/21/2020 9:42:14 PM]  at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
[2/21/2020 9:42:14 PM]  at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
[2/21/2020 9:42:14 PM]  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2/21/2020 9:42:14 PM]  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2/21/2020 9:42:14 PM]  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2/21/2020 9:42:14 PM]  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2/21/2020 9:42:14 PM]  at java.lang.Thread.run(Thread.java:748)
[2/21/2020 9:42:14 PM] Caused by: java.lang.NoSuchMethodError: io.netty.handler.ssl.SslProvider.isAlpnSupported(Lio/netty/handler/ssl/SslProvider;)Z
[2/21/2020 9:42:14 PM]  at reactor.netty.http.client.HttpClientSecure.<clinit>(HttpClientSecure.java:79)
[2/21/2020 9:42:14 PM]  at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.lambda$subscribe$0(HttpClientConnect.java:297)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.FluxRetryPredicate$RetryPredicateSubscriber.resubscribe(FluxRetryPredicate.java:124)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.MonoRetryPredicate.subscribeOrReturn(MonoRetryPredicate.java:51)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:48)
[2/21/2020 9:42:14 PM]  at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:322)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.MonoTakeLastOne$TakeLastOneSubscriber.onComplete(MonoTakeLastOne.java:112)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:252)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.FluxIterable$IterableSubscription.fastPath(FluxIterable.java:333)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:198)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onSubscribeInner(MonoFlatMapMany.java:143)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onSubscribe(MonoFlatMapMany.java:237)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:139)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:63)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.Flux.subscribe(Flux.java:8134)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:188)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:145)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onComplete(FluxDefaultIfEmpty.java:98)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.FluxJust$WeakScalarSubscription.request(FluxJust.java:101)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.request(FluxDefaultIfEmpty.java:68)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.MonoCollect$CollectSubscriber.onSubscribe(MonoCollect.java:107)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onSubscribe(FluxDefaultIfEmpty.java:82)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.FluxJust.subscribe(FluxJust.java:70)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.Mono.subscribe(Mono.java:4087)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.Mono.block(Mono.java:1662)
[2/21/2020 9:42:14 PM]  at com.azure.data.appconfiguration.ConfigurationClient.getConfigurationSetting(ConfigurationClient.java:206)
[2/21/2020 9:42:14 PM]  at com.azure.data.appconfiguration.ConfigurationClient.getConfigurationSetting(ConfigurationClient.java:179)
[2/21/2020 9:42:14 PM]  at com.microsoft.azure.HelloFunction.lambda$hello$0(HelloFunction.java:38)
[2/21/2020 9:42:14 PM]  at org.springframework.cloud.function.context.catalog.BeanFactoryAwareFunctionRegistry$FunctionInvocationWrapper.invokeFunction(BeanFactoryAwareFunctionRegistry.java:499)
[2/21/2020 9:42:14 PM]  at org.springframework.cloud.function.context.catalog.BeanFactoryAwareFunctionRegistry$FunctionInvocationWrapper.lambda$doApply$1(BeanFactoryAwareFunctionRegistry.java:543)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:107)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.FluxJust$WeakScalarSubscription.request(FluxJust.java:99)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:162)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:162)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.BlockingIterable$SubscriberIterator.onSubscribe(BlockingIterable.java:218)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.FluxJust.subscribe(FluxJust.java:70)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:53)
[2/21/2020 9:42:14 PM]  at reactor.core.publisher.BlockingIterable.iterator(BlockingIterable.java:80)
[2/21/2020 9:42:14 PM]  at org.springframework.cloud.function.context.AbstractSpringFunctionAdapterInitializer.result(AbstractSpringFunctionAdapterInitializer.java:210)
[2/21/2020 9:42:14 PM]  at org.springframework.cloud.function.adapter.azure.AzureSpringBootRequestHandler.handleRequest(AzureSpringBootRequestHandler.java:63)
[2/21/2020 9:42:14 PM]  at com.microsoft.azure.HelloHandler.execute(HelloHandler.java:28)
[2/21/2020 9:42:14 PM]  ... 16 more
```
**To Reproduce**
I am using the hello-spring-function-azure example: https://github.com/Azure-Samples/hello-spring-function-azure

1. I updated HelloFunction to call App Configuration
```java
ConfigurationClientBuilder builder = new ConfigurationClientBuilder();
builder.connectionString(myConnectionString).buildClient();
eturn user -> new Greeting("Welcome, " + client.getConfigurationSetting("/application/config.message", null).getValue());
```
2. Updated dependencies to include 
```xml
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-core</artifactId>
            <version>1.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-data-appconfiguration</artifactId>
            <version>1.0.1</version>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-identity</artifactId>
            <version>1.0.3</version>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-core-http-netty</artifactId>
            <version>1.2.0</version>
        </dependency>
```
***Code Snippet***
See Reproduction.

**Expected behavior**
Being able to connect with App Configuration.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: Windows/Azure Function (Used local maven setup and deploying to an Azure Function)
 - IDE :  Eclipse 2019-12
 - Version of the Library used: See reproduction steps

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by joshfree** [comment] 2020-03-04 18:54
@mssfang @mrm9084 please see https://github.com/Azure/azure-sdk-for-java/wiki/Frequently-Asked-Questions#dependency-conflict for steps on diagnosing and resolving dependency conflicts

**Comment by JarroVGIT** [comment] 2020-05-01 14:40
For what it is worth: I had the same problem. I couldn't make out a dependency issue via `mvn dependency:tree`. 
I was accidently using version 1.1.0-beta3 of com.azure:azure-identity. Changing to version 1.0.5 (latest non-beta) solved this issue for me :)

**Comment by mssfang** [comment] 2020-06-30 20:14
The issue is been take cared of and closed in https://github.com/Azure/azure-functions-java-worker/issues/365

**Closed by mssfang** 2020-06-30 20:14 UTC
Labels: AzConfig, Client, tracking-external-issue
