### ISSUE TITLE
[FEATURE REQ] Allow remote access to ci/pipeline vms 

### ISSUE THREAD

**Issue by rickle-msft** [Azure/azure-sdk-for-java#14134] opened 2020-08-14 18:41 UTC
**Is your feature request related to a problem? Please describe.**
It can be very difficult to maintain live tests in particular when the vms are torn down immediately and we aren't given a way to recreate those environments to reproduce test failures. Often times we are unable to reproduce live test failures locally, so we are left to using print statements to try to capture information and having to wait for several hours between runs to give the pipeline time to hit the test in question. 

**Describe the solution you'd like**
Either for the vms to persist for some amount of time after the pipeline run and a way to access them, or a repository somewhere which contains the images of the vms so we can quickly deploy something identical to use to reproduce the errors in an environment we can work in.

**Comment by kurtzeborn** [comment] 2020-08-20 17:01
The only way we would be able to enable this would be if we hosted our own machines for running pipelines rather than using the DevOps host pools that we currently use.

That said, we could provide containers that we use as our dev environments for builds.  That way everything that happens in the pipelines would be reproducible by individual devs using the same container.  

We do intend to add support for the latter (dev containers) but we're waiting for VS/GitHub Code Spaces to exit private preview and become widely available.

CC: @weshaggard

**Comment by kurtzeborn** [comment] 2020-08-20 17:02
We need to create an epic for this (dev containers) anyway.  I'm going to close this issue since the specific thing being asked for is not the direction we're going in, but I'll link to the new epic as I close it.

**Comment by kurtzeborn** [comment] 2020-08-20 17:09
Closing this issue now that we've got an epic tracking it: https://github.com/Azure/azure-sdk/issues/1714

Great suggestion!  @rickle-msft, I hope you agree with the reasoning and the direction I recorded here.  If you have concerns, please reach out.

**Closed by kurtzeborn** 2020-08-20 17:09 UTC
Labels: EngSys
