### ISSUE TITLE
[FEATURE REQUEST] uploadFromFileWithResponse on ShareFileClient

### ISSUE THREAD

**Issue by timja** [Azure/azure-sdk-for-java#26867] opened 2022-02-04 08:39 UTC
**Describe the bug**
I cannot seem to find a way to upload an empty file with:

`com.azure:azure-storage-file-share:12.11.3`

***Exception or Stack Trace***

```text
java.lang.IllegalArgumentException: ShareFileRange end must be greater than or equal to 0 if specified.
java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: ShareFileRange end must be greater than or equal to 0 if specified.
	at com.azure.storage.file.share.models.ShareFileRange.<init>(ShareFileRange.java:43)
	at com.azure.storage.file.share.ShareFileAsyncClient.uploadRangeWithResponse(ShareFileAsyncClient.java:2069)
	at com.azure.storage.file.share.ShareFileAsyncClient.lambda$uploadWithResponse$33(ShareFileAsyncClient.java:1915)
	at com.azure.storage.common.implementation.UploadUtils.lambda$uploadFullOrChunked$0(UploadUtils.java:73)
	at reactor.core.publisher.FluxSwitchOnFirst$AbstractSwitchOnFirstMain.onComplete(FluxSwitchOnFirst.java:563)
	at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onComplete(FluxConcatMapNoPrefetch.java:240)
	at reactor.core.publisher.FluxFilter$FilterSubscriber.onComplete(FluxFilter.java:166)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:368)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onComplete(FluxConcatMap.java:276)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:142)
	at reactor.core.publisher.Operators.complete(Operators.java:137)
	at reactor.core.publisher.FluxEmpty.subscribe(FluxEmpty.java:42)
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
	at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
	at reactor.core.publisher.Mono.block(Mono.java:1706)
	at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:128)
	at com.azure.storage.file.share.ShareFileClient.uploadWithResponse(ShareFileClient.java:1490)
	at com.azure.storage.file.share.ShareFileClient.upload(ShareFileClient.java:1457)
	at UploadEmptyFileTest.uploadFile(UploadEmptyFileTest.java:61)
	at UploadEmptyFileTest.uploadEmptyFile(UploadEmptyFileTest.java:33)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:135)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1707)
		... 95 more
Caused by: java.lang.IllegalArgumentException: ShareFileRange end must be greater than or equal to 0 if specified.
	... 111 more
```

**To Reproduce**

Run the provided test

***Code Snippet***

```shell
gh repo clone timja/azure-empty-file-reproducer
cd azure-empty-file-reproducer

export STORAGE_ACCOUNT_NAME=...
export STORAGE_ACCOUNT_KEY=...
./gradlew check
```

Code is in this class:
https://github.com/timja/azure-empty-file-reproducer/blob/master/src/test/java/UploadEmptyFileTest.java

**Expected behavior**

I can upload the file

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. iOS], reported on many OSes, I'm on Mac
 - IDE: [e.g. IntelliJ] IntelliJ
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)], `com.azure:azure-storage-file-share:12.11.3`
 - Java version: [e.g. 8] `11`
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

https://github.com/jenkinsci/azure-storage-plugin/issues/210

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by rickle-msft** [comment] 2022-02-04 20:26
Couple thoughts here while I investigate this exact api that you're using.

1. Since you're already getting the file size, wouldn't it be preferrable to return early if the file size is zero? It'll save you a network request.
2. You can also call uploadFromFile and pass in the path rather than creating a buffered stream around a FileInputStream. I see we have some tests for empty files already in place for that, so it should work.

**Comment by timja** [comment] 2022-02-04 20:43
I'll take a look but this is a general purpose uploading between kbs and gbs, or occasionally empty files.

Would be nice if it this worked too :)

**Comment by rickle-msft** [comment] 2022-02-07 21:26
@timja I've looked into this a bit more, and I don't think this will be possible for us to fix as it's not really a bug in some sense. The reason uploadFromFile works is because we short circuit on seeing an empty file and simply don't perform any uploads. This is possible because we return void from the uploadFromFile method, so we are obligated to return some form of response from the upload. 

In upload, however, we always make an upload request. This largely due to the semantics of how we've defined the api's behavior, including its return type, which is an actual response. Because we have to make at least one api request in this method, we are prohibited from "uploading" an empty file because the service does not accept an upload request with a range that specifies 0 bytes. This is why I say it is not a bug in the sdk. 

Given all this, I would again recommend that you add a conditional statement in your application's logic to skip the call to upload if you determine the file is empty or otherwise call uploadFromFile directly.

**Comment by timja** [comment] 2022-02-07 22:03
Is there a separate create file call or similar as I can upload an empty file in the portal.

but yes can possibly just skip the empty file

**Comment by rickle-msft** [comment] 2022-02-07 22:10
There is a create file call, which is a pre-requisite for calling any of the upload methods. You already call this method in the code sample you provided--`fileClient.create()`

As far as uploading an empty file in the portal... it is possible to upload an empty file using the SDK. You can pass the filePath to `uploadFromFile` rather than calling `upload`, and it should work just fine and be general purpose as you requested. And then you also won't have to wrap it in a BufferedStream. The uploadFromFile method is also generally faster.

**Comment by timja** [comment] 2022-02-08 08:13
Hmm I use the `uploadWithResponse` option because I want the response.

(I didn't show it in the example but the application uses the Md5 from `response.getValue().getContentMd5()`)

Looks like I can do:

```diff
diff --git a/src/test/java/UploadEmptyFileTest.java b/src/test/java/UploadEmptyFileTest.java
index e3fbe01..36cac35 100644
--- a/src/test/java/UploadEmptyFileTest.java
+++ b/src/test/java/UploadEmptyFileTest.java
@@ -51,10 +51,13 @@ class UploadEmptyFileTest {
     }

     private void uploadFile(ShareFileClient fileClient, File file) throws IOException {
+        long bytes = Files.size(file.toPath());
+        fileClient.create(bytes);
+        if (bytes == 0L) {
+            return new Result(EMPTY_FILE_MD5);
+        }
         try (FileInputStream fis = new FileInputStream(file);
              BufferedInputStream bis = new BufferedInputStream(fis)) {
-            long bytes = Files.size(file.toPath());
-            fileClient.create(bytes);

             ShareFileUploadOptions fileUploadOptions = new ShareFileUploadOptions(bis);
             fileClient
```

I would prefer to use the `uploadFromFile` method if you could expose a version of it that returns a result, not sure if there's a reason you don't or if there's a sample that does something similar?

Do you have any recommendations?

Feel free to close this also as it looks like I have a solution

**Comment by rickle-msft** [comment] 2022-02-08 21:38
@timja Ah I see. It would be too simple if you guys didn't want the response and everything worked out :) 

Let me have a discussion with my team about it and see what we come up with. I don't think there's a strong reason why we don't that I'm aware of at the moment, but even considering that fact, it might be tough to add it for the case of an empty file. As I mentioned, the service doesn't actually permit empty uploads for file ranges to my knowledge, so we'd have to somehow fake the response in that case, which is unusual for us and still wouldn't give you the MD5 info you're looking for unless we again fake it.

Also, I am curious to hear more about how you're using the MD5s from the response. The response returned from the upload method you're using I believe is just the last response we get. So if the file is large enough, we'd upload it in a series of requests, and the response (and consequently MD5) is just the last one that comes back. That seems like it might affect the efficacy of your validation? This is again a service limitation since there is a maximum payload size, but I think it does mean that you aren't seeing the MD5 of the whole file, just a piece of it

**Comment by timja** [comment] 2022-02-08 22:00
> Also, I am curious to hear more about how you're using the MD5s from the response

Not much by the looks of it, 
![image](https://user-images.githubusercontent.com/21194782/153082724-12370328-3204-469e-b14f-3d6edafe1d00.png)

It's exposed in the response of an API about the uploaded objects, but I can try remove it and see what happens.

> is just the last one that comes back

Lol, interesting 😄.
I had noticed that sometimes the md5 came back null, normally in larger files.

**Comment by timja** [comment] 2022-02-09 08:49
From my side this is now resolved (https://github.com/jenkinsci/azure-storage-plugin/pull/216), but you're welcome to keep it open if you think it's a valid feature request.

**Comment by rickle-msft** [comment] 2022-02-09 17:50
Thanks, @timja! I'll leave it open for now as a discussion item for when we do our next round of features. We may or may not decide to close it then.

**Comment by ibrahimrabab** [comment] 2022-09-29 18:11
Hi @timja ,
The service unfortunately does not support uploading empty data still. We will go ahead and close this issue for now but will revisit in the future once service supports uploading empty data.

Thank you :)

**Closed by ibrahimrabab** 2022-09-29 18:11 UTC
Labels: Storage, Client, customer-reported, feature-request
