### ISSUE TITLE
Application Id used in User Agent string should be easily discoverable for users

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#12617] opened 2020-06-29 19:26 UTC
Currently, the optional application id used in the user agent string is set by looking at `HttpLogOptions.applicationId` property. This is not easily discoverable as the user might not always look into `HttpLogOptions` or expect it to be used in the user agent string. 

So, we should consider making this a property on client builders.

[ConfigurationClientBuilder](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/appconfiguration/azure-data-appconfiguration/src/main/java/com/azure/data/appconfiguration/ConfigurationClientBuilder.java#L180) sample where `httpLogOptions.getApplicationId()` is used to create `UserAgentPolicy`.

**Comment by JonathanGiles** [comment] 2020-09-10 23:00
This is a duplicate of what @hemanttanwar is working on.

**Comment by hemanttanwar** [comment] 2020-09-28 18:20
Closing as it is duplicate of https://github.com/Azure/azure-sdk-for-java/issues/13330
We have created Epic https://github.com/Azure/azure-sdk-for-java/issues/15107 to track this in each library.

**Closed by hemanttanwar** 2020-09-28 18:20 UTC
Labels: Azure.Core, Client
