### ISSUE TITLE
[FEATURE REQ] Support digest proxy authentication

### ISSUE THREAD

**Issue by jianghaolu** [Azure/azure-sdk-for-java#4567] opened 2019-07-24 21:55 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by joshfree** [comment] 2019-11-05 19:53
Resolving as duplicate of #6109

**Closed by joshfree** 2019-11-05 19:53 UTC
Labels: Azure.Core, Client
