### ISSUE TITLE
[QUERY] Error seen on azure-identity:1.9.0

### ISSUE THREAD

**Issue by simipaul** [Azure/azure-sdk-for-java#35863] opened 2023-07-13 11:24 UTC
**Query/Question**
I'm authenticating as below and getting successful response. 
 DefaultAzureCredential defaultCredential = new DefaultAzureCredentialBuilder()
                .managedIdentityClientId(identityClientId)
                .build();

However, I'm seeing this error in logs:-
[main] ERROR com.azure.identity.WorkloadIdentityCredential - WorkloadIdentityCredential authentication unavailable. The workload options are not fully configured. See the troubleshooting guide for more information. https://aka.ms/azsdk/java/identity/workloadidentitycredential/troubleshoot
[ForkJoinPool.commonPool-worker-1] ERROR com.azure.identity.implementation.WindowsCredentialAccessor - Element not found.

I would like to understand why this error is thrown.

***Why is this not a Bug or a feature Request?***
This isn't blocking authentication flow and I'm successfully able to get token from my app and secrets from KeyVault.

**Setup (please complete the following information if applicable):**
 - OS: Windows 11
 - IDE: IntelliJ IDEA 2023.1.3 (Community Edition)
 - Library/Libraries: [com.azure:azure-sdk-bom:1.2.13, com.azure:azure-identity:1.9.0, com.azure:azure-security-keyvault-secrets:4.6.2]
 - Azure Toolkit Plugin for IntelliJ: 3.78.1-2023.1
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by g2vinay** [comment] 2023-07-17 14:52
@simipaul 
Thank you for your query.

It looks like you're using managed identity authentication.
DefaultAzureCredential is trying Workload Identity Credential underneath before managed identity, that is not available in your environment.
This error log isn't impacting your Managed Identity authentication and can be ignored.

On our end, we will look into preventing this log from showing up when using DefaultAzureCredential.

**Comment by tkent** [comment] 2023-08-21 22:26
@simipaul, I just came here to file the same issue and saw it had already been done.

The error message is, of course, ignorable. However, every other method of authentication attempted in the `DefaultCredentialChain` does not log an error when the method cannot be used (which makes sense).

This problem impacts everyone who has monitoring in place for log messages above a certain level.  We have to either get irrelevant alerts or write a custom rule to ignore just this message type.

**Comment by g2vinay** [comment] 2023-08-23 18:03
@tkent @tinolazreg @simipaul 
An update related to this was released in azure-identity:1.10.0 recently, I'd recommend to try that version.

**Comment by tkent** [comment] 2023-08-28 04:10
@g2vinay - I can confirm this works. Unfortunately, it was not done under a patch revision. The breaking changes between `1.9.0` and `1.10.0` didn't impact our application, but may impact others.

**Comment by joshfree** [comment] 2023-09-05 17:30
We recommend folks upgrade to `1.10.0` of azure-identity.  The changes between 1.9 and 1.10 are documented here: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/CHANGELOG.md#1100-2023-08-09.   If anyone has feedback on these changes, as always, we'd love to hear from you!

**Comment by g2vinay** [comment] 2023-09-05 17:34
@tkent 
Thank you for the confirmation.
The breaking change in 1.10.0 is from 1.10.0-beta.1, it won't impact customer who are upgrading from a stable version.

Closing this issue.

**Closed by g2vinay** 2023-09-05 17:34 UTC
Labels: bug, Client, customer-reported, Azure.Identity, needs-team-attention
