### ISSUE TITLE
Checkpoints are not getting properly updated in the Blob storage when using Azure Event Hubs Spring Cloud Stream Binder client library

### ISSUE THREAD

**Issue by venkin84** [Azure/azure-sdk-for-java#21751] opened 2021-05-24 06:54 UTC
I am using Azure Event Hubs Spring Cloud Stream Binder client library 2.4.0
Checkpointing is set to Manual Mode
When I receive the data from the event hub receiver, I check for the message received is enqueued later than the previously read messages then I try doing the checkpointer.success() to checkpoint in the blob storage. Refer the code below.

```java
    private Instant lastMessageEnqueuedTime = null;

    @Bean
    public Consumer<Message<String>> consume() {
        return message -> {
            Instant messageEnqueuedTime = (Instant) message.getHeaders().get("azure_eventhub_enqueued_time");
            LOGGER.info("New message received: '{}'", message);
            System.out.println(message.getPayload() + " | Enqueued Time: " + messageEnqueuedTime + " | Last Instant: " + lastMessageEnqueuedTime);
            if(lastMessageEnqueuedTime == null || lastMessageEnqueuedTime.isBefore(messageEnqueuedTime)){
                lastMessageEnqueuedTime = messageEnqueuedTime;
                Checkpointer checkpointer = (Checkpointer) message.getHeaders().get(CHECKPOINTER);
                checkpointer.success()
                        .doOnSuccess(success -> LOGGER.info("Message '{}' successfully checkpointed", message))
                        .doOnError(error -> LOGGER.error("Exception: {}", error.getMessage()))
                        .subscribe();
            }
        };
    }
```

The behaviour I see is 
- Not all the messages are getting checkpointed, but they are not received again as long as the service is alive.
- When the receiver service is restarted the messages that are missed are getting received again.

Need support in fixing this issue asap.

**Comment by saragluna** [comment] 2021-05-24 09:07
@yiliuTo please take a look at this.

**Comment by han-gao** [comment] 2021-05-26 03:23
@venkin84  
I will look into it.

**Comment by venkin84** [comment] 2021-05-28 18:55
> @venkin84
> I will look into it.

Hi @han-gao... Thanks for looking into it... Any update on the issue?

**Comment by backwind1233** [comment] 2021-05-31 06:48
Hi, @venkin84, can you tell us how many partitions do you have in your eventhub configuration?

**Comment by yiliuTo** [comment] 2021-05-31 10:09
Hi @venkin84 could you introduce more about your context? For example, how you use the Event Hub( your partition number and why you checkpoint messages with the order or enqueued time? )?

**Comment by venkin84** [comment] 2021-05-31 17:12
Hi @yiliuTo @backwind1233... I am developing a performance testing tool for testing the performance of our large platform IoT applications. The eventhubs are typically the endpoints for these tests and so I need to use this tool in various environment and platforms, hence can't say what will be the partitions count etc. as it might change from platform to platform. Having said that, the test Eventhub that I am using for validating this tool is having 3 partitions.

When I am testing, I validate for the events sent and event received depending on the tests (can involve aggregations, data consistency, latency, data duplications etc). The applications I test is expected to handle real time data from the eventhubs. So I am interested in the ensuring that we get the data within the test window. hence checkpointing the latest data is required.

**Comment by yiliuTo** [comment] 2021-06-01 03:23
Hi @venkin84 , in a multiple partition case, the receiver client is not promised to get messages from different partitions with the order of enqueued time, but of course in a single partition case, it is different. 

So if you go with `if(lastMessageEnqueuedTime == null || lastMessageEnqueuedTime.isBefore(messageEnqueuedTime)){` , then once the receiver client receives a message A earlier than B, while A is in partition 0 which enqueued later than the time message B enqueued in partition 1, then you will never checkpoint B. That's the explanation of the phenomenon 
```
Not all the messages are getting checkpointed, but they are not received again as long as the service is alive.
```

And in this case, your offset of partition 1 stored in Storage blob is possible to stop at message B(if no more messages in partition1 are checkpointed), then when the receiver client is restart, it continues to consume messages from those offsets of each partition, then it's possible that you receive message B.

So due to we cannot promise that messages in multiple partitions will be received by the client by the order of enqueued time globally, I think to consume message with enqueued time may not be a reasonable way.

**Comment by venkin84** [comment] 2021-06-01 12:44
Hi @yiliuTo... Sorry to distract you guys with that piece of code/logic, that was something of a trial I was doing. Even if I remove the logic completely as shown below the same issue is seen.

`@Bean
    public Consumer<Message<String>> consume() {
        return message -> {
            LOGGER.info("New message received: '{}'", message);
            System.out.println(message.getPayload()
                    + " | Enqueued Time: " + message.getHeaders().get("azure_eventhub_enqueued_time"));
            Checkpointer checkpointer = (Checkpointer) message.getHeaders().get(CHECKPOINTER);
            checkpointer.success()
                    .doOnSuccess(success -> LOGGER.info("Message '{}' successfully checkpointed", message))
                    .doOnError(error -> LOGGER.error("Exception: {}", error.getMessage()))
                    .subscribe();

            this.gateway.sendEvent(message.getPayload());
        };
    }`

**Comment by venkin84** [comment] 2021-06-01 12:48
Sorry for some reason the code insert doesn't seem to work as expected.

**Comment by venkin84** [comment] 2021-06-02 11:54
@yiliuTo @backwind1233  Can you please prioritise this issue. Also let me know if you need any clarification. Thanks.

**Comment by yiliuTo** [comment] 2021-06-02 15:24
Hi @venkin84 , I tried to reproduce your issue with our [single binder sample](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-samples/azure-spring-cloud-sample-eventhubs-binder) but failed. As you could see our sample uses similiar checkpointing way as you do. And I run the sample with one application instance which means only one producer and consumer(one consumer group, one event processor) communicates with the Event Hub(3 partions as you mensioned).

So could you share a sample project that I could reproduce the behavior with. And if there are other necessary configurations e.g. Azure resources, application property configuration, running environment, please share as well.

And for the behavior you mensioned 
```
- Not all the messages are getting checkpointed, but they are not received again as long as the service is alive.
- When the receiver service is restarted the messages that are missed are getting received again.
```
I could reproduce it only for the following two cases:
1. When I stoped my application then there might be messages that the consumer havn't consumed. So when I restart the application, it will continue consuming from lastest position. This is normal behavior so I think what you meet must not be like this.
2. There are times that the load balancer of Event Hub doesn't work timly. In this case there are partitions that are not claimed or consumed before the application stops. The load balance performance is not stable. In my experients, there are cases that 3 partitions cannot be claimed completely within 90s. In this case, you cloud check the log of 
   ```
   [ctor-http-nio-2] c.a.m.e.PartitionBasedLoadBalancer       : Successfully claimed ownership of x
   ```
   to see if all of the partitions are claimed. And this is your case, I could report a bug to the Java Event Hub client SDK.

**Comment by yiliuTo** [comment] 2021-06-02 15:35
And could you help to confirm `Not all the messages are getting checkpointed, but they are not received again as long as the service is alive`, do you mean your client has checkpointed a message, but the Blob storage is not updated? Or the client didn't checkpoint the message?

**Comment by venkin84** [comment] 2021-06-02 19:22
@yiliuTo With regards to the case scenarios  you have mentioned related to reproduction

- I do see in my log that the client has received all the messages that I have sent to the EventHub. After which I even have left the application running for over an hour.
- I do see all the partitions getting claimed.
- I only see that the some of the received messages are not getting check pointed.
- Those exact same messages that are not getting check pointed get received again when I restart my service.
- This time again all messages do not get check pointed only some portion of the received messages get check pointed.
- I have to do this process 3-4 times for a total message count of 1000 for all of them to get check pointed.

When I say 

> Not all the messages are getting check pointed, but they are not received again as long as the service is alive

I mean that I do not see the message log I expect when the checkpointing succeeds, and neither do I see any Error Logs showing failure of the check pointing. In blob storage I see that the message that is seen as check pointed in my applications logs are only updated.

My code it is very similar to your code except that I did not handle onBackpressure scenario and I have used the Emitters (in the controller) instead of Sink as in the documentation.

**Comment by lzc-1997-abel** [comment] 2021-06-08 09:50
@venkin84 Sorry to reply you late.
As the modified checkpoint message is sent asynchronously, it may cause the first consumed message to checkpoint later, so that the checkpoint of the later consumed message will be overwritten. You can turn this into a synchronous operation by calling `.block()` instead of `subscribe()`.

**Comment by yiliuTo** [comment] 2021-06-15 02:57
Closing this issue due to lack of requested feedback, please reopen it if you would like us to look at this issue.

**Closed by yiliuTo** 2021-06-15 02:57 UTC
Labels: Client, azure-spring, azure-spring-eventhubs, customer-reported, question
