### ISSUE TITLE
[BUG] Interface is not visible from class loader when listening from Service Bus

### ISSUE THREAD

**Issue by rushabh196** [Azure/azure-sdk-for-java#10475] opened 2020-04-24 01:26 UTC
**Describe the bug**
We are currently facing an issue when we are consuming messages from azure service bus. The issue is not necessarily due to azure service bus library. However, it internally uses “CompletableFuture” to spawn a new thread every time a message is received. Some of the java libraries which we are using are failing under this setup due class loader visibility. The reason for this is because the threads created using CompleteableFuture.supplyAsync() do not use the AppClassLoader as a parent. Due to this, the classes available to the classpath are not visible during runtime.

***Exception or Stack Trace***
java.lang.IllegalArgumentException - exc.name=java.lang.IllegalArgumentException,exc.orig=java.lang.reflect.Proxy$ProxyClassFactory.apply:581,exc.tenant=com.walmartlabs.pangaea.dal.oracle.connectionpool.AbstractOracleUCPFactory$OracleUCPFacade.take:533,exc.msg=java.lang.IllegalArgumentException:interface oracle.jdbc.OracleConnection is not visible from class loader,exc.chain=458df330,exc.stack=java.lang.IllegalArgumentException: interface oracle.jdbc.OracleConnection is not visible from class loader\n\tat java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:581)\n\tat java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557)\n\tat java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)\n\tat java.lang.reflect.WeakCache.get(WeakCache.java:127)\n\tat java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419)\n\tat java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719)\n\tat oracle.ucp.jdbc.proxy.ConnectionProxyFactory.createConnectionProxy(ConnectionProxyFactory.java:78)\n\tat oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:919)\n\tat oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:863)\n\tat oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:855)\n\tat com.walmartlabs.pangaea.dal.oracle.connectionpool.AbstractOracleUCPFactory$OracleUCPFacade.take(AbstractOracleUCPFactory.java:533)\n\tat com.walmartlabs.pangaea.dal.oracle.connectionpool.AbstractOracleUCPFactory$OracleUCPFacade.take(AbstractOracleUCPFactory.java:411)\n\tat com.walmartlabs.dal.core.pool.SharedPool.take(SharedPool.java:110)\n\tat com.walmartlabs.dal.rdbms.connectionpool.RdbmsConnectionProvider.getConnection(RdbmsConnectionProvider.java:74)\n\tat org.hibernate.internal.AbstractSessionImpl$NonContextualJdbcConnectionAccess.obtainConnection(AbstractSessionImpl.java:281)\n...\n,applog.msg=RuntimeException caught during get retry count: 0.

**Expected behavior**
The classes available on the classpath should be visible during runtime

**Setup (please complete the following information):**
 - OS: iOS
 - IDE : Eclipse
 - Version of the Library used
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-servicebus</artifactId>
            <version>3.1.4</version>
        </dependency>

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [ ] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment] 2020-04-27 19:41
Thanks for posting the v3 ServiceBus issue @rushabh196.  @yvgopal can you please take a look?

/cc @hemanttanwar @conniey who are working on the v4 ServiceBus SDK

**Comment by conniey** [comment] 2020-04-27 20:04
What is the version of UCP you are using? This seems like an issue that was resolved with 12.2.0.1. 
https://community.oracle.com/thread/4190744

Otherwise, is there a minimal repro you can provide that can give us more context?

**Comment by rushabh196** [comment] 2020-04-30 18:20
Hi Conniey,

Thanks for looking into this issue.

We're using the following versions:
UCP - 11.2.0.3
OJDBC - 11.2.0.3

I've already gone through the thread you mentioned (https://community.oracle.com/thread/4190744), and understand that probably the issue would be resolved with 12.2.0.1 version of these artifacts.
However, our service bus implementation is part of a larger code base. Unfortunately, this code base (currently using oracle 11.X.X) cannot be migrated to oracle 12.X.X.

As mentioned in the thread, there seems to be no solution for 11.X.X versions. Or at least I was not able to find one.

What would you recommend in this scenario?

**Comment by conniey** [comment] 2020-04-30 20:24
Hey,

Unfortunately, since they are doing this proxy loading inside their own code, it is not something we can modify or fix. Do you have any Oracle contacts you can ping? Otherwise, the thoughts are to wrap `PoolDataSourceImpl.getConnection()` and loading that class yourself.

Cheers,
Connie

**Comment by axisc** [comment] 2020-08-12 01:53
routing to @conniey and @hemanttanwar to help with this since it's not related to Service Bus

**Comment by conniey** [comment] 2020-08-12 05:03
@axisc Hey. While this is not related to the service, it is related to the Track 1 Java client for Service Bus. We had added the "Service Attention" label so that the service could respond appropriately to this issue.

**Comment by jongio** [comment] 2020-08-18 17:24
@joshfree  - Can you please verify that the right tags are applied to this one?

**Comment by joshfree** [comment] 2020-08-19 23:08
@yvgopal can you please assist per the request above?

**Comment by yvgopal** [comment] 2020-08-20 21:59
As @conniey already explained, there is nothing that the SDK can do to resolve the issue for you. SDK makes no assumptions about class loaders, except the default java class loader logic. I don't the environment under which you application is running. You should either move to the proper version of UCP where the issue is resolved or work around the issue.

A simplistic workaround I would try is adding all jars used by the application to the boot classpath. Or I see classloader heirarchy as a tree, and workaround any such class visibility issues by making all jars available at the level in the hierarchy that the lowest common ancestor of all relevant paths.

It is not something the SDK team can fix.

**Closed by yvgopal** 2020-08-20 21:59 UTC
Labels: Client, Service Attention, Service Bus, Track 1, customer-reported, question
