### ISSUE TITLE
[Azure Cosmos DB OLTP Spark 3 connector] low performance WRITE

### ISSUE THREAD

**Issue by michalmar** [Azure/azure-sdk-for-java#31149] opened 2022-09-26 11:23 UTC
I am writing wide dataframe from Azure Databricks to Cosmos using Azure Cosmos DB OLTP Spark 3 connector.

I am facing performance issues (slow load) - 2k rows (items) in 30s. The dataframe represents 1M profiles with 200 attributes.

Env:
Cosmos DB Serverless.
Azure Databricks runtime 11.2 (includes Apache Spark 3.3.0, Scala 2.12)
Azure Cosmos DB OLTP Spark 3 connector ver. azure-cosmos-spark_3-2_2-12-4.13.1

**Comment by FabianMeiswinkel** [comment] 2022-09-26 11:29
First - The Cosmos DB Spark connector is not supported on Spark 3.3 - only Spark 3.1 (https://mvnrepository.com/artifact/com.azure.cosmos.spark/azure-cosmos-spark_3-1_2-12/4.13.1) and Spark 3.2 (https://mvnrepository.com/artifact/com.azure.cosmos.spark/azure-cosmos-spark_3-2_2-12/4.13.1)

Usually ingestion/write performance issues are caused by not having enough provisioned throughput on the Cosmos DB Container. We have a document walking through some recommendations for ingestion here: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3_2-12/docs/scenarios/Ingestion.md - that also covers aspects of identifying necessary provisioned throughput etc. If you still face issues after going through that document and moving to Spark 3.1 or Spark 3.2 please reactivate the github issue or file a support incident with the AccountName, Databasename and Containername and we can take a look.

**Closed by FabianMeiswinkel** 2022-09-26 11:29 UTC
Labels: needs-triage
