### ISSUE TITLE
[BUG]: Error processing condition on org.springframework.cloud.stream.config.BindingServiceConfiguration.binderFactory

### ISSUE THREAD

**Issue by bitbaggi** [Azure/azure-sdk-for-java#31436] opened 2022-10-12 22:26 UTC
**Describe the bug**
Hey guys,
this is my build.gradle:
[build.gradle.txt](https://github.com/Azure/azure-sdk-for-java/files/9769055/build.gradle.txt)

After starting of spring an exception occured.

***Exception or Stack Trace***
[exception.txt](https://github.com/Azure/azure-sdk-for-java/files/9769057/exception.txt)

**To Reproduce**
1. Create new Spring boot project
2. Override build.gradle with my build.gradle
3. Start

**Setup (please complete the following information):**
 - OS: Windwos 10
 - IDE: IntelliJ
 - Library/Libraries: com.azure.spring:spring-cloud-azure-stream-binder-servicebus:6.0.0-beta.2
 - Java version: 17
 - App Server/Environment: Tomcat
 - Frameworks: Spring Boot

**Comment by moarychan** [comment] 2022-10-13 02:11
Hi @bitbaggi ， the Spring Cloud Azure 6.0.0-beta.2 is based on Spring Boot 3.0.0-M4 and Java 17, could you try to upgrade the Spring Boot version? Please check the reference doc https://microsoft.github.io/spring-cloud-azure/6.0.0-beta.2/reference/html/index.html#what-is-new-in-6-0-since-4-x

**Comment by bitbaggi** [comment] 2022-10-13 08:45
Nice, its working.
Thank you very much ☺️

**Comment by yiliuTo** [comment] 2022-10-13 10:13
@bitbaggi , the 6.0.0-beta.2 of spring-cloud-azure-stream-binder-servicebus has a bug which blocks the sending feature. It has been fixed in https://github.com/Azure/azure-sdk-for-java/pull/31447. So if you want to use the sending function, please expect our next release.

**Comment by saragluna** [comment] 2022-10-17 02:30
@yiliuTo, should we update the IT to cover such case?

**Comment by yiliuTo** [comment] 2022-10-18 01:54
@saragluna yeah I agree, this issue https://github.com/Azure/azure-sdk-for-java/issues/31491 I think could cover the IT for such case

**Comment by moarychan** [comment] 2022-11-03 09:06
Hi @bitbaggi , the `6.0.0-beta.3` version is coming, since the `6.0.0-beta.2` is a new beta version based on Spring Boot 3 milestone version, I am wondering how you find this version for your application, this is just a survey for our side to improve the documentation or other aspect, any comments are welcome!

**Comment by moarychan** [comment] 2022-11-04 10:13
Hi @bitbaggi , the Spring Cloud Azure 6.0.0-beta.3 is available now, please check if you want to use this version, https://microsoft.github.io/spring-cloud-azure/6.0.0-beta.3/reference/html/

**Comment by stliu** [comment] 2022-11-08 05:58
@bitbaggi I'm wondering where you saw the `com.azure.spring:spring-cloud-azure-stream-binder-servicebus:6.0.0-beta.2` and add this into your `build.gradle`? the 6.x version is compatible with Spring Boot 3 not 2.7, maybe we have something on document to improve and avoid further mistake happen

**Comment by saragluna** [comment] 2022-11-11 08:52
It could be dependabot https://github.com/Azure-Samples/azure-spring-boot-samples/pull/555.

**Comment by stliu** [comment] 2022-11-21 06:57
@saragluna  @moarychan with regard to this issue, since we don't know how to config dependabot to not promote our 6.0 to a spring boot 2.x application, I think we need to add clear error message when our 6.0 is used in a spring boot 2.x application to inform users how to fix it

**Comment by saragluna** [comment] 2022-11-21 09:30
@stliu thanks, good point. @moarychan will the compatibility verifier handle this? Or is the exception happens before the compatibility verifier?

**Comment by moarychan** [comment] 2022-11-25 02:11
Hi all, I re-examined this issue, sorted it out as follows, and concluded that there is a user scenario that we have not covered. 

The brief summary is:

When using our 6.x(6.0.0-beta.2) spring-cloud-azure-stream-binder-xxx library, the Spring Boot version is locked at 2(2.7.4), and the Spring Cloud version(2021.0.4) is not locked, which will cause current problems for users.

The detailed analysis is as follows:

# 1 Overview
Since Spring Boot(SB) ships multiple major versions(2.7..x and 3.x), and Spring Cloud Azure(SCA) also ships multiple major versions(4.x and 6.x) to match the Spring Boot version, At the same time, there are multiple versions(2021 & 2022) corresponding to Spring Cloud(SC). If the user does not read this [SCA version mapping](https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Versions-Mapping#spring-cloud-azure-support-status) carefully, it is likely to use the wrong version.

## 1.1 Customers use SCA 4 in an SB 3 application
When the customer uses the SCA 6 scenario in the SB 2 application, the error message is as expected. Assuming that the customer has a Gradle configuration similar to the following, when the customer starts the application, the following failure report should be reported to the user first.

Customer Gradle configuration:
```groovy
plugins {
    id 'java'
    id 'org.springframework.boot' version '3.0.0-M4'
    id 'io.spring.dependency-management' version '1.0.9.RELEASE'
}

group 'de.test'
version '1.1'
sourceCompatibility = '17'

repositories {
    mavenLocal()
    mavenCentral()
    gradlePluginPortal()
    maven { url 'https://repo.spring.io/release' }
    maven { url 'https://repo.spring.io/milestone' }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'com.azure.spring:spring-cloud-azure-stream-binder-servicebus:4.4.1'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
```

![image](https://user-images.githubusercontent.com/19926623/203885379-e789eecf-374d-4d30-b81e-60298929b353.png)


## 1.2 Customers use SCA 6 in an SB 2 and SC 2021 application

If customers add the `dependencyManagement` with Spring Cloud 2021.0.4, Gradle configuration like below:

```groovy
plugins {
    id 'java'
    id 'org.springframework.boot' version '2.7.4'
    id 'io.spring.dependency-management' version '1.0.14.RELEASE'
//    id 'org.springframework.experimental.aot' version '0.12.1'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '17'

repositories {
    mavenLocal()
    mavenCentral()
    maven { url 'https://repo.spring.io/release' }
}

ext {
    set('springCloudVersion', "2021.0.4")
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'com.azure.spring:spring-cloud-azure-stream-binder-servicebus:6.0.0-beta.2'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.named('bootBuildImage') {
    builder = 'paketobuildpacks/builder:tiny'
    environment = ['BP_NATIVE_IMAGE': 'true']
}

```

then the below failure report is as expected:

![image](https://user-images.githubusercontent.com/19926623/203885426-4949d636-5575-4b1b-a515-298b7c431f30.png)


But other situations may not be friendly to help customers.

# 2 Problem statement

The SCA 4 customers may notice the new version of SCA 6, they may try to upgrade to SCA 6, when they forget to lock the SC version to 2021. they will get the unclear error message encountered before the SB version compatibility validation. 

This is because the AOT support of Spring Framework 6 will bring up lots of callback (Such as `BeanRegistrationAotProcessor` in `org.springframework.cloud.stream.binder.BinderChildContextInitializer`) process, and the implementations are referenced to the new Spring Cloud Stream(SCS) 2022.

# 3 User stories

## 3.1 Customers use SCA 6 in an SB 2 application

Customer Gradle configuration:
```groovy
plugins {
    id 'java'
    id 'org.springframework.boot' version '2.7.4'
    id 'io.spring.dependency-management' version '1.0.14.RELEASE'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '17'

repositories {
    mavenLocal()
    mavenCentral()
    gradlePluginPortal()
    maven { url 'https://repo.spring.io/release' }
    maven { url 'https://repo.spring.io/milestone' }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'com.azure.spring:spring-cloud-azure-stream-binder-servicebus:6.0.0-beta.2'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
```

a clear failure report should be output to the customer, not the error message with a long stack trace of Spring.
the clear error message should contain the below items:
- The root cause of the error is using the wrong dependency SCA 6.
- Prompt to downgrade to SCA 4.

**Comment by saragluna** [comment] 2022-11-28 07:59
@moarychan please help me understand this, the error messages from the screenshots you pasted are our current behavior?

**Comment by stliu** [comment] 2022-11-28 09:47
I'm still a little bit lost here.

could you explain these scenarios, I can see some are discussed and some arent' 


# Secnarios 

## No Spring Cloud

- [ ] Spring Boot 2 + Spring Cloud Azure 4
- [ ] Spring Boot 2 + Spring Cloud Azure 6
- [ ] Spring Boot 3 + Spring Cloud Azure 4
- [ ] Spring Boot 3 + Spring Cloud Azure 6

## With Spring Cloud

- [ ] Spring Boot 2 + Spring Cloud Azure 4 + Spring Cloud x?
- [ ] Spring Boot 2 + Spring Cloud Azure 6 + Spring Cloud x?
- [ ] Spring Boot 3 + Spring Cloud Azure 4 + Spring Cloud x?
- [ ] Spring Boot 3 + Spring Cloud Azure 6 + Spring Cloud x?

**Comment by moarychan** [comment] 2022-12-09 11:18
# 1 Overview
Since Spring Boot(SB) has released multiple major versions(2.x and 3.x), and Spring Cloud Azure(SCA) also has released multiple major versions(4.x and 6.x) to match the SB version, At the same time, there are multiple versions(2021.x & 2022.x) corresponding to Spring Cloud(SC). If the customer does not read this [SCA version mapping](https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Versions-Mapping#spring-cloud-azure-support-status) carefully, it is likely to use the wrong version.

# 2 Problem statement

If customers use the below combination, the application will fail to start and the error message is not clear or actionable.
- SB 2.x + SCA 6.x
- SB 3.x + SCA 4.x

SCA should make the application fast fail with a clear message.

# 3 User scenarios

Note:
- 'SCA with SC component' means the following artifacts
   - spring-cloud-azure-starter-stream-eventhubs
   - spring-cloud-azure-starter-stream-servicebus
   - spring-cloud-azure-stream-binder-eventhubs
   - spring-cloud-azure-stream-binder-servicebus

- 'SCA not SC component' means all SCA artifacts except those listed above.

## 3.1 Scenario: SB 2.x + SCA 6.x(not SC component)

### 3.1.1 Current behavior and message

The application fails to start, the error message as below:

```console
Description:

Your project setup is incompatible with our requirements due to following reasons:
- Spring Boot [2.7.4] is not compatible with this Spring Cloud Azure version.


Action:

Consider applying the following actions:
- Change Spring Boot version to one of the following versions [3.0.0].
You can find the latest Spring Boot versions here [https://spring.io/projects/spring-boot#learn].
If you want to learn more about the Spring Cloud Azure compatibility, you can visit this page [https://aka.ms/spring/versions] and check the [Which Version of Spring Cloud Azure Should I Use] section.
 If you want to disable this check, just set the property [spring.cloud.azure.compatibility-verifier.enabled=false].
```

### 3.1.2 Except behavior and message

The application fails to start, and a more accurate message should be output as below:

```console
Description:

Your project setup is incompatible with our requirements due to following reasons:
- Spring Boot [2.7.4] is not compatible with this Spring Cloud Azure version.


Action:

Consider applying the following actions:
- Change Spring Boot version to one of the following versions [3.0.0-M4].
You can find the latest Spring Boot versions here [https://spring.io/projects/spring-boot#learn].
If you want to learn more about the Spring Cloud Azure compatibility, you can visit this page [https://aka.ms/spring/versions] and check the [Which Version of Spring Cloud Azure Should I Use] section.
If you want to disable this check, just set the property [spring.cloud.azure.compatibility-verifier.enabled=false].
```

## 3.2 Scenario: SB 2.x + SCA 6.x(with SC component)

### 3.2.1 Current behavior and message

The application fails to start, this is expected, but the error message is not clear and the customer is having a difficult time finding the root cause of the failure. See full stack trace from this issue description.

### 3.2.2 Except behavior and message

The application fails to start, and instead of outputting an error stack trace, it should output a clear message, as expected by 3.1.2.

## 3.3 Scenario: SB 3.x + SCA 4.x(not SC component)

### 3.3.1 Current behavior and message

The application fails to start, the error message as below:

```console
Description:

Your project setup is incompatible with our requirements due to following reasons:
- Spring Boot [3.0.0-M4] is not compatible with this Spring Cloud Azure version.


Action:

Consider applying the following actions:
- Change Spring Boot version to one of the following versions [2.5.x, 2.6.x, 2.7.x].
You can find the latest Spring Boot versions here [https://spring.io/projects/spring-boot#learn].
If you want to learn more about the Spring Cloud Azure compatibility, you can visit this page [https://aka.ms/spring/versions] and check the [Which Version of Spring Cloud Azure Should I Use] section.
 If you want to disable this check, just set the property [spring.cloud.azure.compatibility-verifier.enabled=false].
```

### 3.3.2 Except behavior and message

Behavior and error messages as expected.

## 3.4 Scenario: SB 3.x + SCA 4.x(with SC component)

### 3.4.1 Current behavior and message

The application fails to start, the error message as below:

```console
Description:

Your project setup is incompatible with our requirements due to following reasons:
- Spring Boot [3.0.0-M4] is not compatible with this Spring Cloud Azure version.


Action:

Consider applying the following actions:
- Change Spring Boot version to one of the following versions [2.5.x, 2.6.x, 2.7.x].
You can find the latest Spring Boot versions here [https://spring.io/projects/spring-boot#learn].
If you want to learn more about the Spring Cloud Azure compatibility, you can visit this page [https://aka.ms/spring/versions] and check the [Which Version of Spring Cloud Azure Should I Use] section.
 If you want to disable this check, just set the property [spring.cloud.azure.compatibility-verifier.enabled=false].
```

### 3.4.2 Except behavior and message

Behavior and error messages as expected.

# 4 Goals

Verify compatibility between the Spring Boot version and Spring Cloud Azure version.

# 5 Non-Goals

Not verify compatibility with Spring Cloud version.

# 6 Exit Criteria(TBC)

# 7 Follow up considerations

## 7.1 What's the alignment to choose

### 7.1.1 Alignment 1

- Spring Cloud verifies Spring Boot version

- Spring Cloud Azure verifies Spring Boot version

### 7.1.1 Alignment 2

- Spring Cloud Azure verifies Spring Boot version
- Spring Cloud Azure verifies Spring Cloud version

## 7.2 What phases of verification occur

- On JVM startup

- On Application Context bean initialization (SCA selected)

- On Application Context other stages

## 7.3 SCA verifies which version

- Only Spring Boot version

- Spring Boot and Spring Cloud

## 7.4 Who to enable SB and SC verification when using SC component-based SCA

- SCA
- Spring Cloud Stream

**Comment by moarychan** [comment] 2022-12-14 03:36
Superseded by https://github.com/Azure/azure-sdk-for-java/issues/32593

**Closed by moarychan** 2022-12-14 03:36 UTC
Labels: bug, Client, customer-reported, needs-team-attention, needs-author-feedback, azure-spring, azure-spring-servicebus
