### ISSUE TITLE
[BUG] Perf framework hangs while executing async scenario with insufficient heap.

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-java#21629] opened 2021-05-18 16:39 UTC
Try the following scenario:
```
java -Xms100m -Xmx100m -jar azure-storage-perf-1.0.0-beta.1-jar-with-dependencies.jar uploadblob --warmup 0 --duration 1 --size 1048576000
```

The program keeps reporting zero progress. It is expected to crash with OOM in that case.

It repros easily on local machime.
Test run where this happened: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=899330&view=logs&j=1ebff73e-a26c-5a81-5f48-b56b69f60e6e&t=3f94ee88-7ff1-5b4e-3fcb-67bf1ac93b37
![image](https://user-images.githubusercontent.com/61715331/118690210-ae3e8680-b7bc-11eb-9997-70747934687c.png)

In order to triage whether it's SDK or perf framework I executed similar scenario in simple console app. That one failed immediately with OOM. That suggest problem is in perf framework.
![image](https://user-images.githubusercontent.com/61715331/118690413-e34ad900-b7bc-11eb-83eb-8acf15338a52.png)

**Comment by mikeharder** [comment] 2021-05-20 21:43
The root cause is exceptions like `OutOfMemoryError` are handled differently by the default Reactor schedulers.  Instead of terminating the Flux, the Flux will hang and the exception is only sent to the thread's `uncaughtExceptionHandler` and the Reactor `Schedulers.onHandleError`.

https://github.com/reactor/reactor-core/issues/2521

https://github.com/reactor/reactor-core/blob/84e921fbfd84754d519b5e3c78262495dcf48b87/reactor-core/src/main/java/reactor/core/Exceptions.java#L443

https://github.com/reactor/reactor-core/blob/84e921fbfd84754d519b5e3c78262495dcf48b87/reactor-core/src/main/java/reactor/core/Exceptions.java#L443

The perf framework will be fixed by this PR: https://github.com/Azure/azure-sdk-for-java/pull/21690

This issue could also impact any SDK code which uses the default Reactor schedulers.

**Closed** 2021-05-20 22:09 UTC
Labels: Central-EngSys, tenet-performance, test bug, test-reliability
