### ISSUE TITLE
Make sure telemetry is correctly sent and collected in Spring Cloud Azure 4.0

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#25892] opened 2021-12-08 03:07 UTC
In Spring Cloud Azure 4.0 we changed the mechanism of adding spring identifier to User-Agent header, we should make sure all the user-agent are set correctly. When HTTP-based sdk clients send requests, we should make sure all User-Agent headers with our identifiers are sent to the server. When AMQP-based clients send messages, we should make sure the same. And the Cosmos client should also be tested.

Spring identifier contains two parts of information: library identifier and library version.

We should make sure:
- Spring identifiers are sent to the server.
- Telemetry be collected correctly by our BI system.

The components to test: 
- Spring Cloud Azure AutoConfigure for App Configuration, Cosmos, Event Hubs, KeyVault Certificate, KeyVault Secrets, KeyVault Property Source, Service Bus, Storage Blob, Storage File, Storage Queue.
- Spring Integration for Service Bus and Event Hubs.
- Spring Cloud Stream Binder for Service Bus and Event Hubs.

**Comment by chenrujun** [comment] 2022-01-19 00:49
[Link to excel about current process](https://microsoftapc.sharepoint.com/:x:/r/teams/Springintegration/_layouts/15/Doc.aspx?sourcedoc=%7B6D12D2D4-B3AF-4045-9F36-0948820BBE35%7D&file=BI%20usage%20track%20for%204.0.xlsx&wdOrigin=OFFICECOM-WEB.MAIN.REC&ct=1642552590931&action=default&mobileredirect=true)

**Comment by chenrujun** [comment] 2022-03-15 09:09
> [Link to excel about current process](https://microsoftapc.sharepoint.com/:x:/r/teams/Springintegration/_layouts/15/Doc.aspx?sourcedoc=%7B6D12D2D4-B3AF-4045-9F36-0948820BBE35%7D&file=BI%20usage%20track%20for%204.0.xlsx&wdOrigin=OFFICECOM-WEB.MAIN.REC&ct=1642552590931&action=default&mobileredirect=true)

Now all user-agent is collected except for storage related items: `az-sp-sb/`, `az-sp-sf/`, `az-sp-sq/`.
This is caused by service side. Here is the comment from Kyle:
> The storage service samples at a very high rate, so it's likely that the request was not logged on their side. I'd recommend working with CosmosDB for now, if there is a spring offering for it. There are several known data gaps, including the configurations of our DDAzureServicesApps, that limit our analysis - I will look for the recording which details these gaps for you


Closing this issue because we have finished all tasks in our side.

**Closed by chenrujun** 2022-03-15 09:09 UTC
Labels: Client, azure-spring
