### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by akreienbring** [Azure/azure-sdk-for-java#34617] opened 2023-04-24 18:46 UTC
**Describe the bug**
I have also reported this to MSAL4J.

I see this error:
`Azure Identity => ERROR in getToken() call for scopes [https://graph.microsoft.com/.default]: Could not initialize class com.microsoft.aad.msal4j.HttpHeaders`

Cause:
`java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.aad.msal4j.HttpHeaders`

The flow of code is:
```
		final ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
				.clientId(m365_clientId)
				.clientSecret(m365_clientSecret)
				.tenantId(m365_tenantId).build();

		final List<String> scopes = new ArrayList<String>();
		scopes.add("https://graph.microsoft.com/.default");

		final TokenCredentialAuthProvider tokenCredentialAuthProvider = new TokenCredentialAuthProvider(scopes,
				clientSecretCredential);

		graphClient = GraphServiceClient.builder()
				.authenticationProvider(tokenCredentialAuthProvider)
				.buildClient();
		
		List<Option> requestOptions = new LinkedList<Option>();
        requestOptions.add(new QueryOption("search", m365_sharepoint_sitename));
        **SiteCollectionPage sites = graphClient.sites().buildRequest(requestOptions).get();**
```
And the last line produces the error.

The funny thing is: Exactly the same code work in a Spring Boot application.
While the error occurs in a more complex Tomcat Webapplication (with Maven and Spring beans).
I even use the exact same version of the artifacts...

As this is the same code it should work in any JAVA environment. 

Somehow the HttpHeaders class can not be initialized. Can someone point me in the right direction why this is only happening in the Tomcat Framework?

**Comment by weidongxu-microsoft** [comment] 2023-04-26 12:28
Try to make sure the azure-core lib in runtime is latest.

**Comment by alzimmermsft** [comment] 2023-05-22 12:28
I'm going to close this as a duplicate of #34639, even though this issue is older the other has more information and links out.

**Closed by alzimmermsft** 2023-05-22 12:28 UTC
Labels: question, Client, customer-reported, Azure.Identity, needs-team-triage
