### ISSUE TITLE
[BUG]There is an error when creating vm using withLinuxGalleryImageVersion

### ISSUE THREAD

**Issue by 123Jun321** [Azure/azure-sdk-for-java#11912] opened 2020-06-09 03:10 UTC
**Describe the bug**
There is an error when creating vm using withLinuxGalleryImageVersion

***Exception or Stack Trace***
Exception in thread "main" com.microsoft.azure.CloudException: Parameter 'osProfile' is not allowed.: Parameter 'osProfile' is not allowed.
	at com.microsoft.azure.AzureClient.createExceptionFromResponse(AzureClient.java:771)
	at com.microsoft.azure.AzureClient.access$100(AzureClient.java:33)
	at com.microsoft.azure.AzureClient$3.call(AzureClient.java:160)
	at com.microsoft.azure.AzureClient$3.call(AzureClient.java:157)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120)
	at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:81)
	at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:27)
	at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:39)
	at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:27)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153)
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:32)
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:22)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: retrofit2.Response.class
	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
	... 43 more

**To Reproduce**
when use withLinuxGalleryImageVersion（）function to create vm

***Code Snippet***
VirtualMachine placementGroup = azure.virtualMachines().define("guanjuntest060198").withRegion(Region.CHINA_NORTH)
				.withExistingResourceGroup("test0608").withNewPrimaryNetwork("10.0.0.0/28")
				.withPrimaryPrivateIPAddressDynamic().withoutPrimaryPublicIPAddress()
				.withProximityPlacementGroup(
						"***")
				.withLinuxGalleryImageVersion(
						"****")
				.withRootUsername("***")
				.withRootPassword("***")
				.withOSDiskStorageAccountType(StorageAccountTypes.STANDARD_SSD_LRS)
				.withSize(VirtualMachineSizeTypes.STANDARD_A1_V2)
				.withOSDiskName("test").withOSDiskSizeInGB(128)
				.create();

**Expected behavior**
create successfully

**Screenshots**

**Setup (please complete the following information):**
 - OS: win 10
 - IDE : Eclipse
 - Version of the Library used:
<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure</artifactId>
			<version>1.34.0</version>
		</dependency>

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by yungezz** [comment] 2020-06-10 06:23
hi @xccc-msft could you pls have a look? thanks

**Comment by xccc-msft** [comment] 2020-06-11 02:23
@123Jun321 Thanks for sharing the code snippet. I tried similar scenario with region of `US west` instead of `China north` as our testing environment cannot create a resource group via `China north` for now.

```java
        VirtualMachine virtualMachine = this.computeManager.virtualMachines().define("test")
                .withRegion(REGION)
                .withExistingResourceGroup(RG_NAME)
                .withNewPrimaryNetwork("10.0.0.0/28")
                .withPrimaryPrivateIPAddressDynamic()
                .withoutPrimaryPublicIPAddress()
                .withLinuxGalleryImageVersion(imageVersion.id())
                .withRootUsername("user")
                .withRootPassword("pwd")
                .withOSDiskStorageAccountType(StorageAccountTypes.STANDARD_SSD_LRS)
                .withSize(VirtualMachineSizeTypes.STANDARD_A1_V2)
                .withOSDiskName("test").withOSDiskSizeInGB(128)
                .create();
```

From my end, I cannot reproduce your issue. And also, it's weird that it returns error message of osProfile not allowed as the root user/password are part of os profile. I would add label of `Service Attention` so the service team could provide help on this issue. Thanks.

**Comment by axayjo** [comment] 2020-06-11 07:26
@123Jun321 Are you trying to create a VM using a specialized image version? If so, OSProfile (username, password, computer name) should not be passed.

**Comment by 123Jun321** [comment] 2020-06-12 09:36
Hi  axayjo,

Yes, we try to create a VM using a specialized image version, but when we use the withLinuxGalleryImageVersion method, you must use this withRootUsername later, if you don't, it will report an error. To learn more about this issue, I think you can try it in your local.

**Comment by axayjo** [comment] 2020-06-12 17:58
Thanks @123Jun321. @xccc-msft, can you take a look at this? Seems like an SDK issue. On the service end, we don't require users to pass OSProfile related information (username, password, computer name) if the VM is being created from a specialized image. You should be able to reproduce this if you use a specialized image.

**Comment by xccc-msft** [comment] 2020-06-14 23:32
@123Jun321 Thanks for sharing the details.
@axayjo Is this a new scenario or existing one? Do we have any doc with related service scenarios? We might need to make some changes on phases of VM interfaces.

**Comment by xccc-msft** [comment] 2020-06-15 06:30
@123Jun321 Please feel free to review the [PR](https://github.com/Azure/azure-libraries-for-java/pull/1220) with supporting specialized gallery image version and share your comments.
@axayjo It would be appreciated if you could advise similar scenarios which should not pass the OS profile besides the specialized image version.
Thanks.

**Comment by 123Jun321** [comment] 2020-06-15 06:59
@xccc-msft  ok thanks. I will focus on it

**Comment by Drewm3** [comment] 2020-06-18 18:42
Removing the ServcieAttention label because this is being fixed on the SDK side.

**Closed** 2020-06-22 03:55 UTC
Labels: Compute, Mgmt, customer-reported
