### ISSUE TITLE
[BUG] NIO Directory creation not working

### ISSUE THREAD

**Issue by pditommaso** [Azure/azure-sdk-for-java#18001] opened 2020-12-07 14:22 UTC
**Describe the bug**

Trying to create a directory using the NIO API results in the creation of a plain. 

***Exception or Stack Trace***

No error is reported. 

**To Reproduce**

```
Path dirPath = myFs.getPath("mydir");
Files.createDirectory(dirPath);
```

***Code Snippet***
The one above

**Expected behavior**

A directory folder is created, a file is created instead. 

**Screenshots**

<img width="1208" alt="Screenshot 2020-12-07 at 15 20 33" src="https://user-images.githubusercontent.com/816968/101362084-efdb1500-389f-11eb-974f-3d85fde660d0.png">

**Setup (please complete the following information):**
 - OS: MacOS
 - IDE : IntelliJ
 - Version of the Library used: `com.azure:azure-storage-blob-nio:12.0.0-beta.2` 

**Additional context**

None

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by gapra-msft** [comment] 2020-12-07 17:48
@rickle-msft Could you take a look at this?

**Comment by rickle-msft** [comment] 2020-12-08 00:35
Hey, @pditommaso! Thanks for posting this issue! I believe this is actually by design and is a result of the portal and NIO handling directories differently.

The portal only interprets a directory based on the path, so if you have blob foo/bar, it'll show "foo" as a directly and only show "bar" if you enter the directory. Because of this understanding of directories, you actually can't have an empty directory on the portal. If you delete the blob "foo/bar", it deletes the directory as well as the directory only existed as a part of the path of that blob. 

We wanted to have support for empty directories in NIO, and the way that Storage tooling generally does this is by putting a blob with the directory name and giving it a special piece of metadata. Basically that blob functions as the directory object This is different from what the portal does, so it will display the empty directory as a blob instead of a directory. And in fact if you put a blob underneath the directory, you should see that the portal will show two entries: one for the blob that NIO uses as its directory object and one that the portal displays as a folder because now another blob has that directory name as a prefix. 

So, if you look at the blob created by nio, you should be able to see some metadata on it that is `hdi_isfolder=true`, which means NIO successfully put a directory. If you don't see that metadata than it's a bug.

There's another explanation of some of this on the docs for create directory that tries to spell out some of this nuance, but unfortunately it's not very intuitive because of the way the service/portal work. Let me know if you have any questions about that.

**Comment by pditommaso** [comment] 2020-12-08 09:18
Hi Rick, I understand I was confused by the UI representation. I confirm the from API point of view it's OK and the metadata is OK. 

However, I'm experiencing another problem related to directories creation. I'll open a separate issue for it.

**Comment by rickle-msft** [comment] 2020-12-08 18:12
Great! I'll close this one and take a look at the new one.

**Closed by rickle-msft** 2020-12-08 18:12 UTC
Labels: Client, Storage, customer-reported, question
