### ISSUE TITLE
[BUG] ServiceBusReceiverClient hangs on receiveMessages()

### ISSUE THREAD

**Issue by Kyrychenkozaurus** [Azure/azure-sdk-for-java#38393] opened 2024-01-21 13:22 UTC
**Describe the bug**
We have a multithreaded application, set to process multiple queues, each having it's own dedicated thread. Each thread has it's own ServiceBusReceiverClient and deals with it's own queue independently. Occasionally, one random ReceiverClient stops processing and just hangs there. Thread dumps indicate that no process related to this thread pool is locked or stopped, all of them are either in a RUNNING or a WAITING state.
The core of the issue seems to be related to some kind of Reactor crash, which is processed independently in it's own thread by the library.

***Exception or Stack Trace***
```
reactor.core.publisher.Sinks$EmissionException: Spec. Rule 1.3 - onSubscribe, onNext, onError and onComplete signaled to a Subscriber MUST be signaled serially.
	at reactor.core.publisher.InternalManySink.emitComplete(InternalManySink.java:86)
	at com.azure.messaging.servicebus.SynchronousReceiveWork.complete(SynchronousReceiveWork.java:205)
	at com.azure.messaging.servicebus.SynchronousReceiveWork.complete(SynchronousReceiveWork.java:179)
	at com.azure.messaging.servicebus.SynchronousReceiveWork.lambda$start$3(SynchronousReceiveWork.java:120)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:64)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:100)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:91)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onNext(TracingSubscriber.java:64)
	at reactor.core.publisher.FluxSwitchMap$SwitchMapMain.drain(FluxSwitchMap.java:355)
	at reactor.core.publisher.FluxSwitchMap$SwitchMapMain.innerNext(FluxSwitchMap.java:413)
	at reactor.core.publisher.FluxSwitchMap$SwitchMapInner.onNext(FluxSwitchMap.java:512)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.lambda$onNext$1(TracingSubscriber.java:64)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:100)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.withActiveSpan(TracingSubscriber.java:91)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onNext(TracingSubscriber.java:64)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.propagateDelay(MonoDelay.java:271)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:286)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**To Reproduce**
Keep in mind that this is hard to reproduce in a single queue environment. It requires high load and even then we may wait for the next drop for at least 2-3 days.
1) Create a ServiceBusReceiverClient that reads from a single queue
2) Request messages in batch using receiveMessages() method with fixedDelay of 10 seconds
3) Wait for it to reproduce

***Code Snippet***
```
public ExtractedInstanceData extract() throws ServiceBusException {
        ExtractedInstanceData extractedData = new ExtractedInstanceData();
        if (receiverClient != null) {
            IterableStream<ServiceBusReceivedMessage> messagesStream = receiverClient.receiveMessages(REQUESTED_MESSAGES_AMOUNT, Duration.ofSeconds(90));
            messagesStream.forEach(receivedMessage -> {
                MyMetric metric = gson.fromJson(String.valueOf(receivedMessage.getBody()), MyMetric.class);
                metric.setCreated(metric.getCreated().withZoneSameInstant(ZoneOffset.UTC));
                extractedData.getMetrics().add(metric);
                log.info("Received metric with messageId: " + receivedMessage.getMessageId() + " and body: " + receivedMessage.getBody());
            });
        }
        return extractedData;
    }
```

**Expected behavior**
ServiceBusReceiverClient should work indefinitely or throw an exception in case something goes wrong and our app could rebuild a client in that case.

**Setup (please complete the following information):**
 - OS: Azure App Service
 - IDE: Intellij IDEA
 - Library/Libraries: com.azure:azure-messaging-servicebus:7.4.13; 
 - Java version: 8
 - App Server/Environment: Tomcat
 - Frameworks: Spring Boot 2.7.10

**Comment by joshfree** [comment] 2024-01-22 21:19
@anuchandy can you please follow up?

**Comment by anuchandy** [comment] 2024-01-23 16:33
Hello @Kyrychenkozaurus, could you confirm that – the receiver stops incidents are always accompanied by this stack trace? Is this a consistent pattern?

**Comment by Kiriche** [comment] 2024-01-23 18:01
Yes, I can confirm it. We've been fighting this issue for quite a while (at least 5 months) and we always find a reactor crash in a separate log, completely unrelated to a service that does ServiceBus processing. Apparently, the crash happens somewhere on the reactor level, while ReceiverClient just hangs, waiting for a response from a reactor (at least to my understanding).

We've suspected dependency issues, so we've used this BOM to ensure that all libraries use the correct version:
https://mvnrepository.com/artifact/com.azure/azure-sdk-bom/1.2.16

We've been monitoring this kind of behavior for months. The pattern is something along the lines:
1) Have 50 queues  (in our case it's something along the lines of 2200 messages per day)
2) Wait 2-7 days
3) It stops receiving messages. With no exception in the stacktrace or error/warning in the logger of service responsible for ServiceBus processing

The only thing that indicates that the stacktrace shown in my original post is related to the problem is the timestamp. It occurs in 100% cases of ServiceBusReceiverClient hanging and every time timestamps match to the milisecond with the last message received from ReceiverClient.

**Comment by anuchandy** [comment] 2024-01-24 23:27
@Kiriche, thank you for sharing the observation in detail. I’ll do analysis based on this. It seems the terminal signal event is lost (per the trace you shared) which results in Stream not completing.

**Comment by Kiriche** [comment] 2024-01-28 17:37
@anuchandy just noticed that I've made the last reply in this issue thread from a different account. Sorry about that, but me and the topic starter are the same person. :) Just to clear things out, so you don't have a wrong idea that there are multiple reports of the same issue

**Comment by anuchandy** [comment] 2024-01-29 22:58
@Kiriche, Thanks for the clarification, no worries I figured out that both ids are owned by you given the context.

I started looking into this, this requires some refactoring in the synchronous API side of the library. I’ll open a PR once re-factoring is complete.

**Comment by anuchandy** [comment] 2024-02-28 19:19
Hi @Kiriche, appreciate your patience. We've released 7.15.1 that resolves the concurrent signaling issue.  

Please refer to this documentation on how to upgrade to 7.15.1 and enable/opt-in to the new Synchronous Receive. https://learn.microsoft.com/en-us/azure/developer/java/sdk/troubleshooting-messaging-service-bus-overview#upgrade-to-715x


In your scenario, there are 50 separate continues receive streams sharing one IO-Thread, this may cause some of the receive streams to lag or slow down. A Service Bus Client builder instance has one IO-Thread, which will be shared by all the client instances created from that builder instance.  

So, one suggestion is – balance the load by using multiple builder instances, for example ~10 builder instances, and then limit the number of clients created from each builder instance to ~5.

**Comment by Kiriche** [comment] 2024-03-02 21:09
Thank you for your response, I'm pretty sure I'd missed that update if you didn't. We'll proceed with this update procedure ASAP. I'll come back to this thread or open another one with a link to this one if it somehow resurfaces.

**Comment by anuchandy** [comment] 2024-03-04 18:03
Sounds good @Kiriche, summarizing points to note when upgrading -

1.	Make sure new sync receive is Enabled (as explained in the [documentation](https://learn.microsoft.com/en-us/azure/developer/java/sdk/troubleshooting-messaging-service-bus-overview#upgrade-to-715x)), the setting to enable in this case is, "com.azure.messaging.servicebus.nonSession.syncReceive.v2".
2.	Check that no transitive dependencies are changing the required versions of “azure-messaging-service" and "azure-core-amqp". We can use "mvn dependency:tree" to verify that the versions are precisely “7.15.1” and “2.9.1”.
3.	Make sure that the same dependency versions are used when the application is running. A simple way to check this is to turn on VERBOSE log temporarily and see if you get logs from these two classes: "ReceiveLinkHandler2" and "WindowWork". These two classes are only loaded when you choose the new sync receive option.
4.	[Important] Also, as suggested in the previous [comment](https://github.com/Azure/azure-sdk-for-java/issues/38393#issuecomment-1969683384), think about distributing the receiver-client instances evenly among builder instances. In this case, there are ~110K messages handled across queues, and having only one IO-Thread may become a bottleneck, resulting in delays/freeze and timeouts randomly. A load balancing pattern is recommended to improve reliability.

**Comment by anuchandy** [comment] 2024-04-09 16:05
Hi @Kiriche , I hope you're doing well. I wanted to follow up on how 7.15.x is working for you with v2 sync receive opt-in and other suggestions we talked about before.

**Comment by anuchandy** [comment] 2024-04-18 15:32
Hello @Kiriche, thank you for getting back. No worries. If you run into issues once you upgrade, let me know. Given the originally reported problem is resolved, I’ll go ahead and close this.

**Closed by anuchandy** 2024-04-18 15:32 UTC
Labels: question, Service Bus, Client, customer-reported, needs-team-attention
