### ISSUE TITLE
[BUG] Possible ByteBuf Leak in Cosmos SDK.

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#13390] opened 2020-07-21 21:24 UTC
Opening this issue on the behalf of @tysonnorris:

An error like below:

```
[      ] [reactor-http-nio-1] ERROR io.netty.util.ResourceLeakDetector.reportTracedLeak(320) - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records:
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:349)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
	io.netty.handler.ssl.SslHandler.allocate(SslHandler.java:2134)
	io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1319)
	io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1231)
	io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1268)
	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.base/java.lang.Thread.run(Thread.java:834)
```
appearing with some of the tests that Tyson wrote to exercise cosmosdb sdk.

com.azure:azure-cosmos:4.0.1 with jdk 1.8 and jdk 11. 

Tyson is trying to narrow down a test case, but it happens intermittently, about 50% of the test runs. 

@tysonnorris do you have any more details/test/repo-steps you can provide? ( I added "need-author-feedback").

\\cc @kushagraThapar @moderakh @David-Noble-at-work (From Cosmos team).

**Comment by kushagraThapar** [comment] 2020-07-21 21:55
@anuchandy thanks for opening the issue - @tysonnorris can you please upgrade the SDK to 4.2.0 and still repro it ?

**Comment by tysonnorris** [comment] 2020-07-22 19:19
I am still able to reproduce with SDK 4.2.0, I am working on trimming down our test case that demonstrates the issue, but it has been complicated due to intermittent nature. I will update here ASAP when I have more details.

**Comment by kushagraThapar** [comment] 2020-07-22 20:29
@tysonnorris thanks for the information - if you can come up with more details, that would be great and we should be able to solve it.

**Comment by tysonnorris** [comment] 2020-07-29 19:13
I am still working on narrowing this down, but it seems like it is related to exception handling, where our sdk client code might ignore a CosmosException(with statusCode 404) during DELETE, then at some point in the future the LEAK error appears. Running a similar test that purposefully avoids the exception does not produce the LEAK error. 
With this in mind, I am still working towards producing a smaller sample test that produces the problem.
I have been most recently testing with the 4.2.0 version of SDK.

**Comment by kushagraThapar** [comment] 2020-07-29 19:23
@tysonnorris - we just (like a min ago) released v4.3.0 with very very important bug fixes (including error handling on SDK side) and one super awesome performance bug fix. Care to try that out ?

Here is the changelog : https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-cosmos/CHANGELOG.md#430-2020-07-29

**Comment by tysonnorris** [comment] 2020-07-29 20:27
Thanks @kushagraThapar - I still get the LEAK error with 4.3.0. I'm close to providing a sample, I think.

**Comment by kushagraThapar** [comment] 2020-07-29 21:02
Cool, that would be great @tysonnorris . Thank you so much!

**Comment by tysonnorris** [comment] 2020-07-30 17:09
One difference I'm sorting through - our application is using com.azure.cosmos.implementation.AsyncDocumentClient, vs com.azure.cosmos.CosmosAsyncClient. I haven't found any examples with newer SDK versions that are using AsyncDocumentClient - can you point me to an example? I am currently working through changing the azure-cosmos-java-getting-started sample to use AsyncDocumentClient to see if that is related to the LEAK errors we see.

**Comment by kushagraThapar** [comment] 2020-07-30 17:16
@tysonnorris , please don't use `AsyncDocumentClient` - as that is implementation details and not supposed to be used by customers at all. Though it might be useful to see the bug, but at the same time, if the bug is not reproducible through the use of `CosmosAsyncClient`, that could easily mean as an issue with your code, since you are using an implementation detail, and it might be possible that all the resources are not getting cleaned up properly because of interference of one internal class.

**Comment by tysonnorris** [comment] 2020-07-30 19:18
Thanks @kushagraThapar - I will try to port our existing usage of `AsyncDocumentClient` to `CosmosAsyncClient`

**Comment by kushagraThapar** [comment] 2020-07-30 19:49
@tysonnorris - please do so, it is highly highly recommended. Can't stress enough on not using the implementation classes :)

**Comment by tysonnorris** [comment] 2020-07-30 20:24
To do this i'm having trouble finding some way to implement some things that previous existed with our use of AsyncDocumentClient:
* query metrics - how can I retrieve query metrics from CosmosPagedFlux returned via CosmosAsyncContainer.queryItems? 
* aggregate queries - how can I run count queries? Is there an example of this?

**Comment by kushagraThapar** [comment] 2020-07-30 20:41
@tysonnorris  You can use `byPage()` API from `CosmosPagedFlux` to get query metrics : https://github.com/Azure-Samples/azure-cosmos-java-sql-api-samples/blob/master/src/main/java/com/azure/cosmos/examples/crudquickstart/async/SampleCRUDQuickstartAsync.java#L290

Example for count query - https://github.com/Azure-Samples/azure-cosmos-java-sql-api-samples/blob/master/src/main/java/com/azure/cosmos/examples/queries/sync/QueriesQuickstart.java#L139

Full set of examples : https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-java-sdk-samples

**Comment by tysonnorris** [comment] 2020-07-30 21:11
Thanks - that helps a lot!
Lastly, I'm not sure how to use CosmosAsyncClient to query the collection to return usage headers:
* x-ms-documentdb-collection-index-transformation-progress
* x-ms-resource-usage
* x-ms-resource-quota

**Comment by kushagraThapar** [comment] 2020-07-30 23:20
@tysonnorris - new V4 SDK is hierarchal. 
CosmosAsyncClient -> CosmosAsyncDatabase -> CosmosAsyncContainer . 

When you get `CosmosContainerResponse` -> call `getResponseHeaders` and get the above information. 

If you are using query to get all containers, you should get `FeedResponse` -> which also has same API -> `getResponseHeaders` and you can get the above information.

Remember calling `byPage()` API on CosmosPagedFlux to get the `FeedResponse`

Please close this issue if the issue is not reproducible any more. If you see it again, feel free to open it back up :)

**Comment by tysonnorris** [comment] 2020-07-31 16:43
@kushagraThapar thanks for your help!
I think it is OK to close this issue, but I cannot do it - @anuchandy can you close it?

**Comment by kushagraThapar** [comment] 2020-07-31 17:03
I will close it now. Thanks!

**Closed by kushagraThapar** 2020-07-31 17:03 UTC
Labels: Client, Cosmos, cosmos:v4-item, needs-author-feedback

**Comment by tysonnorris** [comment] 2020-08-03 23:37
Finally got a stripped down case to produce the LEAK errors; logged #13763

**Comment by kushagraThapar** [comment] 2020-08-04 02:25
@tysonnorris - thanks, will investigate that one.
