### ISSUE TITLE
[QUERY] Can not list VMs: "No ObjectCodec defined for parser, needed for deserialization"

### ISSUE THREAD

**Issue by snnn** [Azure/azure-sdk-for-java#21615] opened 2021-05-17 16:41 UTC
**Query/Question**
When I loop the VMs in a certain subscription, I got the following error:
```
May 17, 2021 9:36:46 AM com.azure.core.util.logging.ClientLogger performLogging
INFO: Azure Identity => getToken() result for scopes [https://management.core.windows.net//.default]: SUCCESS
Exception in thread "main" com.azure.core.exception.HttpResponseException: Deserialization Failed.
	at com.azure.core.implementation.serializer.HttpResponseBodyDecoder.lambda$decodeByteArray$1(HttpResponseBodyDecoder.java:114)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2397)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:110)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:134)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
	at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onNext(FluxDoOnEach.java:173)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:173)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:185)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:260)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:150)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:150)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
	at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:159)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:145)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:212)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:269)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:389)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:396)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:452)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:684)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:94)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1534)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1295)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1332)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1703)
		at com.azure.resourcemanager.compute.implementation.VirtualMachineImpl.refreshInstanceView(VirtualMachineImpl.java:412)
		at com.azure.resourcemanager.compute.implementation.VirtualMachineImpl.instanceView(VirtualMachineImpl.java:1658)
		at com.azure.resourcemanager.compute.implementation.VirtualMachineImpl.powerState(VirtualMachineImpl.java:1676)
		at changmingazuretool.CountVirtualMachines.main(CountVirtualMachines.java:41)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No ObjectCodec defined for parser, needed for deserialization (through reference chain: com.azure.resourcemanager.compute.fluent.models.VirtualMachineInner["properties.instanceView"]->com.azure.resourcemanager.compute.fluent.models.VirtualMachineInstanceViewInner["patchStatus"]->com.azure.resourcemanager.compute.models.VirtualMachinePatchStatus["availablePatchSummary"]->com.azure.resourcemanager.compute.models.AvailablePatchSummary["error"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:390)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:349)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1822)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.azure.core.util.serializer.FlatteningDeserializer.deserialize(FlatteningDeserializer.java:135)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3643)
	at com.azure.core.util.serializer.JacksonAdapter.deserialize(JacksonAdapter.java:283)
	at com.azure.core.implementation.serializer.HttpResponseBodyDecoder.deserializeBody(HttpResponseBodyDecoder.java:169)
	at com.azure.core.implementation.serializer.HttpResponseBodyDecoder.lambda$decodeByteArray$1(HttpResponseBodyDecoder.java:105)
	... 72 more
Caused by: java.lang.IllegalStateException: No ObjectCodec defined for parser, needed for deserialization
	at com.fasterxml.jackson.core.JsonParser._codec(JsonParser.java:2317)
	at com.fasterxml.jackson.core.JsonParser.readValueAsTree(JsonParser.java:2311)
	at com.azure.core.management.implementation.serializer.ManagementErrorDeserializer.deserialize(ManagementErrorDeserializer.java:68)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
	... 89 more
```
Probably I forgot to include some maven dependencies. Would you please let me which one I should add?

Source code:
```java
import com.azure.core.http.policy.HttpLogDetailLevel;
import com.azure.core.management.AzureEnvironment;
import com.azure.core.management.profile.AzureProfile;
import com.azure.identity.AzureCliCredential;
import com.azure.identity.AzureCliCredentialBuilder;
import com.azure.resourcemanager.AzureResourceManager;
import com.azure.resourcemanager.compute.models.OperatingSystemTypes;
import com.azure.resourcemanager.compute.models.PowerState;
import com.azure.resourcemanager.compute.models.VirtualMachine;

public class CountVirtualMachines {

	public static void main(String[] args) {
		AzureCliCredential cliCredential = new AzureCliCredentialBuilder().build();

		final AzureProfile profile = new AzureProfile(AzureEnvironment.AZURE);

		AzureResourceManager azureResourceManager = AzureResourceManager.configure()
				.withLogLevel(HttpLogDetailLevel.NONE).authenticate(cliCredential, profile)
				.withSubscription("xxxxxxxxxxxxxxx");

		int totalWindowsMachines = 0;
		int totalLinuxMachines = 0;
		int totalRunningWindowsMachines = 0;
		int totalRunningLinuxMachines = 0;
		int totalLinuxPasswordAuthenticationMachines = 0;
		for (VirtualMachine vm : azureResourceManager.virtualMachines().list()) {
			if (vm.osType().equals(OperatingSystemTypes.LINUX)) {
				++totalLinuxMachines;
				if(vm.osProfile() == null) {
					System.out.println(vm.name());
					continue;
				}
				if (!vm.osProfile().linuxConfiguration().disablePasswordAuthentication()) {
					++totalLinuxPasswordAuthenticationMachines;
				}
				if (vm.powerState().equals(PowerState.RUNNING))
					++totalRunningLinuxMachines;
			}

			if (vm.osType().equals(OperatingSystemTypes.WINDOWS)) {
				++totalWindowsMachines;
				if (vm.powerState().equals(PowerState.RUNNING))
					++totalRunningWindowsMachines;
			}

		}
		System.out.println("totalWindowsMachines:" + totalWindowsMachines + "\ntotalLinuxMachines:" + totalLinuxMachines
				+ "\ntotalRunningWindowsMachines:" + totalRunningWindowsMachines + "\ntotalRunningLinuxMachines:"
				+ totalRunningLinuxMachines + "\ntotalLinuxPasswordAuthenticationMachines:"
				+ totalLinuxPasswordAuthenticationMachines);

	}

}
```

***Why is this not a Bug or a feature Request?***

I don't know if I did something wrong. 

**Setup (please complete the following information if applicable):**
 - OS: [e.g. iOS] Windows 10
 - IDE : [e.g. IntelliJ] eclipse
 - Version of the Library used
 Maven dependencies:
```xml
<dependencies>
                <dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-jdk14</artifactId>
			<version>1.7.30</version>
		</dependency>
		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-core-http-netty</artifactId>
			<version>1.9.1</version>
		</dependency>
		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-identity</artifactId>
			<version>1.3.0</version>
		</dependency>
		<dependency>
			<groupId>com.azure.resourcemanager</groupId>
			<artifactId>azure-resourcemanager</artifactId>
			<version>2.4.0</version>
		</dependency>
</dependencies>
```

 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ x] Setup information Added

**Comment by joshfree** [comment] 2021-05-17 21:13
@yungezz could you take a look?

**Comment by yungezz** [comment] 2021-05-18 01:33
thanks @joshfree for routing. HI @weidongxu-microsoft  could you look at this issue, is this issue in core libs or specific to vm? thanks.

**Comment by weidongxu-microsoft** [comment] 2021-05-18 04:38
@snnn

Could you let us know your jackson-core version?

Also could you enable logging (use `HttpLogDetailLevel.BODY_AND_HEADERS`)
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/resourcemanager#enabling-logging
And show us the JSON content about `patchStatus`?

**Comment by snnn** [comment] 2021-05-18 15:58
Jackson 2.12.2.

![image](https://user-images.githubusercontent.com/856316/118684610-3883ec00-b7b7-11eb-9620-bead36db5115.png)

**Comment by snnn** [comment] 2021-05-18 16:15
```javascript
{
  "name": "anubis-pool-nv12v3",
  "id": "/subscriptions/xxxxxx/resourceGroups/PROJ-ANUBIS-PROD/providers/Microsoft.Compute/virtualMachines/anubis-pool-nv12v3",
  "type": "Microsoft.Compute/virtualMachines",
  "location": "southcentralus",
  "tags": {
    "platformsettings.host_environment.service.platform_optedin_for_rootcerts": "true",
    "azsecpack": "nonprod"
  },
  "identity": {
    "type": "SystemAssigned, UserAssigned",
    "principalId": "xxxxx",
    "tenantId": "xxxx",
    "userAssignedIdentities": {
      "/subscriptions/xxxxxx/resourceGroups/AzSecPackAutoConfigRG/providers/Microsoft.ManagedIdentity/userAssignedIdentities/AzSecPackAutoConfigUA-southcentralus": {
        "principalId": "xxxxxx",
        "clientId": "xxxxxx"
      }
    }
  },
  "properties": {
    "vmId": "xxxxxx",
    "hardwareProfile": {
      "vmSize": "Standard_NC12s_v3"
    },
    "storageProfile": {
      "imageReference": {
        "publisher": "Canonical",
        "offer": "UbuntuServer",
        "sku": "18.04-LTS",
        "version": "latest",
        "exactVersion": "18.04.202102240"
      },
      "osDisk": {
        "osType": "Linux",
        "name": "anubis-pool-nv12v3_OsDisk_1_8a40310f0fc74e81a8045435d4dd7ef0",
        "createOption": "FromImage",
        "caching": "ReadWrite",
        "managedDisk": {
          "storageAccountType": "Premium_LRS",
          "id": "/subscriptions/xxxxxx/resourceGroups/PROJ-ANUBIS-PROD/providers/Microsoft.Compute/disks/anubis-pool-nv12v3_OsDisk_1_8a40310f0fc74e81a8045435d4dd7ef0"
        },
        "diskSizeGB": 1024
      },
      "dataDisks": []
    },
    "osProfile": {
      "computerName": "anubis-pool-nv12v3",
      "adminUsername": "azureuser",
      "linuxConfiguration": {
        "disablePasswordAuthentication": true,
        "ssh": {
          "publicKeys": [
            {
              "path": "/home/azureuser/.ssh/authorized_keys",
              "keyData": "ssh-rsa xxxxx generated-by-azure\r\n"
            }
          ]
        },
        "provisionVMAgent": true,
        "patchSettings": {
          "patchMode": "ImageDefault"
        }
      },
      "secrets": [],
      "allowExtensionOperations": true,
      "requireGuestProvisionSignal": true
    },
    "networkProfile": {
      "networkInterfaces": [
        {
          "id": "/subscriptions/xxxxxx/resourceGroups/proj-anubis-prod/providers/Microsoft.Network/networkInterfaces/anubis-pool-nv12v328"
        }
      ]
    },
    "diagnosticsProfile": {
      "bootDiagnostics": {
        "enabled": true
      }
    },
    "provisioningState": "Succeeded",
    "instanceView": {
      "computerName": "anubis-pool-nv12v3",
      "osName": "ubuntu",
      "osVersion": "18.04",
      "vmAgent": {
        "vmAgentVersion": "2.2.54.2",
        "statuses": [
          {
            "code": "ProvisioningState/succeeded",
            "level": "Info",
            "displayStatus": "Ready",
            "message": "Guest Agent is running",
            "time": "2021-05-18T16:09:48+00:00"
          }
        ],
        "extensionHandlers": [
          {
            "type": "Microsoft.CPlat.Core.LinuxPatchExtension",
            "typeHandlerVersion": "1.6.17",
            "status": {
              "code": "ProvisioningState/succeeded",
              "level": "Info",
              "displayStatus": "Ready",
              "message": "Plugin enabled"
            }
          },
          {
            "type": "Microsoft.Azure.Monitor.AzureMonitorLinuxAgent",
            "typeHandlerVersion": "1.7.0",
            "status": {
              "code": "ProvisioningState/succeeded",
              "level": "Info",
              "displayStatus": "Ready",
              "message": "Plugin enabled"
            }
          },
          {
            "type": "Microsoft.Azure.Security.Monitoring.AzureSecurityLinuxAgent",
            "typeHandlerVersion": "2.14.64",
            "status": {
              "code": "ProvisioningState/succeeded",
              "level": "Info",
              "displayStatus": "Ready",
              "message": "Plugin enabled"
            }
          },
          {
            "type": "Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux",
            "typeHandlerVersion": "1.13.35",
            "status": {
              "code": "ProvisioningState/succeeded",
              "level": "Info",
              "displayStatus": "Ready",
              "message": "Plugin enabled"
            }
          }
        ]
      },
      "patchStatus": {
        "availablePatchSummary": {
          "assessmentActivityId": "2bc483cd-0644-46c0-8192-9a3b76cf60f5",
          "status": "Succeeded",
          "startTime": "2021-05-18T06:53:01.7545098+00:00",
          "lastModifiedTime": "2021-05-18T06:54:20+00:00",
          "criticalAndSecurityPatchCount": 28,
          "otherPatchCount": 20,
          "rebootPending": false,
          "error": {
            "details": [],
            "code": "0",
            "message": "0 error/s reported."
          }
        }
      },
      "disks": [
        {
          "name": "anubis-pool-nv12v3_OsDisk_1_8a40310f0fc74e81a8045435d4dd7ef0",
          "statuses": [
            {
              "code": "ProvisioningState/succeeded",
              "level": "Info",
              "displayStatus": "Provisioning succeeded",
              "time": "2021-04-28T11:10:57.7337606+00:00"
            }
          ]
        }
      ],
      "bootDiagnostics": {},
      "extensions": [
        {
          "name": "Microsoft.Azure.Monitor.AzureMonitorLinuxAgent",
          "type": "Microsoft.Azure.Monitor.AzureMonitorLinuxAgent",
          "typeHandlerVersion": "1.7.0",
          "statuses": [
            {
              "code": "ProvisioningState/succeeded",
              "level": "Info",
              "displayStatus": "Provisioning succeeded",
              "message": "Enable succeeded"
            }
          ]
        },
        {
          "name": "Microsoft.Azure.Security.Monitoring.AzureSecurityLinuxAgent",
          "type": "Microsoft.Azure.Security.Monitoring.AzureSecurityLinuxAgent",
          "typeHandlerVersion": "2.14.64",
          "statuses": [
            {
              "code": "ProvisioningState/succeeded",
              "level": "Info",
              "displayStatus": "Provisioning succeeded",
              "message": "Enable ASM succeeded"
            }
          ]
        },
        {
          "name": "OmsAgentForLinux",
          "type": "Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux",
          "typeHandlerVersion": "1.13.35",
          "statuses": [
            {
              "code": "ProvisioningState/succeeded",
              "level": "Info",
              "displayStatus": "Provisioning succeeded",
              "message": "Enable succeeded"
            }
          ]
        }
      ],
      "hyperVGeneration": "V1",
      "statuses": [
        {
          "code": "ProvisioningState/succeeded",
          "level": "Info",
          "displayStatus": "Provisioning succeeded",
          "time": "2021-05-18T06:53:35.7235474+00:00"
        },
        {
          "code": "PowerState/running",
          "level": "Info",
          "displayStatus": "VM running"
        }
      ]
    }
  },
  "zones": [
    "1"
  ],
  "resources": [
    {
      "name": "Microsoft.Azure.Monitor.AzureMonitorLinuxAgent",
      "id": "/subscriptions/xxxxxx/resourceGroups/PROJ-ANUBIS-PROD/providers/Microsoft.Compute/virtualMachines/anubis-pool-nv12v3/extensions/Microsoft.Azure.Monitor.AzureMonitorLinuxAgent",
      "type": "Microsoft.Compute/virtualMachines/extensions",
      "location": "southcentralus",
      "properties": {
        "autoUpgradeMinorVersion": true,
        "provisioningState": "Succeeded",
        "enableAutomaticUpgrade": true,
        "publisher": "Microsoft.Azure.Monitor",
        "type": "AzureMonitorLinuxAgent",
        "typeHandlerVersion": "1.0",
        "settings": {
          "GCS_AUTO_CONFIG": true
        }
      }
    },
    {
      "name": "Microsoft.Azure.Security.Monitoring.AzureSecurityLinuxAgent",
      "id": "/subscriptions/xxxxxx/resourceGroups/PROJ-ANUBIS-PROD/providers/Microsoft.Compute/virtualMachines/anubis-pool-nv12v3/extensions/Microsoft.Azure.Security.Monitoring.AzureSecurityLinuxAgent",
      "type": "Microsoft.Compute/virtualMachines/extensions",
      "location": "southcentralus",
      "properties": {
        "autoUpgradeMinorVersion": true,
        "provisioningState": "Succeeded",
        "enableAutomaticUpgrade": true,
        "publisher": "Microsoft.Azure.Security.Monitoring",
        "type": "AzureSecurityLinuxAgent",
        "typeHandlerVersion": "2.0",
        "settings": {
          "enableGenevaUpload": true
        }
      }
    },
    {
      "name": "OmsAgentForLinux",
      "id": "/subscriptions/xxxxxx/resourceGroups/PROJ-ANUBIS-PROD/providers/Microsoft.Compute/virtualMachines/anubis-pool-nv12v3/extensions/OmsAgentForLinux",
      "type": "Microsoft.Compute/virtualMachines/extensions",
      "location": "southcentralus",
      "properties": {
        "autoUpgradeMinorVersion": true,
        "provisioningState": "Succeeded",
        "publisher": "Microsoft.EnterpriseCloud.Monitoring",
        "type": "OmsAgentForLinux",
        "typeHandlerVersion": "1.0",
        "settings": {
          "workspaceId": "xxxxx"
        }
      }
    }
  ]
}
```

**Comment by weidongxu-microsoft** [comment] 2021-05-19 02:38
@snnn

Thanks for you log on the response. Root cause is a bug in azure-core-management. Fix here https://github.com/Azure/azure-sdk-for-java/pull/21647

As the fix is in dependent lib, SDK release with the fix might be at June.

**Comment by weidongxu-microsoft** [comment] 2021-05-21 08:37
The fix on `azure-core-management` is scheduled to be released on the first or second week of June, as version 1.2.3.

You can explicit include this version of `azure-core-management` in your pom after it is released. That should fix the problem.

Later when you upgrade `azure-resourcemanager` to 2.6.0 or above, the explicit dependency of `azure-core-management` can then be dropped as `azure-resourcemanager` would implicit depends on `azure-core-management` 1.2.3 or above.

PS: guide on possible dependency conflict on azure-core https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/resourcemanager#dependency-management

**Comment by snnn** [comment] 2021-05-21 17:49
Nice. Thank you!

**Comment by weidongxu-microsoft** [comment] 2021-06-08 02:22
@snnn

`azure-core-management` 1.3.0 is released.

**Closed by weidongxu-microsoft** 2021-06-08 02:22 UTC
Labels: Compute - VM, Mgmt, Mgmt - Track 2

**Comment by snnn** [comment] 2021-06-08 02:27
Thank you!

**Comment by weidongxu-microsoft** [comment] 2021-08-19 12:59
Short survey for us to hear you:
https://microsoft.qualtrics.com/jfe/form/SV_ehN0lIk2FKEBkwd?Q_CHL=ISSUES
