### ISSUE TITLE
[BUG] DatalakeGen2 file upload fails with "The uploaded data is not contiguous or the position query parameter value is not equal to the length of the file after appending the uploaded data"

### ISSUE THREAD

**Issue by jmakuc** [Azure/azure-sdk-for-java#30735] opened 2022-09-01 04:02 UTC
**Describe the bug**
When having multiple Java threads uploading files to a Datalake Container, the DatalakeFileClient fails randomly with the following message: "The uploaded data is not contiguous or the position query parameter value is not equal to the length of the file after appending the uploaded data".

***Exception or Stack Trace***
`Caused by: com.azure.storage.file.datalake.models.DataLakeStorageException: Status code 400, "{"error":{"code":"InvalidFlushPosition","message":"The uploaded data is not contiguous or the position query parameter value is not equal to the length of the file after appending the uploaded data.\nRequestId:30bca09d-b01f-0012-80b3-bd9382000000\nTime:2022-09-01T03:30:44.5431228Z"}}"
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at com.azure.core.http.rest.RestProxy.instantiateUnexpectedException(RestProxy.java:337)
        at com.azure.core.http.rest.RestProxy.lambda$ensureExpectedStatus$5(RestProxy.java:376)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
        at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:328)
        at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:345)
        at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2397)
        at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onSubscribe(MonoCacheTime.java:284)
        at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:191)
        at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
        at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:134)
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
        at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:130)
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:118)
        at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:220)
        at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:130)
        at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:184)
        at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
        at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:128)
        at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:259)
        at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:142)
        at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:389)
        at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:396)
        at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:452)
        at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:684)
        at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:94)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1534)
        at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1295)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1332)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        ... 1 more
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
                at reactor.core.publisher.Mono.block(Mono.java:1703)
                at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:128)
                at com.azure.storage.file.datalake.DataLakeFileClient.uploadFromFile(DataLakeFileClient.java:304)
                at com.azure.storage.file.datalake.DataLakeFileClient.uploadFromFile(DataLakeFileClient.java:275)
                at cl.bithaus.medium.datalake.writer.DatalakeAzureMessageWriter.write(DatalakeAzureMessageWriter.java:127)
                at cl.specto.hf.SpectoHistoricalWorker.write(SpectoHistoricalWorker.java:107)
                at cl.specto.hf.SpectoHistoricalWorker.work(SpectoHistoricalWorker.java:138)
                at cl.specto.hf.SpectoHistoricalWorker.run(SpectoHistoricalWorker.java:191)
                at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                ... 1 more
`

**To Reproduce**
A simple java class that creates a directory structure using FieSystemClient and then uploads a file from a local folder. When you parallelize the process with many threads (we used 48), you start getting these errors randomly. 

***Code Snippet***
`           DataLakeFileSystemClient fsClient = this.getFileSystemClient();

            if(logger.isDebugEnabled())
                logger.debug("Getting directory client for " + directory);

            DataLakeDirectoryClient dirClient = fsClient.createDirectory(directory, true);

            if(logger.isDebugEnabled())
                logger.debug("Getting file client for " + filename);

            DataLakeFileClient fileClient = dirClient.getFileClient(filename);

            (...)
            
            logger.info("Uploading " + filename + " to " + fileClient.getFilePath());
            fileClient.uploadFromFile(temp.toFile().getAbsolutePath(), true); // <-- FAILS HERE
`

**Expected behavior**
Should upload the file without errors. 
 

**Setup (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - IDE: command line
 - Library/Libraries: com.azure.azure-storage-file-datalake 12.5.0
 - Java version: 11
 - App Server/Environment: plain java on command line.
 - Frameworks: none

**Additional context**
Here are some other failed RequestI ids:
- e476a754-101f-0079-79b7-bd1476000000 
- dc855ce8-101f-0056-4fb7-bd19bd000000
- a15c6bb5-b01f-0084-68b7-bd9a53000000

Thanks!

**Comment by joshfree** [comment] 2022-09-02 21:09
@rickle-msft could you help take a look at the issue created by @jmakuc?  Thank you

**Comment by ibrahimrabab** [comment] 2022-09-06 20:04
Hi @jmakuc , thank you for opening this issue. In order to understand this problem better, I have a few questions.

1. Does this fail every time you make the upload calls or sometimes?
2. Are you trying to use multiple threads for a single file upload or using 48 threads for different file uploads?
3. Are the threads targeting the same file path or different file paths?

Thanks!
Rabab

**Comment by jmakuc** [comment] 2022-09-06 21:22
Hi @ibrahimrabab

1. It does happen every time we run the app. 
2. Every thread uploads a different file
3. Every thread uses a different final path, but they may share part of the structure. One thread may upload to /a/b/c/file1 an another to /a/b/c/file2. It is not fixed, the path is dynamic as well. 

Thanks!
J

**Comment by ibrahimrabab** [comment] 2022-09-07 21:34
@jmakuc would you be able to share a code sample of how you are enumerating the file paths, and how you're constructing your file clients? Being able to see how you're setting your clients up for uploads will help us with reproducing this on our end.

**Comment by jmakuc** [comment] 2022-09-08 01:46
Hi @ibrahimrabab 

A brief summary of what the app does:

- A single DatalakeWriter is initialized on startup. It initialize a single DataLakeFileSystemClient instance shared among all threads. 
- A worker thread takes a set of records, write them down into a temp file and then uploads it to Azure DL.
- The upload is done by creating a DataLakeDirectoryClient from the unique DataLakeFileSystemClient instance and then creating the file.
- The directory structure is such that about 6 files share the same directory, then it moves into another one.
- Filenames are unique.

The code that write the files is this.

`

    public String write(Collection<? extends MediumMessage> messages, DatalakeWriteControlEntry entry, DatalakeScope scope) throws DatalakeMessageWriterException {
        
        try {
            if(this.config == null)
                throw new DatalakeMessageWriterException("Writer not initialized. Call init first.");

            String directory = scope.getDatalakeDirectory(entry);
            
            // azure does no like initial nor trailing slashes
            if(directory.startsWith("/"))
                directory = directory.substring(1); 
            
            if(directory.endsWith("/"))
                directory = directory.substring(0, directory.length()-1);
            
            String filename = scope.getDatalakeFilename(entry);


            DataLakeFileSystemClient fsClient = this.getFileSystemClient();

            if(logger.isDebugEnabled())
                logger.debug("Getting directory client for " + directory);

            DataLakeDirectoryClient dirClient = fsClient.createDirectory(directory, true);

            if(logger.isDebugEnabled())
                logger.debug("Getting file client for " + filename);

            DataLakeFileClient fileClient = dirClient.getFileClient(filename);

            
            Path temp = this.getTempFile();
            logger.info("Writing temp file " + temp.toFile().getAbsolutePath());
            
            var bw = Files.newBufferedWriter(temp, StandardCharsets.UTF_8, StandardOpenOption.TRUNCATE_EXISTING);
            
            for(var m : messages) {
                
                bw.append(this.gson.toJson(m));
                bw.newLine();
            }
            
            bw.close();
            
            logger.info("Uploading " + filename + " to " + fileClient.getFilePath());
            fileClient.uploadFromFile(temp.toFile().getAbsolutePath(), true);

            temp.toFile().delete();

            if(entry.getTags() != null && entry.getTags().size() > 0)
                fileClient.setMetadata(entry.getTags());


            return "/" + this.config.getFilesystem() + "/" + directory + "/" + filename;

            
        }
        catch(Exception e) {
            
            throw new DatalakeMessageWriterException("Error uploading: " + e.getMessage(), e);
        }
 
    }


`

The exception is thrown in the `fileClient.uploadFromFile` line.

Here are some failed request Ids from a moment ago:

> RequestId: eeb3dd9a-101f-008d-5a23-c3df80000000  Time:2022-09-08T01:34:34.6243013Z
RequestId: 812be870-801f-0054-6b23-c3a705000000  Time:2022-09-08T01:34:37.2237009Z
RequestId: 6ffa8236-501f-0047-1223-c38309000000  Time:2022-09-08T01:34:44.1143977Z
RequestId: 22f2b7fa-c01f-009e-6423-c3fb8c000000  Time:2022-09-08T01:35:07.6988943Z
RequestId: 041259c9-401f-0080-1023-c31754000000  Time:2022-09-08T01:35:21.0914227Z
RequestId: c1a8273f-901f-0067-6b23-c3f8ae000000  Time:2022-09-08T01:35:27.2594482Z
RequestId: 69e035a8-f01f-0095-5423-c300e7000000  Time:2022-09-08T01:35:47.1254821Z
RequestId: eeb405cf-101f-008d-6c23-c3df80000000  Time:2022-09-08T01:36:05.5786637Z
RequestId: 22f2d352-c01f-009e-4823-c3fb8c000000  Time:2022-09-08T01:36:08.8219362Z
RequestId: 812c282e-801f-0054-7323-c3a705000000  Time:2022-09-08T01:36:27.4261388Z
RequestId: 1988c24a-901f-0083-0323-c3f630000000  Time:2022-09-08T01:36:33.0263327Z
RequestId: 7119107d-201f-004d-3f23-c327be000000  Time:2022-09-08T01:36:47.1969668Z
RequestId: 041276db-401f-0080-5e23-c31754000000  Time:2022-09-08T01:37:10.5186835Z
RequestId: c158e475-101f-0046-2723-c3dcd5000000  Time:2022-09-08T01:37:28.7731401Z
RequestId: a76e2721-a01f-0053-6523-c3cb66000000  Time:2022-09-08T01:37:53.0794049Z
RequestId: 7dd1c413-601f-003e-0723-c37f2d000000  Time:2022-09-08T01:38:34.2932314Z
RequestId: 71193b22-201f-004d-8023-c327be000000  Time:2022-09-08T01:38:39.2384973Z
RequestId: f75e027e-001f-0081-3f23-c34888000000  Time:2022-09-08T01:39:36.2337601Z
RequestId: 24ae6d7b-201f-0062-6723-c32a75000000  Time:2022-09-08T01:39:40.2853519Z

**Comment by ibrahimrabab** [comment] 2022-09-13 22:41
Hi @jmakuc 
Would you mind sharing what the size is of files that are you trying to upload?

**Comment by jmakuc** [comment] 2022-09-14 00:52
Hi Rabab

About half of the files are under 100k. The other half, almost all of them
are below 20Mb.



Jonathan Makuc

*Bit**haus Software*
# --------------------------------------------------------
0x77 bithaus.cl
0x74 +56994191736
Truth is out there

**Comment by ibrahimrabab** [comment] 2022-09-15 18:30
Hi Jonathan,

I have one suggestion. I noticed you call 
`DataLakeDirectoryClient dirClient = fsClient.createDirectory(directory, true);`

Everytime you try uploading a new file. This may potentially be causing an overwrite issue, since it is overwriting this folder every time you call this method. Can you try using 
`DataLakeDirectoryClient dirClient = fsClient.createDirectoryIfNotExists(directory);` 

This may help, it will avoid the overwrite. Please let me know if this works, if not we can look into other possible solutions.

Thanks! :)

**Comment by jmakuc** [comment] 2022-09-28 11:20
Hi Rabab

I'm sorry for the late reply, we had to update several dependencies to use
the new version, the one we were using did not have that method.

The good thing is that the change worked ok :) We did not have a single
error in about 4 million uploaded files.


Thank you very much

Jonathan Makuc

*Bit**haus Software*
# --------------------------------------------------------
0x77 bithaus.cl
0x74 +56994191736
Truth is out there

**Comment by ibrahimrabab** [comment] 2022-09-28 18:11
That is great to hear! Glad your issue is fixed :) I'll go ahead and close this issue now, but feel free to reach out if you have any more questions.

**Closed by ibrahimrabab** 2022-09-28 18:11 UTC
Labels: question, Data Lake, Storage, Client, customer-reported
